### ISSUE TITLE
AttributeError: 'exceptions.RuntimeError' object has no attribute 'split'

### ISSUE THREAD

**Issue by zemravi** [mozilla/DeepSpeech#1016]
Hi,
I am seeing an error while running DeepSpeech with the export directory set.

D Epochs - running: 0, done: 9
D Closing queues...
D Queues closed.
D Session closed.
D Done.
I Exporting the model...
2017-11-23 11:07:57.736719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
I Restored checkpoint at training epoch 4701
WARNING:tensorflow:From DeepSpeech.py:1687: generic_signature (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
No longer supported. Switch to SavedModel immediately.
WARNING:tensorflow:From DeepSpeech.py:1689: generic_signature (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
No longer supported. Switch to SavedModel immediately.
WARNING:tensorflow:From DeepSpeech.py:1689: init (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
No longer supported. Switch to SavedModel immediately.
WARNING:tensorflow:From DeepSpeech.py:1697: export (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
No longer supported. Switch to SavedModel immediately.
Traceback (most recent call last):
  File "DeepSpeech.py", line 1769, in <module>
    tf.app.run()
  File "/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1763, in main
    export()
  File "DeepSpeech.py", line 1719, in export
    log_error(sys.exc_info()[1])
  File "DeepSpeech.py", line 336, in log_error
    prefix_print('E ', message)
  File "DeepSpeech.py", line 316, in prefix_print
    print(prefix + ('\n' + prefix).join(message.split('\n')))
AttributeError: 'exceptions.RuntimeError' object has no attribute 'split'

Any idea what is causing it? 
Thanks
ravi

**Comment by kdavis-mozilla** [comment]
What arguments did you pass to `DeepSpeech.py`?

**Comment by zemravi** [comment]
Ok.. It went away. Looks like it was caused because there was an earlier model stored in the exports folder, but i did not set the remove_export True. I removed the earlier exported model from the directory, and the error went away.

**Comment by zemravi** [comment]
Looks like that is the reason.. if version number is not changed, and remove attribute is not set, it throws an error.
Maybe this could be dealt with by setting exported model version number automatically if remove_export is not set to True? 
Thanks a lot

**Comment by nobuf** [comment]
```
E Overwriting exports can cause corruption and are not allowed. Duplicate export dir: models/00000001
```

Perhaps there should be `if FLAGS.remove_export and FLAGS.remove_export dir is NOT empty` check and stop the program earlier, maybe after `initialize_globals()`?

As @zemravi suggests, supporting `--export_version=auto` and incrementing the number automatically would be nice.
