### ISSUE TITLE
Error compiling Tensorflow and Deepspeech

### ISSUE THREAD

**Issue by manuliner** [mozilla/DeepSpeech#1017]
Hello,

i followed your guide to install DeepSpeech, but when it comes to compiling bazel throws some errors. Maybe you can help me on this :-)
 What I did so far:

- Building TensorFlow ( Master) from sources till ./configure 
- i used all default paths and N for all Y/N Questions
- linked native_client dir  with my deepSpeech rep

build with bazel:
```bazel build -c opt --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:ctc_decoder_with_kenlm //native_client:generate_trie ```

  Error:  
```
WARNING: The lower priority option '-c opt' does not override the previous value '-c opt'
ERROR: /home/deepspeech/tensorflow/native_client/BUILD:18:1: Traceback (most recent call last):
        File "/home/deepspeech/tensorflow/native_client/BUILD", line 18
                tf_library(name = "deepspeech_model", cpp_cla...", <5 more arguments>)
        File "/home/deepspeech/tensorflow/tensorflow/compiler/aot/tfcompile.bzl", line 136, in tf_library
                " ".join([(("'" + arg.replace("'", "'\\''... [])])
        File "/home/deepspeech/tensorflow/tensorflow/compiler/aot/tfcompile.bzl", line 136, in " ".join
                [(("'" + arg.replace("'", "'\\''")) + "'") for arg in (tfcompile_flags or [])]
type 'select' is not iterable
ERROR: error loading package 'native_client': Package 'native_client' contains errors
INFO: Elapsed time: 0.900s
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: tensorflow

```

thank you very much

edit:

when i install deepspeech via python pip i get the message ``` TensorFlow library was compiled to use FMA instruction``` and nothing happens

**Comment by lissyx** [comment]
You need to use https://github.com/mozilla/tensorflow to build.

**Comment by manuliner** [comment]
thank you very much for your fast response

Do you have any suggestions for this error?
 ```

WARNING: The lower priority option '-c opt' does not override the previous value '-c opt'
ERROR: /home/deepspeech/.cache/bazel/_bazel_deepspeech/36222e0779483291035596b9a7374318/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 1.763s
FAILED: Build did NOT complete successfully (0 packages loaded)

```

**Comment by lissyx** [comment]
@manuliner Please make sure you wiped everything and you are using bazel 0.5.4. Also, please move that kind of discussion to discourse https://discourse.mozilla.org/c/deep-speech, github issues are really for bugs :)

**Comment by codehag** [comment]
Can we add this to the documentation? I also ran into this issue, the docs just say to install tensor flow

**Comment by manuliner** [comment]
i did, but i can't remeber as i didn't wrote it down somewhere as i had some other issues while training the deepspeech with the mozilla corpus which i couldn't solve. So i moved on to an different solution.

i remember indeed that it i didn't use the right tensorlflow version

> 
> 
> You need to use https://github.com/mozilla/tensorflow to build.

**Comment by TTTJJJWWW** [comment]
@manuliner  thank you very much for your response, but you mean "ERROR: error loading package 'native_client': Package 'native_client' contains errors" can be fixed by changing tensorlflow version?

**Comment by manuliner** [comment]
i am not sure. it is the information which sticked in my brain from installing deepspeech

its not about the right version, it is more about the right repo (https://github.com/mozilla/tensorflow  != official tensorflow)

**Comment by TTTJJJWWW** [comment]
@manuliner Oh,i see. so i need remove official tensorflow and rebuild it from "https://github.com/mozilla/tensorflow"? Or just download source code from "https://github.com/mozilla/tensorflow" and use "bazel build ..." to build deepspeech?
I am a newcomer and thanks for your help again!

**Comment by lissyx** [comment]
> @manuliner Oh,i see. so i need remove official tensorflow and rebuild it from "https://github.com/mozilla/tensorflow"? Or just download source code from "https://github.com/mozilla/tensorflow" and use "bazel build ..." to build deepspeech?
> I am a newcomer and thanks for your help again!

Being a newcomer is no excuse for not reading the documentations and not reading the replies we sent you: https://github.com/mozilla/DeepSpeech/issues/1805

**Comment by TTTJJJWWW** [comment]
@lissyx thanks , i get your replies just now, i will try it again.
