### ISSUE TITLE
Error when trying to build native_client..

### ISSUE THREAD

**Issue by anandjeyahar** [mozilla/DeepSpeech#1024]
Hi I am trying to build native client following the README.md page. 
I am using Debian 9, Anaconda 3, python 3.6 and bazel 0.7.

Here's the error:
>[anand:~/sources/mozilla_tf] [deepspeech] master* 1 ± bazel build  --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:ctc_decoder_with_kenlm //native_client:generate_trie --incompatible_disallow_set_constructor=false
ERROR: /home/anand/sources/mozilla_tf/tensorflow/core/BUILD:1453:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /home/anand/sources/mozilla_tf/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'
ERROR: /home/anand/sources/mozilla_tf/tensorflow/core/BUILD:1453:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /home/anand/sources/mozilla_tf/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'
ERROR: /home/anand/sources/mozilla_tf/tensorflow/core/BUILD:1453:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /home/anand/sources/mozilla_tf/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'
ERROR: Analysis of target '//native_client:ctc_decoder_with_kenlm' failed; build aborted: Loading failed
INFO: Elapsed time: 20.621s
FAILED: Build did NOT complete successfully (30 packages loaded)
    currently loading: tensorflow/core/kernels_

**Comment by reuben** [comment]
Try downgrading to Bazel 0.5.4, AFAIK TensorFlow doesn't test with newer versions of Bazel.

**Comment by lissyx** [comment]
Closing because nothing actionable so far.
