### ISSUE TITLE
Change the order of positional arguments

### ISSUE THREAD

**Issue by mbebenita** [mozilla/DeepSpeech#1032]
Some feedback I got from testers was that not having the audio clip as the last argument was strange. Is there a reason for it currently being the second argument?

**Comment by reuben** [comment]
>Is there a reason for it currently being the second argument?

Only that it was the last argument before we added more arguments :P

**Comment by divyanshj16** [comment]
I want to take it up. Can somebody guide me through?

**Comment by lissyx** [comment]
@divyanshj16 You're welcome to ask any question so we can help you take that bug :-). It's about updating C++ (`client.cc`), Python (`client.py`) and NodeJS (`client.js`) to change the order of the arguments.
