### ISSUE TITLE
Avoid useless TaskCluster runs

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#1035]
We need a way to inhibit running builds, e.g., for PR or merges about doc only.

**Comment by lissyx** [comment]
Current proposal: augment tc-decision.py with handling to:
 - shallow git clone the PR/merge
 - check latest git message for a keyword

Keyword could be: "NOBUILD". Debate is open.

**Comment by tilmankamp** [comment]
I'd prefer doing this on base of a PR-comment/title and not a commit message.
Another thing: What about having separate scripts for PR and merge? The "PR" one would be a simple one-platform check, while the "merge" version builds and tests everything on every platform.

**Comment by lissyx** [comment]
So we move to something similar to Signoff information in Git history?
Like "X-DeepSpeech: NOBUILD" in the (end of) the commit (also valid for merge) message ?
