### ISSUE TITLE
Distributed training in a cluster 

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#1045]
In the distributed setup, are the queues local or shared by all the workers in the cluster?

I am trying to run the code on cloudML and the Worker seems to shut down while the master or chief worker runs without any interruption. So I wanted to check if each worker is independently creating queues and iterating through the whole data or if the data is passed between the chief and non-chief workers.

**Comment by kdavis-mozilla** [comment]
Hi @pdcoded 

As this is not concerning a bug with the code base, I wonder if you could move this discussion over to the [Deep Speech Discourse Forums](https://github.com/mozilla/deepspeech#contactgetting-help) as suggested in the [README](https://github.com/mozilla/deepspeech#contactgetting-help).

Thanks again you taking such a hands on interest in our code!
