### ISSUE TITLE
Wers compute diff from kaldi

### ISSUE THREAD

**Issue by zh794390558** [mozilla/DeepSpeech#1046]
https://github.com/mozilla/DeepSpeech/blob/cc16fd4cf519fb7ab1352888dc9b6430713c6bdb/util/text.py#L99

Why the wers compute method is different from kaldi's method? Which one is correct?

**Comment by tilmankamp** [comment]
`wers` just computes a WER mean. The actual implementation are the `wer` and `levenshtein` functions in the same file.

**Comment by zh794390558** [comment]
@tilmankamp I mean the WER mean is error when use to test test dataset WERs.

**Comment by tilmankamp** [comment]
@zh794390558 Thanks for bringing this up - could you point me to the equivalent code in Kaldi?

**Comment by zh794390558** [comment]
@tilmankamp
This is Kaldi's implemention:
 https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/bin/compute-wer.cc#L104

**Comment by tilmankamp** [comment]
I think I got your point: We (half intentionally) compute it as a factor and not as a percentage value. So our 0.06 is the same as 6%. Is it that what you mean?

**Comment by tilmankamp** [comment]
@zh794390558 Got your point now. So far we interpret and compute our WER as "the mean WER of a sentence" and therefore don't weigh long sentences higher than short ones. Kaldi's solution seems to be more precise here, albeit I am not sure if this is "the official way to go". Do you have any sources regarding this (like a paper)? I'd like to see the alternative computation in action. How about a PR? There could also be a command line option for this alternative computation.

**Comment by kdavis-mozilla** [comment]
It's a rate. So longer and  shorter sentences shouldn't be weighted differently.

The length of longer and shorter sentences is accounted for in the denominator of their respective rates.

**Comment by zh794390558** [comment]
@tilmankamp See https://github.com/PaddlePaddle/DeepSpeech/issues/45

**Comment by kdavis-mozilla** [comment]
The Kaldi way of doing things will give much better WER.

For example, say the test set has 100 words across all sentences and we get 10 wrong.

If each of the 10 words are in separate sentences and the final 90 words are in a single sentence, then the WER according to Kaldi is
```
10 / 100 = 0.1
```
According to our way of computing it is
```
(1+1+1+1+1+1+1+1+1+1+0) / 11 = 0.9090...
```
Question is which one is "right"?

In practice, I'd guess ours is a more user focused measure of WER: You speak to the system it gets WER `A` on the phrase, your do it again it gets WER `B` on the phrase... the average across `N` phrases is
```
(A+B+C...)/N
```
This is what a user would see as the WER, some average of the WER across all phrases. Generically a user wouldn't count all their words.

However, formally the Kaldi calculation looks to be correct.

So our real WER is likely much better than our reported WER.

**Comment by reuben** [comment]
#1130 was a partial fix (we're still averaging WERs, just over batches instead of samples), so reopening.

**Comment by samgd** [comment]
^ From my findings posted on irc to reuben: 

The WER is of each job is [averaged over](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L1014):

```python
                for i in range(num_jobs):
                    job = jobs.pop(0)
                    ...
                    if self.report:
                        agg_wer += job.wer

                ...

                if self.report:
                    self.wer = agg_wer / num_jobs
```

and by default the number of jobs [defaults to the total number of batches](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L1181) when an [epoch is created](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L1274):

```python
            # Total number of train/dev/test jobs covering their respective whole sets (one epoch)
            self._num_jobs_train = max(1, model_feeder.train.total_batches // batches_per_job)
            self._num_jobs_dev   = max(1, model_feeder.dev.total_batches   // batches_per_job)
            self._num_jobs_test  = max(1, model_feeder.test.total_batches  // batches_per_job)
```

```python
            self._epochs_running.append(Epoch(self._epoch, self._num_jobs_test, set_name='test', report=True))
```
