### ISSUE TITLE
Window fuction for MFCC in audio.py

### ISSUE THREAD

**Issue by StevenLOL** [mozilla/DeepSpeech#1047]
Hi, just want to confirm that there is no [window function](https://dsp.stackexchange.com/questions/25992/what-is-the-advantage-of-applying-a-hamming-window-for-mfcc-calculations) used in MFCC computation in audio.py.

Should I file a feature request ?

**Comment by kdavis-mozilla** [comment]
As far as I can see the original research paper [1412.5567](https://arxiv.org/abs/1412.5567) didn't use a Hamming window, though it might have improved their performance. Hence, we didn't use such a window. 

However, before merging a Hamming window PR, I think we'd have to do some testing on the PR to see how it affected performance. (I'd suspect it would improve things.) 

That said a PR or feature request would be welcome!

**Comment by bjtommychen** [comment]
in release 0.2.0, window function missed in audiofile_to_input_vector(), which make the output shape is wrong.  I have to add the code from previous version, in order to make DeepSpeech.py work. would you check this ?

**Comment by reuben** [comment]
We ended up fixing this in #1773 / #1744.
