### ISSUE TITLE
Tensorflow problem

### ISSUE THREAD

**Issue by pantrombka** [mozilla/DeepSpeech#1050]
I have a problem during run deepspeech, after pip install deepspeech

tensorflow/core/platform/cpu_feature_guard.cc:35 The TensorFlow library was compiled to use AVXZ instructions, but these aren't available on your machine.

Ubuntu 16.04.3 LTS
Python 2.7.12
gcc 5.4.0

**Comment by lissyx** [comment]
This is already reported as #1023, there is no easy solution for the time being.
