### ISSUE TITLE
'pip install deepspeech' fails to find valid deepspeech wheel if Mac OSX 10.11 is used and not 10.12

### ISSUE THREAD

**Issue by JustinGOSSES** [mozilla/DeepSpeech#1055]
'pip install deepspeech' fails to find valid deepspeech wheel if Mac OSX 10.11 is used and not 10.12

*This problem was debugged/identified in the discourse forum here:*
https://discourse.mozilla.org/t/pip-install-deepspeech-doesnt-find-a-valid-deepspeech-when-mac-osx-10-11-is-used-and-not-mac-osx-10-12/22788/13

*I documented how I got around the bug here:*
https://github.com/JustinGOSSES/DeepSpeech/blob/master/DeepSpeechInstallationForMacOSX10.11_20171201.md

Ideally, more wheels for Mac OSX would be provided such that 10.11 would work with a simple
`pip install deepspeech`
or, less ideally, the readme.md would be modified to let people know only one version of Mac OS was supported and one way around this was to manually change the pypi wheel's filename and follow instructions like these: https://github.com/JustinGOSSES/DeepSpeech/blob/master/DeepSpeechInstallationForMacOSX10.11_20171201.md

**Comment by lissyx** [comment]
Looks like we could set MACOSX_DEPLOYMENT_TARGET to control this behavior.

**Comment by lissyx** [comment]
@JustinGOSSES Would you mind testing binaries out of https://tools.taskcluster.net/groups/L-EaivWeQji0yt-5D6Ab-g/tasks/du_EuF5rRd-eIvNW8CvGKQ/runs/0/artifacts ?

**Comment by JustinGOSSES** [comment]
@lissyx I was able to get the 10.10 binaries working on my 10.11 mac. I used the installation methods I detailed above.
