### ISSUE TITLE
Speech Recognition Result Not in Correct English

### ISSUE THREAD

**Issue by loretoparisi** [mozilla/DeepSpeech#1056]
This is my speech recognition result.

```
ummm the  he  hh wede a rad an a janen dowar with tat e li o e e grownd every in thir wivennding and thed af teang ad than radyo tahowon an then  taninnionin miommm e e tell wold o er ham and lun li and a lot that non mesing non   up with the new day y bere with the od and nothin cin we bon lo n onow mno h  shon e an om un you do' know a e needs and teder had on a te n yo yhe pi in la e id you loo it mewe don't  ater day when you r uneronnm mom ready a pay any mon te e then i nhe tha ha one  like ahhh e de te rad en and drid and to wot but you know tad an rad is sting and  you in ma lie and he street a gordn la il maket ti sade i then a  nhe ma man a ta o knowno hen like the thinn on on batninnd you dol know a id't ben the nee a hade louni nd lo it you ae an you et in he we known mi be tate day when you're undher man in ted m a i my t nd liy tan a lonen iv i ihe ha d one moon like gata  m muh
```

Assumed that the input audio is not a clean voice, why it is not in correct english (I mean words tokens) or just partial english words? My example audio file (english male voice) is [here](https://github.com/loretoparisi/audionamix.js/blob/master/examples/sample.wav). I have used the node.js client like:

```
node client.js /models/output_graph.pb /examples/sample.wav /models/alphabet.txt
```

while using the language model binary file and the language model trie file like:

```
node client.js /models/output_graph.pb /examples/sample.wav /models/alphabet.txt /models/lm.binary /models/trie
```

I get

```
ummmthehehhhwedesaradandajanendowarwithtateliotedgrowndeveryinthirwivenndingandthedafteangadtanradyotahowonanthentaninnioninmiommheetellwoldoter ewdayyberewiththeodandnothincinwibolononowmnomashoneanomunmyoudo'knowateneedsandtederhadonatenyoyhepiinlaeid you look it mewedon'tmaterdaywhentyouruneronnmomreadyapayanymonteethenidnhethahaonelikeahederaenanddridandtowot treat a gordnlailmakettisadethedainhemamanatao ike the thingnononbatninndyoudol 
```

**Comment by joseph-zhong** [comment]
I also get strange results using my own sample `wav` files, but good results from the example audio files

**Comment by reuben** [comment]
The audio is a 4m27s long, 8 kHz, and a song, while the model was trained on sentences of a few seconds. There's very little chance that you'll get anything useful out of it. We should document better the type of audio that the model is meant to transcribe.

You could try applying noise reduction, find a 16 kHz version of that audio, and use a VAD tool to split it into sentence long chunks. Then you'll at least have a chance of getting something useful out of the model.

I'm closing this for now as the use case is quite extremely out of our scope.

**Comment by reuben** [comment]
Here's some useful links:

https://discourse.mozilla.org/t/longer-audio-files-with-deep-speech/22784/2
https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830
https://people.xiph.org/~jm/demo/rnnoise/

**Comment by loretoparisi** [comment]
@reuben ok thank you I will try to split the audio by VAD after some pre-processing (noise, source separation etc.) theorically speaking, having a trained model of noisy audio (music or anything else) could it be possibile? The rnnnoise can help on this? It would be interesting to train a new model for that, since source separation can be applied in a very specific range of frequencies when dealing with music bbut the result is not guarantee im all conditions.

**Comment by loretoparisi** [comment]
@reuben any hint about training with noisy audio samples?
