### ISSUE TITLE
Switchboard and TED dataset result

### ISSUE THREAD

**Issue by anupbera** [mozilla/DeepSpeech#1058]
Hi,
Anyone tell the WER of switchboard when train only on switchboard dataset. Also WER of TED when training on TED dataset. Actually I wanted to know how the Deepspeech perform when train on small dataset (around 200hrs).

**Comment by kdavis-mozilla** [comment]
@anupbera Though interesting, as this is not a bug related to the current code base, I ask that you migrate this discussion over to the Deep Speech [Discourse  Forums](https://discourse.mozilla.org/c/deep-speech) as recommended in the [README](DeepSpeech).
