### ISSUE TITLE
Modify the clients to support longer audio clips

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#1064]
On possible solution would be to clips long audio, over 5 sec say, using VAD, then feed each 5 second clip to the network.

However, there may be other better solutions that work near term until streaming is introduced.

**Comment by lparam** [comment]
@kdavis-mozilla Do you have any plans for streaming like kaldi's online decode?

**Comment by zh794390558** [comment]
@kdavis-mozilla Does reference clipped?

**Comment by kdavis-mozilla** [comment]
@lparam Longer term we plan to allow for streaming

**Comment by kdavis-mozilla** [comment]
@zh794390558 I'm note sure I know what you mean by "Does reference clipped?"

**Comment by lissyx** [comment]
It might be easy to reuse some of what I did for AOT to perform that: https://github.com/mozilla/DeepSpeech/blob/cbc868346bd0a0c0e9745a978f5818364a33084c/native_client/deepspeech.cc#L225-L245

**Comment by reuben** [comment]
5-10s might be overly aggressive. Here's someone using our released model on a 10 minutes long audio file and getting good results: http://www.phpied.com/taking-mozillas-deepspeech-for-a-spin/

**Comment by sanjayraojjn** [comment]
Is the trained model provided on deepspeech, is optimized for transcription of larger clips ? say 5-10 minutes.
I feed a 15 minute clip and on CPU it hung like never ending process.

**Comment by kdavis-mozilla** [comment]
@sanjayraojjn It is not optimized for transcription of larger clips, 5-10 minutes. 

If you want to transcribe longer clips, use VAD, e.g. [webrtcvad](https://pypi.python.org/pypi/webrtcvad/2.0.10), then feed each clip to the network.

**Comment by reuben** [comment]
Streaming helps quite a bit here, but ideally there should be some client support to improve the experience, detecting silence and finishing/restarting the streaming stream.

**Comment by bhargav-ak** [comment]
@sanjayraojjn @reuben I've a very crude command line and GUI python implementation that uses @kdavis-mozilla suggestions. I could clean it up and commit it here or my github page, whichever is better/easier.

**Comment by lissyx** [comment]
Just open a PR that's the best :-)

**Comment by bhargav-ak** [comment]
@lissyx Done :)

**Comment by sanjayraojjn** [comment]
Thanks a lot for suggestion. Though it is very late for me.

Sent from Yahoo Mail on Android 
 
  On Wed, 20 Dec 2017 at 3:04 PM, Kelly Davis<notifications@github.com> wrote:   
@sanjayraojjn It is not optimized for transcription of larger clips, 5-10 minutes.

If you want to transcribe longer clips, use VAD, e.g. webrtcvad, then feed each clip to the network.

**Comment by kdavis-mozilla** [comment]
@lissyx seems reasonable
