### ISSUE TITLE
Offline voice recognition on iOS / Android

### ISSUE THREAD

**Issue by allenleein** [mozilla/DeepSpeech#1068]
Can DeepSpeech let me implement local, offline speech recognition on mobile?

**Comment by reuben** [comment]
Please take discussions to our [Discourse forums](https://github.com/mozilla/DeepSpeech/blob/master/README.md#contactgetting-help)

**Comment by anton6** [comment]
@allenleein have you opened a discussion for this on discourse forum? I can't seem to find your post. How far did you get with this? Thanks
