### ISSUE TITLE
use_warpctc conditional doesn't use tf.cond()

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#107]

**Comment by kdavis-mozilla** [comment]
@lissyx I don't think your current solution can work when the operator graph uses a `tf.cond()` correctly as the operator  graph contains both side sides of the conditional branch[http://stackoverflow.com/a/37064128/1297739] and thus can't work on machine that does not have our version of tensorflow installed.

**Comment by lissyx** [comment]
I don't understand what is the problem of not using tf.cond() at first

**Comment by kdavis-mozilla** [comment]
Going to close as invalid.

It is OK "as is" as the `use_warpctc` conditional is evaluated at operator graph creation time and the value of `use_warpctc` does not depend upon any graph results.
