### ISSUE TITLE
adding deepspeech to macos homebrew, and python package manager

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [mozilla/DeepSpeech#1075]
**i think we should consider to:**
- *add deepspeech to macos homebrew*
- *adding deepspeech to python pip package manager*

---

that makes the overall installation process easier for MacOS users, as well as other operative systems

**Comment by reuben** [comment]
DeepSpeech is already on PIP, which is easily available to macOS users.

**Comment by tiagomoraismorgado88** [comment]
cool. didn't know about it. thanks for pointing me out to that. looking forward

**Comment by vucuong12** [comment]
@reuben The latest version of deepspeech on PIP does not allow `-t` flag for benchmark mode. If I want to also include the benchmark mode, I have to get the deepspeech binary from native_client.tar.xz by running `python util/taskcluster.py --target /path/to/destination/folder` (it is not CUDA capable version)
However, that binary is not executable on MacOS.

> -bash: ./deepspeech: cannot execute binary file

I think we should
(1) Update the version on pip
and/or (2) Create a binary for MacOS

**Comment by reuben** [comment]
The Python and Node.JS packages have never supported `-t`, you've always needed the native binary for that. (PRs welcome)

As the README says, you need to pass the `--arch osx` parameter to get macOS binaries.

**Comment by tiagomoraismorgado88** [comment]
we should also include a sycl capable version

**Comment by tiagomoraismorgado88** [comment]
at least for linux, as compute cpp is already available and you seem to be able to install sycl in some linux distros straigtht from the default os package manager

**Comment by tiagomoraismorgado88** [comment]
i think that is the case within antergos. and maybe fedora, but please correct me if I am wrong

**Comment by lissyx** [comment]
@tiagomoraismorgado88 I already spent some time in the past trying to get SYCL builds and it was painful to setup. We also don't really have hardware to test that, so, for now it's on hold. There's preliminary support from https://github.com/doe300/VC4CL for OpenCL on RPi3, this might be the first target we focus on that.

**Comment by lissyx** [comment]
@tiagomoraismorgado88 
Status of SYCL/ComputeCpp does not seems to be that good, in fact:
 - As much as I can tell, with tensorflow 1.4, we need ComputeCpp 0.4.0 to build (0.5.0 fails)
 - It's unable to work on my NVIDIA card (GTX1080, Debian Sid, 384.98 Nvidia driver) because of lack of SPIR likely
 - It's unable to work on a Core i7 5th generation with HD Graphics 5500 (Debian testing) with ComputeCpp complaining about unsupported GPU
 - It's unable to work on my Ubuntu 17.10 laptop (same CPU as above) because OpenCL libs dependency chains pulls libmirclient which links some protobuf version, and thus collides with the one embedded in our tensorflow build

**Comment by tiagomoraismorgado88** [comment]
@lissyx 
<sub>**i understand. I would suggest, so, to add at least:**</sub>
- <sub>*support for OpenCL 2.0;*</sub>

---

<sub>**by the way:**</sub>
- <sub>*you hav some really nice machines at disposal (i wouldn't mind about being in the same situation)*</sub>

**Comment by lissyx** [comment]
@tiagomoraismorgado88 We are dependant on what TensorFlow supports. So no, we cannot add OpenCL like that.

**Comment by tiagomoraismorgado88** [comment]
i see your point

**Comment by tiagomoraismorgado88** [comment]
what about standard opencl? oh, i see. you have already a preliminary business for rpi3

**Comment by lissyx** [comment]
Please @tiagomoraismorgado88 avoid hijacking issues for discussion.
