### ISSUE TITLE
V100 optimization

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#1078]
I am training my model on 3500 hours of data on the new V100 aws machine. It takes around 12 hours per epoch with my hyperparameter configuration. But the GPUs are not sync used to 99% and at any instance, during training, I see a CPU usage of 20-25% and each GPU fluctuating between 10-40% . 

Is it some issue with the queuing mechanism ( Can it be optimized any further)?  How can I synchronously make the gpu usage to till 99%. Batch size is 16.

**Comment by kdavis-mozilla** [comment]
Hi @pdcoded on our system, using Titan X Pascal's, we can get 99% utilization. So I think this is a tuning question and not a bug in our code.

So, as this is a general question about optimizing the training process--setting queue size, thread count, batch size--could you please move the discussion to [discourse](https://discourse.mozilla.org/c/deep-speech). We'll try to address the issue there.

Thanks for using Deep Speech!
