### ISSUE TITLE
DeepSpeech on Windows

### ISSUE THREAD

**Issue by fotiDim** [mozilla/DeepSpeech#1081]
Windows is not supported apparently yet but there are many users including me that want to run DeepSpeech on Windows. I found a way to run it through WSL on Windows 10 and I wrote the guide here: https://fotidim.com/deepspeech-on-windows-wsl-287cb27557d4
Perhaps you should consider mentioning WSL support in the Readme.

**Comment by lissyx** [comment]
@fotiDim Thanks! You should definitively document that on Discourse, there is already someone asking for that, so there is definitively value in it. Regarding your error on RPi3, we have no CI coverage for it (yet), can you also open a discussion on Discourse ? I'd like to know more about your installation steps, your error really looks weird, and I'm not sure it is related to memory.

**Comment by lissyx** [comment]
https://discourse.mozilla.org/c/deep-speech

**Comment by lissyx** [comment]
To be clear, judging by your error, it's likely it's a broken build of Tensorflow. Since you don't give any details on how you did it, I suspect you built by hand and it is possible our documentation is broken. What you could try is our binaries: https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.arm/artifacts/public/native_client.tar.xz those should be working, and if not, we should fix it :).

**Comment by fotiDim** [comment]
Hey @lissyx. I hope you don't mind me simply pasting the link of my article in the corresponding "Windows" discussion.

Now regarding the Pi issue. In fact I did use the binary. I didn't compile Tensorflow myself. The discussion is here: https://discourse.mozilla.org/t/error-with-sample-model-on-raspbian-jessie/23125

I will try the binaries in the link you posted as well in case they make any difference.

**Comment by The-Gupta** [comment]
@kdavis-mozilla @fotiDim @lissyx Can DeepSpeech be installed on Windows normally like on Linux/Mac - ie, without a Linux Virtual Environment or Windows Subsystem for Linux?

**Comment by lissyx** [comment]
@The-Gupta As it has already been documented on https://discourse.mozilla.org/c/deep-speech no. Please use discourse instead of replying to old, closed issues.
