### ISSUE TITLE
Unable to build trie

### ISSUE THREAD

**Issue by riri-leelee** [mozilla/DeepSpeech#1083]
Using python 2.7, tensorflow version ('v1.4.0-rc1-11-g130a514', '1.4.0'). 
Working inside of a Ubuntu VM

I have built my own collection of audio files and alphabet. I made the lm.binary file. However, when I try to built the trie, it is throwing the following error...

./generate_trie ../models/alphabet.txt ../models/lm.binary ../models/vocab.txt trie
Invalid label A
Aborted (core dumped)

**Comment by reuben** [comment]
Make sure your vocabulary does not contain letters that are not in the alphabet file.

**Comment by riri-leelee** [comment]
Ah,  I found that the vocabulary could not contain upper case letter when the alphabet did not.

**Comment by LouisCauchy** [comment]
@riri-leelee Could you help me please, how did you create lm.binary?

**Comment by riri-leelee** [comment]
@LouisCauchy 

You need: 
a textfile containing each wav complete transcript per line (utf8 encoded). Call this textfile, **vocabulary.txt**
You will also need to install Kenlm tools for the LM build : http://kheafield.com/code/kenlm/estimation/

Clean the original textfile:
- open the alphabet.txt textfile,
- feed in your own alphabet,
- save it
- open the original textfile,
- with your best editor, clean the file : all its characters MUST be present in alphabet.txt remove any punctuation, but you can keep the apostroph, if present in alphabet, as a character.

1 - Creating arpa file for binary build :
`/bin/bin/./lmplz --text vocabulary.txt --arpa  words.arpa --o 2`
-o param (“order model to estimate”)
It seems that for small corpus (my case of 400 wav files), a value from 2-4 seems to be the best

2 - creating binary file :
`/bin/bin/./build_binary -T -s words.arpa  lm.binary`

These were the directions that I followed to create my lm.binary. For more help look at [https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830](url)

**Comment by phanlong95** [comment]
can you help me, create trie

**Comment by riri-leelee** [comment]
@phanlong95 

Adapt for the location of your own files: 
`/home/nvidia/tensorflow/bazel-bin/native_client/generate_trie /
/home/nvidia/DeepSpeech/data/alphabet.txt /
/home/nvidia/DeepSpeech/data/lm.binary /
/home/nvidia/DeepSpeech/data/vocabulary.txt /
/home/nvidia/DeepSpeech/data/trie`

Find out what alphabet.txt, lm.binary, and vocabulary.txt are in my previous comment on this post. The last path is where you want the trie to be placed.

**Comment by phanlong95** [comment]
when i run ./generate_trie data/alphabet.txt data/lm.binary data/vocabulary.txt data/trie
error: Invalid label 
Aborted (core dumped)

i run again: bash: ./generate_trie: cannot execute binary file: Exec format error

**Comment by spate141** [comment]
I'm having similar issue with building `trie` model with  `generate_trie ` script! Only issue I'm having is; building process just get killed after using almost 40GB of memory! My binary language model is of size 1.8 GB, vocab file is around 25GB. Is there any way to determine how much memory is required to generate trie file?
