### ISSUE TITLE
libctc_decoder_with_kenlm.so not declared

### ISSUE THREAD

**Issue by andryrkt1** [mozilla/DeepSpeech#1084]
Hi, 
Any idea? Should I install kenLM package?
`bazel build -c opt --copt=-O3 //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie`

`ERROR: no such target '//native_client:libctc_decoder_with_kenlm.so': target 'libctc_decoder_with_kenlm.so' not declared in package 'native_client' defined by /Volumes/Dev/Mozilla/tensorflow/native_client/BUILD.`

I use Bazel 0.5.4

**Comment by vucuong12** [comment]
Please check the file /native_client/BUILD.

In the [latest release ](https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0), the package name is ctc_decoder_with_kenlm while in the [latest code ](https://github.com/mozilla/DeepSpeech/blob/e5757d21a38d40923c1de9b86597685f365150ee/native_client/BUILD#L110) it is libctc_decoder_with_kenlm.so

**Comment by andryrkt1** [comment]
@vucuong12 Thanks, it seems working
