### ISSUE TITLE
Alphabet has size 0.

### ISSUE THREAD

**Issue by elnurmen** [mozilla/DeepSpeech#1087]
I am a noob. Let me know if i am asking something stupid.
Tried to run on the pre-trained models. I am Ubuntu 16.04 64-bit.

Input: `deepspeech output_graph.pb record.wav aplhabet.txt lm.binary trie`

Output:
`Loading model from file output_graph.pb
Error: Alphabet size does not match loaded model: alphabet has size 0, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loaded model in 0.276s.
Loading language model from files lm.binary trie
Error: Mismatching alphabet size in trie file and alphabet file. Trie file will not be loaded.
Loaded language model in 0.056s.
Running inference.
Segmentation fault (core dumped)`

Tried again:
Input: `deepspeech output_graph.pb record.wav aplhabet.txt`
Output: 
`Loading model from file output_graph.pb
Error: Alphabet size does not match loaded model: alphabet has size 0, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loaded model in 0.213s.
Running inference.
Segmentation fault (core dumped)`

Here is my alphabet:
[alphabet.txt](https://github.com/mozilla/DeepSpeech/files/1544602/alphabet.txt)

**Comment by elpimous** [comment]
hi elnurmen,
Could you try with correct word ?!! LOL
not aplhabet.txt, but alphabet.txt
Have a nice day,  and enjoy
vincent

**Comment by bagustris** [comment]
I got the similar issue (also on Ubuntu 16.04) when running for the first time.
`deepspeech models/output_graph.pb models/alphabet.txt test.wav `
Output:
`Loading model from file models/output_graph.pb
Error: Alphabet size does not match loaded model: alphabet has size 768, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loaded model in 0.206s.
Traceback (most recent call last):
  File "/home/xxx/ds/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/home/xxx/ds/local/lib/python2.7/site-packages/deepspeech/client.py", line 66, in main
    fs, audio = wav.read(args.audio)
  File "/home/xxx/ds/local/lib/python2.7/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/xxx/ds/local/lib/python2.7/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format '# Ea'... not understood.`

I used version 0.1.1 and installed deepspeech using pip (tested on virtualenv).

**Comment by reuben** [comment]
You are following the instructions for the master version of the code, whereas you should be following the instructions for the 0.1.1 version of the code: https://github.com/mozilla/DeepSpeech/tree/v0.1.1#using-the-python-package

Namely, the audio file is the second argument to deepspeech, not the last.

**Comment by juancq** [comment]
Can this be updated in the readme for the master version? I just ran into the same issue and found the answer here.

**Comment by juancq** [comment]
Master seems to be in v0.2.0. So it is a little confusing, as users probably expect to be able to follow the readme they are reading (v0.2.0), and then realize the v0.1.1 issue after getting an error. Maybe adding a note under the "Getting the pre-trained model" noting to users that after executing the command, that they should follow the documentation under the v0.1.1 tree (including a link) or a brief sentence similar to what is explained in the wiki. Regardless, I'm all set.

**Comment by kdavis-mozilla** [comment]
@juancq PR's welcome :-)
