### ISSUE TITLE
'wav_filesize' error when try to train model by common voice data

### ISSUE THREAD

**Issue by s7s7s7** [mozilla/DeepSpeech#1090]
- **NO custom code written**
- **Ubuntu 14.04**
- **TensorFlow version:** 1.4.0
- **Python version**: 2.7.6
- **CUDA/cuDNN version**: cuda toolkit 8.0
- **GPU model and memory**: using CPU
- **Exact command to reproduce**: ./DeepSpeech.py --train_files ../CVfiles/cv_corpus_v1/cv-valid-train.csv,../CVfiles/cv_corpus_v1/cv-other-train.csv --dev_files ../CVfiles/cv_corpus_v1/cv-valid-dev.csv --test_files ../CVfiles/cv_corpus_v1/cv-valid-test.csv --decoder_library_path ./libctc_decoder_with_kenlm.so

We got the common voice data from the instruction in README. We already run the example file ldc93s1.sh, which is working properly. But when we try to train our model by the codes above, it always give back an 'wav_filesize' error. Can you help me figure out what is going on please?

> Traceback (most recent call last):
  File "./DeepSpeech.py", line 1829, in <module>
    tf.app.run()
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./DeepSpeech.py", line 1786, in main
    train()
  File "./DeepSpeech.py", line 1466, in train
    next_index=lambda i: COORD.get_next_index('train'))
  File "/home/team18/NLP/DeepSpeech/util/feeding.py", line 95, in __init__
    self.files = self.files.sort_values(by="wav_filesize", ascending=ascending) \
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3619, in sort_values
    k = self.xs(by, axis=other_axis).values
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/generic.py", line 2335, in xs
    return self[key]
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3838, in get
    loc = self.items.get_loc(item)
  File "/home/team18/NLP/my_project/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2524, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'wav_filesize'

**Comment by reuben** [comment]
Can you share the output of the following command, please? Run it from the same folder you were in when you ran `DeepSpeech.py`.

```bash
head ../CVfiles/cv_corpus_v1/cv-valid-train.csv ../CVfiles/cv_corpus_v1/cv-other-train.csv ../CVfiles/cv_corpus_v1/cv-valid-dev.csv ../CVfiles/cv_corpus_v1/cv-valid-test.csv
```

**Comment by s7s7s7** [comment]
@reuben  Thank you for responding. I find the problem, I feed deepspeech the wrong csv file. I should give it the one with file_size, but I gave it the one directly downloaded from common voice, which only included file name and text.

**Comment by s7s7s7** [comment]
If you open the cab file, the correct format should be :

First line: filename,filesize,file content
After first line:[path to your .wav file], filesize,[the words said in .Wav file]

I should give you a screen shoot, but I do not have my working desktop with me now, I will add a picture asap.

**Comment by phanlong95** [comment]
thank for your help.
it's very helpfull

2018-01-30 20:20 GMT+07:00 s7s7s7 <notifications@github.com>:

**Comment by alughaGmbH** [comment]
@phanlong95 
even I am facing the same problem. I checked the answer @s7s7s7 suggested. but i don't see any file with file_size column. should I create a column explicitly?. did you solve your problem.if so, can u share how you did?

**Comment by phanlong95** [comment]
@alughaGmbH 
i think csv file look like that: https://github.com/riri-leelee/machine_learning_17/blob/master/audio/train/train.csv 
it's gona be help you i think :D
sorry u can't help you a lot. i'm stuck . i can't not create trie file.

**Comment by alughaGmbH** [comment]
Hi @phanlong95 , 
Thank you for your response. I downloaded the Common Voice training data, but the files in them do not have wav_filesize column. I understand from the above conversations that I should feed a file with 3 attributes wav_filename	,wav_filesize,transcript. So should I manually create a file with these columns or is the CSV file is already there somewhere in any repository?

**Comment by kdavis-mozilla** [comment]
Did you follow the instructions here[[1](https://github.com/mozilla/deepspeech#common-voice-training-data)] to import the data?

**Comment by alughaGmbH** [comment]
@phanlong95....

yes, I am following the same instruction.

**Comment by alughaGmbH** [comment]
@kdavis-mozilla *

**Comment by kdavis-mozilla** [comment]
Could you provide the output of the `bin/import_cv.py` command you ran?

**Comment by alughaGmbH** [comment]
@kdavis-mozilla ,

I got the below error.
File "bin/import_cv.py", line 143, in <module>
   _download_and_preprocess_data(sys.argv[1])
IndexError: list index out of range
-----------------------------------------------------------------------
So I run bin/import_cv.py /tmp
: the results tell progress. but taking a lot of time.

**Comment by phanlong95** [comment]
i'm the same error

2018-02-09 16:13 GMT+07:00 alughaGmbH <notifications@github.com>:

**Comment by kdavis-mozilla** [comment]
@alughaGmbH As you've found, and as is documented[[1](https://github.com/mozilla/deepspeech#common-voice-training-data)], you have to provide a directory to the command.

As to it taking a lot of time, yes it does take some time as the data set is large and it takes time to download.

**Comment by alughaGmbH** [comment]
@kdavis-mozilla ,

I run this command before only. from this command only we get "  **cv_corpus_v1** " folder is it?.

**Comment by kdavis-mozilla** [comment]
@alughaGmbH Sounds about right. What files are at the same level as `cv_corpus_v1` and what are the contents of `cv_corpus_v1`?

**Comment by alughaGmbH** [comment]
![image](https://user-images.githubusercontent.com/35231420/36215067-57adbe2c-11ab-11e8-89cd-e93f6472242e.png)



these are the files I have

**Comment by Hafsa26** [comment]
Does wave file size in mili-seconds? or in any other form of unit?

**Comment by imKKK** [comment]
I am getting AttributeError: 'Series' object has no attribute 'transcript' while executing

**Comment by imKKK** [comment]
@Hafsa26 the filesize should be in bytes

**Comment by Hafsa26** [comment]
Thank you so much! @imKKK
