### ISSUE TITLE
String-to-Label Error

### ISSUE THREAD

**Issue by riri-leelee** [mozilla/DeepSpeech#1091]
Using python 2.7, tensorflow version ('v1.4.0-rc1-11-g130a514', '1.4.0').
Working inside of a Ubuntu VM

I have created my own set of data to train a model with. 
I am able to run the training but it immediately errors out.
Run command:

./run.sh + [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py --train_files /home/amlee100/tmp/audio/train/train.csv --dev_files /home/amlee100/tmp/audio/dev/dev.csv --test_files /home/amlee100/tmp/audio/test/test.csv --train_batch_size 10 --dev_batch_size 10 --test_batch_size 12 --early_stop True --dropout_rate 0.22 --learning_rate 0.00095 --export_dir /home/amlee100/tmp/result/ --checkpoint_dir /home/amlee100/tmp/result/ --decoder_library_path /home/amlee100/tmp/deepspeech-venv/libctc_decoder_with_kenlm.so --alphabet_config_path /home/amlee100/tmp/models/vocab.txt --lm_binary_path /home/amlee100/tmp/models/lm.binary --lm_trie_path /home/amlee100/tmp/deepspeech-venv/trie
W Parameter --validation_step needs to be >0 for early stopping to work

Error:

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/amlee100/tmp/deepspeech-venv/util/feeding.py", line 148, in _populate_batch_queue
    target = text_to_char_array(transcript, self._alphabet)
  File "/home/amlee100/tmp/deepspeech-venv/util/text.py", line 40, in text_to_char_array
    return np.asarray([alphabet.label_from_string(c) for c in original])
  File "/home/amlee100/tmp/deepspeech-venv/util/text.py", line 30, in label_from_string
    return self._str_to_label[string]
KeyError: u'l'

This error is occurring with threads 3-8. Does that mean that threads 1 and 2 are still running and I can keep he program alive and gets results? Are the threads being used even if they errored out at the beginning? Is there something that I can do to fix this?

**Comment by reuben** [comment]
Can you share the contents of the `/home/amlee100/tmp/models/vocab.txt` file? It looks like it's not a valid alphabet file.

**Comment by riri-leelee** [comment]
[alphabet.txt](https://github.com/mozilla/DeepSpeech/files/1546132/alphabet.txt)

**Comment by reuben** [comment]
It's probably some weird encoding problem in your `train.csv` file. Make it's UTF-8 encoded with the characters matching the contents of your `vocab.txt`. For example, the letter `à` should be encoded as `\xc3\xa0`, not as `\xcc\x80`. You can do this by installing `uconv` and then doing:

```bash
uconv -x any-nfc < /home/amlee100/tmp/audio/train/train.csv > /home/amlee100/tmp/audio/train/train.csv.normalized
uconv -x any-nfc < /home/amlee100/tmp/audio/dev/dev.csv > /home/amlee100/tmp/audio/dev/dev.csv.normalized
uconv -x any-nfc < /home/amlee100/tmp/audio/test/test.csv > /home/amlee100/tmp/audio/test/test.csv.normalized
```

And then passing the `.normalized` files in the `--train_files`, `--dev_files` and `--test_files` arguments.

**Comment by riri-leelee** [comment]
That did not appear to work. 
I used all three commands and it still gave the same errors. Then I sent all of the files over to a WindowsOS, opened them in notepad and saved them as UTF-8. This still had no effect on the error.
What confuses me is that the error is occurring on letters like 'l', 's', and 'b' not the specials ones.

**Comment by reuben** [comment]
Yeah, it's confusing to me too, I've never seen that error. Can you post the output of the following command? Run it from the folder where `DeepSpeech.py` is locate.

```bash
python -c "from util.text import Alphabet; a = Alphabet('/home/amlee100/tmp/models/vocab.txt'); print('\n'.join([u'\'{}\' ({}) -> {}'.format(s, ':'.join('{:02x}'.format(ord(c)) for c in s), a._str_to_label[s]) for s in a._str_to_label]))"
```

**Comment by riri-leelee** [comment]
`'domenica l'afflusso di fedeli al santuario della vergine maria fu consistente' (64:6f:6d:65:6e:69:63:61:20:6c:27:61:66:66:6c:75:73:73:6f:20:64:69:20:66:65:64:65:6c:69:20:61:6c:20:73:61:6e:74:75:61:72:69:6f:20:64:65:6c:6c:61:20:76:65:72:67:69:6e:65:20:6d:61:72:69:61:20:66:75:20:63:6f:6e:73:69:73:74:65:6e:74:65) -> 453
'la spelta ed il sorgo sono cereali utilizzati nell'allevamento di ovini e bovini' (6c:61:20:73:70:65:6c:74:61:20:65:64:20:69:6c:20:73:6f:72:67:6f:20:73:6f:6e:6f:20:63:65:72:65:61:6c:69:20:75:74:69:6c:69:7a:7a:61:74:69:20:6e:65:6c:6c:27:61:6c:6c:65:76:61:6d:65:6e:74:6f:20:64:69:20:6f:76:69:6e:69:20:65:20:62:6f:76:69:6e:69) -> 162
'quattro quei signori non sanno mai cosa fare nè dove andare' (71:75:61:74:74:72:6f:20:71:75:65:69:20:73:69:67:6e:6f:72:69:20:6e:6f:6e:20:73:61:6e:6e:6f:20:6d:61:69:20:63:6f:73:61:20:66:61:72:65:20:6e:e8:20:64:6f:76:65:20:61:6e:64:61:72:65) -> 397
'sci' (73:63:69) -> 421
'otto se mi lasci un'altra volta solo non ti parlerò' (6f:74:74:6f:20:73:65:20:6d:69:20:6c:61:73:63:69:20:75:6e:27:61:6c:74:72:61:20:76:6f:6c:74:61:20:73:6f:6c:6f:20:6e:6f:6e:20:74:69:20:70:61:72:6c:65:72:f2) -> 190
'quando stai buono a scuola la mamma ti regala sempre una cosa bella' (71:75:61:6e:64:6f:20:73:74:61:69:20:62:75:6f:6e:6f:20:61:20:73:63:75:6f:6c:61:20:6c:61:20:6d:61:6d:6d:61:20:74:69:20:72:65:67:61:6c:61:20:73:65:6d:70:72:65:20:75:6e:61:20:63:6f:73:61:20:62:65:6c:6c:61) -> 367
'luigi ha amato una sola donna nella sua vita ed ora è rimasto solo al mondo' (6c:75:69:67:69:20:68:61:20:61:6d:61:74:6f:20:75:6e:61:20:73:6f:6c:61:20:64:6f:6e:6e:61:20:6e:65:6c:6c:61:20:73:75:61:20:76:69:74:61:20:65:64:20:6f:72:61:20:e8:20:72:69:6d:61:73:74:6f:20:73:6f:6c:6f:20:61:6c:20:6d:6f:6e:64:6f) -> 169
'nonostante lo sforzo estremo il superstite non riuscì ad approdare sull'isola' (6e:6f:6e:6f:73:74:61:6e:74:65:20:6c:6f:20:73:66:6f:72:7a:6f:20:65:73:74:72:65:6d:6f:20:69:6c:20:73:75:70:65:72:73:74:69:74:65:20:6e:6f:6e:20:72:69:75:73:63:ec:20:61:64:20:61:70:70:72:6f:64:61:72:65:20:73:75:6c:6c:27:69:73:6f:6c:61) -> 353
'camion' (63:61:6d:69:6f:6e) -> 409
'l'iceberg partito dal polo nord non si potrà sgelare in breve tempo' (6c:27:69:63:65:62:65:72:67:20:70:61:72:74:69:74:6f:20:64:61:6c:20:70:6f:6c:6f:20:6e:6f:72:64:20:6e:6f:6e:20:73:69:20:70:6f:74:72:e0:20:73:67:65:6c:61:72:65:20:69:6e:20:62:72:65:76:65:20:74:65:6d:70:6f) -> 130
'il governo balneare ha dato corso a provvedimenti in ambito pubblico e privato' (69:6c:20:67:6f:76:65:72:6e:6f:20:62:61:6c:6e:65:61:72:65:20:68:61:20:64:61:74:6f:20:63:6f:72:73:6f:20:61:20:70:72:6f:76:76:65:64:69:6d:65:6e:74:69:20:69:6e:20:61:6d:62:69:74:6f:20:70:75:62:62:6c:69:63:6f:20:65:20:70:72:69:76:61:74:6f) -> 358
'costume' (63:6f:73:74:75:6d:65) -> 326
`

Here is a small sample of the larger output. It includes some of the special characters.
When I tried to save the output to a file, I received this error. Not sure if it is of any help.

`python -c "from util.text import Alphabet; a = Alphabet('/home/amlee100/tmp/models/vocab.txt'); print('\n'.join([u'\'{}\' ({}) -> {}'.format(s, ':'.join('{:02x}'.format(ord(c)) for c in s), a._str_to_label[s]) for s in a._str_to_label]))" >> output.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 699: ordinal not in range(128)
`

**Comment by reuben** [comment]
Wait, what? Did you edit the comment where you shared `vocab.txt`? The previous file was a valid alphabet file, but the one that's there now is invalid. You should use a proper alphabet file. It looks like you're confusing the alphabet file and the language model vocabulary file.

**Comment by reuben** [comment]
This was the file you originally shared, which has valid syntax for an alphabet file: https://gist.github.com/reuben/75e7e7159592f581a4546a94bcf80f08

The one currently in [this comment](#issuecomment-350586376) is invalid.

**Comment by riri-leelee** [comment]
Wow... thats been my problem this entire time. I apologize for the inconvenience.
