### ISSUE TITLE
Can this code be used in Chinese speech recognition?

### ISSUE THREAD

**Issue by jackHuanghello** [mozilla/DeepSpeech#1097]
Have someone used this code to do Chinese speech recognition? Does it works?

**Comment by saeedbinhamad** [comment]
https://arxiv.org/abs/1512.02595 Apparently yes!

**Comment by jackHuanghello** [comment]
Thank you! But this project is based on DeepSpeech, not DeepSpeech2. So, I'm worried about whether this project is applicable to Chinese.

**Comment by kdavis-mozilla** [comment]
The same means of supporting Chinese used in DeepSpeech2 can be used in DeepSpeech.

**Comment by jackHuanghello** [comment]
so, it means if the character set( data/alphabet.txt) are changed, the project can transfer Chinese words?

**Comment by kdavis-mozilla** [comment]
Basically yes.

You'll also need to create the language model, trie, vocabulary and the like. For a similar example of going to French see Vincent Foucault's excellent tutorial[[1](https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830?u=kdavis)].

**Comment by bolt163** [comment]
@jackHuanghello, 中文的你跑出来了吗...

**Comment by jackHuanghello** [comment]
https://discourse.mozilla.org/t/training-chinese-model/27769 @bolt163

**Comment by areyliu6** [comment]
@jackHuanghello 
我也在嘗試中文的訓練，有範例嗎？
謝謝

**Comment by yangpei11** [comment]
@jackHuanghello  hello, your link become invalid. Can I have future contact with you, ?My WeChat is: 13797206291
