### ISSUE TITLE
Wrong tower accuracy calculation and usage

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#110]
During training the average accuracy is calculated on base of a wrong divisor.

**Comment by lissyx** [comment]
Could that explain why we saw 50% constantly on the automated WER calculation, and why locally I constantly got 1.0 ?

**Comment by tilmankamp** [comment]
No - this is due to another effect.
Please look at https://github.com/mozilla/DeepSpeech/blob/0849efd6daff49389437195acc91ca9de60f04e6/util/text.py#L74 for context. Actually everything is OK how it is.
