### ISSUE TITLE
Does this project have model for Deep speech 2?

### ISSUE THREAD

**Issue by PandoraLS** [mozilla/DeepSpeech#1100]
Hello, I find out Deep Speech project is based on [DeepSpeech 2014](https://arxiv.org/abs/1412.5567) according to project home page on github. But I want to know if this project supports [DeepSpeech2 2016](http://proceedings.mlr.press/v48/amodei16.html). [One github issue](https://github.com/mozilla/DeepSpeech/issues/560)mentioned to check out ds2-v2 branch, which I cannot locate.
Thanks.

**Comment by kdavis-mozilla** [comment]
It currently is an implementation of Deep Speech.

PS: Issues should focus on bugs in the current code base[[1](https://github.com/mozilla/deepspeech#contactgetting-help)] Questions such as this are better addressed in the Discourse forms or in IRC.
