### ISSUE TITLE
Details of pre-trained model

### ISSUE THREAD

**Issue by zh794390558** [mozilla/DeepSpeech#1101]
Where to get details of pre-trained model, like training dataset, test dataset, and WERs. 
I can not find it in wiki and release notes.

**Comment by kdavis-mozilla** [comment]
These questions are addressed in the discussion on issue 758[[1](https://github.com/mozilla/DeepSpeech/issues/758#issuecomment-346933815)]

**Comment by reuben** [comment]
They are, but I agree that they should at least be in the release notes.
