### ISSUE TITLE
Installed deepspeech-gpu, but keep running by CPU

### ISSUE THREAD

**Issue by s7s7s7** [mozilla/DeepSpeech#1105]
Hi,

I installed the deepspeech-gpu, and try to train my model by commands like below:

>#!/bin/sh
set -xe
if [ ! -f DeepSpeech.py ]; then
    echo "Please make sure you run this from DeepSpeech's top level directory."
    exit 1
fi;
if [ -d "${COMPUTE_KEEP_DIR}" ]; then
    checkpoint_dir=$COMPUTE_KEEP_DIR
else
    checkpoint_dir=$(python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/myself"))')
fi
python -u DeepSpeech.py \
  --train_files ../MyTestData/cv-valid-train2.csv \
  --dev_files ../MyTestData/cv-valid-dev2.csv \
  --test_files ../MyTestData/cv-valid-test2.csv \
  --train_batch_size 1 \
  --dev_batch_size 1 \
  --test_batch_size 1 \
  --n_hidden 494 \
  --epoch 550 \
  --checkpoint_dir "$checkpoint_dir" \
  --decoder_library_path ./libctc_decoder_with_kenlm.so \
"$@"

but the training is super slow, and I cannot find the process from nvidia-smi.
I can run the CUDA-samples(I tried 1 and 5, they worked properly).

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Yes, and they are shown above.
- **OS Platform and Distribution**: Ubuntu 14.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: can't rememver
- **TensorFlow version (use command below)**: TensorFlow 1.4.0
- **Python version**: 2.7.6
- **CUDA/cuDNN version**: CUDA-8.0
- **GPU model and memory**: GTX1080-8GB

I am wondering if I need to pass any other arguments to the DeepSpeech.py in order to use gpu, or there is anything possibly wrong with my GPU setting?

Thanks for any help and advice.

**Comment by lissyx** [comment]
You don't need `deepspeech-gpu` Python package to perform training, but rather TensorFlow with `CUDA` support enabled. Please `pip uninstall deepspeech-gpu tensorflow && pip install tensorflow-gpu==1.4.0` and it should leverage your hardware better.

**Comment by lissyx** [comment]
@dakshvar22 Please document your setup.
