### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by jackHuanghello** [mozilla/DeepSpeech#1106]
I have run the training program for 1 days, But now I got this error.
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/disk2/my-dir/IDE/anaconda2/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/disk2/my-dir/IDE/anaconda2/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/disk2/my-dir/IDE/deepspeech-venv/DeepSpeech/util/feeding.py", line 148, in _populate_batch_queue
    target = text_to_char_array(transcript, self._alphabet)
  File "/disk2/my-dir/IDE/deepspeech-venv/DeepSpeech/util/text.py", line 40, in text_to_char_array
    return np.asarray([alphabet.label_from_string(c) for c in original])
TypeError: 'float' object is not iterable

```
I only set  --validation_step 5, and the other parameters are default.
I wonder why this error would happen?

**Comment by lissyx** [comment]
Can you share us your changes ?

**Comment by jackHuanghello** [comment]
However, I didn't change the source code.
Here is where the error occurs.
```
def text_to_char_array(original, alphabet):
    r"""
    Given a Python string ``original``, remove unsupported characters, map characters
    to integers and return a numpy array representing the processed string.
    """
    return np.asarray([alphabet.label_from_string(c) for c in original])
```
```
 def _populate_batch_queue(self, session, coord):
        '''
        Queue thread routine.
        '''
        file_count = len(self._data_set.files)
        index = -1
        while not coord.should_stop():
            index = self._data_set.next_index(index) % file_count
            wav_file, transcript = self._data_set.files[index]
            source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
            source_len = len(source)
            target = text_to_char_array(transcript, self._alphabet)
            target_len = len(target)
            if source_len < target_len:
                raise ValueError('Error: Audio file {} is too short for transcription.'.format(wav_file))
            try:
                session.run(self._enqueue_op, feed_dict={ self._model_feeder.ph_x: source,
                                                          self._model_feeder.ph_x_length: source_len,
                                                          self._model_feeder.ph_y: target,
                                                          self._model_feeder.ph_y_length: target_len })
            except tf.errors.CancelledError:
                return
```

**Comment by reuben** [comment]
Do any of your transcriptions look like a floating point value? Pandas is sometimes too clever for its own good and casts the string to a float if it looks like a float. This includes things like '0e0' , '1e1', '1.'. You could also add a check before that `if source_len < target_len:` to test if `isinstance(transcript, str)`, then you can identify the problematic sample.

We should also look into disabling these casts completely in Pandas.

**Comment by jackHuanghello** [comment]
I find what caused the problem today. The error occurs when the "original" value is nan.
```
def text_to_char_array(original, alphabet):
    r"""
    Given a Python string ``original``, remove unsupported characters, map characters
    to integers and return a numpy array representing the processed string.
    """
    return np.asarray([alphabet.label_from_string(c) for c in original])
```
It seems that the system can't transcribe the audio to words.

**Comment by dalonlobo** [comment]
Hi, Even I'm facing the same issue, is there any resolution?

**Comment by jackHuanghello** [comment]
Is "train-other.csv" file included in your training set? I find some data in that file is defective like the transcript is blank.

**Comment by dalonlobo** [comment]
Yes its included. Is it because the transcripts are defective?

**Comment by jackHuanghello** [comment]
Yes, I removed the defective data, and the problem didn't happen again.

**Comment by dalonlobo** [comment]
Can you give me an idea, on what to look for? Like spaces or special characters?

**Comment by jackHuanghello** [comment]
I use the Excel, choose the column of  "transcript", use "ctrl + f"， input nothing,  just use "find next", and then the defective data can be found.

**Comment by dalonlobo** [comment]
Thank you for you help @jackHuanghello, I will try that.

**Comment by jackHuanghello** [comment]
That's OK!

**Comment by dalonlobo** [comment]
Cleaning up the transcripts solved this error. I removed the NaN from my transcripts.

**Comment by manuliner** [comment]
when downloading the CV data there are two empty references/text in the cv-other-train.csv
Line 22378
Line 83264

**Comment by kdavis-mozilla** [comment]
@tilmankamp Could you comment on the empty references?

**Comment by manuliner** [comment]
after cleaning the CSV file, the error still occurs

 `I STARTING Optimization
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rechenknecht/DeepSpeech/util/feeding.py", line 148, in _populate_batch_queue
    target = text_to_char_array(transcript, self._alphabet)
  File "/home/rechenknecht/DeepSpeech/util/text.py", line 40, in text_to_char_array
    return np.asarray([alphabet.label_from_string(c) for c in original])
TypeError: 'float' object is not iterable

`

**Comment by manuliner** [comment]
i printetd the input of the function "text_to_xhar_array" and the error appears after the sentece "the only things that concerned the sheep were food and water"
Console says input is nan

**Comment by kavuri** [comment]
I am facing the same problem (the error and stack trace) when I am trying to train with a different language.
I checked the training file and there is text associated with the wav file entry, but it is short (2 characters of a sound). But there are other entries for which the same error is thrown that have more chars (<7). Could this be a problem?

```Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kavuri/ds/util/feeding.py", line 149, in _populate_batch_queue
    target = text_to_char_array(transcript, self._alphabet)
  File "/home/kavuri/ds/util/text.py", line 40, in text_to_char_array
    return np.asarray([alphabet.label_from_string(c) for c in original])
TypeError: 'float' object is not iterable```

Also, I see that even after these errors, DeepSpeech.py does not exit and continues to do something (not sure what it is). Is there any progress shown while the training happens?

**Comment by kavuri** [comment]
My problem got resolved. It was because the header in my train.csv file had a wrong "transcript" text (it was "transcri"). I fixed the problem and was able to successfully generate the model

**Comment by lissyx** [comment]
@kavuri Thanks for updating us ! I guess it's one more example we need that tooling to help validate the corpus.
