### ISSUE TITLE
Create tooling to create/validate the trie and alphabet.txt files, given a text corpus

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#1107]
People have been falling into all kinds of traps with these files, it'd be good if we could make it easier to create them or validate existing ones.

**Comment by thebrahminator** [comment]
Has anyone worked on it, and what exactly is required to solve this issue? I can help with it.

**Comment by lissyx** [comment]
@thebrahminator Nobody worked on that yet. It's basically making sure prior to training that everything is fine. Mostly, it should be about exercizing the feeding / importers but not running training.

**Comment by Hafsa26** [comment]
Have somebody work on it? It will be a big help.

**Comment by lissyx** [comment]
@Hafsa26 I think we can consider that `util/check_characters.py` does the work?

**Comment by reuben** [comment]
`util/check_characters.py` helps with character set consistency, and we now embed the alphabet and other parameters directly in the model, which reduces surface for errors. If you use `util_characters.py` to generate alphabet.txt, everything should be consistent. I think this can be considered fixed.
