### ISSUE TITLE
Supported GPUs

### ISSUE THREAD

**Issue by wonkothesane42** [mozilla/DeepSpeech#1111]
what GPUs are supported. can't find the details in the documentation. please provide link, don't just say "see release notes".

**Comment by lissyx** [comment]
Please take this kind of discussion to Discourse: https://discourse.mozilla.org/c/deep-speech/l/latest

**Comment by lissyx** [comment]
Regarding your precise question, current builds available from pypi/npm are relying on CUDA, so NVIDIA GPUs only.

**Comment by lissyx** [comment]
CUDA 8.0 / CuDNN v6 for the version based on TensorFlow v1.4 (available from TaskCluster), and CUDA 8.0 / CuDNN v5.1 for the version that is still available from pypi / npm registries.
