### ISSUE TITLE
Using deepspeech from code (python 2.7.10, Mac OS High Sierra 10.13.1, LLVM version 8.1.0 (clang-802.0.42))

### ISSUE THREAD

**Issue by sn0wf1llin** [mozilla/DeepSpeech#1112]
I want to use your library from the code, with standard import deepspeech or smth else; 
I just want to process speech with your pre-trained model (client.py has this functional)

```from deepspeech.model import Model```

give me illegal instruction: 4

**Comment by lissyx** [comment]
It's not very clear:
 - What's your CPU? 
 - How did you install the Python module ?

When you say "client.py has this functional"  do you mean that it works using client.py?

**Comment by sn0wf1llin** [comment]
1. CPU: 2,8 GHz Intel Core i7

2. I installed **deepspeech** by ```pip install deepspeech```
    It installed successfully
    2.1 But I can't install **deepspeech-gpu** 
          The error ```DistributionNotFound: No matching distribution found for deepspeech-gpu```    appeared

"When you say "client.py has this functional" do you mean that it works using client.py?" -- no, it doesn't work in this case too. 

```
 >> deepspeech models/output_graph.pb my_speech.wav models/alphabet.txt 
```
gave me
```
illegal instruction: 4
```

**Comment by reuben** [comment]
Can you try with a newer build of the Python package? It could be due to unsupported instructions in the binary. Is your computer several years old?

```bash
pip uninstall tensorflow
pip install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.osx/artifacts/public/deepspeech-0.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
```

**Comment by sn0wf1llin** [comment]
reuben, thanks a lot!
```
pip uninstall tensorflow
pip uninstall tensorflow-tensorboard
pip uninstall deepspeech
pip install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.osx/artifacts/public/deepspeech-0.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
```
worked for me

But the quality of recognition is very bad (I used pre-trained model)
Why could it happen?

**Comment by lissyx** [comment]
@sn0wf1llin Thanks for confirming it's no issue in fact. Regarding the issue you have about quality, that kind of topic is better discussed on Discourse https://discourse.mozilla.org/c/deep-speech, there are other threads already. Please share as much as details as you can on your use (model file downloaded from where, how you recorded your audio, are you native english speaker, etc.).
