### ISSUE TITLE
Is the language model based on character or word?

### ISSUE THREAD

**Issue by jackHuanghello** [mozilla/DeepSpeech#1114]
I wonder whether the n-gram model is trained based on character or word?

**Comment by kdavis-mozilla** [comment]
These type of questions are better addressed in the discourse forms[[1](https://discourse.mozilla.org/c/deep-speech)] as they don't refer to bugs/feature requests in the current code base.

**Comment by jackHuanghello** [comment]
Thank you, and I will do that.
