### ISSUE TITLE
Unable to train when installing TensorFlow and DeepSpeech bindings in the same python env: cannot register 2 metrics with the same name

### ISSUE THREAD

**Issue by alirezadir** [mozilla/DeepSpeech#1116]
- OS Platform and Distribution: Linux Ubuntu 16.04:
- TensorFlow installed from: 
`python util/taskcluster.py --target /tmp --source tensorflow --arch gpu --artifact tensorflow_gpu_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl`
`pip install /tmp/tensorflow_gpu_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl`
- native client installed  using: 
`python util/taskcluster.py --target . --arch gpu`
- Deep speech installed using: 
`pip install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.gpu/artifacts/public/deepspeech_gpu-0.1.0-cp27-cp27mu-manylinux1_x86_64.whl`
- TensorFlow version: tensorflow-gpu-warpctc (1.4.0) ` eigen-osx-fix-8d1ccfd9c5a0-2973-g1390dc1', '1.4.0-warpctc0.1`
- Python version: 2.7.12
- CUDA/cuDNN version: CUDA: 8.0 / cudnn 6.0
- GPU model and memory: GeForce GTX 1080 TI
- Exact command to reproduce: python ./DeepSpeech.py --help

Hey guys, 

I have been trying to run deepspeech with  gpu support with cudnn 6.0. I keep getting several issues with tensorflow  after uninstalling tensorflow 1.4 and installing the warp-ctc version (including no module found). This is the latest error that I get after creating a new virtualenv and trying everything fresh, when I run `python ./DeepSpeech.py --help`:
```
F tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count
Aborted (core dumped)
```
I appreciate your help.

**Comment by lissyx** [comment]
Thanks, can you retry with tensorflow upstream ? Destroy your virtual env, create one were you install first just tensorflow==1.4.0, then try training.

**Comment by lissyx** [comment]
@alirezadir I do reproduce the issue locally, when installing `deepspeech-gpu` package. Looks like it's broken :(

**Comment by lissyx** [comment]
So, those venv fails, when installing:
 - upstream tensorflow cpu + deepspeech cpu python bindings
 - upstream tensorflow gpu + deepspeech gpu python bindings

Not installing deepspeech bindings in the same venv is enough.

**Comment by lissyx** [comment]
So, during training, we can leverage some code from the `deepspeech` or the `deepspeech-gpu` package, as you can read in `util/audio.py`:
```
from deepspeech.utils import audioToInputVector
```

However, Python wrapper `deepspeech/_utils.so` is linking against too much, including `libdeepspeech.so`, `libtensorflow_cc.so` and `libtensorflow_framework.so`. Using `patchelf` to quickly remove those deps (I don't have a ready to use build dir on my machine right now), I removed those and the result was:
 - tensorflow-gpu + deepspeech-gpu in the same virtualenv
 - `python DeepSpeech --help` does not fail anymore like above
 - no warning about lack of `deepspeech.utils.audioToInputVector`, so `libdeepspeech_utils.so` is actually leveraged.

**Comment by lissyx** [comment]
https://tools.taskcluster.net/groups/VShe5svMTCC4gLsZNtuh8g for PR https://github.com/mozilla/DeepSpeech/pull/1117 reproduces the issue. I have some local changes that should fix that, it needs some more cleanup and testing, though.

**Comment by alirezadir** [comment]
@lissyx thank you very much for your follow up. Here is my result of your initial suggestion:

I tried tensorflow upstream (tensorflow==1.4.0), and I can run the training, but it throws a warning: 
`WARNING: libdeepspeech failed to load, resorting to deprecated code
         Refer to README.md for instructions on installing libdeepspeech`

Then I tried a new venv, and installed deepspeech-gpu using pip install deepspeech-gpu. Now I get the error:
`Traceback (most recent call last):
  File "/home/a.dirafzoon/tmp/deepspeech-venv/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/home/a.dirafzoon/tmp/deepspeech-venv/lib/python2.7/site-packages/deepspeech/client.py", line 10, in <module>
    from deepspeech.model import Model
  File "/home/a.dirafzoon/tmp/deepspeech-venv/lib/python2.7/site-packages/deepspeech/model.py", line 21, in <module>
    _model = swig_import_helper()
  File "/home/a.dirafzoon/tmp/deepspeech-venv/lib/python2.7/site-packages/deepspeech/model.py", line 20, in swig_import_helper
    return importlib.import_module('_model')
  File "/home/a.dirafzoon/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _model`
which I think is for the same reason as #1094 . I think I need to install deepspeech from `https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.gpu/artifacts/public/deepspeech_gpu-0.1.0-cp27-cp27mu-manylinux1_x86_64.whl`, but then it will require the new native client, which will loop me back to the same situation. I will try your work-around suggestions soon. 

Thanks,

**Comment by lissyx** [comment]
@alirezadir Thanks, as you can see, it should be okay once we merge https://github.com/mozilla/DeepSpeech/pull/1117 and you will be able to pip install from TaskCluster :)

**Comment by lissyx** [comment]
@alirezadir As soon as tasks from https://tools.taskcluster.net/groups/IUAMmrcSRISjrTiNBlajOg are finished, you should be able to pip install from taskcluster with fixes :)

**Comment by alirezadir** [comment]
@lissyx thanks for fixing he issue. So what would be the new link to do `pip install`?

**Comment by alirezadir** [comment]
@lissyx also, which versions of tensorflow and naive-client should I use? :)

**Comment by lissyx** [comment]
@alirezadir This should work and install you the fixed version: `pip install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.gpu/artifacts/public/deepspeech_gpu-0.1.0-cp27-cp27mu-manylinux1_x86_64.whl`, same link yes :)

**Comment by alirezadir** [comment]
@lissyx thanks a lot. It works now :)
