### ISSUE TITLE
How does DeepSpeech discriminate between speech-music?

### ISSUE THREAD

**Issue by StanSilas** [mozilla/DeepSpeech#1118]
Say I'm recording a radio DJ, and the final results in an audio file containing : 
**_music --- some music --- speech -- music--- speech --- speech --- speech --- hold music --- end of audio_**
here speech is assumed to be non overlapping or marginally overlapping.

How do I ignore the non speech and extract only the speech portions of the audio?
i.e I want my final audio to have only the speech portions.

How does deep speech currently handle this kind of music?

**Comment by lissyx** [comment]
Thanks for your question, however, it's not an issue, so please use Discourse for this, https://discourse.mozilla.org/c/deep-speech where better exchanges can be achieved.
