### ISSUE TITLE
What is the training data of your language model?

### ISSUE THREAD

**Issue by ksellesk** [mozilla/DeepSpeech#1119]
We are making a benchmark between Deepspeech and Attention-base ASR.

Could you please tell us What is the training data of your language model?

**Comment by kdavis-mozilla** [comment]
Fisher + Switchboard + Librivox test sets plus, as far as I remember, some wikipedia text.

In future questions like this should be directed towards the Discourse form[[1](https://discourse.mozilla.org/c/deep-speech)].
