### ISSUE TITLE
Wrong result while testing Trump 5 seconds speech using a pre-trained model & python

### ISSUE THREAD

**Issue by sn0wf1llin** [mozilla/DeepSpeech#1121]
Here is the .wav file: [Trump.wav](https://soundcloud.com/max-weiss-528941509/trump-speech5s)

But when I use your pre-trained model, the results I get are veeery strange.
```
 >> deepspeech models/output_graph.pb trump_speech5s.wav models/alphabet.txt
Loading model from file models/output_graph.pb
Loaded model in 1.005s.
Running inference.
un sh
Inference took 14.645s for 13.781s audio file.
```
Why could it happened?
What an I do to make it work?

**Comment by kdavis-mozilla** [comment]
The audio 16-bit, 16 kHz, and mono? What happens when you use the language model + trie?

**Comment by sn0wf1llin** [comment]
I have a mono 16kHz 16-bit file, an then I cut it into small pieces, and test on one of them. Error happened.
But when I take one piece of .mp3 file and convert it to mono 16-bit 16kHz separately, everything is good.
Thank you very much!
