### ISSUE TITLE
Provide a way to get N top paths from decoder instead of only the best path

### ISSUE THREAD

**Issue by sadhana195090** [mozilla/DeepSpeech#1122]
First of all thanks a lot for this awesome open source speech to text model . I am using the pretrained English model using deepspeech python package. Is there a way for me to get top N transcripts instead of just the best one?

**Comment by reuben** [comment]
One would have to modify the code, in particular, the `top_paths` parameter to the [decoder call](https://github.com/mozilla/DeepSpeech/blob/99d0c311a3e6108ed835fa38e4680ba7b3744fad/DeepSpeech.py#L532), and then handle the multiple results downstream from that call.

**Comment by sadhana195090** [comment]
got it. thanks. But i am struggling with pre-trained model loading [here](https://github.com/mozilla/DeepSpeech/blob/99d0c311a3e6108ed835fa38e4680ba7b3744fad/DeepSpeech.py#L1758). Is there a way to create .data and .meta files from .pb file? or a way to restore the graph with trained variable weights from .pb file?

**Comment by kdavis-mozilla** [comment]
We haven't currently released a checkpoint for our model. However, we plan to do so in the next maintenance release.

**Comment by sadhana195090** [comment]
approximate timeline please?

**Comment by kdavis-mozilla** [comment]
Approximately a month. 

@sadhana195090 As this is evolving in to a discussion, can we move and talk not related to the original issue to the [discourse form](https://discourse.mozilla.org/c/deep-speech).

**Comment by sadhana195090** [comment]
sure
