### ISSUE TITLE
Export model to .pb

### ISSUE THREAD

**Issue by tuong-olli** [mozilla/DeepSpeech#1124]
I train model with cv_corpus_v1 and add 2 parameters: --checkpoint_dir and --export_dir
Checkpoint_dir has files model.ckpt 
But export_dir does not have output_graph.pb

**Comment by lissyx** [comment]
@tuong-olli 
There is no reason it would not work, especially since TaskCluster tests do rely on this feature: `bin/run-tc-ldc93s1.sh` has `--export_dir "/tmp/train"` resulting in `/tmp/train/output_graph.pb`.

Can you share your exact command line and the output?

**Comment by tuong-olli** [comment]
This is my code
./DeepSpeech.py --train_files data/CV/cv-valid-train.csv,data/CV/cv-other-train.csv --dev_files data/CV/cv-valid-dev.csv --test_files data/CV/cv-valid-test.csv --export_der logs/ --checkpoint checkpoints/
I create 2 folders: logs/ and checkpoints/ in folder DeepSpeech/. The result is in checkpoints/ has files but logs/ is empty.
Thanks for your answer. I will fix it.

**Comment by lissyx** [comment]
@tuong-olli Your command line above uses `--export_der` instead of `--export_dir`, isn't it just this typo?
