### ISSUE TITLE
Audio pre-processing documentation for beginners

### ISSUE THREAD

**Issue by kofalt** [mozilla/DeepSpeech#1126]
Hello! I'm enthusiastic about the DeepSpeech project, and have successfully ran detection on some clean samples from the LibriSpeech corpus. Similar attempts using my laptop microphone have generally produced gibberish, and it's my understanding that I need to pre-process my audio before sending it into DeepSpeech. From what I've seen, de-noising, possibly using speech detection to split a sample into smaller fragments, and other changes that may be necessary.

I understand this is a large topic, but would anyone be interested in helping provide some general pointers for an audio novice? If someone can provide enough direction to get started, I'd be willing to write up a section of the readme, or maybe a wiki article, about a one-size-fits-most process to apply to audio before sending it through DeepSpeech. Thoughts?

---

- **Have I written custom code**: No
- **OS Platform and Distribution**: Ubuntu 14.04.5 LTS
- **TensorFlow installed from**: I'm using the v0.1.0 pre-trained command-line binary
- **TensorFlow version**: n/a
- **Python version**: 2.7.6
- **Bazel version**: n/a
- **GCC/Compiler version**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

**Comment by lissyx** [comment]
Thanks for that, but it's much more suited to discuss that on Discourse: https://discourse.mozilla.org/c/deep-speech, it's not an issue with the code, and we try to keep github issues only to track issues / features :)

**Comment by kofalt** [comment]
Thanks! I will open a topic there.
