### ISSUE TITLE
PIP installl fails on Ubuntu

### ISSUE THREAD

**Issue by mrutyu1987** [mozilla/DeepSpeech#1128]
Hi,

I am getting the following error while installing the deepspeech via PIP. It looks not able to fetch the packages. Any suggestion how to resolve this issue. 

```
desktop:~/DeepSpeech$ pip install --verbose deepspeech
Downloading/unpacking deepspeech
  Could not fetch URL https://packagecloud.io/github/git-lfs/pypi/simple/deepspeech/: 404 Client Error: Not Found
  Will skip URL https://packagecloud.io/github/git-lfs/pypi/simple/deepspeech/ when looking for download links for deepspeech
  Could not find any downloads that satisfy the requirement deepspeech
Cleaning up...
  Removing temporary dir /tmp/pip_build_mjay...
No distributions at all found for deepspeech
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for deepspeech
```

Regards,
MJay

**Comment by lissyx** [comment]
Thanks. This log seems completely inconsistent, you need to provide more informations on your setup @mrutyu1987, `pip` should not even try to fetch anything from `https://packagecloud.io/github/git-lfs/pypi/`, I don't even know what that URL stands for.

**Comment by mrutyu1987** [comment]
I am just following the steps mentioned: https://github.com/mozilla/DeepSpeech#prerequisites, to install python bindings.

Regards,
MJay

**Comment by lissyx** [comment]
@mrutyu1987 Obviously, you have something different on your system. Please describe your setup, I insist this URL `https://packagecloud.io/github/git-lfs/pypi/` is totally invalid, and explains by itself your issue. I have no idea where it comes from, and for sure not from steps in our documentation.

**Comment by lissyx** [comment]
Closing because it's unlikely to be an issue on our side.
