### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ShireeshPyreddy** [mozilla/DeepSpeech#1129]
Hi, i am getting message saying "Illegal instruction (core dumped)" while running the model.

(deep_speech_env) shireesh@shireesh:~/deepspeech$ deepspeech models/output_graph.pb audio/english1.wav models/alphabet.txt models/lm.binary models/trie
Illegal instruction (core dumped)

**Comment by adkarhe** [comment]
Facing same problem. @ShireeshPyreddy Have you got any solution?????

**Comment by kdavis-mozilla** [comment]
@ShireeshPyreddy Could you describe in more detail your setup and how you installed deepspeech?
