### ISSUE TITLE
Illegal Instruction (core dumped) when importing deepspeech._model

### ISSUE THREAD

**Issue by jhdulaney** [mozilla/DeepSpeech#1135]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:  No custom code

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Fedora 27 and Centos 7, both fully up to date, with distribution python packages and with those installed automatically by pip when pip installing deepspeech.  Tried python2.7 and python3
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:  Tried both, same result
- **TensorFlow version (use command below)**: ('v1.4.0-19-ga52c8d9', '1.4.1')
- **Python version**: 2.7.14
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: python -c 'import deepspeech._model' or simply run deepspeech from cli with no arguments

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by lissyx** [comment]
Likely you are running that on a system that does not supports `AVX2`/`FMA` extensions. This has already been fixed, but updated packages have not been pushed to repos, so you should just `pip uninstall` them before installing newer ones from TaskCluster: https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu or https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/gpu

**Comment by jhdulaney** [comment]
Just out of curiosity, what is an eta with a release?

**Comment by jhdulaney** [comment]
So, it looks like I am still getting the same error.

**Comment by lissyx** [comment]
@jhdulaney It would help if you gave more details on your hardware, output of `cat /proc/cpuinfo` for example.

**Comment by amirmasoud** [comment]
@lissyx 
I get the same error, output of `cat /proc/cpuinfo`:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x1
cpu MHz		: 2399.930
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb lm constant_tsc arch_perfmon nopl pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm
bugs		:
bogomips	: 4799.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by lissyx** [comment]
@amirmasoud There's not even `AVX` nor `FMA` flags there, you have to rebuild from scratch, sadly. If it's a virtual machine, make sure you have configured that properly to expose all instructions.

**Comment by amirmasoud** [comment]
@lissyx Thanks, I will give it another try

**Comment by lissyx** [comment]
@amirmasoud I just checked, it's from 2010, best you can hope is SSE4.2: https://ark.intel.com/products/47925/Intel-Xeon-Processor-E5620-12M-Cache-2_40-GHz-5_86-GTs-Intel-QPI
