### ISSUE TITLE
How to use the checkpoint?

### ISSUE THREAD

**Issue by jackHuanghello** [mozilla/DeepSpeech#1136]
7 days ago, I input this command to train the model:
`./DeepSpeech.py --train_files ./data/CV/cv-valid-train.csv,./data/CV/cv-other-train.csv --dev_files ./data/CV/cv-valid-dev.csv --test_files ./data/CV/cv-valid-test.csv --export_dir ./export_model/ --validation_step 1 --display_step 1 --checkpoint_dir /disk2/hy-dir/IDE/deepspeech-venv/deepSpeech_checkpoint/`
Then showing the "I STARTING Optimization"
after 7 days, I use the "ctrl + c" to interrupt the training process.
Then, I input the the same command to continue the training process:
`./DeepSpeech.py --train_files ./data/CV/cv-valid-train.csv,./data/CV/cv-other-train.csv --dev_files ./data/CV/cv-valid-dev.csv --test_files ./data/CV/cv-valid-test.csv --export_dir ./export_model/ --validation_step 1 --display_step 1 --checkpoint_dir /disk2/hy-dir/IDE/deepspeech-venv/deepSpeech_checkpoint/`
Then,  just showing the same sentence  "I STARTING Optimization"
Is my operation right?

**Comment by lissyx** [comment]
Training on big dataset is intensive, without details on your hardware it might juste have not completed epoch #1. You should try and test that with LDC93S1 that contains just one sample and thus trains fast.

**Comment by shunfeichen** [comment]
I also want to know how to use the checkpoint continue the train, the example of ldc93s1 is too simple.

**Comment by kdavis-mozilla** [comment]
As this is a "how to " question instead of a bug or feature request, could you please take the discussion to [Discourse](https://discourse.mozilla.org/c/deep-speech). Thanks.
