### ISSUE TITLE
The Volatile GPU-Util is very low

### ISSUE THREAD

**Issue by jackHuanghello** [mozilla/DeepSpeech#1138]
When I run the progress with CUDA supported, the GPU Util is nearly 0%.
![image](https://user-images.githubusercontent.com/21215308/34399548-36de8d10-ebc3-11e7-984b-f65db8c39c1a.png)
(I use GPU 0)

**Comment by lissyx** [comment]
There is no bug exposed here, please continue this discussion on Discourse: https://discourse.mozilla.org/t/about-the-utilization-of-cpu-and-gpu/23881, since you already opened a thread here. Github issues are only for bugs.
