### ISSUE TITLE
Accuracy of the English Pre-trained Model

### ISSUE THREAD

**Issue by The-Gupta** [mozilla/DeepSpeech#1144]
What is the absolute accuracy (error rate) of the  English pre-trained model or with respect to Google's Speech Recognition API?

Is the word error rate 6.5% as mentioned [here](https://blog.mozilla.org/blog/2017/11/29/announcing-the-initial-release-of-mozillas-open-source-speech-recognition-model-and-voice-dataset/)?

**Comment by kdavis-mozilla** [comment]
This isn't a question related to an error in the current code base. So it should be moved to our [Discourse Forum](https://discourse.mozilla.org/c/deep-speech).
