### ISSUE TITLE
Are you working on "Text to Speech"? or will you do it?

### ISSUE THREAD

**Issue by delgermurun** [mozilla/DeepSpeech#1147]
Is there anything happening on "text to speech" area?

I see there is meeting note that mentions it is future work.

Any progress on it? Thank you.

**Comment by kdavis-mozilla** [comment]
While we are starting on TTS, a STT issue isn't the best place to discuss this. I'd suggest moving the discussion to [IRC](https://github.com/mozilla/deepspeech#contactgetting-help)
