### ISSUE TITLE
16000Hz wav file restriction

### ISSUE THREAD

**Issue by pikumar** [mozilla/DeepSpeech#1150]
When the deepspeech python script generated by pip is run, which in turn runs native_client/python/client.py , there is an assumption that the input file is 16000Hz. It would be nice if the user supplies something else, the user gets an output/error instead of an empty transcription.

**Comment by lissyx** [comment]
Technically, getting an empty transcription is just a specific corner case, but it's more likely you get garbage :).

**Comment by pikumar** [comment]
@lissyx https://github.com/mozilla/DeepSpeech/pull/1151 - can you please check and merge.
