### ISSUE TITLE
Training and test data contains overly long and too short files

### ISSUE THREAD

**Issue by palles77** [mozilla/DeepSpeech#1155]
I don't know if that applies here, but I am working on using DeepSpeech in Julius and HTK. I don't use Python for training but I noticed that original data sets contain quite a few files which are way too long, such as 15 minutes for a mere few seconds of speech. Conversely there are super short files, such as 10 milliseconds which have noting in them at all. So I suggest you review the training and test data set for such files and remove them from corpus and at least the sets used in the process, as this will have quite negative effects on the outcome speech model.

**Comment by kdavis-mozilla** [comment]
@palles77 I am not sure what you are talking about Deep Speech contains no data sets.
