### ISSUE TITLE
DeepSpeech fails on CPUs without AVX support

### ISSUE THREAD

**Issue by DJ-Hayden** [mozilla/DeepSpeech#1157]
Hello,

I am running through the standard set-up and was having some trouble on the final step. It appears to be a recurring issue, but the solution I believe is provided hasn't fixed the problem, which is why I'm assuming there is a bug. Very well may be me though so I've tried to describe every step.

I'm using a MacBook Pro 10.11.6 with a 2.4 GHz Intel Core 2 Duo Processor (incredibly old).

Tensorflow has not been installed (instruction don't seem to indicate it as a prerequisite).

Python is 2.7.

I first cloned the repository, but that doesn't seem to be important for what's next. Then I downloaded and unzipped the pre-trained model.

I set up a virtual environment for deepspeech using conda. Then I activated it and ran pip install deepspeech. After installation I ran:

```
deepspeech location_of_downloaded_pretrained_model.pb location_of_sound.wav
```

This immediately got the "Illegal instruction: 4" and the code stopped. 

After a bit of searching it seems like the problem is AVX2/FMA as documented here (https://github.com/mozilla/DeepSpeech/issues/1057) and here (https://github.com/mozilla/DeepSpeech/issues/1023).

The consensus seemed to be to go to https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/osx and select deepspeech-0.1.0-cp27-cp27m-macosx_10_10_x86_64.whl (since I'm running python 2.7 with an old Mac).

Then, I uninstalled the current deepspeech with:

```
pip uninstall deepspeech 
```

and ran:

```
pip install deepspeech-0.1.0-cp27-cp27m-macosx_10_10_x86_64.whl 
```
while in a folder that contained that file.

Seemed to work, but then I ran:

```
deepspeech location_of_downloaded_pretrained_model.pb location_of_sound.wav
```

once more and it still gives me the error "Illegal instruction: 4" and the code stopped. 

Have I done something wrong here or is this still a bug?

**Comment by reuben** [comment]
The steps you followed seem to be correct. Maybe your CPU doesn't support some other instruction set that we compile with. Can you share more information on the CPU model? Specifically the output of this command:

```bash
sysctl -n machdep.cpu.brand_string && sysctl -n machdep.cpu.features
```

**Comment by DJ-Hayden** [comment]
Oh good, I did something right! 

I used command:

sysctl -n machdep.cpu.brand_string && sysctl -n machdep.cpu.features

and got

Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 XSAVE

Is my computer just too bad to even run this? I honestly wouldn't doubt that.

**Comment by reuben** [comment]
I suspect SSE4.2 is the culprit. Let me check.

**Comment by reuben** [comment]
I was wrong, it's AVX, which your CPU does not support. Your best bet is building the bindings from source. The process is documented here: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md

**Comment by DJ-Hayden** [comment]
To be clear, I need to follow the "Build Requirements" portion and skip the first sections "Installation, Required Dependencies, Installing the language bindings, Node.JS bindings"?

**Comment by reuben** [comment]
Exactly!

**Comment by DJ-Hayden** [comment]
Okay, a few hours of troubleshooting and I'm stuck again.

First, I followed these instructions: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md and https://www.tensorflow.org/install/install_sources

Namely, downloaded the DeepSpeech repository, bazel, TensorFlow Python dependencies, etc up to (and including) "Configure the installation" on the https://www.tensorflow.org/install/install_sources website.

Then I put both DeepSpeech and tensorflow-master in the same directory. Tensorflow-master is the direct download from the DeepSpeech website, so it contains a folder named tensorflow as well.

Within tensorflow-master, I ran:

ln -s ../DeepSpeech/native_client ./

then ran:

bazel build -c opt --copt=-O3 //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie

Which failed.

I tried it again by cd'ing into the tensorflow folder within the tensorflow-master folder and ran:

bazel build -c opt --copt=-O3 //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie

That failed too. The error message is: 

ERROR: (path stuff)/local_config_sycl/sycl/BUILD:4:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /(path stuff)/local_config_sycl/sycl/BUILD:6:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /(path stuff)/local_config_sycl/sycl/BUILD:30:9: Traceback (most recent call last):
	File "/(path stuff)/local_config_sycl/sycl/BUILD", line 27
		cc_library(name = "syclrt", srcs = [sycl_libr...")], <3 more arguments>)
	File "/(path stuff)/local_config_sycl/sycl/BUILD", line 30, in cc_library
		sycl_library_path
name 'sycl_library_path' is not defined
ERROR: /(path stuff)/local_config_sycl/sycl/BUILD:39:1: Target '@local_config_sycl//sycl:using_sycl' contains an error and its package is in error and referenced by '@local_config_sycl//sycl:sycl'
ERROR: /(other path stuff)/tensorflow-master/third_party/eigen3/BUILD:20:1: Target '@local_config_sycl//sycl:sycl' contains an error and its package is in error and referenced by '//third_party/eigen3:eigen3'
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: Loading failed
INFO: Elapsed time: 80.050s
FAILED: Build did NOT complete successfully (34 packages loaded)

**Comment by lissyx** [comment]
@DJ-Hayden can you make sure you used our tensorflow: https://github.com/mozilla/tensorflow ? And Bazel 0.5.4 ? Besides, `bazel build` should be done in the tensorflow directory, as you did :)

**Comment by cahya-wirawan** [comment]
@DJ-Hayden I had the same problem with my old MBP, I didn't compile my self but I installed it as follow:
`pip install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.osx/artifacts/public/deepspeech-0.1.0-cp27-cp27m-macosx_10_10_x86_64.whl`
(maybe you need also the option --upgrade if you already installed deepspeech)

**Comment by DJ-Hayden** [comment]
@lissyx Ah shoot, I definitely

**Comment by DJ-Hayden** [comment]
My new steps are:

1) Download DeepSpeech and Mozilla's fork of tensorflow. Place DeepSpeech within tensorflow-master folder (not the tensorflow folder within tensorflow-master)

2) Install mozilla's version of tensowflow by using https://www.tensorflow.org/install/install_sources#PrepareMac
2a) install bazel 0.5.4 using https://docs.bazel.build/versions/master/install-os-x.html (Installing using binary installer)
2b) use export PATH="$PATH:$HOME/bin" to let PATH know where bazel is
2c) pip install six numpy wheel (which just confirms I have these installed)
2d) cd into tensorflow-master folder from mozilla's version of tensorflow to run ./configure; again say no to literally everything; I noticed that this never really asks where bazel is but I think 2b takes care of that

3a) cd into actual tensorflow folder (within the tensorflow-master folder) and check that cd ../DeepSpeech/native_client ./ correctly gets me to the native_client folder within DeepSpeech
3b) cd back into actual tensorflow folder (within the tensorflow-master folder) and run ln -s ../DeepSpeech/native_client ./ to create an alias which alerts subsequent programs that’s where to find DeepSpeech

4) run:
bazel build -c opt --copt=-O3 //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie
and get:
ERROR: no such package 'native_client': BUILD file not found on package path.

I'm doing something obviously wrong here but  cd ../DeepSpeech/native_client ./ works fine, so I'm not sure why the alias isn't working at step 4). I thought I may need to run the ./configure with DeepSpeech already in the folder with tensorflow-master (instead of after, like I initially did), but doing that returned the same error.

**Comment by lissyx** [comment]
@DJ-Hayden Can you make sure the symlink is good? It's possible GNU / BSD `ln -s` have different behaviors.

**Comment by DJ-Hayden** [comment]
@lissyx double-clicking on it within finder correctly takes me to the native_folder within DeepSpeech. It does already contain quite a bit of files so I'm not sure if that's the problem or not.

**Comment by lissyx** [comment]
@DJ-Hayden I'd prefer `ls -hal` and `ls -hal native_client/` inside your tensorflow dir

**Comment by DJ-Hayden** [comment]
@lissyx ls -hal lists many things including 
lrwxr-xr-x   1 <user> staff    27B Jan  8 10:54 native_client -> ../DeepSpeech/native_client

and ls -hal native_client/ lists many things, all of which are in the /DeepSpeech/native_client folder

**Comment by reuben** [comment]
I think your folder structure is incorrect. It should be:

```
DeepSpeech
  - DeepSpeech.py
  - native_client
  - etc.
mozilla-tensorflow
  - tensorflow
  - tools
  - native_client -> ../DeepSpeech/native_client
  - etc.
```

You should invoke `bazel` from the root of the mozilla-tensorflow repository, aka `cd mozilla-tensorflow`, not `cd mozilla-tensorflow/tensorflow`.

**Comment by DJ-Hayden** [comment]
@reuben I thought that's what I was originally doing, but perhaps I got one of the steps slightly wrong. It is now running (albeit with a large swathe of warnings related to:

"unused typedef 'VerifySizesAreEqual' [-Wunused-local-typedef]
  typedef char VerifySizesAreEqual[sizeof(Dest) == sizeof(Source) ? 1 : -1]"

and:

"in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in <path>/tensorflow-master/tensorflow/tensorflow.bzl:1064:30"

There's quite a few other warnings (too many to list) but nothing has broken yet. It has been a few hours and it says " [2,405 / 2,410] Still waiting for 2 jobs to complete: " but that number has been increasing as the code runs. Once finished I'll cd into the DeepSpeech/native_client directory and run make deepspeech.

Once that is done, should I do the source activate deepspeech-venv, cd to where deepspeech is in the native_client directory, then run the prebuilt model command? Or does the command "make deepspeech" effectively do the same as pip install deepspeech such that I can just run deepspeech from any folder within the console?

**Comment by DJ-Hayden** [comment]
The bazel build finished. 

I then tried to make deepspeech but it didn't recognize the directory initially. I looked at the makefile and it seems it's hardcoded as tensorflow/tensorflow and not tensorflow-master/tensorflow. I changed my tensorflow-master folder to tensorflow and reran make deepspeech in the appropriate place. It then said sox.h wasn't installed, so I did brew install sox.

After that, it gave the following error:

/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
client.cc:117:23: warning: 'tmpnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent
      in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
  char* output_name = tmpnam(NULL);
                      ^
/usr/include/stdio.h:276:7: note: 'tmpnam' has been explicitly marked deprecated here
char    *tmpnam(char *);
         ^
1 warning generated.
ld: warning: directory not found for option '-L/<path>/tensorflow/bazel-bin/tensorflow'
ld: library not found for -ldeepspeech
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [deepspeech] Error 1

I feel like we're really close, but there's something wrong. Those pathway warning are correct in that they are not found in the directory.

**Comment by reuben** [comment]
Looks like $TFDIR is pointing to the wrong place. Did you set it?

**Comment by DJ-Hayden** [comment]
I didn't set it, but my_path/tensorflow(previously tensorflow-master)/bazel-bin only contains a reference to native_client, not tensorflow, as the directory not found for option error "option '-L/my_path/tensorflow/bazel-bin/tensorflow'" would suggest.

**Comment by reuben** [comment]
Weird… You should have a `bazel-bin/tensorflow` as a result of building libtensorflow_cc and libtensorflow_framework.

**Comment by DJ-Hayden** [comment]
Ah, that sounds like the topic of a lot of warnings I was getting. The very first thing that came up (as mentioned above) is:

my_path/tensorflow/tensorflow/core/BUILD:1784:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in my_path/tensorflow/tensorflow/tensorflow.bzl:1064:30.

Good news is that I just received a new Asus that will be running Ubuntu, so that's one way to solve the problem.

**Comment by reuben** [comment]
Can you try building again? Things should be in cache this time so should not take as long. Hopefully that'll create the binaries normally. I see that warning on my system as well, but it doesn't break the build.

**Comment by DJ-Hayden** [comment]
Doing that now. Still a lot of warnings along the lines of:

"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/darwin_x86_64-opt/bin/external/protobuf_archive/libprotobuf_lite.a(arenastring.o) has no symbols"

I'll monitor other warnings and see if any are specifically about libtensorflow_cc

**Comment by DJ-Hayden** [comment]
Finally finished. The last lines are:

INFO: From Linking tensorflow/libtensorflow_cc.so:
clang: warning: argument unused during compilation: '-pthread

There were a number of warnings related to:

INFO: From Linking tensorflow/cc/libcc_ops_internal.lo:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/darwin_x86_64-opt/bin/tensorflow/cc/libcc_ops_internal.lo(audio_ops_internal.o) has no symbols

**Comment by DJ-Hayden** [comment]
Oh, and when trying to make deepspeech, I get the following error:

Undefined symbols for architecture x86_64:
  "_sox_add_effect", referenced from:
      _main in client-ebd38b.o
  "_sox_close", referenced from:
      _main in client-ebd38b.o
  "_sox_create_effect", referenced from:
      _main in client-ebd38b.o
  "_sox_create_effects_chain", referenced from:
      _main in client-ebd38b.o
  "_sox_delete_effects_chain", referenced from:
      _main in client-ebd38b.o
  "_sox_effect_options", referenced from:
      _main in client-ebd38b.o
  "_sox_find_effect", referenced from:
      _main in client-ebd38b.o
  "_sox_flow_effects", referenced from:
      _main in client-ebd38b.o
  "_sox_init", referenced from:
      _main in client-ebd38b.o
  "_sox_open_read", referenced from:
      _main in client-ebd38b.o
  "_sox_open_write", referenced from:
      _main in client-ebd38b.o
  "_sox_quit", referenced from:
      _main in client-ebd38b.o
ld: symbol(s) not found for architecture x86_64

**Comment by cahya-wirawan** [comment]
@DJ-Hayden did you try to use python 3.5 and install deepspeech from taskcluster? because this is what I have in my old MBP and it works fine without recompiling anything which is very cumbersome as you see.

**Comment by reuben** [comment]
Can you try doing `brew install pkg-config` and then retrying `make deepspeech`?

**Comment by DJ-Hayden** [comment]
Last night I ran:

brew install libtool
brew install wget
brew install automake
brew install autoconf

and this morning I ran: 

brew install pkg-config
make deepspeech (when in the native client folder)

It seemingly worked, so I ran (when in the native client folder):

/my_path/DeepSpeech/native_client/deepspeech cd ../models/output_graph.pb cd ../models/vox-machina.wav cd ../models/alphabet.txt cd ../models/lm.binary models/trie

It states: 

dyld: Library not loaded: @rpath/libdeepspeech.so
  Referenced from: /my_path/DeepSpeech/native_client/deepspeech
  Reason: image not found
Trace/BPT trap: 5

**Comment by lissyx** [comment]
@DJ-Hayden Can you post you build commands? It seems you have some empty library name. `otool -L deepspeech` would help also. The `deepspeech` make target should take care of proper renaming: https://github.com/mozilla/DeepSpeech/blob/a03604d0847b9c190ecc8b2a21c622c3559b4f42/native_client/Makefile#L23-L27

**Comment by DJ-Hayden** [comment]
Sure thing!

otool -L deepspeech
deepspeech:
	@rpath/libdeepspeech.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libdeepspeech_utils.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtensorflow_cc.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtensorflow_framework.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/sox/lib/libsox.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

and build was the standard:

bazel build -c opt --copt=-O3 //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie

(which ran with a plethora of warnings)

**Comment by lissyx** [comment]
@DJ-Hayden Can you use proper formatting? it's really strange that you have only `.so`, that should not even happen, but I cannot tell if it's not just Github reformatting your input. 

Also, we need your `make` statement.

**Comment by DJ-Hayden** [comment]
@lissyx Wasn't sure how, but now I see it and am editing all of my previous comments. 

My make statement was simply

```
make deepspeech
```

while in the native_client folder

**Comment by lissyx** [comment]
@DJ-Hayden Ok, that makes more sense now. It's just that you need to help `dyld` locate your libraries. Please use `ARGS="../models/output_graph.pb ../models/vox-machina.wav ../models/alphabet.txt ../models/lm.binary models/trie" make run`

**Comment by DJ-Hayden** [comment]
Awesome, thanks so much! I think it's finally working. I ran:

```
ARGS="../models/output_graph.pb ../models/vox-machina.wav ../models/alphabet.txt ../models/lm.binary models/trie" make run
```
which output:
```
DYLD_LIBRARY_PATH=/my_path/tensorflow/bazel-bin/tensorflow:/Users/my_path/tensorflow/bazel-bin/native_client: ./deepspeech ../models/output_graph.pb ../models/vox-machina.wav ../models/alphabet.txt ../models/lm.binary models/trie
2018-01-09 11:44:41.342291: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1

Error: Can't parse trie file, invalid header. Try updating your trie file.
input: multi-channel effect drained asymmetrically!

a obbushdtatsunshsenhamsohimestofarerermsholtfromtolthebdromsouwolddre

```

I presume "a obbushdtatsunshsenhamsohimestofarerermsholtfromtolthebdromsouwolddre" is the output, which I believe was due to the minute-long file I used and seems to be a known issue with longer files. I'll try a shorter five second version. 

In the future, will I need to do:

```
ARGS="../models/output_graph.pb ../models/my_audio.wav ../models/alphabet.txt ../models/lm.binary models/trie" make run
```

For every piece of audio I'd like to run? Or now that I've "made" it can I go back to the documented way of:

```
/my_path/DeepSpeech/native_client/deepspeech cd ../models/output_graph.pb cd ../models/my_audio.wav cd ../models/alphabet.txt cd ../models/lm.binary models/trie
```

**Comment by lissyx** [comment]
@DJ-Hayden Either you continue to `make run`, or you copy the libraries altogether with the `deepspeech` binary :). Everything looks like so far it's working as expected. You might be hitting issue #1156 as a side effect related to your parsing error about the trie file. At the same time, it seems you should rebuild (sorry, but the long `bazel build`) with `-march=native` added, since you have the warning about `SSE4.1`.

I guess you can close the issue now :)

**Comment by DJ-Hayden** [comment]
@lissyx @reuben Thanks for all the help! When configuring I did use ```-march=native```, but maybe that got lost in translation somewhere. I can rebuild that later.

For now though, before I close the issue, how would I go about copying the libraries with the deepspeech binary? I'm at a bit of a loss as to why, in the native folder:

```
ARGS="../models/output_graph.pb ../models/my_audio.wav ../models/alphabet.txt ../models/lm.binary models/trie" make run
```
works but:

```
/my_path/DeepSpeech/native_client/deepspeech cd ../models/output_graph.pb cd ../models/my_audio.wav cd ../models/alphabet.txt cd ../models/lm.binary models/trie
```

doesn't.

**Comment by lissyx** [comment]
Just pick (`cp`):
```
	@rpath/libdeepspeech.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libdeepspeech_utils.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtensorflow_cc.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtensorflow_framework.so (compatibility version 0.0.0, current version 0.0.0)
```

From `$TFDIR/bazel-bin/native_client` and `$TFDIR/bazel-bin/tensorflow`

Regarding `-march`, it seems you have to add it manually again when you issue `bazel build`:
```
$ bazel build -c opt --copt=-O3 --copt=-march=native [...]
```

**Comment by DJ-Hayden** [comment]
Sweet, thanks again for all the help!

**Comment by jehoshua7** [comment]
@DJ-Hayden - I'm having a few problems with doing the build and saw at https://github.com/mozilla/DeepSpeech/issues/1157#issuecomment-356010095 , you listed the instructions. Do you have an updated set of instructions please ?
