### ISSUE TITLE
 TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

### ISSUE THREAD

**Issue by crazygirl1992** [mozilla/DeepSpeech#1159]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

**Comment by kdavis-mozilla** [comment]
Can you please provide a bit more information on what you are doing, in particular fill out the issue template.

**Comment by crazygirl1992** [comment]
thank you for your reply, i run the deepspeech.py,this error found,but when i use ldc93s1 data,the error is disappeared.  maybe the data format is error .the original data is cv-corpus-1,i download and extract it, i process the data with import_cv.py,but the data without  any different from the original data,the run  import_cv.py  
result as follows:
Found archive "/home/cww/deepspeechdataset/cv_corpus_v1.tar.gz" - not downloading.Found directory "/home/cww/deepspeechdataset/cv_corpus_v1.tar.gz" - not extracting it from archive.
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-other-test.csv".
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-other-train.csv".
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-valid-train.csv".
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-invalid.csv".
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-valid-dev.csv".
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-other-dev.csv".
/home/cww/deepspeechdataset/cv_corpus_v1
Found CSV file "/home/cww/deepspeechdataset/cv_corpus_v1" - not importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-valid-test.csv".

Process finished with exit code 0

**Comment by tilmankamp** [comment]
@crazygirl1992 The log of your `import_cv.py` call indicate a repeated import on the same directory which results in this kind of output.
The `numpy.float64 found` could come from a flaw that we should've fixed already - I'll look for the issue...

**Comment by tilmankamp** [comment]
@crazygirl1992 Could you do a fresh import (deleting the import directory and all its contents) and a test run using our current master?

**Comment by crazygirl1992** [comment]
sorry,i cant understand ,if delete the directory ,the code cant run,
 if __name__ == "__main__":
    _download_and_preprocess_data('/home/cww/deepspeechdataset')
and
 _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[0]))
i change the source_csv[-1]to source_csv[0]

**Comment by tilmankamp** [comment]
Sorry, I should've said "delete all contents within the import directory".

**Comment by crazygirl1992** [comment]
if i dont change the code,just ready a directory,the error is:
No CSV file "/home/cww/deepspeechdataset/cv-other-test.csv" - importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-other-test.csv"...
Importing mp3 files...
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
Traceback (most recent call last):
This install of SoX cannot process .mp3 files.
  File "/home/cww/DeepSpeech-master/bin/import_cv.py", line 152, in <module>
    _download_and_preprocess_data('/home/cww/deepspeechdataset')
  File "/home/cww/DeepSpeech-master/bin/import_cv.py", line 38, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "/home/cww/DeepSpeech-master/bin/import_cv.py", line 81, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1]))
  File "/home/cww/DeepSpeech-master/bin/import_cv.py", line 124, in _maybe_convert_set
    pool.map(one_sample, samples)
  File "/home/cww/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/cww/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
sox.core.SoxError: Stdout: 
Stderr: sox FAIL formats: no handler for file extension `mp3'

**Comment by tilmankamp** [comment]
Looks OK - however: You have to install mp3 support for SoX. Which OS are you using?

**Comment by crazygirl1992** [comment]
ubuntu16.4, and i have installed the sox with conda

**Comment by crazygirl1992** [comment]
can you train using the cv_corpus_v1 or your self data,i can run the sample of the ldc93s1.sh @tilmankamp

**Comment by tilmankamp** [comment]
The python package `sox` is just a wrapper around the SoX installation of the OS.
For Ubuntu, you can install mp3 support for SoX like this: `sudo apt install libsox-fmt-mp3`.

**Comment by tilmankamp** [comment]
We already trained with the CV data.

**Comment by crazygirl1992** [comment]
ok,when you process your cv data to train,what difference from original data?and do you change the code of import_cv.py? i guess i cant train with cv data maybe the data preprocess .and can you tell me
where  your training data directory ,thank you for your reply!! @tilmankamp

**Comment by tilmankamp** [comment]
@crazygirl1992 So far we were able to use the data exactly in the way the README describes. There should be no need to alter code or data after the import.

**Comment by crazygirl1992** [comment]
o.thank you,can you tell me whether your cv data .mp3 convert to  .wav before training @tilmankamp

**Comment by tilmankamp** [comment]
The wav files are automatically converted during import.

**Comment by lissyx** [comment]
@crazygirl1992 Is this still an issue ?

**Comment by lissyx** [comment]
This is usually a symptom of a number in a transcription, and no answer for months now. Closing.
