### ISSUE TITLE
DeepSpeech/native_client/kenlm/lm/common/model_buffer.cc:10:29: fatal error: util/stream/io.hh: No such file or directory

### ISSUE THREAD

**Issue by levi-2018** [mozilla/DeepSpeech#1161]
Hi, when I was compiling the source files, there occurs an error as follow. How should I fix it?

DeepSpeech/native_client/kenlm/lm/common/model_buffer.cc:10:29: fatal error: util/stream/io.hh: No such file or directory
 #include "util/stream/io.hh"
compilation terminated.
make[2]: *** [lm/CMakeFiles/kenlm.dir/common/model_buffer.cc.o] Error 1
make[1]: *** [lm/CMakeFiles/kenlm.dir/all] Error 2
make: *** [all] Error 2

**Comment by lissyx** [comment]
@levi-2018 Can you give more details on your setup and the steps you are following?

**Comment by levi-2018** [comment]
I downloaded the source project from https://github.com/mozilla/DeepSpeech.git. Then I created a build directory with the path Deep_Speech/DeepSpeech/native_client/kenlm/build and executed the command 'cmake ..'.  At the first time, there is an error as follows:

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   system
--   thread
--   unit_test_framework
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET)        
CMake Error at util/CMakeLists.txt:58 (add_subdirectory):
  add_subdirectory given source "stream" which is not an existing directory.
CMake Error at lm/CMakeLists.txt:44 (add_subdirectory):
  add_subdirectory given source "builder" which is not an existing directory.
CMake Error at lm/CMakeLists.txt:45 (add_subdirectory):
  add_subdirectory given source "filter" which is not an existing directory.
-- Could NOT find Eigen3 (missing:  EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
CMake Warning at lm/interpolate/CMakeLists.txt:65 (message):
  Not building interpolation.  Eigen3 was not found.
-- To install Eigen3 in your home directory, copy paste this:
export EIGEN3_ROOT=$HOME/eigen-eigen-07105f7124f9
(cd $HOME; wget -O - https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2 |tar xj)
rm CMakeCache.txt
-- Configuring incomplete, errors occurred! 

In order to solve this error, I added there directories,  util/stream, lm/builder, lm/filter. Then there was no error in the process of cmake.

However, when i executed the command 'make', there was an error like this.
DeepSpeech/native_client/kenlm/lm/common/model_buffer.cc:10:29: fatal error: util/stream/io.hh: No such file or directory
#include "util/stream/io.hh"
compilation terminated.
make[2]: *** [lm/CMakeFiles/kenlm.dir/common/model_buffer.cc.o] Error 1
make[1]: *** [lm/CMakeFiles/kenlm.dir/all] Error 2
make: *** [all] Error 2

**Comment by lissyx** [comment]
@levi-2018 What are you trying to do by issuing `cmake` ? Where in the documentation did you found anything related to that ?

There is nothing to do with `cmake`, please read carefully `README.md` and `native_client/README.md`, this error is irrelevant.

**Comment by cahya-wirawan** [comment]
@lissyx actually cmake is mentioned in Readme.md of kenlm directory: https://github.com/mozilla/DeepSpeech/blob/8818874217bb5f4e1bd1aeeae23efd336fce87f9/native_client/kenlm/README.md
So, if I try to build kenlm, I get the same error message as described above by levi-2018. 
I can build kenlm if I clone kenlm directly from  https://github.com/kpu/kenlm.

**Comment by lissyx** [comment]
@cahya-wirawan Yes, this is expected. Don't build KenLM from our sub directory.

**Comment by HackInvent** [comment]
@lissyx if we need to build KenLM from kpu's repo, what is the rational for putting KenLM in Deepspeech repo?

**Comment by lissyx** [comment]
We imported part of what we need from KenLM for building the language model's usage in libdeepspeech
