### ISSUE TITLE
Cannot cast array data from dtype('float32') to dtype('int16') according to the rule 'safe'

### ISSUE THREAD

**Issue by testphys** [mozilla/DeepSpeech#1170]
I simply installed deepspeech using pip and run into the following error.

`    return _model.Model_stt(self, aBuffer, aSampleRate)
TypeError: Cannot cast array data from dtype('float32') to dtype('int16') according to the rule 'safe'`

**Comment by kdavis-mozilla** [comment]
`pip install deepspeech` gave this error?

Or did you run some other command?

**Comment by testphys** [comment]
The error occures when running the pretrained model with a audio file which is not in the int16 format.
