### ISSUE TITLE
I want I want to step-by-step DBG,and libdeepspeech.so file does not have debugging information,I want to recompile，but not.How to compile it,

### ISSUE THREAD

**Issue by Allenxiaokang** [mozilla/DeepSpeech#1171]

**Comment by reuben** [comment]
Please keep issues to bugs and feature requests. Questions should be asked in our Discourse forums: http://discourse.mozilla.org/

The build process is documented in [native_client/README.md](../blob/master/native_client/README.md#build-requirements).

**Comment by Allenxiaokang** [comment]
From  python util/taskcluster.py download the .so file is already compiled in native_client/README.md. 

yxj@yxj-PR4964GW:~/Desktop/yxj/mcd/SP_Deep/DeepSpeech/native_client$ file libdeepspeech.so
libdeepspeech.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a34fd1896ff1dcc78dc4935312df2d10bfdef8d0, not stripped.

The file is not debuggable, I had to recompile the link library.So I want to know how you compile the file.
Can you assist here?
