### ISSUE TITLE
Audio Adversarial Examples: Targeted Attacks on Speech-to-Text

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#1179]
Address adversarial attack of [Audio Adversarial Examples: Targeted Attacks on Speech-to-Text](https://arxiv.org/abs/1801.01944)

**Comment by divyanshj16** [comment]
Can you please elaborate what we need to do on this issue? 
What I guess is that we have to implement the paper.

**Comment by kdavis-mozilla** [comment]
No, this involves countering the attack of the paper.

**Comment by kdavis-mozilla** [comment]
Not going to do for now.
