### ISSUE TITLE
TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by jehoshua7** [mozilla/DeepSpeech#1181]
I had installed DeepSpeech and also a DeepSpeech server ( https://github.com/ashwan1/django-deepspeech-server ). Went to start the server and got an error message - "2018-01-17 08:21:49.120154: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)"

Apparently I need to compile TensorFlow on the same computer. Is there a list somewhere to match Kubuntu 17.10.1 and a HP Probook 4330S please ?

I did try the wheel file at https://getpocket.com/redirect?url=https%3A%2F%2Findex.taskcluster.net%2Fv1%2Ftask%2Fproject.deepspeech.deepspeech.native_client.master.cpu%2Fartifacts%2Fpublic%2Fdeepspeech-0.1.0-cp35-cp35m-manylinux1_x86_64.whl&formCheck=c926fe8ba25e2f144816b163a4aab101 , but when I went to install it, got an error message - "msg - "deepspeech-0.1.0-cp35-cp35m-manylinux1_x86_64.whl is not a supported wheel on this platform."

Here is some information on the computer that I'm using:

=========================
HP Probook 4330S

Software

Kubuntu 17.10.1
Kernel: 4.13.0-25-generic
OS Type:  64 bit

Hardware

Processors: 4 x Intel Core i5-2430M CPU @ 2.40GHz
Memory: 3.8 GiB of RAM

Each processor has max speed: 3000
Supported instruction sets:

Intel MMX
Intel SSE
Intel SSE2
Intel SSE3
Intel SSE4
====================

and the (cutdown) cpuinfo is:

flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts

AVX but no AVX2

$ gcc --version
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0

I'm new to Python, so please excuse my ignorance. When I do a "pip3 list' I can  see DeepSpeech but no TensorFlow ??  Yet if I look in the requirements.txt for DeepSpeeech, TensorFlow is there.

Have done all this in a virtual environment, so dropped out of there (deactivate) and di another "pip3 list", but still no Tensorflow showing.

**Comment by lissyx** [comment]
Thanks, however there are several things I need to comment.

The documentation of https://github.com/ashwan1/django-deepspeech-server is wrong, you don't need the `pip install -r requirements.txt` step. The message you are refering to is harmless, it just says your CPU is capable of AVX2 but it's not built. This should not be a problem. Regarding your core dump, please ensure this is actually an issue with DeepSpeech and not with this external tool. Check `README.md` and `README.md` for steps, you may want to use newer artifacts from https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu rather than from pip registry. Your error about wheel being unsupported might come from several things: outdated `pip`, mismatching wheel version for your system Python version.

Please file issue only for actual reproductible and verified issed on DeepSpeech. if you are just reaching for help, please use Discourse: https://discourse.mozilla.org/c/deep-speech

**Comment by ashwan1** [comment]
@lissyx Actually I mean to run requirements.txt of my project. But, thanks for pointing out, if it was not clear for you, it might not be for others. I fixed that. :)

**Comment by jehoshua7** [comment]
@ashwan1 - Your documentation wasn't wrong at all. I found it easy to understand. Thanks for changing it though. :)

> Actually I mean to run requirements.txt of my project. But, thanks for pointing out, if it was not clear for you, it might not be for others. I fixed that. :)

**Comment by jehoshua7** [comment]
> The message you are refering to is harmless, it just says your CPU is capable of AVX2 but it's not built. This should not be a problem. Regarding your core dump, please ensure this is actually an issue with DeepSpeech and not with this external tool.

@lissyx - An error message with "aborted" as the severity is not a harmless message. The content of the message doesn't say that "the CPU is capable of AVX2". It states that - "The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.", which means that the CPU is **NOT** capable of AVX2. That was also confirmed in the cpuinfo, where the flag for AVX was present, but the flag for AVX2 was not present.

> Regarding your core dump, please ensure this is actually an issue with DeepSpeech and not with this external tool

Have now run deepspeech this morning and the message appears again ..

`$ deepspeech models/output_graph.pb my_audio_file.wav models/alphabet.txt`
2018-01-19 11:24:06.998175: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)

I tried to determine the version of TensorFlow

`$ python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, `tf.VERSION)"`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

Yet Tensorflow is in the Deepspeech requirements.txt file, and the installation of Deepspeech had no errrors, as follows:

`$ pip3 install deepspeech
Collecting deepspeech
  Downloading deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl (17.1MB)
    100% |████████████████████████████████| 17.2MB 58kB/s 
Collecting scipy==0.19.1 (from deepspeech)
  Downloading scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl (48.2MB)
    100% |████████████████████████████████| 48.2MB 25kB/s 
Collecting numpy (from deepspeech)
  Downloading numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (17.2MB)
    100% |████████████████████████████████| 17.2MB 70kB/s 
Installing collected packages: numpy, scipy, deepspeech
Successfully installed deepspeech-0.1.0 numpy-1.14.0 scipy-0.19.1`

> you may want to use newer artifacts from https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu rather than from pip registry

Thanks for the link. I did try this wheel the other day - https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp35-cp35m-manylinux1_x86_64.whl

I'm using pip3 and the version is 9.0.1, and from the changelog, that appears to be the latest.

**Comment by jehoshua7** [comment]
Have been doing a bit of research on this problem. Some related links, with possibly the last one the most relevant for Ubuntu users:

https://discourse.mozilla.org/t/error-after-following-installation-steps/22578

https://github.com/tensorflow/tensorflow/issues/8037

https://github.com/tensorflow/tensorflow/issues/6896

https://github.com/triagemd/tensorflow-docker/issues/2

https://github.com/lakshayg/tensorflow-build

https://github.com/yaroslavvb/tensorflow-community-wheels/issues/26

https://github.com/yaroslavvb/tensorflow-community-wheels

https://github.com/mind/wheels

**Comment by lissyx** [comment]
@jehoshua7 I misread your AVX2 error message: this is an error that has been explained multiple times. You need to use newer artifacts from TaskCluster. On my system, ubuntu 17.10, `python3` and thus `pip3` is Python 3.6 and not 3.5. Can you make sure you are using the proper version ? Mismatching 3.5 wheel with 3.6 Python would account for your `deepspeech-0.1.0-cp35-cp35m-manylinux1_x86_64.whl is not a supported wheel on this platform`

**Comment by jehoshua7** [comment]
> On my system, ubuntu 17.10, python3 and thus pip3 is Python 3.6 and not 3.5. Can you make sure you are using the proper version ?

@lissyx - okay, that is great you have the same system. I waited for 17.10.1 as there was a CPU problem (but I don't use a Lenovo). I checked pip3 and python3 within the virtual environment and outside of it, just to be sure. Both of them are:

pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
Python 3.6.3

I then download this artifact - https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl , and then installed it

`$ pip3 install `/home/********/Downloads/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl`

Requirement already satisfied: deepspeech==0.1.0 from file:///home/********/Downloads/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl in ./lib/python3.6/site-packages
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from deepspeech==0.1.0)
Requirement already satisfied: scipy==0.19.1 in ./lib/python3.6/site-packages (from deepspeech==0.1.0)`

and then tried DeepSpeech again

`$ deepspeech models/output_graph.pb my_audio_file.wav `models/alphabet.txt`

2018-01-19 21:04:00.937657: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)`

**Comment by lissyx** [comment]
@jehoshua7 Can you try that with a clean virtualenv? We have not yet bumped version number. And you have not forced `--upgrade` nor documented any uninstall step, and the behavior is consistent with old pip-registry-AVX2 package installed and not getting overwritten: `Requirement already satisfied: deepspeech==0.1.0 from file:///home/********/Downloads/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl in ./lib/python3.6/site-packages`.

And please, until proven otherwise, this is unlikely to be a DeepSpeech code issue, so this discussion should move to Discourse, were there is already a lot of documentation for the very same issue: https://discourse.mozilla.org/c/deep-speech

**Comment by lissyx** [comment]
@jehoshua7 I do insist, there is no need for TensorFlow Python package for inference, the `requirements.txt` in our repo is just there for **training** use-case. Regarding Discourse, you should have highlighted that in the first place, because if it's not working, then it's a problem for us as well. Passwordless authentication is broken for you then. If you can join us on IRC, we could try and see what we can do.

**Comment by jehoshua7** [comment]
> I do insist, there is no need for TensorFlow Python package for inference, the requirements.txt in our repo is just there for training use-case.

@lissyx - Okay thanks. I assumed that error message was sourced from tensorflow, as the msg content had tensor flow in it.

> Regarding Discourse, you should have highlighted that in the first place, because if it's not working, then it's a problem for us as well. 

No doubt a lot of people would have attempted to 'sign up' at Discourse, and then given up. I don't give up easily. :)

> Passwordless authentication is broken for you then. If you can join us on IRC, we could try and see what we can do.

It may be caused by a number of factors. All our email goes through a server which has "MailScanner" and in the emails , all had the message link - "MailScanner has detected a possible fraud attempt from "auth.mozilla.auth0.com" claiming to be Sign in to discourse.mozilla.org". Does MailScanner (and similar tools) change the authentication link ?

Of course we **should** be having this conversation elsewhere, a forum where we can have a discourse. But that is catch-22, is it not ?  (tongue in cheek).

Another problem in the email has "The link will expire in five minutes.". Our email server is USA and I assume the one at mozilla.org is also, but some of the emails arrived too late. It needs to be 30 mins minimum.

This 'about' is well hidden - https://discourse.mozilla.org/about , but the one moderator who has an email address public has replied to my email and copied in an admin from https://discourse.mozilla.org/about , so that is a good start. Where to from here ??

Of interest is that I do have an 'account' at https://support.mozilla.org , as that has a normal registration process. Not sure where to discuss this ? I did have a mod reply to a post at https://support.mozilla.org , so that is good.

I have now actually been able to login to Discourse, **BUT** everytime I need to login, it requires the "passwordless" authentication procedure. It's still 'hit and miss' as to whether there will be another successful login.

**Comment by jehoshua7** [comment]
> Can you try that with a clean virtualenv? We have not yet bumped version number. And you have not forced --upgrade nor documented any uninstall step, and the behavior is consistent with old pip-registry-AVX2 package installed and not getting overwritten:

Have just done the clean installation, after removing the virtual environment. Same error message. Forced an upgrade, tried deepspeech again, same error message. :(

**Comment by lissyx** [comment]
@jehoshua7 Well, I don't know what is wrong. https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl works for sure on AVX-only CPUs like yours. Besides, does the error message still mentions lack of `AVX2` before abort? If so, there's something else broken somewhere, you should check with `LD_DEBUG=libs` and make sure `libtensorflow_*.so` is loaded from the right place.

**Comment by jehoshua7** [comment]
The debug commands didn't display anything extra ? Found that library, it is within the virtual environment where deepspeech is installed. Here are the terminal commands and output ..

1. Remove virtual environment

Used Dolphin and deleted /home/********/Public/Servers and all sub paths

2.  Install these packages

    python3-venv
    python3-pip
    git-lfs
    curl

3. Created /home/********/Public/Servers/django-deepspeech-server

4.  Create virtual environment and install/test deepspeech

$ python3 -m venv /home/********/Public/Servers/django-deepspeech-server

$ cd Servers/django-deepspeech-server/       
$ source bin/activate
$ pip3 install deepspeech
Collecting deepspeech
  Using cached deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy==0.19.1 (from deepspeech)
  Using cached scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy (from deepspeech)
  Using cached numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, scipy, deepspeech
Successfully installed deepspeech-0.1.0 numpy-1.14.0 scipy-0.19.1

$ deepspeech -h
2018-01-20 12:05:19.853993: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)

$ pip3 install --upgrade deepspeech                                               
Requirement already up-to-date: deepspeech in ./lib/python3.6/site-packages                                                                                                        
Requirement already up-to-date: scipy==0.19.1 in ./lib/python3.6/site-packages (from deepspeech)                                                                                   
Requirement already up-to-date: numpy in ./lib/python3.6/site-packages (from deepspeech)                                                                                           

$ deepspeech -h                                                                   
2018-01-20 12:09:28.968959: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.                                                                                                                                                                             
Aborted (core dumped)                                                                                                                                                              

$ pip3 install /home/********/Downloads/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: deepspeech==0.1.0 from file:///home/********/Downloads/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl in ./lib/python3.6/site-packages
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from deepspeech==0.1.0)
Requirement already satisfied: scipy==0.19.1 in ./lib/python3.6/site-packages (from deepspeech==0.1.0)

$ pip3 install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: deepspeech==0.1.0 from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl in ./lib/python3.6/site-packages
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from deepspeech==0.1.0)
Requirement already satisfied: scipy==0.19.1 in ./lib/python3.6/site-packages (from deepspeech==0.1.0)

$ LD_DEBUG=libs
$ deepspeech -h
2018-01-20 14:07:37.930735: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)

$ pip3 install deepspeech
Requirement already satisfied: deepspeech in ./lib/python3.6/site-packages
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from deepspeech)
Requirement already satisfied: scipy==0.19.1 in ./lib/python3.6/site-packages (from deepspeech)

$ LD_DEBUG=all
$ deepspeech -h
2018-01-20 14:11:28.851099: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)

$ ls  /home/********/Public/Servers/django-deepspeech-server/lib/python3.6/site-packages/deepspeech/lib/libtensorflow_cc.so 
/home/********/Public/Servers/django-deepspeech-server/lib/python3.6/site-packages/deepspeech/lib/libtensorflow_cc.so

**Comment by jehoshua7** [comment]
If I was running Android it would let me off with a "warning" ,..lol

// If the CPU feature isn't present, log a fatal error.
void CheckFeatureOrDie(CPUFeature feature, const string& feature_name) {
  if (!TestCPUFeature(feature)) {
#ifdef __ANDROID__
    // Some Android emulators seem to indicate they don't support SSE, so to
    // avoid crashes when testing, switch this to a warning.
    LOG(WARNING)
#else
    LOG(FATAL)
#endif
        << "The TensorFlow library was compiled to use " << feature_name
        << " instructions, but these aren't available on your machine.";
  }
}

**Comment by jehoshua7** [comment]
Several hours of going through posts on many sites, and found this one at https://github.com/mozilla/DeepSpeech/issues/1023#issuecomment-351761360

`pip install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl --upgrade`

So tried that ..

$ pip3 install https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl --upgrade
Collecting deepspeech==0.1.0 from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl
  Downloading https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl (16.2MB)
    100% |████████████████████████████████| 16.2MB 74kB/s 
Requirement already up-to-date: numpy in ./lib/python3.6/site-packages (from deepspeech==0.1.0)
Collecting scipy (from deepspeech==0.1.0)
  Downloading scipy-1.0.0-cp36-cp36m-manylinux1_x86_64.whl (50.0MB)
    100% |████████████████████████████████| 50.0MB 26kB/s 
Installing collected packages: scipy, deepspeech
  Found existing installation: scipy 0.19.1
    Uninstalling scipy-0.19.1:
      Successfully uninstalled scipy-0.19.1
  Found existing installation: deepspeech 0.1.0
    Uninstalling deepspeech-0.1.0:
      Successfully uninstalled deepspeech-0.1.0
Successfully installed deepspeech-0.1.0 scipy-1.0.0

$ deepspeech -h
usage: deepspeech [-h] model audio alphabet [lm] [trie]

Benchmarking tooling for DeepSpeech native_client.

positional arguments:
  model       Path to the model (protocol buffer binary file)
  audio       Path to the audio file to run (WAV format)
  alphabet    Path to the configuration file specifying the alphabet used by
              the network
  lm          Path to the language model binary file
  trie        Path to the language model trie file created with
              native_client/generate_trie

optional arguments:
  -h, --help  show this help message and exit

-------------------------------
What, no message ?  So my question is, was there anything that was installed/changed today that contributed to it working, or was it simply a case of obtaining/installing that wheel ?

I did 'part' perform a build today, but only got **so** far with it.

**Comment by lissyx** [comment]
@jehoshua7 It was `LD_DEBUG=libs deepspeech` that would have done something. The URL you retried is the exact same I gave you, and there was no change. However, you forced `--uograde`. Is it possible that you just installed `deepspeech` once outside of any virtual env and you kept a stale lib somewhere.

Anyway, it is all working, as I said since the begining, so nothing more to add here.

**Comment by jehoshua7** [comment]
@lissyx Thanks for the tip regards using `LD_DEBUG=libs deepspeech`

> Is it possible that you just installed deepspeech once outside of any virtual env and you kept a stale lib somewhere.

Not possible at all. This is a 'bare bones' computer and I have **only** worked within the virtual environment. If I had installed deepspeech outside of any virtual environment, then deepspeech would show. Out of those 3 python packages, the virtual environment shows:

deepspeech (0.1.0)
numpy (1.14.0)
scipy (1.0.0)

and **outside** the virtual environment, pip3 shows:

numpy (1.12.1)

and that is showing in the base system because python3-numpy is installed by default. Related post at https://stackoverflow.com/questions/42339034/python-module-in-dist-packages-vs-site-packages

> The fact that you had scipy==0.19.1 is also a huge warning that from the begining you were still relying on the wrong version. I guess it advocates for us changing the way we use versions?

Looking back through the logs I have kept for the deepspeech install, that version of scipy came from the wheel that was recommended

> $ pip3 install deepspeech
Collecting deepspeech
  Downloading deepspeech-0.1.0-cp36-cp36m-manylinux1_x86_64.whl (17.1MB)
    100% |████████████████████████████████| 17.2MB 58kB/s 
Collecting scipy==0.19.1 (from deepspeech)
  Downloading scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl (48.2MB)
    100% |████████████████████████████████| 48.2MB 25kB/s 
Collecting numpy (from deepspeech)
  Downloading numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (17.2MB)
    100% |████████████████████████████████| 17.2MB 70kB/s 
Installing collected packages: numpy, scipy, deepspeech
Successfully installed deepspeech-0.1.0 numpy-1.14.0 scipy-0.19.1

So at least we know the source of that version of scipy

> Anyway, it is all working, as I said since the begining, so nothing more to add here.

Yes, and thanks for all your help, much appreciated. I ran a small test WAV on deepspeech and the word error rate is 43.63 % , but that's another question.  :)

**Comment by jehoshua7** [comment]
@lissyx - thanks. Some things will remain a mystery. :)

**Comment by verdverm** [comment]
@jehoshua7 I install the CPU version from your last link, `pip3 install deepspeech` (no specific version) and that resolved my error
