### ISSUE TITLE
Adaptation on new dataset 

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#1193]
I was wondering how to the use the best checkpoint model on new dataset [let's say 5 hours of new data] quickly without doing a full epoch training. Freezing inner layers and just using FC doesn't help in learning. Is there any other way - just like Kaldi adapts

**Comment by lissyx** [comment]
Please take that kind of discussion on Discourse: https://discourse.mozilla.org/c/deep-speech
