### ISSUE TITLE
SoX error while extracting bin/import_cv.py

### ISSUE THREAD

**Issue by mijeongl** [mozilla/DeepSpeech#1195]
I've installed SoX from pip install -r requirements, but it gives me this error.

sh: 1: sox: not found
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

Found archive "/home/student_lm/DeepSpeech/download/cv_corpus_v1.tar.gz" - not downloading.
Found directory "/home/student_lm/DeepSpeech/download/cv_corpus_v1.tar.gz" - not extracting it from archive.

No CSV file "/home/student_lm/DeepSpeech/download/cv-valid-train.csv" - importing "/home/student_lm/DeepSpeech/download/cv_corpus_v1/cv-valid-train.csv"...
Importing mp3 files...
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
Traceback (most recent call last):
  File "bin/import_cv.py", line 143, in <module>
    _download_and_preprocess_data(sys.argv[1])
This install of SoX cannot process .wav files.
  File "bin/import_cv.py", line 37, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "bin/import_cv.py", line 72, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1]))
This install of SoX cannot process .mp3 files.
  File "bin/import_cv.py", line 115, in _maybe_convert_set
This install of SoX cannot process .wav files.
    This install of SoX cannot process .mp3 files.
pool.map(one_sample, samples)
  File "/home/student_lm/anaconda2/envs/py2/lib/python2.7/multiprocessing/pool.py", line 253, in map
This install of SoX cannot process .mp3 files.
    return self.map_async(func, iterable, chunksize).get()
  File "/home/student_lm/anaconda2/envs/py2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
This install of SoX cannot process .wav files.
sox.core.This install of SoX cannot process .wav files.
SoxErrorThis install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
: Stdout:
Stderr: /bin/sh: 1: sox: not found

This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.

**Comment by lissyx** [comment]
`sox` python package requires the `sox` binary, it seems.

**Comment by mijeongl** [comment]
@lissyx  i downloaded sox package but it does not contain the file extension mp3.

**Comment by lissyx** [comment]
@mijeongl I'm not sure to understand what you mean. Please install `sox` binary from your distribution.

**Comment by mijeongl** [comment]
I am currently using conda environment and I downloaded sox with conda install -c conda-forge sox. This and when I see the help page of sox, there is no handler for file extension mp3

**Comment by lissyx** [comment]
@mijeongl Isn't this the `sox` python wrapper? I doubt it is the sox binary. Please refer to your distribution for that.

**Comment by spyamine** [comment]
if you are on MAC OS just write this command: brew install sox
if you are on ubuntu:
sudo apt-get install sox
sudo apt-get install libsox-fmt-mp3

and hopefully you will be fine :)

**Comment by disha3** [comment]
I had the same error on ubuntu. I tried the same thing as suggested by @spyamine . It worked for me.

**Comment by yizhake** [comment]
I had the same error on same environment (virtual env, mac osx). I tried the same thing as suggested by @spyamine . It worked for me. thanks @spyamine!

**Comment by Rishabh-Maheshwari** [comment]
@spyamine What should i do i am using windows

**Comment by spyamine** [comment]
I have no idea my friend. Maybe that you should install linux on your machine. its more appropriate for Machine Learning work

**Comment by dawningo** [comment]
same error on virtualenv & ubuntu, solved by @spyamine 's solution. thanks a lot!!

**Comment by lissyx** [comment]
@spyamine Thanks, this was in fact already documented in https://github.com/mozilla/DeepSpeech/blob/c1e7244c6c6d63bd1a3610cd116b41064edbf2ed/native_client/README.md#required-dependencies :)
