### ISSUE TITLE
Model class does not unicoded string

### ISSUE THREAD

**Issue by xiaoleihuang** [mozilla/DeepSpeech#1198]
My environment:
* Ubuntu 16.04
* Virtual Env: Python 2.7.13
* Deepspeech: deepspeech-0.1.0

I loaded the paths of pretrained files as unicoded strings (utf-8), I used the strings as following:
```python
ds = Model(init_settings['deepspeech']['model_path'],
               int(init_settings['deepspeech']['N_FEATURES']),
               int(init_settings['deepspeech']['N_CONTEXT']),
               init_settings['deepspeech']['alphabet_path'],
               int(init_settings['deepspeech']['BEAM_WIDTH']))
```
One example of strings: `model_path = u'/mozilla/models/output_graph.pb'`
Then it raised errors: 
TypeError: in method 'new_Model', argument 1 of type 'char const *'

Solutions:
To use str(model_path) to convert.

Question:
Does anyone know why this happens?

**Comment by lissyx** [comment]
This is likely because libdeepspeech wants a const char *?

**Comment by lissyx** [comment]
@xiaoleihuang https://github.com/mozilla/DeepSpeech/blob/f9028aee1b3e803184497fac5d9aaf4d79c6cfd0/native_client/deepspeech.cc#L40

So that's why the module does not accept `UTF-8` string. Do you have path with unicode and this is blocking you?

**Comment by xiaoleihuang** [comment]
Thanks. I think I have solved it now as I've mentioned previously using `str(path)` to convert utf8 back to chars.

Interesting, because Python 2.7 support ends in 2020 and python 3 uses utf-8 as its default encoding. I think future modules might support utf-8 for the native client.
