### ISSUE TITLE
Documentation on build from source is unclear

### ISSUE THREAD

**Issue by David-Levinthal** [mozilla/DeepSpeech#1199]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
('v1.4.1-7-gaa03bfc', '1.4.1')
built and installed from source with
git checkout r1.4
bazel build -c opt --copt=-march="haswell" --config=cuda --verbose_failures --incompatible_load_argument_is_label=false //tensorflow/tools/pip_package:build_pip_package >pip_package_build2.log 2>&1
note: incompatible path flag is required with R1.4 at this time per #15492
ubuntu 16.04
Cuda 9.1, cudnn 7.0.4
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
uname -r
4.4.0-104-generic
Bazel 0.9
Describe the problem

Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
It is unclear how to build and install the entire package purely from source
I will attempt to log what I have done so far
clone and build TF R1.4 for cuda
install wheel into local directory (sudo pip install /tmp/tensorflow-pkg/tensorflow*.whl -t /mytf_r1.4_c9.1
export PYTHONPATH=/mytf_r1.4_c9.1
move tensorflow directory

install common_voice files to ~/Common_voice

per native client build from source instructions: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md
git clone tensorflow
cd tensorflow
git checkout r1.4
ln -s ../DeepSpeech/native_client ./
./configure
edit native_client/BUILD
comment out the following:
tfcompile_flags = select({
"//tensorflow:rpi3": str('--target_triple="armv6-linux-gnueabihf" --target_cpu="cortex-a53" --target_features="+neon-fp-armv8"'),
"//conditions:default": str('')
}),

bazel build -c opt --copt=-O3 --incompatible_load_argument_is_label=false //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //native_client:deepspeech //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie
at this point all the native client binaries are in
/tensorflow/bazel-bin/native_client
levinth@zt-gpu-lin:/DeepSpeech/native_client$ ls ~/tensorflow/bazel-bin/native_client/
generate_trie
generate_trie-2.params
generate_trie.runfiles
generate_trie.runfiles_manifest
libctc_decoder_with_kenlm.so
libctc_decoder_with_kenlm.so-2.params
libctc_decoder_with_kenlm.so.runfiles
libctc_decoder_with_kenlm.so.runfiles_manifest
libdeepspeech.a
libdeepspeech.a-2.params
libdeepspeech.pic.a
libdeepspeech.pic.a-2.params
libdeepspeech.so
libdeepspeech.so-2.params
libdeepspeech_utils.a
libdeepspeech_utils.a-2.params
libdeepspeech_utils.pic.a
libdeepspeech_utils.pic.a-2.params
libdeepspeech_utils.so
libdeepspeech_utils.so-2.params
_objs

cd ../Deepspeech/native_client
export TFDIR ~/tensorflow
make deepspeech

at this point however the native client shared objects are still in bazel-bin/native client and have not been installed. the invocation of Deepspeech.py fails as it cannot find the shared objects
python DeepSpeech.py --train_files ../Common_voice/cv-valid-train.csv,../Common_voice/cv-other-train.csv --dev_files ../Common_voice/cv-valid-dev.csv --test_files ../Common_voice/cv-valid-test.csv >deepspeech_1.log 2>&1
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: cannot open shared object file: No such file or directory

the native_client/Makefile has sections for bindings and install..so try
sudo make install
and this still generates the error as install does not put
~/tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so
into /usr/local/lib
though deepspeech.so and deepspeech_utils.so are installed there.
manually copy /tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so to ~/DeepSpeech/native_client and set permissions
at this point the invocation now starts running but complains about
WARNING: libdeepspeech failed to load, resorting to deprecated code
Refer to README.md for instructions on installing libdeepspeech

even though /usr/local/lib is in the $LD_LIBRARY_PATH

invoking
python DeepSpeech.py --train_files ../Common_voice/cv-valid-train.csv,../Common_voice/cv-other-train.csv --dev_files ../Common_voice/cv-valid-dev.csv --test_files ../Common_voice/cv-valid-test.csv --display_step 1 --validation_step 10
WARNING: libdeepspeech failed to load, resorting to deprecated code
Refer to README.md for instructions on installing libdeepspeech

I STARTING Optimization
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
what(): native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector&) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data. Byte: 43
a couple minutes after the last bit of output show above the program crashed
Aborted (core dumped)

I clearly have not figured this out
:-)

**Comment by lissyx** [comment]
Git-LFS installation is covered in https://github.com/mozilla/DeepSpeech#prerequisites

**Comment by lissyx** [comment]
Specific flag for `libctc_decoder_with_kenlm.so` is documented in:
```
python DeepSpeech.py --help
```

**Comment by lissyx** [comment]
TensorFlow's build system documents the Bazel version to 0.5.4, you are using 0.9.0, that's why you hat the stuff about incompatible path flag

**Comment by lissyx** [comment]
@David-Levinthal It's really hard to read your issue thouth, formatting is improper. Can you list explicitely where are the pain points? All I could see was already documented.

**Comment by lissyx** [comment]
For the warning about `libdeepspeech`, you need to install the python binding.

**Comment by David-Levinthal** [comment]
actually the two issues that were a bit tricky were figuring out what to
delete from native_client/BUILD and realizing that the 'make deepspeech'
was not the end..(sudo make install and manual copy of the kenlm.so library
were needed)
even after installing git-lfs with
curl -s
https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh |
sudo bash
sudo apt-get install git-lfs
I get the following output
------------------------------------------------------------------------
WARNING: libdeepspeech failed to load, resorting to deprecated code
         Refer to README.md for instructions on installing libdeepspeech
------------------------------------------------------------------------
I STARTING Optimization
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/read_arpa.cc:65 in void
lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw
FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not
\data\. Byte: 43
and core dumps

is the python binding installed with
cd ~/Deepspeech/native_client
sudo make bindings

did that and still get the same output shown above
???

**Comment by David-Levinthal** [comment]
sudo make bindings creates a python wheel in DeepSpeech/native_client/dist
which must be installed with
sudo pip install ~/Deepspeech/native_client/dist/*.whl

and the libdeepspeech warning is fixed

**Comment by lissyx** [comment]
Try to force git lfs pull and make sure the git-lfs binary is in your PATH

**Comment by lissyx** [comment]
@David-Levinthal The deletion from `native_client/BUILD` is specific to your case, there's nothing to fix here. We already document what are all the steps to get the system up and running in `README.md` and we document how to builds bits in `native_client/README.md`, can you highlight what is not clear?

**Comment by David-Levinthal** [comment]
the need for the sudo make install, explicitly copying the libctc_decoder
to native_client, make bindings, sudo pip install native_client/dist/*.whl
also I am reinstalling Common voice after installing git-lfs
the FAQ seems to say that you have to reinstall common voice after
installing git-lfs
is that not correct?   (this is going to take a while to test)

perhaps the  bin/import_cv.py script could check for the presence of
git-lfs and fail if it is not there?
The point about documenting the full build completely from source is that
for someone using prototype HW none of the premade wheels will work and
everything has to be done for the nerw HW (including TF)
having tf r1.4 in the requirements file may not be helpful
:-)

**Comment by reuben** [comment]
You don't have to copy libctc_decoder anywhere, just use the command line flag to specify where it's located on your system. `native_client/` is just the default location.

The need to do `make bindings` and installing the Wheel file from dist/*.whl is clearly documented here: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md#python-bindings

You need to have Git LFS installed before cloning the repository, that requirement is very clearly documented in the "Getting the code" section of the README: https://github.com/mozilla/DeepSpeech/blob/master/README.md#getting-the-code

TensorFlow 1.4 is our current supported version. I fail to see how helping hardware startups should be a priority for our project. We'll bump support to TF 1.5 eventually, as we'll want to use some of the stuff that's being released there. Until then, patches are welcome, and everyone is free to hack with whatever setups they have, of course.

**Comment by lissyx** [comment]
Still open to any pointer on what is unclear in our docs, but that discussion for now does not provide anything actionable. Closing, but feel free to file new, precise issues.
