### ISSUE TITLE
bash: ./generate_trie: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by phanlong95** [mozilla/DeepSpeech#1202]
when i run this code to create trie file: 
./generate_trie data/alphabet.txt data/lm.binary data/vocabulary.txt data/trie
 
error: bash: ./generate_trie: cannot execute binary file: Exec format error

**Comment by lissyx** [comment]
What is your system? What did you downloaded?

**Comment by lissyx** [comment]
Can you paste also the output of `file generate_trie`?

**Comment by phanlong95** [comment]
i build in linux 16.04 .

**Comment by lissyx** [comment]
@phanlong95 Please document exactly what you are doing and your system, "linux 16.04" is too light. I just tested both v0.1.1 and current master artifacts out of TaskCluster, and they both work as expected on my system.

**Comment by lissyx** [comment]
@phanlong95 Instead of spamming several other Github issues like you are doing: https://github.com/mozilla/DeepSpeech/issues/833#issuecomment-364060408 how about you answer my questions so we can help you ?

**Comment by lissyx** [comment]
Closing for lack of answer, spam, and the same question asked again in discourse: https://discourse.mozilla.org/t/can-we-use-deepspeech-for-vietnamese-speech-to-text/25311
