### ISSUE TITLE
Continuing training from a frozen graph - Unable to use the trained new model to predict new data

### ISSUE THREAD

**Issue by kmrambo** [mozilla/DeepSpeech#1208]
I have continued the training from frozen graph and the training completed successfully. Below is the command I used for training purpose:

`python DeepSpeech.py --n_hidden 2048 --initialize_from_frozen_model /Users/kmrambo/Deepspeech/models/output_graph.pb --checkpoint_dir fine_tuning_checkpoints --epoch 3 --train_files /Users/kmrambo/DeepSpeech-master/sampledata/cv-valid-train.csv --dev_files /Users/kmrambo/DeepSpeech-master/sampledata/cv-valid-dev.csv --test_files /Users/kmrambo/DeepSpeech-master/sampledata/cv-valid-test.csv --learning_rate 0.0001 —decoder_library_path /Users/kmrambo/Documents/GitHub/DeepSpeech/libctc_decoder_with_kenlm.so`

Now I see that the Checkpoint directory has been updated with the checkpoint files after training. Below is a snapshot of the outputs in my checkpoint directory:

<img width="1070" alt="screen shot 2018-02-06 at 2 37 04 pm" src="https://user-images.githubusercontent.com/29517231/35850613-6feda4c2-0b4b-11e8-853d-9a5b95e59338.png">

I now want to use this re-trained model to predict new data. I see that the following is the command to predict new data:

`./deepspeech models/output_graph.pb audio_input.wav models/alphabet.txt models/lm.binary models/trie`

But in the above command, I have to supply the output.pb , trie files of the re-trained model. Where do I find those files or should I follow any additional steps for those files to get generated after re-training from a frozen model?

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Sierra
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 2.7.14
- **GPU model and memory**: No GPU, Only CPU

**Comment by kdavis-mozilla** [comment]
As this is not a bug or feature request, but a discussion on use of the current codebase, could you please move this discussion to our Discourse Forms[[1](https://discourse.mozilla.org/c/deep-speech)]. Thank you.
