### ISSUE TITLE
Can we do speaker diarization using deep speech

### ISSUE THREAD

**Issue by krishnakt031990** [mozilla/DeepSpeech#1212]
Can we train a model using deep speech to recognize a speaker?

I can use my wav files for training my model and want to verify if the system can detect me.

**Comment by kdavis-mozilla** [comment]
As this is not a bug or feature request on the current code base, could you please move this discussion to our Discourse Forum[[1](https://discourse.mozilla.org/c/deep-speech)]. Thank you.
