### ISSUE TITLE
Which DeepSpeech version / paper is mozilla DeepSpeech is based on?

### ISSUE THREAD

**Issue by RadZaeem** [mozilla/DeepSpeech#1214]
Sorry I have a simple question:
Which DeepSpeech version or paper does mozilla Deep Speech is implemented with?
DeepSpeech 1 (2014) or DeepSpeech 2 (2015) or DeepSpeech 3 (2017) ?

**Comment by kdavis-mozilla** [comment]
As this is not a bug or feature request on the current code base, could you please move the discussion to our Discourse Forum[[1](https://discourse.mozilla.org/c/deep-speech)].

We try to separate bugs/feature requests, which merit GitHub issues, from discussion, which is handled in IRC or in the  Discourse Forum[[1](https://discourse.mozilla.org/c/deep-speech)].

Thanks for your understanding.
