### ISSUE TITLE
'module' object has no attribute 'ctc_beam_search_decoder_with_lm'

### ISSUE THREAD

**Issue by abuvaneswari** [mozilla/DeepSpeech#1223]
Hello,

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: from your builds
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: 4.8.5
- **CUDA/cuDNN version**: 9
- **GPU model and memory**: Tesla P100
- **Exact command to reproduce**:

I followed your instructions at:
https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md#required-dependencies
to build the libraries and deepspeech binary.

(I think you are missing an instruction that the user needs to copy the libctc_decoder_with_kenlm.so from bazel-bin/native_client directory onto DeepSpeech/native_client directory. Anyway, I just did that)

The deepspeech binary built as a result, works fine. It is able to transcribe a wav file against your distributed model.

But I am having problem when I try training. I ran the following at the dir-level of DeepSpeech:
./bin/run-ldc93s1.sh. And I get the following error message:
```
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/root/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1
Traceback (most recent call last):
  File "DeepSpeech.py", line 1861, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1818, in main
    train()
  File "DeepSpeech.py", line 1505, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 644, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
  File "DeepSpeech.py", line 537, in calculate_mean_edit_distance_and_loss
    decoded, _ = decode_with_lm(logits, batch_seq_len, merge_repeated=False, beam_width=FLAGS.beam_width)
  File "DeepSpeech.py", line 492, in decode_with_lm
    custom_op_module.ctc_beam_search_decoder_with_lm(
AttributeError: 'module' object has no attribute 'ctc_beam_search_decoder_with_lm'
```

**Comment by lissyx** [comment]
@abuvaneswari TensorFlow 1.4.0 with CUDA 9.0 / CuDNN v7 ? We have no such 1.4.0 with CUDA 9.0, so I don't see how you could install it from our builds.

Can you try forcing the path of the decoder ? `--decoder_library_path=path/to/libctc_decoder_with_kenlm.so`

Also, can you try to run with `LD_DEBUG=libs` and share it, to verify where it picks the decoder?

Can you try with `libctc_decoder_with_kenlm.so` from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.tf-master.cpu/artifacts/public/native_client.tar.xz It should be okay against a TensorFlow 1.6.0-rc0 and it works with CUDA 9 / CuDNN v7.

**Comment by reuben** [comment]
@abuvaneswari thanks for filling the issue template! 

> (I think you are missing an instruction that the user needs to copy the libctc_decoder_with_kenlm.so from bazel-bin/native_client directory onto DeepSpeech/native_client directory. Anyway, I just did that)

We should document the `--decoder_library_path` in those instructions, you're not the first one to hit this problem.

**Comment by abuvaneswari** [comment]
I downloaded https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.tf-master.cpu/artifacts/public/native_client.tar.xz

And the error message I get is now different:
python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1 --decoder_library_path=/home/buvana/downloaded_native_client/libctc_decoder_with_kenlm.so
Traceback (most recent call last):
  File "DeepSpeech.py", line 1861, in <module>
    tf.app.run()
  File "/root/tmp/deepspeech_py2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1813, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/root/tmp/deepspeech_py2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/root/tmp/deepspeech_py2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/buvana/downloaded_native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKNS_6StatusE

**Comment by lissyx** [comment]
@abuvaneswari That's because you have not switched to TensorFlow 1.6.0-rc0 :)

**Comment by abuvaneswari** [comment]
After switching to tf 1.6.0-rc0, it works with the model you provided at your website. I am still wondering how I can get bazel to build a version of libctc_decoder_with_kenlm.so that will work for me.

**Comment by lissyx** [comment]
@abuvaneswari Thanks for confirming that then. It's obviously not an issue in the code, do you mind opening a thread on discourse so we can help you? https://discourse.mozilla.org/c/deep-speech

When you make the thread, please document exactly all the steps you performed. I know you "followed the docs", but obviously there's something different :)

We use issues only for problems / features requests.

**Comment by gooofy** [comment]
Did anyone ever get to the bottom oft this? I am having the exact same issue with my libctc_decoder_with_kenlm.so:

```
Traceback (most recent call last):
  File "DeepSpeech.py", line 1841, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1793, in main
    initialize_globals()
  File "DeepSpeech.py", line 337, in initialize_globals
    foo = custom_op_module.ctc_beam_search_decoder_with_lm
AttributeError: 'module' object has no attribute 'ctc_beam_search_decoder_with_lm'

```
(this is with tensorflow 1.6.0rc1 compiled from source) however using the pre-built native_client from task cluster is not an option for me as my CPUs do not support AVX.

**Comment by lissyx** [comment]
@gooofy Please provide more context: how exactly did you built, how you are calling `DeepSpeech.py`. And please use Discourse for asking for help.

**Comment by gooofy** [comment]
@lissyx thanks for looking into this :) not sure what it is exactly that you'd like to know, but this is what I did:

first, I checked out and built tf branch r1.6 (cannot use binaries because of the AVX issue) - actually built a python wheel and installed it using pip system-wide, with cuda support.
to build the native client I followed the instructions in native_client/README.md (i.e. I cloned the mozilla version of tf, configured it and built the native client from there).

now, to test this I ran bin/run-librivox.sh where I added this option:

`  --decoder_library_path "../tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so"`

which results in:

```
[bofh@hal DeepSpeech]$ bin/run-librivox.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -d data/librivox ']'
+ '[' '!' -f data/librivox/librivox-train-clean-100.csv ']'
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/librivox"))'
+ checkpoint_dir=/home/bofh/.local/share/deepspeech/librivox
+ python -u DeepSpeech.py --train_files data/librivox/librivox-train-clean-100.csv,data/librivox/librivox-train-clean-360.csv,data/librivox/librivox-train-other-500.csv --dev_files data/librivox/librivox-dev-clean.csv,data/librivox/librivox-dev-other.csv --test_files data/librivox/librivox-test-clean.csv,data/librivox/librivox-test-other.csv --train_batch_size 12 --dev_batch_size 12 --test_batch_size 12 --learning_rate 0.0001 --epoch 15 --display_step 5 --validation_step 5 --dropout_rate 0.30 --default_stddev 0.046875 --checkpoint_dir /home/bofh/.local/share/deepspeech/librivox --decoder_library_path ../tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so
decoder library path: ../tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so
Traceback (most recent call last):
  File "DeepSpeech.py", line 1843, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1800, in main
    train()
  File "DeepSpeech.py", line 1506, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 645, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
  File "DeepSpeech.py", line 538, in calculate_mean_edit_distance_and_loss
    decoded, _ = decode_with_lm(logits, batch_seq_len, merge_repeated=False, beam_width=FLAGS.beam_width)
  File "DeepSpeech.py", line 493, in decode_with_lm
    custom_op_module.ctc_beam_search_decoder_with_lm(
AttributeError: 'module' object has no attribute 'ctc_beam_search_decoder_with_lm'

```

**Comment by gooofy** [comment]
ok, I seem to have managed to build a working `libctc_decoder_with_kenlm.so`: seems I had to replace "`--config=monolithic`" by "`--config=opt --config=cuda`" in the bazel build invocation, i.e.

```
rm -rf bazel-bin/native_client/
bazel build --config=opt --config=cuda -c opt --copt=-O3 --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:deepspeech_utils //native_client:libctc_decoder_with_kenlm.so //native_client:generate_trie

```
seems to have done the trick

**Comment by lissyx** [comment]
Thanks @gooofy. It makes sense. Can you file a new issue about fixing the doc for building ctc decoder? Aside, you should not have had to build, I think that even with AVX enabled on the build the pre-built ctc decoder should have worked. Current TaskCluster native_client.tar.xz contains some compatible with tensorflow r1.5 and tf-master branch produces current tensorflow master bins, so 1.6.0-rc1. 

Wasn't that clear in the docs? Or did you ran into issues? In either case, it would be good you file another issue so that we either fix what is not working or fix the doc: long story short, you should not have needed to rebuild, I guess :-)

**Comment by gooofy** [comment]
ah, guess I didn't try running the TaskCluster binaries once I had discovered I had to build TensorFlow myself  :o)

About the docs: apart from what @reuben suggested above (mention where the .so is to be found and how to use it via the --decoder_library_path option) it was mainly the --config=monolithic vs --config=cuda that kept me from building a useable libctc_decoder_with_kenlm.so

**Comment by twmht** [comment]
@gooofy 

how did you know the workaround ( replace `--config=monolithic" by "--config=opt --config=cuda`)?

**Comment by twmht** [comment]
I meet the same issue.

After trying the workaround from @gooofy 

I got the bazel build errors below

```
ERROR: /home/alec.tu/.cache/bazel/_bazel_alec.tu/3cdfb51aa5f382f6a0a0a9d72b84a1d3/external/protobuf_archive/BUILD:104:1: C++ compilation of rule '@protobuf_archive//:protobuf' failed (Exit 2)
python: can't open file 'external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc': [Errno 2] No such file or directory

```

Any suggestion?

**Comment by lissyx** [comment]
@twmht Your CUDA setup is incomplete / invalid. The workaround is not changing `--config=monolithic` by `--config=opt --config=cuda`, it's just building `libctc_decoder_with_kenlm.so` without `--config=monolithic` as I updated the doc in #1261.

**Comment by gooofy** [comment]
@lissyx just for the record: I tried running the taskcluster binaries on my non-AVX enabled CPUs and the result seems to confirm my suspicion that those binaries include AVX instructions as well:

```
[bofh@hal native_client]$ ARGS="../data/voxforge_de/export/output_graph.pb gsp1.wav" make run
LD_LIBRARY_PATH=/home/bofh/projects/ai/mozilla/tensorflow/bazel-bin/native_client:/home/bofh/projects/ai/mozilla/DeepSpeech/native_client:/apps/kaldi-cuda/tools/openfst/lib:/apps/kaldi-cuda/src/lib: ./deepspeech ../data/voxforge_de/export/output_graph.pb gsp1.wav
make: *** [run] Illegal instruction (core dumped)

```

**Comment by lissyx** [comment]
If you used TaskCluster-built libs then it's expected :-), you need to rebuild libdeepspeech without AVX
