### ISSUE TITLE
Support for audios with background music

### ISSUE THREAD

**Issue by moeedkundi** [mozilla/DeepSpeech#1225]
I am using this implementation of DeepSpeech on a dataset of around 600-700 audio files with background music. It appears that it can't work with such data despite efforts of suppressing music components.
**I would like to know if DeepSpeech implementation is supposed to work with narrated files with background music or not?**

**Comment by kdavis-mozilla** [comment]
It's a matter of signal to noise ratio + training data.

However, as this is not a bug or feature request, cold you move discussion of this topic to our Discourse Form[[1](https://discourse.mozilla.org/c/deep-speech)]. Thanks.
