### ISSUE TITLE
Running deepspeech- KeyError , TypeError,  frozen graph

### ISSUE THREAD

**Issue by alughaGmbH** [mozilla/DeepSpeech#1233]
Hi all,

I am following https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md to use Deepspeech. I am not able to advance. kindly clear my points. It will be a great help. 

**Issues**
---------------------------------------
1) When I am trying to train my model, the corpus which I downloaded do not have wav_filesize column in the CSV file . So it gives me 
          **KeyError**: 'wav_filesize' . 
2) I have a audio file which I am trying to run with Deepspeech- it gives me 
         **TypeError**: Cannot cast array data from dtype('float32') to dtype('int16') according to the rule 'safe'
3) If I want to train my model further, we have **Continuing training from a frozen graph** option. But I am not so clear how this is working. I can I continue with this. 
4) The audio file which I used was a 2-Dimensional it tells. So now how can I conver it into 1 dimensional.
           **TypeError**: Array must have 1 dimensions.  Given array has 2 dimensions

Thank you,
Alugha

**Comment by alughaGmbH** [comment]
I also checked **Handling audio with more than one channel? #675**  . But this could not help me.

**Comment by lissyx** [comment]
@alughaGmbH Thanks, however:
- Your KeyError is actually a dupe from #1090 
- The rest is not issues, but question. Please use Discourse for that: https://discourse.mozilla.org/c/deep-speech
