### ISSUE TITLE
Change Deep Speech architecture to allow streaming

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#1239]
Remove BRNN and explicitly loop over timesteps, each corresponding to tick in the old BRNN architecture. Also, update all the various clients to allow for this streaming interface.

**Comment by svmguru** [comment]
Any update on this? Maybe a tentative ETA?

**Comment by lissyx** [comment]
@svmguru Check #1275

**Comment by est31** [comment]
Newest PR: #1463
