### ISSUE TITLE
Keeping third-party in sync

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#1253]
We have a few third-party plugins / bindings now, yet it seems they are still targetting v0.1.0. We should aim at better cooperation, however I don't have yet a strong opinion on this. Likely that decoupling our current Python and NodeJS bindings from the main repo would help us solve and simplify the work for those third-party :).

In the meantime, I've opened issues on their repos:
 - Go: https://github.com/asticode/go-astideepspeech/issues/1
 - Rust: https://github.com/RustAudio/deepspeech-rs/issues/1
 - G-Streamer: https://github.com/Elleo/gst-deepspeech/issues/1
 - ArchLinux: https://github.com/stes/arch-deepspeech/issues/1

**Comment by asticode** [comment]
Hey guys, I've developed the GO bindings and I've to say it's a great idea to at least try to find a way to keep bindings in sync.

As far as I'm concerned, creating an issue in each repos everytime there's a release is perfect even though I doubt you'll be able to keep doing that in the future as you may forget to do it.

And moving Python/NodeJS bindings into other repos may help other languages bindings as it would stop anybody from coupling stuff too much in the main repo.

Once again, great initiative!

**Comment by lissyx** [comment]
@asticode Thanks for your feedback. I'm going to close this issue because the work it was tracking, ensuring people are up to date with us for v0.1.1 / v0.2.0 is completed. I'd invite you (and others) to start the discussion regarding further improvements to our interactions with upstream on Discourse: https://discourse.mozilla.org/c/deep-speech

Thanks !
