### ISSUE TITLE
Erro installing DeepSpeech python bindings

### ISSUE THREAD

**Issue by Macha-Pujitha** [mozilla/DeepSpeech#1257]
**On Ubuntu while i was trying to run** 
deepspeech models/output_graph.pbmm models/alphabet.txt models/lm.binary models/trie my_audio_file.wav

**It's giving the following error**

Loading model from file models/output_graph.pbmm
2018-02-17 13:55:39.481842: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: models/output_graph.pbmm; No such file or directory
Loaded model in 4.661s.
Loading language model from files models/trie my_audio_file.wav
Loading the LM will be faster if you build a binary file.
Reading models/trie
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "1414678853" not \data\. Byte: 11
Aborted (core dumped)

**Comment by lissyx** [comment]
Hello,

Currently released model is not including the  mmap able file, you should use `output_graph.pb` :-).
Also the order of the arguments changed, please check the readme from the tag v0.1.1 and not from master branch :-)

**Comment by lissyx** [comment]
Feel free to reopen the issue if you find it's not working. If the doc is not clear or accurate please file a new issue. For any discussion or more of help request please use discourse :-).

**Comment by jenniferzhu** [comment]
@lissyx I got the same issue with v0.1.1. Can you please point me to the right README for v0.1.1?

> $ deepspeech models/output_graph.pb models/alphabet.txt models/lm.binary models/trie audio/8455-210777-0068.wav 
Loading model from file models/output_graph.pb
2018-04-03 13:37:39.513061: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error: Alphabet size does not match loaded model: alphabet has size 3349619, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loaded model in 16.747s.
Loading language model from files models/trie audio/8455-210777-0068.wav
Loading the LM will be faster if you build a binary file.
Reading models/trie
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
libc++abi.dylib: terminating with uncaught exception of type lm::FormatLoadException: native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece &, std::vector<uint64_t> &) threw FormatLoadException.
first non-empty line was "1414678853" not \data\. Byte: 11
Abort trap: 6

**Comment by lissyx** [comment]
@jenniferzhu https://github.com/mozilla/DeepSpeech/blob/v0.1.1/README.md ?
