### ISSUE TITLE
calculate_wer only runs for first batch per CPU

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#126]

**Comment by tilmankamp** [comment]
Automatically solved, once #108 gets merged.

**Comment by kdavis-mozilla** [comment]
Just a heads up.

After you left on Friday @lissyx and I looked at the graphs he's been producing and realized that the WER calculation that occurs on the last batch after each epoch is slow.

Quantitatively, looking at the graph for issue #187 one sees that the WER for one batch takes about 120 seconds, or 2 minutes. From the GPU usage from issue #187 one can also see that this happens on the CPU.

So with the changes of _this_ issue, we now calculate the WER for each batch of the training set. For the TED data set there are 2906 batches of 32 items. So, the WER calculation will take 2906*2=5812 minutes. In other words, 96 hours! (The WER is done on the CPU and can't be parallelized like a GPU calculation could.)

So all of this implies that the WER calculation should be moved to the GPU. I don't think that this movement to the GPU should be part of this issue, but it should happen as part of issue #187. However, I want to give you a heads up that running the fix of this on the server will be very slow, likely  around 4 days for one epoch.

**Comment by tilmankamp** [comment]
Fixed by https://github.com/mozilla/DeepSpeech/commit/d4beb748b93f2f2e10f0415b913693cdaaa7b1c4 .
