### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ramialbatal** [mozilla/DeepSpeech#1267]
Hi, I am not trying to run the ./bin/run-ldc93s1.sh directly without compiling the from the source code.

Here are the information of my system and machine:

- **OS Platform and Distribution**: Linux Ubuntu 16.04.1
- **TensorFlow installed from**: upstream
- **TensorFlow version**: ('v1.3.0-rc2-20-g0787eee', '1.3.0'), tensorflow-gpu (1.3.0)
- **Python version**: 2.7.12
- **CUDA/cuDNN version**: CUDA 8.0.61
- **GPU model and memory**: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 8GB memory
- **Exact command to reproduce**: ./bin/run-ldc93s1.sh

I have installed the native client as described [here](https://github.com/mozilla/DeepSpeech/tree/master/native_client), and I am getting the following error once I try to run ./bin/run-ldc93s1.sh, and I am unable to figure-out the reason.

```
(deepspeech-virtualenv) me@my-gpu:~/DeepSpeech$ ./bin/run-ldc93s1.sh 
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/rami/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/rami/.local/share/deepspeech/ldc93s1
Traceback (most recent call last):
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/home/rami/.virtualenvs/deepspeech/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1790, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/rami/.virtualenvs/deepspeech/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory
```

**Comment by lissyx** [comment]
@ramialbatal How did you installed TensorFlow ? Which branch of DeepSpeech are you using? Current `master` of DeepSpeech specifies `tensorflow==1.5.0` (or `tensorflow-gpu==1.5.0` for CUDA), in `requirements.txt`, as documented here: https://github.com/mozilla/DeepSpeech/blob/93393ddca3775f3f03a5c2d637e1824ac37cfec9/README.md#training

**Comment by lissyx** [comment]
@ramialbatal You need to use 1.5.0 if you want to use current prebuilt binaries. You should be able to install locally CUDA 9.0 and CuDNN v7 and make that available with `LD_LIBRARY_PATH`.

**Comment by lissyx** [comment]
@ramialbatal Also, which `native_client` did you downloaded ?

**Comment by ramialbatal** [comment]
@lissyx I have just ran the command from [here](https://github.com/mozilla/DeepSpeech/tree/master/native_client):

```
cd DeepSpeech
python util/taskcluster.py --target native_client/
```

So I presume this download the latest `native_client`.

Installing a different CUDA version will probably break the other apps running on the GPU, so it is probably not feasible, but then the only option is trying to build the libs.

**Comment by lissyx** [comment]
@ramialbatal No, if you do a local install and just adjust `LD_LIBRARY_PATH` it should not break anything. Besides, using `util/taskcluster.py` will download you latest master, so it means binaries build for 1.5.0. We don't have anything r1.3~ish. As much as I can verify, TensorFlow r1.4 should work with CUDA 8.0 / CuDNN v6, and the latest r1.4 compatible build we have can be found under https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.master.7f9b3e3807c0c1c339ea263f522e155cf15e4c1f 

So pick the proper set of artifacts, likely you want `gpu`: https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.master.7f9b3e3807c0c1c339ea263f522e155cf15e4c1f/gpu

**Comment by lissyx** [comment]
Closing.
