### ISSUE TITLE
Got this error: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA why should one halt on the way

### ISSUE THREAD

**Issue by mohab2014** [mozilla/DeepSpeech#1268]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by kdavis-mozilla** [comment]
Could you please file a new issue filling the issue template out? It makes us able to track/fix any bug that may be in our code. Thanks.

**Comment by mohab2014** [comment]
Got this error:
" I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA why should one halt on the way".

My CPU is intel ® Core™ i7-6600U CPU @ 2.60GHz × 4.

**Comment by lissyx** [comment]
@mohab2014 That's not an error, that's just telling you AVX2 and FMA are not used because we have downgraded to requireing AVX at most, in parity with upstream TensorFlow.
