### ISSUE TITLE
WER accuracy on librispeech 1000hour dataset

### ISSUE THREAD

**Issue by xhzhao** [mozilla/DeepSpeech#1271]
Excellent work for the good WER accuracy in this [release ](https://github.com/mozilla/DeepSpeech/releases)(5.66% on librispeech test-clean).
We are trying to repeat the release accuracy, but we found that the training dataset is Fisher+Librispeech+SwitchBoard, while Fisher+SwitchBoard datasets are not free of charge.

So my question is

- Do you have the accuracy data on librispeech? (trained on 960hour, tested on test-clean/test-other)

- Could you provide the WER accuracy with and without the language model?

@kdavis-mozilla 
BTW, i found the 12% WER accuracy from this [issue](https://github.com/mozilla/DeepSpeech/issues/629), but i suppose there maybe accuracy update for it.

**Comment by kdavis-mozilla** [comment]
@xhzhao I'm wondering if you could take this to the Discourse Forum[[1](https://discourse.mozilla.org/c/deep-speech)] as we're trying to have issues only reflect bugs/feature requests.
