### ISSUE TITLE
Python 2.7 Linux wheel without ucs4 support

### ISSUE THREAD

**Issue by dursch00** [mozilla/DeepSpeech#1276]
Could a Python 2.7, Linux wheel be supported that doesn't have the --enable-unicode=ucs4 (-cp27mu-) requirement. Most Python Linux installs aren't usually compiled with this flag (e.g. Canopy Python package) in my experience. The OSX 2.7 wheel works well with just the  --enable-unicode=ucs2 flag, so I suspect it isn't critical.

**Comment by lissyx** [comment]
@dursch00 We are using `pyenv` for building this package, I don't know how we should change the unicode configure flag. I'll investigate closely, but this is likely to be the root cause of https://discourse.mozilla.org/t/unable-to-install-deepspeech-on-centos-6-9/26023

**Comment by lissyx** [comment]
Ok, that was faster than I expected, I found that on some github issue: 
```
PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs4" pyenv install
```

I'm wondering if there's value in more than cp27-m and cp27-mu variants ?

**Comment by lissyx** [comment]
@dursch00 This should be an easy task, mostly duplicating the current 2.7 builds and just tweaking `do_deepspeech_python_build` to add the configure flags. If you like, you can try a PR :)

**Comment by dursch00** [comment]
Thanks for quick response.. One thing I just noticed that may adversely affect this that tensorflow also doesn't have a cp27m option for Linux ....
