### ISSUE TITLE
applying the model on a set of audio files 

### ISSUE THREAD

**Issue by badis23000** [mozilla/DeepSpeech#1283]
i have tried the pre-trained model on a single file, but i need to try it on a set of audio files an save the results (text of each audio file) in exel file ..
need some hints to start with 
Thanks

**Comment by reuben** [comment]
This is supported in master but hasn't been released yet. Can you try using the client from master on the release model? Follow these instructions to get it: https://github.com/mozilla/DeepSpeech#using-the-command-line-client

**Comment by badis23000** [comment]
i run this command:
deepspeech ../models/output_graph.pb ba.wav ../models/alphabet.txt ../models/lm.binary ../mo
dels/trie
where ba.wav is my wav file and i obtained a satisfied rusult, but i want to apply it on many files and also save the resuls

**Comment by reuben** [comment]
If you download the master version by following the steps I linked, you can run inference on several audio files in a folder by doing `deepspeech ../models/output_graph.pb ../models/alphabet.txt ../models/lm.binary ../models/trie path/to/folder/containing/wav/files`

**Comment by lissyx** [comment]
@badis23000 As @reuben said, this is already supported in the current master version, coming from #1232.
