### ISSUE TITLE
Error with syntax parsing in YAMLObject meaning that tensorflow doesn't work at all

### ISSUE THREAD

**Issue by ftyers** [mozilla/DeepSpeech#1297]
- **Modified?** I'm running an unmodified clone.
- **OS**: Debian GNU/Linux, `deb http://ftp.de.debian.org/debian testing main contrib`
- **TensorFlow**: installed from your builds
- **TensorFlow version** _unknown, command fails_
- **Python version**: Python 2.7.14+
- **CUDA/cuDNN version**: ??
- **Exact command to reproduce**:

```
./DeepSpeech.py --train_files data/cvdigits.tsv --dev_files data/cvdigits_dev.tsv --test_files data/cvdigits_tst.tsv 
```

This command fails.

* Result from running the script: https://paste2.org/yyLFOBHf
* Result from installing requirements: https://paste2.org/433cwDIj
* Result from trying to find out tensorflow version: https://paste2.org/YFeLJ7Mm

**Comment by elpimous** [comment]
hello.
what command to install TF ? 
with/without cuda ?

test TF validation : 

# Python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

if not : Hello, TensorFlow!

reinstall TF the correct way

**Comment by reuben** [comment]
Your Python 2.7 virtual environment (`/home/fran/tmp/deepspeech-venv/local/lib/python2.7`) is loading the PyYAML module from a Python 3 environment (`/home/fran/local/lib/python3.5/`). I don't know how this ended up happening, but you should not have both Python 2 and 3 modules in your `sys.path`.

Can you try manually installing PyYAML in `deepspeech-venv`?

**Comment by ftyers** [comment]
It seems to be a problem with my $PYTHONPATH, I did this and now it works:

```
$ echo $PYTHONPATH
/home/fran/local/lib/python3.5/site-packages/:/home/fran/source/pyAudioAnalysis:/home/fran/local/lib/python3.6/site-packages/
$ export PYTHONPATH=""
$ python tf.py 
2018-03-16 12:06:03.072372: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Hello, TensorFlow!
```

Thanks for your help guys! :)
