### ISSUE TITLE
Get rid of references to python2 in the readme

### ISSUE THREAD

**Issue by ftyers** [mozilla/DeepSpeech#1298]
At the moment the readme makes it seem like it's necessary to have python2 to use DeepSpeech. Python2 is terrible with unicode compared to Python3, so if it's not necessary it would be great to not need it.

**Comment by lissyx** [comment]
Seems like a good idea, maybe you can do the PR :)

**Comment by lissyx** [comment]
This was fixed in #1336, thanks !
