### ISSUE TITLE
DeepSpeech exporting INT64 instead of expected INT32 into SparseToDence opp, not friendly to mobile TensorFlow.

### ISSUE THREAD

**Issue by evangel76** [mozilla/DeepSpeech#1309]
tf.sparse_to_dense should be casted to be only INT32 parameters instead of INT64 default
https://github.com/mozilla/DeepSpeech/blob/d68fde8d7af91cd0a2519f283fe559576e0f43da/DeepSpeech.py#L1697

I used Tensorflow 1.6 on Ubuntu 16.04

The lack of casting makes the model import crash on iOS and android, and requires to post processing  to be mobile friendly.
[tf.sparse_tensor_to_dense(sparse_tensor) for sparse_tensor in decoded], name='output_node')

should be something like this:

[tf.sparse_tensor_to_dense(tf.to_int32(sparse_tensor)) for sparse_tensor in decoded], name='output_node')

There are probably better solution that a brutal C like casting.  

Because of it, the Import of the model under iOS gives:

No OpKernel was registered to support Op 'SparseToDense' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT64]

	[[Node: SparseToDense = SparseToDense[T=DT_INT64, Tindices=DT_INT64, validate_indices=true](CTCBeamSearchDecoder, CTCBeamSearchDecoder:2, CTCBeamSearchDecoder:1, SparseToDense/default_value)]]

**Comment by lissyx** [comment]
Thanks. To my knowledge, iOS, Android (and RPi3) builds are defining `IS_MOBILE_PLATFORM` that makes the `SparseToDense` op happier:
 - https://github.com/tensorflow/tensorflow/blob/2450b1f978065593374c78a36f5c65290a393f14/tensorflow/core/platform/platform.h#L29
 - https://github.com/tensorflow/tensorflow/blob/2450b1f978065593374c78a36f5c65290a393f14/tensorflow/core/platform/platform.h#L37
 - https://github.com/tensorflow/tensorflow/blob/2450b1f978065593374c78a36f5c65290a393f14/tensorflow/core/platform/platform.h#L49

So i'm curious to know more about your build steps.

**Comment by lissyx** [comment]
See also #1095

**Comment by evangel76** [comment]
I am running my own training of Deepspeech on the side, I got to pretty high accuracy on desktop. 
I am attempting to move the all thing to iOS, and I got it to work, but I had to cast and remove the IS_MOBILE_PLATFORM, because it does removes "opps" ( features of TensorFlows)  you need to run DeepSpeech.
I have posted the steps here: https://github.com/evangel76/TensorFlow15CocoPod

**Comment by lissyx** [comment]
@evangel76 Right, thanks. Then I would suggest you try to work on the streaming branch https://github.com/mozilla/DeepSpeech/tree/streaming-inference that @reuben is going to land, because you are loosing your time with that right now :-). Doing that kind of hack on the current model is a dead-end, and if we need this kind of changes, then we would rather do it on the streaming model and it might be of interest to @reuben if you can experiment on iOS, because none of us has time for that right now :).

FYI, with the streaming model, you can see also #1224, I've run some experiments with `tococo` and only `TensorFlowMinimum` is missing, and there's an upstream issue: https://github.com/tensorflow/tensorflow/issues/17289

I'm going to close this, but really, thanks for hacking on iOS, we are interested in that :)

**Comment by lissyx** [comment]
@evangel76 Also, you might want to come and discuss with us on IRC (#machinelearning on irc.mozilla.org) and / or on Discourse: https://discourse.mozilla.org/c/deep-speech, I'd hate that you burn your time for nothing: contributor's time has too much value to me, especially when you are hacking stuff that are that useful !

**Comment by evangel76** [comment]
That is an odd reply ... I got the all thing working pretty accurately on iOS, saying it is a dead-end is strange at best, but well, since we are sharing opinions, here is mine:
I know what you are referring to, you fear the memory foot print of the all thing. (There are programmers like me to solve those problems, performance experts are for that)
I am pretty happy with my fix, I 'll keep going in my direction, it works great for what I need it for.

**Comment by lissyx** [comment]
@evangel76 I never said it was not good, I said that the code you need to change is going away: https://github.com/mozilla/DeepSpeech/blob/1926bce0ebf893c006a0c6407af389a15fcdc646/DeepSpeech.py#L1720-L1763 there is no use of `sparse_to_dense` anymore. It's not just about memory footprint, it's about complexity of the network.

**Comment by evangel76** [comment]
Fair, thanks

**Comment by lissyx** [comment]
@evangel76 Just to give more context: changing this datatype might have impact on the recognition rate itself (or it might not): this is something that would require precise investigation to ensure we are not breaking anything. Now, we still have several pending benchmarks before we can release v0.2.0, a version where we do not want to change the model. Then, streaming will arrive in v0.3.0. Still, we are very interested in any result you get :)

**Comment by evangel76** [comment]
I started to replace the code with the streaming version , and replugging Metal acceleration into it for iOS.
