### ISSUE TITLE
getting 'FileNotFoundError: File b'' does not exist' after running  python DeepSpeech.py 

### ISSUE THREAD

**Issue by arunimathappa** [mozilla/DeepSpeech#1311]
python version - 3.6
deepspeech version 0.1.1
RedHat linux 7.4

`
I have the following stack trace
```
$ python DeepSpeech.py --train_files corpus/cv-valid-train.csv,  corpus/cv-other-train.csv  --dev_files corpus/cv-valid-dev.csv  --test_files corpus/cv-valid-test.csv
Traceback (most recent call last):

  File "DeepSpeech.py", line 1834, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1791, in main
    train()
  File "DeepSpeech.py", line 1464, in train
    next_index=lambda i: COORD.get_next_index('train'))
  File "/data/util/feeding.py", line 90, in __init__
    file = pandas.read_csv(csv, encoding='utf-8', na_filter=False)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
**FileNotFoundError: File b'' does not exist**
```

`
i am getting this error **FileNotFoundError: File b'' does not exist** , 
while running 
DeepSpeech.py --train_files corpus/cv-valid-train.csv,  corpus/cv-other-train.csv  --dev_files corpus/cv-valid-dev.csv  --test_files corpus/cv-valid-test.csv.

The csv files were generated by executing the below command
/data/tmp/DeepSpeech/bin/import_cv.py data/corpus  
and the corpus was downloaded from
https://voice.mozilla.org/en/data

**Comment by lissyx** [comment]
@arunimathappa Are you sure this is good: `python DeepSpeech.py --train_files corpus/cv-valid-train.csv,  corpus/cv-other-train.csv  --dev_files corpus/cv-valid-dev.csv  --test_files corpus/cv-valid-test.csv` ? Is this really what you wrote, with **two** CSV files, separated by `, ` ?

**Comment by arunimathappa** [comment]
yes this is the command i wrote and i followed the command written on   https://github.com/mozilla/DeepSpeech#common-voice-training-data. please let me know if i am running a wrong command

**Comment by lissyx** [comment]
@arunimathappa The doc specifies a `,`, but there is no space. I'm pretty sure this is your problem.

**Comment by arunimathappa** [comment]
Thankyou so much @lissyx  the error was solved.
also could you tell me how much approx time does it take to train on LINUX VM (RHEL 7) with 8 CPU’s, 8 GB RAM and 200 free disk space.

**Comment by lissyx** [comment]
Full Common Voice on pure CPU will take weeks at best. Thanks for updating us on the outcome :-).

**Comment by jageshmaharjan** [comment]
Sorry for Opening the closed Issue.
I got the same error, and read this to resolve, However It didn't work for me. I checked the help on Deepspeech.py file. Followed the same approach, didn't work for me.

![deepspeech_help](https://user-images.githubusercontent.com/15376938/39359553-0a63f5de-4a4d-11e8-8d72-11d2dd61886f.png)
And, my csv file looks fine and formatted properly.
![cv_files](https://user-images.githubusercontent.com/15376938/39359598-362c998c-4a4d-11e8-9831-35785d7dbcc7.png)

**Comment by lissyx** [comment]
@jageshmaharjan Please use Discourse to reach out for help. And do not use screenshots, it's completely impossible to work with. Last, the root cause of the error was because of misuse of the multiple, comma-separated filenames and you don't provide your command line to call `DeepSpeech.py`, so there's nothing actionnable here.

**Comment by jageshmaharjan** [comment]
Thanks @lissyx , it was because of multiple csv file. it worked.
