### ISSUE TITLE
sox: command not found, what should I do?

### ISSUE THREAD

**Issue by RaphaelHuirong** [mozilla/DeepSpeech#1319]
I followed the instruction and tried to run your test, by entering the commend : "bin/import_cv.py"
a error has occur. What should I do? 

No directory "/Users/Raphael/Desktop/DeepSpeech/test/cv_corpus_v1.tar.gz" - extracting archive...
Progress |####################################################################################################| 100.0% completed

No CSV file "/Users/Raphael/Desktop/DeepSpeech/test/cv-valid-train.csv" - importing "/Users/Raphael/Desktop/DeepSpeech/test/cv_corpus_v1/cv-valid-train.csv"...
Importing mp3 files...
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
Traceback (most recent call last):
  File "bin/import_cv.py", line 143, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_cv.py", line 37, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "bin/import_cv.py", line 72, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1]))
  File "bin/import_cv.py", line 115, in _maybe_convert_set
    pool.map(one_sample, samples)
  File "/Users/Raphael/anaconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/Raphael/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/Users/Raphael/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/Raphael/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "bin/import_cv.py", line 97, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "bin/import_cv.py", line 140, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/Users/Raphael/anaconda3/lib/python3.6/site-packages/sox/transform.py", line 444, in build
    "Stdout: {}\nStderr: {}".format(out, err)
sox.core.SoxError: Stdout: 
Stderr: /bin/sh: sox: command not found

**Comment by kdavis-mozilla** [comment]
Did you install sox?

**Comment by RaphaelHuirong** [comment]
I did install the requirement, but still cannot use sox from commend line.

Raphaels-MacBook-Pro:~ Raphael$ sox
-bash: sox: command not found

What should I do next?

**Comment by kdavis-mozilla** [comment]
By "I did install the requirement" do you mean you installed the python wrapper to sox or sox itself?

From the lack of sox on the command line, it looks like the former, the python wrapper.

You need to install sox itself using say brew.

**Comment by RaphaelHuirong** [comment]
I use brew to install the sox and glad it works! Really appreciate your help!

**Comment by kdavis-mozilla** [comment]
Welcome!
