### ISSUE TITLE
lm::FormatLoadException and LFS upload missing objects 

### ISSUE THREAD

**Issue by wenjinghy** [mozilla/DeepSpeech#1320]
when I run ./bin/run-ldc93s1.sh,I get an error about lm::FormatLoadException during training:
![delfs2](https://user-images.githubusercontent.com/31907394/38035528-2bbe9db6-32d7-11e8-8738-d3d915458a64.png)
I don't forgot to install Git LFS before cloning the repository,and I follow the instructions on https://git-lfs.github.com/, including running git lfs install once before I clone the repo.
But In the previous setup, when I pushed the project to github, the following prompt appeared:
![delfs](https://user-images.githubusercontent.com/31907394/38036880-4f826978-32da-11e8-96c2-d569f777c790.png)
I'm not sure if this is the cause of the error.
Looking forward to your reply.Thanks in advance.

**Comment by kdavis-mozilla** [comment]
It looks like you didn't use git lfs to do the original checkout the language model.

For example in my repo
```bash
Kellys-MacBook-Pro:DeepSpeech kdavis$ ls -lh data/lm/lm.binary 
-rw-r--r--  1 kdavis  staff   1.5G Mar 11 07:47 data/lm/lm.binary
```
What's the size of `lm.binary` in your repo?

**Comment by wenjinghy** [comment]
Thanks to your prompt reply, I noticed I had a problem with my binary file.Then I re-cloned the project using git lfs，solved the error.
