### ISSUE TITLE
Illegal instruction (core dumped) - when trying to run the pre-trained model

### ISSUE THREAD

**Issue by guruvasuraj** [mozilla/DeepSpeech#1322]
Hi,
     When I tried to run the pre-trained model, I am getting the below issue:

I used both python bindings and command-line client. But, it's the same result.

wiz@gpu2h:~/Speech_recognition/deepspeech/DeepSpeech$ ./deepspeech models/output_graph.pb models/alphabet.txt models/lm.binary models/trie audio_input.wav
Illegal instruction (core dumped)

Any help would be greatly appreciated.

Thanks,
Guru.

**Comment by nigelskeels** [comment]
Hi, im getting this too..

Illegal instruction (core dumped)

**Comment by kdavis-mozilla** [comment]
Execute
```bash
./deepspeech -h
```
to find the correct command line argument ordering.

**Comment by nigelskeels** [comment]
deepspeech -h

also gives ...

Illegal instruction (core dumped)

**Comment by kdavis-mozilla** [comment]
@nigelskeels Ubuntu on Windows Subsystem for Linux is not supported, sorry. Maybe if you compiled everything from scratch?

@guruvasuraj Did you get a chance to try 
```bash
./deepspeech -h
```

**Comment by guruvasuraj** [comment]
@kdavis-mozilla Yes, I did that as well but ending up in the same error. 
I tried python util/taskcluster.py --target .
and ./deepspeech -h gives me the error **"./deepspeech: error while loading shared libraries: libsox.so.2: cannot open shared object file: No such file or directory"**

would you suggest any fix for the above?

Thanks.

**Comment by kdavis-mozilla** [comment]
@guruvasuraj Is sox installed? What does
```bash
which sox
```
result in?

**Comment by guruvasuraj** [comment]
@kdavis-mozilla Sorry, got sox installed now.

But after installation, I am not able to see the inference results.
For eg:
Approach 1 gives me the error
(tensorflow_p36) ubuntu@ip-172-31-36-98:~/speech-to-text-wavenet/Deepspeech/DeepSpeech$ deepspeech models/output_graph.pb LDC93S1.wav models/alphabet.txt models/lm.binary models/trie
Loading model from file models/output_graph.pb
2018-04-03 15:37:15.902374: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 5.858s.
Loading language model from files models/lm.binary models/trie
Loaded language model in 26.990s.
Running inference.
Killed

and Approach 2 gives me the error
Error: Alphabet size does not match loaded model: alphabet has size 212, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loading the LM will be faster if you build a binary file.
Reading models/alphabet.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "a" not \data\. Byte: 218
Aborted (core dumped)

Could you please help me with this?

**Comment by lissyx** [comment]
@guruvasuraj You have downloaded latest build from TaskCluster, and thus you need to change the order of the arguments: WAV file should be the last one. Please check `deepspeech -h`.

**Comment by guruvasuraj** [comment]
I have around 820 MB of free space. I am using a free-tier EC2 instance. Isn't that enough to run a pre-trained model?

**Comment by lissyx** [comment]
@guruvasuraj I'm referring to RAM, not disk space. WIth the `.pb` model, peak allocation will be around 4.5GB. You can convert to `.pbmm` to optimize that (we have not yet released an updated model with `.pbmm` file).

**Comment by guruvasuraj** [comment]
Thanks @lissyx and @kdavis-mozilla for your assistance. I will try that and let you know.

**Comment by adkarhe** [comment]
hey guys,
i am also getting the error:
(py2) gt20@gt20-System-Product-Name:~/temp/apr2018/deepspeech/DeepSpeech$ deepspeech models/output_graph.pb models/alphabet.txt models/lm.binary models/trie my_audio_file.wav 
**Illegal instruction (core dumped)**

**Comment by kdavis-mozilla** [comment]
@adkarhe Execute
```bash
./deepspeech -h
```
to find the correct command line argument ordering.

**Comment by adkarhe** [comment]
@kdavis-mozilla 
again getting same error
(py2) gt20@gt20-System-Product-Name:~/temp/apr2018/deepspeech/DeepSpeech$ deepspeech -h
Illegal instruction (core dumped)

**Comment by kdavis-mozilla** [comment]
@adkarhe Could you describe your system and how you installed deepspeech?

**Comment by adkarhe** [comment]
i created a virtual environment of python2 than installed sox and than cloned the git repo
after that i used **pip install deepspeech**  
than downloaded the pre-trained weights than execute the script 
**deepspeech models/output_graph.pb models/alphabet.txt models/lm.binary models/trie my_audio_file.wav**
and getting the error 
**Illegal instruction (core dumped)**

**Comment by kdavis-mozilla** [comment]
@adkarhe What type of OS are you using? Is the OS virtualized?

**Comment by adkarhe** [comment]
i am using ubuntu and its not virtualized

**Comment by lissyx** [comment]
@adkarhe What's your CPU ? Likely it lacks AVX.

**Comment by jageshmaharjan** [comment]
@adkarhe , I still doubt your positional argument passed to infer. It should be in the format shown below:
![position](https://user-images.githubusercontent.com/15376938/39355692-77be3886-4a40-11e8-9c51-3da7571008fb.png)

and The Inference output would yield to:

![inference](https://user-images.githubusercontent.com/15376938/39355713-894d4628-4a40-11e8-898a-119236a5a5cc.png)

**Comment by lissyx** [comment]
Closing because of lack of feedback.
