### ISSUE TITLE
deepspeech-gpu: command not found When installed

### ISSUE THREAD

**Issue by dantalksalot** [mozilla/DeepSpeech#1323]
Hey all,
So I've installed deepspeech-gpu via `pip3 install deepspeech-gpu` and it's still returning `deepspeech_gpu: command not found` when I try running it.

I'm using python 3.5.2 and I initially thought it was due to a pip/python mismatch but installing and using deepspeech (`pip3 install deepspeech`) works perfectly fine. 

Am I doing something wrong?

**Comment by lissyx** [comment]
Just use the "deepspeech" command.
