### ISSUE TITLE
Terminating with uncaught exception of type

### ISSUE THREAD

**Issue by RaphaelHuirong** [mozilla/DeepSpeech#1324]
Hi,
I follow the README and try to train a sample model. When I type  ./bin/run-ldc93s1.sh, everything works well. However, when it finishes optimization, I can get the result. And Throwing this following:

I FINISHED Optimization - training time: 0:00:43
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
libc++abi.dylib: terminating with uncaught exception of type lm::FormatLoadException: native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece &, std::vector<uint64_t> &) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43
./bin/run-ldc93s1.sh: line 30:  1668 Abort trap: 6           python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir "$checkpoint_dir" --decoder_library_path /Users/Raphael/Desktop/DeepSpeech/NativeClient/libctc_decoder_with_kenlm.so "$@"

And here is my lm.binary size: 

Raphaels-MacBook-Pro:DeepSpeech-master Raphael$ ls -lh data/lm/lm.binary 
-rwxr-xr-x@ 1 Raphael  staff   135B Mar 19 13:25 data/lm/lm.binary

What should I do?

**Comment by kdavis-mozilla** [comment]
You did not use git lfs[[1](https://github.com/mozilla/deepspeech#prerequisites)] to checkout the repo.

Remove your current checkout, instally git lfs, checkout the repo again, and try training again.

**Comment by RaphaelHuirong** [comment]
git is pretty new for me, therefore, I don't know how to remove checkout and checkout the repo. Can you provide the commend line code for me? Thanks in advance.

**Comment by kdavis-mozilla** [comment]
Removing the checkout is simply removing the `DeepSpeech` folder.
```bash
rm -fr DeepSpeech
```
Checking out the repo is simply checking it out as you did initially.
```bash
git clone https://github.com/mozilla/DeepSpeech.git
```
However, note you have to install git lfs between these two steps.

**Comment by RaphaelHuirong** [comment]
Thank you for your help, glad that I solve this problem. I get a result which shows as output_graph.pb. Could you tell me how to interpret or use it with code example?

**Comment by kdavis-mozilla** [comment]
@RaphaelHuirong Using output_graph.pb is discussed in the [README.md](https://github.com/mozilla/DeepSpeech/blob/v0.1.1/README.md)

**Comment by slavaGanzin** [comment]
You can skip repo recreating. You can just run lfs pull:
```
cd DeepSpeech
git lfs install
git lfs pull
```

**Comment by pranjaldaga** [comment]
Thanks, @slavaGanzin I had the same issue, and instead of removing/recreating the repo, this helped me fix the issue quickly.
