### ISSUE TITLE
Wake up word / Hot word like "ok google"

### ISSUE THREAD

**Issue by alxistn** [mozilla/DeepSpeech#1325]
Hello,

I am wondering if I can use DeepSpeech to implement hotword detection like google home wakes up when you say "ok google".

I am trying to train a model for this purpose but I'm unable to get good results. Any advice on how to do this with DeepSpeech ?

Thanks

**Comment by kdavis-mozilla** [comment]
We've not tried, but there is some research in that direction[[1](https://arxiv.org/abs/1512.08903)][[2](https://mediatum.ub.tum.de/doc/1289941/160946.pdf)(PDF)]
