### ISSUE TITLE
Error: Alphabet size does not match loaded model: alphabet has size 212, but model has 28 classes in its output?

### ISSUE THREAD

**Issue by bolt163** [mozilla/DeepSpeech#1328]
root@f904f6ce95a3:/data/home/DeepSpeechOK  ./deepspeech  /data/home/DeepSpeechOK/data/ldc93s1/results/model_export/output_graph.pb /data/home/DeepSpeechOK/data/alphabet.txt    /data/home/DeepSpeechOK/data/ldc93s1/LDC93S1.wav

Loading model from file /data/home/DeepSpeechOK/data/ldc93s1/results/model_export/output_graph.pb
2018-04-10 09:51:41.430313: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error: Alphabet size does not match loaded model: alphabet has size 212, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loaded model in 0.043s.
Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepspeech/client.py", line 66, in main
    fs, audio = wav.read(args.audio)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format '# Ea'... not understood.

**Comment by bolt163** [comment]
the  output_graph.pb  model  was created after runing the  ./bin/run-ldc93s1.sh
while i use the   generated model output_graph.pb  to  test  with the same training wav: /data/home/DeepSpeechOK/data/ldc93s1/LDC93S1.wav

Error1: Alphabet size does not match loaded model: alphabet has size 212, but model has 28 classes in its output.

Error2: /usr/local/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
"understood.".format(repr(str1)))
ValueError: File format '# Ea'... not understood.

very oddly?

**Comment by lissyx** [comment]
@bolt163 How did you installed ? I suspect you are using v0.1.1 and you are mixing the order of arguments.

**Comment by bolt163** [comment]
@lissyx
thanks for u reply 
i solved it myself, the  deepspeech of the native-client.tar.gz was not working, the default deepspeech was using the /usr/local/bin/deepspeech， 

after using  the deepspeech from the native-client.tar.gz, the problem go die
