### ISSUE TITLE
Quantization of the model 

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#133]
Should be split up

**Comment by lissyx** [comment]
Currently, we have a process in place to : 
- Export graph session as GraphDef file
- Quantize using checkpoint and GraphDef files
- Reload the quantized model
- Trigger a Test WER on the quantized model

So far, with 10k samples and 100 epochs on TED, we get:
- Test WER ~0.39 on non quantized model
- Test WER ~0.82 on quantized reloaded model

**Comment by lissyx** [comment]
I did a second run on top of current master (`ted_10000s_100e_quant_new.log`):
```
$ grep -E "^Test.*WER|^Test Quantized.*WER" ted_10000s_100e_quant.log ted_10000s_100e_quant_new.log
ted_10000s_100e_quant.log:Test WER: 0.396643
ted_10000s_100e_quant.log:Test Quantized WER: 0.820484
ted_10000s_100e_quant_new.log:Test loss=245.908058711 avg_cer=0.562084945 WER: 0.982135
ted_10000s_100e_quant_new.log:Test Quantized loss=1720.364662638 avg_cer=2.913973395 WER: 1.806516
```

**Comment by lissyx** [comment]
After much problems, process is now sound and complete and we can apply "weights" quantization, reload the graph, perform an inference step and get consistent results.

There are still issues:
 - unable to rely on "eightbit" quantization method (https://github.com/tensorflow/tensorflow/issues/7162)
 - using BasicLSTMCell results in errors at run time, switching to BasicRNNCell works

**Comment by kdavis-mozilla** [comment]
Does GRUCell work?

**Comment by lissyx** [comment]
I just tested, GRUCell fails in a similar way:
> tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'bidirectional_rnn/bw/bw/while/Select' has inputs from different frames. The input 'bidirectional_rnn/bw/bw/while/gru_cell/add' is in frame ''. The input 'bidirectional_rnn/bw/bw/while/Select/Enter' is in frame 'bidirectional_rnn/bw/bw/while/bidirectional_rnn/bw/bw/while/'.

**Comment by reuben** [comment]
Good news from upstream: weights quantization works on LSTMCell by using the new Graph Transform Tool: https://github.com/tensorflow/tensorflow/issues/7949#issuecomment-283398812

Bad news: quantizing the operations themselves is still broken.

**Comment by lissyx** [comment]
Using the graph transformation tool as suggested by upstream, we get quantize_weights to work on the model (but using quantize_nodes still exposes the frame problem). Using the frozen/quantized graph works with the native client, and I am currently experimenting with valgrind massif to get data on memory usage at runtime.

**Comment by lissyx** [comment]
Closing because #1850
