### ISSUE TITLE
Test trained models using DeepSpeech.py

### ISSUE THREAD

**Issue by kmonachopoulos** [mozilla/DeepSpeech#1343]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:  NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Source
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.9.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0 

I want to use **DeepSpeech.py** to test a set of voice recordings using a pre-trained model (checkpoint and protobuf) and a .csv file. 

I would expect something like this for the checkpoint : 

```bash
python DeepSpeech.py --test_files ./data/tiny/test_tiny.csv --checkpoint_dir ../models/checkpoints/
```
And something like this for the protobuf : 

```bash
python DeepSpeech.py --test_files ./data/tiny/test_tiny.csv --initialize_from_frozen_model ./models/protobufs/output_graph.pb
```
And probably extract some results ... 

Is this supported by the script ?

Thanks!

**Comment by kdavis-mozilla** [comment]
Is the antecedent of "This" in your newest comment the method in your first comment or second comment?

PS: Does "--train False --notrain" lead to a double negative?

**Comment by kmonachopoulos** [comment]
I managed to change Deepspeech script and extract evaluation scores on librispeech, while using the checkpoint or the protobuf model.

Closing.

**Comment by lissyx** [comment]
Thanks for updating us @kmonachopoulos. Maybe you could share some code that can be useful to others? :)

**Comment by kmonachopoulos** [comment]
Hello,
I have created a revised version on Deepspeech.py that as an extra supports : 

- Optional GPU memory allocation upfront or ondemand
- Choice of unidirectional / bidirectional architecture.
- Evaluation support using a checkpoint file and a csv annotation list.

How can I do a merge request (master / branch) ? Where should I attach the code ?

Thanks :)

**Comment by kdavis-mozilla** [comment]
@kmonachopoulos Wow! Awesome! We'd love to incorporate some of your code!

One issue, unfortunately, is that we have a PR that's about to be merged[[1](https://github.com/mozilla/DeepSpeech/pull/1463)] which covers some of the same ground, for example unidirectional RNN.

Maybe the best course of action would be to wait until the PR lands, hopefully in the next few days, then cherry pick some of your changes, for example the "Optional GPU memory allocation upfront or ondemand", and land those as PR's?

Does that sound like a reasonable way to proceed?
