### ISSUE TITLE
Full size of Mozilla vocab.txt

### ISSUE THREAD

**Issue by saisrinivas047** [mozilla/DeepSpeech#1351]
hi 
can someone say what is the full size of mozilla vocab.txt ? In this repository the size is only 11.6 mb

thanks

**Comment by lissyx** [comment]
You are right, the current vocab.txt is not the one used to produce the final model. However, we have licensing issues to solve and thus need to recreate one we can redistribute. This is tracked in https://github.com/mozilla/DeepSpeech/issues/1244
