### ISSUE TITLE
Failed to recognize own recordings

### ISSUE THREAD

**Issue by kmonachopoulos** [mozilla/DeepSpeech#1356]
I am using the pre-trained model and I am trying to recognize some of my own recordings, but fail. It is weird because when I inference .wav files of the test db (LibriSpeech) or download random .wav files from the internet the model manage to extract the ~ correct results and fail only on my recordings. 

To extract the wav files (that i later inference) I tried both `pyaudio` and (`sounddevice + soundfile`). In both cases I am using sample frequency of 16000 (also tested other rates but still fail). Is there any properties that I must change or adjust while recording?

**pyaudio** example : 

```
import pyaudio
import wave
 
FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 16000
CHUNK = 1024
RECORD_SECONDS = 2
WAVE_OUTPUT_FILENAME = "test.wav"
 
audio = pyaudio.PyAudio()
 

# start Recording
stream = audio.open(format=FORMAT, channels=CHANNELS,
                rate=RATE, input=True,
                frames_per_buffer=CHUNK)
print "recording..."
frames = []
 
for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    data = stream.read(CHUNK)
    frames.append(data)
print "finished recording"
 
 
# stop Recording
stream.stop_stream()
stream.close()
audio.terminate()
 
waveFile = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
waveFile.setnchannels(CHANNELS)
waveFile.setsampwidth(audio.get_sample_size(FORMAT))
waveFile.setframerate(RATE)
waveFile.writeframes(b''.join(frames))
waveFile.close()
```

**sounddevice + soundfile** example : 

```
def record_and_save():
	duration = 3  # seconds
	fs=16000

	sd.default.samplerate = fs
	sd.default.channels = 2

	print('press any key to record')
	input()
	data = sd.rec(duration * fs, dtype='float32')
	print('Recording Audio')
	sd.wait()

	sd.play(data, fs)
	print('Play Audio')
	sd.wait()

	sf.write('test.wav', data, fs)
```

What should I change for my own recordings to get recognized ?

Thanks.

**Comment by lissyx** [comment]
Can you take that discussion on Discourse ? Also, we document using mono, and I see you have two channels. We have some code taking care of the conversion, but we have not tested that very intensively, so you should try to record in mono, 16 bits: https://github.com/mozilla/DeepSpeech/blob/master/README.md

**Comment by kmonachopoulos** [comment]
Thanks, that was the problem ...

**Comment by lissyx** [comment]
@kmonachopoulos Thanks for confirming, but it's be good if you can open a thread on that on Discourse, we should obviously be working and sharing that :)
