### ISSUE TITLE
Feature Request: Produce lattices or n-bests instead of just one best

### ISSUE THREAD

**Issue by loctruong96** [mozilla/DeepSpeech#1372]
I asked the question on discourse and discovered that currently this is not possible. Therefore I'm putting this in as a request for future implementation if possible. Keep up the great work guys,

Thank you,
Loc

**Comment by lissyx** [comment]
@loctruong96 It's doable with the new decoder, taking PR if you want :)

**Comment by loctruong96** [comment]
> @loctruong96 It's doable with the new decoder, taking PR if you want :)

Awesome. I will take a look over break.

Have a good holiday,
Loc

**Comment by lissyx** [comment]
@loctruong96 Are you still interested ? Do you have any PR to send ?

**Comment by loctruong96** [comment]
@lissyx my research team moved to use a motion based feature from video and taken a step back from using word prediction from the audio so I haven't get the chance to dive into this feature. Should we come back to the idea of using key word prediction, I may get time to work on it. In the mean time no substantial PR from me. Thanks!
