### ISSUE TITLE
License of Audio testfiles

### ISSUE THREAD

**Issue by AtosNicoS** [mozilla/DeepSpeech#1375]
https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.1

"audio-0.1.1.tar.gz" -> Which license is used for those audio files?

**Comment by lissyx** [comment]
@kdavis-mozilla should know that for sure :)

**Comment by kdavis-mozilla** [comment]
As far as I remember they are from the clean test set of the LibriSpeech[[1](http://www.openslr.org/12/)] data set. So they are CC-By 4.0[[2]](https://creativecommons.org/licenses/by/4.0/)

**Comment by reuben** [comment]
We should probably include that license in the download for the sample files then, no?

**Comment by AtosNicoS** [comment]
Yes you should include a license, please. And also give "appropriate credit", otherwise you violate the license.

**Comment by kdavis-mozilla** [comment]
Done for 0.1.1 and 0.1.0 releases

**Comment by AtosNicoS** [comment]
Thanks for adding the license.

If I understood the license correct, you still must give "appropriate credit":
https://creativecommons.org/licenses/by/4.0/
https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart

I guess a readme to the original source and the name(s) of the author/project would be good.

**Comment by kdavis-mozilla** [comment]
@AtosNicoS Completely correct, sorry was in a rush. It should be with attribution now.

**Comment by AtosNicoS** [comment]
Thanks a lot!
