### ISSUE TITLE
Cannot run the simplest example "client.py" : "TypeError: Array must have 1 dimensions.  Given array has 2 dimensions"

### ISSUE THREAD

**Issue by Svito-zar** [mozilla/DeepSpeech#1382]
- I have not written a custom code, I used a code which you provided as an example of usage by python : "client.py".

- My OS Platform is Linux Ubuntu 16.04

- My TensorFlow is 1.8.0 and was installed from upstream TensorFlow

- My Python version is 3.5.2

- I do not have CUDA on my machine, because I do not have external GPU.

- **Exact command to reproduce**
`python client.py /home/taras/Dropbox/GetSandwich/models/output_graph.pb /home/taras/Dropbox/GetSandwich/models/alphabet.txt /home/taras/Dropbox/GetSandwich/models/lm.binary /home/taras/Dropbox/GetSandwich/models/trie /home/taras/Dropbox/GetSandwich/Code/VideoProcessing/wisdom.wav`

So I just run the basic script you provide on my audio and I get the following error;

> Loading model from file /home/taras/Dropbox/GetSandwich/models/output_graph.pb
2018-05-12 11:31:33.903476: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.258s.
Loading language model from files /home/taras/Dropbox/GetSandwich/models/lm.binary /home/taras/Dropbox/GetSandwich/models/trie
Loaded language model in 0.891s.
Running inference.
Traceback (most recent call last):
  File "asr_2.py", line 97, in <module>
    main()
  File "asr_2.py", line 92, in main
    print(ds.stt(audio, fs))
  File "/home/taras/tmp/deepspeech-venv/lib/python3.5/site-packages/deepspeech/model.py", line 127, in stt
    return _model.Model_stt(self, aBuffer, aSampleRate)
TypeError: Array must have 1 dimensions.  Given array has 2 dimensions

It seems that there is an issue with the model you provide ...

**Comment by lissyx** [comment]
I'm pretty sure you are passing some stereo audio ?

**Comment by Svito-zar** [comment]
Yes, wisdom.wav contains a normal audio file, I can attach it if it helps

**Comment by lissyx** [comment]
@Svito-zar Please stick to the supported documented audio: wav, 16 bits, 16khz, mono

**Comment by Svito-zar** [comment]
Now it works, I guess the problem was that my audio was not mono, but stereo.
