### ISSUE TITLE
How Spell Check work in DeepSpeech ? thanks.

### ISSUE THREAD

**Issue by bjtommychen** [mozilla/DeepSpeech#1383]
Hi, all
    I read your documents, and it's said DeepSpeech use the trie file(in the /data/model) to do spell check.  I guess it still use beam search, but I can't understand it well even after I read the src code. like generate_trie.cpp. 
   If you know some paper can explain this well, please let me know. 
   Thanks.

**Comment by kdavis-mozilla** [comment]
@bjtommychen We try to reserve issues for feature requests or bugs in our code. So we ask that discussion topics like this be taken to our discourse forum[[1](https://discourse.mozilla.org/c/deep-speech)]. Thanks for your understanding!
