### ISSUE TITLE
Documentation does not mention the libsox2 dependency (it should)

### ISSUE THREAD

**Issue by Tigraan** [mozilla/DeepSpeech#1384]
Following the exact instructions of https://github.com/mozilla/DeepSpeech/blob/master/README.md#using-the-command-line-client on Ubuntu 16.04.4 (after having git-cloned the source repo) one is met with

`./deepspeech: error while loading shared libraries: libsox.so.2: cannot open shared object file: No such file or directory`

That is easily fixed (in my case by installing the `libsox2` package v14.4.1-5 from the universe repo) but shouldn't it be mentioned in the docs? AFAICT that lib is not on the standard Ubuntu 16.04 (mine is not a fresh install but I doubt I uninstalled or unlinked it by error).

FWIW:
DeepSpeech: v0.2.0-alpha.5-0-g7cc8382
TensorFlow: v1.6.0-16-gc346f2c
Python: 3.5.2

**Comment by lissyx** [comment]
It is documented: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md#required-dependencies
