### ISSUE TITLE
Train a model compatible with streaming inference

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#1389]

**Comment by mathematiguy** [comment]
Has any progress been made on this? I've just trained a model on v0.2.0-alpha.9 and I've been having trouble getting it to do inference. I'm wondering if this might be related to why.

Also streaming inference is of particular interest to our project, so any information (if indeed there is any) would be great.

**Comment by badarivishal** [comment]
Hi @reuben was following this issue for some time. Are the models available now to test? Can you provide the link please? Thanks. 
(I had got an older set of models that work with v0.2.0-alpha.9-0. However, the results were quite unsatisfactory. So I decided to wait for closure of this issue to proceed further.

**Comment by calmncollected** [comment]
Hi @reuben was following this issue for some time. Are the models available now to test? Can you provide the link please? Thanks.
(I had received an older set of models that work with v0.2.0-alpha.9-0. However, the results were quite unsatisfactory. So I decided to wait for closure of this issue to proceed further.
