### ISSUE TITLE
support for arbitrary length audio files

### ISSUE THREAD

**Issue by jtoy** [mozilla/DeepSpeech#1397]
the ability to run the model of audio files of any length.

**Comment by lissyx** [comment]
Can you be more specific ?

**Comment by jtoy** [comment]
currently we are only able to run the model on audio files of about 5 seconds:
"Once everything is installed you can then use the deepspeech binary to do speech-to-text on short, approximately 5 second, audio files (currently only WAVE files with 16-bit, 16 kHz, mono are supported in the Python client):"

**Comment by lissyx** [comment]
This is mostly a warning because we got reports of people trying to feed 3 hours of audio and getting bad results. Also #1275 will address that.

**Comment by reuben** [comment]
> Also #1275 will address that.

Not really, segmenting the audio would still be the user's responsibility, streaming just makes it easier to use.
