### ISSUE TITLE
decoding time of 30 second audio file 

### ISSUE THREAD

**Issue by nomitjangid** [mozilla/DeepSpeech#1400]
Hi,

I'm running deep-speech training on 1000 hours of audio files.
How much time will an epoch take if I'm using 4  NVIDIA TESLA P100 (16 GB each) and also how much time it will take to decode a 30-second audio file on both GPU and CPU system?

Thanks

**Comment by kdavis-mozilla** [comment]
@nomitjangid We try to reserve issues for feature bugs and feature request in the current code base. So could you move this training time discussion to our [discourse channel](https://discourse.mozilla.org/c/deep-speech)? Thanks.
