### ISSUE TITLE
Provide Java bindings

### ISSUE THREAD

**Issue by RaphaelHuirong** [mozilla/DeepSpeech#1401]
Hi, 
Nice job with pre-trained model, however, I want to use that in Java class. Could you mind providing me a example to use pre-trained model in Java class? I have already used TensorFlow API in my Java project. Thank you very much!

**Comment by lissyx** [comment]
We don't have Java bindings, so if you need to use that from java, you will have to do the JNI stuff ):

**Comment by kdavis-mozilla** [comment]
@RaphaelHuirong If you do make a Java binding using JNI, we'd love to have it as a PR!

**Comment by RaphaelHuirong** [comment]
Thank you for your quick response. Since I have time deadline, let me finish what I have in hand, then I will take a look at it.

**Comment by lissyx** [comment]
@RaphaelHuirong PR are welcome, if you make any JNI binding send us one to at least list it next to the Go / Rust and others in the readme!

**Comment by lissyx** [comment]
I have some pending WIP with JNI support and a simple android app making use of it.

**Comment by lissyx** [comment]
There's some basic JNI bindings exposed now.
