### ISSUE TITLE
 Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes'

### ISSUE THREAD

**Issue by KonstantinMorjan** [mozilla/DeepSpeech#1412]
Hi,

I have an issue with my deepspeech and couldn't find anything on other posts.
The only thing I found is that the tensorflow version was old (1.4.0), but mine is 1.6.0.
I have even created a new VM to see if I did something wrong in setup, but I get the same issue.

I have the latest DeepSpeech (0.1.1).
Tensorflow 1.6.0.

Running an inference with the pre-trained model works fine. No issues.
However any model I train does not work.
In my example below I was running the **bin/run-ldc93s1.sh** and used the generated **output_graph.pb**:
deepspeech data/ldc93s1/export/output_graph.pb data/ldc93s1/LDC93S1.wav data/alphabet.txt

Here is the error I'm getting:

018-06-14 19:34:22.875271: E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,988], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
2018-06-14 19:34:22.875337: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,988], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,988], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice)]]
Error running session: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,988], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,988], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice)]]

**Comment by reuben** [comment]
> The only thing I found is that the tensorflow version was old (1.4.0), but mine is 1.6.0.

That's the problem. The error message says "Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary". In your case, you're trying to interpret a GraphDef generated by TensorFlow 1.6 with a binary that was linked to TensorFlow 1.4 (our pre-built binaries).

**Comment by reuben** [comment]
You can either train with TensorFlow 1.4 or build the client from source with TensorFlow 1.6

**Comment by lissyx** [comment]
Yes, it's documented, you cannot train with r1.6 and then run inference with r1.4: https://github.com/mozilla/DeepSpeech/wiki#i-get-an-error-about-e-tensorflowcoreframeworkop_segmentcc53-create-kernel-failed-invalid-argument-nodedef-mentions-attr-identical_element_shapes-when-running-inference
