### ISSUE TITLE
 Tensorflow Install Issue 

### ISSUE THREAD

**Issue by beeteax** [mozilla/DeepSpeech#1413]
bazel build -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" //native_client:libctc_decoder_with_kenlm.so
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:deepspeech_utils //native_client:generate_trie
In tensorflow directory i ran these two commands which ran succesfully .
Following the complete 
https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md
My tensorflow is not installed .
Do I have to install it seperatly??

**Comment by lissyx** [comment]
This is not supposed to install TensorFlow, but to build `libdeepspeech`. If you want to install tensorflow, refer to TensorFlow's documentation.
