### ISSUE TITLE
dependent lib linked to non-standard path when compiling from source with tensorflow 1.4 and cuda 8.0, 

### ISSUE THREAD

**Issue by phoenixbai** [mozilla/DeepSpeech#1418]
I strictly followed the instruction here, with command as below with tf_library disabled:
`bazel build -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --incompatible_load_argument_is_label=false //native_client:libctc_decoder_with_kenlm.so`
`bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden --incompatible_load_argument_is_label=false //native_client:libdeepspeech.so //native_client:deepspeech_utils //native_client:generate_trie`

And I find that, the so libs are located here : /home/zhimo.bmz/work/tensorflow-1.4.0/bazel-out/k8-opt/bin/native_client

with LDD, find as below.  The problem I am facing is, these so libs are not portable to same linux environment due to the fact that some of dependent libs are linked to path like this:

> /home/zhimo.bmz/.cache/bazel/_bazel_zhimo.bmz/a813d17b148ea754dbbf7ff71d6f03ea/execroot/org_tensorflow/bazel-out/k8-opt/bin/native_client/./../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudart.so.8.0

> ldd libctc_decoder_with_kenlm.so
> 	linux-vdso.so.1 =>  (0x00007ffc01b90000)
> 	libtensorflow_framework.so => **/home/zhimo.bmz/.cache/bazel/_bazel_zhimo.bmz/a813d17b148ea754dbbf7ff71d6f03ea/execroot/org_tensorflow/bazel-out/k8-opt/bin/native_client/./../_solib_local/_U_S_Snative_Uclient_Clibctc_Udecoder_Uwith_Ukenlm.so___Uexternal_Sorg_Utensorflow_Stensorflow/libtensorflow_framework.so (0x00007f758d530000)**
> 	libcudart.so.8.0 => **/home/zhimo.bmz/.cache/bazel/_bazel_zhimo.bmz/a813d17b148ea754dbbf7ff71d6f03ea/execroot/org_tensorflow/bazel-out/k8-opt/bin/native_client/./../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudart.so.8.0 (0x00007f758d2ca000)**
> 	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f758d0c5000)
> 	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f758cea9000)
> 	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f758cba7000)
> 	libstdc++.so.6 => /opt/anaconda/lib/libstdc++.so.6 (0x00007f758c890000)
> 	libgcc_s.so.1 => /opt/anaconda/lib/libgcc_s.so.1 (0x00007f758c67a000)
> 	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f758c2b6000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f758e792000)
> 	libcublas.so.8.0 => /usr/local/lib/libcublas.so.8.0 (0x00007f758981c000)
> 	libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007f75889d6000)
> 	libcudnn.so.6 => /usr/local/cuda/targets/x86_64-linux/lib/libcudnn.so.6 (0x00007f757f474000)
> 	libcufft.so.8.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcufft.so.8.0 (0x00007f7576625000)
> 	libcurand.so.8.0 => /usr/local/lib/libcurand.so.8.0 (0x00007f75726ae000)
> 	librt.so.1 => /usr/lib64/librt.so.1 (0x00007f75724a6000)
> 	libnvidia-fatbinaryloader.so.384.66 => /usr/lib64/nvidia/libnvidia-fatbinaryloader.so.384.66 (0x00007f7572242000)

What I am doing wrong? How can I fix it?

**Comment by lissyx** [comment]
The tensorflow build system adds rpath for those, this makes ldd find them in your build directory, if you adjust LD_LIBRARY_PATH or ld.so.conf you should be able to get that working properly anywhere without any problem.

Look at them with `readelf -d` that should show you the rpath value :-).
