### ISSUE TITLE
how to run the final exported  pb model on hosts equipped  without  GPU

### ISSUE THREAD

**Issue by bolt163** [mozilla/DeepSpeech#1420]
the final exported  output_graph  pb model must be worked  through deepspeech on hosts  equipped with GPU,

is there any solutions to convert the pb model to working on  normal  hosts, such as hosts which was  only equipped with  cpu device?

**Comment by lissyx** [comment]
As documented in the README, you can see it runs both on pure CPU and on CUDA-enabled binaries. Just pick the proper one for your system: https://github.com/mozilla/DeepSpeech#using-the-model

**Comment by bolt163** [comment]
@lissyx  thanks very much
