### ISSUE TITLE
# Wrong Order of Arguments in the Code Examples

### ISSUE THREAD

**Issue by juax335** [mozilla/DeepSpeech#1421]
# Wrong Order of Arguments in the Code Examples

I followed the steps provided in README.md to install `deepspeech` via pip, get the pretrained model and test it on an audio file.

I initiated my virtual environment via `pipenv`

```sh
pipenv install --three
wget -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz | tar xvfz -
pipenv shell
pip3 install deepspeech
deepspeech models/output_graph.pb models/alphabet.txt models/lm.binary models/trie audio/file_3.wav
```

It seems that the **order** of the arguments in the README.md is **wrong** 

In the first paragraph and in the section `Using the Python Package/Installing DeepSpeech Python binding`:

```
deepspeech models/output_graph.pb models/alphabet.txt my_audio_file.wav
```

```
deepspeech models/output_graph.pbmm models/alphabet.txt models/lm.binary models/trie my_audio_file.wav
```

The correct order (as shown in the gif in README.md) seems to be:

```
deepspeech models/output_graph.pb audio/my_audio_file.wav models/alphabet.txt models/lm.binary models/trie 
```

Thanks for updating it or correcting me :).  And thanks for the awesome project!

**Comment by lissyx** [comment]
The order is right for master, check the `-h` of your binary it should give your proper ordering.

**Comment by juax335** [comment]
Thanks for looking into it so quickly. `-h` does give me the right order. However,  I do not understand why the commands in the displayed gif on top of the README differ from the code examples in the mentioned sections.

**Comment by lissyx** [comment]
Because the doc has been updated but not the GIF :(

**Comment by juax335** [comment]
Alright, that's an easy answer ;). Thank you for your help!
