### ISSUE TITLE
Why not using tf.layers.Dense?

### ISSUE THREAD

**Issue by bernardohenz** [mozilla/DeepSpeech#1422]
Is there a reason for not using ```tf.layers.Dense(batch_x,h1,kernel_initializer=tf.contrib.layers.xavier_initializer(uniform=False))``` instead of 

```python
b1 = variable_on_worker_level('b1', [n_hidden_1], tf.random_normal_initializer(stddev=FLAGS.b1_stddev))
h1 = variable_on_worker_level('h1', [n_input + 2*n_input*n_context, n_hidden_1], tf.contrib.layers.xavier_initializer(uniform=False))
layer_1 = tf.minimum(tf.nn.relu(tf.add(tf.matmul(batch_x, h1), b1)), FLAGS.relu_clip)
```
?

It is easier to use regularization, besides making the code more clean.

**Comment by reuben** [comment]
Originally, because it didn't exist when that code was written.

Since then, a mixture of not wanting to break the weights naming for existing models/checkpoints and... no one bothered to do it :)

**Comment by jtoy** [comment]
think we can close this then
