### ISSUE TITLE
Common Voice's cv-other-train.csv contains empty transcripts, which cause the training to crash (Labels length is zero in batch 0)

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mozilla/DeepSpeech#1423]
**Issue**: Common Voice's `cv-other-train.csv` contains 2 empty transcripts. which cause the training on `cv-other-train.csv` to crash:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Labels length is zero in batch 0
         [[Node: tower_1/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_1/logits/_1879, tower_1/ToInt64/_1881, tower_1/Gather, tower_1/Gather_1_DequeueMany:1)]]
```

However, in the current [README.md](https://github.com/mozilla/DeepSpeech/blob/28b07e45fd9a10741f2f31b4ed2d8242dba377f2/README.md), it says that one can train DeepSpeech with Common Voice on `cv-other-train.csv`:

```
./DeepSpeech.py --train_files ../data/CV/cv-valid-train.csv,../data/CV/cv-other-train.csv --dev_files ../data/CV/cv-valid-dev.csv --test_files ../data/CV/cv-valid-test.csv
```

It's not user-friendly for people going through the README.md.

**Suggestions**: 

- Remove `../data/CV/cv-other-train.csv` from the command given in `README.md`
- Amend `import_cv.py` to remove empty transcripts from `cv-other-train.csv`
- Ignore empty transcripts in `DeepSpeech.py`

**Comment by lissyx** [comment]
Thanks for that, I guess the best fix would be:
 - fix the common voice dataset, I don't know ho we should handle this, but @mikehenrty might be of help
 - fix the `import_cv` script

**Comment by mikehenrty** [comment]
> fix the common voice dataset, I don't know ho we should handle this, but @mikehenrty might be of help

`other` is our dataset that is not yet validated. there will always get bad data in there, even if we manually removed the ones in question here. users of the website will eventually move those to invalid once users try to listen to them (probably already have). so Common Voice is working as expected here, so I think the issue is only on the importer script.

**Comment by lissyx** [comment]
@mikehenrty I missed the fact that this was with other. I guess we should also update the doc with some warning on that point.
