### ISSUE TITLE
Why does the README not suggest to pass lm and trie files?

### ISSUE THREAD

**Issue by nh2** [mozilla/DeepSpeech#1429]
From the README:

> `deepspeech models/output_graph.pb models/alphabet.txt my_audio_file.wav`

Why does this not suggest to also pass `models/lm.binary` and `models/trie`?

I get much better accuracry when those are passed, compare:

```
tearest creature in creation stydy englich pronunciation i wul teacher in my verse sounds like corps cor hors and worse
```

to

```
dearest creature in creation study english pronunciation i will teach you in my verse sounds like corps core horse and worse
```

Putting the files into the README instructions might make for a much better first impression when people try DeepSpeech.

**Comment by lissyx** [comment]
@nh2 Patches are welcome, it's likely that we are used to doing so, and the command line documents it, so we forgot to update the README on that specific point.
