### ISSUE TITLE
pip3 install deepspeech is incompatible with v0.11 pre-built model

### ISSUE THREAD

**Issue by Cloudmersive** [mozilla/DeepSpeech#1446]
pip3 install deepspeech is incompatible with v0.11 pre-built model.  

```
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/binary_format.cc:131 in void lm::ngram::MatchCheck(lm::ngram::ModelType, unsigned int, const lm::ngram::Parameters&) threw FormatLoadException.
The binary file was built for probing hash tables but the inference code is trying to load trie with quantization and array-compressed pointers
Aborted (core dumped)
```

Can you  update the deepspeech on pip to support the 0.11 model or vice versa?

**Comment by kdavis-mozilla** [comment]
It appears as if you have not installed `deepspeech` using
```bash
pip3 install deepspeech
```
but installed `deepspeech` using some other method as you appear to have a post v0.1.1 version of `deepspeech` and not a v0.1.1 version of `deepspeech` and are trying to use this with a v0.1.1 model version.

Could you describe in detail your installation process and any previous installs of `deepspeech` that may be on your machine.

**Comment by lissyx** [comment]
@Cloudmersive This error makes no sense. If you use `pip install deepspeech` and v0.1.1 model, they are in sync. Your error message suggest using 0.1.1 binary and current master language model files.

**Comment by lissyx** [comment]
@kkshmz Your console output shown 0.2.0 alpha 6, your pip list shows 0.1.1. What are you using, precisely ? Where is your lm.binary and trie from ?

**Comment by kkshmz** [comment]
I have only used to pip to install and have used the link in the readme.

**Comment by lissyx** [comment]
@kkshmz We need more details.

**Comment by lissyx** [comment]
Works for me:
```
alex@portable-alex:~/tmp/deepspeech/cpu$ ./deepspeech --model ../models/output_graph.pbmm --alphabet ../models/alphabet.txt --lm ~/codaz/Mozilla/DeepSpeech/deepspeech-kdavis/data/lm/lm.binary --trie ~/codaz/Mozilla/DeepSpeech/deepspeech-kdavis/data/lm/trie --audio ../audio/ -t
TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.6-21-gdc301f3
2018-07-10 09:14:15.423974: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Running on directory ../audio/
> ../audio//2830-3980-0043.wav
experience proves this
cpu_time_overall=4.52897 cpu_time_mfcc=0.00275 cpu_time_infer=4.52622
> ../audio//4507-16021-0012.wav
why should one halt on the way
cpu_time_overall=5.72224 cpu_time_mfcc=0.00319 cpu_time_infer=5.71905
> ../audio//8455-210777-0068.wav
your power is sufficient i said
cpu_time_overall=5.49385 cpu_time_mfcc=0.00341 cpu_time_infer=5.49044
alex@portable-alex:~/tmp/deepspeech/cpu$
```

**Comment by lissyx** [comment]
@kkshmz So my guess is that you are not using the proper language model file. We changed the format, the one in 0.1.1 archive is not good with 0.2.0 alpha 6 binaries.

**Comment by Cloudmersive** [comment]
You can reproduce this by making a Docker file like this:

```
FROM python:latest


RUN pip3 install --upgrade pip

RUN pip install --upgrade pip

RUN pip3 install deepspeech

RUN apt-get install wget

WORKDIR /model

RUN wget -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.1.0/deepspeech-0.1.0-models.tar.gz | tar xvfz -
```

**Comment by lissyx** [comment]
@Cloudmersive Can you be more specific on the actual python version being used ?
Can you reproduce using verbose pip install ?
Can you use 0.1.1 model files and not 0.1.0 ?
Can you use verbose pip install step ?

**Comment by lissyx** [comment]
`python:latest` might pull 3.7 build. I'm not sure exactly what `deepspeech` release it might get you in this case, because we only have some 0.2.0 alpha builds for Python 3.7. Which would be incompatible with the language model bundled in 0.1.1 tar.gz you are using.

**Comment by lissyx** [comment]
cp37m:
 - https://pypi.org/project/deepspeech/0.2.0a6/#files
 - https://pypi.org/project/deepspeech/0.2.0a7/#files

**Comment by lissyx** [comment]
@Cloudmersive It works for me, without a language model: https://taskcluster-artifacts.net/C2EdU2DKQKeUxgwHWDUsIg/0/public/logs/live_backing.log

And as I expected, it did download 0.2.0a7. So the error reported is just mismatch of the language model until we release proper 0.2.0 ...

**Comment by lissyx** [comment]
We are reverting to the old language model for now in #1465

**Comment by lissyx** [comment]
So, revert is applied and new Python wheel and NPM packages have been uploaded. New language model should come back, in the future :-).
