### ISSUE TITLE
Transcription mode for long audio files

### ISSUE THREAD

**Issue by renderpci** [mozilla/DeepSpeech#1448]
Hi to all.

I don't know if this thread is the place to put this kind of message, sorry If not.

Well, I see that the project only process 5 seconds of audio files and I read some threads about the long files with very creative solutions to this "situation", split audiofiles with "phrases", etc.

I don't know if the community are thinking in other use of the DeepSpeech other than "short commands". For ex transcriptions of the interviews. We have a open source project for management Oral History https://github.com/renderpci/dedalo-4 and for us will be amazing if Deep Speech can do this. In Oral History the interviews are 1hour ~ 2 hour long, and only big companies or large institutions can build a Speech to Text models for do this task.

Is very heavy do the transcription of the interviews for small projects and automatic task /help can be great for the Oral History community.

Are you thinking in build a "transcription mode"? can be part of the future plans?

We are very grateful for this initiative.
Really, Thanks.
Alex

**Comment by lissyx** [comment]
@renderpci This discussion should take place on Discourse: https://discourse.mozilla.org/c/deep-speech.

**Comment by lissyx** [comment]
When taking the discussion to Discourse, please be clear in stating what is not good / enough in the current shape of the project. Your description feels like your only limitation is about audio file length, which can be circumvented with spltting the audio as you said.
