### ISSUE TITLE
Early_Stop not stoppable

### ISSUE THREAD

**Issue by tarekeldeeb** [mozilla/DeepSpeech#1460]
I'm using Deepspeech to train a new arabic net. I'm still in the early phases where I'm still exploring many hyper parameters. I wish to disable the early_stop feature.

In my run script, I have the following option:

      --early_stop False \

I also tried `0` instead of `False`, but unfortunately, early_stops are still triggered.

**Comment by kdavis-mozilla** [comment]
Arabic, nice!

Setting early stopping using ``False`` looks right.

What behaviour are you seeing exactly? What is the output of the training run?

**Comment by reuben** [comment]
Try `--noearly_stop`.

**Comment by tarekeldeeb** [comment]
Thanks @reuben , that fixed the issue.
