### ISSUE TITLE
 tensorflow.python.framework.errors_impl.NotFoundError: /home/nvidia/tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

### ISSUE THREAD

**Issue by elpimous** [mozilla/DeepSpeech#1467]
**TensorFlow**: v1.6.0-18-g5021473
**DeepSpeech**: v0.2.0-alpha.7-10-gea21010
**cuda**: 9.0 cudnn: 7.0
**bazel**: 0.10.0

**Sys** : ubuntu 16.04
**board**: Jetson TX2

---------------------------------------------------------------------------
Hi all,

I had this error, when trying deepspeech after builds !

**POSSIBLE SOLUTION** 

For those who built Tensorflow from source, with a bazel version >= 5.0
you don't need the next Flag : **D_GLIBCXX_USE_CXX11_ABI=0**

so, you can build native client replacing : 

```
bazel build -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" //native_client:libctc_decoder_with_kenlm.so

bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:deepspeech_utils //native_client:generate_trie
```

by: 

```
bazel build -c opt --copt=-O3  //native_client:libctc_decoder_with_kenlm.so

bazel build --config=monolithic -c opt --copt=-O3 --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:deepspeech_utils //native_client:generate_trie
```

It worked for me.
Hope it will help each other.

**Comment by lissyx** [comment]
@elpimous I know you are building your own TensorFlow, is it possible your Python wheel was built *without* `-D_GLIBCXX_USE_CXX11_ABI=0` ? If so, then it's consistent and therefore not an issue.

**Comment by lissyx** [comment]
Yeah, looking at our IRC history, that's likely why.
