### ISSUE TITLE
Starting batch slow.. GPU Utilization from 0 to 100% in each batch

### ISSUE THREAD

**Issue by kalfasyan** [mozilla/DeepSpeech#1468]
Hi, I am running a training session for the Common Voice data which I downloaded/extracted using the import_cv.py script. Everything seems to work fine, but I just want to ask if it's normal for the GPU utilization to be unstable and not (relatively) constant.

For example, that's what I see 

> D Starting batch... # GPU utilization is 0 at this point for some time
> D Finished batch step 12325.
> D Sending Job (ID: 10223, worker: 0, epoch: 0, set_name: train)...
> D Computing Job (ID: 10224, worker: 0, epoch: 0, set_name: train)... # GPU util goes 100% for a few seconds
> D Starting batch... # GPU util becomes 0 again
> ...

The CPU utilization on the other hand seems to be almost always at 100% (it grows to more from time to time, due to distributing to other processors I presume).

(At the moment I'm using one 1070 8GB)

**Comment by lissyx** [comment]
Can you share the training parameters you are using ?

**Comment by kalfasyan** [comment]
train/test/dev batch size = 16
validation_step = 1
display_step = 1

**Comment by lissyx** [comment]
Yeah, it might be WER computation that is CPU-bound that kicks-in often with validation. GPU usage might relate to your batch size you should try and increase it. Also, one single GTX1070 8GB is not very very fast for training on that amount of data :)

**Comment by kalfasyan** [comment]
Yes, you are right that one 1070 will take a lot of time (1 epoch completed in about three days), but I have some mobo/hardware issues and I'm still experimenting (aiming for 6x1070; hopefully they'll do the job much quicker). 

I now increased the batch size to 32 and made a second GPU available for training, but the GPU utilization of both GPUs goes to 0 and then to 100 for a few seconds and back to 0 again. Is there any other computation that is CPU-bound (some preprocessing that I'm missing)?

**Comment by lissyx** [comment]
well, generally speaking that behavior is a hint that your system is spending more time loading than processing. we have have data ordering per length, as much as I remember, so short clips first ; it might just be that, since those will be faster to process on the GPU. Try to reduce both validation and display step, also

**Comment by kalfasyan** [comment]
After making display and validation to 20, I have constantly high GPU utilization in both GPUs and much faster processing of the batches. Thank you very much!
