### ISSUE TITLE
Inference on RPi3 fails when using Trie AND lm

### ISSUE THREAD

**Issue by rpszabad** [mozilla/DeepSpeech#1469]
I got DeepSpeech running on the RPi3 using the native client, got version v.0.2.0-alpha.7-13-gda760bd. Running `./deepspeech --model /model.pbmm --alphabet alphabet.txt --audio audio.wav` works fine using the pre-trained model, albeit expectably slow. What baffles me now is the following fact:

`./deepspeech --model /model.pbmm --alphabet alphabet.txt --lm lm.binary --audio audio.wav` and
`./deepspeech --model /model.pbmm --alphabet alphabet.txt --trie trie --audio audio.wav` 

will both work, while

`./deepspeech --model /model.pbmm --alphabet alphabet.txt --lm lm.binary  --trie trie --audio audio.wav` 

immediatelly ends with the following error

`TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.7-13-gda760bd
terminate called after throwing an instance of 'util::ErrnoException'
  what():  native_client/kenlm/util/mmap.cc:122 in void* util::MapOrThrow(std::size_t, bool, int, bool, int, uint64_t) threw ErrnoException because '(ret = mmap(__null, size, protect, flags, fd, offset)) == ((void *) -1)'.
Cannot allocate memory mmap failed for size 1599616228 at offset 0
Aborted
`

Are these not supposed to work together or am I going wrong somewhere? And how much would lm and trie influence inference, when added?

**Comment by lissyx** [comment]
It should work. We switched back to the 1.5gb language model temporarily, that's likely why the memory fails to allocate. Try without language model to check.

**Comment by rpszabad** [comment]
You mean without the `--lm` option? Works fine.

**Comment by lissyx** [comment]
@rpszabad Yes, without `--lm` and `--trie`. You cannot for now, we need to do some work. Performances are anyway too bad for the moment to make any useful usage, as you experienced.

Re-reading your issue, the size 1599616228 really looks like the original, big model. Which is not compatible with the 0.2.0-alpha-7 binaries.
