### ISSUE TITLE
Getting "feed_dict" used before assignment when initializing from frozen model

### ISSUE THREAD

**Issue by kalfasyan** [mozilla/DeepSpeech#1472]
Hi, I am trying to run DeepSpeech with my own data by continuing from frozen graph like instructed [here](https://github.com/mozilla/DeepSpeech#continuing-training-from-a-frozen-graph).
However, I am getting this error:  
`UnboundLocalError: local variable 'feed_dict' referenced before assignment`

The problem seems to be coming from line 1604, where in `session.run(init_from_frozen_model_op, feed_dict=feed_dict)`, you pass feed_dict=feed_dict but I suppose you intended to pass "no_dropout_feed_dict". Is that correct or am I missing something?

**Comment by lissyx** [comment]
And as much as I remember, you wre right on the fix. I'll look into that and ensure we have test coverage as well

**Comment by kalfasyan** [comment]
Ok thanks. Feel free to close the issue when fixed and give me an update in the end if you wish.
