### ISSUE TITLE
docker build failed with error: error loading package 'native_client'

### ISSUE THREAD

**Issue by gilamsalem** [mozilla/DeepSpeech#1474]
I am trying to build a docker image on my mac osx machine.
I am getting the following errors:

```
ERROR: Skipping '//native_client:libctc_decoder_with_kenlm.so': error loading package 'native_client': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
...
Cuda Configuration Error: cuDNN version detected from /usr/lib/x86_64-linux-gnu/include/cudnn.h (7.1.4) does not match TF_CUDNN_VERSION (7.1.1)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'native_client': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
```

I also see those two warnings before:
tensorflow 1.6.0 has requirement numpy>=1.13.3, but you'll have numpy 1.11.0 which is incompatible.
tensorboard 1.6.0 has requirement numpy>=1.12.0, but you'll have numpy 1.11.0 which is incompatible.

What should I do?
Thanks!

**Comment by lissyx** [comment]
@GeorgeFedoseev did worked on this Dockerfile. I'm really not sure what you can expect of running that ubuntu+cuda based docker on osx, especially because Docker with CUDA requires specific handling on the host side.

**Comment by lissyx** [comment]
@gilamsalem Maybe you should change the Dockerfile to not depend on CUDA and only build libctc decoder ? What is your usecase ?
