### ISSUE TITLE
requirements.txt is missing git module

### ISSUE THREAD

**Issue by tarekeldeeb** [mozilla/DeepSpeech#1478]
- OS Platform: Linux Ubuntu 16.04

During training I started
> python bin/gpu_usage_chart

which invoked util/automation.py with a missing dependency "git"

> Traceback (most recent call last):
>   File "bin/gpu_usage_chart", line 8, in <module>
>     from util.automation import GPUUsage
>   File "/home/teldeeb/ai/DeepSpeech/util/automation.py", line 8, in <module>
>     import git
> ModuleNotFoundError: No module named 'git'

Please update the requirements.txt with the missing git module.

**Comment by lissyx** [comment]
This code is something I was thinking of deleting. Any opinion @reuben. ?

**Comment by reuben** [comment]
I'm all for removing code :) If there's any compelling use case for some of its functionality we can trim it down.

**Comment by lissyx** [comment]
@tarekeldeeb This was old code mostly tailored for our own use, I'm curious how it can help you

**Comment by lissyx** [comment]
@tarekeldeeb Can you test on your side the PR #1479 ? I should keep the GPU usage feature but not depend anymore on specfic python modules.
