### ISSUE TITLE
 build the binaries and bindings from source code myself. I got `undefined symbol` error after make bindings.

### ISSUE THREAD

**Issue by hongguangguo** [mozilla/DeepSpeech#1481]
`from deepspeech.model import Model`
when run the code, I got this.

> /home/miniconda3/envs/ds/lib/python3.5/site-packages/deepspeech/_model.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN10DeepSpeech5Model14getInputVectorEPKsjiPPfPiS5_

**Comment by lissyx** [comment]
Can you give more details? Versions used, etc. Also, why rebuilding since we have py35 wheels?

**Comment by hongguangguo** [comment]
Thank your reply. My carelessness. there is no so file in the directory for g++ -L .
