### ISSUE TITLE
Language model built using test and dev data

### ISSUE THREAD

**Issue by samgd** [mozilla/DeepSpeech#1485]
The current 5-gram language model `lm.binary` contains the test and development datasets - this statement is based on the following example code that shows it contains _all_ five grams from `test-clean`, `test-other`, `dev-clean`, and `dev-other`.

Requirements to run the minimal example: a `.txt` file for each of the four dataset that contains one target transcription per line.

```python3
import kenlm
import os

from nltk import ngrams
from urllib import request

url = 'https://github.com/mozilla/DeepSpeech/raw/master/data/lm/lm.binary'
lm_file = '/tmp/lm.binary'
if not os.path.isfile(lm_file):
    request.urlretrieve(url, lm_file)

model = kenlm.Model('/tmp/lm.binary')

dataset_files = ['/tmp/test-clean.txt',
                 '/tmp/test-other.txt',
                 '/tmp/dev-clean.txt',
                 '/tmp/dev-other.txt']

for dataset_file in dataset_files:
    
    with open(dataset_file, 'r') as dataset:
        in_ = set()
        out = set()
        
        for sentence in dataset:
            # Remove apostrophes as LM excludes them.
            sentence = ''.join(filter(lambda s: s != "'", sentence))
            
            for ngram_parts in ngrams(sentence.split(), 5):
                ngram = ' '.join(ngram_parts)
                match_lens = model.full_scores(ngram)
                        
                if list(match_lens)[4][1] != 5:
                    out.add(ngram)
                else:
                    in_.add(ngram)
        
        print(dataset_file + ':')
        print('\tin: %d, out: %d' % (len(in_), len(out)))
```

This produces:

```
/tmp/test-clean.txt:
	in: 42088, out: 0
/tmp/test-other.txt:
	in: 40515, out: 0
/tmp/dev-clean.txt:
	in: 43614, out: 0
/tmp/dev-other.txt:
	in: 39457, out: 0
```

**Comment by samgd** [comment]
@kdavis-mozilla Do you think it's worth noting this on the 1.X release notes next to the WER claim?

**Comment by kdavis-mozilla** [comment]
@samgd What's you opinion on how we should modify the WER text?

Should we just note that the WER is inaccurate? Maybe try to re-optimize with a new language model and update the WER text? Or maybe something else?

As an outside party I'd be interested in your take on this.

**Comment by kdavis-mozilla** [comment]
@samgd I'm sorry it's impacted your research. I've updated the release notes, striking out the word error rates and indicating why they were striked out. Hopefully that will prevent future problems.

As to a collaboration, we'd love to collaborate on creating a new language model. See you on IRC!
