### ISSUE TITLE
Error in building the deepspeech library from native client

### ISSUE THREAD

**Issue by sshabana** [mozilla/DeepSpeech#1489]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:https://github.com/mozilla/tensorflow/
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.15
- **Exact command to reproduce**: bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.
i am trying to build the native_client for deepspeech from https://github.com/mozilla/DeepSpeech/tree/master/native_client .  on running the bazel commands
```
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
```

 i am getting the below error.

```
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
ERROR: /home/shabana/.cache/bazel/_bazel_shabana/53a74e5b211539a7dabefae2f7fc794a/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//native_client:libdeepspeech.so' failed; build aborted:

/home/shabana/.cache/bazel/_bazel_shabana/53a74e5b211539a7dabefae2f7fc794a/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 0.778s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

i want to build the deepspeech libraries.

**Comment by lissyx** [comment]
First, what is wrong for you not using prebuilt binaries ? Second, you document our TensorFlow fork **and** TensorFlow 1.9, which makes no sense since we are still relying on `r1.6`. Third, Bazel 0.15 is likely not the proper version, since upstream TensorFlow `r1.6` documents 0.10.

**Comment by lissyx** [comment]
@sshabana It's very likely to be just because of Bazel 0.15, use 0.10.

**Comment by kenogo** [comment]
Can confirm, it's because of the bazel version.

**Comment by lissyx** [comment]
Thanks @kenogo, closing!
