### ISSUE TITLE
A feature request：How can I judge user intentions ？

### ISSUE THREAD

**Issue by gangyahaidao** [mozilla/DeepSpeech#1496]
Hello，
I have a need for speech recognition now, and I have read many documents of this project, but I am still not sure whether this project can meet my need：

Now I have hundreds of thousands of wav audio files, which are only one to five seconds and divided into two categories, one is positive answer, the other is negative answer, but I do not have the text information corresponding to each wav file, now my demand is whether I can use DeepSpeech to make intention judgment？

For example, if I input an audio data, then I can get the intention expressed by this audio, but there is no text corresponding to this audio

Any help will be greatly appreciated！

**Comment by kdavis-mozilla** [comment]
This project can not directly solve your problem. However, an architectural variation of Deep Speech could likely solve your problem, e.g. adding a softmax that takes the final state of the RNN as input. 

One idea might be to fork Deep Speech, add such an architectural variation, use Deep Speech model as initialization, and fine tune with your data.

However, as this is not central to Deep Speech. I'm going to close this issue.

**Comment by gangyahaidao** [comment]
Thank you, change the existing framework in the short term I should is impossible, so I'm going to try this project supported by the way, first annotation about ten thousand audio data for training, each of the audio is about 1 to 3 seconds, don't know if this can get a good result

I'm going to is a reference to this article on the small language model training.
[https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830](https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830)
