### ISSUE TITLE
fine tuning from frozen model ends with ValueError: Requested return_element 'lstm_fused_cell/kernel:0' not found in graph_def.

### ISSUE THREAD

**Issue by pvanickova** [mozilla/DeepSpeech#1503]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: added word_count_weight=1.00 in decode_with_lm into Deepspeech.py to make it compatible with client downloaded from taskcluster branch 0.2.0a8 (not using 0.2.0a9 as I understood that no compatible models have been released for it yet)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream tensorflow installed using requirements.txt
- **TensorFlow version (use command below)**:v1.6.0-0-gd2e24b6039 1.6.0
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: Tesla M60 
- **Exact command to reproduce**:

`python3 DeepSpeech.py --n_hidden 2048 --initialize_from_frozen_model ../models/output_graph.pb --checkpoint_dir fine_tuning_checkpoints --export_dir fine_tuning_model --epoch 3 --train_files ../data/training/transcript.csv --dev_files ../data/dev/transcript.csv --test_files ../data/test/transcript.csv --learning_rate 0.0001`

using models downloaded from https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz

stack trace: 
```
/home/ubuntu/tmp/deepspeech-venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ubuntu/tmp/deepspeech-venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ubuntu/DeepSpeech/util/audio.py:17: DeepSpeechDeprecationWarning: DeepSpeech Python bindings could not be imported, resorting to slower code to compute audio features. Refer to README.md for instructions on how to install (or build) the DeepSpeech Python bindings.
  category=DeepSpeechDeprecationWarning)
W Parameter --validation_step needs to be >0 for early stopping to work
Traceback (most recent call last):
  File "/home/ubuntu/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 764, in import_graph_def
    ret.append(name_to_op[operation_name].outputs[output_index])
KeyError: 'lstm_fused_cell/kernel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1945, in <module>
    tf.app.run(main)
  File "/home/ubuntu/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1901, in main
    train()
  File "DeepSpeech.py", line 1566, in train
    var_tensors = tf.import_graph_def(graph_def, return_elements=var_names)
  File "/home/ubuntu/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 767, in import_graph_def
    'Requested return_element %r not found in graph_def.' % name)
ValueError: Requested return_element 'lstm_fused_cell/kernel:0' not found in graph_def.
```

**Comment by lissyx** [comment]
@pvanickova You cannot fine-tune v0.1.1 model using current master.

**Comment by pvanickova** [comment]
so the only way to fine tune the latest released model at the moment is to use 0.1.1 source code from release, correct? if so, do I need TF 1.4 or can I keep 1.6?

**Comment by lissyx** [comment]
@pvanickova Use latest commit from master before we landed the new model, so detaching at https://github.com/mozilla/DeepSpeech/commit/e00bfd0f413912855eb2312bc1efe3bd2b023b25 should be okay. As you can read from `requirements.txt`, `r1.6` is good.

@reuben might have some pending model shareable for fine tuning, with this new architecture?

**Comment by reuben** [comment]
We'll share a checkpoint with the v0.3 release.

**Comment by kdavis-mozilla** [comment]
I think @reuben meant the v0.2 release, i.e. the next release.

**Comment by reuben** [comment]
Yes, I did :)

**Comment by pvanickova** [comment]
so this worked for me (in combination with TF-GPU 1.6 from pip3 and model 0.1.1):
`git checkout e00bfd0`

after that, running a test fine tuning with a couple of hundreds training wavs completed successfully (in about 20 minutes, running on amazon's g3.4xlarge with Tesla M60 - 8GB of RAM)

Do you have any guesstimate on 0.2 ETA?

thanks for the support

**Comment by DWhettam** [comment]
Please could you expand a little more on your setup @pvanickova? I've been having the same issue, and when I tried training from model 0.1.1 I'm getting the following error:
`TypeError: ctc_beam_search_decoder_with_lm() got an unexpected keyword argument 'word_count_weight'`

After doing 

`git clone https://github.com/mozilla/DeepSpeech`

 are you then doing "git checkout e00bfd0", and then proceeding as normal? I'm using 

`wget -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz | tar xvfz -`

to get the model. Is that correct? And and are you then simply doing

```
pip3 uninstall tensorflow
pip3 install 'tensorflow-gpu==1.6.0'
```
to get TF-GPU 1.6?

Cheers

**Comment by pvanickova** [comment]
@DWhettam make sure, you're using  client version 0.2.0a8 (not the latest version 0.2.0a9) , obtained by:

`python3 util/taskcluster.py --arch gpu --branch v0.2.0-alpha.8 --target native_client`

**Comment by DWhettam** [comment]
Thank you @pvanickova! That seems to have fixed it
