### ISSUE TITLE
bazel --batch mode is deprecated

### ISSUE THREAD

**Issue by NicoHood** [mozilla/DeepSpeech#1507]
For 0.2.0.alpha9:

```
$ ./configure
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.16.0- (@non-git) installed.
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=tensorrt    	# Build with TensorRT support.
Configuration finished
```

It should be better fixed sooner than later. I am on ArchLinux.

**Comment by lissyx** [comment]
Thanks, but with TensorFlow r1.6 that we still use, Bazel 0.10 is recommended, so it's actually not a big deal. People reported being unable to build at all with too new bazel as well (0.15 I guess). We'll deal with that when we move to newer tensorflow (hopefully soon).

**Comment by lissyx** [comment]
This will happen with #1520

**Comment by lissyx** [comment]
@NicoHood So, it seems like this is not an issue on our side, but some TensorFlow upstream code, as you can see from current master: https://github.com/tensorflow/tensorflow/blob/0d8942fcbcc9cb3a05be8acc843d1fc4b6dfc9f1/configure.py#L450

You should report that to them.
