### ISSUE TITLE
train_batch = 1 not run all train files

### ISSUE THREAD

**Issue by djpg** [mozilla/DeepSpeech#1508]
- **Deepspeech**: 0.2.0a5
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: 9.0/7.1
- **GPU model and memory**: 2 x gtx 1080 ti
- **Exact command to reproduce**: 
``` bash
./DeepSpeech.py --train_files /home/enigma-admin/DeepSpeech/data/CV/cv-valid-train.csv --dev_files /home/enigma-admin/DeepSpeech/data/CV/cv-valid-dev.csv --test_files /home/enigma-admin/DeepSpeech/data/CV/cv-valid-test.csv --decoder_library_path /home/enigma-admin/ASR-CLARA/models/language/libctc_decoder_with_kenlm.so --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 2048 --epoch 500 --checkpoint_dir /home/enigma-admin/DeepSpeech/models/session/ --summary_dir /home/enigma-admin/DeepSpeech/models/summary/ --summary_secs 25 --export_dir /home/enigma-admin/DeepSpeech/models/modelo/ --validation_step 1 --earlystop_nsteps 1000
```
I'm training with common voice dataset (I call before: ``bin/import_cv.py /home/enigma-admin/DeepSpeech/data/CV``

So in _cv-valid-train_ folder there are 195.776 wav's files but in cv-valid-train.csv there are 193.284 lines. But when I set train_batch_size = 1, in each epoch seems that deepspeech only train with 96.642 files (see the bottom figure).
![batch](https://user-images.githubusercontent.com/25202539/44520660-cb5bce80-a6d0-11e8-94a6-ffd5d0852ffa.png)

The same thing happens when I use a custom dataset, it seems in the epoch that not all wav's files are using to train the model.

**Comment by reuben** [comment]
96.642 is 193.284/2. You have two GPUs, so each step is actually two batches.

**Comment by reuben** [comment]
Or, put another way, the algorithmic batch size is number_of_GPUs times the value of the `--train_batch_size` flag.
