### ISSUE TITLE
No OpKernel error when running inference on v0.2.0-alpha.9

### ISSUE THREAD

**Issue by mathematiguy** [mozilla/DeepSpeech#1512]
Hi there,

At the moment, I am dealing with the following error:

```bash
deepspeech \
	--model models/machine_approved_model/output_graph.pb \
	--alphabet models/machine_approved_model/alphabet.txt \
	--lm models/machine_approved_model/lm.binary \
	--trie models/machine_approved_model/trie \
	--audio ../data/wav/120165/167429.wav
Loading model from file models/machine_approved_model/output_graph.pb
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-08-29 09:43:38.086905: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Invalid argument: No OpKernel was registered to support Op 'Pack' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: lstm_fused_cell/stack_1 = Pack[N=2, T=DT_INT32, axis=1](input_lengths, lstm_fused_cell/range_1)]]
Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/client.py", line 76, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 3
```

At the moment, my guess is that the code to build a model using the streaming architecture hasn't been implemented yet. I have locked my version of DeepSpeech at commit fe5305c081.

Can anyone confirm if my efforts to resolve the error without downgrading are futile? If it is possible to resolve the error now, then I would like to continue. Otherwise I'll downgrade the DeepSpeech bindings (which wouldn't be the end of the world) and continue with the BiRNN architecture model for now.

I am particularly confused by the difficulty of performing inference because deepspeech does inference at the end of training anyway - I'm not sure why inference doesn't work in this situation.

Platform info: I am currently using docker images with the following specs
- Linux Ubuntu 16.04
- `Tensorflow v1.6.0-0-gd2e24b6039` (not using your builds, but open to the idea if that resolves the issue)
- `Python 3.6.6`

Thanks very much

**Comment by mathematiguy** [comment]
It was the product of a train just a few days ago, I believe with DeepSpeech and native_client v0.2.0-alpha.9

If you need more detail than that, you’ll need to be more specific I’m sorry.

The commit of DeepSpeech we locked down at was after the bump to v0.2.0-alpha.9 so I took the effort to make sure we got the right native_client from taskcluster. Because of this, I believe, training the model seemed to go off without a hitch.

**Comment by mathematiguy** [comment]
It sounds like I need to downgrade for the time being. Is v0.2.0-alpha.8 ok? Or do I have to go all the way back to v0.1.0 (pre-streaming inference)

It’s okay, I can always upgrade later

**Comment by mathematiguy** [comment]
I did have the DeprecationError while training, so I believe the python bindings I was using during the train were ‘DeepSpeech-GPU==0.1.1’

**Comment by sidedger** [comment]
I had installed the v0.2.0-alpha.9-0. If you remove the model parameter, deepspeech would load the built-in model. 
But I don't run the model successfully. It occur a Segmentation fault.(core dumped)

**Comment by kdavis-mozilla** [comment]
@mathematiguy I just wanted to establish that you were _not_ using our 0.1.1 or 0.1.0 pretrained models. If I understand correctly, you're using a model you trained yourself?

If that's so, what did you mean by the statement:

> At the moment, my guess is that the code to build a model using the streaming architecture hasn't been implemented yet.

This confuses me as to me as it suggests that you did _not_ train your own model as it implies you believe the the code to build a model is not there, but later on[[1](https://github.com/mozilla/DeepSpeech/issues/1512#issuecomment-416911903)] your comment implies you that you trained your own model using v0.2.0-alpha.9.

**Comment by kdavis-mozilla** [comment]
@mathematiguy One suggestion is also to use our build of tensorflow.

**Comment by mathematiguy** [comment]
Hi- I definitely trained the model myself. You can discard the confusing comment I made, in hindsight it doesn’t contribute anything valuable.

I want to try using your build of tensorflow, I’ve just been confused by the documentation so far. In any case, if that’s necessary for this to work then it would be worth it.

**Comment by mathematiguy** [comment]
For posterity, I found running inference on a trained model worked fine when I downgraded to v0.2.0-alpha.7. I definitely want to build DeepSpeech's Tensorflow myself, because we have implemented language specific modifications to the language model - but we haven't had time to do that with the available funding.

In any case, thanks for your help - I'll close the issue now.
