### ISSUE TITLE
How to combine my own custom model and pretrained deepspeech language model? 

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/DeepSpeech#1515]
Sir I have my own trained model. but it is working for that particular trained audios only. how to combine deepspeech pretrained language model, else other common voice model. sir help me. i am very low knowledge about this topic. thank you sir.

**Comment by MuruganR96** [comment]
sir, not needed Continuing training from a frozen graph.  any other way?

**Comment by kdavis-mozilla** [comment]
@MuruganR96 As this is not really a bug or request for enhancement, could you please move the discussion to Discourse[[1](https://discourse.mozilla.org/c/deep-speech)]. Thanks.
