### ISSUE TITLE
How do i working on completely other language like TAMIL for speech to text.?  

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/DeepSpeech#1516]
please sir share your thoughts, ideas and suggestions.

**Comment by MuruganR96** [comment]
if i feed other languages alphabets in that alphabet.txt, feed audio with similar language sentence, vocabulary.txt to feed that language sentence. and then create a lm.arpa, lm.binary and trie files. this steps is enough or will do some another steps? thank you sir

**Comment by kdavis-mozilla** [comment]
@MuruganR96 As this is not really a bug or request for enhancement, could you please move the discussion to Discourse[[1](https://discourse.mozilla.org/c/deep-speech)]. In particular there is a discussion there[[2](https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830)] that addresses much of your question. Thanks.
