### ISSUE TITLE
Inference prediction with own trained model

### ISSUE THREAD

**Issue by djpg** [mozilla/DeepSpeech#1524]
- **OS Platform and Distribution**: Ubuntu 16.04
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: 9.0/7.1
- **GPU model and memory**: 2 x gtx 1080 ti

I have trained my own model with my own data (8 kHz) and I would like make predictions but I can't do it. (I modified _client.py_ script to allow 8KHz audios)

**Experiment 1:**
- **Deepspeech**: 0.2.0a8
- **TensorFlow version**: tensorflow-warpctc 1.6.0 (build from source)
Model trained with deepspeech 0.2.0a8

``` bash
$ python native_client/python/client.py --model models/output_graph_0a8.pb
--alphabet models/alphabet.txt --lm models/5gram.klm --trie models/trie --audio data/audio_1.wav

Loading model from file models/output_graph_0a8.pb
TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.8-0-gcd47560
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-09-07 08:48:42.331571: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: Op type not registered 'BlockLSTM' in binary running on david-desktop. Make sure the Op and Kernel are registered in the binary running in this process.
Loaded model in 0.118s.
Loading language model from files models/5gram.klm models/trie
Loaded language model in 0.0787s.
Running inference.
Segmentation fault (core dumped)

```

**Experiment 2:**
- **Deepspeech**: 0.2.0a9
- **TensorFlow version**: tensorflow-warpctc 1.6.0 (build from source)
Model trained with deepspeech 0.2.0a9. In this case it's seems that make the prediction but is wrong since the audio is used in the train dataset.

```bash
$ python native_client/python/client.py --model models/output_graph_0a9.pb 
--alphabet models/alphabet.txt --lm models/5gram.klm --trie models/trie --audio data/audio_0.wav

Loading model from file models/output_graph_0a9.pb
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-09-07 09:42:49.747845: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.085s.
Loading language model from files models/5gram.klm models/trie
Loaded language model in 0.192s.
Running inference.
te te v pal
Inference took 3.998s for 10.450s audio file.
```

**Comment by kdavis-mozilla** [comment]
@djpg We try to reserve issues for bugs or enhancements to the code. As you've added your own modifications to the code and trained your own models, the best place to discuss this topic is on our discourse forum[[1](https://discourse.mozilla.org/c/deep-speech)].

**Comment by lissyx** [comment]
Thanks, but that does not seems to be a bug. In experiment 1, I don't even understand why you get this `BlockLSTM` issue, since there is no code referring to it: https://github.com/mozilla/DeepSpeech/blob/v0.2.0-alpha.8/DeepSpeech.py#L430-L441

For experiment two, there is not enough informations on your training conditions to see if there is anything problematic. Please be advised that we are still working on a model based on that version as well.

Also, you are using 8kHz, so maybe some hyperparameters we have behave better with 16kHz.

Your training should not even require building our tensorflow, but rather please use the upstream python package.

**Comment by djpg** [comment]
@lissyx thanks for your reply.
I need to train my own spanish model so I only have 8 KHz audios. So I've trained the model with 3 differents datasets and get a razonable WER. So I don't know how I get such a bad prediction with train data.

```bash
$ CUDA_VISIBLE_DEVICES=0,1 ./DeepSpeech.py \
--train_files data/train.csv \
--dev_files data/dev.csv \
--test_files data/test.csv \
--decoder_library_path models/language/libctc_decoder_with_kenlm.so \
--lm_binary_path models/language/clara_5gram.klm \
--lm_trie_path models/language/trie \
--alphabet_config_path models/language/alphabet.txt \
--train_batch_size 64 \
--dev_batch_size 64 \
--test_batch_size 64 \
--n_hidden 2048 \
--epoch 150 \
--checkpoint_dir models/session/ \
--summary_dir models/summary/ \
--summary_secs 1756 \
--export_dir models/modelo/ \
--validation_step 20 \
--earlystop_nsteps 4 \
--display_step 20
```

**Comment by lissyx** [comment]
@djpg As said earlier, it would be better to do that discussion on Discourse, and the hyperparameters you are using might just be not good: we are still working on that new model.

**Comment by djpg** [comment]
@lissyx move to [Discourse](https://discourse.mozilla.org/t/inference-prediction-with-own-trained-model/31564).
