### ISSUE TITLE
TypeError: ctc_beam_search_decoder_with_lm() missing 1 required positional argument

### ISSUE THREAD

**Issue by SemabAli** [mozilla/DeepSpeech#1526]

**Comment by lissyx** [comment]
How did you checked out the source? Are you on the correct tag?

**Comment by lissyx** [comment]
Here: https://github.com/mozilla/DeepSpeech/blob/v0.2.0-alpha.8/DeepSpeech.py#L486
And now: https://github.com/mozilla/DeepSpeech/blob/v0.2.0-alpha.9/DeepSpeech.py#L476

@SemabAli My best guess is that your git clone is not on `v0.2.0-alpha.8`

**Comment by SemabAli** [comment]
@lissyx    Thanks it resolved by downloading correct one.
