### ISSUE TITLE
packages mismatching tenserflow Vs native_client Vs git clone deepspeech.? how can i fix it? 

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/DeepSpeech#1529]
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow CPU 1.6.0
- python 3.6
- bazel release 0.16.1

  i was using,
-----------------> git lfs clone https://github.com/MuruganR96/DeepSpeech.git  --branch v0.1.1(before did git lfs install)
                        tensorflow 1.6.0
                        native_client v0.1.1
                        pip3 install upgrade v0.1.1
                        pretrained model v0.1.1
i fine tuning pretrained model with my own audio.csv generate a output_graph.pb . i am testing that model,it shows,
this issue,

Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3

Again i search some solution for how to fix, @lissyx said tensorflow version is reason so i follow @lissyx sir instructions,
------------------->git lfs clone https://github.com/MuruganR96/DeepSpeech.git  --branchv0.2.0-alpha.6(before did git lfs install)
                         tensorflow 1.6.0
                         native_client  v0.2.0-alpha.6
                         pip3 install upgrade  dev0.2.0-alpha.6
                         pretrained model v0.1.1

again i fine tuning pretrained model with my own audio.csv, but this time also shows error
this error,
what():  native_client/kenlm/lm/binary_format.cc:131 in void lm::ngram::MatchCheck(lm::ngram::ModelType, unsigned int, const lm::ngram::Parameters&) threw FormatLoadException.
The binary file was built for probing hash tables but the inference code is trying to load trie with quantization and array-compressed pointers

this fine tuning process i have lot of time tried. however  it show some error. sir please can you properly mension sir, what are version packages needed to fine tune a pretrained model.

packages mismatching tenserflow Vs native_client Vs git clone deepspeech.? how can i fix it?

please help me sir. i search and follow lot of solution instruction but can't do anything?

thank you sir. thank you so much for your fast reply.

**Comment by kdavis-mozilla** [comment]
I'm afraid you need to provide more information.

**Comment by MuruganR96** [comment]
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow CPU 1.6.0
- python 3.6
- bazel release 0.16.1

  i was using,
-----------------> git lfs clone https://github.com/MuruganR96/DeepSpeech.git  --branch v0.1.1(before did git lfs install)
                        tensorflow 1.6.0
                        native_client v0.1.1
                        pip3 install upgrade v0.1.1
                        pretrained model v0.1.1
i fine tuning pretrained model with my own audio.csv generate a output_graph.pb . i am testing that model,it shows,
this issue,

Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3

Again i search some solution for how to fix, @lissyx said tensorflow version is reason so i follow @lissyx sir instructions,
------------------->git lfs clone https://github.com/MuruganR96/DeepSpeech.git  --branchv0.2.0-alpha.6(before did git lfs install)
                         tensorflow 1.6.0
                         native_client  v0.2.0-alpha.6
                         pip3 install upgrade  dev0.2.0-alpha.6
                         pretrained model v0.1.1

again i fine tuning pretrained model with my own audio.csv, but this time also shows error
this error,
what():  native_client/kenlm/lm/binary_format.cc:131 in void lm::ngram::MatchCheck(lm::ngram::ModelType, unsigned int, const lm::ngram::Parameters&) threw FormatLoadException.
The binary file was built for probing hash tables but the inference code is trying to load trie with quantization and array-compressed pointers

this fine tuning process i have lot of time tried. however  it show some error. sir please can you properly mension sir, what are version packages needed to fine tune a pretrained model.

packages mismatching tenserflow Vs native_client Vs git clone deepspeech.? how can i fix it?

please help me sir. i search and follow lot of solution instruction but can't do anything?

thank you sir. thank you so much for your fast reply.

**Comment by lissyx** [comment]
@MuruganR96 I'm sorry, but it's too much messy. Can you properly format your message, and explicitely document the current state ? The NodeDef error and the lm error have nothing to do together.

You are also referring to your own clone. Please work our upstream. Alpha 6 might be using the improper language model, please use Alpha 8 binaries if you rely on pretrained model v0.1.1

**Comment by MuruganR96** [comment]
Sir what version tensorflow i followed. currently i am using tensorflow1.6.0(alpha 6).
i can't checkout our own DeepSpeech model sir. that the reason only i fork on our model into my github repo then i clone. 
i can't checkout our DeepSpeech. i follow this https://github.com/mozilla/DeepSpeech/issues/1528#issuecomment-419818260 instruction sir.
please tell me sir how to clone DeepSpeech particular branch. 
then now i am using native_client alpha 6 , i will change this into alpha 8, 
next i change pip3 install upgrade deepspeech-alpha08,

sir is this enough to retrain a frozen graph? is there is anything else i have to change? 
thank you so much sir :)

**Comment by lissyx** [comment]
@MuruganR96 How come you cannot git clone our repo ? Please retry with 0.2.0-alpha.8 binaries.

**Comment by lissyx** [comment]
@MuruganR96 Try `v0.2.0-alpha.8` and not `0.2.0-alpha.8`. Also, you could try and git clone without `--branch` and git checkout the `v0.2.0-alpha.8` tag after.

**Comment by MuruganR96** [comment]
oh sorry sir. sorry for the trouble

**Comment by lissyx** [comment]
Please take any fine-tuning question to a properly documented thread on Discourse, so we and others can help you. Details can be very tricky (recording mic, audio quality, post-treatement). So please be direct, simple and give as much as details on your process as possible.

**Comment by MuruganR96** [comment]
Excuse me sir. I have a question sir. vocab.txt -> lm.arpa -> lm.binary & trie. this is the process for pretrained binaries. but i have my audio vocab.txt is there. but i can't use or added into that frozen model retraining.
then how it will predict my audio technical terms or words.?
in my starting stage i run that model it is not predicting my technical term words. that the reason only i again retrain a frozen model.
if there is any possible ways is there to add my audio vocab.txt binaries , will it possible?  
thank you for your kindness and fast awesome wonderful reply. it is very very useful for my project.:)

**Comment by lissyx** [comment]
@MuruganR96 I'm not going to be kind forever, if you keep doing that: I've asked you to take that kind of questions to Discourse. This is not the place.
