### ISSUE TITLE
DeepSpeechDeprecationWarning: DeepSpeech Python bindings could not be imported, resorting to slower code to compute audio features. Refer to README.md for instructions on how to install (or build) the DeepSpeech Python bindings.

### ISSUE THREAD

**Issue by avipartho** [mozilla/DeepSpeech#1530]
I have installed deepspeech using this command `pip3 install deepspeech`. It installs the package successfully but when I try to train on some dataset using `DeepSpeech.py`, it shows a **DeepSpeechDeprecationWarning** from `DeepSpeech/util/audio.py:17` where it actually tries tio import **audioToInputVector**. There was no problem when I, as a test, tried to import **deepspeech.model**. Any idea what's causing this problem? 

[I understand, this is just a warning and the training starts no matter what. Also it doesn't show any error if I simply run inference on any audio file using `deepspeech [-h] model audio alphabet [lm] [trie]`. But I'm on cpu and according to the error message, a successful import could save me some time.] 

- **OS Platform and Distribution**: Linux Mint 18.1 cinnamon 64 bit
- **TensorFlow version**: 1.6
- **Python version**: 3.5.2 
- **Pip version**: 18.0
- **GPU model and memory**: None
- **Installed deepspeech version**: 0.1.1

**Comment by lissyx** [comment]
@avipartho Can you document the steps ? Which version do you checkout to train ? What does a `from deepspeech import audioToInputVector` in a python shell gives?

**Comment by lissyx** [comment]
My guess is that you are playing with 0.1.1 binaries / bindings, that used to expose `audioToInputVector` under `deepspeech.utils`, and you are training with current master, matching 0.2.0-alpha.9 binaries, who exposes that under `deepspeech`.

**Comment by reuben** [comment]
The performance difference is very small, and we'll probably drop use of the bindings in the training code pretty soon. So I wouldn't worry about it.

**Comment by kdavis-mozilla** [comment]
@avipartho In moving to a streaming architecture we've moved from a bidirectional RNN to a unidirectional RNN.

**Comment by avipartho** [comment]
Thanks to all for your replies. I'm closing this issue.
