### ISSUE TITLE
What is the purpose of setting "chunk" for evaluate in master branch 

### ISSUE THREAD

**Issue by luckmoon** [mozilla/DeepSpeech#1533]
https://github.com/mozilla/DeepSpeech/blob/5ff3b31bbde1b748d069dd7bba8ca7fff87ce56d/evaluate.py#L242

**Comment by kdavis-mozilla** [comment]
@luckmoon As this isn't a bug or feature request, could you move this discussion to Discourse[[1](https://discourse.mozilla.org/c/deep-speech)]? We try to reserve GutHub issues for only bugs or feature requests. Thanks for your understanding.

**Comment by luckmoon** [comment]
> @luckmoon As this isn't a bug or feature request, could you move this discussion to Discourse[[1](https://discourse.mozilla.org/c/deep-speech)]? We try to reserve GutHub issues for only bugs or feature requests. Thanks for your understanding.

Gotcha
