### ISSUE TITLE
Allow for relative paths in CSV files

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#1537]
Future versions of our cluster will mount `${DATA_ROOT}` in different location(s). At the moment we (actually the CSV files) rely on absolute paths to WAVs.
Design consideration:
If a sample file path is not an absolute one (no leading slash), we prefix it with the parent directory of the CSV file.

**Comment by reuben** [comment]
Fixed with the feature caching PR.

**Comment by Hafsa26** [comment]
what will be the cache featured path files in deepspeech.py ?

**Comment by Hafsa26** [comment]
Should I place the same files in cache featured path files as I gave path in train, test and dev?

**Comment by Hafsa26** [comment]
Should I place the same files path in cache featured path as I gave path in train ,dev files?
Thank you for replying @tilmankamp 


![deepspeech](https://user-images.githubusercontent.com/43984420/48059402-e7084880-e1da-11e8-831e-568e75c35b86.png)

**Comment by tilmankamp** [comment]
@Hafsa26 These are optional. If you provide a path for one of them and the file is not existing, it will get created during training as a cache that prevents reading single wav files over and over again for every epoch and later runs. I think the only condition is that the parent directory has to exist and be writeable by the calling user. Please ask further questions on [discourse](https://discourse.mozilla.org/c/deep-speech).

@reuben I think we should improve the help text a bit. I opened https://github.com/mozilla/DeepSpeech/issues/1709 for this.

**Comment by Hafsa26** [comment]
Got it. Thank you for help. @tilmankamp
