### ISSUE TITLE
Update Dockerfile to r1.11

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#1578]
With #1572 being in flight, the `Dockerfile` will need to be updated.

**Comment by lissyx** [comment]
@GeorgeFedoseev If you have time, it'd be great :)

**Comment by GeorgeFedoseev** [comment]
@lissyx thanks for updating this) I was away from keyboard past week.

**Comment by lissyx** [comment]
@GeorgeFedoseev I've removed but left as comments the build and installation of the Python wheel from our sources, it's better to rely on upstream :).
