### ISSUE TITLE
Fails to built on FreeBSD 11.2

### ISSUE THREAD

**Issue by janb14** [mozilla/DeepSpeech#1581]
Im trying to built the native client for FreeBSD but get an error in the last file bazel trys to compile.
My Specs:
-Modified code: replaced needed Systemdefs in native_client/kenlm/util/usage.cc
-OS: FreeBSD 11.2 (Jail)
-Tensorflow 1.10.0-rc1 modified from original Github
-Python 3.6
-Bazel 0.17.1(selfbuilt from source)
-GCC version 6.4.1 20180516
-command that fails:
`bazel build --local_resources 1024,3.0,1.0 --jobs 8 --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie`

Error i got : 

>ERROR: /mnt/speech/tensorflow/native_client/BUILD:13:1: Linking of rule '//native_client:libdeepspeech.so' failed (Exit 1)
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::PlusCompare(double_conversion::Bignum const&, double_conversion::Bignum const&, double_conversion::Bignum const&)':
bignum.cc:(.text._ZN17double_conversion6Bignum11PlusCompareERKS0_S2_S2_+0x0): multiple definition of `double_conversion::Bignum::PlusCompare(double_conversion::Bignum const&, double_conversion::Bignum const&, double_conversion::Bignum const&)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/bignum.pic.o:bignum.cc:(.text._ZN17double_conversion6Bignum11PlusCompareERKS0_S2_S2_+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::AssignBignum(double_conversion::Bignum const&)':
bignum.cc:(.text._ZN17double_conversion6Bignum12AssignBignumERKS0_+0x0): multiple definition of `double_conversion::Bignum::AssignBignum(double_conversion::Bignum const&)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/bignum.pic.o:bignum.cc:(.text._ZN17double_conversion6Bignum12AssignBignumERKS0_+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::AssignUInt16(unsigned short)':
bignum.cc:(.text._ZN17double_conversion6Bignum12AssignUInt16Et+0x0): multiple definition of `double_conversion::Bignum::AssignUInt16(unsigned short)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/bignum.pic.o:bignum.cc:(.text._ZN17double_conversion6Bignum12AssignUInt16Et+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::AssignUInt64(unsigned long)':
bignum.cc:(.text._ZN17double_conversion6Bignum12AssignUInt64Em+0x0): multiple definition of `double_conversion::Bignum::AssignUInt64(unsigned long)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/bignum.pic.o:bignum.cc:(.text._ZN17double_conversion6Bignum12AssignUInt64Em+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::SubtractTimes(double_conversion::Bignum const&, int)':
bignum.cc:(.text._ZN17double_conversion6Bignum13SubtractTimesERKS0_i+0x0): multiple definition of `double_conversion::Bignum::SubtractTimes(double_conversion::Bignum const&, int)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/bignum.pic.o:bignum.cc:(.text._ZN17double_conversion6Bignum13SubtractTimesERKS0_i+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::SubtractBignum(double_conversion::Bignum const&)':
bignum.cc:(.text._ZN17double_conversion6Bignum14SubtractBignumERKS0_+0x0): multiple definition of `double_conversion::Bignum::SubtractBignum(double_conversion::Bignum const&)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/bignum.pic.o:bignum.cc:(.text._ZN17double_conversion6Bignum14SubtractBignumERKS0_+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(bignum.pic.o): In function `double_conversion::Bignum::AssignHexString(double_conversion::Vector<char const>)':
...
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/double-conversion.pic.o:double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter20ToShortestIeeeNumberEdPNS_13StringBuilderENS0_8DtoaModeE+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(double-conversion.pic.o): In function `double_conversion::DoubleToStringConverter::CreateDecimalRepresentation(char const*, int, int, int, double_conversion::StringBuilder*) const':
double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter27CreateDecimalRepresentationEPKciiiPNS_13StringBuilderE+0x0): multiple definition of `double_conversion::DoubleToStringConverter::CreateDecimalRepresentation(char const*, int, int, int, double_conversion::StringBuilder*) const'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/double-conversion.pic.o:double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter27CreateDecimalRepresentationEPKciiiPNS_13StringBuilderE+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(double-conversion.pic.o): In function `double_conversion::DoubleToStringConverter::CreateExponentialRepresentation(char const*, int, int, double_conversion::StringBuilder*) const':
double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter31CreateExponentialRepresentationEPKciiPNS_13StringBuilderE+0x0): multiple definition of `double_conversion::DoubleToStringConverter::CreateExponentialRepresentation(char const*, int, int, double_conversion::StringBuilder*) const'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/double-conversion.pic.o:double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter31CreateExponentialRepresentationEPKciiPNS_13StringBuilderE+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(double-conversion.pic.o): In function `double_conversion::DoubleToStringConverter::ToFixed(double, int, double_conversion::StringBuilder*) const':
double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter7ToFixedEdiPNS_13StringBuilderE+0x0): multiple definition of `double_conversion::DoubleToStringConverter::ToFixed(double, int, double_conversion::StringBuilder*) const'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/double-conversion.pic.o:double-conversion.cc:(.text._ZNK17double_conversion23DoubleToStringConverter7ToFixedEdiPNS_13StringBuilderE+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(fast-dtoa.pic.o): In function `double_conversion::FastDtoa(double, double_conversion::FastDtoaMode, int, double_conversion::Vector<char>, int*, int*)':
fast-dtoa.cc:(.text._ZN17double_conversion8FastDtoaEdNS_12FastDtoaModeEiNS_6VectorIcEEPiS3_+0x0): multiple definition of `double_conversion::FastDtoa(double, double_conversion::FastDtoaMode, int, double_conversion::Vector<char>, int*, int*)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/fast-dtoa.pic.o:fast-dtoa.cc:(.text._ZN17double_conversion8FastDtoaEdNS_12FastDtoaModeEiNS_6VectorIcEEPiS3_+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(fixed-dtoa.pic.o): In function `double_conversion::FastFixedDtoa(double, int, double_conversion::Vector<char>, int*, int*)':
fixed-dtoa.cc:(.text._ZN17double_conversion13FastFixedDtoaEdiNS_6VectorIcEEPiS2_+0x0): multiple definition of `double_conversion::FastFixedDtoa(double, int, double_conversion::Vector<char>, int*, int*)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/fixed-dtoa.pic.o:fixed-dtoa.cc:(.text._ZN17double_conversion13FastFixedDtoaEdiNS_6VectorIcEEPiS2_+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(strtod.pic.o): In function `double_conversion::Strtod(double_conversion::Vector<char const>, int)':
strtod.cc:(.text._ZN17double_conversion6StrtodENS_6VectorIKcEEi+0x0): multiple definition of `double_conversion::Strtod(double_conversion::Vector<char const>, int)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/strtod.pic.o:strtod.cc:(.text._ZN17double_conversion6StrtodENS_6VectorIKcEEi+0x0): first defined here
bazel-out/freebsd-opt/bin/external/double_conversion/libdouble-conversion.pic.a(strtod.pic.o): In function `double_conversion::Strtof(double_conversion::Vector<char const>, int)':
strtod.cc:(.text._ZN17double_conversion6StrtofENS_6VectorIKcEEi+0x0): multiple definition of `double_conversion::Strtof(double_conversion::Vector<char const>, int)'
bazel-out/freebsd-opt/bin/native_client/_objs/libdeepspeech.so/strtod.pic.o:strtod.cc:(.text._ZN17double_conversion6StrtofENS_6VectorIKcEEi+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 8.869s, Critical Path: 8.73s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by janb14** [comment]
The thing is that the error revolves around an external lib you are using double_conversion that i already have compiled on my system. Is it possible to rather import this file over using the BUILT instructions given ?

**Comment by lissyx** [comment]
> -Tensorflow 1.10.0-rc1 modified from original Github
> -Python 3.6
> -Bazel 0.17.1(selfbuilt from source)

If you are doing that with current master, then it's not surprising: use TensorFlow r1.6, and Bazel 0.10: TensorFlow after ~r1.7-r1.8 started to use `double_conversion` that is already in `KenLM`. I'm right now in the process of updating to `r1.11` and this will be namespaced properly.

Feel free to re-open if you still hit issues after https://github.com/mozilla/DeepSpeech/issues/1572 :)

**Comment by janb14** [comment]
As i cant get tensorflow 1.6.0 to work on FreeBSD and only this lib fails in Deepspeech is there a possibility of a quick fix ? I already looked into bazel using precompiled libs but i cant find the entrypoint for doubleconversion.

**Comment by lissyx** [comment]
@janb14 Why 1.6 would not be okay on TensorFlow ?

**Comment by lissyx** [comment]
@janb14 But basically, once all tasks are green here: https://tools.taskcluster.net/groups/d0jtpt5cQqCZwn7lAcjK1A I'll be able to merge the r1.11 move. It might be no later than after I arrive home.

**Comment by janb14** [comment]
when i checkout tensorflow 1.6 and try to built i get alot of bad cpu defs. i need to agree in tensorflow not beeing made for FreeBSD as nothing is rly XD. Even for 1.10 i needed to patch files for a couple of hours as FreeBSD is not supported :/

**Comment by lissyx** [comment]
@janb14 Just merged, if you get latest master, this should now be r1.11-based.

**Comment by janb14** [comment]
@lissyx thx alot man i will give it a go ^^

**Comment by janb14** [comment]
wow man it worked even with 1.10.0-rc1 as a base. just need some proper testing now.
