### ISSUE TITLE
 FormatLoadException/Data loss: Can't parse models/output_graph.pbmm as binary proto

### ISSUE THREAD

**Issue by JunaidMuthukadan** [mozilla/DeepSpeech#1584]
I am not able to find a solution for this error.. if anyone could help it would be really appreciated

```
 [m.muthukadan@srp100-0208 speech]$ deepspeech models/output_graph.pbmm models/alphabet.txt models/lm.binary models/trie sound1.wav
Loading model from file models/output_graph.pbmm
2018-09-25 15:30:39.348973: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
**Data loss: Can't parse models/output_graph.pbmm as binary proto**
Loaded model in 13.111s.
Loading language model from files models/trie sound1.wav
Loading the LM will be faster if you build a binary file.
Reading models/trie
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "1414678853" not \data\. Byte: 11
중지됨 (core dumped)
```

**Comment by lissyx** [comment]
@JunaidMuthukadan Can you document a bit more what you are doing ?
Can you share the output of `sha256sum models/*` ?

**Comment by JunaidMuthukadan** [comment]
i have installed deepspeech library and and just testing with an input file in a gpu.
i have already downloaded the trained model (latest) and extracted all files in models folder?
what is  sha256sum?

**Comment by lissyx** [comment]
@JunaidMuthukadan It would help that you document your installation steps. For example, this would help identify that you are not using 0.2.0 binaries. So I don't know the kind of mix you are trying to attempt, but we added positionnal arguments weeks ago now. Make sure your model is 0.2.0 from the latest release and your binaries are 0.2.0 as well.

**Comment by lissyx** [comment]
Obviously a mismatch of models / binary.
