### ISSUE TITLE
Interim results with streaming

### ISSUE THREAD

**Issue by sruteesh-pivot** [mozilla/DeepSpeech#1585]
Hi,
I started playing around with streaming inference. 

As it anyway doesn't give us interim results, why not use the earlier architecture Bi-LSTM and send recorded audio files split on silence (maybe using VAD) and continuosly transcribe.
Is speed of inference the only advantage streaming service is offering?

I modified [ds_mic.py](https://gist.github.com/reuben/80d64de15d1f46d34d28c7e83fc5f57e#file-ds_mic-py) as follows
```
while True:
  try:
      sctx = model.setupStream()

      subproc = subprocess.Popen(shlex.split('rec -q -V0 -e signed -L -c 1 -b 16 -r 16k -t raw - gain -2'),
                                 stdout=subprocess.PIPE,
                                 bufsize=0)
      print('You can start speaking now. Press Control-C to stop recording.')
      while True:
          data = subproc.stdout.read(512)
          model.feedAudioContent(sctx, np.frombuffer(data, np.int16))
  except KeyboardInterrupt:
      print('Transcription: ', model.finishStream(sctx))
      subproc.terminate()
      subproc.wait()
```
to help me continuously stream. But this could have been done using the earlier (0.1.1) architecture aswell. Please clarify me.

Thanks.

**Comment by lissyx** [comment]
@sruteesh-pivot I'm not really sure I get the point of your issue. There is no bug described, and the goal of the architecture change was explicitely to **avoid** the kind of hack you document. Of course, we could have some kind of streaming done that way, but this would still come with the extra complexity cost of the bidirectionnal layer.

If you want to discuss the architecture, Discourse https://discourse.mozilla.org/c/deep-speech would be better.
