### ISSUE TITLE
Op type not registered 'BlockLSTM' in binary running on user-OptiPlex-3020M.

### ISSUE THREAD

**Issue by akshat9425** [mozilla/DeepSpeech#1586]
i follow all instructions provided on link : https://progur.com/2018/02/how-to-use-mozilla-deepspeech-tutorial.html

and i am using https://github.com/mozilla/DeepSpeech/releases/download/v0.2.0/deepspeech-0.2.0-models.tar.gz model

Below is error i got
Not found: Op type not registered 'BlockLSTM' in binary running on user-OptiPlex-3020M. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by lissyx** [comment]
@akshat9425 Please refer to our documentation for release v0.2.0, this blog post is not from us and is now outdated.
