### ISSUE TITLE
how to use v0.2.0-alpha.9 

### ISSUE THREAD

**Issue by akshat9425** [mozilla/DeepSpeech#1588]
i found an error and its solution is in link  : https://discourse.mozilla.org/t/inference-troubles-not-found-op-type-not-registered-blocklstm/31061/2

but i don't know that what they actually want to say by using v0.2.0-alpha.9 which is present in your site https://github.com/mozilla/DeepSpeech/releases

in short : how to use v0.2.0-alpha.9 

waiting for reply

**Comment by lissyx** [comment]
@akshat9425 This is the third issue you are opening. This is not a forum, use Discourse. And follow the docs.
