### ISSUE TITLE
Tensorflow r1.6 files

### ISSUE THREAD

**Issue by 9define** [mozilla/DeepSpeech#1590]
Hello, I'm back with another release request!
Seeing as Mozilla's TF is required for DS (whether it be r1.6 or r1.11 with the upcoming v0.2.1 release), can a _prebuilt_ version of it be included in DS releases (or in that GH repo)? I found the r1.6 prebuild library on [taskcluster](https://tools.taskcluster.net/index/project.deepspeech.tensorflow.pip.r1.6), but it expires in a few months, and regardless of the version, that could be an issue for future DS releases if someone wants to use their NVIDIA GPU for STT inferences via DS. Thanks.

**Comment by lissyx** [comment]
@9define There's no need to use mozilla/tensorflow fork for training. It's only required to build `libdeepspeech.so` and friends.

**Comment by 9define** [comment]
Ah, I see. Is the ctc decoder with kenlm only needed for training as well then? Your comment seems to imply that TF isn't needed for normal use of existing models. I think I'd still need CUDA libs for using DS' GPU release, though. Thanks.

**Comment by lissyx** [comment]
@9define Yes, `libctc_decoder_with_kenlm.so` is only required at training, and works (and is tested) with upstream. We don't build anymore python package out of our TensorFlow fork for months now.

And yes, when you are just running inference, there's no need to install TensorFlow: it's statically linked into `libdeepspeech.so`.

You need CUDA libs if you run CUDA binaries, but it's like any CUDA-based tool, you need to install the CUDA runtime ...
