### ISSUE TITLE
Error running session: Invalid argument: Session was not created with a graph before Run()!

### ISSUE THREAD

**Issue by akshat9425** [mozilla/DeepSpeech#1592]
my code is :

from deepspeech.model import Model
import scipy.io.wavfile as wav
import sys

ds = Model("/home/user/new_mozilla/speech/models_2/output_graph.rounded.pbmm", 26, 9, "/home/user/new_mozilla/speech/models_2/alphabet.txt", 500)
fs, audio = wav.read("/home/user/new_mozilla/speech/gaurav.wav")
processed_data = ds.stt(audio, fs)
print(processed_data)

I used model folder =>: https://github.com/mozilla/DeepSpeech/releases/download/v0.2.0/deepspeech-0.2.0-models.tar.gz

**Comment by kdavis-mozilla** [comment]
Please take a look at our example [client.py](https://github.com/mozilla/DeepSpeech/blob/v0.2.0/native_client/python/client.py) to see how to correctly call in to Deep Speech using Python.
