### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by aswin1980** [mozilla/DeepSpeech#1598]
Hi,

I would like to use deepspeech in Windows 7 and greater. How do I build it for Windows?
When I use msys64 it says cannot find deepspeech library.

Could you please help me with this.

Thanks
Aswin

**Comment by lissyx** [comment]
We don't have Windows builds yet as filed already in #1123. If you want to work on that, you are more than welcome, but I have no idea what you are doing, so I cannot help you. Also, this discussion should be done on Discourse: https://discourse.mozilla.org/c/deep-speech

**Comment by aswin1980** [comment]
Hi,
When I compile the native_client it is linked to deepspeech (-ldeepspeech). The question I have is where can I find libdeepspeech source code.

here it is in make file

install_name_tool -change bazel-out/local-opt/bin/native_client/libdeepspeech.so @rpath/libdeepspeech.so deepspeech

Thanks
Aswin

**Comment by lissyx** [comment]
@aswin1980 Please follow the documented build instructions for native client, and use Discourse.
