### ISSUE TITLE
code not works for downloaded files

### ISSUE THREAD

**Issue by akshat9425** [mozilla/DeepSpeech#1607]
Discosure refused to discuss and login recorded voice is not working for speech to text and pyaudio code is doing best work please tell me how could i use downloaded audio for speech to text 

Thanks in advance 
and please give me a chance to speak before closing the issue

**Comment by reuben** [comment]
@akshat9425 you keep opening issues when you're being told several times to take discussion and support topics to Discourse, as issues are meant for tracking bugs in the code only.

On top of that, your issues don't give any detail about the problems you're facing, giving us no useful information to try and diagnose the problem.

The clients work just fine with downloaded files, we even include some files with the release so users can test.

If you keep disregarding our instructions and opening issue after issue on GitHub, we'll have to block you from interacting with the repository.
