### ISSUE TITLE
Failed using my own model

### ISSUE THREAD

**Issue by paezxavi** [mozilla/DeepSpeech#1609]
- **OS Platform and Distribution** : Linux Mint 18.3 cinnamon 64bit
- **TensorFlow installed from**: your build
- **TensorFlow version** : v1.11.0
- **Python version**: 3.6.5
- **DeepSpeech version** : 0.2.0a9
- **native_client** : branch 0.2.0a9
I'm on CPU
- **Exact command to reproduce**:
```
python -u DeepSpeech.py   --train_files ./data/ldc93s1/ldc93s1.csv --dev_files ./data/ldc93s1/ldc93s1.csv --test_files ./data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 test_batch_size 1 --n_hidden 494   --epoch 20   --checkpoint_dir   /home/Me/Bureau/checkpoint/test   --decoder_library_path ./libctc_decoder_with_kenlm.so   --export_dir /home/Me/Bureau/exportModel   "$@"
```
 
```
deepspeech --model ../exportModel/output_graph.pb --alphabet ./data/alphabet.txt --lm ./data/lm/lm.binary --trie ./data/lm/trie --audio ./data/ldc93s1/LDC93S1.wav 
```

Logs :
```
Loading model from file ../exportModels/output_graph.pb
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
Invalid argument: No OpKernel was registered to support Op 'Pack' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: lstm_fused_cell/stack_1 = Pack[N=2, T=DT_INT32, axis=1](input_lengths, lstm_fused_cell/range_1)]]
Traceback (most recent call last):
  File "/home/Me/tmp/deepspeech-venv/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/home/Me/tmp/deepspeech-venv/lib/python3.6/site-packages/deepspeech/client.py", line 76, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/Me/tmp/deepspeech-venv/lib/python3.6/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 3
```

Here is my problem, I created a model from the ldc93s1 learning and I can't use it. However, I can use the one is given as test in your github, but when it's me who created one, it doesn't work. I tried to downgrade to 0.2.0a7, 0.2.0a8 but nothing works. I hope you could show me my mistake because I ran out of ideas.

Thanks in advanced.

**Comment by lissyx** [comment]
As you suspected it's likely just a mess of trained / inference versions. It'd be better you retrain and test with 0.2.0 and not alpha 9. Given the errors and the documented versions, I suspect you trained on current master and you installed 0.2.0a9 binaries.

You should make sure you:
 - `git checkout v0.2.0`
 - install tensorflow upstream, you need our version only if you have to rebuild native client
 - install `deepspeech==0.2.0`

Feel free to reopen in case it persists, but if you just need help, please take the discussion to Discourse: https://discourse.mozilla.org/c/deep-speech
