### ISSUE TITLE
mfcc extraction with another library

### ISSUE THREAD

**Issue by rumschuettel** [mozilla/DeepSpeech#1622]
Hi!

I'm trying to do mfcc extraction from within javascript in a browser; e.g. using meyda:
https://github.com/meyda/meyda/blob/master/src/extractors/mfcc.js

the problem is: it seems almost impossible to obtain the same output for an array of, say, 1024 floating point values. Has anyone tried this before? Why does deepspeech do so much extra processing that deviates from the standard mfcc feature extraction?

Thanks!
- J

**Comment by reuben** [comment]
> Why does deepspeech do so much extra processing that deviates from the standard mfcc feature extraction?

We don't. We use the [python-speech-features package](https://github.com/jameslyons/python_speech_features) as well as a C reimplementation of it that lives here: https://github.com/mozilla/DeepSpeech/tree/master/native_client/c_speech_features
