### ISSUE TITLE
What are the hyper-paramters used to fine tune the pre-trained model 0.1.0 during training

### ISSUE THREAD

**Issue by oceank** [mozilla/DeepSpeech#1624]
Hi, DeepSpeech developers and community friends,

My current research work needs to check the different training parameter configurations of pre-trained model 0.1.0 and pre-trained model 0.1.1. I find the hyper-parameters of pre-trained model 0.1.1, but could not find the corresponding ones for model 0.1.0. Could you share me the trainning setting for pre-trained model 0.1.0? thank you!

**Comment by lissyx** [comment]
@oceank While it's not on the release page, I'm sure we documented that somewhere. @kdavis-mozilla @reuben Any memory of that?

**Comment by lissyx** [comment]
Maybe https://github.com/mozilla/DeepSpeech/commit/2d3818b492045ccea0cea660c27355994c1413b6#diff-bcf163f5d10b12e30bb1721f339a286e ?

**Comment by oceank** [comment]
@lissyx Thank you for your quick response. I digged into the mentioned commit and find something in In the removed script, bin/run-wer-automation.sh. Could you help me confirm it?

=bin/run-wer-automation.sh=
```
#!/bin/sh
 python -u DeepSpeech.py \
  --train_files "${COMPUTE_DATA_DIR}/ted-train.csv" \
  --dev_files "${COMPUTE_DATA_DIR}/ted-dev.csv" \
  --test_files "${COMPUTE_DATA_DIR}/ted-test.csv" \
  --train_batch_size 16 \
  --dev_batch_size 8 \
  --test_batch_size 8 \
  --epoch=50 \
  --learning_rate 0.0001 \
  --display_step 10 \
  --validation_step 10 \
  --dropout_rate 0.30 \
  --default_stddev 0.046875 \
  --checkpoint_step 1 \
  --checkpoint_dir "${COMPUTE_KEEP_DIR}" \
  --wer_log_pattern "GLOBAL LOG: logwer('${COMPUTE_ID}', '%s', '%s', %f)"\
  "$@"
```

**Comment by kdavis-mozilla** [comment]
For v0.1.0 the parameters, as far as I remember, were the same as in the v0.1.1 model, which are described in the release notes[[1](https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.1)]

**Comment by lissyx** [comment]
We can close that I guess :)
