### ISSUE TITLE
ImportError: No module named model

### ISSUE THREAD

**Issue by chrisspen** [mozilla/DeepSpeech#1632]
In version 0.1.0, the Python package supported the import:

     from deepspeech.model import Model

which you could then instantiate like:

    ds = Model(MODEL, N_FEATURES, N_CONTEXT, ALPHABET, BEAM_WIDTH)

and perform speech to text functions with, like:

    fs, audio = wav.read(audio_fn)
    text = ds.stt(audio, fs)

I'm testing version 0.2.0, and the import for Model now returns an import error, and all references to this stt Python interface has been removed from PyPI, as well as the docs on readthedocs.

Has this functionality been removed, or just relocated/renamed without any update to the docs?

**Comment by lissyx** [comment]
@chrisspen Can you give more informations as documented above?

**Comment by chrisspen** [comment]
Nevermind. It looks like the module was moved from ".models*" to "."

**Comment by tiefenauer** [comment]
How can I import the `Model` class then? The following import do all not work:

```python
from deepspeech import *
from deepspeech import Model
from deepspeech.model import Mode
```

**Comment by lissyx** [comment]
We do use the second form in client.py so if it's nor working there's something else on your side.
