### ISSUE TITLE
broken link on readme to download pre trained models for v0.3.0

### ISSUE THREAD

**Issue by mone27** [mozilla/DeepSpeech#1653]
the link to download pre trained models is broken 
`wget -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.3.0/deepspeech-0.3.0-models.tar.gz | tar xvfz -` 
since it points to v0.3.0 which is not released yet.
The last working link is 
`wget -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.2.0/deepspeech-0.2.0-models.tar.gz | tar xvfz -`

**Comment by kdavis-mozilla** [comment]
@mone27 0.3.0 has not yet been released. The README has the link in preparation for the release.
