### ISSUE TITLE
Training of Epoch x - loss: inf. again decrease LR, stil same issue repeating. can't guess what is happened?

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/DeepSpeech#1654]
Training of Epoch x - loss: inf. again decrease LR, stil same issue repeating. can't guess what is happened?
help me how to rectify this? thank you sir.

**Comment by lissyx** [comment]
@MuruganR96 We can't provide support without any information. And please reach for that kind of help on training on Discourse.
