### ISSUE TITLE
speech-to-text json result with time per word

### ISSUE THREAD

**Issue by mouradski** [mozilla/DeepSpeech#1656]
it would be really cool if we had a transcription result as follows:

[
{name: "word1, time: 130}
{name: "word2, time: 132},
.....
]

seen @ http://speechmatics.com API

**Comment by lissyx** [comment]
@mouradski You can build it ?

**Comment by lissyx** [comment]
@mouradski I meant, it's not directly in the scope of what we expect to provide, but it should be fairly easy to build, and we'd welcome a PR that adds something dealing with that, either directly in our repo, or in another repo

**Comment by kdavis-mozilla** [comment]
@lissyx just yesterday @reuben started looking in to integrating [ctcdecode](https://github.com/parlance/ctcdecode/) as it outperforms tensorflow's CTC. In addition, [ctcdecode](https://github.com/parlance/ctcdecode/) provides character level timings.

The integration would require work, but it would be a big win, giving a better WER's plus timings.

**Comment by loretoparisi** [comment]
+1

**Comment by mouradski** [comment]
> @mouradski You can build it ?

i'll try :) it's a good challenge :)

**Comment by lissyx** [comment]
@mouradski Under the new light of ctcdecode, you may want to wait until this lands to complete your changes, but it's still interesting

**Comment by reuben** [comment]
Duplicate of #1125.
