### ISSUE TITLE
bin/import_librivox.py: No module named 'util'

### ISSUE THREAD

**Issue by mehadi-trackrep** [mozilla/DeepSpeech#1658]
from util.downloader import maybe_download
ModuleNotFoundError: No module named 'util'

**Comment by lissyx** [comment]
@mehadi-trackrep Do you care to give more informations ?

**Comment by mehadi-trackrep** [comment]
Actually, when I run the bin/import_librivox.py there is an error like that. I haven't understood how to solve it. Already I have tried to install all packages of 'util' but it didn't work.

**Comment by lissyx** [comment]
@mehadi-trackrep How do you run it ? How did you setup your virtualenv ?

**Comment by lissyx** [comment]
I'm unable to repro, and no news from @mehadi-trackrep. Closing, as it's likely just wrong usage / setup. Please re-open if you reproduce and provide more STR / documentation on your setup.
