### ISSUE TITLE
preprocess generate feature for all dataset?

### ISSUE THREAD

**Issue by zhangjinhong17** [mozilla/DeepSpeech#1664]
I found in the code preprocess.py, it will generate the feature for all dataset before training.
and we can save it to hdf5_cache_path, so next time, we don't need re-generate feature again. Is it right?

My question is , if the dataset is super big, it will use all of the memory and out of memory.
Is there any option to generate the feature real time, which is previous used?

![image](https://user-images.githubusercontent.com/32910309/47329507-d62bd480-d629-11e8-9646-4233602897e5.png)

Thanks
Jinhong

**Comment by lissyx** [comment]
@zhangjinhong17 Please refrain from using screenshots to document : it is hard to read for everyone, and not searchable. As a side effect, I'm unable to see the point you are exposing.

**Comment by lissyx** [comment]
> generate the feature real time

@reuben will correct me if I'm wrong, but this was slowing down the training enough that the increase in memory usage from features preprocessing was a big win. So I don't think we kept a code path allowing not to use.

**Comment by reuben** [comment]
>  Is there any option to generate the feature real time, which is previous used?

Alex's comments are correct. No such option exists for now, but we are planning to at least add chunking so you can split the preprocessed features in several files and load them as they're needed.

**Comment by zhangjinhong17** [comment]
> > Is there any option to generate the feature real time, which is previous used?
> 
> Alex's comments are correct. No such option exists for now, but we are planning to at least add chunking so you can split the preprocessed features in several files and load them as they're needed.

Thanks your guys. I know the pereprocess is faster. You don't need add chunking for it. I can do it by myself if need.
