### ISSUE TITLE
Write Python/NumPy bindings for ctcdecode and use it where we currently use libctc_decoder_with_kenlm.so

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#1675]
- [x] Write ctcdecode bindings
- [x] Switch Python code to it
- [x] Remove old CTC code & KenLM scorer

**Comment by mouradski** [comment]
So with that we can more easily add the timeline of words ?

https://github.com/mozilla/DeepSpeech/issues/1656
