### ISSUE TITLE
Extracting alignment data of detected speech

### ISSUE THREAD

**Issue by saeidaau** [mozilla/DeepSpeech#1684]
I am using DeepSpeech 1.1.0 on some .wav files. This command works well on my machine:

`$deepspeech models/output_graph.pb sample.wav models/alphabet.txt`

I need to extract and save the alignment data of detected speech. For example when I perform  the DeepSpeech on the file "sample.wav" and detected speech is "How are you", I need a vector that shows each character corresponds to which part of the "sample.wav" audio signal.

Anyone can help me?

Thank you all in advance.

**Comment by saeidaau** [comment]
@reuben 
Any suggestion?

**Comment by kdavis-mozilla** [comment]
When PR #1679 lands this should be solved.

**Comment by reuben** [comment]
Not really as that PR only switches our existing features to ctcdecode, exposing timing, result probabilities, etc are going to be follow up PRs. But I'm pretty sure there's already an issue for timing output here somewhere.

**Comment by reuben** [comment]
Yes, issue #1125.
