### ISSUE TITLE
Evaluate error - FailedPreconditionError (see above for traceback): sequence_length(0) <= 1696

### ISSUE THREAD

**Issue by GabrielLin** [mozilla/DeepSpeech#1691]
I am facing the following error when I ran the command. Could you help? Many thanks.
`python -u evaluate.py --test_files /home2/xxxx/nlp/DeepSpeech-020/data/Libri/librivox-test-clean.csv --n_hidden 2048 --checkpoint_dir ~/.local/share/deepspeech/pre-train`

> 
> Preprocessing ['/home2/xxxx/nlp/DeepSpeech-020/data/Libri/librivox-test-clean.csv']
> Preprocessing done
> 100% (2619 of 2619) |####################| Elapsed Time: 0:08:40 Time:  0:08:40
>   0% (1 of 2619) |                       | Elapsed Time: 0:00:15 ETA:  11:21:19Traceback (most recent call last):
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
>     return fn(*args)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: sequence_length(0) <= 1696
> 	 [[{{node CTCBeamSearchDecoderWithLM}} = CTCBeamSearchDecoderWithLM[alphabet_path="data/alphabet.txt", beam_width=1024, lm_weight=1.5, merge_repeated=false, model_path="data/lm/lm.binary", top_paths=1, trie_path="data/lm/trie", valid_word_count_weight=2.1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_1, _arg_Placeholder_1_0_0)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "evaluate.py", line 258, in <module>
>     tf.app.run(main)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "evaluate.py", line 225, in main
>     label_lengths_ph: label_lengths
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
>     run_metadata_ptr)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
>     run_metadata)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: sequence_length(0) <= 1696
> 	 [[{{node CTCBeamSearchDecoderWithLM}} = CTCBeamSearchDecoderWithLM[alphabet_path="data/alphabet.txt", beam_width=1024, lm_weight=1.5, merge_repeated=false, model_path="data/lm/lm.binary", top_paths=1, trie_path="data/lm/trie", valid_word_count_weight=2.1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_1, _arg_Placeholder_1_0_0)]]
> 
> Caused by op 'CTCBeamSearchDecoderWithLM', defined at:
>   File "evaluate.py", line 258, in <module>
>     tf.app.run(main)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "evaluate.py", line 138, in main
>     beam_width=FLAGS.beam_width)
>   File "/home2/xxxx/nlp/DeepSpeech-030/DeepSpeech.py", line 489, in decode_with_lm
>     top_paths=top_paths, merge_repeated=merge_repeated))
>   File "<string>", line 103, in ctc_beam_search_decoder_with_lm
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
>     return func(*args, **kwargs)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
>     op_def=op_def)
>   File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> FailedPreconditionError (see above for traceback): sequence_length(0) <= 1696
> 	 [[{{node CTCBeamSearchDecoderWithLM}} = CTCBeamSearchDecoderWithLM[alphabet_path="data/alphabet.txt", beam_width=1024, lm_weight=1.5, merge_repeated=false, model_path="data/lm/lm.binary", top_paths=1, trie_path="data/lm/trie", valid_word_count_weight=2.1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_1, _arg_Placeholder_1_0_0)]]
> 
>

**Comment by GabrielLin** [comment]
My version is 0.3.0; Please ignore the character in my command. I just reuse the data of version 0.2.0. Actually, I also facing the same issue in version 0.2.0.

**Comment by lissyx** [comment]
@GabrielLin Try passing `ignore_longer_outputs_than_inputs=True`, I ran into this on some dataset, I'm not sure yet if we have a bug in DeepSpeech or in those datasets.

**Comment by lissyx** [comment]
Or @reuben is it possible we broke something on `evaluate.py` ?

**Comment by lissyx** [comment]
> @lissyx Thanks for your rapid reply. I have added `ignore_longer_outputs_than_inputs=True`, but the error still appeared. I am also facing the error on TIMIT dataset.
> 
> The evaluate script is OK for the following command:
> `python -u evaluate.py --test_files /home2/xxxx/nlp/DeepSpeech-030/data/ldc93s1/ldc93s1.csv --n_hidden 2048 --checkpoint_dir ~/.local/share/deepspeech/pre-train `

So is it possible there some empty text for an audio in `librivox-test-clean.csv` ?

**Comment by GabrielLin** [comment]
> > @lissyx Thanks for your rapid reply. I have added `ignore_longer_outputs_than_inputs=True`, but the error still appeared. I am also facing the error on TIMIT dataset.
> > The evaluate script is OK for the following command:
> > `python -u evaluate.py --test_files /home2/xxxx/nlp/DeepSpeech-030/data/ldc93s1/ldc93s1.csv --n_hidden 2048 --checkpoint_dir ~/.local/share/deepspeech/pre-train `
> 
> So is it possible there some empty text for an audio in `librivox-test-clean.csv` ?

Oh, it might be. I removed all lines in librivox-test-clean.csv except the first two lines. There is not error. But I just created librivox-test-clean.csv by using import_librivox.py.

Do you have the same situation in the lastest repository? @lissyx Thanks.

**Comment by lissyx** [comment]
> > > @lissyx Thanks for your rapid reply. I have added `ignore_longer_outputs_than_inputs=True`, but the error still appeared. I am also facing the error on TIMIT dataset.
> > > The evaluate script is OK for the following command:
> > > `python -u evaluate.py --test_files /home2/xxxx/nlp/DeepSpeech-030/data/ldc93s1/ldc93s1.csv --n_hidden 2048 --checkpoint_dir ~/.local/share/deepspeech/pre-train `
> > 
> > 
> > So is it possible there some empty text for an audio in `librivox-test-clean.csv` ?
> 
> Oh, it might be. I removed all lines in librivox-test-clean.csv except the first two lines. There is not error. But I just created librivox-test-clean.csv by using import_librivox.py.
> 
> Do you have the same situation in the lastest repository? @lissyx Thanks.

I don't really have time to check :/

**Comment by TrinaDu** [comment]
> I am facing the following error when I ran the command. Could you help? Many thanks.
> `python -u evaluate.py --test_files /home2/xxxx/nlp/DeepSpeech-020/data/Libri/librivox-test-clean.csv --n_hidden 2048 --checkpoint_dir ~/.local/share/deepspeech/pre-train`
> 
> > Preprocessing ['/home2/xxxx/nlp/DeepSpeech-020/data/Libri/librivox-test-clean.csv']
> > Preprocessing done
> > 100% (2619 of 2619) |####################| Elapsed Time: 0:08:40 Time:  0:08:40
> > 0% (1 of 2619) |                       | Elapsed Time: 0:00:15 ETA:  11:21:19Traceback (most recent call last):
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
> > return fn(*args)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
> > options, feed_dict, fetch_list, target_list, run_metadata)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
> > run_metadata)
> > tensorflow.python.framework.errors_impl.FailedPreconditionError: sequence_length(0) <= 1696
> > [[{{node CTCBeamSearchDecoderWithLM}} = CTCBeamSearchDecoderWithLM[alphabet_path="data/alphabet.txt", beam_width=1024, lm_weight=1.5, merge_repeated=false, model_path="data/lm/lm.binary", top_paths=1, trie_path="data/lm/trie", valid_word_count_weight=2.1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_1, _arg_Placeholder_1_0_0)]]
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "evaluate.py", line 258, in 
> > tf.app.run(main)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> > _sys.exit(main(argv))
> > File "evaluate.py", line 225, in main
> > label_lengths_ph: label_lengths
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
> > run_metadata_ptr)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
> > feed_dict_tensor, options, run_metadata)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
> > run_metadata)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
> > raise type(e)(node_def, op, message)
> > tensorflow.python.framework.errors_impl.FailedPreconditionError: sequence_length(0) <= 1696
> > [[{{node CTCBeamSearchDecoderWithLM}} = CTCBeamSearchDecoderWithLM[alphabet_path="data/alphabet.txt", beam_width=1024, lm_weight=1.5, merge_repeated=false, model_path="data/lm/lm.binary", top_paths=1, trie_path="data/lm/trie", valid_word_count_weight=2.1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_1, _arg_Placeholder_1_0_0)]]
> > Caused by op 'CTCBeamSearchDecoderWithLM', defined at:
> > File "evaluate.py", line 258, in 
> > tf.app.run(main)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> > _sys.exit(main(argv))
> > File "evaluate.py", line 138, in main
> > beam_width=FLAGS.beam_width)
> > File "/home2/xxxx/nlp/DeepSpeech-030/DeepSpeech.py", line 489, in decode_with_lm
> > top_paths=top_paths, merge_repeated=merge_repeated))
> > File "", line 103, in ctc_beam_search_decoder_with_lm
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> > op_def=op_def)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
> > return func(*args, **kwargs)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
> > op_def=op_def)
> > File "/home2/xxxx/pkgs/miniconda2/envs/py36ds030/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in **init**
> > self._traceback = tf_stack.extract_stack()
> > FailedPreconditionError (see above for traceback): sequence_length(0) <= 1696
> > [[{{node CTCBeamSearchDecoderWithLM}} = CTCBeamSearchDecoderWithLM[alphabet_path="data/alphabet.txt", beam_width=1024, lm_weight=1.5, merge_repeated=false, model_path="data/lm/lm.binary", top_paths=1, trie_path="data/lm/trie", valid_word_count_weight=2.1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_1, _arg_Placeholder_1_0_0)]]

I got the same problem, and think there are two bugs:

1. test_data['features'] = test_data['features'].apply(create_windows)
    + test_data['features_len'] = test_data['features'].apply(len)
   the feature_len should be updated accordingly

2. pass by reference error
   -batch_features_len = batch['features_len'].values
   +batch_features_len = batch['features_len'].values.copy()

Now it works well for me.

**Comment by kdavis-mozilla** [comment]
@TrinaDu Would you be up for creating a small PR?

**Comment by GabrielLin** [comment]
@TrinaDu  Thank you for your solution. I have just figured out this issue in another way. I followed the code from DeepSpeech.py. Maybe your solution is better. I hope you can create your pull request.

**Comment by lissyx** [comment]
Closing since the matching PR seems not to be useful anymore.
