### ISSUE TITLE
Feature cache documentation

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#1709]
This is about `--train_cached_features_path`, `--dev_cached_features_path` and `--test_cached_features_path` options.
- They are not supporting comma separated lists of cache files yet. If not added, the statement should at least be removed from their respective help texts.
- We should provide a brief description of the feature in documentation and help texts.

**Comment by kdavis-mozilla** [comment]
I think for 0.7.0 we should at least fix the help texts
