### ISSUE TITLE
Error: Trie file version mismatch (3 instead of expected 2). Update your trie file.

### ISSUE THREAD

**Issue by cogmeta** [mozilla/DeepSpeech#1714]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
mozilla tensorflow
- **TensorFlow version (use command below)**:
v1.12.0-0-ga6d8ffae09 1.12.0

- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

In deepspeech version 0.3.0, I can not load trie file generated with generate_trie.  In trie_node.h, It is expecting file version to be 2 while generate_trie is dumping file version 3 (in scorer.cpp ).

in trie_node.h

https://github.com/mozilla/DeepSpeech/blob/8b0abd5364e154c9c5f057386c9c77a971c39462/native_client/trie_node.h#L28

In scorer.cpp 

https://github.com/mozilla/DeepSpeech/blob/8b0abd5364e154c9c5f057386c9c77a971c39462/native_client/ctcdecode/scorer.cpp#L17

**Comment by cogmeta** [comment]
Now, I am getting Error: Can't parse trie file, invalid header. Try updating your trie file.

**Comment by cogmeta** [comment]
I am using version 0.3.0 of deepspeech installed with pip.
pip3 list | grep deepspeech
deepspeech (0.3.0)

I installed the native client with v0.3.0 tag
python3 util/taskcluster.py --branch "v0.3.0" --target .

The generate trie file is not compatible.

**Comment by lissyx** [comment]
> Now, I am getting Error: Can't parse trie file, invalid header. Try updating your trie file.

You need to give more context. Are you training ? Running inference ? Have you carefully read the docs ?

**Comment by lissyx** [comment]
> The generate trie file is not compatible.

`generate_trie` or generated trie file ?

**Comment by cogmeta** [comment]
Loading model from file output_graph.pbmm
TensorFlow: v1.11.0-9-g97d851f
DeepSpeech: v0.3.0-0-gef6b5bd
2018-11-07 22:42:36.782568: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.00443s.
Loading language model from files smarthome.klm smarthome.trie
Error: Can't parse trie file, invalid header. Try updating your trie file.
Loaded language model in 0.000197s.
Running inference.
becreatedbanspee
Inference took 1.411s for 2.013s audio file.

**Comment by lissyx** [comment]
@cogmeta Can you include your full command-line?

**Comment by cogmeta** [comment]
deepspeech --model output_graph.pbmm --alphabet alphabet.txt --lm smarthome.klm --trie smarthome.trie --audio ~/exp/sample1.wav

**Comment by lissyx** [comment]
> Loading language model from files smarthome.klm smarthome.trie Error: Can't parse trie file, invalid header. Try updating your trie file.

This output looks weird, are you passing multiple file names ?

**Comment by lissyx** [comment]
> > Loading language model from files smarthome.klm smarthome.trie Error: Can't parse trie file, invalid header. Try updating your trie file.
> 
> This output looks weird, are you passing multiple file names ?

Never mind, it's me

**Comment by cogmeta** [comment]
I have looked at the code in trie_node.h carefully. In 0.3.0, it expected magic word "TRIE" at the beginning followed by version number (2). The trie file generated with generate_trie, version 0.3.0, does not have this format.

**Comment by lissyx** [comment]
> `deepspeech --model output_graph.pbmm --alphabet alphabet.txt --lm smarthome.klm --trie smarthome.trie --audio ~/exp/sample1.wav`

That looks correct, are you sure `smarthome.trie` is good ? What's its size ?

**Comment by cogmeta** [comment]
ls -al smarthome.trie 
-rw-rw-r-- 1 XXXXX XXXX 124541 Nov  7 22:46 smarthome.trie

**Comment by lissyx** [comment]
> ls -al smarthome.trie
> -rw-rw-r-- 1 XXXXX XXXX 124541 Nov 7 22:46 smarthome.trie

And `head -n1 smarthome.trie` ?

**Comment by cogmeta** [comment]
It is failing here because magic is missing.

https://github.com/mozilla/DeepSpeech/blob/b022f02f26eb33a043cb85332448de281d512e39/native_client/trie_node.h#L60

**Comment by cogmeta** [comment]
head -1 smarthome.trie 
1414678853

**Comment by lissyx** [comment]
> head -1 smarthome.trie
> 1414678853

Clearly not expected. Can you share the whole content ? Can you trie to re-generate with `generate_trie`, ensuring you are using the matching version ?

**Comment by cogmeta** [comment]
I am looking at the code in generate_trie.cpp. I dont see the magic word (TRIE) and version number getting dumped anywhere. What am I missing? 

https://github.com/mozilla/DeepSpeech/blob/ef6b5bd4707ca5042c04f07236cd3f028d279b26/native_client/generate_trie.cpp#L36

**Comment by cogmeta** [comment]
Well, that points to master one. v0.3.0 is different. generate_trie expected one more argument (vocab.txt) 

./generate_trie ../data/alphabet.txt /tmp/lm.binary /tmp/vocab.txt /tmp/trie


https://github.com/mozilla/DeepSpeech/blob/v0.3.0/data/lm/README.md

**Comment by cogmeta** [comment]
It works! My apologies! I mixed up version. @lissyx  Thank you so much.
