### ISSUE TITLE
New ctc decoder - missing coordinator argument 

### ISSUE THREAD

**Issue by robmsmt** [mozilla/DeepSpeech#1722]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 1804 Server
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Tensorflow from requirements file:  
- **TensorFlow version (use command below)**: v1.12
- **Python version**: 3.6
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

run any of the deepspeech runscripts with the new ctc decoder. Seems to be missing self command 394 of util/coordinator.py

: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
D Starting queue runners...
D Queue runners started.
I STARTING Optimization
D step: 250473
D epoch: 315
D target epoch: 323
D steps per epoch: 793
D number of batches in train set: 793
D batches per job: 1
D batches per step: 1
D number of jobs in train set: 793
D number of jobs already trained in first epoch: 678
E __init__() missing 1 required positional argument: 'num_jobs'
Traceback (most recent call last):
  File "DeepSpeech.py", line 551, in train
    coord.start_coordination(model_feeder, step)
  File "/fast/DeepSpeech-gpu/util/coordinator.py", line 349, in start_coordination
    self._next_epoch()
  File "/fast/DeepSpeech-gpu/util/coordinator.py", line 394, in _next_epoch
    self._epochs_running.append(Epoch(self._epoch, self._num_jobs_dev, set_name='dev'))
TypeError: __init__() missing 1 required positional argument: 'num_jobs'
D Closing queues...
D Queues closed.

**Comment by lissyx** [comment]
Thanks !
