### ISSUE TITLE
building native client with bazel fails on ppc64le

### ISSUE THREAD

**Issue by bill-kalog** [mozilla/DeepSpeech#1728]
Hi,

I was trying to built DeepSpeech with bazel from the master branch on a ppc64le architecture but
I got the following error (I never had a problem with the previous deepspeech versions, at least until 0.2..)

```
ERROR: /tensorflow/native_client/BUILD:41:1: Configurable attribute "linkopts" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //tensorflow:darwin
 //tensorflow:linux_x86_64
 //tensorflow:rpi3
 //tensorflow:rpi3-armv8
ERROR: Analysis of target '//native_client:libdeepspeech.so' failed; build aborted:

/tensorflow/native_client/BUILD:41:1: Configurable attribute "linkopts" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //tensorflow:darwin
 //tensorflow:linux_x86_64
 //tensorflow:rpi3
 //tensorflow:rpi3-armv8
INFO: Elapsed time: 6.846s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded)
FAILED: Build did NOT complete successfully (11 packages loaded)
```

So, I added the line `"//tensorflow:linux_ppc64le": LINUX_LINKOPTS,` inside the `native_client/BUILD` file and it the eventually built successfully. However, I am a bit clueless so I was wondering, was this the correct approach?should something else change as well?

**Comment by lissyx** [comment]
@bill-kalog ^

**Comment by bill-kalog** [comment]
thanks for the info! will try to further test it and maybe do a pull request if I am succesful
