### ISSUE TITLE
Bool Args documentation

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/DeepSpeech#1730]
we don't have anything saying --notrain is the opposite of --train True

**Comment by JRMeyer** [comment]
This is for the utils/flags.py script

**Comment by reuben** [comment]
This is already documented in the output of `--helpfull`, where else do you think we should have it?

```
  --[no]early_stop: enable early stopping mechanism over validation dataset. Make sure that dev FLAG is enabled for this to work
    (default: 'true')
```
