### ISSUE TITLE
Issue while training Deepspeech in distributed mode 

### ISSUE THREAD

**Issue by code-R** [mozilla/DeepSpeech#1731]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No (using latest master - 02af22b69214fa1869fd51effc776a6810a5ed51)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**: 1.12.0rc2
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: No Gpu
- **CUDA/cuDNN version**: No Gpu
- **GPU model and memory**: No Gpu
- **Exact command to reproduce**: I am trying to run on the distributed tensorflow

This is to startup the params server 
```
python -u DeepSpeech.py \ 
--train_files data/ldc93s1/ldc93s1.csv \
--dev_files data/ldc93s1/ldc93s1.csv \
--test_files data/ldc93s1/ldc93s1.csv \
--train_batch_size 1 \
--dev_batch_size 1 \
--test_batch_size 1 \
--n_hidden 494 \
--epoch 15 \
--ps_hosts localhost:2000 \
--worker_hosts localhost:3000 \
--task_index=0 \
--checkpoint_dir /tmp/deepspeech/ldc93s1 \
--export_dir /tmp/deepspeech/models \
--job_name=ps
```
This is to run the woker
```
python -u DeepSpeech.py \    
--train_files data/ldc93s1/ldc93s1.csv \   
--dev_files data/ldc93s1/ldc93s1.csv \
--test_files data/ldc93s1/ldc93s1.csv \
--train_batch_size 1 \
--dev_batch_size 1 \
--test_batch_size 1 \
--n_hidden 494 \
--epoch 15 \
--ps_hosts localhost:2000 \
--worker_hosts localhost:3000 \
--task_index=0 \
--checkpoint_dir /tmp/deepspeech/ldc93s1 \
--export_dir /tmp/deepspeech/models \
--job_name=worker
```

this above code threw this error

> Traceback (most recent call last):
>   File "DeepSpeech.py", line 942, in <module>
>     tf.app.run(main)
>   File "/Users/coder/.virtualenvs/moz-ds/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "DeepSpeech.py", line 926, in main
>     train(server)
>   File "DeepSpeech.py", line 476, in train
>     hooks.append(optimizer.make_session_run_hook(is_chief))
> NameError: name 'is_chief' is not defined

https://github.com/mozilla/DeepSpeech/blob/02af22b69214fa1869fd51effc776a6810a5ed51/DeepSpeech.py#L476

is_chief is not defined anywhere above in the code...it should be Config.is_chief? I can contribute to this issue..but, I would like to understand if whatever I am trying is correct or is it something I am missing while trying run-cluster script?

**Comment by reuben** [comment]
Yep, it should be `Config.is_chief`. We recently refactored this code and it looks like that part has slipped through as we haven't tested the cluster mode.

**Comment by code-R** [comment]
@reuben I have created a pull request, can you please review it. I am currently trying to run deepspeech in cluster mode, if I find any issues I will report them.

**Comment by reuben** [comment]
@code-R merged, thanks for filing the issue and sending the PR! Feel free to comment here or create a new issue if you find any other problems.
