### ISSUE TITLE
Display progress information while preprocessing audio files

### ISSUE THREAD

**Issue by j-a-h-i-r** [mozilla/DeepSpeech#1739]
Currently preprocessing scripts in `DeepSpeech/util` only displays the filenames that are currently being processed. But with large audio files, it takes quite some time and it would be helpful to have some progress information.

**Comment by visi0nary** [comment]
This should be switchable though. When huge CSVs with tens of thousands of entries are processed you get a huge I/O overhead if the preprocessing script is too verbose ;-)

**Comment by lissyx** [comment]
This is something that has been implemented. Closing the issue.
