### ISSUE TITLE
Increase mfcc step size instead of throwing away feature frames

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#1744]
https://github.com/mozilla/DeepSpeech/blob/a3a96cf2d1030a7906ae6d7eff83c2bed3cfe143/util/audio.py#L17-L21

We could instead pass `winlen=0.03s` and `winstep=0.02s` to `mfcc` to get the same rate of feature windows over time, but without discarding any data.

**Comment by khsinclair** [comment]
I'd recommend increasing step to 0.032 to match the 512-sample FFT.  This avoids creating the step discontinuity when using the traditional Hamming window.  That is, a 480-sample step adds 32 zeroes to create a 512-sample FFT, and the discontinuity of the raised cosine window at sample 480 produces some spectral splatter.

HOWEVER, it appears to me that line 226 of deepspeech.cc invokes feature generation with NO window function at all, and that's a serious problem.  Is that indeed the usual path for audio feature generation?

Also note that any of these changes will make existing models incompatible with new audio, to various degrees.  I don't know what your compatibility policy is for this.

**Comment by khsinclair** [comment]
Without a window function, the current implementation with 0.025s step has two discontinuities in the FFT input: one at sample 400 and one at sample 512/0.  Not good.

**Comment by kdavis-mozilla** [comment]
>  I don't know what your compatibility policy is for this.

Currently, as we are not to 1.0, we are free to break backwards compatibility when the engine benefits.

**Comment by reuben** [comment]
@khsinclair thanks for the tips! I've created PR #1773 fixing this.
