### ISSUE TITLE
How to train data from comom voice 

### ISSUE THREAD

**Issue by kurodenjiro** [mozilla/DeepSpeech#1748]
hello im starter of machine learning . i want to train data from comom voice can you help me ?

**Comment by kdavis-mozilla** [comment]
The documentation cover this topic [Common Voice training data](https://github.com/mozilla/DeepSpeech/tree/issue1740%2B1747#common-voice-training-data).

**Comment by kurodenjiro** [comment]
> The documentation cover this topic [Common Voice training data](https://github.com/mozilla/DeepSpeech/tree/issue1740%2B1747#common-voice-training-data).

I want to train common voice on my cloud amazon so how can i do it ?

**Comment by kdavis-mozilla** [comment]
This is better dealt with either on [discourse](https://discourse.mozilla.org/c/deep-speech) or by using Amazon's documentation.
