### ISSUE TITLE
KeyError: '\n'

### ISSUE THREAD

**Issue by SkyFire512** [mozilla/DeepSpeech#1759]
Greetings,

My and my mates have been attempting to create a model for the Urdu language through Deep-speech. Ive been following these 2 amazing guides for creating the dataset, the alphabet list, the language model, the trie, and finally the model.

https://github.com/mozilla/DeepSpeech#training
https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830/19

I believe I am now at the stage to run training in order to create and export the model, however, the command for doing so returns an error(full stack trace can be found below):

Preprocessing ['/home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-train/cv-valid-train.csv']
Traceback (most recent call last):
  File "/home/hmr/DeepSpeech/util/text.py", line 33, in label_from_string
    return self._str_to_label[string]
KeyError: '\n'

Its telling me that my transcript contains characters not in my alphabets list. I have double checked to make sure this is not the case, and I have also made sure to cover superscripts in the alphabets. I have seen other related issues on this repo, and at "KeyError: 'XXX' " im supposed to see the characters that were missing. I skimmed the code, and it seems '\n' characters are supposed to be removed entirely automatically, so i'm confused as to why it is asking me for '\n'. Any insight to this would be highly appreciated.

Here is my alphabet list:
https://pastebin.com/57PggL5s

And here is the transcript from which the alphabets were extracted (yes I specifically extracted from the transcript so I wouldn't miss anything):
https://pastebin.com/wza6RQqA

- No modified code.
- OS: Ubuntu 18.04
- TensorFlow Version: v1.12.0-rc2-0-g748435b8ef 1.12.0-rc2
- Python 3.6.5 
- CUDA: release 9.0, V9.0.176
- Using a cpu for now, will port to gpu machine later.
- python -u DeepSpeech.py \
  --train_files /home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-train/cv-valid-train.csv \
  --dev_files /home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-dev/cv-valid-dev.csv \
  --test_files /home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-test/cv-valid-test.csv \
  --export_dir /home/hmr/DeepSpeech/data/results/model_export/ \
  --checkpoint_dir /home/hmr/DeepSpeech/data/results/checkout/ \
  --alphabet_config_path /home/hmr/DeepSpeech/data/alphabet.txt \
  --lm_binary_path /home/hmr/DeepSpeech/data/lm.binary \
  --lm_trie_path /home/hmr/DeepSpeech/data/trie \

Full Stack trace:
(deepspeech-venv) hmr@hmr-All-Series:~/DeepSpeech$ python -u DeepSpeech.py \
>   --train_files /home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-train/cv-valid-train.csv \
>   --dev_files /home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-dev/cv-valid-dev.csv \
>   --test_files /home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-test/cv-valid-test.csv \
>   --export_dir /home/hmr/DeepSpeech/data/results/model_export/ \
>   --checkpoint_dir /home/hmr/DeepSpeech/data/results/checkout/ \
>   --alphabet_config_path /home/hmr/DeepSpeech/data/alphabet.txt \
>   --lm_binary_path /home/hmr/DeepSpeech/data/lm.binary \
>   --lm_trie_path /home/hmr/DeepSpeech/data/trie \
> 

Preprocessing ['/home/hmr/DeepSpeech/data/CV-Compatible-Urdu-Dataset/cv-valid-train/cv-valid-train.csv']
Traceback (most recent call last):
  File "/home/hmr/DeepSpeech/util/text.py", line 33, in label_from_string
    return self._str_to_label[string]
KeyError: '\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 941, in <module>
    tf.app.run(main)
  File "/home/hmr/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 893, in main
    train()
  File "DeepSpeech.py", line 388, in train
    hdf5_cache_path=FLAGS.train_cached_features_path)
  File "/home/hmr/DeepSpeech/util/preprocess.py", line 69, in preprocess
    out_data = pmap(step_fn, source_data.iterrows())
  File "/home/hmr/DeepSpeech/util/preprocess.py", line 13, in pmap
    results = pool.map(fun, iterable)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/hmr/DeepSpeech/util/preprocess.py", line 23, in process_single_file
    transcript = text_to_char_array(file.transcript, alphabet)
  File "/home/hmr/DeepSpeech/util/text.py", line 64, in text_to_char_array
    return np.asarray([alphabet.label_from_string(c) for c in original])
  File "/home/hmr/DeepSpeech/util/text.py", line 64, in <listcomp>
    return np.asarray([alphabet.label_from_string(c) for c in original])
  File "/home/hmr/DeepSpeech/util/text.py", line 44, in label_from_string
    ).with_traceback(e.__traceback__)
  File "/home/hmr/DeepSpeech/util/text.py", line 33, in label_from_string
    return self._str_to_label[string]
KeyError: '\n                ERROR: You have characters in your transcripts\n                       which do not occur in your data/alphabet.txt\n                       file. Please verify that your alphabet.txt\n                       contains all neccessary characters. Use\n                       util/check_characters.py to see what characters are in\n                       your train / dev / test transcripts.\n 

^(yes it appears exactly like this in the terminal)

**Comment by visi0nary** [comment]
Have you used "util/check_characters.py" on your transcripts to make sure all characters are in the alphabet?

**Comment by SkyFire512** [comment]
The issue has been resolved. The transcripts in my .csv were ending in '\n'. Removing them resolved it.
