### ISSUE TITLE
Improving the accuracy of the speech recognition with newer iterations of deepspeech or other competing techniques in deep speech recognition!

### ISSUE THREAD

**Issue by shyamalschandra** [mozilla/DeepSpeech#1764]
Are you working on improving the accuracy or tips to tune it to get better accuracy with the current tool in deepspeech from Mozilla?

**Comment by kdavis-mozilla** [comment]
We are, but this is better addressed in our Deep Speech [Discourse Forum](https://discourse.mozilla.org/c/deep-speech). We try to use issues only for bugs and feature requests.

**Comment by shyamalschandra** [comment]
Thank you! I left more information on my question on the Discourse Forum for Deep Speech. (https://arxiv.org/pdf/1707.07413.pdf)
