### ISSUE TITLE
Add comments for all the packages in the requirements.txt file

### ISSUE THREAD

**Issue by nullbyte91** [mozilla/DeepSpeech#1766]
I would like to add comments for all the packages in the requirements.txt file. A simple note why that package is on the list like below, 
`pandas #Lib for Flexible and powerful data analysis/manipulation`
`progressbar2 #Lib for Text progress bar`
`bs4 #Package for parsing HTML and XML documents`
`six #Provides simple utilities for wrapping over differences between Python 2 and Python 3`
`requests #Python HTTP library provies to make HTTP requests simpler and more human-friendly`
`librosa #Package for music and audio analysis`

**Comment by lissyx** [comment]
Comments can only be new lines in `requirements.txt`, and I'm unsure about the value this brings: can you explain why it's important ?

**Comment by nullbyte91** [comment]
@lissyx I'm a newbie to Deep Speech and When I was going through the requirements.txt file, I was googling to understand few packages features. So, I thought good to have the package description in that file.
