### ISSUE TITLE
SoX error while extracting bin/import_cv.py on Intel AI DevCloud

### ISSUE THREAD

**Issue by MAkramHanif** [mozilla/DeepSpeech#1768]
I am using Intel AI Dev Cloud for training a model in deepSpeech but when i try to extracting bin.import_cv.py i get error unable to find Sox 
i tried installing sox using pip3 but i didn't find Sox 
there is an issue in Intel AI Dev Cloud is i can't have privilige to install new software using apt-get or yum 
so is there any way i can install sox without any privilige please let me know

**Comment by lissyx** [comment]
No, this is not something we can help about, sorry.
