### ISSUE TITLE
 5 seconds audio limitation

### ISSUE THREAD

**Issue by pietrop** [mozilla/DeepSpeech#1769]
Hello, 
Thanks for such a great project, really looking forward to see how it shapes up. 

This is more of just a question. I was wondering about the 5 seconds audio limitation mentioned in the README. Does this still apply? and are there plans to extend that in the future?

**Comment by kdavis-mozilla** [comment]
You can now stream audio. There are several examples in the [examples](https://github.com/mozilla/DeepSpeech/tree/master/examples) folder.

**Comment by pietrop** [comment]
Thansk, might be good to add this to the README.

**Comment by kdavis-mozilla** [comment]
PR's welcome 😉
