### ISSUE TITLE
Unable to download git LFS model files

### ISSUE THREAD

**Issue by 9define** [mozilla/DeepSpeech#1774]
I am unable to download LM files from GitHub. I've tried using other ISPs (via mobile) and VPNs, but I always get a 404. An example file is the [lm.binary file](https://media.githubusercontent.com/media/mozilla/DeepSpeech/v0.3.0/data/lm/lm.binary). Here's a sample of the output when trying to use wget to download the file in a terminal, and the web UI just displays a blank page if I try to download the file in a browser.

```
wget https://media.githubusercontent.com/media/mozilla/DeepSpeech/v0.3.0/data/lm/lm.binary
--2018-12-10 11:24:39--  https://media.githubusercontent.com/media/mozilla/DeepSpeech/v0.3.0/data/lm/lm.binary
Cargado certificado CA '/etc/ssl/certs/ca-certificates.crt'
Resolviendo media.githubusercontent.com (media.githubusercontent.com)... 151.101.116.133
Conectando con media.githubusercontent.com (media.githubusercontent.com)[151.101.116.133]:443... conectado.
Petición HTTP enviada, esperando respuesta... 404 Not Found
2018-12-10 11:24:40 ERROR 404: Not Found.
```

I think this is a GH issue, but I'm not sure. Is anyone else seeing this issue? Is there something I can do to fix it?

**Comment by lissyx** [comment]
How exactly are you trying to do that? It's git-lfs binary's job to perform the download when you git fetch / checkout.

**Comment by 9define** [comment]
@lissyx Like my example shows I was using wget to try the download. It worked in the recent past, but 404s now. Thoughts?

**Comment by reuben** [comment]
Seems to be working again, looks like it was a GitHub bug.
