### ISSUE TITLE
Add Windows builds

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#1793]

**Comment by belkacem77** [comment]
Ce sera parfait si l'on peut entraîner aussi sur Windows.

**Comment by lissyx** [comment]
@belkacem77 This is something more in the hands of upstream than us :)

**Comment by lissyx** [comment]
For now, let's focus on getting at least `libdeepspeech.so` for CPU and GPU on `x64` platform, as well as the `.Net` bindings and the `NuGet` package. Early testing shows it's going to be a bit more painful to get Python / NodeJS bindings there.

**Comment by lissyx** [comment]
> Ce sera parfait si l'on peut entraîner aussi sur Windows.

It's going to be a bit more complicated, now we depend on `ds_ctcdecoder`, so we would need to build that on Windows

**Comment by lissyx** [comment]
Current status is that we have `libdeepspeech.so` and the `.Net Framework` examples building properly on TC, targetting CPU. Some packaging needs to be adjusted. Regarding CUDA builds, it's more or less solved, just dependent on some TaskCluster re-deployment.

**Comment by lissyx** [comment]
CPU and CUDA builds are okay.

**Comment by mozillakab** [comment]
@lissyx what do you mean are okay? is there any release for Windows?

**Comment by lissyx** [comment]
> @lissyx what do you mean are okay? is there any release for Windows?

It means the changes to have them are good, it should be able to get merged soon
