### ISSUE TITLE
vad transcriber issue in python 3.5

### ISSUE THREAD

**Issue by maddigibiter** [mozilla/DeepSpeech#1795]
I have been using deepspeech in python3 and have also managed to use audioTranscript_cmd.py to transcribe from wav to string however suddenly keep getting this error, 

```
$ python3 audioTranscript_cmd.py --aggressive 1 --audio /var/www/out.wav --model  /var/deepspeech/models
DEBUG:root:Transcribing audio file @ /var/www/objects/5/converted/out.wav
DEBUG:root:Found Model: /var/deepspeech/models/output_graph.rounded.pb
DEBUG:root:Found Alphabet: /var/deepspeech/models/alphabet.txt
DEBUG:root:Found Language Model: /var/deepspeech/models/lm.binary
DEBUG:root:Found Trie: /var/deepspeech/models/trie
TensorFlow: v1.11.0-9-g97d851f
DeepSpeech: v0.3.0-0-gef6b5bd
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-12-16 17:37:48.650243: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
DEBUG:root:Loaded model in 0.375s.
DEBUG:root:Loaded language model in 2.962s.

Filename                       Duration(s)          Inference Time(s)    Model Load Time(s)   LM Load Time(s)
DEBUG:root:Caught the wav file @: /var/www/out.wav
Traceback (most recent call last):
  File "audioTranscript_cmd.py", line 92, in <module>
    main(sys.argv[1:])
  File "audioTranscript_cmd.py", line 50, in main
    segments, sample_rate, audio_length = wavTranscriber.vad_segment_generator(waveFile, args.aggressive)
  File "/var/www/wavTranscriber.py", line 96, in vad_segment_generator
    audio, sample_rate, audio_length = wavSplit.read_wave(wavFile)
  File "/var/www/transcriberwavSplit.py", line 11, in read_wave
    with contextlib.closing(wave.open(path, 'rb')) as wf:
  File "/usr/lib/python3.5/wave.py", line 499, in open
    return Wave_read(f)
  File "/usr/lib/python3.5/wave.py", line 163, in __init__
    self.initfp(f)
  File "/usr/lib/python3.5/wave.py", line 128, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python3.5/chunk.py", line 63, in __init__
    raise EOFError
EOFError
```

I have re-installed all requirements, done a fresh install but still getting this error. I haven't made any changes to examples folder or any other part of codebase. Im using wav files, 16khz, mono. Have you experienced this before?

Br

**Comment by b-ak** [comment]
@maddigibiter can you try the same on the standard [audio samples](https://github.com/mozilla/DeepSpeech/releases/download/v0.3.0/audio-0.3.0.tar.gz).

**Comment by maddigibiter** [comment]
@b-ak it actually worked, my audio file is definitley 16khz mono and this is the command I use
`   ffmpeg -hide_banner -loglevel panic -i file.flac -acodec, pcm_s16le -ac 1 -ar 16000 out.wav
`
Any issue with this version? 

Thanks

**Comment by b-ak** [comment]
Can I get a copy of the wav ur file ?

**Comment by maddigibiter** [comment]
@b-ak issue was -acodec pcm_s16le - issue is resolved, thanks

**Comment by lissyx** [comment]
> @b-ak issue was -acodec pcm_s16le - issue is resolved, thanks

Thanks for updating us, but can you be more explicit? It's likely others will run into that as well, so your answer might be very useful.

**Comment by maddigibiter** [comment]
Of course @lissyx - I used one of flac files from an audio library, initially I was using  -acodec pcm_s16le in my ffmpeg transcoding. I changed it to as recommended in vad examples and didn't face errors any more. Works just fine when transcoding audio using this command

`ffmpeg -hide_banner -loglevel panic -i input.mp3 -ac 1 -ar 16000 output.wav
`
Having in mind these options are not required in ffmpeg command 

`-hide_banner -loglevel panic`

**Comment by b-ak** [comment]
@maddigibiter Does the same command work for flac files also ?

**Comment by MuruganR96** [comment]
Yes sir. Of course i did this. Flac to wav
