### ISSUE TITLE
KeyError: '\ufeff' starting training of model

### ISSUE THREAD

**Issue by ambigus9** [mozilla/DeepSpeech#1796]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.10
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 2.7.14
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/6.0.21
- **GPU model and memory**: GeForce GTX 1080Ti 11 GB
- **Exact command to reproduce**: 

```
python -u DeepSpeech.py \
--train_files /home/miguel/voice-to-text/csv/train.csv \
--dev_files datasets/concat/test.csv \
--test_files datasets/concat/test.csv \
--train_batch_size 16 \
--dev_batch_size 16 \
--test_batch_size 16 \
--n_hidden 512 \
--epoch 50 \
--display_step 1 \
--validation_step 1 \
--dropout_rate 0.2 \
--checkpoint_dir "/home/miguel/voice-to-text/checkpoints/fusion/" \
--decoder_library_path /home/ofnanezn/DeepSpeech-lfs/DeepSpeech/libctc_decoder_with_kenlm.so \
--lm_binary_path models/concat.binary \
--lm_trie_path data/trie_spanish \
--alphabet_config_path data/alphabet_no_number.txt \
--export_dir /home/miguel/voice-to-text/models/fusion 2>&1| tee -a /home/miguel/voice-to-text/log-vtt5.txt
```

Currently I'm getting this error:

```
/home/ofnanezn/deepspeech-venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ofnanezn/deepspeech-venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ofnanezn/DeepSpeech-lfs/DeepSpeech/util/feeding.py", line 151, in _populate_batch_queue
    raise ValueError('Error: Audio file {} is too short for transcription.'.format(wav_file))
ValueError: Error: Audio file /home/miguel/voice-to-text/final_output/1521175834.161321-7018-7018-20180315-235035/f000020.wav is too short for transcription.

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ofnanezn/DeepSpeech-lfs/DeepSpeech/util/feeding.py", line 148, in _populate_batch_queue
    target = text_to_char_array(transcript, self._alphabet)
  File "/home/ofnanezn/DeepSpeech-lfs/DeepSpeech/util/text.py", line 40, in text_to_char_array
    return np.asarray([alphabet.label_from_string(c) for c in original])
  File "/home/ofnanezn/DeepSpeech-lfs/DeepSpeech/util/text.py", line 40, in <listcomp>
    return np.asarray([alphabet.label_from_string(c) for c in original])
  File "/home/ofnanezn/DeepSpeech-lfs/DeepSpeech/util/text.py", line 30, in label_from_string
    return self._str_to_label[string]
KeyError: '\ufeff'
```
And it looks like it still traning:

![image](https://user-images.githubusercontent.com/16579856/50108032-3a21e200-0202-11e9-9b93-7090b7342673.png)

Currently i'm not getting any model at the end of the training.

**Comment by lissyx** [comment]
@ambigus9 You have two errors here, and they arise from your dataset:
> ValueError: Error: Audio file /home/miguel/voice-to-text/final_output/1521175834.161321-7018-7018-20180315-235035/f000020.wav is too short for transcription.

And:
> KeyError: '\ufeff'

Last one means you have chars in your transcriptions that are missing from your alphabet. You should have had a better exception error message, that points to the fact you are not running on master.

Please describe more your environment.

Also, avoid screenshots: it's painful to read.

**Comment by lissyx** [comment]
> Currently i'm not getting any model at the end of the training.

I'm unsure about that statement: you have errors, so it's expected not to finish anything.

**Comment by JRMeyer** [comment]
you're using old code. pull from master so you can have and use this new script: https://github.com/mozilla/DeepSpeech/blob/master/util/check_characters.py

**Comment by reuben** [comment]
\uFEFF is a byte order mark, maybe check if something in your process to create/manipulate transcripts is saving text files with a BOM.

**Comment by ambigus9** [comment]
Thanks! @lissyx and @JRMeyer i fix this issue on 2 steps:

1. Parse all transcriptions of audios as follows:

```
	    if '\ufeff' in line:
	        line = line.replace('\ufeff','')
```
2. To ignore small audios i filter them using librosa:
```
	x, sr = librosa.load("path_to_audio_file")
	ratio = len(x)/sr
	print(ratio)
	if ratio > 0.6:	
	    print("OK - ","path_to_audio_file" )
	    csv.writelines(line)
```

**Comment by lissyx** [comment]
Closing this since it was not an issue in the codebase but in your dataset.
