### ISSUE TITLE
wrong Inference results in DeepSpeech.  CPU vs GPU? 

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/DeepSpeech#1797]
Inference Running on GPU:
Linux Ubuntu 16.04
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.43
totalMemory: 3.94GiB
CUDA/cuDNN version:9.0

Inference Running on CPU:
Linux Ubuntu 16.04
i5 processor.
8 GB RAM

CPU gives Correct expected Inference result. like this,

```
deepspeech --model output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 1.wav
Loading model from file output_graph.pbmm
TensorFlow: v1.11.0-9-g97d851f
DeepSpeech: v0.3.0-0-gef6b5bd
Loaded model in 0.00495s.
Loading language model from files models/lm.binary models/trie
Loaded language model in 1.5s.
Running inference.
**a what is the benefit for pan card** 
Inference took 3.080s for 4.598s audio file.
```

but in GPU gives wrong inference for same model. like this,

```
deepspeech --model model_export_cv02/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 1.wav
Loading model from file model_export_cv02/output_graph.pbmm
TensorFlow: v1.11.0-9-g97d851f
DeepSpeech: v0.3.0-0-gef6b5bd
Loaded model in 0.304s.
Loading language model from files models/lm.binary models/trie
Loaded language model in 1.35s.
Running inference.
**e e love jesting is wicebanethexapsing and weareiosdd** 
Inference took 3.154s for 10.000s audio file.
```

sir, My model trained on, **EC2 P3 Instance 512GB RAM, 8 GPUs 16GB**.

sir what is the problem? i don't know have idea, how to resolve this?

trained on: checkout DeepSpeech v0.3.0 and pretrained model, lm, trie.

how to resolve this issue sir.
thanks sir.

**Comment by lissyx** [comment]
@MuruganR96 Your command lines are different:
```
deepspeech --model output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 1.wav
deepspeech --model model_export_cv02/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 1.wav
```

Are you sure you are running the same models ?

**Comment by MuruganR96** [comment]
@lissyx  sir,  both same model. but different system(one is GPU, one is CPU), different dir sir.

**Comment by lissyx** [comment]
> @lissyx sir, both same model. but different system(one is GPU, another one is CPU), different dir sir.
> thanks for your quick reply sir.

Still, I insist, your pasted console output refers to different models. The one testing on GPU seems to be some Common Voice ; it might be one you trained. This output would be consistent of a model improperly trained.

**Comment by MuruganR96** [comment]
> > @lissyx sir, both same model. but different system(one is GPU, another one is CPU), different dir sir.
> > thanks for your quick reply sir.
> 
> Still, I insist, your pasted console output refers to different models. The one testing on GPU seems to be some Common Voice ; it might be one you trained. This output would be consistent of a model improperly trained.

@lissyx sir,
but both as same model. one is copied from another one. both as same, common voice indian accents(augmented) audios trained model. how is this happened? three times i tried to copy right one and tested inference in the GPU. still it shows same wrong output.

Thank you so much for your reply sir

**Comment by kdavis-mozilla** [comment]
What is the output of
```bash
diff output_graph.pbmm model_export_cv02/output_graph.pbmm
```

**Comment by MuruganR96** [comment]
> What is the output of
> 
> ```shell
> diff output_graph.pbmm model_export_cv02/output_graph.pbmm
> ```
**this on GPU result sir**
![errrr_cpuvsgpu_inferenceresults_veried](https://user-images.githubusercontent.com/35978784/50142751-dd412d00-02d0-11e9-8d3a-024d552f4783.png)

**this one cpu result sir**
![inference_correct_cpu_instance](https://user-images.githubusercontent.com/35978784/50142753-df0af080-02d0-11e9-9f57-5fe0feef4ea3.png)

**Comment by MuruganR96** [comment]
sorry sir,if you will see this scrrenshot and reply to me.after then i will remove.

**Comment by kdavis-mozilla** [comment]
What is the output of
```bash
diff output_graph.pbmm model_export_cv02/output_graph.pbmm
```

**Comment by MuruganR96** [comment]
sorry sir, i am very nerves, can't understand.  this is difference sir.
```
CPU Result: a what is the benefit for credit card
GPU Result: e e love jesting is wicebanethexapsing and weareiosdd

Expected output:(transcript) :what is the benefit for credit car
```d

**Comment by kdavis-mozilla** [comment]
Could you please type the following command into you terminal then hit return
```bash
diff output_graph.pbmm model_export_cv02/output_graph.pbmm
```
and add the text of the output to this issue

**Comment by MuruganR96** [comment]
```
(deepspeech-venv003) dell@dell-OptiPlex-7050:~/Murugan_R/DeepSpeech$ diff output_graph.pbmm model_export_cv02/output_graph.pbmm
**Binary files output_graph.pbmm and model_export_cv02/output_graph.pbmm differ**
```
```

(deepspeech-venv003) dell@dell-OptiPlex-7050:~/Murugan_R/DeepSpeech$ diff output_graph.pbmm DeepSpeech_Model/output_graph.pb
**Binary files output_graph.pbmm and DeepSpeech_Model/output_graph.pb differ**

```
sir what it means. i don't know. both are diffient binaries? 
explain me what mistakes i made?

thank you sir.

**Comment by MuruganR96** [comment]
how can i resolve this?

**Comment by lissyx** [comment]
>  both as same, common voice indian accents(augmented) audios trained model.

So not the same

**Comment by lissyx** [comment]
> i don't know. both are diffient binaries?
> explain me what mistakes i made?

Explain us what you did, because so far, it's not good.

**Comment by lissyx** [comment]
> how do i resolve this?

Can you start by running **exactly** the same model and share the complete output? So far, all you did confirms you are running two different models and getting different results, which is 100% consistent.

**Comment by MuruganR96** [comment]
Mm k sir. again i will do same stuff. and report to you sir. 
thank you so much @lissyx  sir @kdavis-mozilla  sir.

**Comment by MuruganR96** [comment]
I am really sorry @lissyx  sir @kdavis-mozilla sir  and @bill-kalog sir. this is my very careless one. same audio name but different audio content. very sorry i was disrupt to lots.

@bill-kalog thanks. thank you so much sir @lissyx @kdavis-mozilla
