### ISSUE TITLE
Without LM

### ISSUE THREAD

**Issue by mehadi-trackrep** [mozilla/DeepSpeech#1803]
Please, anyone, tell me that is it possible to use this project without a language model training for another language speech recognition?

**Comment by lissyx** [comment]
Why @mehadi-trackrep is it an issue ?

**Comment by mehadi-trackrep** [comment]
Actually, I want to use this repository for my personal project for Bangla
language. But, I have no language model for Bangla. That's why it's
important to know that is this project works without the language model.
Such as some commands like ".. --lm models/lm.binary .."

**Comment by lissyx** [comment]
What's the problem with building one language model ? Also, could we have that discussion on Discourse https://discourse.mozilla.org/c/deep-speech ? GitHub issues are for bugs / features.

**Comment by mehadi-trackrep** [comment]
Oh! ok, I have got what is the issues. Thanks!!
