### ISSUE TITLE
Errors when build it  from source

### ISSUE THREAD

**Issue by TTTJJJWWW** [mozilla/DeepSpeech#1805]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:installed from source
- **TensorFlow version (use command below)**:1.8.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:0.16.1
- **GCC/Compiler version (if compiling from source)**:4.9.4
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:1070ti,8G
- **Exact command to reproduce**:

 **when i install deepspeech from source, i get some errors. i use source code v0.1.1 downloaded form the release page of deepspeech.**
$ bazel build --config=cuda --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: /home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD:18:1: Traceback (most recent call last):
	File "/home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD", line 18
		tf_library(name = "deepspeech_model", cpp_cla...", <5 more arguments>)
	File "/home/tjw/audio_adversarial_examples-master/tensorflow/tensorflow/compiler/aot/tfcompile.bzl", line 139, in tf_library
		" ".join([(("'" + arg.replace("'", "'\\''... [])])
	File "/home/tjw/audio_adversarial_examples-master/tensorflow/tensorflow/compiler/aot/tfcompile.bzl", line 139, in " ".join
		[(("'" + arg.replace("'", "'\\''")) + "'") for arg in (tfcompile_flags or [])]
type 'select' is not iterable
ERROR: error loading package 'native_client': Package 'native_client' contains errors
INFO: Elapsed time: 0.050s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
**********************************************************************************************************************************

**and then i try "python util/taskcluster.py --arch gpu --target ./native_client" to download some files maybe can fix this problem, but i do not work.**
$ bazel build --config=cuda --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie

WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: /home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD:18:1: Traceback (most recent call last):
	File "/home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD", line 18
		tf_library(name = "deepspeech_model", cpp_cla...", <5 more arguments>)
	File "/home/tjw/audio_adversarial_examples-master/tensorflow/tensorflow/compiler/aot/tfcompile.bzl", line 139, in tf_library
		" ".join([(("'" + arg.replace("'", "'\\''... [])])
	File "/home/tjw/audio_adversarial_examples-master/tensorflow/tensorflow/compiler/aot/tfcompile.bzl", line 139, in " ".join
		[(("'" + arg.replace("'", "'\\''")) + "'") for arg in (tfcompile_flags or [])]
type 'select' is not iterable
ERROR: Skipping '//native_client:libdeepspeech.so': no such target '//native_client:libdeepspeech.so': target 'libdeepspeech.so' not declared in package 'native_client'; however, a source file of this name exists.  (Perhaps add 'exports_files(["libdeepspeech.so"])' to native_client/BUILD?) defined by /home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD
ERROR: no such target '//native_client:libdeepspeech.so': target 'libdeepspeech.so' not declared in package 'native_client'; however, a source file of this name exists.  (Perhaps add 'exports_files(["libdeepspeech.so"])' to native_client/BUILD?) defined by /home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD
INFO: Elapsed time: 0.041s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

how to fix that and install deepspeech form source with version 0.1.1??

**Comment by lissyx** [comment]
> **TensorFlow version (use command below)**:1.8.0

Have you read the docs ? You need to use Mozilla's fork of TensorFlow. For v0.1.1 you need to checkout the `master-ds-v0.1.1` branch / tag.

Also, please checkout `v0.1.1` tag on DeepSpeech side.

**Comment by TTTJJJWWW** [comment]
Thanks , i got your replies just now and i will try it again.

**Comment by lissyx** [comment]
> **Bazel version (if compiling from source)**:0.16.1

That is also going to be an issue, please stick to upstream documented versions of tooling.

**Comment by TTTJJJWWW** [comment]
Now i use bazel 0.5.4(upstream documented version), Mozilla's fork of TensorFlow with branch master-ds-v0.1.1 and Deepspeech with tag v0.1.1.

bazel build --config=cuda --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
ERROR: no such target '//native_client:libdeepspeech.so': target 'libdeepspeech.so' not declared in package 'native_client' defined by /home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD.

Did i use the wrong source code of Deepspeech? i download it from "https://github.com/mozilla/DeepSpeech/tree/v0.1.1"

**Comment by lissyx** [comment]
> Now i use bazel 0.5.4(upstream documented version), Mozilla's fork of TensorFlow with branch master-ds-v0.1.1 and Deepspeech with tag v0.1.1.
> 
> bazel build --config=cuda --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
> ERROR: no such target '//native_client:libdeepspeech.so': target 'libdeepspeech.so' not declared in package 'native_client' defined by /home/tjw/audio_adversarial_examples-master/tensorflow/native_client/BUILD.
> 
> Did i use the wrong source code of Deepspeech? i download it from "https://github.com/mozilla/DeepSpeech/tree/v0.1.1"

No, you are just once again not reading the documentation: https://github.com/mozilla/DeepSpeech/tree/v0.1.1/native_client#building

**Comment by reuben** [comment]
Looks like this was solved, feel free to reopen otherwise.
