### ISSUE TITLE
The released model is only 16% WER

### ISSUE THREAD

**Issue by UsedToBe97** [mozilla/DeepSpeech#1809]
Hi, DeepSpeech developers and community friends:)
I've heard that the developer claims the WER has achieved 6.0%, but the model on released page is still 16% WER, I wonder if it's just a joke ?
If not, would you be kind enough to provide us with one 6%WER model?

**Comment by lissyx** [comment]
@UsedToBe97 Please avoid spamming. This was already answered: https://github.com/mozilla/DeepSpeech/issues/1808#issuecomment-449952848

**Comment by UsedToBe97** [comment]
But the checkpoint of v0.3.0 is actually v0.2.0...
I couldn't figureo out why, is it just a mistake by uncarefullness? @lissyx

**Comment by lissyx** [comment]
> But the checkpoint of v0.3.0 is actually v0.2.0...
> I couldn't figure out why, is it just a mistake by uncarefullness? @lissyx

Do you really need to spam again and again ? There was no change to the network itself, so 0.3.0 model is exactly the same as 0.2.0 ...
