### ISSUE TITLE
Issue with Language Model

### ISSUE THREAD

**Issue by sgangs** [mozilla/DeepSpeech#1814]
I am using existing deepspeech model currently. As I try using this command (without a LM):

deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --audio output.wav

I get the output as: 
not impresecriptson crusing twice taily for three days

Using deepspeech LM:
 deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio output.wav 

I get:

not in presecriptsoncrusingtwicetailyforthreedays

Using a model I generated from wikipedia dump, using KenLM, and the binary being created in the Trie Structure and not Probing Structure <a>https://kheafield.com/code/kenlm/structures/</a> , as Trie takes smaller memory and the .arpa file was some 68GB sized. However, using my wikipedia model and Deepspeech audio model:

deepspeech --model models/output_graph.pbmm --alphabet wiki_model/alphabet.txt --lm wiki_model/lm.binary --trie wiki_model/trie --audio output.wav 

I get something gibberish:

/#'zyxwvutsrqponm/#'zyxwvutsrqponm/#'zyxwvutsrqponm/#'zyxwvutsrqponm/#'zyxwvutsrqboam/#'rqxwvtsr'zonm'zyxwjujseqgonm/#'z nwcutgripoem/#'zyxjvufsrqponm/#'zyxwvutsrqponm/#'zxwaujirjpond/#'qyxwvuasryxonm/#'zyxwulsmqponj/#bcyxvulsrspo'ml'zvxwvutsrwvnmo'pyxwul/#rgmotm/#'y wvwtsrngfem/#'zyxwvutsrqponm/#'zyxwvu

I don't know why that's so

The real output is:
"Note in prescription crocin twice daily for three days"

Kindly help why my own wiki model is doing what it is doing.

**Comment by kdavis-mozilla** [comment]
As this does not appear to be a bug with the repo's code, could you take the discussion to our [Discourse Forum](https://discourse.mozilla.org/c/deep-speech) please. Thank you.

**Comment by sgangs** [comment]
I am really sorry. I shall do that immediately.

**Comment by kdavis-mozilla** [comment]
No problem. Thanks!
