### ISSUE TITLE
Unable to run Deepspeech

### ISSUE THREAD

**Issue by AASHISHAG1** [mozilla/DeepSpeech#1818]
root@speech:~/DeepSpeech# deepspeech -h
Illegal instruction (core dumped)

I have installed deepspeech using pip3 install deepspeech but I am getting above error. Please advice

Here are my system details:

root@speech:~/DeepSpeech#  cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by kdavis-mozilla** [comment]
Are you using a python virtual environment[[1](https://github.com/mozilla/DeepSpeech#using-the-python-package)]?

**Comment by lissyx** [comment]
> root@speech:~/DeepSpeech# deepspeech -h
> Illegal instruction (core dumped)

First, it's a bad habit to run that kind of userland process as root. There's 0 reason deepspeech needs to run as root.

Second, that's likely missing AVX, or other kind of CPU extensions. Please check `/proc/cpuinfo`.

**Comment by AASHISHAG1** [comment]
Yes, next time I will it only in virtual environment.

@lissyx: As you pointed out, I don't have AVX. Attached is the the output for /proc/cpuinfo. 

Can you please point out, what else configuration is required to run the model?

[Output.txt](https://github.com/mozilla/DeepSpeech/files/2728769/Output.txt)

**Comment by lissyx** [comment]
> Can you please point out, what else configuration is required to run the model?

it's documented at multiple places, including releases pages.
