### ISSUE TITLE
Running unmodified code with nvidia docker using provided Dockerfile through run-cluster.sh throws AttributeError: 'TrainingCoordinator' object has no attribute '_epoch' by worker 1

### ISSUE THREAD

**Issue by PiotrowskiD** [mozilla/DeepSpeech#1819]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Original code run on nvidia docker using provided Dockerfile
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: DeepSpeech build installed by Dockerfile
- **TensorFlow version (use command below)**: 1.12 gpu
- **Python version**: python installed by provided Dockerfile (2.7)
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: Version installed by provided Dockerfile
- **CUDA/cuDNN version**: CUDA 9.0.176 cuDNN 7
- **GPU model and memory**: tested on two configurations - two K80s and Titan X + GeForce 780 Ti
- **Exact command to reproduce**: nvidia-docker run -it piotrowskidariusz/deepspeech:original ./bin/run-cluster.sh 1:2:1 --train_files=ldc93s1/ldc93s1.csv --dev_files=ldc93s1/ldc93s1.csv --test_files=ldc93s1/ldc93s1.csv --log_level=0 --train_batch_size=2 --notest

(image above is built by using original Dockerfile with addition of importing ldc dataset)

After running above command worker 0 is doing some traning but when worker 1 starts doing its first batch I get the following error:

[worker 1] D Starting queue runners...
[worker 1] D Queue runners started.
D Sending Job (ID: 40, worker: 0, epoch: 19, set_name: train)...
[worker 0] I Training of Epoch 19 - loss: 273.254395
[worker 0] D Computing Job (ID: 42, worker: 0, epoch: 20, set_name: train)...
[worker 0] D Starting batch...
[worker 0] B 8  3.12
D Finished batch step 9.
100% (1 of 1) |########################################################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
[worker 0] I Training epoch 20...
[worker 1] D Computing Job (ID: 46, worker: 1, epoch: 22, set_name: train)...
[worker 1] D Starting batch...
D Sending Job (ID: 42, worker: 0, epoch: 20, set_name: train)...
[worker 0] I Training of Epoch 20 - loss: 271.174805
[worker 0] D Computing Job (ID: 44, worker: 0, epoch: 21, set_name: train)...
[worker 0] D Starting batch...
[worker 0] B 9  3.24
D Finished batch step 10.
100% (1 of 1) |########################################################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
[worker 0] I Training epoch 22...
                                                          [worker 1] D Finished batch step 10.#########################################################################################################| Elapsed Time: 0:00:00 ETA:  00:00:00
[worker 1] E 'TrainingCoordinator' object has no attribute '_epoch'
[worker 1] Traceback (most recent call last):
[worker 1]   File "DeepSpeech.py", line 621, in train
[worker 1]     update_progressbar(job.set_name)
[worker 1]   File "DeepSpeech.py", line 519, in update_progressbar
[worker 1]     current_epoch = coord._epoch-1
[worker 1] AttributeError: 'TrainingCoordinator' object has no attribute '_epoch'
[worker 1] D Closing queues...
D Sending Job (ID: 44, worker: 0, epoch: 21, set_name: train)...
[worker 0] I Training of Epoch 21 - loss: 226.357147
[worker 0] D Computing Job (ID: 48, worker: 0, epoch: 23, set_name: train)...
[worker 0] D Starting batch...
[worker 0] B 9  2.89
D Finished batch step 10.
100% (1 of 1) |########################################################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
[worker 0] I Training epoch 23...
[worker 1] D Queues closed.
[worker 1] D Sending stop token to ps 0...
[ps     0] D Got a stop token from worker 1.
[ps     0] D Waiting for stop token...
[worker 1] D Sent stop token to ps 0.

**Comment by tilmankamp** [comment]
Ah - seems like the progress-bar was not tested for multi-process training.
@PiotrowskiD Please try running with `--noshow_progressbar`.

**Comment by PiotrowskiD** [comment]
It did the job, thanks!
