### ISSUE TITLE
Readme unclear about git-lfs and download size

### ISSUE THREAD

**Issue by kristiank** [mozilla/DeepSpeech#1822]
Reading the readme about git-lfs and the mentioning of 70gb made me hesitate to clone the repository, it left me unsure whether the clone will download 70gb or more. The GitHub interface doesn't state file sizes either ...

**Comment by lissyx** [comment]
What 70GB are you referring to?

**Comment by lissyx** [comment]
@kristiank Do you mind explaining what's unclear? We clearly states it is for Common Voice dataset. Not for the git clone.

**Comment by JRMeyer** [comment]
@lissyx - some confusion is caused by the README's assumption that training DeepSpeech means "training DeepSpeech on Common Voice". I think a great addition would be a section on "How to Train DeepSpeech for your own data". However, that will take a lot of time to write up, and I can't volunteer to do it in the near future:/

**Comment by kristiank** [comment]
@JRMeyer this is a great idea! Since it will take me more than a month before I can do a training with Votic language, I can't volunteer either.

@lissyx it was under the heading "Common Voice training data" that the following phrase confused me

> Please be aware that this requires at least 70GB of free disk space and quite some time to conclude.

Now re-reading the whole thing it all makes sense to me. The only solution I can come up with making it more clear would be to state the size of the download in the previous sentence:

> If you already downloaded the Common Voice corpus archive from here, you can simply run the import script on the directory where the corpus is located.

I checked the download is 12 GB now.

My logic for this is that it makes it very clear that it is the downloaded stuff that will get expanded to 70 GB and not something that is necessary for training with another data set.

**Comment by kristiank** [comment]
Another solution would be to simply rewrite the sentence
> Please be aware that this requires at least 70GB of free disk space and quite some time to conclude.
like this
> Please be aware that training with the Common Voice corpus archive requires at least 70GB of free disk space and quite some time to conclude.

I can make a pull request for this if wanted.

**Comment by kristiank** [comment]
@lissyx The readme now states that `git-lfs` is needed, but none of the git commands never use it. This is also confusing. Is `git-lfs` only a requirement when working with the Common Voice dataset?

**Comment by lissyx** [comment]
git-lfs is needed for the language model, not common voice. There's no specific command needed, install it and git should be able to pick it. For the wording, a PR clarifying is always welcome, current sentence seems okay to us, but it can always be better :-)

**Comment by lissyx** [comment]
> I can make a pull request for this if wanted.

@kristiank I guess that would be the perfect way to have a better wording

**Comment by kristiank** [comment]
Pull requested now at #1853
