### ISSUE TITLE
virtualenv broken if conda is installed

### ISSUE THREAD

**Issue by kristiank** [mozilla/DeepSpeech#1823]
Running the commands for setting up `virtualenv` environment doesn't work when `conda` is installed. I circumvented this by just using `conda` to install `deepspeech`.

**Comment by lissyx** [comment]
Care to be more descriptive? There's not even STR or error messages documenting what's broken. Isnt conda already setting up virtualenv anyway?

**Comment by kdavis-mozilla** [comment]
@kristiank Neither `virtualenv` nor `conda` are part of this project. So if they don't interact well, we can't help. We suggest using _only_ `virtualenv`.
