### ISSUE TITLE
Significant drop in accuracy

### ISSUE THREAD

**Issue by chrisspen** [mozilla/DeepSpeech#1824]
I'm not sure what happened to the 0.4.0 model, but I've noticed a significant drop in accuracy over past models. I constructed a small corpus of 142 sample sound files (a random collection of pop culture audio clips and Voxforge recordings in 16k mono wav format), and I've been using it to measure the accuracy of DeepSpeech's transcription every few months for the last year to see how the project's been progressing as well as compare it to other speech-to-text systems.

Last July, absolute accuracy was 25%. Last October, it was down to 2%. The 0.4.0 model now gets 0%, and it gives nonsensical predictions like "vkblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalblalbqb" for nearly every one of my sample audio files, even ones it used to get correct.

For comparison, Google Speech gets around 39% accuracy, and PocketSphinx gets around 16% accuracy.

Do you know why accuracy has dropped so quickly over the last year? I haven't made any significant changes to my script (other than to point to the most recent model) nor data files. Understandably, you don't train your model using any of my audio files, so I wouldn't expect accuracy to be great, but I also wouldn't expect such a sharp drop off either. You can find my scripts [here](https://github.com/chrisspen/speech-to-text-test).

**Comment by kdavis-mozilla** [comment]
From our benchmarking it actually improved. So I'd guess there's some problem in your setup.

Could you describe in detail how you set up your system?

**Comment by reuben** [comment]
Looks like you're using the old decoder hyperparameter values in your code, which could at least partially explain a drop in accuracy. Try using the new values (alpha=0.75, beta=1.85). I've updated the release notes to list those hyperparameters as well.

**Comment by reuben** [comment]
Embedding hyperparameters into the model is issue #1770. It shouldn’t make the model completely unusable, I don’t think that’s all of the problem here, but it’s hard to diagnose without testing with the same audio files. I’ll take a look after I come back from vacation next week.

**Comment by kdavis-mozilla** [comment]
@chrisspen One more thing we just found with the release model is that it's not the final model we wanted to use, we're currently creating a 0.4.1 release with the update which hopefully should be done today.

**Comment by chrisspen** [comment]
I just plugged in the new alpha and beta parameters to my script, but I got same low accuracy scores.

**Comment by chrisspen** [comment]
I noticed the wave file loading code had changed slightly in the reference client.py script. I updated my code to use the same method, and that seems to have fixed the problem. It seems the `scipy.io.wavfile` and `wave` modules aren't compatible.

**Comment by lissyx** [comment]
> that seems to have fixed the problem.

I'll close the issue then, thanks!
