### ISSUE TITLE
v0.4.1 is missing rpi3 tarball

### ISSUE THREAD

**Issue by 9define** [mozilla/DeepSpeech#1830]
The release for version 0.4.0 contained a RPi3 specific tarball. The release for version 0.4.1 does not, despite claiming compatibility with that platform. Was this tarball accidentally omitted? Can this be fixed?

Thanks

**Comment by lissyx** [comment]
Something failed during the upload, we'll have to re-upload it

**Comment by lissyx** [comment]
Though the 0.4.1 is really just changing the model so the rpi3 tarball from 0.4.0 should work well

**Comment by 9define** [comment]
@lissyx I have scripts that pull specific versions for CI, so having one version to pull for all required platforms is best. If 0.4.1 could be uploaded for RPi3 that would be optimal. Thanks.

**Comment by lissyx** [comment]
I said earlier we will take care of re-uploading

**Comment by lissyx** [comment]
Right, so we had some issues when the 0.4.1 release happened, somehow it looks like the rpi3 package was half-uploaded and in an error state, once I removed that manually from the release, re-upload could proceed.
