### ISSUE TITLE
CTC decode very slow  when training Mandarin Model

### ISSUE THREAD

**Issue by jaycicle** [mozilla/DeepSpeech#1831]
Hey guys,
I'm following this tutorial to train a Chinese Model DeepSpeech on my own data : https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830

I got the alphabet which contains 4333 Chinese characters, vocab,  3gram language model with lm.binary and trie. 

Training Acoustic model is is normal, but the **ctc-decode step is very very slowly(three batch(batch size is 12) of test data take two days to decode)!!!**

this is the training log:
![deepspeech](https://user-images.githubusercontent.com/12438015/51100169-c2020880-180f-11e9-926c-729dc9fa2bf6.PNG)

My training environment is: 
Linux Ubuntu 16.04 with 4 Gpus(p100)
DeepSpeech-gpu-0.4.0
Tensorflow-1.12.0

**Comment by jaycicle** [comment]
@kdavis-mozilla  Do you do any other optimization suggestion？ It’s really a problem for me....  
I have set the beam_width to 128, but shows no positive effect

**Comment by kdavis-mozilla** [comment]
You could try implementing the work int he cited paper.
