### ISSUE TITLE
IPA support aka Speech to Phonetics

### ISSUE THREAD

**Issue by Kreijstal** [mozilla/DeepSpeech#1838]
Is there a speech to IPA trained model?

I see that these engines try so hard to match phonetics to words in one specific word, so when you want to switch languages or for custom sounding names they just don't really understand what you want.

So what I want is something that recognizes phonetics but doesn't try to map it to any meaningful language, so that it can capture accents, different languages, and things that have no meaningful letter.

Is this harder? or easier considering that we don't worry about trying to map it into words. 

Similar to #755

**Comment by kdavis-mozilla** [comment]
Phonemes differ slightly between languages.

**Comment by Kreijstal** [comment]
If that's true it probably makes more sense to assign different labels for different sounds, this seems harder than I considered though.

**Comment by boxabirds** [comment]
IPA is about a [language-independent representation -- the phones](http://www.internationalphoneticalphabet.org/ipa/). This is to be contrasted against phonemes are language-dependent semantic interpretations. E.g. the "p" in spot vs pot are functionally the same in English but two separate phones from the 9 different kinds of "[voiceless bilabial stops](https://en.wikipedia.org/wiki/Voiceless_bilabial_stop)" or "p"s that are pronounced in human languages around the world. 

I'm by no means an expert in this territory and appreciate that given other threads, IPA support may not be core to DeepSpeech and therefore may require a fork.

**Comment by kdavis-mozilla** [comment]
If you have audio transcribed to IPA, you can train your own model with the current code now. There is nothing saying the alphabet used has to be "normal" letters.

**Comment by boxabirds** [comment]
Makes sense, of course thanks! 

I wonder if there's merit in doing some fine-tuning against the current trained English model, part of the experimentation being progressively resetting / retraining more of the higher layers until you get the right level of automatic feature detection that overlaps between English characters and IPA phonetics (of which there appear to be [173 unique ones including various modifiers](https://www.quora.com/How-many-phonetic-symbols-are-there)). 

This would in theory get IPA generation for English phones, but would not be trained on IPA phones that don't occur in English I guess.

My rationale is that while it's a many-to-many mapping between sequences of English characters and IPA symbols, it is a closed set that should map to the spectrogram cleanly, but I don't know. Someone shout if this seems conceptually misplaced.

**Comment by kdavis-mozilla** [comment]
We've done some tests of fine-tuning from one language to another, but no fine-tuning from one language to it's IPA version. So, I'm not sure I have a good intuition as to how the fine-tuning should proceed.

**Comment by reuben** [comment]
You could start by running a phonemizer on an existing dataset and training with that. See for example espeak-ng.

**Comment by reuben** [comment]
I'm not sure there's value in keeping this issue open. There's nothing actionable, as Kelly said, we support it already, all you need is the labelled data. If people are interested in experimenting and discussing this approach, please open a thread on [Discourse](https://discourse.mozilla.org/c/deep-speech)
