### ISSUE TITLE
running

### ISSUE THREAD

**Issue by Giles754128704** [mozilla/DeepSpeech#1849]
The files in the example are too difficult . How to run a simple demo?

**Comment by lissyx** [comment]
> The files in the example are too difficult . How to run a simple demo?

Please explain why it's difficult, since we think it is not.

**Comment by kdavis-mozilla** [comment]
Did you see the READEME with the command line example?

```bash
deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio_file.wav
```

**Comment by imKKK** [comment]
1. just download the pretrained models from [here](https://github.com/mozilla/DeepSpeech/releases/download/v0.4.1/deepspeech-0.4.1-models.tar.gz)
2. extract the tar file in a folder
3. create a virtual environment

**Comment by reuben** [comment]
Closing as this was answered.
