### ISSUE TITLE
Refactor DataSet and DatSets out of importers

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#185]

**Comment by kdavis-mozilla** [comment]
There are actually slight differences between the various `DataSet` instances.

**Comment by tilmankamp** [comment]
There is some overlap with [issue 289](https://github.com/mozilla/DeepSpeech/issues/289).

**Comment by tilmankamp** [comment]
@kdavis-mozilla The DataSets implementation is now shared among importers. Maybe we close this and let the DataSet implementation be subject of @reuben's planned importers refactoring/flattening.

**Comment by reuben** [comment]
Yes, this issue is fixed by my refactoring.
