### ISSUE TITLE
Segmentation fault in the inference

### ISSUE THREAD

**Issue by pKrysenko** [mozilla/DeepSpeech#1858]
Good day, several weeks ago, i started train deepspeech on russian dataset. I created LM without any problem. Also in the moment of trainind i didnt face any problem. But when i try inference this model, i got "Segmentation fault(Core dumped)". I think it's problem of LM, because i tested english LM with my russian model and i didn't get this error. I use deepspeech 0.4.0

**Comment by kdavis-mozilla** [comment]
What command line arguments did you use to create your Russian language model?

**Comment by pKrysenko** [comment]
kenlm/build/bin/lmplz -o 5 <russian_corpus.txt >lm.arpa
kenlm/build/bin/build_binary lm.arpa lm.binary
DeepSpeech/native_client/generate_trie alphabet_ru.txt lm.binary russian_corpus.txt trie

**Comment by kdavis-mozilla** [comment]
Could you try mimicking the [README instructions](https://github.com/mozilla/DeepSpeech/tree/master/data/lm) with Russian.

**Comment by pKrysenko** [comment]
I fixed it. I used generate_trie from deepspeech alpha 0.5.0 and all ok
