### ISSUE TITLE
processing data on the fly

### ISSUE THREAD

**Issue by mikeyshulman** [mozilla/DeepSpeech#1859]
I'm wondering if there's any interest in having the data be loaded and processed on the fly, instead of all of the features being held in memory. 

This is will allow much larger training sets to be processed. 

I have tried this out both on CPU and GPU configurations, and it does not noticeably slow down training if you have an SSD.

If there is interest I can make a PR.

**Comment by bernardohenz** [comment]
The data used to be loaded and processed on the fly, so I suspect that this new preprocessing step must had improved the performance.

But I agree with you, not only this would allow larger training sets, this would support the use of online (on-the-fly) data augs (like speed/pitch variation on the audio).

**Comment by kdavis-mozilla** [comment]
What we're planning on doing is creating a training data set on disk with noise and the like via [voice-corpus-tool](https://github.com/mozilla/voice-corpus-tool), then allowing the current preprocessing step to run.

This doesn't however, solve the problem of a data set being too large to fit in memory. We haven't, fingers crossed, run in to that problem yet. However, I assume that day of reckoning will come. 

Out of curiosity, how many hours of audio are you working with and how much RAM do you have?

**Comment by bernardohenz** [comment]
@kdavis-mozilla I am currently training using more than 900h on a 16gb RAM. I would like to ask if you have performed a benchmark for checking the speed-up gained with this preprocessing step?

**Comment by kdavis-mozilla** [comment]
@bernardohenz We've a roughly a speed up of a factor of 4.

Previously we used two nodes of our cluster to train a model and it took about 8 days to train. Now we can do the same on one node in 4 days.

**Comment by mikeyshulman** [comment]
I'll have to look at it again, but it might be possible. 
The problem with smaller HDF5 caches is that you can't data augment on the fly because you no longer have the access to the waveforms

**Comment by reuben** [comment]
Right, but you can augment to disk and keep the files within a size that fits in memory.

**Comment by reuben** [comment]
This is now easily supported by removing the `.cache()` call in `feeding.py`.
