### ISSUE TITLE
Remove remaining readthedocs link

### ISSUE THREAD

**Issue by gene1wood** [mozilla/DeepSpeech#1864]
@kdavis-mozilla I think you missed [one more reference](https://github.com/mozilla/DeepSpeech/blame/4356704a768ddf1f014e40fb431fa13697c005c6/README.md#L386-L389) to readthedocs in #1863 (which addresses #1861). Would you pull this one too?

**Comment by kdavis-mozilla** [comment]
@gene1wood Good eye!
