### ISSUE TITLE
Subpar performance with non-native English speakers

### ISSUE THREAD

**Issue by nbraud** [mozilla/DeepSpeech#1866]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 10 `buster`
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip
- **TensorFlow version (use command below)**: v1.12.0-10-ge232881
- **Python version**: 3.7.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `./transrip.py -t -30 data/*.wav`

I am in the process of writing an open tool for automatically transcribing interviews, based on DeepSpeech.

During development, I am testing on an interview between a quasi-bilingual, European speaker, and an Indian one; I noticed that DeepSpeech has noticeably poorer performance for the Indian speaker.

Could it be that the corpus used for training the ML models is insufficiently diverse?
While I will be publishing the tool shortly, the interview itself is confidential and not suitable for sharing with 3rd parties  :(

**Comment by nbraud** [comment]
PS: The audio source is 44.1kHz WAV, 16b, resampled to 16kHz for DeepSpeech.
    The recording pipeline and resampling is the same on both tracks (one track per speaker)

**Comment by kdavis-mozilla** [comment]
As this is neither a bug nor feature request and necessitates a discussion could you please move this to our [discourse form](https://discourse.mozilla.org/c/deep-speech).

**Comment by nbraud** [comment]
@kdavis-mozilla I would consider not working with non-native speakers to be a bug, but whatever.

**Comment by kdavis-mozilla** [comment]
@nbraud It's standard that different models are required for different accents.

For example Google's speech-to-text service[[1](https://cloud.google.com/speech-to-text/)] has different models for Australian English, Canadian English, Ghanaian English....

**Comment by nbraud** [comment]
I see; in any case, I will move the discussion to the Discourse, I've just been occupied by other things
