### ISSUE TITLE
Test - WER  vs CER vs loss

### ISSUE THREAD

**Issue by waqasr6** [mozilla/DeepSpeech#1867]
I've trained my own model and need to know what my results describes in term of % WER, CER and loss. do i need to train with more epochs ?

Preprocessing done
Computing acoustic model predictions...
 96% (171 of 177) |#################################################################################################    | Elapsed Time: 0:00:13 ETA:   0:00:00^
100% (177 of 177) |#####################################################################################################| Elapsed Time: 0:00:14 Time:  0:00:14
Decoding predictions...
 81% (145 of 177) |##################################################################################                   | Elapsed Time: 0:03:59 ETA:   0:00:46^
100% (177 of 177) |#####################################################################################################| Elapsed Time: 0:04:54 Time:  0:04:54
**Test - WER: 0.213015, CER: 3.542373, loss: 25.164192**

**Comment by kdavis-mozilla** [comment]
As we try to reserve issues for bugs and/or feature requests, would you mind moving this query to our [discourse form](https://discourse.mozilla.org/c/deep-speech). Thanks you.
