### ISSUE TITLE
May i use deepspeech ldc93si train chinese?

### ISSUE THREAD

**Issue by jkkj1630** [mozilla/DeepSpeech#1868]
May i use deepspeech ldc93si train chinese? Thanks.

**Comment by kdavis-mozilla** [comment]
As this is not a bug and/or request for enhancement could you please move this request to our [discourse channel](https://discourse.mozilla.org/c/deep-speech)? Also, could you supply a link to the LDC corpus, I can't seem to find LDC93SI. Thanks.

**Comment by jkkj1630** [comment]
ok thank you.
