### ISSUE TITLE
WER calculation on CPU is slow

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#187]
For example after each epoch, when the WER calculation occurs but not when the checkpoint occurs, the power curve of the GPU dips for many min, this is when the WER calculation is done. In the graph below, TED run on the server, it starts at about 300 seconds and last for about 120 seconds.
![test_gpu_pwr](https://cloud.githubusercontent.com/assets/12054740/20238881/246f122e-a8f5-11e6-92b2-2b4dc8a8e656.png)

**Comment by tilmankamp** [comment]
@kdavis-mozilla I'll try to implement WER calculation on GPU.

**Comment by tilmankamp** [comment]
I'd suggest doing accuracy calculation only done for display steps, as it is only required there. This should relief the graph from doing the CPU bound ```ctc_ops.ctc_beam_search_decoder``` for every single step. The only other dependency to it are decodings which are already just calculated during display steps.

After all, this would strengthen the effect of increasing the ```display_step``` variable - reducing overall CPU time.

**Comment by kdavis-mozilla** [comment]
Large parts of this were dealt with in commit e83b49e where the WER calculation is only done occasionally, when a report is requested not every epoch.
