### ISSUE TITLE
Bazel build fails

### ISSUE THREAD

**Issue by baerbock** [mozilla/DeepSpeech#1871]
I've tried to build _master_ with `bazel build --config=monolithic -c opt --copt=-O3`

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:~/.cache/bazel/_bazel_$username/install/fa7ec40bc24d880a0387f2df50c6a7ce/_embedded_binaries/A-server.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: The 'build' command is only supported from within a workspace.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 81ebd25f-87c7-4434-b5f6-eb20acef5d5f
```

Why is this failing?

**Comment by reuben** [comment]
Too recent version of bazel? Too recent version of Java? Broken bazel cache? This doesn't seem to be a problem with our code. Are you able to build e.g. TensorFlow or do you run into the same problem?

**Comment by baerbock** [comment]
@reuben Which versions would be too young?

**Comment by lissyx** [comment]
@baerbock Bazel, as stated before ? You ripped out all the template for reporting bugs, we don't even know if you are starting that from the correct directory.

**Comment by reuben** [comment]
https://www.tensorflow.org/install/source#tested_build_configurations

**Comment by visi0nary** [comment]
@baerbock What's the exact bazel command you issue?

**Comment by lissyx** [comment]
Nothing actionable here.
