### ISSUE TITLE
where can get the correct csv file of cv_corpus

### ISSUE THREAD

**Issue by wingchu** [mozilla/DeepSpeech#1876]
After I run the command 
bin/import_cv.py path/to/target/directory
unexpected result comes out

Found archive "/mnt/c/Storage/cv_corpus_v1.tar.gz" - not downloading.
No directory "/mnt/c/Storage/cv_corpus_v1" - extracting archive...

No CSV file "/mnt/c/Storage/cv-invalid.csv" - importing "/mnt/c/Storage/cv_corpus_v1/cv-invalid.csv"...
Importing mp3 files...
Traceback (most recent call last):
  File "bin/import_cv.py", line 124, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_cv.py", line 39, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "bin/import_cv.py", line 54, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1]))
  File "bin/import_cv.py", line 96, in _maybe_convert_set
    bar = progressbar.ProgressBar(max_value=num_samples, widgets=SIMPLE_BAR)
TypeError: __init__() got an unexpected keyword argument 'max_value'

It seems that the csv file is wrong in format? where can i get the correct file?

**Comment by reuben** [comment]
Doesn't have anything to do with the file format, looks like you installed the wrong version of the progressbar2 package? Try reinstalling it with `pip install -U progressbar2`

**Comment by wingchu** [comment]
That's work, thank you @reuben , I did install the wrong progressbar2 package
