### ISSUE TITLE
Hyper-parameter Optimisation for the Language Model

### ISSUE THREAD

**Issue by mathematiguy** [mozilla/DeepSpeech#1881]
This is a feature request for some kind of hyperparameter optimisation for the language model parameters `lm_alpha` and `lm_beta`.

In [this discourse post](https://discourse.mozilla.org/t/how-to-run-inference-repeatedly-with-different-tf-flags/35946/3) I outlined my proposed approach to doing this, and @reuben gave some tips for how best to implement the feature.

This issue is for me to discuss progress on the feature, which I'm hoping to wrap up in the next few days.

**Comment by kdavis-mozilla** [comment]
Code finished, waiting on review of PR 2783

**Comment by mathematiguy** [comment]
#2783 has been merged, so I can close this one myself.
