### ISSUE TITLE
Insufficient information about how to use the NodeJS bindings

### ISSUE THREAD

**Issue by dsteinman** [mozilla/DeepSpeech#1898]
'npm install deepspeech'

> See client.js for an example of how to use the bindings.

Unfortunately this is not enough information to get started with the Node bindings because I don't know what to do with the client.js file.

Just some really basic step by step instructions would be very much appreciated.

**Comment by reuben** [comment]
You're not supposed to do anything with the file, just read it. It's an example of a script that uses the bindings, it has comments and informative console messages. The script *is* the step-by-step instructions.

**Comment by dsteinman** [comment]
The script imports other dependencies such as:

```
const Ds = require('./index.js');
...
var model = new Ds.Model(args['model'], N_FEATURES, N_CONTEXT, args['alphabet'], BEAM_WIDTH);
```

So if I use client.js as an example I can't just use it because I get errors and I have to have some detailed knowledge about what the dependencies are, and know which I can remove or replace. Even just running that example code as-is isn't clearly documented at:

https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md

Perhaps is there any example of a simplified "single file" script without any extraneous dependencies and gyp building?

**Comment by kdavis-mozilla** [comment]
Another example is here [ffmpeg_vad_streaming](https://github.com/mozilla/DeepSpeech/tree/master/examples/ffmpeg_vad_streaming) which includes a [package.json](https://github.com/mozilla/DeepSpeech/blob/master/examples/ffmpeg_vad_streaming/package.json) with all the info on dependencies.

**Comment by dsteinman** [comment]
> Another example is here [ffmpeg_vad_streaming](https://github.com/mozilla/DeepSpeech/tree/master/examples/ffmpeg_vad_streaming) which includes a [package.json](https://github.com/mozilla/DeepSpeech/blob/master/examples/ffmpeg_vad_streaming/package.json) with all the info on dependencies.

Ah okay, between examining that and the other file I've got a simplified example working.  I'll publish a git repo for you to consider adding to the examples directory.

**Comment by dsteinman** [comment]
Here's my example code:

https://github.com/dsteinman/deepspeech-simple

Just one JS file and one WAV file, and I removed all the "args" stuff which was making everything look more complicated than it actually is.  Thanks for the help, guys.  You can close this ticket.

**Comment by lissyx** [comment]
> Here's my example code:
> 
> https://github.com/dsteinman/deepspeech-simple
> 
> Just one JS file and one WAV file, and I removed all the "args" stuff which was making everything look more complicated than it actually is. Thanks for the help, guys. You can close this ticket.

Do not hesitate if you feel the need to send a PR augmenting docs / examples, it's always welcome !
