### ISSUE TITLE
README for `DeepSpeech/taskcluster`

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/DeepSpeech#1902]
For those of us who aren't so familiar with `taskcluster`, a README would be very helpful in the `DeepSpeech/taskcluster` dir.

**Comment by kdavis-mozilla** [comment]
Why should we document taskcluster here? It's a task execution framework for Mozilla's CI system. It be much better simply to reference the [existing taskcluster documentation](https://docs.taskcluster.net/docs).

**Comment by JRMeyer** [comment]
How about a README that says exactly what you just wrote? I agree we don't need full-length documentation, but for a newcomer to DeepSpeech, they peek into this dir and it's not at all obvious what the contents are for.

I can make a PR with a README.md with the following contents:

```
# taskcluster

A task execution framework for Mozilla's CI system. Please consult the [existing taskcluster documentation](https://docs.taskcluster.net/docs).
```

**Comment by kdavis-mozilla** [comment]
That sounds fine.

**Comment by JRMeyer** [comment]
#1907
