### ISSUE TITLE
Sentence boundary detection

### ISSUE THREAD

**Issue by pvanickova** [mozilla/DeepSpeech#1905]
Now that audio streaming is available, it would be a useful addition to detect end of sentences.

Alternatively, many sentence segmentation techniques work better when information about silence gaps between the words is available. So returning this metadata information about the transcript would help for the sentence boundary detection also.

**Comment by bedapudi6788** [comment]
@pvanickova even without the silence gap, sentence end detection should work well in general. Which ones did you try with?

**Comment by pvanickova** [comment]
I've seen the prosodic featues such as the silence gaps mentioned in a few papers e.g. http://www.cs.tut.fi/~huangg/papers/2014_IS/xu2014deep.pdf or https://arxiv.org/pdf/1610.00211.pdf. 

Do you have a recommendation for another text only based method?

**Comment by bedapudi6788** [comment]
I built https://github.com/bedapudi6788/deepsegment for this purpose (sentence segmentation without punctuation). You can find a demo at http://bpraneeth.com/projects

**Comment by pvanickova** [comment]
thanks, i'll check it out

**Comment by lissyx** [comment]
@pvanickova Sorry if it feels like a dumb question but I'm wondering if it's really something that should fit into the scope of the project ?

**Comment by absin1** [comment]
You can use a puncuator https://github.com/ottokart/punctuator2

**Comment by pvanickova** [comment]
@lissyx  I'd argue that adding sentence boundaries to the transcript is a part of an ASR system as many following NLP tasks depend on the speech segmentation to sentences. Also some of the acoustic properties, such as silence gaps between individual words, could be helpful in producing accurate punctuation. (btw. commercial solutions such as google speech API or IBM's speech to text provide this functionality as well). 

If the text-only based solutions recommended above prove to be accurate enough, having an external component that would add the punctuation to the Deepspeech generated stream of words would be less cumbersome. 

Still I'd be an enthusiastic user of the feature if it was provided by Deepspeech out of the box:).

**Comment by kdavis-mozilla** [comment]
@pvanickova Deep Speech is purely speech-to-text, any auxiliary functionality will limit it's applicability.

In particular, adding a sentence boundary detector will require an additional model, and thus additional memory and compute, and thus limit the small platform devices it can be deployed on.

Adding a sentence boundary detector will require obtaining data to train the sentence boundary detector on. For example, if we wished to target simplified Chinese Mandarin, we would have to obtain a data set tagged with sentence boundaries which adds another dependency to the data sets required and a further delay to others not interested in detecting sentence boundaries.

Furthermore, there are many Deep Speech applications, e.g. command and control, that do not require sentence boundaries. Requiring such applications to install a sentence boundary detector that is not used seems inefficient.

That said, downstream products should feel free to integrate a sentence boundary detector.

**Comment by pvanickova** [comment]
ok, thanks for your feedback
