### ISSUE TITLE
Comment DeepSpeech/util/stm.py

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/DeepSpeech#1913]
@reuben --- can you make a short comment as to what an STM file is? I don't know what that stands for, and I doubt I'm the only one.

**Comment by reuben** [comment]
It's the format used by the TED-LIUM corpus, which we no longer use due to licensing constraints.

http://www1.icsi.berkeley.edu/Speech/docs/sctk-1.2/infmts.htm#stm_fmt_name_0
