### ISSUE TITLE
 (feature request) add `FLAGS.exported_model_batch_size` parameter

### ISSUE THREAD

**Issue by nicolaspanel** [mozilla/DeepSpeech#1920]
**Use case**: I'm using the exported model (`output_graph.pb`) to transcribe entire audio files (ie no streaming) and for performance reasons I would like to be able to transcribe multiple at once.

currently, `export` method  force model batch size to be `1`, see https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L752 which prevent batch mode.

**Feature request**: it would be nice to have a `FLAGS.exported_model_batch_size` parameter to customize this.

Possible values:
 - `None`: dynamic
 - `1` (default)
 - any integer > `1`

Code would then look like:
```py
inputs, outputs, _ = create_inference_graph(batch_size=FLAGS.exported_model_batch_size, n_steps=FLAGS.n_steps, tflite=FLAGS.export_tflite)
...
do_graph_freeze(...)
```

What do you think ? 
I can work on the PR

**Comment by lissyx** [comment]
The current inference graph is really tailored for `libdeepspeech.so`, which does not take care of batching. If we can keep the current lib code (or with few changes), maybe it's worth?

**Comment by nicolaspanel** [comment]
Thanks @lissyx for the quick reply
Since default value will still be `1`, this will have no impact on existing clients (such as libdeepspeech.so).

**Comment by lissyx** [comment]
Oh, you just add the parameter? I guess it's r+ then, maybe an opinion @reuben ?

**Comment by reuben** [comment]
Yep, would gladly take this PR. This use case is already tested (by evaluate.py) and it works fine, I see no reason to expose it to outside consumers.

**Comment by nicolaspanel** [comment]
@reuben @lissyx flag already exists but is not used. see https://github.com/mozilla/DeepSpeech/blame/master/util/flags.py#L65
