### ISSUE TITLE
(feature request) enable dynamic `batch_size`

### ISSUE THREAD

**Issue by nicolaspanel** [mozilla/DeepSpeech#1923]
NB: for now `export_batch_size` must be constant and greater than or equal to 1 due to https://github.com/mozilla/DeepSpeech/blame/master/DeepSpeech.py#L672 and https://github.com/mozilla/DeepSpeech/blame/master/DeepSpeech.py#L703

It would be nice to enable dynamic `export_batch_size`.

I think we could do that through a 0-D placeholder

Example
```py
def create_inference_graph(n_steps=16, tflite=False):
    batch_size = tf.placeholder(tf.int32, shape=(), name="batch_size")
    ...
    return (
            {
                'batch_size': batch_size,
                'input': input_tensor,
                'input_lengths': seq_length,
            },
            {
                'outputs': logits,
                'initialize_state': initialize_state,
            },
            layers
        )

logits, loss_ = session.run([transposed, loss], feed_dict={
    inputs['batch_size']: len(batch),
    inputs['input']: features,
    inputs['input_lengths']: features_len,
})
```
However, since it changes the inference graph we also have to update clients such as `
libdeepspeech.so`.

I can work on the PR if needed

**Comment by reuben** [comment]
I think the easiest first step would be to add optional support for dynamic batch size, not caring about the native clients, and just make sure not to change our defaults. Batch size > 1 with the streaming graph is really complicated and not really useful, since the streaming graph optimizes for latency rather than throughput, so I don't think we'll add support for that. But having the ability to export a model that handles variable batch sizes would be nice.

**Comment by nicolaspanel** [comment]
> I think the easiest first step would be to add optional support for dynamic batch size, not caring about the native clients, and just make sure not to change our defaults. 

ok

> Batch size > 1 with the streaming graph is really complicated and not really useful, since the streaming graph optimizes for latency rather than throughput, so I don't think we'll add support for that.

ok

> But having the ability to export a model that handles variable batch sizes would be nice.

ok. I'll work on the PR then.

Implementation will look like
```py
def create_inference_graph(batch_size=1, n_steps=16, tflite=False):
    ...
    if batch_size <= 0:
        if tflite:
            raise NotImplementedError('...')
        batch_size = tf.placeholder(tf.int32, name="batch_size")
        .... 
        return (
            {
                'batch_size': batch_size,
                'input': input_tensor,
                'input_lengths': seq_length,
            },
            {
                'outputs': logits,
                'initialize_state': initialize_state,
            },
            layers
        )
    elif not tflite:
        ... # same as before
    else:
        ... # same as before
```

**Comment by reuben** [comment]
Do you really need the batch_size placeholder? If you enforce n_steps=-1 then you avoid all of the state stuff which depends on the batch size.

**Comment by nicolaspanel** [comment]
@reuben  good point!
see https://github.com/mozilla/DeepSpeech/pull/1926
tested, work like a charm :+1:
