### ISSUE TITLE
fetching convert_graphdef_memmapped_format return 404 error

### ISSUE THREAD

**Issue by raspi-three** [mozilla/DeepSpeech#1927]
When I run the following, it returns a 404 error:
python3 util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --target /home/maxx/DeepSpeech/bin --arch gpu

index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.gpu/artifacts/public/convert_graphdef_memmapped_format return 404 error.

**Comment by lissyx** [comment]
there is no such target built, please use `--arch cpu`, there's nothing GPU specific on this binary.
