### ISSUE TITLE
Arbitrary number of LSTMs

### ISSUE THREAD

**Issue by bernardohenz** [mozilla/DeepSpeech#1933]
I've read some recent papers for speech recognition [1,2], and I noticed that they all tend to use more than a single LSTM layer.
[1] Park et al., Fully Neural Network Based Speech Recognition on Mobile and Embedded Devices. NeurIPS 2018.
[2]  He et al., Streaming End-to-end Speech Recognition For Mobile Devices. arXiv:1811.0662, 2018.

I tried to implement it by myself, and it seems to be working for training/evaluation/exporting. Unfortunately, I need some help about what changes should I make on the binaries.

The following patch holds the implementation of arbitrary number of LSTMs (haven't created a PR because the binaries were not touched).
[patch_more_LSTMs.patch.txt](https://github.com/mozilla/DeepSpeech/files/2928944/patch_more_LSTMs.patch.txt)

**Comment by kdavis-mozilla** [comment]
We have made a conscious choice to use a single LSTM layer; we want the model to be as lightweight as possible to allow targeting as many devices as possible, despite some of the devices being resource constrained.

However, that said if you want to discuss your multi-layer LSTM experiments we encourage and invite your input on our [discourse form](discourse) as we'd be very much interested in your results.

**Comment by cahuja1992** [comment]
> I've read some recent papers for speech recognition [1,2], and I noticed that they all tend to use more than a single LSTM layer.
> [1] Park et al., Fully Neural Network Based Speech Recognition on Mobile and Embedded Devices. NeurIPS 2018.
> [2] He et al., Streaming End-to-end Speech Recognition For Mobile Devices. arXiv:1811.0662, 2018.
> 
> I tried to implement it by myself, and it seems to be working for training/evaluation/exporting. Unfortunately, I need some help about what changes should I make on the binaries.
> 
> The following patch holds the implementation of arbitrary number of LSTMs (haven't created a PR because the binaries were not touched).
> [patch_more_LSTMs.patch.txt](https://github.com/mozilla/DeepSpeech/files/2928944/patch_more_LSTMs.patch.txt)

I am trying to apply this patch. Can you please tell for which tag this tag is for ?

**Comment by reuben** [comment]
Now that we've merged TensorFlow 1.14 support I plan to merge the CuDNN RNN support into master.

**Comment by kdavis-mozilla** [comment]
CuDNN RNN support  is in master.
