### ISSUE TITLE
CommonVoice importers should clean transcripts

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#1962]
At the moment there is no transcript cleaning done. At least `validate_label` should be applied to each sample. If invalid, the sample should be excluded and notified accordingly.

**Comment by rhamnett** [comment]
You have missed this line:

from util.text import validate_label

**Comment by tilmankamp** [comment]
Thanks! https://github.com/mozilla/DeepSpeech/pull/1964
