### ISSUE TITLE
how can run in tensorflow1.9.0-gpu?

### ISSUE THREAD

**Issue by feifaxiaoming** [mozilla/DeepSpeech#1971]
when i run this demo in linux   use tensorflow1.9.0-gpu ,but  i not use gpu ,it use cpu only .
how can i change demo to use gpu

**Comment by kdavis-mozilla** [comment]
The [documentation](https://github.com/mozilla/deepspeech#installing-deepspeech-python-bindings) states how to get the GPU version.
