### ISSUE TITLE
Can not infer after training.

### ISSUE THREAD

**Issue by aijianiula0601** [mozilla/DeepSpeech#1977]
hi,I trained “data_thcs30”.It can run and exported model file correctly,but it output nothing when i use the model to infer. I use the following command:

```
deepspeech --model /tmp/DeepSpeech/data_thchs30/model_201903201911/output_graph.pbmm 
–alphabet /tmp/dataset/data_thchs30/csv/alphabet.txt 
–lm /tmp/data_thchs30/csv/lm.binary 
–trie /tmp/data_thchs30/csv/trie 
–audio /tmp/data_thchs30/test/D8_999.wav
```

And,It always output like the in training

```
WER: 1.000000, CER: 37.000000, loss: 161.008698
 - src: "好 容 易 盼 来 一 位 望 望 这 一 片 荒 芜 又 扭 身 而 去"
 - res: ""
```

The WER is always 1.0 and res is null.

**Comment by lissyx** [comment]
> hi,I trained “data_thcs30”.It can run and exported model file correctly,but it output nothing when i use the model to infer. I use the following command:

Can you document your training ?

> The WER is always 1.0 and res is null.

It's not `null`, it's empty

**Comment by aijianiula0601** [comment]
yes,it's empty.Has anyone come across this?

**Comment by lissyx** [comment]
Still lacking your training infos

**Comment by feifaxiaoming** [comment]
@aijianiula0601  您好，我想问一下，你自己训练完model deepspeech --model /tmp/DeepSpeech/data_thchs30/model_201903201911/output_graph.pbmm 
–alphabet /tmp/dataset/data_thchs30/csv/alphabet.txt 
–lm /tmp/data_thchs30/csv/lm.binary 
–trie /tmp/data_thchs30/csv/trie 
–audio /tmp/data_thchs30/test/D8_999.wav
这个可以运行吗 ，您是在gpu上运行的吗？  你的gpu是多少呢 ？

**Comment by feifaxiaoming** [comment]
@aijianiula0601  @lissyx 我自己训练完成之后，然后用这个命令运行，我报错了，说是需要libcuda10.0,这个download下来gpu的是10.0的吗？
python3 util/taskcluster.py --arch gpu --target  ./native_client 我运行的是这个命令安装的
"libcudart.so.10.0 cannot open shared object file: No such file or directory"  报这个错。
但是我系统只有libcudart.so.9.0 ，请问有9的GPU吗？

**Comment by feifaxiaoming** [comment]
@lissyx  之后，我就测试不了了，请问我什么解决方法吗？

**Comment by aijianiula0601** [comment]
> Still lacking your training infos

my training commad:

python -u /home/huangjiahong/github/DeepSpeech/DeepSpeech.py \
--train_files /tmp/thchs30-train.csv \
--dev_files /tmp/thchs30-dev.csv \
--test_files /tmp/thchs30-test.csv \
--train_batch_size 1024 \
--dev_batch_size 256 \
--test_batch_size 256 \
--beam_width 20 \
--n_hidden 100 \
--epoch 30 \
--report_count 1000 \
--validation_step 1 \
--coord_port 2502 \
--export_dir /tmp/DeepSpeech/data_thchs30/model \
--checkpoint_dir /tmp/DeepSpeech/data_thchs30/checkpoint \
--alphabet_config_path /tmp/speechRecognition/dataset/data_thchs30/external_csv/test/alphabet.txt \
--lm_binary_path /tmp/speechRecognition/dataset/data_thchs30/external_csv/test/lm.binary \
--lm_trie_path /tmps/speechRecognition/dataset/data_thchs30/external_csv/test/trie

**Comment by lissyx** [comment]
> --train_files /tmp/thchs30-train.csv
> --dev_files /tmp/thchs30-dev.csv
> --test_files /tmp/thchs30-test.csv

How much data is there here?

> --lm_binary_path /tmp/speechRecognition/dataset/data_thchs30/external_csv/test/lm.binary
> --lm_trie_path /tmps/speechRecognition/dataset/data_thchs30/external_csv/test/trie

Are you sure about your language model here? It might interact



> ```
> WER: 1.000000, CER: 37.000000, loss: 161.008698
>  - src: "好 容 易 盼 来 一 位 望 望 这 一 片 荒 芜 又 扭 身 而 去"
>  - res: ""
> ```
> 
> 
> The WER is always 1.0 and res is null.

Please remember we show a subset of the worst from the test results. Depending on how your test dataset is built and its size, it may explain and your model could be okay.

**Comment by lissyx** [comment]
> @aijianiula0601 @lissyx 我自己训练完成之后，然后用这个命令运行，我报错了，说是需要libcuda10.0,这个download下来gpu的是10.0的吗？
> python3 util/taskcluster.py --arch gpu --target ./native_client 我运行的是这个命令安装的
> "libcudart.so.10.0 cannot open shared object file: No such file or directory" 报这个错。
> 但是我系统只有libcudart.so.9.0 ，请问有9的GPU吗？

> @lissyx 之后，我就测试不了了，请问我什么解决方法吗？

I don't speak chinese, but you need to use CUDA 10.0 with current master binaries. Use `0.4.1` release if you are stuck with CUDA 9.0

**Comment by raultang** [comment]
@lissyx Seems there are more people have this issue:
https://discourse.mozilla.org/t/training-chinese-model/27769/25

I tried with one wav file from data_thchs30 data set, but infer nothing.
wav_filename,wav_filesize,transcript
/data/data_thchs30/train/A11_0.wav,249644,绿 是 阳 春 烟 景 大 块 文 章 的 底 色 四 月 的 林 峦 更 是 绿 得 鲜 活 秀 媚 诗 意 盎 然

**Comment by lissyx** [comment]
>  Seems there are more people have this issue:

Maybe, but none of my questions above have been answered, it's hard to help in this context.

**Comment by lissyx** [comment]
@raultang Can you share more details on your single-file example ? We need network parameters, training parameter to have anything conclusive. Please see what we do with `LDC93S1` sample.

We've got a lot of people able to train on Chinese, so it's unlikely that this is the problem here. I do insist again, examples shown when we finish training and **the worst ones**. It's hard to have any definitive conclusion when the only informations we have here are incomplete:

**Comment by kdavis-mozilla** [comment]
@raultang Two questions:

1. What happens to inference when you **do not** use any language model?
2. How did you create your language model?

**Comment by raultang** [comment]
@lissyx Thanks for the quick reply, today I tried to reproduce the problem, that was I tried one month before, the environment changed a lot during the time.
Seems I adjusted  alphabet using all character, now seem the infer is working:

The training steps:
`
python DeepSpeech.py \
	--alphabet_config_path ./data/thchs30/alphabet.txt \
	--train_files ./data/thchs30/train.csv \
	--dev_files ./data/thchs30/train.csv \
	--test_files ./data/thchs30/train.csv \
	--train_batch_size 1 \
	--dev_batch_size 1 \
	--test_batch_size 1 \
	--n_hidden 2048 \
	--learning_rate 0.0001 \
	--checkpoint_dir /tmp/thchs30/checkpoints \
	--checkpoint_secs 60 \
	--validation_step 50 \
	--export_dir ./data/thchs30/ \
	--epoch 1000
`
Test - WER: 1.000000, CER: 52.000000, loss: 0.000852
WER: 1.000000, CER: 52.000000, loss: 0.000852
 - src: "绿 是 阳 春 烟 景 大 块 文 章 的 底 色 四 月 的 林 峦 更 是 绿 得 鲜 活 秀 媚 诗 意 盎 然 "
 - res: "更是阳块烟色文底月得诗"

The infer steps:
`deepspeech \
	--model ./data/thchs30/output_graph.pbmm \
	--alphabet ./data/thchs30/alphabet.txt \
	--audio ./data/data_thchs30/train/A11_0.wav`
Running inference.
绿 是 阳 春 烟 景 大 块 文 章 的 底 色 四 月 的 林 峦 更 是 绿 得 鲜 活 秀 媚 诗 意 盎 然

no idea why the training test result is different with recognization result.

@kdavis-mozilla Actually I didn't create language model yet, just want to try DeepSpeech out first; maybe next step.

**Comment by lissyx** [comment]
> no idea why the training test result is different with recognization result.

Can you elaborate ? I'm not speaking Chinese, so I'm unsure about understand the problem here. But your training command line is a bit strange: data batch of 1, learning rate and epoch seems weird.

Is this an overfitting training test ?



> @kdavis-mozilla Actually I didn't create language model yet, just want to try DeepSpeech out first; maybe next step.

That might have an impact, since your are then using english LM in this setup. Maybe try passing lm alpha and beta parameters with value of `0.0` to nuke their impact ?

**Comment by tsungruihon** [comment]
@lissyx @aijianiula0601  It seems that i faced the same problem like you. The `res` in `Test Process` happens to be blank.

![Screen Shot 2019-07-31 at 12 00 54 PM](https://user-images.githubusercontent.com/11624203/62182919-e5933780-b38a-11e9-8e1a-e57dec8f4579.png)

**Comment by lissyx** [comment]
@raultang Can you give us update?

**Comment by cryptoaimdy** [comment]
@lissyx 

Hi i am getting no text in res
out put 
res " "

EXplaination about my training model.
I am using english model
created binary file with 45 audio corpus.
using trie from pretrained english model.
train has 25 audios , 2-4 sec each with their transcript and size
dev has 10 audios with size and trans
and test has 7 audios with size and trans

upon running deepspeech.py i am getting this: 
is it normal? if yes then why am i not getting res?

**Comment by cryptoaimdy** [comment]
@lissyx 

Check output

Epoch 2 | Training | Elapsed Time: 0:11:37 | Steps: 24 | Loss: 200.743011
Epoch 2 | Validation | Elapsed Time: 0:00:09 | Steps: 10 | Loss: 145.589038 | Dataset: data/dev/dev.csv
I Saved new best validating model with loss 145.589038 to: /home/yk/.local/share/deepspeech/checkpoints/best_dev-144
Epoch 3 | Training | Elapsed Time: 0:10:26 | Steps: 23 | Loss: 188.129880

Epoch 3 | Training | Elapsed Time: 0:11:38 | Steps: 24 | Loss: 200.469688
Epoch 3 | Validation | Elapsed Time: 0:00:09 | Steps: 10 | Loss: 145.480138 | Dataset: data/dev/dev.csv
I Saved new best validating model with loss 145.480138 to: /home/yk/.local/share/deepspeech/checkpoints/best_dev-168
I Early stop triggered as (for last 4 steps) validation loss: 145.480138 with standard deviation: 0.053664 and mean: 145.650564
I FINISHED optimization in 0:47:13.484660
WARNING:tensorflow:Entity <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f0637a1a978>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: converting <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f0637a1a978>>: AttributeError: module ‘gast’ has no attribute ‘Num’
W1007 10:09:12.322466 139666740873024 ag_logging.py:145] Entity <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f0637a1a978>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: converting <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f0637a1a978>>: AttributeError: module ‘gast’ has no attribute ‘Num’
INFO:tensorflow:Restoring parameters from /home/yk/.local/share/deepspeech/checkpoints/best_dev-168
I1007 10:09:12.369412 139666740873024 saver.py:1280] Restoring parameters from /home/yk/.local/share/deepspeech/checkpoints/best_dev-168
I Restored variables from best validation checkpoint at /home/yk/.local/share/deepspeech/checkpoints/best_dev-168, step 168
Testing model on data/test/test.csv
Test epoch | Steps: 7 | Elapsed Time: 0:00:05
Test on data/test/test.csv - WER: 1.000000, CER: 1.000000, loss: 473.767029
WER: 1.000000, CER: 1.000000, loss: 191.858261

wav: file:///home/yk/DeepSpeech/data/test/044.wav
src: “syuui”
res: “”
WER: 1.000000, CER: 1.000000, loss: 491.481476

wav: file:///home/yk/DeepSpeech/data/test/041.wav
src: “oimmyy”
res: “”
WER: 1.000000, CER: 1.000000, loss: 507.216888

wav: file:///home/yk/DeepSpeech/data/test/043.wav
src: “o rrhof i”
res: “”
WER: 1.000000, CER: 1.000000, loss: 510.564240

wav: file:///home/yk/DeepSpeech/data/test/047.wav
src: "o p "
res: “”
WER: 1.000000, CER: 1.000000, loss: 512.405273

wav: file:///home/yk/DeepSpeech/data/test/045.wav
src: “ohndieya”
res: “”
WER: 1.000000, CER: 1.000000, loss: 547.843018

wav: file:///home/yk/DeepSpeech/data/test/042.wav
src: “pfnry nya”
res: “”
WER: 1.000000, CER: 1.000000, loss: 554.999878

wav: file:///home/yk/DeepSpeech/data/test/046.wav
src: “o uu”
res: “”

**Comment by lissyx** [comment]
Please use discourse, this is not a bug. 25 audio files of 2-4 secs, that's just not enough data. That's why you get empty strings.

**Comment by cryptoaimdy** [comment]
Okay.
Qn 1: Approximately How much data is minimum required to get the response?
Qn 2: How to train from deepspeech 0.5 released model? what should i do to add my corpus in prebuilt model in train test and dev? how more audio should be added?

**Comment by cryptoaimdy** [comment]
@lissyx Please reply the above questions on discourse. thank you.


https://discourse.mozilla.org/t/deepspeech-training-own-model/46210
