### ISSUE TITLE
DeepSpeech.py ignores provided arguments

### ISSUE THREAD

**Issue by wagnrd** [mozilla/DeepSpeech#1980]
After the commit from [March 19 2019](https://github.com/mozilla/DeepSpeech/commit/91fa181b7406fe5f0010348ef71d26b7000666c6#diff-79c8372f97f7f5a6d8660bd265f836d7) it seems that DeepSpeech.py doesn't care about the parameters I provide anymore. It ignores the given folder for checkpoints and the given number of epochs.

It creates a folder in `~/.local/share/deepsheech/checkpoints` which I haven't provided.
It goes through all his default epochs even though the argument was set to 0/1.

I use this script to run the training:

```
#!/usr/bin/env bash

nice -20 python3 DeepSpeech.py \
	--train_files data/CV/de/clips/train.csv \
	--dev_files data/CV/de/clips/dev.csv \
	--test_files data/CV/de/clips/test.csv \
  	--train_batch_size 150 \	# 48
 	--dev_batch_size 150 \	# 48
  	--test_batch_size 150 \	# 24
  	--n_hidden 2048 \
  	--epoch 0 \	# 33
  	--validation_step 0 \	# 1
  	--early_stop false \	# true
  	--earlystop_nsteps 4 \
  	--estop_mean_thresh 0.5 \
  	--estop_std_thresh 0.5 \
  	--dropout_rate 0.15 \
  	--learning_rate 0.0001 \
  	--export_dir data/results/model_export/ \
  	--checkpoint_dir data/results/checkpoint/ \
```

before pulling the new commit everything went fine.

Also it is worth noting, that there are tensorflow warnings all over the place:

```
WARNING:tensorflow:From /home/frozzen/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Preprocessing ['data/CV/de/clips/train.csv']
Preprocessing done
Preprocessing ['data/CV/de/clips/dev.csv']
Preprocessing done
WARNING:tensorflow:From /home/frozzen/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py:696: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
W Parameter --validation_step needs to be >0 for early stopping to work
WARNING:tensorflow:From /home/frozzen/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /home/frozzen/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1070: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
I STARTING Optimization
I Training epoch 1...
  5% (1 of 18) |##                                    | Elapsed Time: 0:00:00 ETA:  00:00:00
```

- Linux Deepin 15.9
- TensorFlow installed with `pip3 -r requirements.txt`
- Tensorflow 1.13
- Python 3.6.5 
- I use everything precompiled from taskcluster

**Comment by reuben** [comment]
In the shell script you can't add comments after a line that ends with `\`, it causes everything below to be a comment. If you remove the `# 48`, `# 24`, etc, it should work.

**Comment by reuben** [comment]
Actually, it doesn't cause everything below to be a comment, just ends the command right there, IIRC. If you want for the training to complete, you should see some errors about `--dev_batch_size` not being a recognized command or something like that. In any case, removing the comments should fix it :)

**Comment by wagnrd** [comment]
Ok, I didn't expect it to be this trivial.
But now it works, thank you so much.
