### ISSUE TITLE
how to test outgrapy.pb

### ISSUE THREAD

**Issue by feifaxiaoming** [mozilla/DeepSpeech#1981]
i use 
python3 util/taskcluster.py --arch gpu --target ./native_client  to  install gpu deepspeech.

but when i run test
./deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio audio_input.wav

It  have an  error occurs.

error while loading shared libraries: libcudart.so.10.0: cannot open shared object file: No such file
but my system is libcudart.so.9.0    
so how i can test it?  i don not want change cuda update.

**Comment by lissyx** [comment]
Current code relies on tensorflow r1.13 that depends on Cuda 10.0, please download earlier version, such as 0.4.1 for Cuda 9.0

**Comment by feifaxiaoming** [comment]
i use DeepSpeech-0.4.1  this version 。
python3 util/taskcluster.py --arch gpu --target ./native_client to install gpu deepspeech.
it also have error :
./native_client/deepspeech: error while loading shared libraries: libcudart.so.10.0: cannot open shared object file: No such file or directory
it really  fo cuda 9.0?

**Comment by feifaxiaoming** [comment]
@lissyx

**Comment by feifaxiaoming** [comment]
we change this method  ,download zip :native_client.amd64.cuda.linux.tar.xz   
we download this package to test ,but i also have a error :
Invalid argument: No OpKernel was registered to support Op 'Slice' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[{{node Slice}} = Slice[Index=DT_INT32, T=DT_INT32](Shape_1, Slice/begin, Slice/size)]]
Could not create model.
we used:
DeepSpeech-0.4.1
native：
native_client.amd64.cuda.linux.tar.xz     i download from github。

**Comment by lissyx** [comment]
Please avoid posting the same question in multiple issues.
