### ISSUE TITLE
Update CommonVoice section in README to import v2.0

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#1982]
The CommonVoice section of the README should instruct on importing CommonVoice v2.0 instead of v1.x.

**Comment by kdavis-mozilla** [comment]
There's already a [PR](https://github.com/mozilla/DeepSpeech/pull/1965) that's inflight

**Comment by tilmankamp** [comment]
Awesome! Now the PR got a backing issue.

**Comment by tilmankamp** [comment]
Fixed by #1965 and #1996.
