### ISSUE TITLE
how can i Specified GPU 

### ISSUE THREAD

**Issue by feifaxiaoming** [mozilla/DeepSpeech#1983]
i have two GPU in my system， but  i do not want to use  two GPU ，i want use  one GPU 。
how can i Specified GPU？

i change  in  util/gpu.py use one GPU ,  but   when  i  run  ,i still use two GPU.

**Comment by feifaxiaoming** [comment]
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:17:00.0 Off |                  N/A |
| 29%   52C    P2    61W / 250W |  11594MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:65:00.0  On |                  N/A |
| 48%   77C    P2   245W / 250W |  11628MiB / 12188MiB |     91%      Default |

**Comment by kdavis-mozilla** [comment]
Use [CUDA_VISIBLE_DEVICES](https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/)
