### ISSUE TITLE
Filtering out-of-alphabet characters

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#1991]
As it turns out, the English sets in CommonVoice v2.0 contain out-of-alphabet (of the English 26 letter one plus space plus apostrophe) characters - `[':', 'ú', 'l', "'", 'é', 'á', ';', '’', 'ō', '`&#96;`', '!', ' ', '–', 'ó', 'â', 'ë', 't', 'ñ',]`. While some of them seem to be a case for `validate_label`, others most probably come from borrowed words of other languages. How should we deal with this cases - short term and long term?
As DeepSpeech fails importing csv files containing such characters in transcripts we need a short term solution which could be one or more of:
 - Adding an option for ignoring samples containing out-of-alphabet transcripts to `DeepSpeech.py`.
- Adding a similar option to `import_cv2.py` along with specifying the alphabet file to use.
- Providing a tool to filter samples from CSV files (providing an alphabet) after import.
- Adding this kind of functionality to the voice corpus tool.

What do you vote for?

**Comment by lissyx** [comment]
@tilmankamp We faced a similar situation for CV French, and I think a multi-stage solution is the best approach, after speaking a bit with @kdavis-mozilla:
 - fix the common voice text corpus dataset
 - if possible, enhance corpora creator: there might be cases where the strippping only makes sense for deepspeech and not other applications of voice, so this is not always possible
 - as a last resort, we could add language-specific tooling on `import_cv2.py` side to cleanup

**Comment by reuben** [comment]
In other importers we used unicode normalization to remove the diacritics and leave the underlying ASCII character, for example: https://github.com/mozilla/DeepSpeech/blob/a009361e470b591f20562214122944d9811592ba/bin/import_fisher.py#L112

For loan words, I think it's acceptable to do something similar in our CV2 importer since it's a DeepSpeech-specific restriction. So I would vote for making the importer deal with this, either ignoring samples or trying to fix them.

**Comment by kdavis-mozilla** [comment]
I second what @reuben suggested, unicode normalization in the importer.

The Common Voice data set can validly contain accents, e.g. in English café is a valid word. So removing them in the Common Voice data set isn't an option. You have to remember Common Voice is used for more than Deep Speech.

**Comment by tilmankamp** [comment]
Thanks for your feedback! Based on it we should do the following:

1. Adding Unicode normalization of diacritics to the CV2 importer
2. Adding an option for alphabet-based character filtering to the CV2 importer (second option from question)
