### ISSUE TITLE
TypeError: repl must be a string

### ISSUE THREAD

**Issue by LuciferA678** [mozilla/DeepSpeech#1998]
As I started training Deepspeech Model it gave error 
Traceback (most recent call last):
  File "./DeepSpeech.py", line 934, in <module>
    tf.app.run(main)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 886, in main
    train()
  File "./DeepSpeech.py", line 386, in train
    hdf5_cache_path=FLAGS.train_cached_features_path)
  File "/app/DeepSpeech-master/util/preprocess.py", line 58, in preprocess
    file['wav_filename'] = file['wav_filename'].str.replace(r'(^[^/])', lambda m: os.path.join(csv_dir, m.group(1)))
  File "/root/anaconda3/lib/python3.6/site-packages/pandas/core/strings.py", line 1506, in replace
    flags=flags)
  File "/root/anaconda3/lib/python3.6/site-packages/pandas/core/strings.py", line 322, in str_replace
    raise TypeError("repl must be a string")
TypeError: repl must be a string
TypeError: repl must be a string
what should be done?

**Comment by kdavis-mozilla** [comment]
What command line did you execute?

**Comment by LuciferA678** [comment]
./DeepSpeech.py --train_files /app/cv-valid-train.csv --dev_files /app/cv-valid-dev.csv --test_files /app/cv-valid-test.csv

**Comment by kdavis-mozilla** [comment]
How are cv-valid-train.csv, cv-valid-dev.csv, and cv-valid-test.csv created?

**Comment by LuciferA678** [comment]
cv-valid-train.csv, cv-valid-dev.csv, and cv-valid-test.csv are created by bin/import_cv.py script

**Comment by kdavis-mozilla** [comment]
Running on what data?

**Comment by LuciferA678** [comment]
data which was downloaded by bin/import_cv.py ,i.e cv_corpus_v1

**Comment by kdavis-mozilla** [comment]
What version of pandas are you using?

**Comment by LuciferA678** [comment]
pandas =0.19.2

**Comment by kdavis-mozilla** [comment]
That's the problem.

This bug was fixed two years ago in Pandas 0.20.0 , see this [issue](https://github.com/pandas-dev/pandas/issues/15055). Could you update to a recent, Pandas.

**Comment by lissyx** [comment]
> That's the problem.
> 
> This bug was fixed two years ago in Pandas 0.20.0 , see this [issue](https://github.com/pandas-dev/pandas/issues/15055). Could you update to a recent, Pandas.

Maybe we should enforce `pandas >= 0.20.0` in `requirements.txt` ?

**Comment by kdavis-mozilla** [comment]
Maybe, but I don't think it would have fixed this problem. LuciferA678 didn't use requirements.txt but used an anaconda package with a pre-installed pandas.

**Comment by LuciferA678** [comment]
Thanks a lot @kdavis-mozilla it worked,and I did not used requirements.txt
but I landed in another error 
Traceback (most recent call last):
  File "./DeepSpeech.py", line 934, in <module>
    tf.app.run(main)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 886, in main
    train()
  File "./DeepSpeech.py", line 424, in train
    gradients, loss = get_tower_results(model_feeder, optimizer, dropout_rates)
  File "./DeepSpeech.py", line 256, in get_tower_results
    avg_loss = calculate_mean_edit_distance_and_loss(model_feeder, i, dropout_rates, reuse=i>0)
  File "./DeepSpeech.py", line 186, in calculate_mean_edit_distance_and_loss
    logits, _ = BiRNN(batch_x, batch_seq_len, dropout, reuse)
  File "./DeepSpeech.py", line 88, in BiRNN
    layer_1 = tf.nn.dropout(layer_1, rate=dropout[0])
TypeError: dropout() got an unexpected keyword argument 'rate'
Can You help it out?

**Comment by kdavis-mozilla** [comment]
Could you use requirements.txt as indicted in [Installing prerequisites for training](https://github.com/mozilla/deepspeech#installing-prerequisites-for-training).

**Comment by LuciferA678** [comment]
Thank you the issue is solved and trainning is started but
after 55 epochs error occured

:---->E [Errno 5] Input/output error

What is this error and what should be done?
