### ISSUE TITLE
Verify that merge_repeated=False is the correct thing to do

### ISSUE THREAD

**Issue by Cwiiis** [mozilla/DeepSpeech#200]
To fix issue #53, we added merged_repeated=False to the ctc_beam_search_decoder call. This allows it to return repeated letters and allows us to get to WER=0 for the ldc93s1 corpus.

I am uncertain if this was the correct change to make globally, however, and am concerned that it only worked on ldc93s1 due to the particular properties of that single audio file. It's probably fine, but opening this issue to keep track of it. If we have some unexplained behaviour with poor WER and we see repeated letters, we may want to investigate this.

**Comment by reuben** [comment]
This might be useful: https://github.com/tensorflow/tensorflow/pull/5194

**Comment by Cwiiis** [comment]
I'm still not really clear from that change to be honest... I guess I don't know exactly how spaces get encoded, so I'm confused. Take the sentence, 'all year', to get that, would you have 'A * L * L * _ * Y * E * A * R', or would you have 'A L L * Y E A R'? And given that letters can last over variable amounts of time, would merge_repeated=False stop you getting 'all year' from 'A L L L L * Y E A R'?

**Comment by lingz** [comment]
Merge repeated is supposed to allow for repeated labels, you juts need to have at least one blank label between the outputs of the L's in that example above.

**Comment by reuben** [comment]
Can this be closed now?

**Comment by Cwiiis** [comment]
Things seem to be fine, so I guess so? I'm still unclear exactly what result this has though (see specifically the last part of my previous comment)

**Comment by reuben** [comment]
The answer to the second part of the comment is yes, it would stop you from getting "all year" in that case. But the network should learn to output blank labels accordingly so that this isn't a problem. I'll close this for now.
