### ISSUE TITLE
E [Errno 5] Input/output error

### ISSUE THREAD

**Issue by LuciferA678** [mozilla/DeepSpeech#2004]
I have started the training using the data by import_cv 
command:-
 ./DeepSpeech.py --train_files /app/cv-valid-train.csv --train_batch_size 5 --dev_files /app/cv-valid-dev.csv --dev_batch_size 5 --test_files /app/cv-valid-test.csv --test_batch_size 5

Error
But after 62 epoch it gave and error and training was stopped
:-->E [Errno 5] Input/output error
what should be done?

**Comment by lissyx** [comment]
> :-->E [Errno 5] Input/output error
> what should be done?

Giving more context, first ?

**Comment by LuciferA678** [comment]
Sorry I can't get you 
Preprocessing ['/app/cv-valid-train.csv']
Preprocessing done
Preprocessing ['/app/cv-valid-dev.csv']
Preprocessing done
W Parameter --validation_step needs to be >0 for early stopping to work
I STARTING Optimization
I Training epoch 55...
I Training of Epoch 55 - loss: 190.732836
I Training epoch 56...
I Training of Epoch 56 - loss: 193.679107
I Training epoch 57...
I Training of Epoch 57 - loss: 193.652214
I Training epoch 58...
I Training of Epoch 58 - loss: 193.667971
I Training epoch 59...
I Training of Epoch 59 - loss: 193.587716
I Training epoch 60...
I Training of Epoch 60 - loss: 193.726443
I Training epoch 61...
I Training of Epoch 61 - loss: 193.645015
I Training epoch 62...
E [Errno 5] Input/output error

**Comment by lissyx** [comment]
Did you searched for "Input/Ouput Error"? It's very likely a space issue

**Comment by LuciferA678** [comment]
I have checked it but Space can't be the problem I have 1 Tb of free space, and as I mentioned I have used batch size also 5 only...

**Comment by lissyx** [comment]
> 1 Tb of free space

Where ? `df -h` please.

**Comment by LuciferA678** [comment]
You are asking for hard drive space or RAM ?

**Comment by lissyx** [comment]
> You are asking for hard drive space or RAM ?

Drive, not RAM. `Errno 5` is 99.999% a space issue, and since you don't provide more details, we can't help. Maybe `/tmp`, maybe `/` ... ?

**Comment by lissyx** [comment]
Also what is `/app` ? How do you run training, bare-metal ? Containers ? Remote disk ?

**Comment by LuciferA678** [comment]
Remote Disk 
Thank you the issue is solved when I started the training again.

 But it gave this error:


Preprocessing ['/app/cv-valid-train.csv']
Preprocessing done
Preprocessing ['/app/cv-valid-dev.csv']
Preprocessing done
W Parameter --validation_step needs to be >0 for early stopping to work
Preprocessing ['/app/cv-valid-test.csv']
Preprocessing done
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  ../kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43
Aborted

What should be done
*-I have install git lfs

**Comment by lissyx** [comment]
> terminate called after throwing an instance of 'lm::FormatLoadException'
> what(): ../kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector&) threw FormatLoadException.
> first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data. Byte: 43
> Aborted
> 
> What should be done
> *-I have install git lfs

Obviously, it's not properly installed / it failed to checkout properly the data. Please `git lfs fetch && git lfs checkout`.

**Comment by lissyx** [comment]
> Remote Disk
> Thank you the issue is solved when I started the training again.

Right, so maybe network issue or something. Nothing we can help, but good to know it's working. I'm going to close this then. For further help, please use Discourse.
