### ISSUE TITLE
Problem in loading lm

### ISSUE THREAD

**Issue by LuciferA678** [mozilla/DeepSpeech#2008]
After running the following command training was completed but it landed in
lm::FormatLoadException'

:------>./DeepSpeech.py --train_files /app/cv-valid-train.csv --train_batch_size 5 --dev_files /app/cv-valid-dev.csv --dev_batch_size 5 --test_files /app/cv-valid-test.csv --test_batch_size 5
----->output
Preprocessing ['/app/cv-valid-train.csv']
Preprocessing done
Preprocessing ['/app/cv-valid-dev.csv']
Preprocessing done
W Parameter --validation_step needs to be >0 for early stopping to work
Preprocessing ['/app/cv-valid-test.csv']
Preprocessing done
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  ../kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43
Aborted
*I have install git lfs
What should be done?

**Comment by lissyx** [comment]
@LuciferA678 I've already replied to that. Stop spamming.

**Comment by LuciferA678** [comment]
I got stuck in that and error and  you closed that issue and hence I had to reopen the issue.
Please listen to problem and then comment whether I am spamming or not.

I followed your steps and did
git lfs fetch all
git lfs checkout
It gave error at git lfs checkout 
Git cannot resolve Head
what should be done?

**Comment by reuben** [comment]
This repository is not for Git LFS support and we're not Git LFS experts. Somehow your install is broken. Try starting from scratch, including cloning DeepSpeech.

**Comment by lissyx** [comment]
> I followed your steps and did

And yet you reopened under a new issue instead of asking / checking on discourse as I said. And you even reopened without giving the new error you got.

So yes, that's spamming.
