### ISSUE TITLE
Change extended output format?

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2013]
There are no issues with the CSV output right now, but thinking ahead to the future, I wonder if it will be too limiting? It might be difficult to add new features in future for scripts that assume there will be a fixed number of commas, or in cases where the number of metadata items is not known in advance.

As an example, what would be really handy is if DeepSpeech could in future suggest alternative words that I could either automatically substitute or provide a dropdown for users to select from. This seems like a system that CSV probably wouldn’t be great for, given that the number of suggested words would vary.

JSON output didn’t work well for me before, but I was outputting all words in a single JSON object. I think it would work better if each word was its own self-contained JSON dictionary on its own line and I just parsed each word dictionary individually.

e.g.
```
{“word”:”the”, “time”:1.004, “duration”:0.132, ”probability”:42, ”alternatives”:[{“word”:”tea”, “probability”:25}]}
{“word”:”angry”, “time”:1.127, “duration”:0.26, ”probability”:22, ”alternatives”:[{“word”:”hungry”, “probability”:15}, {“word”:”mangy”, “probability”:9}]}

```

The reason I bring it up now is that DeepSpeech 0.5 hasn’t shipped publicly yet so probably few people are building scripts around the CSV, so it will be easier to change it now than later on.

I’m happy to make the changes but I’ll be pretty busy over the next week. I might have a spare hour or two here and there though. If not I can definitely get it done by next weekend.

I just wanted to get opinions and feedback before looking into it. Also, JSON needn’t necessarily be the format; I am open to other format suggestions.

**Comment by lissyx** [comment]
Well, since it is all on client-side, we can experiment as much as we want :). I think JSON could still be a good fit.

**Comment by dabinat** [comment]
In theory this is complete, except I can't actually test it due to this issue:
https://discourse.mozilla.org/t/upgrading-pre-trained-model-to-version-1/38220

**Comment by dabinat** [comment]
Ok, I've got it working now. Before I submit a PR, I had one question: what is the unit of the probability variable in the Metadata struct? I'm getting values like 377.149292 so it doesn't seem like it's a percentage.

**Comment by dabinat** [comment]
Also, @lissyx, I noticed you'd made some changes to the implementation in #2022, such as splitting it up into separate --extended and --csv args. I can replicate this for the JSON implementation but I was curious what the purpose of --extended by itself was? It appears to output just the transcription by itself, which is equivalent to not specifying it at all.

**Comment by lissyx** [comment]
It's for testing purposes, shows transcript built from the Metadata structure and matching API call

**Comment by dabinat** [comment]
Ok, I left it as-is for now.

Filed as PR #2058.
