### ISSUE TITLE
Generate Trie Issue

### ISSUE THREAD

**Issue by beeteax** [mozilla/DeepSpeech#2016]
./generate_trie ~/GermanSpeechToText/DeepSpeech/data/alphabet.txt ~/GermanSpeechToText/GermanAudioData/lm2.binary ~/
ERROR: VectorFst::Write: Write failed: <unspecifed>

I keep on getting this Error while trying to create Trie for German Data.

**Comment by reuben** [comment]
The last parameter is the path of the trie file to be written, it needs to be a file, not a folder.
