### ISSUE TITLE
Not able to generate trie file (generate_trie.cpp)

### ISSUE THREAD

**Issue by Dantes999** [mozilla/DeepSpeech#2021]
Hello,

I really don´t know why i cant "use"  generate_trie.
The build of lm.binary was successfull.
But when i write:
`./native_client/generate_trie data/alphabet.txt data/lm/lm.binary data/lm/clean_vocab.txt ./data/trie`
Then evertime the comiler say, that this file or dir does not exist.

![image](https://user-images.githubusercontent.com/16576412/55741048-a41dfb80-5a2c-11e9-9377-a927e99785e0.png)

Ive tried it parallel on local ubuntu laptop, same issue. 
Ive tried g++ generate_trie.cpp but then it get some error with include.

**Comment by reuben** [comment]
You have to build it. https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md

**Comment by reuben** [comment]
Or download pre-built binaries: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md#installing-our-pre-built-binaries
