### ISSUE TITLE
Checkpoint directory does not contain a valid checkpoint state

### ISSUE THREAD

**Issue by dardourimohamed** [mozilla/DeepSpeech#2030]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian Stretch
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream TensorFlow
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**: 3.5.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: No GPU
- **Exact command to reproduce**: `python3 DeepSpeech.py --train_files features/clips/train.csv --dev_files features/clips/dev.csv --test_files features/clips/test.csv`

I am trying to train using the French datasets downloaded from https://voice.mozilla.org/fr/datasets
1 - I extracted `fr.tar.gz` into `features`
2 - Then trasformed them using `python3 bin/import_cv2.py features` with some bug-fixes by adding `encoding="utf-8"` to the `open()` and `write()` so they could support special characters.
3 - Then I extracted `alphabet.txt` from CSV files using `python3 util/check_characters.py -csv features/clips/train.csv` also with same bug-fixes.
4 - And finally ran the training and got this error : `E Checkpoint directory (/root/.local/share/deepspeech/checkpoints) does not contain a valid checkpoint state.`

My `/root/.local/share/deepspeech/checkpoints` is empty
I also have `/root/.local/share/deepspeech/summaries` which contains two empty directories `dev` and `train`
All these directories are created right when I run the command.

**Comment by reuben** [comment]
Please update to latest master and try again.
