### ISSUE TITLE
InvalidArgumentError: Data too short when trying to read string

### ISSUE THREAD

**Issue by kst5118** [mozilla/DeepSpeech#2048]
I just start training with my own datasets and got an error like this.

 + python -u DeepSpeech.py --train_files data/train.csv --dev_files data/dev.csv --test_files data/test.csv --train_batch_size 64 --dev_batch_size 64 --test_batch_size 16 --n_hidden 2048 --epoch 100 --validation_step 1 --early_stop True --earlystop_nsteps 6 --estop_mean_thresh 0.1 --estop_std_thresh 0.1 --dropout_rate 0.2 --learning_rate 0.0001 --report_count 100 --use_seq_length False --export_dir data/results/model_export/ --checkpoint_dir data/results/checkout/ --decoder_library_path native_client/libctc_decoder_with_kenlm.so --alphabet_config_path data/alphabet.txt --lm_binary_path data/lm/newKST4.binary --lm_trie_path data/lm/trie
WARNING:tensorflow:From /home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:429: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    
WARNING:tensorflow:From /home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:358: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py:696: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I Restored variables from most recent checkpoint at data/results/checkout/train-8084, step 8085
I STARTING Optimization
Epoch 0 | Elapsed Time: 0:22:56 | Steps: 1453 | Loss: 18.195565                Traceback (most recent call last):
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Data too short when trying to read string
	 [[{{node DecodeWav}}]]
	 [[{{node tower_0/IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 833, in <module>
    tf.app.run(main)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 817, in main
    train()
  File "DeepSpeech.py", line 511, in train
    train_loss = run_set('train', train_init_op)
  File "DeepSpeech.py", line 482, in run_set
    feed_dict=feed_dict)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/kst/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Data too short when trying to read string
	 [[{{node DecodeWav}}]]
	 [[node tower_0/IteratorGetNext (defined at DeepSpeech.py:182) ]]

-----------------
I have checked my wav files and removed short wav files (by the size of wav files).
But error still exists.

Please help me..Thank you in advance

**Comment by andrenatal** [comment]
I'm having the same error.

**Comment by andrenatal** [comment]
I'm also hitting this issue when using my pt-br dataset, and I can confirm the data is pretty clean and validated.

**Comment by kdavis-mozilla** [comment]
What version of TensorFlow are you using?

Also,  using a virtual environment for training is supported, see [README](https://github.com/mozilla/DeepSpeech#training-your-own-model), while anaconda3 is not tested.

**Comment by andrenatal** [comment]
1.13.1

I think some of my files might be panicking TF here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/wav/wav_io.cc#L88, even though sox says it's good.  

Am saying that because I'm now running the same dataset on an slightly older version of deepspeech, and I'm hitting this issue in the preprocessing step (which doesn't occur in the box with the newer version but same dataset):

` File "/home/ubuntu/projects/DeepSpeech/util/preprocess.py", line 21, in process_single_file
    features = audiofile_to_input_vector(file.wav_filename, numcep, numcontext)
  File "/home/ubuntu/projects/DeepSpeech/util/audio.py", line 15, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/ubuntu/projects/tmp/venv/lib/python3.5/site-packages/scipy/io/wavfile.py", line 246, in read
    raise ValueError("Unexpected end of file.", filename)
ValueError: ('Unexpected end of file.', '/home/ubuntu/projects/corpora/ptbr/293456/audio.wav')`

I modified `wavfile.py` to print the offending file and am manually removing one by one to see if I at least I can get one epoch finished in this box with the older version. If it succeeds, I'll then try removing the same set of files from the corpus in the box with the newer version and retry.

This [test](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/kernels/spectrogram_test.cc) uses the function that is failing to generate the spectrogram, so I think I'll call it with each of the wav files to determine where it's breaking if the above method doesn't work.

**Comment by andrenatal** [comment]
Ok, I confirm that after removing the files that scipy's wavfile.py accused to be faulty, I managed to complete an epoch on both my boxes! 

So I think would be a good idea to figure why wavfile.py is not failing on the newer version since seems some other users are also having this issue.

**Comment by andrenatal** [comment]
I'd suggest the implementation of another verification like this [one](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/kernels/spectrogram_test.cc) in the preprocess step.

**Comment by SSaishruthi** [comment]
Facing the same issue when training using common voice English dataset. 
Any suggested solution ?

**Comment by SSaishruthi** [comment]
Hi @andrenatal @kst5118 
I am facing the same issue. Do you have any suggested solution?

**Comment by lissyx** [comment]
This is 99.99% likely a dataset issue. Nothing we can help on, please check you WAV files.

**Comment by andrenatal** [comment]
@lissyx really? It seems @SSaishruthi had issues with Common Voice data set which supposedly should be clean enough, and I also heard other people facing it with proprietary datasets.

**Comment by lissyx** [comment]
Maybe, but unless we get feedback it's hard to move on.

**Comment by andrenatal** [comment]
@reuben has a fix for it!

**Comment by reuben** [comment]
Here's what I've used to compare the header vs the filesystem file size:

```python
def compare_header_and_size(wav_filename):
    with wave.open(wav_filename, 'r') as fin:
        header_fsize = (fin.getnframes() * fin.getnchannels() * fin.getsampwidth()) + 44
    file_fsize = os.path.getsize(wav_filename)
    return header_fsize != file_fsize
```
