### ISSUE TITLE
Current master not showing progress bar and ETA

### ISSUE THREAD

**Issue by Kailegh** [mozilla/DeepSpeech#2049]
I have been using DeepSpeech for a month or so, today I have pull latest changes from the master branch. And now progress bar and estimated time are not being showed. I have these option by default, so progress bar should be shown.

```
    f.DEFINE_integer('log_level', 1, 'log level for console logs - 0: INFO, 1: WARN, 2: ERROR, 3: FATAL')
    f.DEFINE_boolean('show_progressbar', True, 'Show progress for training, validation and testing processes. Log level should be > 0.')
```
This is what I was getting until last week.

![image](https://user-images.githubusercontent.com/20105814/56079725-6f2cf280-5df8-11e9-8f84-da2fc73d5131.png)
 
And this is what I am getting now,
![image](https://user-images.githubusercontent.com/20105814/56080029-22e3b180-5dfc-11e9-8435-adf10ab9ffff.png)
 has this happened to anyone else?

**Comment by reuben** [comment]
Yes, this is expected. Due to the new tf.data input pipeline, we don't know the size of the dataset upfront, so there's no way to compute an ETA.

**Comment by Kailegh** [comment]
ok, perfect then, when you do updates like this, is there a note with the changes somewhere?
Thanks a lot!

**Comment by reuben** [comment]
We try to include notable changes with the release notes when we do a release. We haven't done any releases since that change landed, so it's not listed anywhere yet. It's an unfortunate side effect if you're tracking master, you gotta keep an eye on the commit log!
