### ISSUE TITLE
make deepspeech: cannot find -ldeepspeech

### ISSUE THREAD

**Issue by rimidalv** [mozilla/DeepSpeech#2051]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: source code
git checkout origin/r1.13
- **TensorFlow version (use command below)**: 
b'v1.13.1-10-g3e0cc5374d' 1.13.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.21.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- **CUDA/cuDNN version**: 10.0/7
- **GPU model and memory**: 
Four video card with same configuration:
       description: VGA compatible controller
       product: GP106 [GeForce GTX 1060 3GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:05:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0

- **Exact command to reproduce**:
~/Projects/ML/DeepSpeech/native_client$ make deepspeech 
c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/rimidalv/Projects/ML/tensorflow/bazel-bin/native_client  -ldeepspeech  `pkg-config --libs sox`
/usr/bin/ld: cannot find -ldeepspeech
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
I tried with: $ pip install deepspeech-gpu
Requirement already satisfied: deepspeech-gpu in ./anaconda3/envs/deep/lib/python3.6/site-packages (0.4.1)
Requirement already satisfied: numpy>=1.7.0 in ./anaconda3/envs/deep/lib/python3.6/site-packages (from deepspeech-gpu) (1.15.4)

**Comment by reuben** [comment]
You have to set the TFDIR variable as documented: https://github.com/mozilla/DeepSpeech/tree/master/native_client/#compile-language-bindings

**Comment by rimidalv** [comment]
> You have to set the TFDIR variable as documented: https://github.com/mozilla/DeepSpeech/tree/master/native_client/#compile-language-bindings

I have already had TFDIR:
(deep) rimidalv@rimidalv-desktop:~/tensorflow/native_client$ $TFDIR
bash: /home/rimidalv/tensorflow: Is a directory
(deep) rimidalv@rimidalv-desktop:~/tensorflow/native_client$ make deepspeech 
c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/rimidalv/Projects/ML/tensorflow/bazel-bin/native_client  -ldeepspeech  `pkg-config --libs sox`
/usr/bin/ld: cannot find -ldeepspeech
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1
(deep) rimidalv@rimidalv-desktop:~/tensorflow/native_client$

**Comment by reuben** [comment]
The Makefile will look for libdeepspeech.so inside $TFDIR/bazel-bin/native_client. If that file is not there, it means something went wrong with your libdeepspeech.so build, so double check there.

**Comment by rimidalv** [comment]
(deep) rimidalv@rimidalv-desktop:~/tensorflow/bazel-bin/native_client$ ls
generate_trie                    ldeepspeech.so.runfiles_manifest
generate_trie-2.params           libdeepspeech.so
generate_trie.runfiles           libdeepspeech.so-2.params
generate_trie.runfiles_manifest  libdeepspeech.so.runfiles
ldeepspeech.so                   libdeepspeech.so.runfiles_manifest
ldeepspeech.so-2.params          _objs

**Comment by reuben** [comment]
I think something is wrong with the way you're setting the TFDIR variable. In your shell it points to /home/rimidalv/tensorflow, but in the error it points to /home/rimidalv/Projects/ML/tensorflow.

**Comment by rimidalv** [comment]
Very strange. 
I cloned the project to users home folder and now all works good.
