### ISSUE TITLE
lm::FormatLoadException after training models with CommonVoice dataset

### ISSUE THREAD

**Issue by EmpRamses** [mozilla/DeepSpeech#2052]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**: 3.6.8
- **CUDA/cuDNN version**: CUDA 10.0 cuDNN 7.4.1
- **GPU model and memory**: 12GB

I have tried from scratch and tried from v0.4.1 model. In both situation, I got the same exception.

> Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100

> terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  ../kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43
Aborted

**Comment by kdavis-mozilla** [comment]
As documented [here](https://github.com/mozilla/deepspeech#getting-the-code) you need to use Git Large File Storage to check out the code.
