### ISSUE TITLE
Getting probabilities / confidence level of DeepSpeech output

### ISSUE THREAD

**Issue by polars05** [mozilla/DeepSpeech#2053]
Noticed that the .cc and .h files returns some sort of probability / confidence level of the predictions from DeepSpeech: https://github.com/mozilla/DeepSpeech/commit/89ed0f47f0ffa8dead21adf78388de6d33abd2e3

- What is this probability (e.g. average of the probabilities for each character, inclusive of blanks)?
- How can this probability be obtained when running DeepSpeech in Python?

Thanks!

**Comment by kdavis-mozilla** [comment]
* The entire transcript probability
* Python access is in the process of being exposed in PR #2022 which addresses issue #2006

**Comment by reuben** [comment]
The probability field is a log probability of the entire transcription according to CTC only, with LM scoring removed. Its value should probably not be interpreted directly, but rather be used only when comparing two transcriptions given by the same model/LM setup.
