### ISSUE TITLE
ffmpeg_vad_streaming undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv

### ISSUE THREAD

**Issue by CP-4** [mozilla/DeepSpeech#2056]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream TensorFlow
- **TensorFlow version (use command below)**: 1.12.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
`node index.js --model '/path/to/models/output_graph.pbmm' --alphabet '/path/to/models/alphabet.txt' --audio '/path/to/audio/benchmark.wav'
`

**Bug**

ffmpeg_vad_streaming produces the following error after some transcriptions.

Error:
`node: symbol lookup error: /path/to/DeepSpeech/examples/ffmpeg_vad_streaming/node_modules/deepspeech/lib/binding/v0.4.1/linux-x64/node-v57/deepspeech.node: undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv`

Audio File:
[benchmark.zip](https://github.com/mozilla/DeepSpeech/files/3083343/benchmark.zip)

**Comment by kdavis-mozilla** [comment]
What happens if you upgrade node to 8.12 or later?

It looks like you are on 5.7, which should work. But there might be a bug in node below 8.12.

**Comment by lissyx** [comment]
Please use official node release

**Comment by CP-4** [comment]
> What happens if you upgrade node to 8.12 or later?

I tried upgrading to current LTS version 10.x and 8.x from PPA, which produces the following message:

``` Your distribution, identified as "bionic", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support```

> It looks like you are on 5.7, which should work. But there might be a bug in node below 8.12.

```
$nodejs -v
v8.10.0
```
Is there any other way to upgrade to v8.12 or above?

**Comment by kdavis-mozilla** [comment]
What about trying [this](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04).

**Comment by CP-4** [comment]
@lissyx I am currently on nodejs v8.10.0 which i installed from ubuntu repos. I tried installing from nodesource PPA but it shows 'not currently supported'

The ffmpeg_vad_streaming runs for some time producing a couple of transcripts before giving the error.
Also, the result is poor (signigicant amount of text is lost) compared to mic_vad_streaming

**Comment by CP-4** [comment]
@kdavis-mozilla I tried that article, except for the install using NVM part. I'll try updating nodejs using NVM if you think that might be responsible for the error. I'll update once it's done.

**Comment by lissyx** [comment]
Unfortunately you are not the first one, I don't know what they do on the Ubuntu package.

**Comment by lissyx** [comment]
We have 8.x installed on 16.04 from nodesource. There's no way you can't get it on bionic...

**Comment by lissyx** [comment]
Don't use ppa just use their packages

**Comment by lissyx** [comment]
https://github.com/nodesource/distributions/blob/master/README.md#deb

**Comment by CP-4** [comment]
> https://github.com/nodesource/distributions/blob/master/README.md#deb

updated nodejs to v10.15.3. Seems to be working fine now. Followed the above installation process.
A lot of text is lost. Seems like some audio is lost while previous inferencing is under process.

**Comment by lissyx** [comment]
> A lot of text is lost. Seems like some audio is lost while previous inferencing is under process.

That's another story, it's possible there are bugs in the code, it's an example usage.
