### ISSUE TITLE
android application build error

### ISSUE THREAD

**Issue by atrah22** [mozilla/DeepSpeech#2057]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**:  3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

Android studio build java 

CMake Error at /home/atul/git_work/Models/pretrained_models/deepspeech/DeepSpeechv0.5/native_client/java/libdeepspeech/CMakeLists.txt:13 (add_library):
  Cannot find source file:

    ../jni/deepspeech_wrap.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: deepspeech-jni
Failed to compute build system.

I could run using the adb shell command but however, cannot build apk inside native_client/java directory.

**Comment by lissyx** [comment]
Please use the documented build steps. It's likely you miss generating the wrapper with swig...

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/tree/master/native_client/java#android-demo-apk

**Comment by atrah22** [comment]
@lissyx, I tried to make the AAR package following the title "Anroid Java / JNI bindings: libdeepspeech"
and used the following command.
./gradlew libdeepspeech:build

However, there is build error like below:
/DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1510: error: undefined reference to 'DS_FreeString(char*)'
  /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1585: error: undefined reference to 'DS_FreeString(char*)'
  /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1600: error: undefined reference to 'DS_FreeString(char*)'
  /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1650: error: undefined reference to 'DS_FreeString(char*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by lissyx** [comment]
> @lissyx, I tried to make the AAR package following the title "Anroid Java / JNI bindings: libdeepspeech"
> and used the following command.
> ./gradlew libdeepspeech:build
> 
> However, there is build error like below:
> /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1510: error: undefined reference to 'DS_FreeString(char*)'
> /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1585: error: undefined reference to 'DS_FreeString(char*)'
> /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1600: error: undefined reference to 'DS_FreeString(char*)'
> /DeepSpeechv0.5/native_client/java/jni/deepspeech_wrap.cpp:1650: error: undefined reference to 'DS_FreeString(char*)'
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.

Means you don't have the matching `libdeepspeech.so` with `DS_FreeString` symbol. Why do you need to rebuild yourself ?

https://bintray.com/alissy/org.mozilla.deepspeech/libdeepspeech/0.5.0-alpha.5

**Comment by atrah22** [comment]
@lissyx ,


Yes, Now I can run the apk. Thankyou.

However, the decoded text message is not shown on apk. Only the inference time is shown. I have seen the similar issue while running with adb-shell command.

Also, when i try to compile libdeepspeech.so for android-arm64 from source, i get compile error regarding ctddecode.

**Comment by lissyx** [comment]
The apk should work, it's tested but it's only here as a demo ... Regarding your build error please make sure you correctly follow the steps. Also why do you not use pre-built binaries?

**Comment by atrah22** [comment]
@lissyx , I want to profile the inference time in more detail for each run. So I need to compile libdeepspeech.so from source after making the necessary changes in /native_client/deepspeech.cc
