### ISSUE TITLE
HOW can I run the evaluation coding to get word error rate(WER)

### ISSUE THREAD

**Issue by JacobXing** [mozilla/DeepSpeech#2059]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by kdavis-mozilla** [comment]
You can use [evaluate.py](https://github.com/mozilla/DeepSpeech/blob/master/evaluate.py)

**Comment by JacobXing** [comment]
what command do I need to write?

**Comment by JacobXing** [comment]
> You can use [evaluate.py](https://github.com/mozilla/DeepSpeech/blob/master/evaluate.py)

what command do I need to write?

**Comment by kdavis-mozilla** [comment]
Use the ``--help`` flag to find the arguments.

**Comment by JacobXing** [comment]
[image: Capture.PNG]
I didn't find the evaluation options here

Kelly Davis <notifications@github.com> 于2019年4月17日周三 下午9:46写道：

**Comment by reuben** [comment]
Please use the Discourse forums for support and discussions.

**Comment by JacobXing** [comment]
After I type ~$ deepspeech --help

It shows optional arguments:

> -h,-- help      show this help message and exit
> -- model MODEL path to the model(protocol buffer binary file)
> -- alphabet ALPHABET Path to the configuration file specifying the alphabet used by the network
> --lm [LM]  Path to the language model binary file
> --trie[TRIE]   Path to the language model trie file created with native_client/generate_trie
> --audio AUDIO  PAth to the audio file to run (WAV format)
> --version  Print version and exits

I don't know which command do I need to type

**Comment by lissyx** [comment]
> ~$ deepspeech --help

try: `python evaluate.py --help`
