### ISSUE TITLE
Deepspeech v0.5.0-alpha.5: pre-built binary doesn't show output result

### ISSUE THREAD

**Issue by atrah22** [mozilla/DeepSpeech#2062]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:  mozilla build (1.13)
- **TensorFlow version (use command below)**: 1.13.0
- **Python version**: 3.6.7
- **Bazel version (if compiling from source)**: 0.19.1
- **GCC/Compiler version (if compiling from source)**:  5.4.0
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

The output of deepspeech binary doesn;t show the output text string but only reports the cpu/inference time.

I downloaded pre-built binary "deepspeech" from the link https://github.com/mozilla/DeepSpeech/releases  for amd64.cpu.linux.

I converted the pre-trained output_graph.pb model from deepspeech v0.4.1 to deepspeech v0.5.0a5  using the following command ("DeepSpeeech.py from v0.5.0a5):
```
python3.6 DeepSpeech.py --checkpoint_dir ./checkpoints --notrain --notest --export_dir ./models
```
when i run the following command, I see the inference time but not the output text result.
```
./deepspeech --model models/output_graph.pb --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio models/my_wav.wav -t
```
The output is:
```
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.0-alpha.5-0-g15adf00
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2019-04-19 13:31:27.726562: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-04-19 13:31:27.726745: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-04-19 13:31:27.726765: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-04-19 13:31:27.726871: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant

cpu_time_overall=1.87525
```

** Secondly, I also tried with the pip deepspeech (v0.5.0a5) and the result is same and the output is:
```
Loaded model in 0.0932s.
Loading language model from files models/lm.binary models/trie
Loaded language model in 0.192s.
Running inference.

Inference took 1.681s for 0.929s audio file.
```

Still no output string is shown. It is empty!

**Thirdly, I build deepspeech and libdeepspeech.so from source and the output is same.

**Comment by lissyx** [comment]
Prebuilt binaries are working as intended, your model re-export is wrong, there was some variables changes and it's expected not to work from 0.4.1 checkpoints.

**Comment by lissyx** [comment]
cc @reuben

**Comment by vinnitu** [comment]
can you share pretrained model for 0.5.0?

**Comment by kdavis-mozilla** [comment]
@vinnitu When it's ready we will share it.

**Comment by 20richardh** [comment]
Any idea when it will come out? Or will 0.4.1 be the latest one for the next few weeks?

**Comment by atrah22** [comment]
@20richardh , I am using 0.5.0 a4 and it is compatible with 0.4.1.

**Comment by 20richardh** [comment]
Cool! I'll try that out and see what happens then. So it's also compatible with deepspeech-0.4.1-models.tar.gz (that pre-built binary)?

**Comment by atrah22** [comment]
@20richardh , You can download the pre-build binary for 0.5.0 a4. You can run the pre-trained model of 0.4.1 with 0.5.0 a4 binary.

**Comment by 20richardh** [comment]
Sorry, one last thing. Where can I find the aforementioned binary?

**Comment by atrah22** [comment]
https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.0-alpha.4

**Comment by 20richardh** [comment]
OH ok I got it now. Was looking for the wrong thing. Thanks!

**Comment by GuntaButya** [comment]
Any update on this?

Thanks AWESOME Work! Thanks for sharing!

**Comment by lissyx** [comment]
> Any update on this? A pre-trained model compatible for at least 0.5.0a5 or greater?

We're getting closer, it should happen soon now.
