### ISSUE TITLE
Include a telephone only trained model in release for transfer learning

### ISSUE THREAD

**Issue by rhamnett** [mozilla/DeepSpeech#2063]
Hello, would it be useful to include a model which has been trained only on low quality 8khz telephony speech data from switchboard/fischer rather than the high fidelity speech as well? I expect there are many people trying to do transfer learning for telephony only recognition. 

Please add a thumbs up to this issue if this applies to you.

**Comment by reuben** [comment]
Please use the [Discourse forums](https://discourse.mozilla.org/c/deep-speech) for this, as documented in the issue template.
