### ISSUE TITLE
Detect English & Urdu using Transfer Learning

### ISSUE THREAD

**Issue by AmeerHamzaRiaz** [mozilla/DeepSpeech#2066]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**: 3.6

Hello, I'm trying to detect both English and Roman Urdu Language. (Both have same alphabet characters). 
I have followed [this comment](https://discourse.mozilla.org/t/transfer-learning-by-training-only-the-last-few-layers/33383/5) on discourse. And generated lm.binary and trie. Downloaded the checkpoints from [here](https://github.com/mozilla/DeepSpeech/releases/download/v0.4.1/deepspeech-0.4.1-checkpoint.tar.gz) .

Now I'm clueless how & which layers to drop and how to proceed further due to lack of documentation about transfer learning.

Need a nudge in the right direction.

**Comment by JRMeyer** [comment]
This is a Discourse-appropriate comment... I'll reply there:)
