### ISSUE TITLE
make new lm.binary

### ISSUE THREAD

**Issue by Giles754128704** [mozilla/DeepSpeech#2069]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 18
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:pip3
- **TensorFlow version (use command below)**:1.13.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce

I made a new lm.txt rather than download the lm.binary from website,how can I use my new lm.txt or how can I transfer txt to binary

**Comment by kdavis-mozilla** [comment]
Issues are for bugs and/or feature requests. For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).
