### ISSUE TITLE
noise problem

### ISSUE THREAD

**Issue by mduzgun** [mozilla/DeepSpeech#2077]
I installed Deep Speech 0.4.1 in linux machine.
I use pretrained data as deepspeech-0.4.1-models.tar.gz. 
When audio data that is unless background noise is used, results are successful. But in office, when I create audio file using microphone and use it , results are failing. 
Google Api's results are succesful for noisy audio data.
How to make noise reduction of audio data for deepspeech? Is there anyone for help this issue?

**Comment by kdavis-mozilla** [comment]
Currently there are no plans to add a noise reduction component to Deep Speech. However, we are planning to train the upcoming [0.6.0](https://github.com/mozilla/DeepSpeech/projects) release with background noise which should address this problem.

**Comment by Hafsa26** [comment]
@kdavis, and what about if numbers are in data, would It increase WER? 
I am working on Urdu language which is RTL, while, numers are LTR. 
I checked by adding numbers in data, training goes fine but I am specifically asking for effect on WER?

**Comment by kdavis-mozilla** [comment]
By "numbers" do you mean digits "1,2,3,4..." or do you mean their textural form "one, two, three, four..."?

How are the numbers read aloud in Urdu? If I read the text "three two one" do I say it verbally as "one two three"? In other words how do RTL and LTR interact for numbers in Urdu?

**Comment by Hafsa26** [comment]
Digits.

**Comment by Hafsa26** [comment]
Lets suppose in English Transcription, if there are digits too. Would it
increase WER?

**Comment by kdavis-mozilla** [comment]
Can we move this to [Discourse](https://discourse.mozilla.org/c/deep-speech) as this becoming more of a discussion than an issue, ie a bug or feature request which we reserve issue for.
