### ISSUE TITLE
How Can I use the deepspeech to evaluate on my own Dataset

### ISSUE THREAD

**Issue by JacobXing** [mozilla/DeepSpeech#2078]
I want to use deepspeech  to recognize all of the WAV files from UNCLASS dataset and evaluate it. How can I do that? 
 **

> deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio_file.wav

**
If I type this command, I will generate the result from only one WAV file. How can I generate results from more than one file?

**Comment by lissyx** [comment]
Those questions should be posted on discourse. I don't know what is UNCLASS. For handling more than one file please look at discourse others already shared solutions.
