### ISSUE TITLE
Not found: Op type not registered 'AudioSpectrogram' in binary running on deep

### ISSUE THREAD

**Issue by gianlucaT1989** [mozilla/DeepSpeech#2082]
Hi to all,

SYSTEM:
1) Linux deep 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
2)Ubuntu 18.04.2 LTS
3) Python 3.6.7
4) **TensorFlow: 1.13.1**

5) deepspeech --version
**TensorFlow:** v1.12.0-10-ge232881 **((((??????? why not match????)))**
DeepSpeech: v0.4.1-0-g0e40db6

from italian dataset i have generated a pb >> pbmm
but when i load the model i have this error:

`(deepspeech-venv) root@deep:/home/DeepSpeech/models# deepspeech --model output_graph.pbmm --audio test.wav --alphabet alphabet.txt`

```
Loading model from file output_graph.pbmm
TensorFlow: v1.12.0-10-ge232881
DeepSpeech: v0.4.1-0-g0e40db6
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2019-04-29 10:31:23.380831: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: Op type not registered 'AudioSpectrogram' in binary running on deep. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "/root/tmp/deepspeech-venv/bin/deepspeech", line 10, in <module>
    sys.exit(main())
  File "/root/tmp/deepspeech-venv/lib/python3.6/site-packages/deepspeech/client.py", line 80, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/root/tmp/deepspeech-venv/lib/python3.6/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5
```

`Not found: Op type not registered 'AudioSpectrogram' in binary running on deep. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

**Comment by lissyx** [comment]
>     4\. **TensorFlow:** v1.12.0-10-ge232881 **((((??????? why not match????)))**

As Reuben said, that's your issue. We can't explain since you don't provide your installation steps. Please use `0.5.0-alpha.6` or above prebuilt binaries.

**Comment by YasineNifa** [comment]
Hello, 
I have the same error as @gianlucaT1989.
I do this command to change the version of the deepspeech-gpu : pip install --upgrade deepspeech-gpu==0.5.0a7 and 0.5.0a6 but it does not work in both case. It gives me this error : 
`deepspeech --model output_graph.pbmm --alphabet DeepSpeech/data/alphabet.txt  --audio my_audio_file.wav`
bash: /home/innovation/.local/bin/deepspeech: Aucun fichier ou dossier de ce type

**Comment by lissyx** [comment]
>  bash: /home/innovation/.local/bin/deepspeech: Aucun fichier ou dossier de ce type

Please verify your virtualenv setup and re-do one from scratch, it's not able to find your `deepspeech` install

**Comment by YasineNifa** [comment]
Thank you for the quick answer.
When I install deepspeech-gpu using this cmd : pip3 install deepspeech-gpu 
And I run the command : 

`deepspeech --model output_graph.pbmm --alphabet DeepSpeech/data/alphabet.txt --audio my_audio_file.wav`

I get this error : 
```
Not found: Op type not registered 'AudioSpectrogram' in binary running on MSI-GAMING. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
RuntimeError: CreateModel failed with error code 5
```

**Comment by kdavis-mozilla** [comment]
Is the model you are using our 0.4.1 model? If so, it's not compatible with 0.5.0a7.

You need to train a new model using the 0.5.0a7 code or revert the install to to 0.4.1.

**Comment by YasineNifa** [comment]
this cmd :  `deepspeech --version`
 give me this output : 
```
TensorFlow: v1.12.0-10-ge232881
DeepSpeech: v0.4.1-0-g0e40db6
```
And I use the master model from `https://github.com/mozilla/DeepSpeech` for training

**Comment by kdavis-mozilla** [comment]
So you are using a newer model, trained using master, with an older command line tool, 0.4.1. They are not compatible.

You need to, as lissyx suggested above, create a new virtualenv and install the newest deep speech
```bash
pip install --upgrade deepspeech-gpu==0.5.0a8
```
in this new virtualenv.

**Comment by YasineNifa** [comment]
it gives me this error :` ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory`
I think it is a problem with the CUDA version
I have the 9.0 version and it requires the 10.0 version . Am I right ?

**Comment by lissyx** [comment]
>  I have the 9.0 version and it requires the 10.0 version . Am I right ?

Yes, we are based on TensorFlow r1.13 which depends on CUDA 10.0

**Comment by YasineNifa** [comment]
ok thank you,
Can you please provide me with a tutorial to install cuda 10.0 because every time I follow a tutorial to install cuda 10.0 I finish by installing cuda 10.1

**Comment by reuben** [comment]
Docs: https://docs.nvidia.com/cuda/archive/10.0/
Downloads: https://developer.nvidia.com/cuda-10.0-download-archive

**Comment by YasineNifa** [comment]
Thank you so much @reuben

**Comment by YasineNifa** [comment]
Hello again !!
Please what are the default values of the MOZILLA model's parameters
