### ISSUE TITLE
Remove checkpoint at epoch 0

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#209]
If `epoch = 0` the `if` of following code is successful for any reasonable `checkpoint_step`
```python
        # Checkpoint the model
        if (epoch % checkpoint_step == 0) or (epoch == training_iters - 1):
            checkpoint_path = os.path.join(checkpoint_dir, 'model.ckpt')
            print "Checkpointing in directory", "%s" % checkpoint_dir
            saver.save(session, checkpoint_path, global_step=epoch)
            print
```
Thus the model checkpoints at `epoch = 0`.

However, a checkpoint at `epoch = 0` is basically of no use, as the model has only seen one epoch. Thus no checkpoint should occur at `epoch = 0`.

**Comment by Cwiiis** [comment]
Fixed by #212
