### ISSUE TITLE
Error when calling libctc_decoder_with_kenlm.so after generating it

### ISSUE THREAD

**Issue by Scofield666** [mozilla/DeepSpeech#2101]
I have been trying to use deepspeech version0.3.0, and i only need `libctc_decoder_with_kenlm.so` loaded, code calling the library is below:
`module = tf.load_op_library("../DeepSpeech/native_client/libctc_decoder_with_kenlm.so")`

So I Build DeepSpeech Binaries following the instructions listed in [https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md](url) 

The envs are:
Tensorflow: 1.11 (git checkout origin/r1.11)
Bazel: 0.15.0
cuda: 9.0
cudnn: 7.5

After I configure tensorflow and build with bazel successfully with the command
`bazel build --config=cuda -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie //native_client:libctc_decoder_with_kenlm.so`
In `/usr/xjc/tensorflow/bazel-bin/native_client` I got `libctc_decoder_with_kenlm.so`, then i copied this to my `../DeepSpeech/native_client/` path for calling, but it still went wrong

`AttributeError: 'str' object has no attribute 'ctc_beam_search_decoder_with_lm'` means this library failed to be loaded.

Does this need to be done after `make deepspeech`? I didn't make deepspeech successfully, because i don't have libtensorflow.so in `bazel-bin/tensorflow/`. Looking for someone to help me out!

**Comment by kdavis-mozilla** [comment]
What about using the method documented in the [0.3.0 README.md](https://github.com/mozilla/DeepSpeech/blob/v0.3.0/README.md)?

**Comment by Scofield666** [comment]
> What about using the method documented in the [0.3.0 README.md](https://github.com/mozilla/DeepSpeech/blob/v0.3.0/README.md)?

Actually, My problem lies in 
I could successfully generate the libctc_decoder_with_kenlm.so after bazel build command, but something went wrong in my code calling this library.
`ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.` 
So it seems that i need to do something with the path instead of copying libctc_decoder_with_kenlm.so?

**Comment by kdavis-mozilla** [comment]
The [0.3.0 documents](https://github.com/mozilla/DeepSpeech/tree/v0.3.0/native_client#building) indicate to build libctc_decoder_with_kenlm.so differently from the way you built it. They suggest...
```bash
bazel build -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" //native_client:libctc_decoder_with_kenlm.so
```

**Comment by kdavis-mozilla** [comment]
Odd, looks like errors you'd see if you were using a newer version of TF with an older bazel.

Is TF really the 1.11 version of Mozilla's fork and is bazel really 0.15.0?

**Comment by Scofield666** [comment]
> Odd, looks like errors you'd see if you were using a newer version of TF with an older bazel.
> 
> Is TF really the 1.11 version of Mozilla's fork and is bazel really 0.15.0?

bazel is exactly 0.15.0
I am not sure if TF is 1.11 because I visited [https://github.com/mozilla/tensorflow/tree/r1.11](url) and cloned it with `git clone https://github.com/mozilla/tensorflow.git`, but it seems that this URL refers to the newest version? BTW, how can I clone the r1.11 version, maybe I should `git checkout origin/r1.11`?

**Comment by kdavis-mozilla** [comment]
Looks like you do have a newer version of tensorflow. Try...
```bash
kdavis-19htdh:mozilla kdavis$ git clone https://github.com/mozilla/tensorflow.git
Cloning into 'tensorflow'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 549136 (delta 0), reused 1 (delta 0), pack-reused 549132
Receiving objects: 100% (549136/549136), 322.00 MiB | 263.00 KiB/s, done.
Resolving deltas: 100% (443183/443183), done.
Checking out files: 100% (16472/16472), done.
kdavis-19htdh:mozilla kdavis$ cd tensorflow/
kdavis-19htdh:tensorflow kdavis$ git checkout r1.11
Checking out files: 100% (12549/12549), done.
Branch 'r1.11' set up to track remote branch 'r1.11' from 'origin'.
Switched to a new branch 'r1.11'
```

**Comment by Scofield666** [comment]
> Looks like you do have a newer version of tensorflow. Try...
> 
> ```shell
> kdavis-19htdh:mozilla kdavis$ git clone https://github.com/mozilla/tensorflow.git
> Cloning into 'tensorflow'...
> remote: Enumerating objects: 4, done.
> remote: Counting objects: 100% (4/4), done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 549136 (delta 0), reused 1 (delta 0), pack-reused 549132
> Receiving objects: 100% (549136/549136), 322.00 MiB | 263.00 KiB/s, done.
> Resolving deltas: 100% (443183/443183), done.
> Checking out files: 100% (16472/16472), done.
> kdavis-19htdh:mozilla kdavis$ cd tensorflow/
> kdavis-19htdh:tensorflow kdavis$ git checkout r1.11
> Checking out files: 100% (12549/12549), done.
> Branch 'r1.11' set up to track remote branch 'r1.11' from 'origin'.
> Switched to a new branch 'r1.11'
> ```

Yes, I have checked out the right version and successfully generating the binaries using the command
```
bazel build -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" //native_client:libctc_decoder_with_kenlm.so
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
```
Then My file structure looks like this, implying that I have generated libctc_decoder_with_kenlm.so successfully.
```
ww@Jenny's Group /usr/whz/generative_audio_attack/tensorflow/bazel-bin/native_client $ tree -L 1
.
├── generate_trie
├── generate_trie-2.params
├── generate_trie.runfiles
├── generate_trie.runfiles_manifest
├── libctc_decoder_with_kenlm.so
├── libctc_decoder_with_kenlm.so-2.params
├── libctc_decoder_with_kenlm.so.runfiles
├── libctc_decoder_with_kenlm.so.runfiles_manifest
├── libdeepspeech.so
├── libdeepspeech.so-2.params
├── libdeepspeech.so.runfiles
├── libdeepspeech.so.runfiles_manifest
└── _objs

```
So here my problem is when I generated libctc_decoder_with_kenlm.so, can I directly copy this to the path for calling it using the code like `module = tf.load_op_library("../DeepSpeech/native_client/libctc_decoder_with_kenlm.so")`?

And after 
```
export TFDIR=/usr/whz/generative_audio_attack/tensorflow/
cd ../DeepSpeech/native_client
make deepspeech
```
Something went wrong like
```
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::shape_inference::InferenceContext::Multiply(tensorflow::shape_inference::DimensionHandle, tensorflow::shape_inference::DimensionOrConstant, tensorflow::shape_inference::DimensionHandle*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::monitoring::CollectionRegistry::Register(tensorflow::monitoring::AbstractMetricDef const*, std::function<void (tensorflow::monitoring::MetricCollectorGetter)> const&)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::CancellationManager::~CancellationManager()'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::shape_inference::InferenceContext::FullyDefined(tensorflow::shape_inference::ShapeHandle)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::thread::ThreadPool::~ThreadPool()'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::OpKernelContext::mutable_input(int, bool)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::AsProtoField(tensorflow::TensorProto*) const'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Env::NewReadOnlyMemoryRegionFromFile(std::string const&, std::unique_ptr<tensorflow::ReadOnlyMemoryRegion, std::default_delete<tensorflow::ReadOnlyMemoryRegion> >*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ResourceMgr::DoLookup(std::string const&, std::type_index, std::string const&, tensorflow::ResourceBase**) const'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::OpDefBuilder::SetShapeFn(tensorflow::Status (*)(tensorflow::shape_inference::InferenceContext*))'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphRunner::GraphRunner(tensorflow::Env*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::OpInfo_TensorProperties::~OpInfo_TensorProperties()'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::FunctionLibraryDefinition::ReplaceFunction(std::string const&, tensorflow::FunctionDef const&)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `vtable for tensorflow::DeviceResolverLocal'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::io::internal::JoinPathImpl(std::initializer_list<absl::string_view>)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::FormatFromString(std::string const&, tensorflow::TensorFormat*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::CallableOptions::CallableOptions()'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::FunctionDef* google::protobuf::Arena::CreateMaybeMessage<tensorflow::FunctionDef>(google::protobuf::Arena*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `stream_executor::Stream::ThenPoolForward(stream_executor::dnn::PoolingDescriptor const&, stream_executor::dnn::BatchDescriptor const&, stream_executor::DeviceMemory<float> const&, stream_executor::dnn::BatchDescriptor const&, stream_executor::DeviceMemory<float>*, stream_executor::ScratchAllocator*)'
/usr/whz/generative_audio_attack/tensorflow//bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Rendezvous::Recv(tensorflow::Rendezvous::ParsedKey const&, tensorflow::Rendezvous::Args const&, tensorflow::Tensor*, bool*, long long)'
collect2: error: ld returned 1 exit status
make: *** [deepspeech] Error 1
```

I don't know how to solve it, any help? Thanks

**Comment by kdavis-mozilla** [comment]
What version of gcc are you using?

**Comment by Scofield666** [comment]
> What version of gcc are you using?

version 5.4.0 
```
ww@Jenny's Group /usr/xjc/tensorflow/bazel-bin/native_client $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-5.4.0/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 5.4.0 (GCC) 
```

Is this related to the makefile error?

**Comment by kdavis-mozilla** [comment]
Makefile error? The above [problem](https://github.com/mozilla/DeepSpeech/issues/2101#issuecomment-490309780) is a linking error. Is there some other problem?

**Comment by Scofield666** [comment]
The error above occurs when `make deepspeech`. 
The main problem I am confused with now is that I still cannot use function `tf.load_library` to load `libctc_decoder_with_kenlm.so` even after I moved the generated library to the current native-client folder. The error is 
```
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
```
According to the error info, it looks like it cannot load the `native-client` folder, but it actually exists with generated binaries in it. 
I don't know whether the generated library is right or not, or there is something wrong with the path. Really confusing.

**Comment by kdavis-mozilla** [comment]
> The error above occurs when `make deepspeech`.

Yes but the error indicates it's a a linking problem. There are undefined symbols.

> The main problem I am confused with now is that I still cannot use function `tf.load_library` to load `libctc_decoder_with_kenlm.so` even after I moved the generated library to the current native-client folder. 

Before we try something off the beaten path I'd suggest getting the standard case of `make deepspeech` working.

What if you rm your tensorflow checkout, check 1.11 out again, and start fresh to make sure there are no artifacts from your old build with the wrong version of tensorflow?

**Comment by lissyx** [comment]
@Scofield666 What's the rationale for you to rebuild ?

**Comment by lissyx** [comment]
`libctc_decoder_wtih_kenlm.so` is in https://github.com/mozilla/DeepSpeech/releases/download/v0.3.0/native_client.amd64.cpu.linux.tar.xz

**Comment by lissyx** [comment]
Maybe just use the nuclear option:
```
$ strace -ff python -c "import tensorflow as tf; module = tf.load_op_library("../DeepSpeech/native_client/libctc_decoder_with_kenlm.so")" 2>&1 | grep "libctc_decoder_with_kenlm"
```

And then look where it tries to load the library?

**Comment by lissyx** [comment]
> What if you rm your tensorflow checkout, check 1.11 out again, and start fresh to make sure there are no artifacts from your old build with the wrong version of tensorflow?

You may also want to ensure the bazel cache is properly cleaned.

**Comment by Scofield666** [comment]
Now I think something might go wrong with the tensorflow configuration. I follow the instructions in [https://www.tensorflow.org/install/source](url) and I just stop after `./configure` without compiling pip packages. So I wonder if it is necessary to build the pip packages until the `Success: TensorFlow is now installed.`

**Comment by Scofield666** [comment]
```
(deepspeechv3) ww@Jenny's Group /usr/whz/generative_audio_attack/DeepSpeech/native_client $ make deepspeech 
c++ -std=c++11 -o deepspeech   `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/usr/whz/generative_audio_attack/tensorflow/bazel-bin/native_client  -ldeepspeech  `pkg-config --libs sox
```
Does this mean `make deepspeech` successfully?

**Comment by lissyx** [comment]
>  I follow the instructions in [https://www.tensorflow.org/install/source](url) and I just stop after `./configure` without compiling pip packages.

Nope, that's what you should be doing, no need to build pip package.

> Does this mean `make deepspeech` successfully?

If you don't have any other output, and your have a `deepspeech` binary in your folder, then yes.

**Comment by Scofield666** [comment]
Thanks for your reply. 
I am still confused with an issue when I saw problems discussed on [https://github.com/mozilla/DeepSpeech/issues/1418](url). This issue makes me wonder is there any need for me to configure the LD_LIBRARY_PATH or ld.so.conf so that I can moved libctc_decoder_with_kenlm.so anywhere for other use?

**Comment by lissyx** [comment]
This is unrealted. Please follow the doc if you have `libctc_decoder_with_kenlm.so` in a non-standard path and set the `--decoder_path` flag at training time ...

**Comment by Scofield666** [comment]
When I am trying to use load_op_library function to load this library like `a = tf.load_op_library("/usr/whz/generative_audio_attack/DeepSpeech/native_client/libctc_decoder_with_kenlm.so")` in python console, with tensorflow 12.0. It went wrong

```
Traceback (most recent call last):
  File "/home/ww/anaconda3/envs/speech/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-a4a3e007e0ff>", line 1, in <module>
    a = tf.load_op_library("/usr/whz/generative_audio_attack/DeepSpeech/native_client/libctc_decoder_with_kenlm.so")
  File "/home/ww/anaconda3/envs/speech/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/whz/generative_audio_attack/DeepSpeech/native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```
What does this mean? I'm sure that the libctc_decoder_with_kenlm.so has been moved to the right path, but it still failed to load. Why?

**Comment by kdavis-mozilla** [comment]
@Scofield666 As we've solved your original problem and issues are to be used for bugs/feature requests. Could you move this discussion to [discourse](https://discourse.mozilla.org/c/deep-speech). Thanks.
