### ISSUE TITLE
RuntimeError: CreateModel failed with error code 5

### ISSUE THREAD

**Issue by Orest-Divintari** [mozilla/DeepSpeech#2103]
Hello

I am trying to load an exported model for testing and this error occured 

```
deepspeech --model ./custom_model/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio ./data/ldc93s1/LDC93S1.wav
Loading model from file ./custom_model/output_graph.pbmm
TensorFlow: v1.12.0-10-ge232881c5a
DeepSpeech: v0.4.1-0-g0e40db6
2019-05-09 09:40:44.024003: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: Op type not registered 'AudioSpectrogram' in binary running on MacBook-Pro-Orestis.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "/anaconda3/envs/speech_to_text/bin/deepspeech", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/envs/speech_to_text/lib/python3.7/site-packages/deepspeech/client.py", line 80, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/anaconda3/envs/speech_to_text/lib/python3.7/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5
```

The python version that i have is 3.7.3, even though in the requirements.txt the python 3.6 is used.

I used the following command to train the model. 
 
`./bin/run-ldc93s1.sh --export_dir ./custom_model`

I exported the model and converted it to .pbmm

Then i tried to load the exported model, using the existing english language model "lm.binary"
and the existing trie model which i don't know what is it.

The questions are 

1) Do you have any idea what caused this error ?
2) What is the trie model ?

**Comment by kdavis-mozilla** [comment]
Did you train the model with master or with the 0.4.1 version of Deep Speech?

**Comment by Orest-Divintari** [comment]
I installed deep speech using 

`pip install deepspeech`

I just ran 

`deepspeech --version`

and the output is this : 

TensorFlow: v1.12.0-10-ge232881c5a
DeepSpeech: v0.4.1-0-g0e40db6

**Comment by lissyx** [comment]
> I installed deep speech using
> 
> `pip install deepspeech`
> 
> I just ran
> 
> `deepspeech --version`
> 
> and the output is this :
> 
> TensorFlow: v1.12.0-10-ge232881c5a
> DeepSpeech: v0.4.1-0-g0e40db6

We need to know which branch of the DeepSpeech repo you used to perform training. It's very likely given the error that it was master, so your model is incompatible with 0.4.1 binaries.

Please `pip install --upgrade deepspeech==0.5.0a7` then.

**Comment by Orest-Divintari** [comment]
Wow that was easy

I did the upgrade and it worked 

Thank you very much

**Comment by lissyx** [comment]
Thanks!

**Comment by YasineNifa** [comment]
Hello,
PLease I have the same error as Orest-Divintari and I did what Lissyx said! But it does not work for me 
It gives me this error :  bash: /home/innovation/.local/bin/deepspeech: Aucun fichier ou dossier de ce type

**Comment by lissyx** [comment]
@YasineNifa Please stop cross-posting on multiple issues.
