### ISSUE TITLE
Error loading libctc_decoder_with_kenlm.so

### ISSUE THREAD

**Issue by Scofield666** [mozilla/DeepSpeech#2108]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 17.3 Rosa
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: conda install 
- **TensorFlow version (use command below)**: 1.11
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0/7.5
- **GPU model and memory**: GeForce GTX 1080ti

I downloaded the library `libctc_decoder_with_kenlm.so` from [https://github.com/mozilla/DeepSpeech/releases/download/v0.3.0/native_client.amd64.cpu.linux.tar.xz](url)
And then i tried to call `libctc_decoder_with_kenlm.so` using `tf.load_op_library` like this:
```
(tf11) ww@Jenny's Group ~/Downloads/Downloads_backup/native_client.amd64.cpu.linux $ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> a = tf.load_op_library("libdeepspeech.so")
>>> a = tf.load_op_library("libctc_decoder_with_kenlm.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ww/anaconda3/envs/tf11/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
>>> a = tf.load_op_library("libdeepspeech.so")
>>> a
<module '6e237d88703da016805889179d3f5baa'>
```
As you can see, it went wrong when loading `libctc_decoder_with_kenlm.so`, but it successfully loaded `libdeepspeech.so`. I just want to load `libctc_decoder_with_kenlm.so`, any help?

**Comment by lissyx** [comment]
This is mismatching between your TensorFlow and what we built against. How was installed your TensorFlow ?

I'm not sure `tf.load_op_library("libdeepspeech.so")` is a conclusive test, since it's not implementing anything from TensorFlow framework.

**Comment by lissyx** [comment]
I'm starting to suspect discrepancy regarding `_GLIBCXX_USE_CXX11_ABI` ...

**Comment by Scofield666** [comment]
> This is mismatching between your TensorFlow and what we built against. How was installed your TensorFlow ?
> 
> I'm not sure `tf.load_op_library("libdeepspeech.so")` is a conclusive test, since it's not implementing anything from TensorFlow framework.

I directly used `conda install tensorflow-gpu=1.11` to install the tensorflow, just for some testing. So do you mean that I have to install tensorflow from source and then try to load this library?

**Comment by lissyx** [comment]
Could you try outside of conda and use official builds from PyPi ? This is what we test against.

**Comment by Scofield666** [comment]
> Could you try outside of conda and use official builds from PyPi ? This is what we test against.

Fine, and questions about installing tensorflow from source on [https://www.tensorflow.org/install/install_sources](url): following these instructions, does it mean I have installed tensorflow when I have done `./configure` command, so there is no need to build pip package?

**Comment by lissyx** [comment]
> so there is no need to build pip package?

Yes, no need to build pip package, only follow what we document. But there's no reason you need to rebuild, it should work with pypi's tensorflow.

**Comment by Scofield666** [comment]
> > so there is no need to build pip package?
> 
> Yes, no need to build pip package, only follow what we document. But there's no reason you need to rebuild, it should work with pypi's tensorflow.

Emm, I'm sorry that i'm new about this. So do you mean that I just need to use `pip3 install tensorflow` to install tensorflow instead of install from source?

**Comment by lissyx** [comment]
> So do you mean that I just need to use `pip3 install tensorflow` to install tensorflow instead of install from source?

Yes. Make sure you setup a virtualenv, to avoid any clash with Conda, and `pip install tensorflow-gpu` ...

**Comment by Scofield666** [comment]
And after using pip to install tensorflow, i just need to complete the `Preparation` and `Building` part in [https://github.com/mozilla/DeepSpeech/tree/v0.3.0/native_client#building](url) to generate the libs, after which i can use `tf.load_op_library` in this tensorflow env?

**Comment by lissyx** [comment]
Why do you keep on building ? Use prebuilt binaries, those are tested.

**Comment by lissyx** [comment]
@Scofield666 ping ?

**Comment by Scofield666** [comment]
> @Scofield666 ping ?

Sorry, can you provide the downloading link which contains libctc_decoder_with_kenlm.so again? I could't find it in the previous link you gave.

**Comment by lissyx** [comment]
> libctc_decoder_with_kenlm.so

We don't use that anymore.

**Comment by lissyx** [comment]
@Scofield666 If you are working out of `0.3.0`, then it should be in https://github.com/mozilla/DeepSpeech/releases/download/v0.3.0/native_client.amd64.cpu.linux.tar.xz

**Comment by Scofield666** [comment]
> @Scofield666 If you are working out of `0.3.0`, then it should be in https://github.com/mozilla/DeepSpeech/releases/download/v0.3.0/native_client.amd64.cpu.linux.tar.xz

Thanks a lot.
