### ISSUE TITLE
Train French Model

### ISSUE THREAD

**Issue by illi88** [mozilla/DeepSpeech#2112]
Hello guys!!
I would like to train my **own model in french**, but the data of common voice is not enough to give a powerful model,

-  I want to know where I can collect **more data**, if you have links do not hesitate !!

-  what is the **minimum** number of hours to have a good model with good results?

**Comment by lissyx** [comment]
@illi88 Please join the efforts on https://github.com/Common-Voice/commonvoice-fr/issues https://discourse.mozilla.org/c/voice/fr

**Comment by illi88** [comment]
@lissyx  thank you
