### ISSUE TITLE
Native Arch packages

### ISSUE THREAD

**Issue by 9define** [mozilla/DeepSpeech#2115]
This issue is to address the creation of native Arch Linux packages (ie via PKGBUILDs) for the native client and the supporting models and files. I have successfully written configs for two packages:

- The first installs `libdeepspeech.so` to `/usr/lib` and `deepspeech.h` to `/usr/include`.
- The second installs `alphabet.txt`, `lm.binary`, `output_graph.pbmm`, and `trie` to `/usr/share/mozilla/deepspeech/models`.

These packages are convenient/useful for a few reasons:

- Users that don't want to use `pip` or `npm` to fetch prebuilt DeepSpeech can get a package that is native to their OS from the AUR (Arch User Repository).
- The models are distinct from the runtime/development files, but both are still easily available, so users can install only what they need.
- There are probably other reasons that I can't think of at this time.

Why did I create these packages/package configs?
I want to eventually release software that uses DeepSpeech and its models, and these packages would support that effort. Being that I created them, I am effectively volunteering to maintain these packages.

Where are these package config files?
I have them saved on my computer, I can make a PR or add pastebin links here if there is interest.

Why am I opening this ticket?
I could probably submit these packages to the AUR right away if I wanted to, but I figured it would be optimal to advise of my plans to do so.

**Comment by lissyx** [comment]
Isn't it a dupe of https://github.com/mozilla/DeepSpeech/issues/979 ?

**Comment by kdavis-mozilla** [comment]
@lissyx Did #979 "fizzle out"? I haven't seen any recent progress.

**Comment by lissyx** [comment]
> @lissyx Did #979 "fizzle out"? I haven't seen any recent progress.

It's stalled but the bug is still open, and it documents that there were already AUR packages done, so it's part of @9define proposal, so I thought maybe it was worth mentionning to avoid re-doing work for nothing :)

**Comment by 9define** [comment]
@lissyx Ah, I missed that issue, my apologies. It seems as though one of the main topics of that thread was a focus on creating a package that builds DS from sources, which is good for a `deepspeech-git` package (which I did find on the AUR but is very outdated). What I am suggesting is a non-`-git` package whose purpose is to install released pre-built binaries/libs, as well as a package to install the models for that release. I think this kind of package fits a pattern that other packages have created (think of any large codebases that people don't want to install a new build system just to compile).

I can hop on to that issue above if you'd like, but I'm not sure if yall want me to bump an old thread. Also, as it seems relevant, I uploaded my PKGBUILDs to pastebin, they can be found [here](https://pastebin.com/368Y8r8L) and [here](https://pastebin.com/VawqdU5j). Please let me know if you'd like to see these upstreamed to the AUR or if there's more work to be done. Thanks!

**Comment by lissyx** [comment]
@9define I just thought it was worth mentionning there might some some existing `PKGBUILD` you may want to build on top, but honestly, I'm not ArchLinux fluent, so you should do it as you'd like :)

**Comment by lissyx** [comment]
Though I have to admit the idea of packaging the models as well is something we thought about, but we never pushed through ...

**Comment by 9define** [comment]
@lissyx Ok I think I will submit these packages to the AUR then. I can open a PR to get these merged into the repo if you'd like. If nothing else, at least it would start a conversation there about what you just mentioned.

**Comment by 9define** [comment]
To wrap this up, [`libdeepspeech`](https://aur.archlinux.org/packages/libdeepspeech/) and [`deepspeech-models`](https://aur.archlinux.org/packages/deepspeech-models/) are now in the AUR. I'll x-post on the other issue.
