### ISSUE TITLE
DeepSpeech 0.4.1 ignored the epoch parameter

### ISSUE THREAD

**Issue by 20richardh** [mozilla/DeepSpeech#2118]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu Virtual Machine
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip3 install tensorflow==1.12.0
- **TensorFlow version (use command below)**: 1.12.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

python3 DeepSpeech.py --n_hidden 2048 --checkpoint_dir /mnt/d/Mozilla/trainings/F04_checkpoints **--epochs 1** --validation_step 1 --train_files /mnt/d/UA_Data/implementation/F04/train.csv --dev_files /mnt/d/UA_Data/implementation/F04/validate.csv --test_files /mnt/d/UA_data/implementation/F04/validate2.csv --learning_rate 0.0001 --alphabet_config_path /mnt/d/richardhu/tensorflow-master/tensorflow/examples/GitLFS_forDeepSpeech/scratch/DeepSpeech-041/data/alphabet.txt export_dir /mnt/d/allModels/UA/F04

I specified one epoch, but it currently has started another epoch (more than the specified amount). Then I tried the above command with a shorter set of data so it could run faster, and it carried out all 75 epochs, which is the default value of the --epoch parameter. Is there a problem with DeepSpeech.py, or maybe I need to change another parameter? Note that I'm on DeepSpeech 0.4.1

Preferably, I also do not want to go into the program and edit the default parameter, because training one epoch takes quite a while (and I don't want to restart).

**Comment by lissyx** [comment]
The name `epochs` is valid for current master, but not on `0.4.1`. Please use `--epoch`.
