### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError

### ISSUE THREAD

**Issue by IsaacDiane** [mozilla/DeepSpeech#2119]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:1.13.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:7.3.0
- **CUDA/cuDNN version**:runtime CUDA 10.0,cuDNN 7.5(accurately , it is 7501 ,and I had tried version 7500,it came the same error  ,so maybe I should try cuDNN 7.4?)
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

I had run bin/run-ldc93s1.sh with both tensorflow==1.13.1 and tensorflow-gpu==1.13.1,but when I did that on the gpu version ,it came the error :tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
But I'm sure that I had installed CUDA 10.0 and configured cuDNN 7.5 correctly ,and I had re-installed it once more , I had search for this issue ,someone said it's caused by the too high version of tensorflow ,is that the true reason?OR I just omitted some step when I installed them?

**Comment by lissyx** [comment]
>  But I'm sure that I had installed CUDA 10.0 and configured cuDNN 7.5 correctly ,and I had re-installed it once more , I had search for this issue ,someone said it's caused by the too high version of tensorflow ,is that the true reason?OR I just omitted some step when I installed them?

We can't tell since you don't give more context. Please stick to TensorFlow recommended versions, this is not a bug on DeepSpeech obviously.
