### ISSUE TITLE
Model for  0.5.0a8

### ISSUE THREAD

**Issue by divamgupta** [mozilla/DeepSpeech#2120]
Hi,

Where can I get the pre-trained model for deepspeech==0.5.0a8 installed via pip. The model given is not compatible with 0.5.0a8

`RuntimeError: CreateModel failed with error code 8195`

**Comment by reuben** [comment]
0.5.0a8 is an alpha release and does not have a published model to go with it.

**Comment by divamgupta** [comment]
Hi, 

Any alternative other than training it from scratch? ... can it be converted from the older version?

**Comment by reuben** [comment]
Not for now. We'll release a compatible model with the stable 0.5 release.

**Comment by divamgupta** [comment]
Okay cool. What is the expected date for the stable 0.5 release.
