### ISSUE TITLE
DeepSpeech french model

### ISSUE THREAD

**Issue by YasineNifa** [mozilla/DeepSpeech#2122]
Hey !!!

After training a French model, and generating a output_graph.pbmm. I tested my model but it was not good as all. Is it because I did not use the language model and the tries. If is that the reason, so how can I do that ?

Examples of my model :   
WER: 3.000000, CER: 7.000000, loss: 19.907118
 - src: "minuit"
 - res: "it le huit"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 2.000000, loss: 10.053004
 - src: "cherchez"
 - res: "che che"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 4.000000, loss: 10.941154
 - src: "enfin"
 - res: "i can"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 2.000000, loss: 13.227859
 - src: "distu"
 - res: "dix u"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 5.000000, loss: 13.248935
 - src: "laquelle"
 - res: "i tell"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 5.000000, loss: 13.811304
 - src: "absolument"
 - res: "as men"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 5.000000, loss: 14.151725
 - src: "lentement"
 - res: "late in"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 1.000000, loss: 14.546191
 - src: "vingttrois"
 - res: "vingt trois"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 5.000000, loss: 15.554608
 - src: "bienvenue"
 - res: "di menu"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 5.000000, loss: 16.124020
 - src: "murmures"
 - res: "mir mir"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 5.000000, loss: 16.619673
 - src: "qu'importe"
 - res: "quam porro"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 3.000000, loss: 18.236885
 - src: "dommage"
 - res: "de age"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 6.000000, loss: 18.687059
 - src: "combien"
 - res: "an i"
--------------------------------------------------------------------------------
WER: 2.000000, CER: 4.000000, loss: 18.847189
 - src: "extra"
 - res: "as a"

Thx

**Comment by lissyx** [comment]
@YasineNifa This kind of question is exactly why we have https://discourse.mozilla.org/c/voice/fr https://github.com/Common-Voice/commonvoice-fr

Please use it.
