### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by SibtainRazaJamali** [mozilla/DeepSpeech#2137]
When will you release the next pre trained model?

**Comment by kdavis-mozilla** [comment]
When it's ready 😉

More seriously, I'm starting to write up the release notes. So, assuming nothing goes horribly wrong with testing 0.5.0 will be released in 2-3 weeks.

**Comment by kdavis-mozilla** [comment]
In light of #2139 the release may be delayed a bit.
