### ISSUE TITLE
CUDA 10 Docker libcuda.so.1 error

### ISSUE THREAD

**Issue by madhavajay** [mozilla/DeepSpeech#2138]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 Docker
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: PyPI
- **TensorFlow version (use command below)**: PyPI
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0 7.5 and 7.4 (as per TF docs)
- **GPU model and memory**: K80 GCE
- **Exact command to reproduce**:

I am using a Dockerfile with this:

```
FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04
```

I have cuda-10-0 and have tried libcudnn7_7.5.1.10-1+cuda10.0_amd64.deb and libcudnn7=7.4.1.5-1+cuda10.0.

I install 0.5.0a10 from pypi and then when I run it I get:
```
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```

The docker container has the file:
```
find / -name "libcuda.so.1"
```
Outputs:
```
/usr/local/cuda-10.0/compat/libcuda.so.1
```

All previous versions from 0.1.1, 0.2, 0.3, 0.4.1 etc have worked fine by pairing the right CUDA / CuDNN files in Ubuntu and using the correct Docker image.

Is something different in v0.5 with TF 1.13.
I tried these steps but its the same error:
https://www.tensorflow.org/install/gpu

**Comment by lissyx** [comment]
And is `/usr/local/cuda-10.0/compat/` in `ld`'s config or `LD_LIBRARY_PATH` ?

**Comment by madhavajay** [comment]
Seems the error was:
```
RuntimeError: CreateModel failed with error code 8195
```

Because I was trying to use the model from 0.4.1, and have now found that there is no available model for 0.5 alpha so I guess we need to wait?

The reason I got the above issues was I accidentally ran the docker command without the --runtime=nvidia while trying to debug why the container wasn't working via a scripted process.
I wish the nvidia images were able to give a warning when ran without the nvidia runtime to make it more obvious. A good trick is just to run inside the container:
```
$ nvidia-smi
```

If you are not using the nvidia runtime the nvidia-smi command fails.

It seems the compat cuda files are there to allow CPU machines to still run the GPU containers and for tensorflow to still load allowing the programatic detection of GPU or CPU in python and to code switch at the last minute which is handy.

I used the following versions of CUDA / CuDNN:
```
cuda_version: cuda-10-0
cudnn_version: libcudnn7.5
nvidia_repo: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
cudnn_package: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7_7.5.1.10-1+cuda10.0_amd64.deb
```

These work with the 0.5 alpha build in this docker image:
```
FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04
```

**Comment by lissyx** [comment]
> Because I was trying to use the model from 0.4.1, and have now found that there is no available model for 0.5 alpha so I guess we need to wait?

That's not a training error, that's a runtime inference error. Sorry, but it's unclear what you are doing.

And `libcuda.so.1` needs to be accessible.

**Comment by madhavajay** [comment]
Sorry, I had been trying various CUDA versions all night and missed the Model error. I found another github issue relating to the 0.5 alpha models not existing. Do you have an ETA on a pre-trained 0.5 model being available? I guess you can close this issue.

**Comment by lissyx** [comment]
No we don't, but it's very close. Thanks!
