### ISSUE TITLE
Getting runtime exception while loading the pretrained model

### ISSUE THREAD

**Issue by rajdeosingh98** [mozilla/DeepSpeech#2144]
Getting runtime exception while running deepspeech command after installing.
Command
deepspeech --model models/output_graph.pb --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio /home/asdf/Downloads/LDC93S1.wav^C

RuntimeException and Warning:-
Not found: Op type not registered 'Assert' in binary running on asdf-Inspiron-5559. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "/home/asdf/tmp/deepspeech-venv/bin/deepspeech", line 10, in <module>
    sys.exit(main())
  File "/home/asdf/tmp/deepspeech-venv/lib/python3.6/site-packages/deepspeech/client.py", line 80, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/asdf/tmp/deepspeech-venv/lib/python3.6/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5

**Comment by lissyx** [comment]
@rajdeosingh98 It looks like you are using incompatible model / deepspeech binary set. Since you have not documented any installation step nor provided the full output including lib versions, we can't help more.
