### ISSUE TITLE
how "ds_ctcdecoder" be installed in windows

### ISSUE THREAD

**Issue by JovanLiu** [mozilla/DeepSpeech#2153]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 7 Anaconda-tensorflow
- **TensorFlow version (use command below)**:tensorflow-gpu   1.13.1
- **Python version**: 3.6.8
- **Bazel version (if compiling from source)**:0.22.0
- **CUDA/cuDNN version**: 10/v7.5.0
- **GPU model and memory**:GPU model 

please help me...

**Comment by lissyx** [comment]
We don't support training outside of Linux, and we don't have builds of ctcdecoder for windows

**Comment by JovanLiu** [comment]
謝謝!
