### ISSUE TITLE
Hi everyone, i am getting an error message: illegal Instruction (core dumped) while trying to load deepspeech pre-trained model deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio_file.wav

### ISSUE THREAD

**Issue by monique94** [mozilla/DeepSpeech#2154]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by lissyx** [comment]
@monique94 We have a template that you have not filled. We can't help you. Illegal instruction means your CPU is too old.

**Comment by Corey-G** [comment]
If you are using the 0.4.1 try going down to tensorflow version 1.5.0 which might work.

**Comment by lissyx** [comment]
> If you are using the 0.4.1 try going down to tensorflow version 1.5.0 which might work.

This does not make any sense.

**Comment by monique94** [comment]
@Corey-G, i have tensorflow 1.5.0 installed already but i still get the same error message

**Comment by lissyx** [comment]
> @Corey-G, i have tensorflow 1.5.0 installed already but i still get the same error message

I've already replied on what you need to share us to be able to help you. Installing TensorFlow will not help.

**Comment by monique94** [comment]
lissyx i got your message loud and clear, thanks anyway
