### ISSUE TITLE
ERROR: ds_ctcdecoder-0.5.0a11-cp36-cp36m-windows_AMD64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by amansulaiman** [mozilla/DeepSpeech#2155]
- **I am trying to install ds_ctcdecoder but an error message is trowing. I am tried it out on 3 different Machine**:
- **OS Platform and Distribution: Windows 10 & Windows Server 2012**:
- **TensorFlow installed from upstream TensorFlow**:
- **TensorFlow version 1.13.1**:
- **Python version 3.6.8**: 

FULL ERROR MESSAGE

ERROR: ds_ctcdecoder-0.5.0a11-cp36-cp36m-windows_AMD64.whl is not a supported wheel on this platform.

**Comment by lissyx** [comment]
@amansulaiman Can you share more detailed `pip install --verbose` ?

**Comment by lissyx** [comment]
> ERROR: ds_ctcdecoder-0.5.0a11-cp36-cp36m-windows_AMD64.whl is not a supported wheel on this platform.

We don't have ctcdecoder on Windows and we don't support training on anything else than Linux. What are you trying to achieve ?

**Comment by amansulaiman** [comment]
Okay. Thanks. I am trying to train a model on a Windows machine. Last four month I trained a model on windows and it's working fine. So, why Windows is not supporting anymore?

**Comment by reuben** [comment]
We never supported it, did you build libctc_decoder_with_kenlm on Windows yourself?

**Comment by lissyx** [comment]
>  Last four month I trained a model on windows and it's working fine

I think that even TensorFlow upstream training support on Windows is still very recent ...

**Comment by amansulaiman** [comment]
> We never supported it, did you build libctc_decoder_with_kenlm on Windows yourself?

No. I followed the steps in the ReadMe.md. And it works fine

**Comment by lissyx** [comment]
> No. I followed the steps in the ReadMe.md. And it works fine

I don't know how it's possible, we never had builds ... Because we never even had Windows.

**Comment by amansulaiman** [comment]
> > No. I followed the steps in the ReadMe.md. And it works fine
> 
> I don't know how it's possible, we never had builds ... Because we never even had Windows.

Anyway, I will switch to Linux. I wish to work on this in the near future. Thanks
