### ISSUE TITLE
Package macOS binaries as zip files

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2162]
The macOS binaries in the releases are packaged as .tar.xz, which isn't a format that's commonly used on the Mac.

While macOS does ship with tar on the command-line, double-clicking the file within the GUI causes weird behavior. If the file is myfile.tar.xz, it converts it to myfile.tar.xz.cpgz. If I then open that file it converts it again to myfile.tar.xz and you end up in a never-ending loop.

Other popular extraction tools like The Unarchiver do slightly better, but I still couldn't find a GUI tool that knew how to deal with a tar file.

While you can still extract it from the command line, I think this is a bad user experience so it would be better if the Mac binaries were packaged in a format that's more common on a Mac, such as zip or gz without tar.

**Comment by dabinat** [comment]
Update: seems like it works fine with the models, which are .tar.gz, so I think it's the .xz format that's the issue here, not tar.

**Comment by lissyx** [comment]
@dabinat Thanks, but at the same time, changing for a specific compression is painful for a lot of reasons, including that zip performs poorly on the lib. The `native_client.tar.xz` is not really intended for end-user, so I'm not really convinced it is such a big deal a developper has to have proper tooling, and `xz` by itself is quite common.

**Comment by lissyx** [comment]
@dabinat For some other use-case we started distributing `libdeepspeech.so` inside a zip file. Does that addresses your use-case ?

**Comment by dabinat** [comment]
@lissyx Is that just the .so file or is it the deepspeech executable too?

**Comment by lissyx** [comment]
Just the `.so`

**Comment by dabinat** [comment]
@lissyx Ah, it doesn't address the use-case then.

**Comment by kdavis-mozilla** [comment]
I'm going to close for lack of activity. If xz still seems like a problem for OS X developers, feel free to re-open.
