### ISSUE TITLE
Feature request: README.md unclear. Break into multiple documents?

### ISSUE THREAD

**Issue by kjcole** [mozilla/DeepSpeech#2171]
The `README.md` appears to have overlapping instructions. I'm a newbie, but it appears to suggest cloning this `git` repository, and installing the Python package via `pip` and downloading the pre-built binaries for the deepspeech command-line via `python3 util/taskcluster.py --target .` 

Are all three steps necessary or are these different ways to accomplish similar tasks? (I get that the downloading of the command-line program requires `taskcluster.py` which is in the git repo, but maybe that could be extracted as well.)

**Comment by lissyx** [comment]
@kjcole The README does have titles / sections, isn't it enough to give context depending on what is your need ? As much as I can remember, we made sure sections depending on use-cases were properly scoped and self-contained.

**Comment by lissyx** [comment]
e.g., you want to play with the inference ? https://github.com/mozilla/DeepSpeech#using-a-pre-trained-model

you want to train a model ? https://github.com/mozilla/DeepSpeech#training-your-own-model

**Comment by lissyx** [comment]
@kjcole Still, if you have suggestions / proposal on how to re-organize, do not hesitate to share input or open a PR.

**Comment by kjcole** [comment]
Perhaps it's just my old brain and old eyes. Yes, I saw the section headings. For now, I'm only talking about playing with the interface, not training a model.

["Getting the code"](https://github.com/mozilla/DeepSpeech#getting-the-code) seems to be a prerequisite for ["Using the command-line client"](https://github.com/mozilla/DeepSpeech#using-the-command-line-client) since it uses `util/taskcluster.py`, but is not a prerequisite for ["Using the Python package"](https://github.com/mozilla/DeepSpeech#using-the-python-package) since that appears to grab everything it needs via pip.

Correct?

Maybe a re-ordering of sections too, from simplest to most complex: If I read things right, I would think the simplest use case -- despite the need to run interpreted code from the git repo to set it up -- would be the pre-compiled, binary, command line client, followed by Python / Node.js (in either order) -- which doesn't need the git repo at all(?) -- then the bindings sections, and finally train your own model.

**Comment by lissyx** [comment]
> Maybe a re-ordering of sections too, from simplest to most complex: If I read things right, I would think the simplest use case -- despite the need to run interpreted code from the git repo to set it up -- would be the pre-compiled, binary, command line client, followed by Python / Node.js (in either order) -- which doesn't need the git repo at all(?) -- then the bindings sections, and finally train your own model.

That re-ordering might be tricky, it really is a judgement depending on your own needs. For some people, the very first need is like yours, for some others, it's really training. So I don't really have an opinion as to whether a re-ordering is needed and which proper order is perfect.

> ["Getting the code"](https://github.com/mozilla/DeepSpeech#getting-the-code) seems to be a prerequisite for ["Using the command-line client"](https://github.com/mozilla/DeepSpeech#using-the-command-line-client) since it uses `util/taskcluster.py`, but is not a prerequisite for ["Using the Python package"](https://github.com/mozilla/DeepSpeech#using-the-python-package) since that appears to grab everything it needs via pip.
> 
> Correct?

That's about right yes


> Perhaps it's just my old brain and old eyes. Yes, I saw the section headings. For now, I'm only talking about playing with the interface, not training a model.

Or a different perspective: we know it well, it all seem obivous to us, but that does not mean it's clear to others :).

**Comment by lissyx** [comment]
@kjcole Could you open a PR with a re-ordering that makes more sense to you ?

**Comment by lissyx** [comment]
@kjcole I'm going to close that, we're taking steps for making the documentation clearer in #2339, and I think we might re-visit all the READMEs we have. Please do not hesitate to share feedback on the doc, but yours has been valuable in the process of re-thinking docs.
