### ISSUE TITLE
native_client: make clean lacks bindings-clean target

### ISSUE THREAD

**Issue by SantosSi** [mozilla/DeepSpeech#2175]
v0.5.0 does not execute make clean in the native_client subfolder. It looks for bindings-clean, but that is not found.

**Comment by lissyx** [comment]
> v0.5.0 does not execute make clean in the native_client subfolder. It looks for bindings-clean, but that is not found.

That's a left-over of era before moving bindings target into their own `Makefile`

**Comment by lissyx** [comment]
@SantosSi Do you mind opening a PR to fix that ?
