### ISSUE TITLE
OSError with Common Voice 2 importer 

### ISSUE THREAD

**Issue by akhilvasvani** [mozilla/DeepSpeech#2177]
I am trying to convert the .mp3 and .tsv files in common voice 2 to .csv files using the 'import_cv2.py' file. 

I used the command (alphabet textfile, the mp3 files, and tsv files are all in the clips folder (as per the instructions on the main page): 

```python3 bin/import_cv2.py --filter_alphabet data/alphabet.txt data/CV/en/```

and got back
```
Importing mp3 files...
Traceback (most recent call last):
  File "bin/import_cv2.py", line 166, in <module>
    _preprocess_data(PARAMS.tsv_dir, AUDIO_DIR, label_filter_fun, PARAMS.space_after_every_character)
  File "bin/import_cv2.py", line 43, in _preprocess_data
    _maybe_convert_set(input_tsv, audio_dir, label_filter, space_after_every_character)
  File "bin/import_cv2.py", line 101, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "bin/import_cv2.py", line 72, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "bin/import_cv2.py", line 135, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/home/akhil/PycharmProjects/DeepSpeech/venv/lib/python3.6/site-packages/sox/transform.py", line 412, in build
    file_info.validate_input_file(input_filepath)
  File "/home/akhil/PycharmProjects/DeepSpeech/venv/lib/python3.6/site-packages/sox/file_info.py", line 215, in validate_input_file
    "input_filepath {} does not exist.".format(input_filepath)
OSError: input_filepath data/CV/en/clips/36e1606224ac9671de8435737cd8828fc910b8f841de83ef421be74b734248b5f52477269d8c768705059b4c6fa4ff9c62d802155f249b56de536f33eb90017d.mp3 does not exist.
```
Did I download something incorrectly? Am I doing something wrong or should I try using 'import_cv.py'?

**Comment by lissyx** [comment]
Are you sure the path is correct? Do you reproduce with full path instead of relative? Is that latest cv release from this week?

**Comment by akhilvasvani** [comment]
The path is correct. I was already in the root directory. And yes, this is the latest data I downloaded from [here](https://voice.mozilla.org/en/datasets)

**Comment by akhilvasvani** [comment]
What should I do?

**Comment by lissyx** [comment]
Well if you can ensure the file is missing in the tarball and its actually referenced in the tsv files, then that's not an importer bug but a common voice release issue.

**Comment by kdavis-mozilla** [comment]
@akhilvasvani Is this the recent "en_1085h_2019-06-12" release of Common Voice?

**Comment by akhilvasvani** [comment]
@kdavis-mozilla, yes

**Comment by akhilvasvani** [comment]
@lissyx, as for proof here is what I can offer:
```
akhil@Minerva:~/DeepSpeech/data/CV/en/clips$ locate 36e1606224ac9671de8435737cd8828fc910b8f841de83ef421be74b734248b5f52477269d8c768705059b4c6fa4ff9c62d802155f249b56de536f33eb90017d.mp3
akhil@Minerva:~/DeepSpeech/data/CV/en/clips$ locate 2cebb7196b292b57a1a2141c4fada2a62318ec53e5deb07a30c89a8bbabfabc2925be2d7159791f8c34f0a9b6f2bd8425a473a9d96f0fefc9054602c084755f7.mp3
/home/akhil/DeepSpeech/data/CV/en/clips/2cebb7196b292b57a1a2141c4fada2a62318ec53e5deb07a30c89a8bbabfabc2925be2d7159791f8c34f0a9b6f2bd8425a473a9d96f0fefc9054602c084755f7.mp3
akhil@Minerva:~/DeepSpeech/data/CV/en/clips$ 
```

So it does not find the missing file. I located another file just for comparsion. And in the first row of the 'train.tsv' file:
client id | path 

2cd9a591b669f14a0b7c039f087c902dc075c19a1be9bb23c8e0fecff255f5be36fb3d72c118c972c00def21b62b1df550f2205eaea066cfb70ef4f4f4e152f7 | 36e1606224ac9671de8435737cd8828fc910b8f841de83ef421be74b734248b5f52477269d8c768705059b4c6fa4ff9c62d802155f249b56de536f33eb90017d
-- | --

**Comment by kdavis-mozilla** [comment]
@akhilvasvani Unfortunately, there is a bug with the Common Voice data. Could you file a bug with [voice-web](http://github.com/mozilla/voice-web)? Thanks for reporting!

**Comment by akhilvasvani** [comment]
Will do. Thanks.
