### ISSUE TITLE
Would you mind tell me the WER of librispeech datasets? thanks

### ISSUE THREAD

**Issue by iamxiaoyubei** [mozilla/DeepSpeech#2182]
Would you mind tell me the WER of librispeech datasets(dev-clean/dev-other/test-clean/test-other/or both of them?) for ASR task? Thank you~

**Comment by kdavis-mozilla** [comment]
We have indicated librispeech test-clean WER in the release notes. We have not computed the WER for datasets(dev-clean/dev-other/test-other) The release also contains a command line tool for you to find the others yourself.
