### ISSUE TITLE
Allow for different audio samplerate

### ISSUE THREAD

**Issue by RegaliaXYZ** [mozilla/DeepSpeech#2183]
It would be really nice to allow lower samplerates like 8kHz, which is really popular for telecommunication, for DeepSpeech.

**Comment by lissyx** [comment]
> It would be really nice to allow lower samplerates like 8kHz, which is really popular for telecommunication, for DeepSpeech.

That's already possible, can you explain more why you filed the issue ?

**Comment by RegaliaXYZ** [comment]
I didn't see that it was possible, do you only need to modify the samplerate in flags.py ?

**Comment by reuben** [comment]
You need to call the API directly or modify the clients, as they don't support different sample rates. Also, if you're using TFLite, you'll need to change the code and recompile libdeepspeech.so.

**Comment by reuben** [comment]
And yes, you should also specify `--audio_sample_rate` when exporting the model.

**Comment by rhamnett** [comment]
I updated the python client to make this a little bit easier https://github.com/mozilla/DeepSpeech/pull/2199

**Comment by lissyx** [comment]
PR #2199 has been merged, we should close this.
