### ISSUE TITLE
Integration of Warp-CTC Algorithm into TensorFlow

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#22]

**Comment by gregorwagner** [comment]
we have to make sure it works on all our machines and the server and we all have to have some idea how to install/compile it on all our machines

**Comment by lissyx** [comment]
WIP PR: https://github.com/mozilla/tensorflow/pull/2

**Comment by lissyx** [comment]
Merged. First builds will be on https://tools.taskcluster.net/task-graph-inspector/#aqiYiWqhQV-_ZcHpQnFbGw/ :)
