### ISSUE TITLE
Error: Trie file version mismatch (4 instead of expected 3). Update your trie file.

### ISSUE THREAD

**Issue by alchemi5t** [mozilla/DeepSpeech#2206]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:  pip installed pre-compiled binary for 1.13.1
- **TensorFlow version (use command below)**:'1.13.1'
- **Python version**: 3.6.8
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:10
- **GPU model and memory**:Titan V
- **Exact command to reproduce**: CUDA_VISIBLE_DEVICES=0 python DeepSpeech.py --train_files ../et/clips/train.csv --dev_files ../et/clips/dev.csv --test_files ../et/clips/test.csv

I have git-lfs and have cloned the repo with it. I am on the master branch and the trie and lm have been cloned with git-lfs. How would i go about fixing this?

**Comment by kdavis-mozilla** [comment]
Does your master include the commit 0ea5804?

**Comment by alchemi5t** [comment]
@kdavis-mozilla yes. Let me explain what all i've done.

1) git lfs clone <repo>
2) have all the pre-reqs
3) preprocessed the datasets
4) run "CUDA_VISIBLE_DEVICES=0 python DeepSpeech.py --train_files ../et/clips/train.csv --dev_files ../et/clips/dev.csv --test_files ../et/clips/test.csv"

**Comment by lissyx** [comment]
> @kdavis-mozilla yes. Let me explain what all i've done.
> 
>     1. git lfs clone
> 
>     2. have all the pre-reqs
> 
>     3. preprocessed the datasets
> 
>     4. run "CUDA_VISIBLE_DEVICES=0 python DeepSpeech.py --train_files ../et/clips/train.csv --dev_files ../et/clips/dev.csv --test_files ../et/clips/test.csv"

Can you check ? 

```
$ sha1sum data/lm/lm.binary data/lm/trie 
098c71d7f720ff1842650881e2e3ebb9d18bd7d3  data/lm/lm.binary
5f2c59596a977779f27869768e544c82e840290f  data/lm/trie
```

**Comment by alchemi5t** [comment]
$ sha1sum lm.binary trie

098c71d7f720ff1842650881e2e3ebb9d18bd7d3  lm.binary
5f2c59596a977779f27869768e544c82e840290f  trie

**Comment by lissyx** [comment]
@alchemi5t What's your `ds_ctcdecoder` version? `pip list`

**Comment by alchemi5t** [comment]
ds-ctcdecoder==0.6.0a0

**Comment by lissyx** [comment]
> @lissyx ds-ctcdecoder==0.6.0a0

Ok, can you pick the wheel matching your python version on https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.master/cpu-ctc and retry ?

**Comment by lissyx** [comment]
`pip install --upgrade <URL>` with `<URL>` being one of those package on https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.master/cpu-ctc

**Comment by alchemi5t** [comment]
@lissyx got it. on it. will reply as soon as done.

**Comment by alchemi5t** [comment]
HOLY $***!! @lissyx that actually worked! Thanks a ton, mate!

**Comment by lissyx** [comment]
Thanks, so we need to release a new alpha then.

**Comment by alchemi5t** [comment]
yep! 
pip install --upgrade https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu-ctc/artifacts/public/ds_ctcdecoder-0.6.0a0-cp36-cp36m-manylinux1_x86_64.whl 

for python 3.6 if anyone needs it.

**Comment by lissyx** [comment]
> yep!
> pip install --upgrade https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu-ctc/artifacts/public/ds_ctcdecoder-0.6.0a0-cp36-cp36m-manylinux1_x86_64.whl
> 
> for python 3.6 if anyone needs it.

Thanks, I just pushed the `v0.6.0-alpha.1` tag so it should be properly handled as soon as the builds finished.

**Comment by lissyx** [comment]
Builds finished, it should be transparent now following the docs. Thanks @alchemi5t for reporting.
