### ISSUE TITLE
NodeJS extended metadata API segfault at GC

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2217]
I can't reproduce locally on macOS. I haven't checked every single failure but a bunch of them have been during the `--extended` test, which leads me to believe the problem is in the NodeJS bindings for that API.

**Comment by lissyx** [comment]
I gave a try to run nodejs bindings under valgrind, but could not uncover any memory access issues. There are leakages reported, though.

**Comment by lissyx** [comment]
[ds_node.log.gz](https://github.com/mozilla/DeepSpeech/files/3345301/ds_node.log.gz)

valgrind log with debug build

**Comment by lissyx** [comment]
@reuben I also don't reproduce on our macOS workers ?!

**Comment by lissyx** [comment]
```
ds-worker-vm-sierra-light-9:node9 workeradmin$ ./node_modules/.bin/deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --audio audio/2830-3980-0043.wav --extended
Loading model from file deepspeech-0.5.1-models/output_graph.pbmm
TensorFlow: v1.13.1-10-g3e0cc5374d
DeepSpeech: v0.5.1-0-g4b29b78
2019-07-02 14:46:17.295030: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-02 14:46:17.311300: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2019-07-02 14:46:17.311359: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-07-02 14:46:17.311373: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-07-02 14:46:17.311383: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
Loaded model in 0.08451s.
Running inference.
experienced proof this
Inference took 11.58s for 1.975s audio file.
ds-worker-vm-sierra-light-9:node9 workeradmin$ echo $?
0
```

**Comment by lissyx** [comment]
So, hacking `native_client/javascript/client.js` for looping around in `metadataToString()`, I could reproduce the issue on my system:

```
==22104== LEAK SUMMARY:
==22104==    definitely lost: 94 bytes in 2 blocks
==22104==    indirectly lost: 0 bytes in 0 blocks
==22104==      possibly lost: 276,282 bytes in 85 blocks
==22104==    still reachable: 949,617,787 bytes in 60,240 blocks
==22104==                       of which reachable via heuristic:
==22104==                         stdstring          : 181 bytes in 4 blocks
==22104==                         newarray           : 67,840 bytes in 225 blocks
==22104==                         multipleinheritance: 312 bytes in 3 blocks
==22104==         suppressed: 0 bytes in 0 blocks
==22104== 
==22104== ERROR SUMMARY: 25 errors from 25 contexts (suppressed: 2 from 2)
==22104== 
==22104== 1 errors in context 1 of 25:
==22104== Jump to the invalid address stated on the next line
==22104==    at 0x0: ???
==22104==    by 0xDE7439: v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
==22104==    by 0xE16626: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
==22104==    by 0xE1746D: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
==22104==    by 0xDBB371: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
==22104==    by 0x103430F: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
==22104==    by 0x2931EBD042FC: ???
==22104==    by 0x2931EBD0C6B3: ???
==22104==    by 0x2931EBDF1EF5: ???
==22104==    by 0x2931EBDBD195: ???
==22104==    by 0x2931EBDBD195: ???
==22104==    by 0x2931EBDBD195: ???
==22104==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

**Comment by lissyx** [comment]
Turns out with some investigation one can reproduce the issue on mostly every NodeJS version ...

**Comment by lissyx** [comment]
Re-testing with current SWIG master I cannot reproduce the issue anymore at all

**Comment by lissyx** [comment]
```
==17834== 2230 errors in context 2 of 26:                                       
  ==17834== Invalid read of size 4                                                
  ==17834==    at 0x8D046D2: decoder_decode(DecoderState*, Alphabet const&, unsigned long, Scorer*) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFDB51: ModelState::decode_raw(DecoderState*) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFDED6: ModelState::decode_metadata(DecoderState*) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFD55E: DS_FinishStreamWithMetadata (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
  ==17834==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xDFC110042FC: ???                                              
  ==17834==    by 0xDFC110BD195: ???                                              
  ==17834==    by 0xDFC1100535E: ???                                              
  ==17834==    by 0xDFC110BD195: ???                                              
  ==17834==  Address 0x4fdf6e4 is 20 bytes inside a block of size 112 free'd      
  ==17834==    at 0x4839E7B: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
  ==17834==    by 0x8D035B0: decoder_next(double const*, Alphabet const&, DecoderState*, int, int, double, unsigned long, unsigned long, Scorer*) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFC1EF: StreamingState::processBatch(std::vector<float, std::allocator<float> > const&, unsigned int) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFD530: StreamingState::finishStreamWithMetadata() (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFD55E: DS_FinishStreamWithMetadata (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
  ==17834==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xDFC110042FC: ???                                              
  ==17834==    by 0xDFC110BD195: ???                                              
  ==17834==    by 0xDFC1100535E: ???                                              
  ==17834==  Block was alloc'd at                                                 
  ==17834==    at 0x4838DBF: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
  ==17834==    by 0x8D113C1: PathTrie::get_path_trie(int, int, float, bool) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8D03121: decoder_next(double const*, Alphabet const&, DecoderState*, int, int, double, unsigned long, unsigned long, Scorer*) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFC1EF: StreamingState::processBatch(std::vector<float, std::allocator<float> > const&, unsigned int) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFD530: StreamingState::finishStreamWithMetadata() (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x8CFD55E: DS_FinishStreamWithMetadata (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/libdeepspeech.so)
  ==17834==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
  ==17834==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==17834==    by 0xDFC110042FC: ???                                              
  ==17834==    by 0xDFC110BD195: ???                                              
```

**Comment by lissyx** [comment]
> ```
>   ==28087== 2230 errors in context 2 of 26:                                       
>   ==28087== Invalid read of size 4                                                
>   ==28087==    at 0x8DCFD62: decoder_decode(DecoderState*, Alphabet const&, unsigned long, Scorer*) (ctc_beam_search_decoder.cpp:167)
>   ==28087==    by 0x8DCD521: ModelState::decode_raw(DecoderState*) (modelstate.cc:47)
>   ==28087==    by 0x8DCD7E6: ModelState::decode_metadata(DecoderState*) (modelstate.cc:61)
>   ==28087==    by 0x8DCC4BE: DS_FinishStreamWithMetadata (deepspeech.cc:390)      
>   ==28087==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
>   ==28087==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0x17A1FE8842FC: ???                                             
>   ==28087==    by 0x17A1FE93D195: ???                                             
>   ==28087==    by 0x17A1FE88535E: ???                                             
>   ==28087==    by 0x17A1FE93D195: ???                                             
>   ==28087==  Address 0x7ed1114 is 20 bytes inside a block of size 112 free'd      
>   ==28087==    at 0x4839E7B: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
>   ==28087==    by 0x8DCF040: decoder_next(double const*, Alphabet const&, DecoderState*, int, int, double, unsigned long, unsigned long, Scorer*) (ctc_beam_search_decoder.cpp:151)
>   ==28087==    by 0x8DCBA3F: StreamingState::processBatch(std::vector<float, std::allocator<float> > const&, unsigned int) (deepspeech.cc:255)
>   ==28087==    by 0x8DCC490: StreamingState::finishStreamWithMetadata() (deepspeech.cc:149)
>   ==28087==    by 0x8DCC4BE: DS_FinishStreamWithMetadata (deepspeech.cc:390)      
>   ==28087==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
>   ==28087==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0x17A1FE8842FC: ???                                             
>   ==28087==    by 0x17A1FE93D195: ???                                             
>   ==28087==    by 0x17A1FE88535E: ???                                             
>   ==28087==  Block was alloc'd at                                                 
>   ==28087==    at 0x4838DBF: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
>   ==28087==    by 0x8DE2AB1: PathTrie::get_path_trie(int, int, float, bool) (path_trie.cpp:72)
>   ==28087==    by 0x8DCEBB1: decoder_next(double const*, Alphabet const&, DecoderState*, int, int, double, unsigned long, unsigned long, Scorer*) (ctc_beam_search_decoder.cpp:103)
>   ==28087==    by 0x8DCBA3F: StreamingState::processBatch(std::vector<float, std::allocator<float> > const&, unsigned int) (deepspeech.cc:255)
>   ==28087==    by 0x8DCC490: StreamingState::finishStreamWithMetadata() (deepspeech.cc:149)
>   ==28087==    by 0x8DCC4BE: DS_FinishStreamWithMetadata (deepspeech.cc:390)      
>   ==28087==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
>   ==28087==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
>   ==28087==    by 0x17A1FE8842FC: ???                                             
>   ==28087==    by 0x17A1FE93D195: ???    
> ```

Those are a fallout from 95a54bfdb8b2f9d0d2b85cc7b8438c4b11be7e57
