### ISSUE TITLE
Any plans to add model training via pip-install?

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [mozilla/DeepSpeech#2219]
**For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).
...
Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.**

This is not a problem or a bug but I think it belongs here since it's a feature request.

To use DeepSpeech for (pre-trained) model inference, we can `pip install` `deepspeech`/`deepspeech-gpu` without cloning the whole repo. But if we want to (re)train a pretrained model on our own data for transfer learning, (unless I'm mistaken) we have to clone the whole DeepSpeech repository. 

Is there any plan to provide capability for retraining a model / transfer learning via pip install (plus maybe a couple extra steps like `wget`'ing the pretrained model, etc)? For my own project/repo, ideally dependencies just add another line in a Pipfile (and maybe a couple extra install steps), as opposed to requiring a whole new repo installed. Not a big deal though if it's not a priority, just wondering if it's in the plan, and if not wanted to offer it as a (mild) request.

Thanks again for an awesome project!

**Comment by kdavis-mozilla** [comment]
Currently, there is no plan to provide a pip install for retraining a model.

PS: Thanks for the encouraging words!

**Comment by MaxPowerWasTaken** [comment]
Ok thanks for the answer! Feel free to close this issue if you'd like.

**Comment by kdavis-mozilla** [comment]
Closing for now.
