### ISSUE TITLE
Error running session: Not found: PruneForTargets: Some target nodes not found: initialize_state 

### ISSUE THREAD

**Issue by zikola** [mozilla/DeepSpeech#2220]
i was trying to do inference with python native client with the following command
`python3 client.py --model sd/output_graph.pbmm --alphabet sd/alphabet.txt --audio sd/audio.wav`

then i got the following error

> Loading model from file sd/output_graph.pbmm
> TensorFlow: v1.13.1-10-g3e0cc53
> DeepSpeech: v0.5.1-0-g4b29b78
> 2019-06-29 06:10:40.461327: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-06-29 06:10:40.466405: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
> 2019-06-29 06:10:40.466441: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
> 2019-06-29 06:10:40.466455: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
> 2019-06-29 06:10:40.466514: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
> Loaded model in 0.00841s.
> Running inference.
> Error running session: Not found: PruneForTargets: Some target nodes not found: initialize_state

**Comment by lissyx** [comment]
Where is this model coming from? Why do you run client.py directly?

**Comment by zikola** [comment]
it is a model i have trained and i don't know what other method to try the inference on python

**Comment by zikola** [comment]
now i tried the following command as in documentation but same error
`deepspeech --model sd/output_graph.pbmm --alphabet sd/alphabet.txt --audio sd/audio.wav`

**Comment by zikola** [comment]
it seems the problem with the model i tried pre-trained model and it worked so what is gone wrong with own my model

**Comment by lissyx** [comment]
You trained out of master? So your binary is v0.5.1, thus incompatible. Please install some v0.6.0-alpha

**Comment by zikola** [comment]
yes i trained from master like 2 weeks ago ,where can i find v0.6.0 if it is not the version in pip

**Comment by zikola** [comment]
i found it in release and problem solved when i upgrade to v0.6.0-alpha thank you
