### ISSUE TITLE
Error when running deepspeech on GPU

### ISSUE THREAD

**Issue by Scofield666** [mozilla/DeepSpeech#2221]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip install tensorflow-gpu==1.11.0
- **TensorFlow version (use command below)**: pip install tensorflow-gpu==1.11.0
- **Python version**: 3.6.8
- **CUDA/cuDNN version**: cuda 9.0
- **GPU model and memory**: GeForce GTX 1080 Ti

I successfully installed Deepspeech v0.3.0 and configured neccessary environment, but encountered errors when running deepspeech in virtualenv to translate one sample.wav.
The command I use is:

> deepspeech --model models/output_graph.pb --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio samples/sample.wav

The error logging info is:

> Not found: Op type not registered 'AudioSpectrogram' in binary running on ww-X299-UD4. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

It seems that I should configure something in binary file, but I dont know how. Can you help me?

**Comment by lissyx** [comment]
Looks like you are trying to run v0.5 model with v0.3.0. That's not going to work.

**Comment by lissyx** [comment]
@Scofield666 So you are running v0.3.0 binaries with an incompatible model. Either use a v0.3.0 model or v0.5.1 binaries.

Also, you don't need to install `tensorflow-gpu==1.11.0`, this is only required if you perform training.

Please re-open if that's not solving your problem.
