### ISSUE TITLE
Not able to import the pb file in tensorflow

### ISSUE THREAD

**Issue by fanghuaqi** [mozilla/DeepSpeech#2227]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream TensorFlow
- **TensorFlow version (use command below)**: 1.13
- **Python version**:  2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.1
- **GPU model and memory**:   TITAN Xp 12GB
- **Exact command to reproduce**:

I want to load the tf pb model of deepspeech-0.5.1-models using the following commands:
```python
def load_tf_model(tf_model_pb):
    tf.reset_default_graph()
    gpu_options=tf.GPUOptions(allow_growth=True) #, visible_device_list='1'

    sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
    with gfile.FastGFile(tf_model_pb, 'rb') as f: 
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        sess.graph.as_default()
        tf.import_graph_def(graph_def, name='')  

    sess.run(tf.global_variables_initializer())
    return sess
deepsess = load_tf_model('path/to/deepspeech/output_graph.pb')
```

But I am getting the following error message, could you give me some hints what happened?
```
ValueError: NodeDef mentions attr 'feature_win_step' not in Op<name=NoOp; signature= -> >; NodeDef: {{node model_metadata}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

Thanks
Huaqi

**Comment by lissyx** [comment]
> `ValueError: NodeDef mentions attr 'feature_win_step' not in Op<name=NoOp; signature= -> >; NodeDef: {{node model_metadata}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).`

Those are extra-metadata that we add at export.

Can you try running with `evaluate.py` ?

**Comment by mortont** [comment]
I'm seeing the same error when trying to load the 0.5.1 pb model. Loading from the checkpoint works and running `evaluate.py` seems to work fine too (removed the deprecation warnings for brevity).
```
python evaluate.py --checkpoint_dir checkpoint/ --test_files datasets/commonvoice/clips/test_small.csv
I Restored variables from most recent checkpoint at checkpoint/model.v0.5.1, step 467356
Testing model on datasets/commonvoice/clips/test_small.csv
Test epoch | Steps: 3 | Elapsed Time: 0:00:03
Test on datasets/commonvoice/clips/test_small.csv - WER: 0.666667, CER: 0.459459, loss: 113.408905
--------------------------------------------------------------------------------
WER: 1.000000, CER: 0.925926, loss: 304.088928
 - src: "did she ever marry the girl"
 - res: "yes"
--------------------------------------------------------------------------------
WER: 0.800000, CER: 0.360000, loss: 34.971336
 - src: "the cup handle has broken"
 - res: "the cap and it has brought"
--------------------------------------------------------------------------------
WER: 0.000000, CER: 0.000000, loss: 1.166428
 - src: "do you understand that"
 - res: "do you understand that"
--------------------------------------------------------------------------------
```
My pb loading code is essentially the same as @fanghuaqi's but I'm using CPU only. Python version 3.7.3 and tensorflow 1.13.1. I've also tried exporting the working checkpoint to a pb and it has the same error. The GraphDef has the attrs mentioned in the error (as expected)
```python
import tensorflow as tf
from tensorflow.python.platform import gfile

GRAPH_PB_PATH = './DeepSpeech/export/output_graph.pb'
with tf.Session() as sess:
   with tf.gfile.GFile(GRAPH_PB_PATH,'rb') as f:
       graph_def = tf.GraphDef()
       graph_def.ParseFromString(f.read())
       print(graph_def.node[-1])
```
```
name: "model_metadata"
op: "NoOp"
attr {
  key: "feature_win_len"
  value {
    i: 32
  }
}
attr {
  key: "feature_win_step"
  value {
    i: 20
  }
}
attr {
  key: "sample_rate"
  value {
    i: 16000
  }
}
```

**Comment by lissyx** [comment]
@mortont What are you trying to achieve ? Those extra nodes are added at export time to hold some metadata.

**Comment by reuben** [comment]
Why are you trying to load the graph by hand like that?

**Comment by mortont** [comment]
I'd like to use the acoustic model logits as input to my own CTC decoder. Is there a better way to do this?

**Comment by reuben** [comment]
You could load the checkpoint instead, which should work. Or I guess you could try removing the metadata node before loading the frozen GraphDef.

**Comment by mortont** [comment]
Confirmed that loading the checkpoint works. Also, removing the metadata node works, just a simple `del(graph_def.node[-1])`. Thanks!

**Comment by lissyx** [comment]
> Confirmed that loading the checkpoint works. Also, removing the metadata node works, just a simple `del(graph_def.node[-1])`. Thanks!

I guess that means you issue is solved, thanks!
