### ISSUE TITLE
Using pre trained tflite model on android

### ISSUE THREAD

**Issue by ramrahu** [mozilla/DeepSpeech#2229]
Hello,
I have been trying to use your pre trained .tflite model on android app. Its giving me the following error:
**java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [I (which is compatible with the TensorFlowLite type INT32)**
This is when I use the command **tfLite.runForMultipleInputsOutputs(inputArray, outputScoresNames);** to run the model
If I use **tfLite.run(inputs, outputScores);** to run the model, it executes without error but always outputs only the first character in the list.
Could anyone help me with this error??
Thanks in advance.

**Comment by lissyx** [comment]
@ramrahu Please use our bindings ?

**Comment by ramrahu** [comment]
I tried opening your app. Trying to open your app in android studio throws the following errors:
SIMPLE: Build command failed.


SIMPLE: Error while executing process /home/neha/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/neha/DeepSpeech-master/native_client/java/libdeepspeech -B/home/neha/DeepSpeech-master/native_client/java/libdeepspeech/.externalNativeBuild/cmake/release/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/neha/DeepSpeech-master/native_client/java/libdeepspeech/build/intermediates/cmake/release/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/home/neha/Android/Sdk/ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=/home/neha/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/neha/Android/Sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja}


SIMPLE: -- Check for working C compiler: /home/neha/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang


SIMPLE: -- Check for working C compiler: /home/neha/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works


SIMPLE: -- Detecting C compiler ABI info


SIMPLE: -- Detecting C compiler ABI info - done


SIMPLE: -- Detecting C compile features


SIMPLE: -- Detecting C compile features - done


SIMPLE: -- Check for working CXX compiler: /home/neha/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++


SIMPLE: -- Check for working CXX compiler: /home/neha/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works


SIMPLE: -- Detecting CXX compiler ABI info


SIMPLE: -- Detecting CXX compiler ABI info - done


SIMPLE: -- Detecting CXX compile features


SIMPLE: -- Detecting CXX compile features - done


SIMPLE: -- Configuring done


SIMPLE: CMake Error at CMakeLists.txt:13 (add_library):


SIMPLE:     ../jni/deepspeech_wrap.cpp


SIMPLE:   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp


SIMPLE:   .hxx .in .txx


SIMPLE: CMake Error: CMake can not determine linker language for target: deepspeech-jni


SIMPLE: -- Generating done


SIMPLE: -- Build files have been written to: /home/neha/DeepSpeech-master/native_client/java/libdeepspeech/.externalNativeBuild/cmake/release/arm64-v8a

**Comment by lissyx** [comment]
> SIMPLE: CMake Error: CMake can not determine linker language for target: deepspeech-jni

This is not really the same error as you reported. We don't use Android Studio, so I can't really help you if it's related. Have you tried following the documented steps ?

Please keep in mind the android app is just a very basic demo.

**Comment by ramrahu** [comment]
Ya because of this error we built our own app and tried the tflite model. If you didn't use Android Studio, then can I know which platform did you use?

**Comment by lissyx** [comment]
> Ya because of this error we built our own app and tried the tflite model. If you didn't use Android Studio, then can I know which platform did you use?

As documented under `native_client/java/`, nothing specific, just `gradle` in command-line ...

So you wrote your own code, you don't follow the docs, you don't use the java android bindings.

If you don't share more informations, we can't help you. If you run tflite directly, then you should look at the implementation in `native_client/deepspeech.cc` to see how to run.

**Comment by ramrahu** [comment]
Hi
I went through the documentation. I followed the steps. Now when I try to run the command ./gradlew libdeepspeech:build
Execution failed for task ':libdeepspeech:compileDebugJavaWithJavac'

**Comment by lissyx** [comment]
> Hi
> I went through the documentation. I followed the steps. Now when I try to run the command ./gradlew libdeepspeech:build
> Execution failed for task ':libdeepspeech:compileDebugJavaWithJavac'

Again, if you don't share more of the output, it's going to be hard to help.

**Comment by ramrahu** [comment]
This is the output I am getting on executing that command **./gradlew libdeepspeech:build**:


> Configure project :libdeepspeech 
arm64-v8a armeabi-v7a x86_64
> Task :libdeepspeech:compileDebugJavaWithJavac FAILED
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechStreamingState.java:4: error: cannot find symbol
    private SWIGTYPE_p_StreamingState _sp;
            ^
  symbol:   class SWIGTYPE_p_StreamingState
  location: class DeepSpeechStreamingState
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechStreamingState.java:6: error: cannot find symbol
    public DeepSpeechStreamingState(SWIGTYPE_p_StreamingState sp) {
                                    ^
  symbol:   class SWIGTYPE_p_StreamingState
  location: class DeepSpeechStreamingState
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechStreamingState.java:10: error: cannot find symbol
    public SWIGTYPE_p_StreamingState get() {
           ^
  symbol:   class SWIGTYPE_p_StreamingState
  location: class DeepSpeechStreamingState
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:11: error: cannot find symbol
    SWIGTYPE_p_p_ModelState _mspp;
    ^
  symbol:   class SWIGTYPE_p_p_ModelState
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:12: error: cannot find symbol
    SWIGTYPE_p_ModelState   _msp;
    ^
  symbol:   class SWIGTYPE_p_ModelState
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:32: error: cannot find symbol
    public Metadata sttWithMetadata(short[] buffer, int buffer_size, int sample_rate) {
           ^
  symbol:   class Metadata
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:54: error: cannot find symbol
    public Metadata finishStreamWithMetadata(DeepSpeechStreamingState ctx) {
           ^
  symbol:   class Metadata
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:15: error: cannot find symbol
        this._mspp = impl.new_modelstatep();
                     ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:16: error: cannot find symbol
        impl.CreateModel(modelPath, n_cep, n_context, alphabetPath, beam_width, this._mspp);
        ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:17: error: cannot find symbol
        this._msp  = impl.modelstatep_value(this._mspp);
                     ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:21: error: cannot find symbol
        impl.DestroyModel(this._msp);
        ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:25: error: cannot find symbol
        impl.EnableDecoderWithLM(this._msp, alphabet, lm, trie, lm_alpha, lm_beta);
        ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:29: error: cannot find symbol
        return impl.SpeechToText(this._msp, buffer, buffer_size, sample_rate);
               ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:33: error: cannot find symbol
        return impl.SpeechToTextWithMetadata(this._msp, buffer, buffer_size, sample_rate);
               ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:37: error: cannot find symbol
        SWIGTYPE_p_p_StreamingState ssp = impl.new_streamingstatep();
        ^
  symbol:   class SWIGTYPE_p_p_StreamingState
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:37: error: cannot find symbol
        SWIGTYPE_p_p_StreamingState ssp = impl.new_streamingstatep();
                                          ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:38: error: cannot find symbol
        impl.SetupStream(this._msp, prealloc_frames, sample_rate, ssp);
        ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:39: error: cannot find symbol
        return new DeepSpeechStreamingState(impl.streamingstatep_value(ssp));
                                            ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:43: error: cannot find symbol
        impl.FeedAudioContent(ctx.get(), buffer, buffer_size);
        ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:47: error: cannot find symbol
        return impl.IntermediateDecode(ctx.get());
               ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:51: error: cannot find symbol
        return impl.FinishStream(ctx.get());
               ^
  symbol:   variable impl
  location: class DeepSpeechModel
/home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:55: error: cannot find symbol
        return impl.FinishStreamWithMetadata(ctx.get());
               ^
  symbol:   variable impl
  location: class DeepSpeechModel
22 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libdeepspeech:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
10 actionable tasks: 1 executed, 9 up-to-date

**Comment by lissyx** [comment]
> This is the output I am getting on executing that command **./gradlew libdeepspeech:build**:
> 
> > Configure project :libdeepspeech
> > arm64-v8a armeabi-v7a x86_64
> > Task :libdeepspeech:compileDebugJavaWithJavac FAILED
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechStreamingState.java:4: error: cannot find symbol
> > private SWIGTYPE_p_StreamingState _sp;
> > ^
> > symbol:   class SWIGTYPE_p_StreamingState
> > location: class DeepSpeechStreamingState
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechStreamingState.java:6: error: cannot find symbol
> > public DeepSpeechStreamingState(SWIGTYPE_p_StreamingState sp) {
> > ^
> > symbol:   class SWIGTYPE_p_StreamingState
> > location: class DeepSpeechStreamingState
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechStreamingState.java:10: error: cannot find symbol
> > public SWIGTYPE_p_StreamingState get() {
> > ^
> > symbol:   class SWIGTYPE_p_StreamingState
> > location: class DeepSpeechStreamingState
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:11: error: cannot find symbol
> > SWIGTYPE_p_p_ModelState _mspp;
> > ^
> > symbol:   class SWIGTYPE_p_p_ModelState
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:12: error: cannot find symbol
> > SWIGTYPE_p_ModelState   _msp;
> > ^
> > symbol:   class SWIGTYPE_p_ModelState
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:32: error: cannot find symbol
> > public Metadata sttWithMetadata(short[] buffer, int buffer_size, int sample_rate) {
> > ^
> > symbol:   class Metadata
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:54: error: cannot find symbol
> > public Metadata finishStreamWithMetadata(DeepSpeechStreamingState ctx) {
> > ^
> > symbol:   class Metadata
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:15: error: cannot find symbol
> > this._mspp = impl.new_modelstatep();
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:16: error: cannot find symbol
> > impl.CreateModel(modelPath, n_cep, n_context, alphabetPath, beam_width, this._mspp);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:17: error: cannot find symbol
> > this._msp  = impl.modelstatep_value(this._mspp);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:21: error: cannot find symbol
> > impl.DestroyModel(this._msp);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:25: error: cannot find symbol
> > impl.EnableDecoderWithLM(this._msp, alphabet, lm, trie, lm_alpha, lm_beta);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:29: error: cannot find symbol
> > return impl.SpeechToText(this._msp, buffer, buffer_size, sample_rate);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:33: error: cannot find symbol
> > return impl.SpeechToTextWithMetadata(this._msp, buffer, buffer_size, sample_rate);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:37: error: cannot find symbol
> > SWIGTYPE_p_p_StreamingState ssp = impl.new_streamingstatep();
> > ^
> > symbol:   class SWIGTYPE_p_p_StreamingState
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:37: error: cannot find symbol
> > SWIGTYPE_p_p_StreamingState ssp = impl.new_streamingstatep();
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:38: error: cannot find symbol
> > impl.SetupStream(this._msp, prealloc_frames, sample_rate, ssp);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:39: error: cannot find symbol
> > return new DeepSpeechStreamingState(impl.streamingstatep_value(ssp));
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:43: error: cannot find symbol
> > impl.FeedAudioContent(ctx.get(), buffer, buffer_size);
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:47: error: cannot find symbol
> > return impl.IntermediateDecode(ctx.get());
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:51: error: cannot find symbol
> > return impl.FinishStream(ctx.get());
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > /home/neha/DeepSpeech/native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java:55: error: cannot find symbol
> > return impl.FinishStreamWithMetadata(ctx.get());
> > ^
> > symbol:   variable impl
> > location: class DeepSpeechModel
> > 22 errors
> 
> FAILURE: Build failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':libdeepspeech:compileDebugJavaWithJavac'.
> 
> 
> > Compilation failed; see the compiler error output for details.
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
>     * Get more help at https://help.gradle.org
> 
> 
> BUILD FAILED in 0s
> 10 actionable tasks: 1 executed, 9 up-to-date

https://github.com/mozilla/DeepSpeech/blob/master/native_client/java/README.md#android-demo-apk

`make apk`, did you do this ?

**Comment by ramrahu** [comment]
I thought that has to be done after running the ./gradlew command

**Comment by lissyx** [comment]
> I thought that has to be done after running the ./gradlew command

If you read the documentation and the Makefile, you will see that `apk` target will take care of everything.

**Comment by ramrahu** [comment]
Hmm ok I'll try that

**Comment by ramrahu** [comment]
This will work for only the pre trained model? What if I want to use my own trained model? Same procedure?

**Comment by lissyx** [comment]
> This will work for only the pre trained model? What if I want to use my own trained model? Same procedure?

I don't understand your question: another model will just be a different `.tflite` file, no change to the library ...

**Comment by ramrahu** [comment]
I understand from the documentation that it will play an existing audio in the phone. But I don't want that. I want to play an audio, the phone should record & then display the decoded results.
So will running the make apk command serve my purpose?

**Comment by lissyx** [comment]
> I understand from the documentation that it will play an existing audio in the phone. But I don't want that. I want to play an audio, the phone should record & then display the decoded results.
> So will running the make apk command serve my purpose?

The purpose of this APK is to demo a trivial use of the API on Android. Please read the code. The SpeechModule app produced from https://github.com/mozilla/androidspeech/ does mostly what you do, you should read its source code as well.

**Comment by ramrahu** [comment]
ok i'll read through it. how about that error I was getting with that ./gradlew command?

**Comment by lissyx** [comment]
> ok i'll read through it. how about that error I was getting with that ./gradlew command?

Have you ran `make apk` ?

**Comment by ramrahu** [comment]
This is the output I get when I run that command:

./gradlew clean

> Configure project :libdeepspeech 
arm64-v8a armeabi-v7a x86_64

BUILD SUCCESSFUL in 0s
5 actionable tasks: 2 executed, 3 up-to-date
rm -rf *.java jni/deepspeech_wrap.cpp
swig -c++ -java -package org.mozilla.deepspeech.libdeepspeech -outdir libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/ -o jni/deepspeech_wrap.cpp jni/deepspeech.i
jni/deepspeech.i:23: Error: Syntax error in input(1).
make: *** [bindings] Error 1

**Comment by ramrahu** [comment]
It shows an error

**Comment by lissyx** [comment]
>  jni/deepspeech.i:23: Error: Syntax error in input(1).

What version of SWIG do you have N

**Comment by lissyx** [comment]
Right here we do document SWIG >= 3.0.12: https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md#building-deepspeech-binaries

**Comment by ramrahu** [comment]
I had already downloaded it before executing make apk

**Comment by lissyx** [comment]
> I had already downloaded it before executing make apk

You need to be a bit more specific ... Is it properly exposed in your PATH ? What does `swig -version` shows ?

**Comment by lissyx** [comment]
@ramrahu Can you please update us ? Have you been able to use `libdeepspeech` ? https://bintray.com/alissy/org.mozilla.deepspeech/libdeepspeech

**Comment by ramrahu** [comment]
Sorry for late response. Was just trying the app link you shared above. Will get back to you on this in a while.

**Comment by lissyx** [comment]
@ramrahu Can you update us please ?

**Comment by ramrahu** [comment]
Sorry. I did try this, was encountering a few errors. In the meantime I have been trying the other app link you shared with me. I will come back to this in the coming days & update you if I am facing any issues.

**Comment by lissyx** [comment]
You filed an issue for something unrelated and unsupported since you were not using libdeepspeech.so ... So it would be great we get feedback as soon as possible. Either something is missing in our doc or?

**Comment by ramrahu** [comment]
Ok I'll be retrying this some time later this month. Actually stuck with other things in my project. So will get back to you soon. But I don't think its anything missing in your documentation. I seem to be missing something somewhere. I'll retry this from scratch soon

**Comment by lissyx** [comment]
> Ok I'll be retrying this some time later this month. Actually stuck with other things in my project. So will get back to you soon. But I don't think its anything missing in your documentation. I seem to be missing something somewhere. I'll retry this from scratch soon

So since there is no bug here, I'll advise you to instead come and discuss for help on Discourse rather than Github. I'm closing that issue.
