### ISSUE TITLE
Do I need to declare "--decoder_library_path" when training my own models?

### ISSUE THREAD

**Issue by csyang6052** [mozilla/DeepSpeech#2231]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

(1) I executed the following in a terminal -
~/tensorflow$ bazel build -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" //native_client:libctc_decoder_with_kenlm.so
Starting local Bazel server and connecting to it...
ERROR: Skipping '//native_client:libctc_decoder_with_kenlm.so': no such target '//native_client:libctc_decoder_with_kenlm.so': target 'libctc_decoder_with_kenlm.so' not declared in package 'native_client' defined by /home/ubuntu4/tensorflow/native_client/BUILD

(2) I checked ~/DeepSpeech/native_client/BUILD, there is no "tf_cc_shared_object(name = "libctc_decoder_with_kenlm.so", ..." declaration as coded in "https://github.com/mozilla/DeepSpeech/blob/v0.3.0/native_client/BUILD"

(3) My question is, do I need to generate "libctc_decoder_with_kenlm.so" in order to train my own models with declaring the flag "--decoder_library_path" ?

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04

- **TensorFlow installed from (our builds, or upstream TensorFlow)**: r1.13

- **TensorFlow version (use command below)**: 
git clone https://github.com/mozilla/tensorflow.git
git checkout origin/r1.13

- **Python version**: 3.6

- **Bazel version (if compiling from source)**: 0.19.2

- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0 / 7.5.1
- **GPU model and memory**: Nvidia 1080ti
- **Exact command to reproduce**:

**Comment by lissyx** [comment]
@csyang6052 Please use Discourse as documented for questions and help.

**Comment by lissyx** [comment]
> (2) I checked ~/DeepSpeech/native_client/BUILD, there is no "tf_cc_shared_object(name = "libctc_decoder_with_kenlm.so", ..." declaration as coded in "https://github.com/mozilla/DeepSpeech/blob/v0.3.0/native_client/BUILD"

Is your checkout of `v0.3.0` or master ?

What is wrong with pre-built binaries, why do you need to rebuild ?

**Comment by csyang6052** [comment]
master, 
I need to train models for taiwanese using dataset downloaded from Common Voice.

**Comment by lissyx** [comment]
>  I need to train models for taiwanese using dataset downloaded from Common Voice.

I don't see the link here:
 - why would you need to stick to v0.3.0 ?
 - why can't you use prebuilt binaries for `libctc_decoder_with_kenlm.so` if you absolutely need v0.3.0 ?

**Comment by csyang6052** [comment]
(1) My checkout is master, not v0.3.0.
(2) Do I need to generate my own libctc_decoder_with_kenlm.so for a language other than English? If not, where can I download libctc_decoder_with_kenlm.so? If yes, how can generate it?

**Comment by lissyx** [comment]
> (1) My checkout is master, not v0.3.0.

You link doc of v0.3.0, so it's complicated to know what you are trying to do. You don't need `libctc_decoder_with_kenlm` with newer versions but you need a python package (please check the documentation)


>  (2) Do I need to generate my own libctc_decoder_with_kenlm.so for a language other than English? If not, where can I download libctc_decoder_with_kenlm.so? If yes, how can generate it?

Have you found any documentation stating the need to rebuild for a different language ? Because no, there is no need. Have you tried to check the release page? It's documented it is bundled within `native_client` tar.

**Comment by lissyx** [comment]
@csyang6052 Also, can we stop discussing on Github and do so on Discourse ?

**Comment by csyang6052** [comment]
I follow the tutorial - https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830
Is this tutorial proper for the "master" checkout? In this tutorial, --decoder_library_path /home/nvidia/tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so was declared.

**Comment by csyang6052** [comment]
Ok, thanks,

**Comment by lissyx** [comment]
> I follow the tutorial - https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830
> Is this tutorial proper for the "master" checkout? In this tutorial, --decoder_library_path /home/nvidia/tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so was declared.

This tutorial is good except it's old, so `master` from that time has moved on.
