### ISSUE TITLE
How to build a cluster to train model

### ISSUE THREAD

**Issue by hao-olli-ai** [mozilla/DeepSpeech#2246]
I am having 2 individual PCs, please show me the way to setup them into a distributed system to train DS2 model. I could not see any guidelines related to this problem in your document.
Thanks

**Comment by kdavis-mozilla** [comment]
We recently removed the ability to train on a cluster ([Removed distributed training support](https://github.com/mozilla/DeepSpeech/pull/1988)) as we were not using it and maintenance was too much of an overhead fro our small team.
