### ISSUE TITLE
Specified tflite model file version (0) is incompatible with minimum version supported by this client (1)

### ISSUE THREAD

**Issue by isjosan** [mozilla/DeepSpeech#2248]
I have the following environment on my Linux host, on which I have cloned Mozilla DeepSpeech:
Linux kernel: 4.15.0-54-generic
Ubuntu: 18.04.2 LTS
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
Downloaded pre-trained model v0.5.1 with sample audio files and models.

The output_graph.pb and output_graph.pbmm have a successful run with deepspeech inference engine client.

**However, I get the following error with output_graph.tflite:**

$ deepspeech --model ./output_graph.tflite --alphabet ./alphabet.txt --lm ./lm.binary --trie ./trie --audio ../audio/4507-16021-0012.wav
Loading model from file ./output_graph.tflite
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
**Specified model file version (0) is incompatible with minimum version supported by this client (1). See https://github.com/mozilla/DeepSpeech/#model-compatibility for more information**
Traceback (most recent call last):
  File "/home/iqbal/tmp/deepspeech-env/bin/deepspeech", line 10, in <module>
    sys.exit(main())
  File "/home/iqbal/tmp/deepspeech-env/lib/python3.6/site-packages/deepspeech/client.py", line 88, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/iqbal/tmp/deepspeech-env/lib/python3.6/site-packages/deepspeech/__init__.py", line 23, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 8195

**Do I need to use a lower version of deepspeech client; if yes, which version do I need and where do I get it?**

**Comment by isjosan** [comment]
BTW...I tried to re-export the TFlite model from checkpoint, but get the following exception at the end of execution:

$ ./DeepSpeech.py --checkpoint_dir /home/iqbal/DeepSpeech-model-0.5.1/deepspeech-0.5.1-checkpoint  --export_tflite --export_dir /home/iqbal/DeepSpeech-model-0.5.1/deepspeech-0.5.1-models
.................................................................................................................................................
.................................................................................................................................................
**Exception: TensorFlow Lite currently doesn't support control flow ops: Merge, Switch**

**Comment by lissyx** [comment]
@isjosan As documented, current distributed binaries are only intended to run TensorFlow models, not TFLite models, except on Android platforms.

**Comment by lissyx** [comment]
@isjosan We have started experimenting with TFLite lib on other platforms, but it's still experimental. For example, you can find them on this link for your platform: https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.4/tflite

**Comment by limapedro** [comment]
@lissyx Thanks, I was looking for this today, found thi thread and now it's working with tflite, thanks again.

**Comment by lissyx** [comment]
> @lissyx Thanks, I was looking for this today, found thi thread and now it's working with tflite, thanks again.

I'll infer from that comment that this issue can be solved as well for @isjosan. Feel free to re-open if required.
