### ISSUE TITLE
 Error loading libctc_decoder_with_kenlm.so

### ISSUE THREAD

**Issue by Dev1158** [mozilla/DeepSpeech#2251]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 17.3 Rosa
    TensorFlow installed from (our builds, or upstream TensorFlow): conda install
    TensorFlow version (use command below): 1.14
    Python version: 3.6
    GCC/Compiler version (if compiling from source): 5.4.0
    CUDA/cuDNN version: 9.0/7.5
    GPU model and memory: GeForce GTX 1080ti

I downloaded the library libctc_decoder_with_kenlm.so from https://github.com/mozilla/DeepSpeech/releases/download/v0.2.0/native_client.amd64.cpu.linux.tar.xz
And then i tried to call libctc_decoder_with_kenlm.so using tf.load_op_library like this:

(tf14) ww@xxx ~/Downloads/Downloads_backup/native_client.amd64.cpu.linux $ python
Python 3.6.8 |Anaconda, Inc.|
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> a = tf.load_op_library("libdeepspeech.so")
>>> a = tf.load_op_library("libctc_decoder_with_kenlm.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ww/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
>>> a = tf.load_op_library("libdeepspeech.so")
>>> a
<module '6e237d88703da016805889179d3f5baa'>

As you can see, it went wrong when loading libctc_decoder_with_kenlm.so, but it successfully loaded libdeepspeech.so. I just want to load libctc_decoder_with_kenlm.so, any help?

**Comment by lissyx** [comment]
>  I just want to load libctc_decoder_with_kenlm.so, any help?

You are using `r1.14` ? This is not what is documented for DeepSpeech v0.2.0. Mismatching TensorFlow version explains your issue. Please stick to documented version. Any reason you want to continue using this 0.2.0 ? It's old and we don't support it anymore.

**Comment by lissyx** [comment]
For 0.2.0 you need TensorFlow 1.6.0

**Comment by lissyx** [comment]
@Dev1158 Also, Anaconda might introduce issues, we've got several reports from people using this and having similar problems as well.

**Comment by Dev1158** [comment]
So it means that Deepspeech0.2.0 cannot be decoded using Tensorflow1.14.

**Comment by Dev1158** [comment]
Is there some way to build the decoder library for DeepSpeech 0.2.0 using Tensorflow 1.14?

**Comment by Dev1158** [comment]
custom_op_module = tf.load_op_library(decoder_library_path)
  File "/home/www/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

I tried without Anaconda environment still facing the same issue.

**Comment by lissyx** [comment]
> So it means that Deepspeech0.2.0 cannot be decoded using Tensorflow1.14.

Yes, that's right.



> Is there some way to build the decoder library for DeepSpeech 0.2.0 using Tensorflow 1.14?

Maybe, but we don't be able to help nor support that.



> I tried without Anaconda environment still facing the same issue.

I explained you the root cause, I just mentionned that ananconda environment itself will also potentially add some similar / different issues.

**Comment by Dev1158** [comment]
But I was able to use DeepSpeech 0.2.0 using Tensorflow version 1.11. So, Why is it not possible with Tensorflow 1.14?

**Comment by lissyx** [comment]
> But I was able to use DeepSpeech 0.2.0 using Tensorflow version 1.11. So, Why is it not possible with Tensorflow 1.14?

I don't know what you mean, but we never supported anything than 1.6 for this version.

**Comment by Dev1158** [comment]
I was using the library "libctc_decoder_with_kenlm.so" and decoded the DeepSpeech model output while running inference using Tensorflow 1.11.

**Comment by lissyx** [comment]
> I was using the library "libctc_decoder_with_kenlm.so" and decoded the DeepSpeech model output while running inference using Tensorflow 1.11.

I highly doubt so. But if it was **really** working, that was just pure luck.

**Comment by lissyx** [comment]
> running inference using Tensorflow 1.11.

Or that's the point, you were not **training** but **running inference**. The CTC decoder code is statically linked into `libdeepspeech.so` inference library that is being bundled by several bindings, including python ones. TensorFlow package is completely orthogonal to that.

**Comment by Dev1158** [comment]
Okay. Thank you.

**Comment by lissyx** [comment]
@Dev1158 If you want to train on TensorFlow r1.14, please follow the doc and use current master.

**Comment by Dev1158** [comment]
Okay.
