### ISSUE TITLE
Mozilla Tensorflow releases don't match source

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2269]
(I'm posting this here because I can't file issues on the mozilla/tensorflow repo)

A potential gotcha that confused me is that the source code zip files on the Releases page of the mozilla/tensorflow repo are not the same as what's in the branch trees so you get compilation errors. 

Downloading from Releases appears to be the cause of this error:
https://github.com/mozilla/DeepSpeech/issues/2208

It seems like the releases might be something inherited from upstream and they're just the original Tensorflow source. So downloading from the Releases page is like not using the Mozilla fork at all.

I found this confusing so I think the releases should either be removed or updated to reflect the actual content of the Mozilla fork.

**Comment by lissyx** [comment]
> A potential gotcha that confused me is that the source code zip files on the Releases page of the mozilla/tensorflow repo are not the same as what's in the branch trees so you get compilation errors.

Are you talking about https://github.com/mozilla/tensorflow/releases ?

Those tags are from upstream, and the page gets generated automatically.



> So downloading from the Releases page is like not using the Mozilla fork at all.

We never, ever, document doing that.

**Comment by reuben** [comment]
That repo doesn't have releases, just tags. We could create our own tags but I'm not sure how useful that'd be. In every documentation we tell people to clone the repo and use the r1.14 *branch*, not a tag.

**Comment by dabinat** [comment]
>  In every documentation we tell people to clone the repo and use the r1.14 branch, not a tag.
