### ISSUE TITLE
lm::FormatLoadException

### ISSUE THREAD

**Issue by ssetty** [mozilla/DeepSpeech#2276]
Hello,

Attempting speech(wav) to text gives below exception:

deepspeech models/output_graph.pbm Thor.wav models/alphabet.txt models/lm.binary models/trie 

Loading model from file models/output_graph.pbm
2019-07-29 12:26:58.832839: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: models/output_graph.pbm; No such file or directory
Loaded model in 0.001s.
Loading language model from files models/lm.binary models/trie
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/binary_format.cc:131 in void lm::ngram::MatchCheck(lm::ngram::ModelType, unsigned int, const lm::ngram::Parameters&) threw FormatLoadException.
The binary file was built for trie with quantization and array-compressed pointers but the inference code is trying to load probing hash tables
Aborted (core dumped)

Kindly help

**Comment by lissyx** [comment]
@ssetty You are not providing any context, versions, anything. Your error is textbook mixing of incompatible binaries and trie/LM file.

**Comment by ssetty** [comment]
Hi how do I solve this? Can you send compatible versions?

**Comment by lissyx** [comment]
> Hi how do I solve this? Can you send compatible versions?

It's going to be hard to help you if you don't document what you do. We don't hide any version, you are just likely mixing stuff inappropriately.

**Comment by ssetty** [comment]
I have used pre-trained model
wget https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
tar xvfz deepspeech-0.5.1-models.tar.gz

or is it because of incompatible with my existing supporting libraries
libsox2
libstdc++6
libgomp1
libpthread

or  I need to build from scratch ?

**Comment by lissyx** [comment]
And what is your version of binaries? Lack of version in the output is likely a good hint it is not 0.5.1... How did you installed?

**Comment by ssetty** [comment]
pip install deepspeech (python bindings)
version: 0.1.1

If not what binaries version do you require?

Thanks

**Comment by lissyx** [comment]
> If not what binaries version do you require?

`pip install --upgrade deepspeech==0.5.1`

**Comment by ssetty** [comment]
Hello,
I executed
pip install --upgrade **deepspeech==0.5.1**

deepspeech --model models/output_graph.pbm --audio Thor.wav --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie

Loading model from file models/output_graph.pbm
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2019-08-06 10:08:53.490805: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: models/output_graph.pbm; No such file or directory
Traceback (most recent call last):
  File "/home/aic_subscription/anaconda3/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/home/aic_subscription/anaconda3/lib/python3.6/site-packages/deepspeech/client.py", line 88, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/aic_subscription/anaconda3/lib/python3.6/site-packages/deepspeech/__init__.py", line 23, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 12293

**Comment by lissyx** [comment]
>  Not found: models/output_graph.pbm; No such file or directory

Do you read error messages ?

**Comment by ssetty** [comment]
Hi,
File is present.  models folder is present. Why this error appears ?

**Comment by lissyx** [comment]
> Hi,
> File is present. models folder is present. Why this error appears ?

Do you read error messages ? The file is not found. Please check its name.

**`--model models/output_graph.pbm`** or **`--model models/output_graph.pbmm`** ?

**Comment by ssetty** [comment]
Hi,

deepspeech --model models/output_graph.pbmm --audio Thor.wav --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie

Now I am getting model incompatibility error.

Loading model from file models/output_graph.pbmm
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
2019-08-07 01:24:02.917095: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-07 01:24:02.979860: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-08-07 01:24:02.979946: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-08-07 01:24:02.979960: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-08-07 01:24:02.980127: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
Specified model file version (0) is incompatible with minimum version supported by this client (1). See https://github.com/mozilla/DeepSpeech/#model-compatibility for more information
Traceback (most recent call last):
  File "/home/aic_subscription/anaconda3/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/home/aic_subscription/anaconda3/lib/python3.6/site-packages/deepspeech/client.py", line 88, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/aic_subscription/anaconda3/lib/python3.6/site-packages/deepspeech/__init__.py", line 23, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 8195

**Comment by ssetty** [comment]
Kindly help with below. What needs to be done for compatibility issues?

Model compatibility
DeepSpeech models are versioned to keep you from trying to use an incompatible graph with a newer client after a breaking change was made to the code. If you get an error saying your model file version is too old for the client, you should either upgrade to a newer model release, re-export your model from the checkpoint using a newer version of the code, or downgrade your client if you need to use the old model and can't re-export it.

**Comment by lissyx** [comment]
Are you sure this is 0.5.1 model?

**Comment by ssetty** [comment]
Yes....
Pre-trained models
wget https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
tar xvfz deepspeech-0.5.1-models.tar.gz

Log also says..
Loading model from file models/output_graph.pbmm
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78

Thanks

**Comment by lissyx** [comment]
Your error mentions model version 0, that's weird.

**Comment by reuben** [comment]
That happens when loading an older pbmm with a newer client. You're probably using one of the 0.6 alphas?

**Comment by ssetty** [comment]
Hi - what needs to be done?  Please send link for correct binaries version which are compatible.

**Comment by kdavis-mozilla** [comment]
Create a new virtual environment and install deep speech
```
 pip install --upgrade deepspeech==0.5.1
```

**Comment by ssetty** [comment]
Thanks now this works. Creation of virtual env  solved version issues.
How do I custom train? Accuracy needs to be increased.

**Comment by lissyx** [comment]
> Thanks now this works. Creation of virtual env solved version issues.
> How do I custom train? Accuracy needs to be increased.

There are plenty of docs covering that aspect, as well as threads on Discourse. Since there is indeed no bug here, i'll close that issue.
