### ISSUE TITLE
GPU Memory remains allocated (nodejs + deepspeech-gpu.v_0.6.0a4) 

### ISSUE THREAD

**Issue by sogris** [mozilla/DeepSpeech#2277]
- **OS Platform and Distribution**: CentOS release 7.6.1810
- **DeepSpeech version**: deepspeech-gpu@0.6.0-alpha.4
- **Nodejs version**: v12.4.0
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: NVIDIA GeForce GTX 1070, 8 GB
- **Exact command to reproduce**:

I noticed a problem with native nodejs client: deepspeech-gpu
After performing sttWithMetadata - process finished without errors, returning recognized text and timings for every letter. 
 
Then command:
```bash
 DeepSpeech.FreeMetadata(metadata);
 DeepSpeech.DestroyModel(model);
```

should destroy model and GPU memory should be freed, but it remans allocated until whole nodejs process is killed / restarted.

**Comment by lissyx** [comment]
As much as I remember, this is tensorflow's behavior, am I right @reuben ?

**Comment by reuben** [comment]
As far as I know, closing the session should release the GPU memory.

**Comment by sogris** [comment]
Thanks for response. Is there other way how to close tensorflow's session in nodejs than `FreeMetadata` and `DestroyModel`or restarting whole process?

**Comment by reuben** [comment]
No. If you're calling DS_DestroyModel and resources are still not being deallocated that's a TensorFlow bug, because we close the TF Session in DS_DestroyModel.

**Comment by sogris** [comment]
OK, thanks, I will close this issue
