### ISSUE TITLE
Training loss going to Inf when audio_sample_rate=44100

### ISSUE THREAD

**Issue by bernardohenz** [mozilla/DeepSpeech#2279]
Hi, 

I've decided to train a new model using `audio_sample_rate=44100`, but got `training_loss=Inf` (something that did not occur when training with 16k, 22k, 42k). Nonetheless, the model seems to be learning, as the validation loss is getting lower on each epoch.

### Replicating with toy example
I've tried to replicate this issue using yours `run-ldc93s1.sh` script, and got the same results: training loss showing fine for all SR below 44k, but getting `Inf` for 44k (and 44100).

Any ideas?

PS: when training for SR of 48k, another error appears:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 52, available: 48) `

**Comment by kdavis-mozilla** [comment]
I don't think is the place for it, maybe discourse is more appropriate.

That said, without ever trying 44k before, I've only trained on 16k, I'd guess the learning rate may be to blame. Try lowering by factors of 1/2, 1/4, 1/8,... until you don't see an Inf to find the approximate range for the new learning rate.

**Comment by reuben** [comment]
Can you share the audio file you used when replicating it with run-ldc93s1.sh?

**Comment by bernardohenz** [comment]
@reuben I've used the default `LDC93S1.wav` that is downloaded when running the script.

@kdavis-mozilla I think the problem is the computation of `audio_window_samples` (https://github.com/mozilla/DeepSpeech/blob/master/util/config.py#L97) and/or `audio_step_samples` (https://github.com/mozilla/DeepSpeech/blob/master/util/config.py#L100).

Dividing any of the above by a factor of 2 seems to solve the problem. Maybe there's a problem when computing spectrogram or extracting features using the values computed. In case you wonder, the values obtained when using `SR=44100` are: `Audio Window Samples: 1411.2` and  `Audio Step Samples: 882.0`.


PS: even casting `audio_window_samples` to int doesn't solve the problem

**Comment by bernardohenz** [comment]
@reuben I was thinking you were internally converting all audios to the desired SR when loading themfor training, but I think this only occurs in the client.

I've tried to convert the `LDC93S1.wav` to 44k and it seems to work fine in the training now, please ignore the issue.
