### ISSUE TITLE
multithreading example with deepspeech

### ISSUE THREAD

**Issue by Ganofins** [mozilla/DeepSpeech#2280]
how can I use multithreading with deepspeech?

I tried posting on disclosure, but I didn't get any reply

**Comment by kdavis-mozilla** [comment]
The [0.5.1. release notes](https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.1) state under the Known Issues section that

> Code not yet thread safe, having multiple concurrent streams tied to the same model leads to bad transcriptions.

A solution is to have multiple threads each with its own model.

**Comment by Ganofins** [comment]
I tried that but it didn't work out for me

I got blank lines in the output

Can you help me with that?

**Comment by kdavis-mozilla** [comment]
Could you move this to discourse?

I know [eggonlea](https://discourse.mozilla.org/u/eggonlea/summary) has this working already so you can ask [eggonlea](https://discourse.mozilla.org/u/eggonlea/summary) there.

**Comment by Ganofins** [comment]
Ok thanks
