### ISSUE TITLE
generated trie file size with only 9 bytes.

### ISSUE THREAD

**Issue by peterhon123** [mozilla/DeepSpeech#2290]
I have succeed in install deepspeech from DeepSpeech Dockfile(DeepSpeech version is v0.5.1). But i still get the 9 bytes `trie` file. What i did is below 

```
/DeepSpeech/native_client/kenlm/build/bin/lmplz -o 3 --text thchs30_vocabulary.txt --arpa thchs30-words.arpa
/DeepSpeech/native_client/kenlm/build/bin/build_binary -T -s thchs30-words.arpa thchs30-lm.binary
/DeepSpeech/native_client/generate_trie thchs30_alphabet.txt thchs30-lm.binary thchs30-trie
```

And here's the file size.

```
-rwxrwxr-x  1 1005 1005  177947 Aug  5 08:26 thchs30-dev.csv
-rw-r--r--  1 root root 1261151 Aug  6 10:57 thchs30-lm.binary
-rwxrwxr-x  1 1005 1005  495749 Aug  5 08:26 thchs30-test.csv
-rwxrwxr-x  1 1005 1005 1990244 Aug  5 08:24 thchs30-train.csv
-rw-r--r--  1 root root       9 Aug  6 10:58 thchs30-trie
-rw-r--r--  1 root root 1599677 Aug  6 10:57 thchs30-words.arpa
-rwxrwxr-x  1 1005 1005   11532 Aug  5 08:11 thchs30_alphabet.txt
-rwxrwxr-x  1 1005 1005  130492 Aug  5 08:11 thchs30_vocabulary.txt
```

The `trie` file content is below: (vim thchs30-trie)

```
EIRT^C^@^@^@^A
~
~
~                 
```

[Archive.zip](https://github.com/mozilla/DeepSpeech/files/3471853/Archive.zip)

**Comment by reuben** [comment]
This is not a bug. If you're using a character-level LM (every space separated word in `thchs30_vocabulary.txt` is one grapheme long) the trie structure is not needed, so the generated file contains just the header.

**Comment by peterhon123** [comment]
@reuben Thanks reuben. so you mean that i don't need `lm_trie_path` in `.sh` file ? Just like below?

```
#!/bin/sh
set -xe
if [ ! -f DeepSpeech.py ]; then
    echo "Please make sure you run this from DeepSpeech's top level directory."
    exit 1
fi;

python -u DeepSpeech.py \
  --train_files /home/data/data_thchs30/thchs30_csv/test_collection/thchs30-train.csv \
  --dev_files /home/data/data_thchs30/thchs30_csv/test_collection/thchs30-dev.csv \
  --test_files /home/data/data_thchs30/thchs30_csv/test_collection/thchs30-test.csv \
  --train_batch_size 30 \
  --dev_batch_size 30 \
  --test_batch_size 30 \
  --n_hidden 512 \
  --epoch 50 \
  --beam_width 10 \
  --learning_rate 0.0001 \
  --export_dir result/thchs30_model/ \
  --checkpoint_dir result/thchs30_checkpoint/ \
  --alphabet_config_path /home/data/data_thchs30/thchs30_csv/test_collection/thchs30_alphabet.txt \
  --lm_binary_path /home/data/data_thchs30/thchs30_csv/test_collection/thchs30-lm.binary \
```

**Comment by reuben** [comment]
No, you need both. That's why we still generate a trie file even though it's only a 9 byte header.

**Comment by peterhon123** [comment]
@reuben thanks reuben. If that is true, then why my inference result is lack of space like below ?

```
- src: "除 中 文 外 还 将 制 作 英 日 等 外 文 版 软 盘 以 方 便 海 外 用 户"
 - res: "这一安晋图务夫宗的文的外岸儿还将的之的作的一应用的日子转等的用务一个外要有文的儿白儿的儿啊牌它案儿夫一个塞方不边样的儿矮海儿外儿一用五户五不和" 
```

**Comment by reuben** [comment]
That is unrelated to the trie. You'll probably need to remove spaces from your corpus. You should know that using DeepSpeech with character-level LMs/data is not something we've tested. We're working on it, but you might encounter several problems like this where we can't help yet.

**Comment by peterhon123** [comment]
@reuben thanks reuben. I will try more experience. The reason i did that cause i follow https://discourse.mozilla.org/t/training-chinese-model/27769.
