### ISSUE TITLE
Declared but unused variable `aPreAllocFrames`

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/DeepSpeech#2298]
@reuben -- the `aPreAllocFrames` variable in `deepspeech.cc` is declared but unused, unless I'm missing something:

https://github.com/mozilla/DeepSpeech/blob/29836c9dcc4c2e30e57ae6e50d303fbb317325bb/native_client/deepspeech.cc#L332

**Comment by lissyx** [comment]
It looks like its use was removed as part of d9a269412e492ca5046c9ab89f0547be51050159 cc @dabinat

**Comment by lissyx** [comment]
Maybe we should take the opportunity of v0.6 to fix that and remove it from the API
