### ISSUE TITLE
Bad audio format f or WAV

### ISSUE THREAD

**Issue by TrieuLe0801** [mozilla/DeepSpeech#2300]
Hi everyone, I have started training deepspeech with my own Japanese dataset, and I got this issue:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Bad audio format for WAV: Expected 1 (PCM), but got3
	 [[{{node DecodeWav}}]]
	 [[tower_0/IteratorGetNext]]
I am using  Ubuntu 18.04 with Tensorflow 1.14, python 3.6, and bazel 0.24.1. My CUDA version is 10.1

**Comment by lissyx** [comment]
@TrieuLe0801 So you have a bogus file in your dataset ? You need to find which one.

**Comment by TrieuLe0801** [comment]
@lissyx Yeah, I also thought like that. I tried printing to make sure it can load and read the wav files 
-----------------------------------------------------------------------------------------------------------------
I Initializing variables...
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000       /home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent302-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4641.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4968.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent311-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent056-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent166-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent225-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4874.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent288-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent056-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent060-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent282-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent060-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent225-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent288-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4873.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4908.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent166-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4769.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4868.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4672.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent201-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent283-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4713.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent279-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4684.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent201-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4988.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4696.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4751.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4850.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_0394.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/precedent130/wav/PRECEDENT130_070.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4622.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent173-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent202-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4849.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0558.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4626.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4693.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4857.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4878.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0456.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0034.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent159-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_1200.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0637.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/loanword128/wav/LOANWORD128_076.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent045-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4958.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0992.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4692.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4679.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_2549.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4950.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0101.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4737.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/loanword128/wav/LOANWORD128_106.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0553.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent119-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_0146.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0374.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0689.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0862.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/loanword128/wav/LOANWORD128_055.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4756.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent277-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_3290.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0396.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0952.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0821.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4989.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/loanword128/wav/LOANWORD128_078.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent045-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0413.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_3150.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent167-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0507.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4858.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0157.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4867.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4995.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0612.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent221-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4762.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0868.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0794.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4636.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0927.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent172-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2462.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4893.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0550.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0310.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0082.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0071.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0052.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0892.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0745.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0934.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4656.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4629.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0061.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0473.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0772.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent097-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0264.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent186-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0991.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_1610.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0774.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0234.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_1000.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent055-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0579.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0436.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0428.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0063.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4275.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0371.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent002-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent078-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0461.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent029-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2743.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0750.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2571.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0626.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0259.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0073.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2115.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0732.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0865.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4886.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0496.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent246-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0795.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0454.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0607.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0679.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent113-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0654.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4991.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2400.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2410.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0905.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4623.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_2813.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4994.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0649.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent202-phrase2.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_1258.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0467.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_2190.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0185.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/japanese-single-speaker-speech-dataset/wav/meian_6063.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4934.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/utparaphrase512/wav/UT-PARAPHRASE-sent126-phrase1.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_1352.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0372.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_0263.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0877.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_1536.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_4877.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0547.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_1140.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/basic5000/wav/BASIC5000_1251.wav
/home/trieulv/work/deepspeech_mozilla/japanese_data/jsut_ver1.1/travel1000/wav/TRAVEL1000_0443.wav
Traceback (most recent call last):
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Bad audio format for WAV: Expected 1 (PCM), but got3
	 [[{{node DecodeWav}}]]
	 [[tower_0/IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 894, in <module>
    tfv1.app.run(main)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 878, in main
    train()
  File "DeepSpeech.py", line 599, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "DeepSpeech.py", line 567, in run_set
    feed_dict=feed_dict)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/trieulv/work/deepspeech_mozilla/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Bad audio format for WAV: Expected 1 (PCM), but got3
	 [[{{node DecodeWav}}]]
	 [[tower_0/IteratorGetNext]]
---------------------------------------------------------------------------------------------------
I saw it stopped loading at file TRAVEL1000_0443.wav, but I didn't know what was wrong with it. It is as same as format with others

**Comment by lissyx** [comment]
> I saw it stopped loading at file TRAVEL1000_0443.wav, but I didn't know what was wrong with it. It is as same as format with others

Well, TensorFlow seems to disagree ... Remove that file from your dataset ?

**Comment by TrieuLe0801** [comment]
Okay, It works now, thank you.

**Comment by lissyx** [comment]
Thanks, I'll close that 😊
