### ISSUE TITLE
Label validator lets invalid characters through

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2304]
The comments for the label validation function suggest that it is supposed to filter all characters except a-z, space and apostrophe, but that’s definitely not what the code actually does.

The Common Voice English wiki sentences initially had accented characters, some of which made their way into the validated dataset. While this is obviously something that needs to be rectified in the dataset, I think the importers need to handle this better too.

While it would be easy to change it to match what the comment says it’s supposed to do (and I’m happy to do so), this would only be useful for English. A more language-robust method would be to use an alphabet file to filter the characters, but text.py is shared by a bunch of other scripts and I was uneasy about making a change that would affect so many other scripts.

Any advice for how best to implement this?

**Comment by rhamnett** [comment]
I think that's what --normalize is for

**Comment by dabinat** [comment]
It’s not just letters, there are some symbols that don’t get stripped either.

**Comment by rhamnett** [comment]
what is the exact command you ran

**Comment by dabinat** [comment]
I ran it without normalization because I don’t want it normalized because those transcripts aren’t even supposed to be in the dataset. I want the importer to skip them. One would assume given that the argument is called

**Comment by dabinat** [comment]
(Didn’t mean to close it - I hit the wrong button on my phone)

**Comment by rhamnett** [comment]
I ran import_cv2.py with normalize and saw only regular alphabet chars.

**Comment by eggonlea** [comment]
Just FYI. With both of "--filter_alphabet" and "--normalize", the dataset generated by import_cv2.py can be trained correctly. But I didn't check which one (or both) actually did the trick.

**Comment by dabinat** [comment]
I think this may have been caused by another script and is not actually a DeepSpeech issue. I can no longer reproduce this.
