### ISSUE TITLE
E Checkpoint directory(/root/.local/share/deepspeech/checkpoints)does not contain a valid checkpoint state. 

### ISSUE THREAD

**Issue by iekhwang** [mozilla/DeepSpeech#2318]
- OS Platform and Distribution  Linux Ubuntu 16.04
- TensorFlow installed from (our builds, or upstream TensorFlow)**:
- TensorFlow version (use command below): tensorflow-gpu   1.14.0
- Python version: Python 3.6.8 
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version:10.0
- GPU model and memory: Titian Xp 12196MB
- DeepSpeech version:0.6.0-alpha.4

I am training madarin deepspeech model, and run with docker container which generate by the master Dockerfile. I'm not planning to using pre-trainned model, so I did not set the --checkpoint_dir. But when I run the script

```
python -u /DeepSpeech/DeepSpeech.py --noshow_progressbar \
  --train_file /DeepSpeech/cn_corpus/aishell/aishell_train.csv \
  --dev_file /DeepSpeech/cn_corpus/aishell/aishell_dev.csv \
  --test_files /DeepSpeech/cn_corpus/aishell/aishell_test.csv \
  --epochs 20 \
  --learning_rate 0.0001 \
  --train_batch_size 128 \
  --test_batch_size 128 \
  --dev_batch_size 128 \
  --n_hidden 512 \
  --lm_binary_path /DeepSpeech/data/lm/zh_giga.no_cna_cmn.prune01244.klm \
  --alphabet_config_path /DeepSpeech/run_corpus/aishell/data/alphabet.txt \
  --lm_trie_path /DeepSpeech/run_corpus/aishell/data/trie \
  --export_dir /DeepSpeech/models/aishell_moz \
  "$@"
```

and I got this 

```
+ [ ! -f /DeepSpeech/DeepSpeech.py ]
+ export CUDA_VISIBLE_DEVICES=0,1,2,3
+ python -u /DeepSpeech/DeepSpeech.py --noshow_progressbar --train_file /DeepSpeech/cn_corpus/aishell/aishell_train.csv --dev_file /DeepSpeech/cn_corpus/aishell/aishell_dev.csv --test_files /DeepSpeech/cn_corpus/aishell/aishell_test.csv --epochs 20 --learning_rate 0.0001 --train_batch_size 128 --test_batch_size 128 --dev_batch_size 128 --n_hidden 512 --lm_binary_path /DeepSpeech/data/lm/zh_giga.no_cna_cmn.prune01244.klm --alphabet_config_path /DeepSpeech/run_corpus/aishell/data/alphabet.txt --lm_trie_path /DeepSpeech/run_corpus/aishell/data/trie --export_dir /DeepSpeech/models/aishell_moz
W0822 17:56:03.327826 139893056509760 deprecation_wrapper.py:119] From /DeepSpeech/util/config.py:60: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0822 17:56:06.259491 139893056509760 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
W0822 17:56:06.339828 139893056509760 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
W0822 17:56:06.339988 139893056509760 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
W0822 17:56:06.340189 139893056509760 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
W0822 17:56:06.402825 139893056509760 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
**E Checkpoint directory (/root/.local/share/deepspeech/checkpoints) does not contain a valid checkpoint state.**
```

the directory of  /root/.local/share/deepspeech/checkpoints is empty.
Does somebody recently encounter this problem? Is it a version problem?

**Comment by lissyx** [comment]
> **E Checkpoint directory (/root/.local/share/deepspeech/checkpoints) does not contain a valid checkpoint state.**

Loading checkpoint should not even happen if you don't give `--checkpoint_dir`. Is this current master ? Are you referring to https://github.com/mozilla/DeepSpeech/blob/master/Dockerfile ?

Can you share Docker build logs as well ?

**Comment by iekhwang** [comment]
Yes, based on that dockerfile, I built it the day before yesterday and it has successfully built. The DeepSpeech version is 0.6.0-alpha.4. The weird thing is I can successfully run it yesterday, today is not working,always shows the problem like ' **does not contain a valid checkpoint state** ', but I did not change any checkpoint stuff. 

Docker builds log: https://github.com/iekhwang/Mozilla-DeepSpeech-Issues/blob/master/docker-built-log)
Successfully ran log: https://github.com/iekhwang/Mozilla-DeepSpeech-Issues/blob/master/mandarin-train-log

**Comment by iekhwang** [comment]
> > **E Checkpoint directory (/root/.local/share/deepspeech/checkpoints) does not contain a valid checkpoint state.**
> 
> Loading checkpoint should not even happen if you don't give `--checkpoint_dir`. Is this current master ? Are you referring to https://github.com/mozilla/DeepSpeech/blob/master/Dockerfile ?
> 
> Can you share Docker build logs as well ?

Yes, based on that Dockerfile, I built it the day before yesterday and it has successfully built. The DeepSpeech version is 0.6.0-alpha.4. The weird thing is I can successfully run it yesterday, today is not working,always shows the problem like ' does not contain a valid checkpoint state ', but I did not change any checkpoint stuff.

Docker builds log: https://github.com/iekhwang/Mozilla-DeepSpeech-Issues/blob/master/docker-built-log)
Successfully ran log: https://github.com/iekhwang/Mozilla-DeepSpeech-Issues/blob/master/mandarin-train-log

**Comment by iekhwang** [comment]
OK, I think I deleted the old checkpoints in (/root/.local/share/deepspeech/checkpoints) this file, because it always shows the --n_hidden is not matched when I changed the --n_hidden to 512. But I don't think this is the main problem.

**Comment by reuben** [comment]
> Loading checkpoint should not even happen if you don't give `--checkpoint_dir`.

`--checkpoint_dir` has a default value of `xdg.BaseDirectory.save_data_path(os.path.join('deepspeech', 'checkpoints'))`, which is where the path in this issue is coming from.

**Comment by iekhwang** [comment]
> > Loading checkpoint should not even happen if you don't give `--checkpoint_dir`.
> 
> `--checkpoint_dir` has a default value of `xdg.BaseDirectory.save_data_path(os.path.join('deepspeech', 'checkpoints'))`, which is where the path in this issue is coming from.

Yes, I know that is a default path. Can I disable checkpoints when I training? Because I want to train a new model, not load any checkpoint. I'm trying to set --checkpoint_dir '', but it also not works.

**Comment by reuben** [comment]
If you want to train a new model just specifying an empty folder is enough. This is a use case that's exercised daily by several people, something weird is going on with your setup.

**Comment by iekhwang** [comment]
> If you want to train a new model just specifying an empty folder is enough. This is a use case that's exercised daily by several people, something weird is going on with your setup.

I set it to empty or ' ' or a directory path

`  --checkpoint_dir  "" \`
`  --checkpoint_dir  " " \`
`  --checkpoint_dir  /DeepSpeech/checkpoints/aishell_moz`

it gives the feedback like this 

`E Checkpoint directory (/root/.local/share/deepspeech/checkpoints) does not contain a valid checkpoint state.
`
`E Checkpoint directory ( ) does not contain a valid checkpoint state.`
`E Checkpoint directory (/DeepSpeech/checkpoints/aishell_moz) does not contain a valid checkpoint state.`

So I was confused, is the --checkpoint_dir an input directory or output directory or both?

**Comment by lissyx** [comment]
> So I was confused, is the --checkpoint_dir an input directory or output directory or both?

It's both, and it's working for everybody, so there's something in your setup, as said before.

**Comment by eggonlea** [comment]
That error happens in inference stage. I guess you changed the code to bypass the whole training process.

**Comment by javeedrahman** [comment]
Even for me when I start training a new model it is continuing from the previous training from a release model checkpoint, I have deleted /root/.local/share/deepspeech/checkpoints and also specified empty folder before I start training a model.

**Comment by lissyx** [comment]
> Even for me when I start training a new model it is continuing from the previous training from a release model checkpoint, I have deleted /root/.local/share/deepspeech/checkpoints and also specified empty folder before I start training a model.

Please check your environment. Looks like there is no issue or nothing actionable here.
