### ISSUE TITLE
Error running session: Not found: PruneForTargets: Some target nodes not found: initialize_state

### ISSUE THREAD

**Issue by gqy2468** [mozilla/DeepSpeech#2319]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux ubuntu 4.4.0-116-generic
TensorFlow installed from (our builds, or upstream TensorFlow): upstream TensorFlow
TensorFlow version (use command below): 1.14.0
Python version: 3.5.2
CUDA/cuDNN version: use CPU
GPU model and memory: use CPU

When I was using my own model. I got this errror as follow:

> deepspeech --model models-thchs30/output_graph.pb --alphabet models-thchs30/thchs30-alphabet.txt --lm models-thchs30/thchs30-lm.binary --trie models-thchs30/thchs30-trie --audio a11_0.wav
> TensorFlow: v1.13.1-10-g3e0cc53
> DeepSpeech: v0.5.1-0-g4b29b78
> ...
> Loaded model in 0.0213s.
> Loading language model from files models-thchs30/thchs30-lm.binary models-thchs30/thchs30-trie
> Error: Can't parse trie file, invalid header. Try updating your trie file.
> Loaded language model in 0.00135s.
> Running inference.
> Error running session: Not found: PruneForTargets: Some target nodes not found: initialize_state
> Segmentation fault

Is there anyone can tell me what's happened?

**Comment by gqy2468** [comment]
Here is my training script : [https://github.com/gqy2468/DeepSpeech/blob/master/bin/run-thch30.sh](https://github.com/gqy2468/DeepSpeech/blob/master/bin/run-thch30.sh)

**Comment by gqy2468** [comment]
Here is my trie file : 
[thchs30-trie.zip](https://github.com/mozilla/DeepSpeech/files/3532623/thchs30-trie.zip)
Why my trie file's format is not binary format?

**Comment by lissyx** [comment]
> Is there anyone can tell me what's happened?

Can you tell us what you did ?

**Comment by gqy2468** [comment]
I have re-generate my trie file by using the commands as follow (refer to [https://github.com/mozilla/DeepSpeech/blob/master/data/lm/README.md](https://github.com/mozilla/DeepSpeech/blob/master/data/lm/README.md)):

```
/DeepSpeech/native_client/kenlm/build/bin/lmplz -o 3 --text thchs30_vocabulary.txt --arpa thchs30-words.arpa
/DeepSpeech/native_client/kenlm/build/bin/build_binary -T -s thchs30-words.arpa thchs30-lm.binary
/DeepSpeech/native_client/generate_trie thchs30_alphabet.txt thchs30-lm.binary thchs30-trie
```

And my trie file format is correct, and maybe I should train the model again?!

**Comment by lissyx** [comment]
> I have re-generate my trie file by using the commands as follow (refer to https://github.com/mozilla/DeepSpeech/blob/master/data/lm/README.md):

Was that from master ? Your inference log shows running 0.5.1 binary. If you trained on master, then your files are not compatible.

**Comment by gqy2468** [comment]
Yes, I trained on master! And now I get the error as follow: 

> Error: Trie file version mismatch (4 instead of expected 3). Update your trie file.

**Comment by gqy2468** [comment]
Here is my new trie file: 
[thchs30-trie.zip](https://github.com/mozilla/DeepSpeech/files/3533441/thchs30-trie.zip)

**Comment by lissyx** [comment]
> Yes, I trained on master! And now I get the error as follow:
> 
> > Error: Trie file version mismatch (4 instead of expected 3). Update your trie file.

I guess I gave you the answer ? Train / infer on matching versions ?

**Comment by gqy2468** [comment]
I upgraded my deepspeech by using `pip install deepspeech --upgrade`, and now the error has disappeared! And now it's running inference, maybe I should wait the result for some minutes?

**Comment by gqy2468** [comment]
Why the newest version of deepspeech is v0.6.0 on windows, but v0.5.0 on ubuntu?The problem still exists on ubuntu!!!

**Comment by lissyx** [comment]
> Why the newest version of deepspeech is v0.6.0 on windows, but v0.5.0 on ubuntu?The problem still exists on ubuntu!!!

`pip install --upgrade deepspeech` should not install you alpha versions ...

**Comment by lissyx** [comment]
Now, as you can see here https://pypi.org/project/deepspeech/0.6.0a5/#files, we have 0.6.0a5 for both systems, so I don't know why it would not insall, unless you start sharing more errors / feedback from pip ...

**Comment by gqy2468** [comment]
I have stay on this status for some minutes and there are no errors! Why?

![无标题](https://user-images.githubusercontent.com/5274484/63578169-7c39c980-c5c2-11e9-88d2-ffa3d1ab8912.png)

**Comment by lissyx** [comment]
> I have stay on this status for some minutes and there are no errors! Why?
> 
> ![无标题](https://user-images.githubusercontent.com/5274484/63578169-7c39c980-c5c2-11e9-88d2-ffa3d1ab8912.png)

I won't reply to a screenshot.

**Comment by gqy2468** [comment]
Sorry, now I get the inference result, but the time seems be too long! However, thanks for your answers!

> 可 是 阳 春 烟 景 大 块 文 张 的 底 色 四 月 的 林 峦 更 是 绿 的 生 活 秀 美 十 一 二 十
> Inference took 1117.604s for 7.800s audio file.

**Comment by lissyx** [comment]
> Sorry, now I get the inference result, but the time seems be too long! However, thanks for your answers!
> 
> > 可 是 阳 春 烟 景 大 块 文 张 的 底 色 四 月 的 林 峦 更 是 绿 的 生 活 秀 美 十 一 二 十
> > Inference took 1117.604s for 7.800s audio file.

See github issues / discourse discussion, this is known on large alphabets.
