### ISSUE TITLE
Feature window/step length in samples can be a floating point value with different sample rates, breaks the export graph

### ISSUE THREAD

**Issue by vcjob** [mozilla/DeepSpeech#2323]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:only flags and Deepspeech.py a bit.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:linux 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:1.14 gpu
- **Python version**: 3.6.8
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0
- **GPU model and memory**:rtx2080ti
- **Exact command to reproduce**:

Hello to everyone!
For some reasons I can not export the model after finishing the training (right after the test phase). I got the error: _ValueError: Ambiguous dimension: 705.6
ValueError: Error converting shape to a TensorShape: Ambiguous dimension: 705.6._
I execute Deepspeech.py with root priveleages. Training goes well, over 10 epoch, then I stop it myself as it tends to overfit. So it breaks training and continues with testing, and fails upon its end.
Model has 2080 hidden layer width (was changed multiple times during other training attemps).
Here are exporting params:
 _f.DEFINE_string('export_dir', '/ssd/ru_speech_ds/models/Deepspeech/', 'directory in which exported models are stored - if omitted, the model won\'t get exported')
    f.DEFINE_boolean('remove_export', False, 'whether to remove old exported models')
    f.DEFINE_boolean('export_tflite', False, 'export a graph ready for TF Lite engine')
    f.DEFINE_integer('n_steps', 16, 'how many timesteps to process at once by the export graph, higher values mean more latency')
    f.DEFINE_string('export_language', 'ru', 'language the model was trained on e.g. "en" or "English". Gets embedded into exported model.')_
Checkpoints are saved well. 
I'm not sure, but maybe it somehow related to the fact I updated the Deepspeech repo version (around a month ago I trained other models with no exporting problems).
Thank you for any suggestion!

![image](https://user-images.githubusercontent.com/51916323/63779602-7f4cf680-c8ef-11e9-8d19-282f6cf85b97.png)

**Comment by kdavis-mozilla** [comment]
If you stop training by hand, e.g. Control-C, how do you know the last checkpoint is completely and correctly written to disk?

PS: Please do not include screen shots. Include text to allow for searching.

**Comment by vcjob** [comment]
> If you stop training by hand, e.g. Control-C, how do you know the last checkpoint is completely and correctly written to disk?
> 
> PS: Please do not include screen shots. Include text to allow for searching.

Sorry for the screen shot.
I don't know that 100%, but earlier with the early-stopping feature turned on I had the same problem. 
If I can not use ctrl+c, how do I suppose to stop training to get the right, not overfitted model? If I click _ctrl+c_ there still will be the "_best_devel_checkpoint_", right? So the model would be generated from that one. 
Let me also mention, that I waited for 2 more epoch after the last _best_dev_checkpoint_ was saved. So this should not be the case.

**Comment by kdavis-mozilla** [comment]
As to how stop training without overfitting, early stopping prevents overfitting.

If you use Control-C there's no guarantee on the validity of any files that are being written. So you should not use it or you'll end up in situations like you are now.

PS: Can we move this to [discourse](https://discourse.mozilla.org/c/deep-speech) as it appears there's no bug per se

**Comment by reuben** [comment]
705.6 is 22050*0.032. Are you using 22050 Hz audio files for training? The problem here, as indicated by the stack in the error message, is that Config.audio_window_samples is a floating point value (computed from the sample rate and feature window length), which is not a valid dimension for a shape.

I *think* adding a `ceil` call there, in this case making it 706 samples long, would be fine. But you'd also have to check every other part of the code that depends on the sample rate, feature window length, and step length, to make sure they're handling this correctly.

Or you can tweak the feature_win_len flag to some value that when multiplied by your sample rate is an integer.

Or you can downsample your files to 16000 Hz.

**Comment by vcjob** [comment]
> 705.6 is 22050*0.032. Are you using 22050 Hz audio files for training? The problem here, as indicated by the stack in the error message, is that Config.audio_window_samples is a floating point value (computed from the sample rate and feature window length), which is not a valid dimension for a shape.
> 
> I _think_ adding a `ceil` call there, in this case making it 706 samples long, would be fine. But you'd also have to check every other part of the code that depends on the sample rate, feature window length, and step length, to make sure they're handling this correctly.
> 
> Or you can tweak the feature_win_len flag to some value that when multiplied by your sample rate is an integer.
> 
> Or you can downsample your files to 16000 Hz.

Thank you for the explanation!
I actually thought that _ f.DEFINE_integer('audio_sample_rate', 22050, 'sample rate value expected by model') _ lets me normally run the code with no tweaks. Am I wrong? What that flag searves for?
So, the best (the most clear) solution for now seems to be downsample all audio to 16000 Hz, right?

**Comment by reuben** [comment]
It should work, but apparently no one ever tested it with 22050 Hz. I suspect there will be similar edge cases in the native client, where we're probably truncating to int instead of ceiling.

**Comment by reuben** [comment]
And yes, in general resampling to 16kHz is the safest choice with DeepSpeech since all the data we use is 16kHz.

**Comment by vcjob** [comment]
> And yes, in general resampling to 16kHz is the safest choice with DeepSpeech since all the data we use is 16kHz.

Thank you a lot! I will try. Have a good one!

**Comment by reuben** [comment]
Added a diagnostic message in #2568
