### ISSUE TITLE
taskcluster --- six and decoder issue. 

### ISSUE THREAD

**Issue by Tortoise17** [mozilla/DeepSpeech#2333]
Dear Friends and support. 

I am facing some issues with deepspeech. Out of which one is here. 

```
DeepSpeech-master]$ python util/taskcluster.py --target .
Traceback (most recent call last):
  File "util/taskcluster.py", line 13, in <module>
    import six.moves.urllib as urllib
ModuleNotFoundError: No module named 'six'
```

although I have installed six in environment of python3. 

I am confuse. Also, I am not able to install decoder. 
Please help and guide. 

For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by lissyx** [comment]
> although I have installed six in environment of python3.

Obviously, not. If you don't share details on your setup, we can't help.



> Also, I am not able to install decoder.
> Please help and guide.

Same, we can't do divination on your errors. If you refuse to share details we will have to close the issue.

**Comment by Tortoise17** [comment]
Hi. 

I have just started from start and this was command which I run after installations of requirement.

**Comment by lissyx** [comment]
> Hi.
> 
> I have just started from start and this was command which I run after installations of requirement.

You said you had installed `six`, now you say you did nothing ?

**Comment by Tortoise17** [comment]
Steps I did. 

1) I clone Deepspeech
2) made conda environments for deepspeech to be installed there
3) Installed requirements
4) then this step task cluster. 
5) six error. as shown above.

**Comment by lissyx** [comment]
> made conda environments for deepspeech to be installed there

As documented, please use vanilla python and virtualenv instead of anaconda


> Installed requirements

`six` is part of the `requirements.txt` file


> then this step task cluster.

No `load the virtual environment step` ?

**Comment by Tortoise17** [comment]
of course the requirements are installed in virtual env. as below. 

1) clone deepspeech
2) conda create -n speech python=3.6
3) activated the environment as conda activate speech
4) Installed requirements
5) then this step task cluster.
6) six error. as shown above.

python conda virtual environment is active. !!

**Comment by lissyx** [comment]
> python conda virtual environment is active. !!

Well, again, do not use conda. Share all, precise steps. Your current console output does not show any `PS1` matching a Python virtual env enabled ...

**Comment by Tortoise17** [comment]
Can you guide what is PS1 matching a python env? or steps to create it?

as the packages in pip list are below 


DeepSpeech]$ pip3 list
Package    Version
---------- -------
pip        19.2.3 
setuptools 39.2.0 
six        1.12.0 


DeepSpeech]$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                          Version                      
-------------------------------- -----------------------------
backports.ssl-match-hostname     3.5.0.1                      
Beaker                           1.5.4                        
blivet                           0.61.15.72                   
Brlapi                           0.6.0                        
cffi                             1.6.0                        
chardet                          2.2.1                        
configobj                        4.7.2                        
configshell-fb                   1.1.23                       
coverage                         3.6b3                        
cryptography                     1.7.2                        
cupshelpers                      1.0                          
custodia                         0.3.1                        
decorator                        3.4.0                        
di                               0.3                          
dnspython                        1.12.0                       
enum34                           1.0.4                        
ethtool                          0.8                          
firstboot                        19.5                         
fros                             1.0                          
futures                          3.1.1                        
gssapi                           1.2.0                        
idna                             2.4                          
iniparse                         0.4                          
initial-setup                    0.3.9.43                     
iotop                            0.6                          
ipaclient                        4.6.4                        
ipaddr                           2.1.11                       
ipaddress                        1.0.16                       
ipalib                           4.6.4                        
ipaplatform                      4.6.4                        
ipapython                        4.6.4                        
ipaserver                        4.6.4                        
IPy                              0.75                         
isc                              2.0                          
javapackages                     1.0.0                        
jwcrypto                         0.4.2                        
kdcproxy                         0.3.2                        
kitchen                          1.1.1                        
kmod                             0.1                          
langtable                        0.0.31                       
libvirt-python                   4.5.0                        
lvm                              2.02.180-2-RHEL7.-2018-07-20-
lxml                             3.2.1                        
M2Crypto                         0.21.1                       
Magic-file-extensions            0.2                          
Mako                             0.8.1                        
MarkupSafe                       0.11                         
MySQL-python                     1.2.5                        
netaddr                          0.7.5                        
netifaces                        0.10.4                       
nose                             1.3.7                        
ntplib                           0.3.2                        
numpy                            1.7.1                        
openlmi                          0.5.0                        
Paste                            1.7.5.1                      
perf                             0.1                          
pip                              19.2.3                       
ply                              3.4                          
policycoreutils-default-encoding 0.1                          
psycopg2                         2.5.1                        
pyasn1                           0.1.9                        
pyasn1-modules                   0.0.8                        
pycparser                        2.14                         
pycups                           1.9.63                       
pycurl                           7.19.0                       
pygobject                        3.22.0                       
pygpgme                          0.3                          
pyinotify                        0.9.4                        
pykickstart                      1.99.66.19                   
pyliblzma                        0.5.3                        
PyOpenGL                         3.1.0b2                      
pyOpenSSL                        0.13.1                       
pyparsing                        1.5.6                        
pyparted                         3.9                          
pysmbc                           1.0.13                       
python-augeas                    0.5.0                        
python-dateutil                  1.5                          
python-dmidecode                 3.10.13                      
python-ldap                      2.4.15                       
python-linux-procfs              0.4.9                        
python-meh                       0.25.2                       
python-nss                       0.16.0                       
python-yubico                    1.2.3                        
pytz                             2016.10                      
pyudev                           0.15                         
pyusb                            1.0.0b1                      
pywbem                           0.7.0                        
pyxattr                          0.5.1                        
PyYAML                           3.10                         
qrcode                           5.0.1                        
requests                         2.6.0                        
rtslib-fb                        2.1.63                       
scdate                           1.10.6                       
schedutils                       0.4                          
seobject                         0.1                          
sepolicy                         1.1                          
setproctitle                     1.1.6                        
setroubleshoot                   1.1                          
setuptools                       0.9.8                        
slip                             0.4.0                        
slip.dbus                        0.4.0                        
SSSDConfig                       1.16.2                       
subprocess32                     3.2.6                        
targetcli-fb                     2.1.fb46                     
targetd                          0.8.5                        
Tempita                          0.5.1                        
urlgrabber                       3.10                         
urllib3                          1.10.2                       
urwid                            1.1.1                        
virtualenv                       15.1.0                       
yum-langpacks                    0.4.2                        
yum-metadata-parser              1.1.4

**Comment by Tortoise17** [comment]
Something worked now. I think I should close this now. !!! thank you for kind help. I will open new issue. Because I am stuck at next stage. //

**Comment by Tortoise17** [comment]
Thank you so much for kind help.

**Comment by lissyx** [comment]
> Can you guide what is PS1 matching a python env? or steps to create it?

Bash PS1, your shell ...


> DeepSpeech]$ pip3 list
> DeepSpeech]$ pip list

Here we go, you are mixing versions ...

**Comment by lissyx** [comment]
> Because I am stuck at next stage.

Please make sure you read documentation and share actionable data.

**Comment by Tortoise17** [comment]
Sure sir, I am happy with your immediate help I will share my all steps detailed and the error. with the data files. in few minutes. // in new issue.
