### ISSUE TITLE
Model training only on 26164 audio files

### ISSUE THREAD

**Issue by shan18** [mozilla/DeepSpeech#2334]
I am trying to run the training by following the **Training Your Own Model** section in the README.

I first downloaded the common voice English dataset. Then ran the script `bin/import_cv2.py` but it only converts 26164 audio files to .wav i.e. only those files which are mentioned in the train, dev and test tsv files which are just a unique subset of files present in validation.tsv

Aren't we required to use the full dataset for training to reproduce the results or just the small dataset will work?
If we need the full dataset then can someone please guide me in the right direction on how to proceed so that I can reproduce the exact results.

**Comment by reuben** [comment]
We have used just the unique subset in our release models.

**Comment by shan18** [comment]
Thank you for the response @reuben. So to reproduce the results, I should use the full validation.tsv right?

**Comment by reuben** [comment]
No, just the train/dev/test splits created by the script.

-- reuben

**Comment by shan18** [comment]
I did that already. I used only the train/dev/test splits created by the script (which have 26,164 wav files) and the loss on the test set I got was 131.93

The trained model generates the same text for every audio it gets. I think 26,164 samples are just too less to train the model.

**Comment by dabinat** [comment]
Common Voice doesn't have enough data at the present time to generate a production-quality model. The solution is to obtain additional data sources or wait until Common Voice has accrued more data.

You're not the first person to be confused by this so I filed an issue to list the number of unique hours on the Datasets page: https://github.com/mozilla/voice-web/issues/2201

**Comment by shan18** [comment]
Okay, I understand now.
Can you please just help me out with the following questions as well?
1. How many unique hours of data would I need to train a production-ready model?
2. If possible, can you tell me what dataset was used by mozilla to train their DeepSpeech model in order to get such good accuracy?

**Comment by kdavis-mozilla** [comment]
>     1. How many unique hours of data would I need to train a production-ready model?

Depends on you application and the target language.

For unrestricted speech on the order of 5k hours of audio, maybe more. For a command and control application, much less. The exact amount would depend on the number of commands and the variance in the end user's speech patterns.

>     2. If possible, can you tell me what dataset was used by mozilla to train their DeepSpeech model in order to get such good accuracy?

This if documented in the [release notes](https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.1), Fisher, LibriSpeech, and Switchboard training corpora.

**Comment by shan18** [comment]
Okay, I understand now. Thanks a lot.
