### ISSUE TITLE
Install instructions from readme fail

### ISSUE THREAD

**Issue by sargense** [mozilla/DeepSpeech#2335]
I am following the pip install instructions from the readme in arch linux and it is saying that it installed correctly, but I have no deepspeech command AND much of the code in DeepSpeech.py if pasted and run independently fails. 

While I don't expect the team to make the library work for every system ever, can you please place within the readme a distribution with a given setup that is guaranteed to work or a docker container build. Something like built and tested on Ubuntu 18... with these libraries installed via apt-get ...

**Comment by dabinat** [comment]
Did you use pip or pip3? It should be pip3 but the pip command on your system may be pointing to the earlier version.

**Comment by lissyx** [comment]
We got several reports from people running arch and it works. Can you describe exactly what you do?

**Comment by sargense** [comment]
I literally copy-pasted the instructions from the readme. Starting with "pip3 install deepspeech". The next command after that "deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio_file.wav" didn't work. In fact, I don't have a "deepspeech" command at all. I didn't get an error in the install, pip claimed deepspeech was installed without issue.

But I don't want an issue to ask for how to ensure deepspeech works on my particular linux system. I would like the readme to include a guaranteed build environment. Like spin X OS in cloud provider of choice or in VM on your machine, install X,Y,Z and it will work. It could be Ubuntu, Debian, CentOS, etc. I can figure out the specifics of getting it to run on whatever system if it's appropriate to build on top of later, but it's nice to have a quick guaranteed path for experimentation to see how it goes. I did another speech recognition ML experiment and would also like to give these models a try.

**Comment by lissyx** [comment]
This is already what we do document. Have you properly setup a virtualenv as documented?

**Comment by kdavis-mozilla** [comment]
For the [latest release](https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.1) we provide a list of supported platforms which includes "Linux x86 64 bit with a modern CPU" and also "Linux x86 64 bit with a modern CPU + NVIDIA GPU". So it's surprising that the install fails.

Also for the latest release we include a [Docker](https://github.com/mozilla/DeepSpeech/blob/v0.5.1/Dockerfile) file too.

**Comment by lissyx** [comment]
> In fact, I don't have a "deepspeech" command at all. I didn't get an error in the install, pip claimed deepspeech was installed without issue.

Honestly, without more context, that just looks like you have not followed the documentation and created a Python virtualenv. And so the deepspeech binary is installed, and it's path is not in your `$PATH`. Which would be taken care of with virtualenv.

**Comment by sargense** [comment]
The request (which can be turned down) is for having a simple do 1,2,3 series of instructions that would be guaranteed to work on a fresh system obtainable via container, VM, or cloud provider, not debugging a particular system.

In fact, when moving to clean systems from a cloud provider both GPU and CPU, I ran into other errors when just doing a blind copy-paste starting at the top of the readme. But the errors weren't the same on any given system.

I figured it out and got it to work, so the above isn't a big deal. I did my test of deepspeech vs. another neural network. The ask was just a request (which can be turned down) to make that process simple and quick with a guaranteed instruction set. I've always appreciated it in other projects when the devs say, we built this on Debian after installing A,B,C then did steps 1,2,3. Sometimes that resolves some unexpected bugs caused by some library or another using a different version as a dependency in one distro vs another which can be very helpful when moving from platform to platform with a given project.

**Comment by lissyx** [comment]
> he ask was just a request (which can be turned down) to make that process simple and quick with a guaranteed instruction set.

The answer is that **we do that, relying on virtualenv**. You still have not replied on whether you properly followed those steps.



> I've always appreciated it in other projects when the devs say, we built this on Debian after installing A,B,C then did steps 1,2,3.

Again, we document how to setup virtualenv and install. That should work for everybody.

**Comment by lissyx** [comment]
> The request (which can be turned down) is for having a simple do 1,2,3 series of instructions

https://github.com/mozilla/DeepSpeech/blob/master/README.md#using-the-python-package

# Create
# Activate
# Install

How does that not qualify ?

**Comment by sargense** [comment]
I never questioned that the needed information wasn't available. 

The readme has step 3 first, step 2 second, and step 1 third. The suggestions was for tested on $OS and then steps 1,2,3. This doesn't have to be at the top. I've already gotten deepspeech to work in more than one way. Thanks.

**Comment by lissyx** [comment]
I'd really love to understand what did not work for you, it would really be useful that you share what problem you faced ...

**Comment by lissyx** [comment]
> the exact commands in the GIF at the top of the readme it doesn't work on all systems...

Commands in that GIF are outdated, I think we should just get rid of it or update it ? cc @kdavis-mozilla

**Comment by sargense** [comment]
So not in a venv, the key is "pip install requirements.txt". Pretty standard fare. I just like to have the quick test this out and see if it works for you option. Deepspeech performed pretty well, so it's probably worth getting to work in a variety of setups (I'll be trying the docker build next but adding some other standard DS packages (like Jupyter) and work on adding my own simple API for file uploads that go into a job queue).

With venv:
Tested on Ubuntu 16.0.4

1) apt-get update
2) apt-get install python-virtualenv (try apt-get install python3-virtualenv if 3 does not install by default (it should))
3) apt install python3-pip
4) apt-get install wget
5) virtualenv -p python3 $HOME/tmp/deepspeech-venv/
6) source $HOME/tmp/deepspeech-venv/bin/activate
7) wget https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
8) tar -xzvf deepspeech-0.5.1-models.tar.gz
9) pip3 install deepspeech 
10) deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio_file.wav

Without a virtualenv:
Tested on Ubuntu 16.0.4

1) apt-get update
2) apt-get install git
3) apt install python3-pip
4) apt-get install wget
5) git clone https://github.com/mozilla/DeepSpeech.git
6) cd DeepSpeech/
7) pip install -r requirements.txt 
8) wget https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
9) tar -xzvf deepspeech-0.5.1-models.tar.gz 
10) deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio_file.wav

**Comment by lissyx** [comment]
> So not in a venv, the key is "pip install requirements.txt". Pretty standard fare.

Honestly, I'm lost. You ask for "easy to reproduce setup", which is what we provide. And then you start with something else. And your statement is wrong, `requirements.txt` is required in any case, but that's for training.



> I just like to have the quick test this out and see if it works for you option.

Again, that's exactly what we do document with the virtualenv ...

**Comment by sargense** [comment]
It would be nice, it is a wish, that it could be as easy as it looks in the GIF at the top of the readme. That's it, there is nothing more to the issue other than that. Just a copy-paste these items in this exact order and you have a working deepspeech model. I am not saying the items are not in the readme, but they are not in order.

The readme, does not start with venv. You have a GIF that shows pip install deepspeech, then downloads and extracts the models, run deepspeech and that's it. The first two steps in the text are pip install then run. The actual first step is setting up venv which at the top is only "recommended". 

Also, not sure what you mean by requirements.txt is wrong, I ran "pip install -r requirements.txt" and it worked. I had a working deepspeech install without setting up a venv.

I already know all of the information is in the readme in one section or another. The request is for someone coming to the project with a system with little to no data science or python packages built-up to be able to do steps 1-? in order and get a working install.

I didn't know coming to the project if I was going to be a tourist and just run it once and move on or continue using the project if the test results were good. So it's always nice to have a quick test that can be run as proof that a given project works as advertised hence the desire to have something that is literally as easy as it looks in the GIF at the top of the readme. Nothing more to it than that.

**Comment by lissyx** [comment]
> It would be nice, it is a wish, that it could be as easy as it looks in the GIF at the top of the readme. That's it, there is nothing more to the issue other than that. Just a copy-paste these items in this exact order and you have a working deepspeech model. I am not saying the items are not in the readme, but they are not in order.

Now we progress. Please, do not hesitate to suggest a better ordering.


> something that is literally as easy as it looks in the GIF at the top of the readme

Well, that's already the case. The GIF is outdated wrt the command line parameters etc., but up-to-date instructions would end up in the same.

**Comment by lissyx** [comment]
> > It would be nice, it is a wish, that it could be as easy as it looks in the GIF at the top of the readme. That's it, there is nothing more to the issue other than that. Just a copy-paste these items in this exact order and you have a working deepspeech model. I am not saying the items are not in the readme, but they are not in order.
> 
> Now we progress. Please, do not hesitate to suggest a better ordering.

My point being that we need your feedback to understand what is to be changed in the current doc.

**Comment by reuben** [comment]
We should update the GIF for the new params. And probably put the virtualenv creation in the first code listing, as a mandatory step. People who already know how virtualenv works can adapt as needed but I guess it'll simplify the text as a whole.

**Comment by reuben** [comment]
@sargense I have no idea how your example number two (without a virtualenv) is working, because it's not supposed to. The `deepspeech` binary is installed when you do `pip install deepspeech`, which is missing from that example. There's probably some namespace pollution happening and you're using the binary installed in the previous step, or something like that.

**Comment by kdavis-mozilla** [comment]
> Commands in that GIF are outdated, I think we should just get rid of it or update it ? cc @kdavis-mozilla

I'm all for getting rid of it @reuben why do you think it's useful to keep?

**Comment by reuben** [comment]
Updated the readme: https://github.com/mozilla/DeepSpeech/pull/2343

**Comment by sargense** [comment]
> @sargense I have no idea how your example number two (without a virtualenv) is working, because it's not supposed to. The `deepspeech` binary is installed when you do `pip install deepspeech`, which is missing from that example. There's probably some namespace pollution happening and you're using the binary installed in the previous step, or something like that.

My bad. Definitely not namespace pollution because each install test was done on a fresh cloud instance spun up for testing. But I definitely did "pip3 install deepspeech" and accidentally dropped that piece when editing the paste from history. But testing on different cloud instances and providers, pipping requirements before pip3 installing deepspeech will not always work and sometimes other configuring or dependency installs have to be done.

The new steps in the readme make it exactly as easy it looked in the GIF.
