### ISSUE TITLE
Make examples first-class citizens

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#2338]
Feedback from some workshop is that we should pay more attention to the quality and working status of the examples we have in the repossitory to help people.

- [x] Have CI running on examples #2353
- [x] Ensure examples works with latest stable version #2351 
- [x] Improve documentation by referring to examples
- [x] Once v0.6, stick examples to it

**Comment by nmstoker** [comment]
Having clear examples to confirm basic functionality would be very useful to deter the kind of naïve posts seen so often from people who've barely read the installation details, tried to go "off road", got into trouble and then post a limited description, expecting help :slightly_smiling_face: 

I sympathise with the temptation to try something new with the exciting toys but if they can't be sure it's working for the basics then they can easily waste loads of time and don't learn necessary context (eg how long inference or training should typically take on their system)

**Comment by lissyx** [comment]
We'll close when the last item is done.

**Comment by lissyx** [comment]
This was completed with the release of v0.6.
