### ISSUE TITLE
Unbounded probability

### ISSUE THREAD

**Issue by chrisspen** [mozilla/DeepSpeech#2347]
The probability returned in the metadata doesn't appear to be bounded, so I'm having trouble interpreting it.

I usually see floats between 40-90, so I thought it was being returned as a percent, but occasionally it returns values like 109.969795227050, which don't make sense. It doesn't appear to be log likelihood either, as exp(109) is still out of bounds.

Is probability a percent but somehow unbounded and allows values greater than 100?

If not, how do you convert the probability returned in the metadata to a true probability bounded between 0:1?

**Comment by dabinat** [comment]
If I recall correctly, when this was implemented one of the devs said that the probability isn't really interpretable by itself but can be used to compare the confidence of a transcription with an alternative transcription.

But I agree that a percentage that could be used independently of other transcriptions would be more useful.

**Comment by chrisspen** [comment]
Someone correct me if I'm wrong, but now I'm thinking the probability being returned is actually a logit value, not a raw probability. Following [this explanation])(https://sebastiansauer.github.io/convert_logit2prob/), if I convert the probability value returned in the metadata via `math.exp(p / (1. + p))` that gives me a value that's always bounded between 0 and 1.

**Comment by reuben** [comment]
Yeah, this field should have a better name like "confidence". It's a sum of the log-odds over the entire transcription/beam. You can convert it to be bounded between 0 and 1, but should still not interpret the value in isolation.

**Comment by lissyx** [comment]
@chrisspen We've renamed to `confidence` and improved doc, I'm closing this issue, feel free to open a new one if you have other feedback :)
