### ISSUE TITLE
Loading BaiduEN8K from DeepSpeech2

### ISSUE THREAD

**Issue by tylercollins590** [mozilla/DeepSpeech#2348]
I have been conducting testing with DeepSpeech on the accuracy of my recordings. I've found that if I use the original DeepSpeech2 from Baidu, using their model, I tend to get better transcription results. I believe this is because it was trained on over 8,000 hours of their own data.

Is it possible to run the BaiduEN8K model from their initial implementation, in this DeepSpeech implementation?

Link to original: https://github.com/PaddlePaddle/DeepSpeech

Thank you

**Comment by reuben** [comment]
It is not possible
