### ISSUE TITLE
Update examples to use latest version of DeepSpeech

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2351]
A lot of our examples are pinned to v0.4.1. It'd be nice to update them, specially after the breaking changes in #2350.

**Comment by lissyx** [comment]
Yeah, that was the next item after #2338

**Comment by Tortoise17** [comment]
@ reuben
Dear Reuben.

I have to ask question regarding examples with DeepSpeech.
While using only CPUs / e.g., 12 cores (no hyper threading), and using common voice. Can you give idea from any of the example dataset how much time it should take to train a model with default parameters. (Like training depends on GBs (volume) or minutes of the dataset). Please guide in this context. No GPU is involved in training.

**Comment by lissyx** [comment]
> Dear Support
> 
> I have to ask question regarding examples with DeepSpeech.
> While using only CPUs / e.g., 12 cores 64GB RAM (no hyper threading), and using common voice. Can you give idea from any of the example dataset how much time it should take to train a model with default parameters. (Like training depends on GBs (volume) or minutes of the dataset). Please guide in this context. No GPU is involved in training.

Please use Discourse and do not hijack unrelated issues.
