### ISSUE TITLE
DeepSpeechConsole throws System.AccessViolationException on Startup

### ISSUE THREAD

**Issue by larsbeck** [mozilla/DeepSpeech#2363]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow version**: v1.13.1-10-g3e0cc5374d from (sttClient.PrintVersions();)
- **DeepSpeech version**: v0.5.1-0-g4b29b78 (from sttClient.PrintVersions();)
- **Exact command to reproduce**:
1) Clone repo
2) Open native_client\dotnet\DeepSpeech.sln in Visual Studio
3) Add "DeepSpeech" Nuget package version 0.5.1 to DeepSpeechClient project
4) Download models and put them into native_client\dotnet\DeepSpeechConsole\bin\x64\Debug
5) Run DeepSpeechConsole project

```           
 var resultCode = NativeImp.DS_CreateModel(aModelPath,
                            aAlphabetConfigPath,
                            aBeamWidth,
                            ref _modelStatePP);
```

throws System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

Is there anything else I need to do to get the sample up and running?

**Comment by lissyx** [comment]
Obviously not something we experience in CI. Maybe @carlfm01 can have more insights ?

**Comment by carlfm01** [comment]
Hello @larsbeck, make sure that you are using 0.5.1 models, can you please share more info about your audio?
Additionally can you debug step by step prior to the error using VS?

**Comment by larsbeck** [comment]
I took the models from here: https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz

I am not getting to the point where audio is loaded. I am simply starting the Sample. The exception is thrown in line 65 of the Console App "DeepSpeechConsole".

I can debug into sttClient.CreateModel and in this method the exception gets thrown as described above. That would be line 63 in DeepSpeech.cs.

**Comment by carlfm01** [comment]
Yes, you are using the correct models, now can you make sure that vs is using x64 on your configuration manager? Sometimes VS resets it, I know it is a pain.
https://discourse.mozilla.org/t/compiling-for-windows/32939/67?u=carlfm01

Sorry, I dont use teamviewer/Skype

**Comment by larsbeck** [comment]
@carlfm01 Yes, it is set to x64.

**Comment by carlfm01** [comment]
> FWIW: When I create another build architecture (x86) I am getting the expected: "An unhandled exception of type 'System.BadImageFormatException' occurred in DeepSpeechClient.dll
> Additional information: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"

That's excpected, DS only runs on x64 configuration.



> I don't need to install things, right?

No, I'm deploying to end user machines and it only needs .Net Framework.



> The steps in my initial post are sufficient, right?

Yes, looks correct. Please before installing the NuGet remove any reference to local projects, then clean the solution and now install the NuGet.

**Comment by larsbeck** [comment]
@carlfm01 There are no references to local projects other than DeepSpeechConsole referencing DeepSpeechClient. And that reference is needed to build. I cleaned the solution and rebuilt but that didn't change anything.

I have uploaded the contents of bin\x64\Debug here: https://uni-paderborn.sciebo.de/s/lvf90f369uEE4qw in case you want to try and run it on your machine.

Of course, I didn't include the contents of https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz which I also have in that folder.

Any other ideas?

**Comment by carlfm01** [comment]
With your files it fails, and looks like somehow it is still holding the lastest reference of DeepSpeechClient, so I removed it manually from reference/projects and then installed the NuGet, now it will warn about missing params, that due to a recent change to the params, only need to aply this change: https://github.com/carlfm01/DeepSpeech/commit/c05eac7f47520c62e86b8ed3a6822becb63a56af

**Comment by larsbeck** [comment]
@carlfm01 Oh, I see the issue now. I thought the Nuget package would only contain the prebuilt .so file, but it is basically a build of the DeepSpeechClient project plus the .so file. It works now thanks!

I do have a follow up issue though. When I use the -GPU package instead of the normal one, there are two issues. The first one is that the .so file does not get added as a project item and hence it is not automatically copied to the build folder. I copied the .so file manually to bin\x64\Debug like it automatically happens with the normal DeepSpeech Nuget package. But for some reason I still get a DllNotFoundException, which is a little odd, since it resides side by side in the same folder with the rest of the files.
Should I open another issue to track this and close this issue?

**Comment by carlfm01** [comment]
Yes, the initial issue has been solved. Please open a new issue with Visual Studio version, Net version, and any other information that you may consider relevant. We faced that issue before so, I'll investigate.

Closing this one.
