### ISSUE TITLE
tflite 1.14 mfcc bug

### ISSUE THREAD

**Issue by bobzsj87** [mozilla/DeepSpeech#2369]
Tensorflow Lite 1.14 has its MFCC bug which is only fixed in 1.15 (https://github.com/tensorflow/tensorflow/commit/d5cc8288d939b522982738370facd456a0a643ba#diff-915f08d7b1773558bfc1a6cd8ed8785cR75) and (https://github.com/tensorflow/tensorflow/issues/26174). I found DeepSpeech also uses MFCC Op in TF Lite in the native client, how does it make it to work with tf 1.14.0? Does the native client bypass that bug?

I export the model (which is OK) to tflite, but the Python Interpreter can't properly load the model and has NumDimension assertion failed.

**Comment by reuben** [comment]
I was the one who filed that bug :)

Yes, we workaround it in our tensorflow fork/native client: https://github.com/mozilla/tensorflow/commit/164adb28df02f3375185cf5f8f25624e0a9c9083
