### ISSUE TITLE
Cannot Install on Windows 10

### ISSUE THREAD

**Issue by tentekal** [mozilla/DeepSpeech#2370]
I've been trying to install DeepSpeech on Windows 10, both through pip/pip3:

`pip install deepspeech`
`Collecting deepspeech
  ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none)
ERROR: No matching distribution found for deepspeech`

As well as directly from a wheel (I have tried both the 35, 36, and 37 python version of the wheel):

`pip install deepspeech-0.5.1-cp36-cp36m-win_amd64.whl`
`ERROR: deepspeech-0.5.1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.`

All of these attempts were made in a virtualenv created for python 3.6, as stated below. I double-checked the supported platforms and it looks like this should be supported. Please let me know if I'm missing any information. 

**System Information:**
- OS: Windows 10 Enterprise
- Version: 1803
- OS Build: 17134.984

- Python Ver: Python-36-32

**Comment by lissyx** [comment]
>     * Python Ver: Python-36-32

Try 64-bits version ?

**Comment by tentekal** [comment]
Sounds likely, I attempted to install TensorFlow from source as well, and ran into architecture targeting errors (x86 vs x64). I'll give this a shot and report back.

**Comment by tentekal** [comment]
Sorry for the delay, even a basic install in an Enterprise is a hassle. 

This cleared up my issue right away, but you may want to capture the 64bit requirement in the documentation. Tensorflow may have done this and I overlooked it, but it can't hurt to duplicate that here. 

Thanks again!
