### ISSUE TITLE
404 error downloading  convert_graphdef_memmapped_format file from upstream

### ISSUE THREAD

**Issue by deevyea** [mozilla/DeepSpeech#2378]
Hi, 

 I am getting 404 Error while downloading convert_graphdef_memmapped_format file. Looks like an upstream issues. Would you please have a look and help is much appreciated.

Please find the command below to reproduce the issue.
```
python util/taskcluster.py --target target-util --source tensorflow --artifact convert_graphdef_memmapped_format

Downloading https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/convert_graphdef_memmapped_format ...
Traceback (most recent call last):
  File "util/taskcluster.py", line 157, in <module>
    main()
  File "util/taskcluster.py", line 151, in main
    maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact, args.branch))
  File "util/taskcluster.py", line 57, in maybe_download_tc
    urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
The same issue when I try to access from the browser. Could you please help me out here.
I have followed the thread from this link --> https://discourse.mozilla.org/t/how-to-create-a-mmap-able-model-from-the-output-graph-pb-file/28984

No luck so far!

**Comment by lissyx** [comment]
> Hi,
> 
> I am getting 404 Error while downloading convert_graphdef_memmapped_format file. Looks like an upstream issues. Would you please have a look and help is much appreciated.
> 
> Please find the command below to reproduce the issue.
> 
> ```
> python util/taskcluster.py --target target-util --source tensorflow --artifact convert_graphdef_memmapped_format
> 
> Downloading https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/convert_graphdef_memmapped_format ...
> Traceback (most recent call last):
>   File "util/taskcluster.py", line 157, in <module>
>     main()
>   File "util/taskcluster.py", line 151, in main
>     maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact, args.branch))
>   File "util/taskcluster.py", line 57, in maybe_download_tc
>     urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 248, in urlretrieve
>     with contextlib.closing(urlopen(url, data)) as fp:
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> ```
> 
> The same issue when I try to access from the browser. Could you please help me out here.
> I have followed the thread from this link --> https://discourse.mozilla.org/t/how-to-create-a-mmap-able-model-from-the-output-graph-pb-file/28984
> 
> No luck so far!

No, that's expected, please use `--branch`, this should generate branch link like: https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/convert_graphdef_memmapped_format

I'm not sure how to make that more clear in the docs, it's already stated at several places that TensorFlow version should be X for DeepSpeech release Y.

**Comment by lissyx** [comment]
@deevyea I'm closing this since there is no issue here. If you think docs should be improved, you are welcome to open a new issue and explain what / where it is unclear and/or send a PR :)
