### ISSUE TITLE
Windows executable is not working converted wav files

### ISSUE THREAD

**Issue by Israrulhaq190** [mozilla/DeepSpeech#2388]
Hi Guys,
I am trying to use deepspeech in windows using executable build 

When i run the below command:
deepspeech.exe  --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 1.wav

it says:

\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'deepspeech.exe  --model models\output_graph.pbmm --alphabet models\alphabet.txt --lm models\lm.binary --trie models\trie --audio audios\1.wav' returned non-zero exit status 3221226505.

**Comment by Israrulhaq190** [comment]
Also, what does it mean:
Assertion failed: num_channels == 1, file client.cc, line 231

**Comment by reuben** [comment]
It means your audio file is not mono. You're probably forgetting to specify that in the conversion process.

**Comment by Israrulhaq190** [comment]
> It means your audio file is not mono. You're probably forgetting to specify that in the conversion process.
I have convert it into mono as well and it's processing without errors but there is still no output. As you can see the details buffer size is also zero. I am testing on files shared by deepspeech all 3 audio files are working fine but i don't know what's the issue with my converted file.

audio_format=1
num_channels=1
sample_rate=16000
bits_per_sample=16
res.buffer_size=0

**Comment by reuben** [comment]
How are you converting it?

**Comment by Israrulhaq190** [comment]
ffmpeg -i audios/"+str(aud)+" -acodec pcm_s16le -ac 1 -ar 16000 audios/"+str(aud.split('.')[0])+ ".wav

**Comment by Israrulhaq190** [comment]
in simple words:
ffmpeg -i input.mp4 -acodec pcm_s16le -ac 1 -ar 16000 output.wav

**Comment by Israrulhaq190** [comment]
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function
''' import libraries to disable warnings'''
import warnings
import logging, os
warnings.filterwarnings('ignore')
logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import subprocess
import csv,wave

cwd = os.getcwd()
aud_dir = str(cwd) + '/audios/'
aud_names = os.listdir(aud_dir)

if not os.path.exists(str(cwd)+'/results/'):
    os.makedirs('results')

for audi in aud_names:
    aud = audi
    if '.mp4' in aud:
        command = "ffmpeg -i audios/"+str(aud)+" -acodec pcm_s16le -ac 1 -ar 16000 audios/"+str(aud.split('.')[0])+ ".wav"
        aud = aud.split('.')[0]+".wav"
        subprocess.call(command, shell=True)
    with open('results/'+str(aud.split('.')[0]+str(".csv")),mode='w') as csv_file:
        csv_writer = csv.writer(csv_file,delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerow(['File Name', 'Audio Text'])
        batcmd="deepspeech.exe  --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio audios/"+str(aud)
        result = subprocess.check_output(batcmd, shell=True)
        res = "{}".format(result.decode("utf-8"))
        print(res)
        csv_writer.writerow([str(audi), str(res)])

**Comment by Israrulhaq190** [comment]
`# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function
''' import libraries to disable warnings'''
import warnings
import logging, os
warnings.filterwarnings('ignore')
logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import subprocess
import csv,wave

cwd = os.getcwd()
aud_dir = str(cwd) + '/audios/'
aud_names = os.listdir(aud_dir)

if not os.path.exists(str(cwd)+'/results/'):
    os.makedirs('results')

for audi in aud_names:
    aud = audi
    if '.mp4' in aud:
        command = "ffmpeg -i audios/"+str(aud)+" -acodec pcm_s16le -ac 1 -ar 16000 audios/"+str(aud.split('.')[0])+ ".wav"
        aud = aud.split('.')[0]+".wav"
        subprocess.call(command, shell=True)
    with open('results/'+str(aud.split('.')[0]+str(".csv")),mode='w') as csv_file:
        csv_writer = csv.writer(csv_file,delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerow(['File Name', 'Audio Text'])
        batcmd="deepspeech.exe  --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio audios/"+str(aud)
        result = subprocess.check_output(batcmd, shell=True)
        res = "{}".format(result.decode("utf-8"))
        print(res)
        csv_writer.writerow([str(audi), str(res)])
`

**Comment by reuben** [comment]
Well, it looks like ffmpeg is writing a size of 0 for the audio data in the file. Can you share the original and converted file that causes the problem?

**Comment by Israrulhaq190** [comment]
Actually, original is video file i.e .mp4 and converted form is .wav file. which is playing audio when i run the file.

![Capture](https://user-images.githubusercontent.com/23098447/65782602-71e19100-e167-11e9-9c0b-24d50920e7d7.PNG)

**Comment by Israrulhaq190** [comment]
Both the files are present at this link:
https://drive.google.com/drive/folders/1XKHy0pPkqZXJAikpHH9rYuuWpOPXvOBN?usp=sharing

**Comment by Israrulhaq190** [comment]
> Well, it looks like ffmpeg is writing a size of 0 for the audio data in the file. Can you share the original and converted file that causes the problem?


I have shared the screenshot of the script. if you want i can add my python file as well.

**Comment by reuben** [comment]
Instead of calling deepspeech using that script, can you call it manually with the problem file and post the log? Please copy and paste the log rather than attaching a screenshot.

**Comment by Israrulhaq190** [comment]
> Instead of calling deepspeech using that script, can you call it manually with the problem file and post the log? Please copy and paste the log rather than attaching a screenshot.


Sure. Sorry for that. This is the logs i have after executing on the shell or command line directly.

TensorFlow: v1.13.1-10-g3e0cc5374d
DeepSpeech: v0.5.1-0-g4b29b78
2019-09-27 15:56:59.499809: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-09-27 15:56:59.514789: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-09-27 15:56:59.519325: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-09-27 15:56:59.525106: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-09-27 15:56:59.530153: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
audio_format=1
num_channels=1
sample_rate=16000
bits_per_sample=16
res.buffer_size=0

**Comment by Israrulhaq190** [comment]
Files provided at this link works fine:
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/audio-0.5.1.tar.gz

here is the result after executing one of those files.

(base) C:\Users\israr\Desktop\sample\native_client.amd64.cpu.win>deepspeech.exe  --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 2830-3980-0043.wav
TensorFlow: v1.13.1-10-g3e0cc5374d
DeepSpeech: v0.5.1-0-g4b29b78
2019-09-27 16:01:28.475058: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-09-27 16:01:28.490500: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-09-27 16:01:28.496062: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-09-27 16:01:28.502660: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-09-27 16:01:28.507335: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
audio_format=1
num_channels=1
sample_rate=16000
bits_per_sample=16
res.buffer_size=63200
**experience proof this**

**Comment by lissyx** [comment]
> here is the result after executing one of those files.

Please keep in mind that this `deepspeech.exe` is only intended as demo purpose, and it's explicitely very limited.

**Comment by Israrulhaq190** [comment]
This is mentioned on Official Readme
"Currently, only 16-bit, 16 kHz, mono-channel WAVE audio files are supported in the Python client".

I have also converted and verified using mediainfo in ubuntu for both the files.
Media Info for example file given by deepspeech officials.

mediainfo 4507-16021-0012.wav
General
Complete name                            : 4507-16021-0012.wav
Format                                   : Wave
File size                                : 85.5 KiB
Duration                                 : 2 s 735 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 256 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 2 s 735 ms
Bit rate mode                            : Constant
Bit rate                                 : 256 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 16.0 kHz
Bit depth                                : 16 bits
Stream size                              : 85.5 KiB (100%)

**Comment by Israrulhaq190** [comment]
And this is for the converted file which i have problem.

mediainfo test.wav
General
Complete name                            : test.wav
Format                                   : Wave
File size                                : 216 KiB
Duration                                 : 6 s 919 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 256 kb/s
Writing application                      : Lavf58.29.100

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 6 s 919 ms
Bit rate mode                            : Constant
Bit rate                                 : 256 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 16.0 kHz
Bit depth                                : 16 bits
Stream size                              : 216 KiB (100%)

**Comment by reuben** [comment]
The problem is ffmpeg, it's creating a header that doesn't match the output we expect. Same file but `test_sox.wav` was converted from wav to wav using sox:

```
$ xxd ~/Downloads/test.wav | head
00000000: 5249 4646 3861 0300 5741 5645 666d 7420  RIFF8a..WAVEfmt
00000010: 1000 0000 0100 0100 803e 0000 007d 0000  .........>...}..
00000020: 0200 1000 4c49 5354 1a00 0000 494e 464f  ....LIST....INFO
00000030: 4953 4654 0e00 0000 4c61 7666 3538 2e32  ISFT....Lavf58.2
00000040: 392e 3130 3000 6461 7461 f260 0300 0000  9.100.data.`....
00000050: 0000 0000 ffff ffff feff fdff fbff faff  ................
00000060: f8ff f6ff f5ff f2ff f0ff eeff ecff e9ff  ................
00000070: e7ff e4ff e0ff dfff dcff daff d8ff d4ff  ................
00000080: d4ff d1ff d2ff d1ff d1ff d0ff d0ff d1ff  ................
00000090: d1ff d2ff d0ff d1ff d2ff d5ff d7ff daff  ................
$ xxd ~/Downloads/test_sox.wav | head
00000000: 5249 4646 1661 0300 5741 5645 666d 7420  RIFF.a..WAVEfmt
00000010: 1000 0000 0100 0100 803e 0000 007d 0000  .........>...}..
00000020: 0200 1000 6461 7461 f260 0300 0000 0000  ....data.`......
00000030: 0000 ffff ffff feff fdff fbff faff f8ff  ................
00000040: f6ff f5ff f2ff f0ff eeff ecff e9ff e7ff  ................
00000050: e4ff e0ff dfff dcff daff d8ff d4ff d4ff  ................
00000060: d1ff d2ff d1ff d1ff d0ff d0ff d1ff d1ff  ................
00000070: d2ff d0ff d1ff d2ff d5ff d7ff daff ddff  ................
00000080: deff e3ff e6ff e9ff ebff eeff f2ff f6ff  ................
00000090: f8ff feff ffff 0800 0900 0d00 1300 1900  ................
```

**Comment by Israrulhaq190** [comment]
> The problem is ffmpeg, it's creating a header that doesn't match the output we expect. Same file but `test_sox.wav` was converted from wav to wav using sox:
> 
> ```
> $ xxd ~/Downloads/test.wav | head
> 00000000: 5249 4646 3861 0300 5741 5645 666d 7420  RIFF8a..WAVEfmt
> 00000010: 1000 0000 0100 0100 803e 0000 007d 0000  .........>...}..
> 00000020: 0200 1000 4c49 5354 1a00 0000 494e 464f  ....LIST....INFO
> 00000030: 4953 4654 0e00 0000 4c61 7666 3538 2e32  ISFT....Lavf58.2
> 00000040: 392e 3130 3000 6461 7461 f260 0300 0000  9.100.data.`....
> 00000050: 0000 0000 ffff ffff feff fdff fbff faff  ................
> 00000060: f8ff f6ff f5ff f2ff f0ff eeff ecff e9ff  ................
> 00000070: e7ff e4ff e0ff dfff dcff daff d8ff d4ff  ................
> 00000080: d4ff d1ff d2ff d1ff d1ff d0ff d0ff d1ff  ................
> 00000090: d1ff d2ff d0ff d1ff d2ff d5ff d7ff daff  ................
> $ xxd ~/Downloads/test_sox.wav | head
> 00000000: 5249 4646 1661 0300 5741 5645 666d 7420  RIFF.a..WAVEfmt
> 00000010: 1000 0000 0100 0100 803e 0000 007d 0000  .........>...}..
> 00000020: 0200 1000 6461 7461 f260 0300 0000 0000  ....data.`......
> 00000030: 0000 ffff ffff feff fdff fbff faff f8ff  ................
> 00000040: f6ff f5ff f2ff f0ff eeff ecff e9ff e7ff  ................
> 00000050: e4ff e0ff dfff dcff daff d8ff d4ff d4ff  ................
> 00000060: d1ff d2ff d1ff d1ff d0ff d0ff d1ff d1ff  ................
> 00000070: d2ff d0ff d1ff d2ff d5ff d7ff daff ddff  ................
> 00000080: deff e3ff e6ff e9ff ebff eeff f2ff f6ff  ................
> 00000090: f8ff feff ffff 0800 0900 0d00 1300 1900  ................
> ```


Thank you, But is there any way to convert it using any other command line tool so that i can use it in my python script ?

**Comment by lissyx** [comment]
> This is mentioned on Official Readme
> "Currently, only 16-bit, 16 kHz, mono-channel WAVE audio files are supported in the Python client".
> 
> I have also converted and verified using mediainfo in ubuntu for both the files.

My point being: code is hand-crafted for reading perfectly formatted WAVE header. Do not expect it to circumvent buggy files.

**Comment by lissyx** [comment]
> Thank you, But is there any way to convert it using any other command line tool so that i can use it in my python script ?

Anything that produces a valid file that will not choke in this: https://github.com/mozilla/DeepSpeech/blob/master/native_client/client.cc#L210-L246

**Comment by reuben** [comment]
Try this: https://stackoverflow.com/questions/39668146/ffmpeg-making-a-clean-wav-file

**Comment by Israrulhaq190** [comment]
Thanks reuben. It's working perfectly fine now.
