### ISSUE TITLE
Converting multiple files in a folder

### ISSUE THREAD

**Issue by AmyChen-Qingxin** [mozilla/DeepSpeech#2389]
I saw the issue #1232 saying that the master model should support converting multiple files from the same folder. But when I tried similar command directing the --audio to the folder, I got a IsADirectoryError. Is it no longer supporting multiple files?

my command:
`time deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio 84-121123wav`
84-121123wav is the folder under Deepspech repo.

The error message I got:
`IsADirectoryError: [Errno 21] Is a directory: '84-121123wav'`

I am on mac 10.14.5 running version 
TensorFlow: v1.13.1-10-g3e0cc5374d
DeepSpeech: v0.5.1-0-g4b29b78
using command line prompt

Thanks.

**Comment by lissyx** [comment]
>  `IsADirectoryError: [Errno 21] Is a directory: '84-121123wav'`

This is a Python exception. #1232 explicitely states this is supported from the C++ client. Please bear in mind those are mostly demo-purpose, so it's easy to quickly test, but it's not meant for serving directly as your solution.

**Comment by AmyChen-Qingxin** [comment]
Ok, thank you. So is there a way that I can simply test multiple files?

**Comment by lissyx** [comment]
> Ok, thank you. So is there a way that I can simply test multiple files?

Use the C++ binary ?
