### ISSUE TITLE
Disable caching when augmentation flags have been specified

### ISSUE THREAD

**Issue by rhamnett** [mozilla/DeepSpeech#2396]
With the addition of the new augmentation code release, it is now required to disable the `.cache()` call in util/feeder.py so that in memory cache is not used. 

It has been suggested that disabling the cache should be done programatically based on the runtime flags provided when invoking DeepSpeech.py

@reuben perhaps we should also check for combination of `--feature_cache` and and `--aug` features and warn that this is not compatible

**Comment by dabinat** [comment]
What performance hit is disabling the cache likely to cause?

**Comment by rhamnett** [comment]
Not disabling the cache will mean you will not get any epochs using augmented data at all.

With no cache YMMV but shouldn't be too bad. I understand it the pipeline should be able to process the next data before it's needed in the batch as per https://www.tensorflow.org/guide/data_performance

**Comment by lissyx** [comment]
@rhamnett I was thinking to generalize that and compute some hash of the dataset to ensure feature cache matches and either fail or cleanup cache

**Comment by rhamnett** [comment]
@lissyx just wondering - is there any point in taking time to compute a hash when we know that augmentations have been specified in flags - therefore the cache definitely cannot be used?
