### ISSUE TITLE
DeepSpeech Generating trie for my own model.

### ISSUE THREAD

**Issue by cryptoaimdy** [mozilla/DeepSpeech#2398]
@lissyx 
Hi

i am a newbie. 

i have generated lm.binary using .arpa file and trying to create trie. I am getting error which generating.

(deepspeech-train-venv) yk@andromeda:~/DeepSpeech/tensorflow$ bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie

ERROR: Skipping '//native_client:libdeepspeech.so': no such package 'native_client': BUILD file not found on package path
ERROR: no such package 'native_client': BUILD file not found on package path
INFO: Elapsed time: 0.086s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Is there any solution otherthan this to create trie file usig my binary?
or can i use DeepSpeech/data/lm/trie (default with clone) ? for my model?

**Comment by lissyx** [comment]
@cryptoaimdy First, this is not the place to request for help. Please use Discourse for that purpose. Second, you should have formatted properly console output. Third, it is documented to use our tensorflow fork, and branch `r1.14`. Fourth, `generate_trie` is packaged in `native_client.tar.xz` so why do you have to rebuild that ?


>  or can i use DeepSpeech/data/lm/trie (default with clone) ? for my model?

Are you training an English model ?

**Comment by cryptoaimdy** [comment]
Hi
Sorry for the posting here.

Yes i am training English Model. can i use the prebuilt one?

**Comment by lissyx** [comment]
> Yes i am training English Model. can i use the prebuilt one?

Then yes.
