### ISSUE TITLE
Pipsqueak Engine as service for Web Speech API SpeechRecognition at desktop?

### ISSUE THREAD

**Issue by guest271314** [mozilla/DeepSpeech#2401]
Found this repository from https://research.mozilla.org/machine-learning/

> Visit Mozilla’s GitHub
> Read the GitHub wiki
> Pipsqueak Engine
> 
> Online STT technologies can have security and privacy vulnerabilities. Mozilla researchers aim to create a competitive offline STT engine called Pipsqueak that promotes security and privacy. This implementation of a deep learning STT engine can be run on a machine as small as a Raspberry Pi 3. Our goal is to disrupt the existing trend in STT that favors a few commercial companies, and to stay true to our mission of making safe, open, affordable technologies available to anyone who wants to use them.

then read

https://discourse.mozilla.org/t/paper-implementation-of-speech-recognition-on-mobile-devices/34063/4

> We aren’t using the pipsqueak repo. All such small platform work is currently happening in the Deep Speech repo. (I just deleted the pipsqueak repo.)

Am interested in the current status of the former intent. Specifically the ability to use Pip Squeak Engine as the service for Web Speech API, to avoid the issue of sending audio to a remote web service https://github.com/w3c/speech-api/issues/56.

How far (in estimated time) are we away from being able to use Pip Squeak or DeepSearch as the **_local_** service to use for STT?

**Comment by lissyx** [comment]
Please take that discussion to Discourse.

**Comment by guest271314** [comment]
@lissyx Same question at the same discourse page https://discourse.mozilla.org/t/paper-implementation-of-speech-recognition-on-mobile-devices/34063/3.
