### ISSUE TITLE
Dataset label format

### ISSUE THREAD

**Issue by vaibhavsatpathy** [mozilla/DeepSpeech#2402]
Sorry for such a simple query in advance.
The model takes in the audio spectrogram as input.
My question is what does it take as a label or the y_true?
And what does the model predict after it's final layer and before the post-processing?

It would be really great if anyone could add an example of the results of the above mentioned questions.
Thank you

**Comment by lissyx** [comment]
@vaibhavsatpathy This is not a bug, please post questions on Discourse.
