### ISSUE TITLE
convert graphdef_memmapped_format link broken for master 

### ISSUE THREAD

**Issue by srevay** [mozilla/DeepSpeech#2404]
When trying to build the convert_graphdef_memmapped_format binary using this command: 

python3 util/taskcluster.py --branch master --arch gpu --artifact convert_graphdef_memmapped_format --target "."

I get a 404: not found error as it tries to download this url: "Downloading https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.gpu/artifacts/public/convert_graphdef_memmapped_format ..."

What is the correct --branch flag that needs to be used to get the most up to date version of the binary? I am currently working on master.

**Comment by lissyx** [comment]
@srevay As documented correct `branch` for tensorflow-related elements is `r1.14`.

**Comment by reuben** [comment]
This isn't actually documented anywhere that I can find. You need:

` python util/taskcluster.py --source tensorflow --branch r1.14 --artifact convert_graphdef_memmapped_format --target .`

**Comment by reuben** [comment]
Also note that this is not building anything, just downloading a binary from our infrastructure. If you actually are trying to build you should be using bazel, not taskcluster.py.

**Comment by srevay** [comment]
branch r1.14 worked thank you.
