### ISSUE TITLE
get model for deepspeech-gpu

### ISSUE THREAD

**Issue by HowieYang0** [mozilla/DeepSpeech#2411]
Could I get a pretrained gpu model (deepspeech-gpu)

-------------------------
I don't think v0.5.1 had support for the RPi4. You can get a version of the v0.5.1 model re-exported to be compatible with the v0.6.0 alphas at https://github.com/reuben/DeepSpeech/releases/v0.6.0-alpha.4

_Originally posted by @reuben in https://github.com/mozilla/DeepSpeech/issues/2336#issuecomment-527316071_

**Comment by lissyx** [comment]
That does not look like an issue. Closing.
