### ISSUE TITLE
change the behavior and pull from current matching tag

### ISSUE THREAD

**Issue by safa0** [mozilla/DeepSpeech#2418]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 19.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Yes
- **TensorFlow version (use command below)**:b'v1.13.0-rc2-5-g6612da8' 1.13.1
- **Python version**: 3.7.3
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**:NA
- **Exact command to reproduce**: python util/taskcluster.py --target .

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
To generate trie from custom language model, util/taskcluster.py is used to download generate_trie binary.
This is nice, and you don't have to compile everything but, taskcluster.py points to master by default. Although this is mentioned in --help, many have missed and it is not intuitive behavior. One would expect that if a certain tag is checked out, e.g. v0.5.1, then taskcluster should download the corresponding native_client and generate_trie for that tag, and not the one on master.
Related conversations:

https://github.com/mozilla/DeepSpeech/blob/master/USING.rst#using-the-command-line-client

**Comment by lissyx** [comment]
@safa0 If you can check on your side, but that is working for me. This is logic we already had for the decoder anyway ...
