### ISSUE TITLE
import m-ailabs data link broken

### ISSUE THREAD

**Issue by srevay** [mozilla/DeepSpeech#2421]
When trying to import m-ailabs Spanish data using the import_m-ailabs.py, the url to the training data is broken. Is the tar file located somewhere else?

**Comment by lissyx** [comment]
> When trying to import m-ailabs Spanish data using the import_m-ailabs.py, the url to the training data is broken. Is the tar file located somewhere else?

Can you be more exhaustive ? This is working for french, I think @tilmankamp verified with German as well.

**Comment by lissyx** [comment]
@srevay Is it just the website down ? https://www.caito.de/ does not work at all here.

**Comment by srevay** [comment]
It looks like it is an issue with the website.
