### ISSUE TITLE
How to get lm.binary,trie&alphabet.txt file after finished training for testing.

### ISSUE THREAD

**Issue by Oblivion97** [mozilla/DeepSpeech#2422]
Hello, if I want to transcribe an audio file i've to run this command-

`deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav`

in  here i need 4 files,

1.alphabet.txt
2.trie
3.lm.binary 
4.output_graph.pb

I've got the  "output_graph.pb" file after I train the data & used my checkpoint.
but how can I get the rest of the 3 files? I'm using it for my native language.

**Comment by lissyx** [comment]
> how can I get the rest of the 3 files? I'm using it for my native language.

Have you read the documentation ?

https://github.com/mozilla/DeepSpeech/blob/master/data/lm/README.rst

If you trained your own model, you should already have produced a valid `alphabet.txt`

**Comment by lissyx** [comment]
This is not a bug, so please continue the discussion on Discourse.

**Comment by Oblivion97** [comment]
what about the lm.binary & trie file?

sorry for the inconvenience, I'm new here.

**Comment by lissyx** [comment]
> what about the lm.binary & trie file?

Read the link I shared ?

**Comment by Oblivion97** [comment]
is the lm.binary & trie file is already given in the repository data folder?& can i use it for any
 language?

**Comment by lissyx** [comment]
> is the lm.binary & trie file is already given in the repository data folder?& can i use it for any
> language?

Do you understand what you are doing ? Do you understand what the LM files are for ? Have you read the link ?

**Comment by Oblivion97** [comment]
like I said, I'm new here. can u make me understand about it? how to solve the problem I'm facing?

I have the alphabet.txt & output graph.pb file how can I generate the lm &  trie file for my native language model? can u help me out, please?

**Comment by lissyx** [comment]
> like I said, I'm new here. can u make me understand about it? how to solve the problem I'm facing?

Being new does not allow you to use Github for support. The problem you are facing is documented in the link I shared earlier.



> I have the alphabet.txt & output graph.pb file how can I generate the lm & trie file for my native language model? can u help me out, please?

Again, please read the documentation.
