### ISSUE TITLE
broken link in training.rst

### ISSUE THREAD

**Issue by mone27** [mozilla/DeepSpeech#2423]
In Training.rst the link at README.md under [https://github.com/mozilla/DeepSpeech/blob/master/TRAINING.rst#exporting-a-model-for-inference] is broken

**Comment by lissyx** [comment]
> In Training.rst the link at README.md under [https://github.com/mozilla/DeepSpeech/blob/master/TRAINING.rst#exporting-a-model-for-inference] is broken

Can you elaborate @mone27 ? Because it's working for me ...

**Comment by lissyx** [comment]
@mone27 Oh, you mean the **README.md** link in **TRAINING.rst** is broken
