### ISSUE TITLE
Specified model file version (0) is incompatible with minimum version supported by this client (3)

### ISSUE THREAD

**Issue by maxima120** [mozilla/DeepSpeech#2430]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 1.14
- **Python version**: 3.7

I am trying to run sample as per your readme.
I downloaded models as suggested: `https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz`

The command:
`deepspeech --model H:\DeepSpeech\deepspeech-0.5.1-models\output_graph.pbmm --alphabet H:\DeepSpeech\deepspeech-0.5.1-models\alphabet.txt --lm H:\DeepSpeech\deepspeech-0.5.1-models\lm.binary --trie H:\DeepSpeech\deepspeech-0.5.1-models\trie --audio H:\SpeechTests\f1lspeue.wav`

And I am getting this:
`Specified model file version (0) is incompatible with minimum version supported by this client (3)`

I did see a similar error which involves TFLite. And the tar has tflite in it. But I suppose the sample must run and it doesn't.

What am I doing wrong?

This is the unpacked tar:
![image](https://user-images.githubusercontent.com/10121753/66701956-77f87580-ed02-11e9-837c-fc70ab24f2ee.png)

**Comment by kdavis-mozilla** [comment]
The error message:

> Specified model file version (0) is incompatible with minimum version supported by this client (3)

hopefully indicates the problem; you need an older client. In particular the 0.5.1 client to work with the 0.5.1 model. Currently, this should be the client installed with say a `pip install`.

**Comment by maxima120** [comment]
I see. the pip install deepspeech installs 0.6.0
