### ISSUE TITLE
Error while loading checkpoint: Fine tuning DeepSpeech model on custom dataset

### ISSUE THREAD

**Issue by tusharrakshe** [mozilla/DeepSpeech#2442]
Hi I am trying to fine tune deepspeech model on custom dataset in google colab. But i am facing problem while loading the released checkpoints:
```
bash
python -u DeepSpeech.py \
--checkpoint_dir deepspeech_checkpoint \
--n_hidden 2048 \
--train_files train.csv \
--dev_files valid.csv \
--test_files test.csv \
--export_dir my_exportdir \
--train_batch_size 24 \
--dev_batch_size 48 \
--test_batch_size 2 \
--learning_rate 0.0001 \
--lm_binary_path lm.binary \
--lm_trie_path trie \
--dropout_rate 0.15 \
--epochs 75 \
--lm_alpha 0.75 \
--lm_beta 1.85 \
```

**Error :**
```
INFO:tensorflow:Restoring parameters from deepspeech_checkpoint/model.v0.5.1
I1016 09:47:56.926222 140531309041536 saver.py:1280] Restoring parameters from deepspeech_checkpoint/model.v0.5.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_17]]
0 successful operations.
0 derived errors ignored.
```

**Comment by lissyx** [comment]
@tusharrakshe Are you doing fine-tuning from `v0.5.1` tag ? Checkpoint is not compatible with newer versions.

**Comment by tusharrakshe** [comment]
yes I am doing fine tuning from v0.5.1. If checkpoint is not compatible then how can i fine train model on new dataset.

**Comment by lissyx** [comment]
> yes I am doing fine tuning from v0.5.1. If checkpoint is not compatible then how can i fine train model on new dataset.

Your error means you are using checkpoint v0.5.1 from a different tag than v0.5.1 of the code. Please `git checkout v0.5.1`.

**Comment by tusharrakshe** [comment]
Yes . Already on 'v0.5.1'

**Comment by lissyx** [comment]
> Yes . Already on 'v0.5.1'

CuDNN training support was added after v0.5.1, so it makes no sense.

**Comment by tusharrakshe** [comment]
So you mean to say, I cannot fine tune model from released checkpoints.

**Comment by lissyx** [comment]
> So you mean to say, I cannot fine tune model from released checkpoints.

No, I am saying that you are not on git tag v0.5.1, and that the released checkpoints will only work on it.

**Comment by lissyx** [comment]
@tusharrakshe Can you ensure you are on proper commit, with clean index ?

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/commit/4b29b78832036216b53f59b953639bde7cde7dfe

**Comment by lissyx** [comment]
@tusharrakshe Can you confirm you have been able to do that ?

**Comment by lissyx** [comment]
No news, closing.

**Comment by tusharrakshe** [comment]
> @tusharrakshe Can you ensure you are on proper commit, with clean index ?

Yes. I solved the problem. 
Now i am able to load the checkpoints. I have done the fine tuning of the model from released checkpoints. But no improvement in WER. Need your suggestion..

I am using 10 Hours of indian accent Audio data for fine tuning model.

**Comment by lissyx** [comment]
>  Now i am able to load the checkpoints. I have done the fine tuning of the model from released checkpoints. But no improvement in WER. Need your suggestion..

Please use Discourse for support.


> I am using 10 Hours of indian accent Audio data for fine tuning model.

Likely 10 hours is not enough. But it also depends on your parameters etc. ...
