### ISSUE TITLE
Issue training with checkpoints

### ISSUE THREAD

**Issue by Vampsj** [mozilla/DeepSpeech#2444]
Linux Ubuntu 16.04
Tensorflow-gpu 1.13.1
Python 3.5
Cuda compilation tools, release 10.0
CuDNN 7.5

I am having an issue similiar to #2297 while using the checkpoint to run the /bin/run-ldc93s1.sh. 

The error message is as follows:

> Traceback (most recent call last):
>  File "DeepSpeech.py", line 926, in <module>
    absl.app.run(main)
  File "/home/vampsj/git/DeepSpeech-master/dpsp/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vampsj/git/DeepSpeech-master/dpsp/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 910, in main
    train()
  File "DeepSpeech.py", line 433, in train
    iterator = tfv1.data.Iterator.from_structure(tfv1.data.get_output_types(train_set),
AttributeError: module 'tensorflow._api.v1.compat.v1.data' has no attribute 'get_output_types' 

And I have switched to v0.5.1 with `git check`

**Comment by lissyx** [comment]
@Vampsj This is classic symptom of `tensorflow-gpu==1.13.1` when using current master and not `v0.5.1`, please ensure you are on the proper tag correctly checked out.

**Comment by Vampsj** [comment]
@lissyx Thank you for your reply! As you said, this is the problem that I haven't changed to the proper tag. I tried to change to the v0.5.1 tag with 
`git checkout v0.5.1` 
but in fact, this turns me into the v0.5.1 branch. Finally, I get this
`git checkout tags/v.0.5.1`
worked!
