### ISSUE TITLE
Occuring an Error like: tensorflow/native_client/BUILD:85:1: no such target '//tensorflow/core/kernels:deepspeech_cwise_ops':

### ISSUE THREAD

**Issue by araf-hasan15** [mozilla/DeepSpeech#2446]
I am facing an Error when I generating the libdeepspeech.so binary.
It shows me like this:

ERROR: /home/araf15/tensorflow/native_client/BUILD:85:1: no such target '//tensorflow/core/kernels:deepspeech_cwise_ops': target 'deepspeech_cwise_ops' not declared in package 'tensorflow/core/kernels' defined by /home/araf15/tensorflow/tensorflow/core/kernels/BUILD and referenced by '//native_client:libdeepspeech.so'
ERROR: Analysis of target '//native_client:libdeepspeech.so' failed; build aborted: Analysis failed
FAILED: Build did NOT complete successfully (93 packages loaded, 5611 targets configured)

Is there any solution about this kind of failure ?

**Comment by lissyx** [comment]
@araf-hasan15 Are you using `mozilla/tensorflow` repository with matching branch as documented? Also, you don't document what version of deepspeech you are trying to build.

**Comment by araf-hasan15** [comment]
Yes, I am using Mozilla's TensorFlow ``r1.14` branch <https://github.com/mozilla/tensorflow/tree/r1.14>`_ as documented there, and my deepspeech version is 0.5.1...

**Comment by lissyx** [comment]
> Yes, I am using Mozilla's TensorFlow ``r1.14` branch <https://github.com/mozilla/tensorflow/tree/r1.14>`_ as documented there, and my deepspeech version is 0.5.1...

Then use `r1.13`, as documented for `v0.5.1`

**Comment by araf-hasan15** [comment]
Which version of deepspeech should I use for Mozilla's TensorFlow ``r1.14 branch ....?

**Comment by lissyx** [comment]
> Which version of deepspeech should I use for Mozilla's TensorFlow ``r1.14 branch ....?

r1.13.

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/blob/v0.5.1/native_client/README.md#building-deepspeech-binaries
