### ISSUE TITLE
TypeError: Required argument 'aSampleRate' (pos 3) not found

### ISSUE THREAD

**Issue by shamoons** [mozilla/DeepSpeech#2449]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream
- **TensorFlow version (use command below)**: b'v1.13.1-0-g6612da8951' 1.13.1
- **Python version**: 3.6.8
- **GPU model and memory**:
- **Exact command to reproduce**:

My code to initialize is:
```
    def initialize_deepspeech(self, model='data/models/deepspeech-0.5.1-models/output_graph.pb', alphabet='data/models/deepspeech-0.5.1-models/alphabet.txt', beam_width=500):
        self.deepspeech_model = deepspeech.Model(
            aModelPath=model, aAlphabetConfigPath=alphabet, aBeamWidth=beam_width, aNCep=1, aNContext=1)
```

This throws the error: `TypeError: Required argument 'aSampleRate' (pos 3) not found`. I had to add the `aModelPath`, etc or else it complained about those as well

**Comment by lissyx** [comment]
@shamoons What version of `deepspeech` are you using ? `aSampleRate` was removed post 0.5.1, so make sure you are depending on `deepspeech==0.5.1`.

**Comment by lissyx** [comment]
@shamoons Could you please clearly indicate what version of DeepSpeech you are using ? This does not make any sense, we don't have keywords arguments, as you can see on https://github.com/mozilla/DeepSpeech/blob/v0.5.1/native_client/python/client.py#L88 and sample rate is not an argument of `Model` either, so I don't understand where your `TypeError` comes from.

**Comment by lissyx** [comment]
@shamoons The Python API mostly directly maps to the C one, e.g., for `Model` look at https://github.com/mozilla/DeepSpeech/blob/v0.5.1/native_client/deepspeech.h#L57-L78 and for `stt` look at https://github.com/mozilla/DeepSpeech/blob/v0.5.1/native_client/deepspeech.h#L110-L126

You can see example usage in https://github.com/mozilla/DeepSpeech/blob/v0.5.1/native_client/python/client.py#L115, e.g., where `fs` is the sample rate.

**Comment by shamoons** [comment]
@lissyx I'm using `deepspeech = "==0.5.1"`. I see the issue. I was following the https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/client.py#L71 file which is missing the `N_FEATURES`
