### ISSUE TITLE
Are there any pre-compiled example programs for real time speech-to-text from a microphone?

### ISSUE THREAD

**Issue by procedural** [mozilla/DeepSpeech#2452]
If the answer is no, then this issue is a feature request: I need a simple way to try speech-to-text in real time, not sure if it's possible with this library, but I need it regardless!

**Comment by procedural** [comment]
I learned that DeepSpeech can do speech-to-text from here: https://blog.rasa.com/how-to-build-a-voice-assistant-with-open-source-rasa-and-mozilla-tools/

**Comment by procedural** [comment]
Currently watching "Mozilla's DeepSpeech and Common Voice projects Open and offline-capable voice recognition for everyone" by Tilman Kamp: https://www.youtube.com/watch?v=aUSyzNr6iK8

**Comment by procedural** [comment]
I guess by "real time" I mean "streaming support", according to (timecode: 33:57): https://www.youtube.com/watch?v=ZJpLldlJYY8&t=2037

**Comment by procedural** [comment]
https://github.com/topics/speech-to-text shows DeepSpeech at the top, so I guess this is state of the art?

**Comment by lissyx** [comment]
> If the answer is no, then this issue is a feature request: I need a simple way to try speech-to-text in real time, not sure if it's possible with this library, but I need it regardless!

Please have a look at `examples/`. And this is obviously not a bug, so please continue discussion on Discourse.

**Comment by procedural** [comment]
> Please have a look at examples

I guess it's this one? https://github.com/mozilla/DeepSpeech/blob/master/examples/mic_vad_streaming/mic_vad_streaming.py

Why does it saves .wav? Is that .wav temporary? Can I keep temporary in memory rather than saving it to a file?

**Comment by lissyx** [comment]
> > Please have a look at examples
> 
> I guess it's this one? https://github.com/mozilla/DeepSpeech/blob/master/examples/mic_vad_streaming/mic_vad_streaming.py
> 
> Why does it saves .wav? Is that .wav temporary? Can I keep temporary in memory rather than saving it to a file?

Can you use Discourse, please ?

**Comment by procedural** [comment]
Does Discourse requires creating an account? If yes, then no, I can't use it.

**Comment by lissyx** [comment]
> Does Discourse requires creating an account? If yes, then no, I can't use it.

Why would not you be able to create an account ? Second, if you had looked at discourse, you would have seen you can logging using Github.

**Comment by procedural** [comment]
@lissyx can you point me to an answer, if it was already asked, why you need to write .wav and not keep a temporary in memory?

**Comment by lissyx** [comment]
> @lissyx can you point me to an answer, if it was already asked, why you need to write .wav and not keep a temporary in memory?

That's the contributor's design, not our choice. Seriously, we have plenty of examples, including the bindings, that shows how to use the API from different point of view. Can you just have a look under `native_client/` and `examples/` ?

**Comment by procedural** [comment]
Ok, I will look

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/tree/master/examples/vad_transcriber

**Comment by procedural** [comment]
@lissyx thank you! Can I download a pre-compiled executable for that example from somewhere?

**Comment by procedural** [comment]
Oh, I just looked, it's python, I guess it can't be precompiled...

**Comment by lissyx** [comment]
Again, can we take this discussion to Discours, please ?

**Comment by procedural** [comment]
@lissyx, I guess, sorry!

**Comment by procedural** [comment]
@lissyx than you for the link, once again!
