### ISSUE TITLE
AttributeError: Can only use .str accessor with string values!

### ISSUE THREAD

**Issue by shubhamchordiya** [mozilla/DeepSpeech#2465]
![Screenshot from 2019-10-25 19-01-11](https://user-images.githubusercontent.com/47270403/67575305-e2c19c00-f759-11e9-8788-12022aaf19eb.png)
whenever i try to train my own model it raise string error.
steps that i perform:
1) load Deepsppech model
2) creat my own dataset
3)split this dataset in train,test and dev.
4)train model by following command:
python3 ./DeepSpeech.py --train_files clips/pranay2/train.csv ~--dev_files clips/pranay1/dev.csv --test_files clips/pranay1/test.csv 

after that it shows error:
   thanx in advance

**Comment by lissyx** [comment]
Please don't use screenshots.

>     2\. python3 ./DeepSpeech.py --train_files clips/pranay2/train.csv ~--dev_files clips/pranay1/dev.csv --test_files clips/pranay1/test.csv

Is this your exact command line? `~--` seems wrong.

**Comment by lissyx** [comment]
@shubhamchordiya Can you update us ?

**Comment by lissyx** [comment]
No reply, nothing actionable, closing.

**Comment by rhamnett** [comment]
There is a tilde in his flags
