### ISSUE TITLE
Alphabet character "ü" throws KeyErrors

### ISSUE THREAD

**Issue by Unbekannter** [mozilla/DeepSpeech#2472]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip3
- **TensorFlow version (use command below)**:  tensorflow-gpu==1.14.0
- **Python version**: python 3.6.6
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: TESLA V100
- **CURRENT MASTER BRANCH**

**ALPHABET FILE:
https://pastebin.com/0ubKMm6b**

Iam trying to train the german model, but i have an exception with my alphabet file.
My Alphabet file has the character "ü", but the Alphabet class throws an error.

Only this character does not work, any ideas? 
I tested my code below with my other characters and it still works.

**Take a look below at my print of all characters. 
"ü" has a corresponding number!**

**- **Exact command to reproduce**:**

```
python -c "from util.text import Alphabet; a = Alphabet('data/alphabet.txt'); print(a._label_from_string('ü'))"
```

> Traceback (most recent call last):
>   File "/home/ubuntu/DeepSpeech/util/text.py", line 31, in _label_from_string
>     return self._str_to_label[string]
> KeyError: 'ü'
> 
> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ubuntu/DeepSpeech/util/text.py", line 37, in _label_from_string
>     ).with_traceback(e.__traceback__)
>   File "/home/ubuntu/DeepSpeech/util/text.py", line 31, in _label_from_string
>     return self._str_to_label[string]
> KeyError: "ERROR: Your transcripts contain characters (e.g. 'ü') which do not occur in data/alphabet.txt! Use util/check_characters.py to see what characters are in your [train,dev,test].csv transcripts, and then add all these to data/alphabet.txt."
> 

```
python -c "from util.text import Alphabet; a = Alphabet('data/alphabet.txt'); print('\n'.join([u'\'{}\' ({}) -> {}'.format(s, ':'.join('{:02x}'.format(ord(c)) for c in s), a._str_to_label[s]) for s in a._str_to_label]))
```
> '  ' (20) -> 37
> 'a' (61) -> 1
> 'b' (62) -> 2
> 'c' (63) -> 3
> 'd' (64) -> 4
> 'e' (65) -> 5
> 'f' (66) -> 6
> 'g' (67) -> 7
> 'h' (68) -> 8
> 'i' (69) -> 9
> 'j' (6a) -> 10
> 'k' (6b) -> 11
> 'l' (6c) -> 12
> 'm' (6d) -> 13
> 'n' (6e) -> 14
> 'o' (6f) -> 15
> 'p' (70) -> 16
> 'q' (71) -> 17
> 'r' (72) -> 18
> 's' (73) -> 19
> 't' (74) -> 20
> 'u' (75) -> 21
> 'v' (76) -> 22
> 'w' (77) -> 23
> 'x' (78) -> 24
> 'y' (79) -> 25
> 'z' (7a) -> 26
> 'ß' (df) -> 27
> '–' (2013) -> 28
> 'à' (e0) -> 29
> 'ö' (f6) -> 30
> 'ä' (e4) -> 31
> **'ü ' (fc:20) -> 32**
> ':' (3a) -> 33
> '!' (21) -> 34
> 'ó' (f3) -> 35
> 'é' (e9) -> 36
> '“' (201c) -> 38
> '„' (201e) -> 39
> '…' (2026) -> 40
> '/' (2f) -> 41
> 'ș' (219) -> 42
> 'ã' (e3) -> 43
> ';' (3b) -> 44
> 'ă' (103) -> 45
> '’' (2019) -> 46
> 'ʻ' (2bb) -> 47
> 'ş' (15f) -> 48
> 'ú' (fa) -> 49
> '´' (b4) -> 50
> 'á' (e1) -> 51
> '@' (40) -> 52
> 'í' (ed) -> 53
> ''' (27) -> 54

**Comment by lissyx** [comment]
> Use util/check_characters.py

Can you do that and generate the alphabet using this script ? It would not be unsurprising you have some unicode-different yet similar-looking char ...

**Comment by lissyx** [comment]
@Unbekannter Can you comment what was wrong ?

**Comment by Unbekannter** [comment]
@lissyx You're right with "unicode-different yet similar-looking char".
The "ü"-char, which was the only char doesnt works, exists in my alphabet file, but it wasn't the same char used in my train/dev/test.csv files - it justs looks like it.

I copied the chars from the check_characters script directly in my alphabet file and it works.

Thank you :)

**Comment by lissyx** [comment]
Thanks, it perfectly illustrates an issue I wanted to take care of ... :)
