### ISSUE TITLE
CreateModel failed with error code 8195

### ISSUE THREAD

**Issue by bhanuSingh97** [mozilla/DeepSpeech#2477]
(deepspeech) C:\Users\165689\Desktop\chatbot\.chatbot>deepspeech --model deepspe
ech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.t
xt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --
audio audio/2830-3980-0043.wav
Loading model from file deepspeech-0.5.1-models/output_graph.pbmm
TensorFlow: v1.14.0-18-g351a98ab6e
DeepSpeech: v0.6.0-alpha.11-0-gf3694ef
2019-10-30 16:18:47.762043: I tensorflow/core/platform/cpu_feature_guard.cc:142]
 Your CPU supports instructions that this TensorFlow binary was not compiled to
use: AVX2
Unable to fetch metadata: Invalid argument: Session was not created with a graph
 before Run()!
Traceback (most recent call last):
  File "c:\users\165689\.conda\envs\deepspeech\lib\runpy.py", line 192, in _run_
module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\165689\.conda\envs\deepspeech\lib\runpy.py", line 85, in _run_c
ode
    exec(code, run_globals)
  File "C:\Users\165689\.conda\envs\deepspeech\Scripts\deepspeech.exe\__main__.p
y", line 7, in <module>
  File "c:\users\165689\.conda\envs\deepspeech\lib\site-packages\deepspeech\clie
nt.py", line 71, in main
    ds = Model(args.model, args.alphabet, args.beam_width)
  File "c:\users\165689\.conda\envs\deepspeech\lib\site-packages\deepspeech\__in
it__.py", line 45, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 8195

**Comment by lissyx** [comment]
> (deepspeech) C:\Users\165689\Desktop\chatbot.chatbot>deepspeech --model deepspe
> ech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.t
> xt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --
> audio audio/2830-3980-0043.wav
> Loading model from file deepspeech-0.5.1-models/output_graph.pbmm
> TensorFlow: v1.14.0-18-g351a98ab6e
> DeepSpeech: v0.6.0-alpha.11-0-gf3694ef

You are running incompatible model / binary.

**Comment by bhanuSingh97** [comment]
but 

> > (deepspeech) C:\Users\165689\Desktop\chatbot.chatbot>deepspeech --model deepspe
> > ech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.t
> > xt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --
> > audio audio/2830-3980-0043.wav
> > Loading model from file deepspeech-0.5.1-models/output_graph.pbmm
> > TensorFlow: v1.14.0-18-g351a98ab6e
> > DeepSpeech: v0.6.0-alpha.11-0-gf3694ef
>
> You are running incompatible model / binary.

What is incompatible?
How can I run it?

**Comment by lissyx** [comment]
> What is incompatible?

Model v0.5.x requires v0.5.x binary. Use proper version.

**Comment by lissyx** [comment]
https://deepspeech.readthedocs.io/en/latest/Error-Codes.html#_CPPv425DS_ERR_MODEL_INCOMPATIBLE

**Comment by bhanuSingh97** [comment]
1. Is there any command by which I can downgrade deepspeech version?
2. Will my command work after downgrading the deepspeech version to 0.5.x?

**Comment by lissyx** [comment]
> Is there any command by which I can downgrade deepspeech version?

pip uninstall deepspeech and then pip install --upgrade deepspeech==0.5.1

**Comment by bhanuSingh97** [comment]
(deepspeech) C:\Users\165689>pip install --upgrade deepspeech==0.5.1
ERROR: Could not find a version that satisfies the requirement deepspeech==0.5.1
 (from versions: 0.6.0a11)
ERROR: No matching distribution found for deepspeech==0.5.1

**Comment by lissyx** [comment]
> (deepspeech) C:\Users\165689>pip install --upgrade deepspeech==0.5.1
> ERROR: Could not find a version that satisfies the requirement deepspeech==0.5.1
> (from versions: 0.6.0a11)
> ERROR: No matching distribution found for deepspeech==0.5.1

Filling the Github issue template would have saved us some time.

**Comment by bhanuSingh97** [comment]
Thanks for the help. It is working now by downgrading deepspeech to 0.5.1.
