### ISSUE TITLE
check_characters.py doesn't properly handle unicode two-points characters

### ISSUE THREAD

**Issue by hjortnaes** [mozilla/DeepSpeech#2488]
If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat Enterprise Linux Server 7.6 (Maipo)
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: from pip
- **TensorFlow version (use command below)**: 14.0.0
- **Python version**: 3.6.8
- **CUDA/cuDNN version**: V10.0.130
- **GPU model and memory**: Nvidia Tesla P100 & Nvidia Tesla V100 (tried both)
- **Exact command to reproduce**: python util/check_characters.py -alpha -csv data/komi/clips/train.csv,data/komi/clips/dev.csv,data/komi/clips/test.csv

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

When using check_characters.py to generate the alphabet it misses diacritics entirely. In my case: 
 ̄ and ʼ . When running training, the Alphabet class then throws a KeyError because the diacritics appear in the transcripts but not in the alphabet. I was able to fix it by manually adding the diacritics to the alphabet file, but anyone working with a language with diacritics in the orthography will probably run into the same issue.

**Comment by lissyx** [comment]
Can you be more specific? Are those one or multi code points chars? One or multibyte?

**Comment by lissyx** [comment]
The two chars you shared makes me think it is the case of two codepoints / two bytes. This is kind of broken with this script right now. Can you try with `unicodedata.normalize("NFKC", s) ` when you generate your csv files?

**Comment by reuben** [comment]
This works fine on my end:

```
$ xxd ../sample.txt
00000000: 6165 696f 750a 2c2c 6520 c3a9 2065 cc81  aeiou.,,e .. e..
00000010: 2061 6161                                 aaa
$ cat ../sample.txt
aeiou
,,e é é aaa%                                                                                                                                                                                                    $ python util/check_characters.py -csv ../sample.txt
### The following unique characters were found in your transcripts: ###
[' ', 'é', 'a', 'e', '́']
$ python util/check_characters.py -csv ../sample.txt -alpha
### The following unique characters were found in your transcripts: ###
e
 ́
a

é
### ^^^ You can copy-paste these into data/alphabet.txt ###
```

**Comment by lissyx** [comment]
@hjortnaes Can you share more details, please ?

**Comment by lissyx** [comment]
@hjortnaes Just landed a new parameter to help checking that kind of discrepencies, running `check_characters.py` from current master should detect error-prone normalizations.

**Comment by lissyx** [comment]
@hjortnaes Ping ?

**Comment by hjortnaes** [comment]
@lissyx So sorry, I got distracted and then forgot to answer.

I'm working in the Cyrillic alphabet space, and all the other characters worked fine, and as you mentioned above the problem characters I shared are the two-codepoint variants. 

In terms of the data itself, it is for research but it is not mine to share. Sorry about that, I know that makes it a bit harder to debug this. 

I ran check_characters on my dataset again with the new tag and it did flag a problem sentence, so based on the change you made, my data isn't in a normalized format. 

I have been using a modified version of import_cv2.py (my audio is already in wav files), but I hadn't been using the normalize flag. I did modify it further because it normalizes to NFKD by default. That may cause an issue to others in the future, having import_cv2.py normalize to NFKD and check_characters test for NFKC. 

**Exact command to reproduce:** python bin/import_cv2.py data/komi_copy/ --normalize

Then I reran check_characters.py and got a slightly different (maybe better? I'll test that when I have time and let you know) alphabet file which normalized the  ̄ to the single codepoint version and captured the ʼ without triggering the error flag. So it seems to be working well, thanks very much for adding that. 

If I could offer one suggestion, I would add "when generating your csv files" to the end of "Consider using NFKC normalization: unicodedata.normalize('NFKC', str)."

**Comment by lissyx** [comment]
> I'm working in the Cyrillic alphabet space, and all the other characters worked fine, and as you mentioned above the problem characters I shared are the two-codepoint variants.

Ok, so it's at least consistent with our experience :)



> I ran check_characters on my dataset again with the new tag and it did flag a problem sentence, so based on the change you made, my data isn't in a normalized format.

This should allow you to move forward, right ?



> I have been using a modified version of import_cv2.py (my audio is already in wav files), but I hadn't been using the normalize flag. I did modify it further because it normalizes to NFKD by default. That may cause an issue to others in the future, having import_cv2.py normalize to NFKD and check_characters test for NFKC.

Technically, NFKD or NFKC we don't care, but what it more important is that all your datasets are sharing the same normalization. Otherwise you risk having two different unicode characters for the same "user-visible" character. This will obviously impact quality.



> If I could offer one suggestion, I would add "when generating your csv files" to the end of "Consider using NFKC normalization: unicodedata.normalize('NFKC', str)."

We had discussions about that, but it's not really clear we would like to enforce such a thing.

**Comment by hjortnaes** [comment]
> Ok, so it's at least consistent with our experience :)
Yep! Very edge case problem.

> This should allow you to move forward, right?
I had already moved forward by just manually editing the alphabet file.

> Technically, NFKD or NFKC we don't care, but what it more important is that all your datasets are 
> sharing the same normalization. Otherwise you risk having two different unicode characters for the 
> same "user-visible" character. This will obviously impact quality.
Right, so if someone follows the workflow import_cv2.py --> check_characters.py like I did (and I think that's the recommended for commonvoice data, right?) they'll run into issues because they use NFKD and NFKC respectively by default.

> We had discussions about that, but it's not really clear we would like to enforce such a thing.
That's fair, and if someone is using a custom dataset like I am they should probably know enough to figure it out.

**Comment by lissyx** [comment]
> Right, so if someone follows the workflow import_cv2.py --> check_characters.py like I did (and I think that's the recommended for commonvoice data, right?) they'll run into issues because they use NFKD and NFKC respectively by default.

Could you please be explicit on the language you imported ? I missed the fact that we were talking about Common Voice.

What language is this ?

> That's fair, and if someone is using a custom dataset like I am they should probably know enough to figure it out.

Yeah, but if we have **released** Common Voice that exposes the behavior, it's another story.

We had to fix that on some not-yet-released part of Common Voice French, and it's already quite a mess.

**Comment by hjortnaes** [comment]
> Could you please be explicit on the language you imported ? I missed the fact that we were talking 
> about Common Voice.

Sorry for the confusion, we are not, I was thinking in hypotheticals here. To sum up what I'm saying, shouldn't the normalization across scripts in DeepSpeech be consistent, regardless of which is chosen?

> Yeah, but if we have released Common Voice that exposes the behavior, it's another story.

As far as I know, you have not. I am working with a Komi dataset I obtained from a colleague, which I unfortunately cannot share at this time.

**Comment by reuben** [comment]
`import_cv2.py` only does NFKD normalization immediately followed by a call to `.encode('ascii', 'ignore')`, which serves as a simple way to eliminate some common diacritics. (And that behavior is behind a flag). It doesn't do NFKD alone, that would break any non-English language.

**Comment by lissyx** [comment]
> Sorry for the confusion, we are not, I was thinking in hypotheticals here. To sum up what I'm saying, shouldn't the normalization across scripts in DeepSpeech be consistent, regardless of which is chosen?

That's why i've implemented this flag for checking. Because ultimately, we don't want to enforce. And the importers here can be used alone, mixed with others we don't know about, so I think it's better we don't try to be smart here, because that would just lead to more complexity.

**Comment by reuben** [comment]
`check_characters.py` now has a flag to warn about this.
