### ISSUE TITLE
Error Code 12294 on 0.6.0a6-11

### ISSUE THREAD

**Issue by erksch** [mozilla/DeepSpeech#2489]
- **OS Platform and Distribution**: Linux Ubuntu 19.10.
- **TensorFlow installed from**: pip
- **TensorFlow version**: v1.14.0-rc1-22-gaf24dc9 1.14.0
- **Python version**: 3.7.2
- **CUDA/cuDNN version**: 10.0/7.6.4.38-1+cuda10.0
- **GPU model and memory**: GeForce GTX 1050 2G

Hey folks!
After upgrading to alpha 11 I get an error (code 12294 = DS_ERR_FAIL_CREATE_SESS) on the Model constructor. 

This is my code:
```python
import os
import deepspeech

BEAM_WIDTH = 500
model_dir = "deepspeech-0.5.1-models"
model = os.path.join(model_dir, 'output_graph.pb')
alphabet = os.path.join(model_dir, 'alphabet.txt')
lm =  os.path.join(model_dir, "lm.binary")
trie = os.path.join(model_dir, "trie")

print('Initializing model...')
model = deepspeech.Model(model, alphabet, BEAM_WIDTH)
```

The error: 
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-e606a29550d0> in <module>
     10 
     11 print('Initializing model...')
---> 12 model = deepspeech.Model(model, alphabet, BEAM_WIDTH)

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/deepspeech/__init__.py in __init__(self, *args, **kwargs)
     25         status, impl = deepspeech.impl.CreateModel(*args, **kwargs)
     26         if status != 0:
---> 27             raise RuntimeError("CreateModel failed with error code {}".format(status))
     28         self._impl = impl
     29 

RuntimeError: CreateModel failed with error code 12294
```

The error appears on alpha 6 (since the model constructor changed).
As you can see I am using the 0.5.1-models. Are there new models that have to be used?

**Comment by lissyx** [comment]
> The error appears on alpha 6 (since the model constructor changed).
> As you can see I am using the 0.5.1-models. Are there new models that have to be used?

A lot changed, the API has been simplified and we have changed the way metadata are being handled.

No v0.6 model is yet avalable.

This is not a bug, please use Discourse for further discussion.

**Comment by erksch** [comment]
Thank you for the quick response!
