### ISSUE TITLE
Use architecture specific NodeJS packages in tests to avoid waiting for slow macOS tasks

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2497]
Right now we build a single CPU package that has all platforms in it and use that package for all the NodeJS tests. This means every NodeJS test on any platform needs to wait for macOS builds to finish. We could instead make the tests depend on the architecture specific packages to speed things up. Note that we should probably keep a set of tests still using with the multi-platform package to make sure we don't break the package creation itself.

@lissyx thoughts?

**Comment by lissyx** [comment]
The real proper fix would be to have better macOS infra :-). But that's okay by me, as long as we also keep good enough coverage for the multi-platform package.

**Comment by lissyx** [comment]
I'll do that with #2501

**Comment by lissyx** [comment]
Final package will be checked:
 - ensuring the number of `libdeepspeech.so` matches what we want (arch and versions)
 - running tests with latest version package only, on all arch

This should get us good coverage and not explode the amount of tests we run.
