### ISSUE TITLE
Integration with Live Transcribe Speech Engine

### ISSUE THREAD

**Issue by breandan** [mozilla/DeepSpeech#2499]
Does DeepSpeech [native client](https://github.com/mozilla/DeepSpeech/tree/master/native_client) plan to integrate with the newly published the Live Transcribe Speech Engine? It would be nice to implement a [`SpeechSessionListener`](https://github.com/google/live-transcribe-speech-engine/blob/8a96ef3f3027ef8cf402b53bd2ce87f37f007951/app/src/main/java/com/google/audio/asr/SpeechSessionListener.java). cc: @lissyx @reuben

**Comment by reuben** [comment]
No plans, but this would probably be a cool project for someone interested in DeepSpeech.

**Comment by kdavis-mozilla** [comment]
As this will likely be external to this repo, I'll close. If there are objections, let me know.
