### ISSUE TITLE
Checkpoint files should be saved in checkpoint_dir named after the commit hash

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#250]
Instead of saving checkpoints in the directory

`checkpoint_dir`

we should create a sub directory of `checkpoint_dir` named after the current commit's hash `<commit_hash>`, then save the checkpoints under

`checkpoint_dir/<commit_hash>`

This would allow us sync the checkpoints with the apropos commit, thus allowing us to load old checkpoints even through the current operator graph is no longer compatible with the older checkpoints.

**Comment by lissyx** [comment]
I could take this one and make it a part of a greater goal of enabling auto-restore of checkpoint. For example, we could use the present issue in the case of a power outage/crash/change of parameters like we already had. We would need to figure out a way for other usecases.

**Comment by kdavis-mozilla** [comment]
It's yours!
