### ISSUE TITLE
TypeError: CreateModel() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by sehargul-123** [mozilla/DeepSpeech#2508]
sehar@sehar-HP-Z220-CMT-Workstation:~/DeepSpeech/examples/mic_vad_streaming$ python mic_vad_streaming.py   --model $HOME/sehar/urdu-models/output_graph.pb   --alphabet $HOME/sehar/urdu-models/alphabet.txt   --lm $HOME/sehar/urdu-models/lm.binary   --trie $HOME/sehar/urdu-models/trie   --file $HOME/sehar/urdumodels/sent6urd.wav
Initializing model...
INFO:root:ARGS.model: /home/sehar/sehar/urdu-models/output_graph.pb
Traceback (most recent call last):
  File "mic_vad_streaming.py", line 243, in <module>
    main(ARGS)
  File "mic_vad_streaming.py", line 168, in main
    logging.info("ARGS.alphabet: %s", ARGS.alphabet).model = deepspeech.Model(ARGS.model, ARGS.alphabet, ARGS.beam_width)
  File "/home/sehar/.local/lib/python2.7/site-packages/deepspeech/__init__.py", line 40, in __init__
    status, impl = deepspeech.impl.CreateModel(*args, **kwargs)
TypeError: CreateModel() takes at most 2 arguments (3 given)

**Comment by sehargul-123** [comment]
kindly help

**Comment by lissyx** [comment]
Kindly read the documentation. I already replied to this on discourse.
