### ISSUE TITLE
Documentation specifies different number of dense layer units compared to code

### ISSUE THREAD

**Issue by shan18** [mozilla/DeepSpeech#2512]
In the documentation, `doc/Geometry.rst`, [this section](https://github.com/mozilla/DeepSpeech/blob/master/doc/Geometry.rst#n_hidden_3) specifies that the number of units in the 3rd hidden layer should be equal to twice the state size of LSTM layer, but when I reference the code `util/config.py`
https://github.com/mozilla/DeepSpeech/blob/d754e53f21657abdd8c139909111993b46d5293c/util/config.py#L93
it sets the number of units in the 3rd hidden layer to be equal to the state size of LSTM. Which one to consider?

**Comment by lissyx** [comment]
This documentation is outdated, and I have been too lazy to find time to fix it 😢

**Comment by lissyx** [comment]
If you are willing to dig into the code and fix the doc you are welcome, though. I started things in https://github.com/mozilla/DeepSpeech/pull/2399

**Comment by shan18** [comment]
Okay. I have been digging into the code for quite some time. I'll try to update the docs.

**Comment by lissyx** [comment]
This was fixed today.
