### ISSUE TITLE
Sorting WAV files causes the model to occupy entire system memory at epoch end

### ISSUE THREAD

**Issue by shan18** [mozilla/DeepSpeech#2513]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **TensorFlow installed from**: upstream TensorFlow
- **TensorFlow version**: 1.14.0
- **Python version**: 3.6.8
- **CUDA/cuDNN version**: 10.0 / 7.6
- **GPU model and memory**: GTX 1080 Ti (12 GB)
- **Exact command to reproduce**:
```bash
python3 DeepSpeech.py --n_hidden 2048 --epoch 100 \
--train_files data/train.csv \
--dev_files data/dev.csv \
--test_files data/test.csv \
--checkpoint_dir ~/checkpoints \
--export_dir ~/checkpoints/export \
--train_batch_size 24 \
--dev_batch_size 24 \
--test_batch_size 48 \
--learning_rate 0.0001 \
--dropout_rate 0.15 \
--lm_alpha 0.75 \
--lm_beta 1.85 \
--alphabet_config_path data/alphabet.txt \
--beam_width 1024
```

When I train the model as it is, it occupies 97% for my machine RAM at the ending steps of the epoch which slows down the machine and I have to kill the process before it can even finish one epoch.

However, when I trained the model again by just **removing** the line which sorts the WAV files, the training went fine and there were no memory issues.

I trained the model on both the cases using the LibriSpeech dataset which after processing contains 104 GB of WAV files.

Why are the WAV files sorted in increasing order of their size before the generator is created?
https://github.com/mozilla/DeepSpeech/blob/179d4d6f318319bcb221414f4da3d951a07691d8/util/feeding.py#L99

**Comment by lissyx** [comment]
This is the sorting for batching file by size, as much as I remember. Maybe @reuben can complete, but this is obviously not a bug for sure.

**Comment by dabinat** [comment]
The massive difference in memory usage seems like it might be a bug though. Is that expected behavior?

**Comment by lissyx** [comment]
If it is, then it's on pandas anyway... But sorting 104GB of files in-memory is it surprising?

**Comment by lissyx** [comment]
BTW the issue was opened on the question of why we sort anyway.

**Comment by lissyx** [comment]
> it occupies 97% for my machine RAM

@shan18 How much RAM do you have ?

**Comment by shan18** [comment]
@lissyx I have 64 GB of RAM on my machine. I don't think it's the issue with RAM. Because when I ran the model without sorting the dataframe, it ran without any issues.

**Comment by reuben** [comment]
Try disabling feature caching (remove the `.cache()` call in feeding.py) or caching features to disk rather than memory (specify --feature_cache flag), that's probably what's causing this.

**Comment by shan18** [comment]
@reuben I'll try it out. Thank you.

**Comment by shan18** [comment]
And can you please tell me why are the files sorted according to their size? Is it achieving something specific or is there no particular reason?

**Comment by reuben** [comment]
https://ronan.collobert.com/pub/matos/2009_curriculum_icml.pdf
