### ISSUE TITLE
Documentation of easy install and use throwing an error

### ISSUE THREAD

**Issue by massielislas** [mozilla/DeepSpeech#2517]
Following the initial README in "To install and use deepspeech all you have to do is:"
I get the following error:

`(deepspeech-venv) massiel@Massiels-MBP:~/tmp/deepspeech-venv $ deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
usage: deepspeech [-h] --model MODEL --alphabet ALPHABET [--lm [LM]]
                  [--trie [TRIE]] --audio AUDIO [--version] [--extended]
deepspeech: error: the following arguments are required: --alphabet`

For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave 10.14.6
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream Tensor flow
- **TensorFlow version (use command below)**: 2.0.0
- **Python version**: Python 3.7.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

`deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav`

**Comment by kdavis-mozilla** [comment]
Could you fill out the issue template so we can understand what went wrong? Also, could you provide the error message to help us debug.

**Comment by lissyx** [comment]
Are you looking at v0.5.1 README @massielislas ? From your error it looks like you are reading doc from master and apply to v0.5.1.

**Comment by lissyx** [comment]
@massielislas Ping ? Can you update us ?

**Comment by massielislas** [comment]
I am looking at the documentation at  https://github.com/mozilla/DeepSpeech on the master branch.

**Comment by massielislas** [comment]
The documentation looks as follows:
![image](https://user-images.githubusercontent.com/31866147/68806101-67e5f580-0622-11ea-92da-39705eeca44a.png)

**Comment by massielislas** [comment]
@lissyx Tried running those commands today and it gives me the error I pointed out in the post

**Comment by lissyx** [comment]
@massielislas As I said, please look for the documentation matching the release you are using.
