### ISSUE TITLE
Build Error when using the Java native client

### ISSUE THREAD

**Issue by sarasamara7** [mozilla/DeepSpeech#2518]
We're having a gradle build error when we're using the Java client. Is it because it's still preliminary work? Can you please provide clear steps for running the Java Client in the documentation?

**Comment by lissyx** [comment]
Are we supposed to also guess your error?

**Comment by lissyx** [comment]
@sarasamara7 can you provide actionable feedback on what is unclear in the documentation?

**Comment by lissyx** [comment]
@sarasamara7 Can you update us ?

**Comment by lissyx** [comment]
@sarasamara7 No feedback, the code is working for us, I'm afraid there's nothing we can do.
