### ISSUE TITLE
Set state_is_tuple=True on BasicLSTMCell

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#253]
It is said to have a performance impact to keep the cell's state as tuple. We need to test this. Please be aware that this most probably implies a change to the model's structure.

**Comment by reuben** [comment]
I don't think it implies a change to the model, since we don't look at the state output of the RNN.

**Comment by kdavis-mozilla** [comment]
But are ops inserted in to the graph by `tf.nn.rnn_cell.BasicLSTMCell()` changed by `state_is_tuple=True`?

**Comment by kdavis-mozilla** [comment]
I guess the easy way to find out is to simply checkpoint with `state_is_tuple=False` then set `state_is_tuple=True` and try to load it.

**Comment by reuben** [comment]
Hm, I see. Looks like the ops are different. state_is_tuple=True eliminates a split and a concat.

**Comment by tilmankamp** [comment]
Seems to have no significant effect - closing it.
