### ISSUE TITLE
Inference takes too long

### ISSUE THREAD

**Issue by samhithaaaa** [mozilla/DeepSpeech#2530]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 18.0
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:1.12
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:No gpu only cpu 
- **Exact command to reproduce**:python audioTranscript_cmd.py --model ./models --aggressive 0 --audio audio/2952-410-0047.wav
You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

I am trying to run the deepspeech inference with live streaming support ,But the inference is twice as the length of audio file in time.
what could be done to lessen the inference time??any suggestions please

Thanks in advance:)

**Comment by lissyx** [comment]
@samhithaaaa This is not a bug. Please seek support on Discourse and share more informations.
