### ISSUE TITLE
Nothing seems to work correctly.  Even the very first call is bad.   

### ISSUE THREAD

**Issue by MikeyBeez** [mozilla/DeepSpeech#2540]
Even the start of the readme is wrong.  The first usage: # Transcribe an audio file
deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav needs to include a path to the alphabet:   deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --audio audio/8455-210777-0068.wav --alphabet deepspeech-0.5.1-models/alphabet.txt 
 Then it works, but still, all the examples core dump.

**Comment by kdavis-mozilla** [comment]
Please use the [0.5.1 documentation](https://github.com/mozilla/DeepSpeech/tree/v0.5.1) when using the [0.5.1 models and code](https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.1) and everything should work as advertised.

**Comment by lissyx** [comment]
> Even the start of the readme is wrong. The first usage: # Transcribe an audio file
> deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav needs to include a path to the alphabet: deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --audio audio/8455-210777-0068.wav --alphabet deepspeech-0.5.1-models/alphabet.txt
> Then it works, but still, all the examples core dump.

@MikeyBeez  Can you be more explicit on those examples ?

`pip3 install deepspeech` should install you 0.5.1. Can you check you have that ? `pip3 list | grep deepspeech`

**Comment by angularorbit** [comment]
The readme instructions seem to be about the development version `deepspeech`,  not `deepspeech 0.5.1`, which is normal since the master branch seems to be the development branch. That needs to be clarified in the readme.

`deepspeech 0.5.1`, the version currently installed by `pip` needs an `--alphabet` argument, but the readme instructions removed it.

**Comment by reuben** [comment]
Added a reminder about reading the documentation for the version installed.
