### ISSUE TITLE
Speech to Text Convertion Issue

### ISSUE THREAD

**Issue by sudhanshu2k** [mozilla/DeepSpeech#2542]
I am using Deepspeech library for converting Speech to Text by using custom 16-bit, 16 kHz, mono-channel WAVE audio files. But text is no where related to speech.
Could you please suggest how I can get expected text output from speech?

**Comment by lissyx** [comment]
> I am using Deepspeech library for converting Speech to Text by using custom 16-bit, 16 kHz, mono-channel WAVE audio files. But text is no where related to speech.
> Could you please suggest how I can get expected text output from speech?

Could you please read the issue template and ask that on Discourse ?
