### ISSUE TITLE
I am trying to run the pre-trained model deepspeech-0.5.1 with the commands. It shows CreateModel failed with error code 8195. Please help.

### ISSUE THREAD

**Issue by kapilg1997** [mozilla/DeepSpeech#2549]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by kapilg1997** [comment]
# Download pre-trained English model and extract
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
tar xvf deepspeech-0.5.1-models.tar.gz

# Download example audio files
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/audio-0.5.1.tar.gz
tar xvf audio-0.5.1.tar.gz

# Transcribe an audio file
deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav 

Following error occurs

![Capture](https://user-images.githubusercontent.com/51714717/69601174-51d03000-1039-11ea-8f91-3bcd77a23ed1.JPG)

**Comment by kdavis-mozilla** [comment]
Anaconda is not supported. Could you try using a virtual environment as documented [here](https://github.com/mozilla/DeepSpeech/tree/v0.5.1#create-a-deepspeech-virtual-environment).

**Comment by lissyx** [comment]
> # Download pre-trained English model and extract
> 
> curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
> tar xvf deepspeech-0.5.1-models.tar.gz
> # Download example audio files
> 
> curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/audio-0.5.1.tar.gz
> tar xvf audio-0.5.1.tar.gz
> # Transcribe an audio file
> 
> deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
> 
> Following error occurs
> 
> ![Capture](https://user-images.githubusercontent.com/51714717/69601174-51d03000-1039-11ea-8f91-3bcd77a23ed1.JPG)

You are running mismatching versions. Please avoid posting screenshots, it is hard to read and not searchable for content.

Please use deepspeech 0.5.1 binary to run 0.5.1 models.

This is not a bug, so please take this to Discourse.
