### ISSUE TITLE
CreateModel failed with error code 8195. 

### ISSUE THREAD

**Issue by kapilg1997** [mozilla/DeepSpeech#2550]
I created a virtual environment as anaconda is not supported and tries to run the pretrained model on the example audio files provided by using the exact commands in read.md
# Download pre-trained English model and extract
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
tar xvf deepspeech-0.5.1-models.tar.gz

# Download example audio files
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/audio-0.5.1.tar.gz
tar xvf audio-0.5.1.tar.gz

# Transcribe an audio file
deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav

But there is following error

(ds_venv) C:\Users\Gund\Testing_DS>deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
Loading model from file deepspeech-0.5.1-models/output_graph.pbmm
TensorFlow: v1.14.0-21-ge77504ac6b
DeepSpeech: v0.6.0-alpha.15-0-gb3787ee
2019-11-26 13:30:51.806967: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Unable to fetch graph version: Invalid argument: Session was not created with a graph before Run()!
Traceback (most recent call last):
  File "c:\users\gund\anaconda3\envs\ds_venv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gund\anaconda3\envs\ds_venv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gund\Anaconda3\envs\ds_venv\Scripts\deepspeech.exe\__main__.py", line 7, in <module>
  File "c:\users\gund\anaconda3\envs\ds_venv\lib\site-packages\deepspeech\client.py", line 69, in main
    ds = Model(args.model, args.beam_width)
  File "c:\users\gund\anaconda3\envs\ds_venv\lib\site-packages\deepspeech\__init__.py", line 42, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 8195

(Even though specified model is v0.5.1 model version installed is 0.6.0. What commands should I use the use the model installed by me?
i tried the following

(ds_venv) C:\Users\Gund\Testing_DS>deepspeech --model deepspeech-0.6.0a15-models/output_graph.pbmm --lm deepspeech-0.6.0a15-models/lm.binary --trie deepspeech-0.6.0a15-models/trie --audio audio/2830-3980-0043.wav

and the error is "DLL load failed: The specified module could not be found."

**Comment by lissyx** [comment]
Use discourse.

**Comment by lissyx** [comment]
@kapilg1997 We don't have Python bindings for Windows on 0.5.1. That's why you got 0.6 binaries. Please wait until we release 0.6 models.
