### ISSUE TITLE
Error in checkpoint model 0.5.0 with transfer learning

### ISSUE THREAD

**Issue by olesyaksyon** [mozilla/DeepSpeech#2556]
Hi! 

I am trying to transfer learn model-v0.5.0. with transfer-learning branch

Parametrs:
python DeepSpeech.py \
--drop_source_layers 2 \
--source_model_checkpoint_dir /DeepSpeech/deepspeech-0.5.0-checkpoint \
--checkpoint_dir /DeepSpeech/checkpoints/ \
--n_hidden 2048 --learning_rate 0.0001 --train_batch_size 1 --dev_batch_size 2 --test_batch_size 1 --epoch 1

The error message:
tensorflow.python.framework.errors_impl.NotFoundError: Key b1 not found in checkpoint

**Comment by lissyx** [comment]
`transfer-learning` is not maintained, I think you need to use `transfer-learning2`. Maybe @JRMeyer can give more insight, but it's Thanks Giving, so I doubt you can get feedback from him before next monday.

**Comment by lissyx** [comment]
@olesyaksyon @JRMeyer Ping?

**Comment by JRMeyer** [comment]
correct - you should use the `transfer-learning2` branch

**Comment by olesyaksyon** [comment]
ok, thanks
