### ISSUE TITLE
Is is possible to add the 0.5.1 wheels for python 3.8 (all arch/os) ?

### ISSUE THREAD

**Issue by shazz** [mozilla/DeepSpeech#2557]
Hi,

Not a bug, but as the 0.6.0x is not yet stable, it would be great to add to https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.1 assets the whl files for python 3.8.

And also to Pypi.
````
$ pip install deepspeech==0.5.1
ERROR: Could not find a version that satisfies the requirement deepspeech==0.5.1 (from versions: 0.6.0a11, 0.6.0a12, 0.6.0a13, 0.6.0a14, 0.6.0a15)
ERROR: No matching distribution found for deepspeech==0.5.1
````

Thanks !

**Comment by kdavis-mozilla** [comment]
0.6.0 will be out soon enough, within the week, that backporting 3.8 support is not going to be an efficient use of our time.
