### ISSUE TITLE
transcribe.py functionality and docs

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/DeepSpeech#2566]
`transcribe.py` has odd directory-scanning behavior which isn't documented

If you point `--src` to a directory, you get the error:

```
E Path in --src not existing
```

Looking at the code logic, the script expects a `JSON` file with a `.catalog` file extension. This is (1) not documented, and (2) not a really useful logic. It would be much better to point the script to a dir, and scan for audio, and then decode.

would you welcome a PR for this?

**Comment by JRMeyer** [comment]
I made a PR addressing this: #2567

**Comment by rhamnett** [comment]
This can be closed, works well. Thanks
