### ISSUE TITLE
Experimental: Using conv2d on mfcc input data to establish redundant context around time slices

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#257]

**Comment by kdavis-mozilla** [comment]
Could you give a bit more details?

**Comment by reuben** [comment]
FWIW, the way we input time steps with some context around them is *already* a type of convolution, with stride=1.

The first Deep Speech paper additionally fed data from the third layer into the recurrent layer by skipping every other time step (convolution with stride=2). Maybe that's what @tilmankamp is referring to?

**Comment by reuben** [comment]
Hm, maybe I misunderstood the paper previously and they actually use a 1D convolution on the first layer, not before the RNN. Here's what it says:

> We have worked to minimize the running time of the recurrent layers of our RNN, since these are the hardest to parallelize. As a final optimization, we shorten the recurrent layers by taking “steps” (or strides) of size 2 in the original input so that the unrolled RNN has half as many steps. This is similar to a convolutional network [25] with a step-size of 2 in the first layer. We use the cuDNN library [2] to implement this first layer of convolution efficiently.

**Comment by kdavis-mozilla** [comment]
They basically make the RNN twice as fast by skipping time steps.

So instead of something like
```
    outputs = []
    state = initial_state
    with tf.variable_scope("RNN"):
      for time_step in range(num_steps):
        if time_step > 0: tf.get_variable_scope().reuse_variables()
        (cell_output, state) = cell(inputs[:, time_step, :], state)
        outputs.append(cell_output)
```
they do
```
    outputs = []
    state = initial_state
    with tf.variable_scope("RNN"):
      for time_step in range(0, num_steps, 2):
        if time_step > 0: tf.get_variable_scope().reuse_variables()
        (cell_output, state) = cell(inputs[:, time_step, :], state)
        outputs.append(cell_output)
```

**Comment by reuben** [comment]
Yeah, that was my initial understanding as well. I then wondered if "first layer" in the paper means "first recurrent layer" or "first layer of the network". But I think you're right.

**Comment by kdavis-mozilla** [comment]
They mention the RNN explicitly 

> We have worked to minimize the running time of the recurrent layers of our RNN, since these are the hardest to parallelize. As a final optimization, we shorten the recurrent layers by taking “steps” (or strides) of size 2 in the original input so that the unrolled RNN has half as many steps.

so my reading is that they do as I did above.

**Comment by tilmankamp** [comment]
[Some StackOverflow answer](http://stackoverflow.com/questions/40186583/tensorflow-slicing-a-tensor-into-overlapping-blocks?answertab=votes#tab-top) inspired me for this approach. The `conv2d` answer is pretty smart. At least its worth taking a second look.

However: Kelly's approach is worth another experiment/issue, right?

**Comment by kdavis-mozilla** [comment]
@tilmankamp I think both are worth a look. However, my approach will likely increase WER, the question is how much. Also one needs to double my approach for the BRNN, one RNN for forward in time one fore backward.

Also, from the StackOverflow answer I wonder if all the ops in `overlap()` have GPU implementations.

If they don't, then I don't think this will help as instead of being able to push the original data to the GPU and create the context there we'll be creating the context on the CPU, as we are now, then pushing the redundant data to the GPU.

**Comment by kdavis-mozilla** [comment]
Introduced issue #284 to track my approach

**Comment by kdavis-mozilla** [comment]
@tilmankamp With you're recent result should this be closed?

**Comment by tilmankamp** [comment]
@kdavis-mozilla Still analyzing. No need to hurry.

**Comment by tilmankamp** [comment]
This approach has two drawbacks:
- It needs CPU bound operations to bundle the list of required convolutions. There are some alternative ways to implement this, but those are also not known to be 100% GPU ready.
- There seems to be no memory saving effect. Training fails at the same batch-sizes as the current solution. 
So I am closing this now.
