### ISSUE TITLE
Node module in Mac OSX - error

### ISSUE THREAD

**Issue by pietrop** [mozilla/DeepSpeech#2570]
I followed these instructions for [NodeJS voice recognition example using Mozilla DeepSpeech](https://github.com/mozilla/DeepSpeech/tree/master/examples/nodejs_wav) on Mac OSX but I got the following error 

```bash
$ node index.js
TensorFlow: v1.14.0-21-ge77504ac6b
DeepSpeech: v0.6.0-0-g6d43e21
2019-12-04 12:08:18.846222: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Unable to fetch graph version: Invalid argument: Session was not created with a graph before Run()!

/Users/passarellip/CODE/PERSONAL/deepspeech-test/node_modules/deepspeech/index.js:39
        throw "CreateModel failed with error code " + status;
        ^
CreateModel failed with error code 8195
```

Am I missing some steps? or does the node module only work with Linux?

**Comment by lissyx** [comment]
> I followed these instructions for [NodeJS voice recognition example using Mozilla DeepSpeech](https://github.com/mozilla/DeepSpeech/tree/master/examples/nodejs_wav) on Mac OSX but I got the following error
> 
> ```shell
> $ node index.js
> TensorFlow: v1.14.0-21-ge77504ac6b
> DeepSpeech: v0.6.0-0-g6d43e21
> 2019-12-04 12:08:18.846222: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Unable to fetch graph version: Invalid argument: Session was not created with a graph before Run()!
> 
> /Users/passarellip/CODE/PERSONAL/deepspeech-test/node_modules/deepspeech/index.js:39
>         throw "CreateModel failed with error code " + status;
>         ^
> CreateModel failed with error code 8195
> ```
> 
> Am I missing some steps? or does the node module only work with Linux?

That codes expects a `output_graph.pbmm` in the `models/` directory, as well as LM files: https://github.com/mozilla/DeepSpeech/blob/master/examples/nodejs_wav/index.js#L8-L18

Also, it seems the README was not updated and it still refers to v0.4.1 models. Have you downloaded v0.6.0 models or v0.4.1 ?

Your error code 0x2003: https://deepspeech.readthedocs.io/en/v0.6.0/Error-Codes.html#_CPPv425DS_ERR_MODEL_INCOMPATIBLE

**Comment by pietrop** [comment]
Thanks, it works after updating to the latest models 
```
$ node index.js audio/4507-16021-0012.wav
TensorFlow: v1.14.0-21-ge77504ac6b
DeepSpeech: v0.6.0-0-g6d43e21
2019-12-04 14:21:32.541988: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
audio length 2.735
result: why should one halt on the way
```

but still get error message/warning

>2019-12-04 14:21:32.541988: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Do you also know if there's a way to get word level timings via the node module?

**Comment by lissyx** [comment]
> ```
> 
> ```
> 
> 
> but still get error message/warning
> 
> > 2019-12-04 14:21:32.541988: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Yeha, it's not a big deal, it just says you don't make full use of your CPU ...



> Do you also know if there's a way to get word level timings via the node module?

Have you had a look at the API's documentation ? https://deepspeech.readthedocs.io/en/v0.6.0/NodeJS-API.html#Model.finishStreamWithMetadata

Anyway, there's no bug, please take further discussion to Discourse instead.

**Comment by pietrop** [comment]
ok great, thanks, I raised a tiny PR to update the README instructions of the node example https://github.com/mozilla/DeepSpeech/pull/2571
