### ISSUE TITLE
OSError: [Errno -9997] Invalid sample rate

### ISSUE THREAD

**Issue by Technerder** [mozilla/DeepSpeech#2575]
I tried running the `mic_vad_streaming` example on my raspberry pi and was met with the following error:

Output: https://gist.github.com/Technerder/4c95fcbe24911965e276eeea46d68cf8
Code: https://github.com/mozilla/DeepSpeech/blob/master/examples/mic_vad_streaming/mic_vad_streaming.py
Command: `python3 mic_vad_streaming.py -m models/output_graph.tflite -l models/lm.binary`

OS: `Raspbian GNU/Linux 10 (buster) armv7l  (Raspberry pi 4)`
TensorFlow: `v1.14.0-21-ge77504a`
DeepSpeech: `v0.6.0-0-g6d43e21`
Python: `3.7.3`

How can I fix this?

**Comment by lissyx** [comment]
> I tried running the `mic_vad_streaming` example on my raspberry pi and was met with the following error:
> 
> Output: https://gist.github.com/Technerder/4c95fcbe24911965e276eeea46d68cf8
> Code: https://github.com/mozilla/DeepSpeech/blob/master/examples/mic_vad_streaming/mic_vad_streaming.py
> Command: `python3 mic_vad_streaming.py -m models/output_graph.tflite -l models/lm.binary`
> 
> OS: `Raspbian GNU/Linux 10 (buster) armv7l (Raspberry pi 4)`
> TensorFlow: `v1.14.0-21-ge77504a`
> DeepSpeech: `v0.6.0-0-g6d43e21`
> Python: `3.7.3`
> 
> How can I fix this?

It looks like your hardware does not like the sample rate, sorry.

**Comment by Technerder** [comment]
I assume you're referring to the microphone and not the raspberry pi?

**Comment by lissyx** [comment]
> I assume you're referring to the microphone and not the raspberry pi?

Maybe, I don't know your setup.

**Comment by Technerder** [comment]
``https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/`` says that it's been tested on the raspberry pi 4. Does my microphone need to support a specific sample rate?

**Comment by lissyx** [comment]
> `https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/` says that it's been tested on the raspberry pi 4. Does my microphone need to support a specific sample rate?

I never played with this example on RPi4. It's not impossible some hardware have different behavior regarding sample rate of microphone.

What was tested is that we are able to perform real-time inference, using C++ client and well as other bindings, that takes existing WAV files.

**Comment by Technerder** [comment]
The main example at the top of the README works without any issues for me. What sample rate does microphone need to support?

**Comment by reuben** [comment]
The mic_vad_streaming example passes sample rate 16000 to PyAudio.

**Comment by lissyx** [comment]
@Technerder Have you been able to figure this out ?

**Comment by Technerder** [comment]
I've just purchased a microphone that specifically supports 16kHz audio, and should hopefully be able to test it within the upcoming week.

**Comment by Technerder** [comment]
I'm recieving the same error as before while using [this](https://www.amazon.com/gp/product/B01MQ2AA0X/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) microphone which specifies a frequency response range of 100-16Khz, which also specifically supports the raspberry pi.

**Comment by Technerder** [comment]
@lissyx @reuben Would any of you be able to test the live example and see if it works on a raspberry pi (or just a normal Linux installation)?

**Comment by lissyx** [comment]
> @lissyx @reuben Would any of you be able to test the live example and see if it works on a raspberry pi (or just a normal Linux installation)?

I might try

**Comment by Technerder** [comment]
Awesome, I'd try it on a normal Linux machine myself but my CPU's don't support a lot of instructions required by tensorflow.

**Comment by lissyx** [comment]
> @lissyx @reuben Would any of you be able to test the live example and see if it works on a raspberry pi (or just a normal Linux installation)?

Could you verify your pulseaudio setup also? I'm seeing reports: https://community.mycroft.ai/t/alsa-issue-oserror-errno-9997-invalid-sample-rate/5070

**Comment by Technerder** [comment]
Their solution seems to have fixed it, thanks!
