### ISSUE TITLE
Pre-trained model is not being downloaded

### ISSUE THREAD

**Issue by kapilg1997** [mozilla/DeepSpeech#2578]
I am trying to run the pre-trained model for English on Ubuntu 18.0.4
I installed it using 
pip install deepspeech
(Version 0.6.0 was installed)
then when i use the given commands for pretrained model, it has been stuck for more than three hours

(base) kapilg1997@DESKTOP-BAUSO2O:~$ conda activate ds_venv
(ds_venv) kapilg1997@DESKTOP-BAUSO2O:~$ curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.6.0/deepspeech-0.6.0-models.tar.gz

It is stuck here. Please help.

**Comment by lissyx** [comment]
> I am trying to run the pre-trained model for English on Ubuntu 18.0.4
> I installed it using
> pip install deepspeech
> (Version 0.6.0 was installed)
> then when i use the given commands for pretrained model, it has been stuck for more than three hours
> 
> (base) kapilg1997@DESKTOP-BAUSO2O:~$ conda activate ds_venv (ds_venv) kapilg1997@DESKTOP-BAUSO2O:~$ curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.6.0/deepspeech-0.6.0-models.tar.gz
> 
> It is stuck here. Please help.

It's hard to help you without more context. What's your internet access? Model is quite big, it might just be slow ?

**Comment by kapilg1997** [comment]
> > I am trying to run the pre-trained model for English on Ubuntu 18.0.4
> > I installed it using
> > pip install deepspeech
> > (Version 0.6.0 was installed)
> > then when i use the given commands for pretrained model, it has been stuck for more than three hours
> > (base) kapilg1997@DESKTOP-BAUSO2O:~$ conda activate ds_venv (ds_venv) kapilg1997@DESKTOP-BAUSO2O:~$ curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.6.0/deepspeech-0.6.0-models.tar.gz
> > It is stuck here. Please help.
> 
> It's hard to help you without more context. What's your internet access? Model is quite big, it might just be slow ?

I have changed my internet connection and I'm trying again.

**Comment by kapilg1997** [comment]
I changed my internet connection and used this.

 wget https://github.com/mozilla/DeepSpeech/releases/download/v0.6.0/deepspeech-0.6.0-models.tar.gz

The model has been downloaded. Thank you.
