### ISSUE TITLE
Publish desktop TFLite builds to PyPI as deepspeech-tflite

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2580]
Then one could do `pip install deepspeech==0.6.0+tflite`.

**Comment by lissyx** [comment]
How is semver handling the `+tflite`?

**Comment by reuben** [comment]
Semver is fine with it: https://semver.org/#spec-item-10

But PEP-440 isn't :( https://www.python.org/dev/peps/pep-0440/#local-version-identifiers

I thought PyTorch was doing this, but they have their own package index page, they don't use PyPI  :(

**Comment by reuben** [comment]
v0.6.1-alpha.0 just finished building with the changes in #2586, but the Windows package wasn't pushed to PyPI because I forgot to add the Windows task to the PyPI task's dependencies.

**Comment by lissyx** [comment]
I think we can close: https://pypi.org/project/deepspeech-tflite/#files
