### ISSUE TITLE
Bazel does not ccomplete successfully for native_client:ds_git_version

### ISSUE THREAD

**Issue by cli0** [mozilla/DeepSpeech#2584]
If you've found a bug, or have a feature request, then please create an issue with the following information:

- ** DeepSpeech version: 0.4.1 (fixed typo)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: tf 1.12
- **TensorFlow version (use command below)**: tf 1.12
- **Python version**: 3.6.9
- **Bazel version (if compiling from source)**: 0.15.0

I need to train a model using DS 0.14.1 but during the bazel build I get the following error:

```
(deepspeech-german) clio@Trantor:~/Desktop/deepspeech-german/tensorflow$ bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 2 targets...
ERROR: /home/clio/Desktop/deepspeech-german/tensorflow/native_client/BUILD:9:1: Executing genrule //native_client:ds_git_version failed (Exit 1)
INFO: Elapsed time: 1.142s, Critical Path: 0.76s
INFO: 8 processes: 8 local.
FAILED: Build did NOT complete successfully
```

The file ds_git_version looks like this:

```
#!/bin/sh

if [ `uname` = "Darwin" ]; then
   export PATH="/Users/build-user/TaskCluster/Workdir/tasks/tc-workdir/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
fi

GIT_DIR="$(realpath "$(dirname "$(realpath "$0")")/../.git/")"
if [ ! -d "${GIT_DIR}" ]; then
   return 1
fi;

GIT_VERSION=$(git --git-dir="${GIT_DIR}" describe --long --tags)
if [ $? -ne 0 ]; then
   GIT_VERSION=unknown;
fi

cat <<EOF
#include <string>
const char* ds_git_version() {
  return "${GIT_VERSION}";
}
EOF
```

Any ideas how to solve this?

**Comment by reuben** [comment]
There is no DeepSpeech version 0.14.1. I assume you mean 0.4.1. When building from source, make sure you clone the repository with git rather than just downloading a tarball. I would also suggest upgrading to the latest release 0.6.0.

**Comment by cli0** [comment]
Yes, you are right. It was a typo. I meant 0.4.1. Unfortunately I can't switch to 0.6.0 for this experiment.

I check the tf and git versions:

```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.12.0-0-ga6d8ffae09 1.12.0
```

they are not identical grammatically but they are both of the same branch. I also cloned the tf repo (didn't use tarballs) but I cloned the latest version and then switched to the 1.12.

```
$ git clone https://github.com/mozilla/tensorflow.git
$ cd tensorflow
$ git checkout origin/r1.12
```
Any idea how to bypass this?

**Comment by reuben** [comment]
Did you also clone DeepSpeech instead of downloading the 0.4.1 tarball?

**Comment by lissyx** [comment]
@cli0 Does the `ds_git_version.sh` script at least runs ? Are you sure you are not missing any dep ?

**Comment by cli0** [comment]
@reuben  @lissyx  I actually used a tarball to get DS 0.4.1. After cloning the DS repo as well I don't get this issue anymore. Bazel builds ok. Thank you for the help :)
