### ISSUE TITLE
Make sure all packages have proper links to GitHub/readthedocs/etc

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2590]
Done in #2585 for Python and JS, double check the rest.

 - [x] Pypi
 - [x] NPM
 - [x] NuGet
 - [x] Bintray

**Comment by lissyx** [comment]
Pypi seems to accept Markdown as well as reStructuredText, packaged in the deepspeech wheel.
NPM seems to accept only Markdown: https://docs.npmjs.com/about-package-readme-files, packaged in the deepspeech package.

**Comment by lissyx** [comment]
Bintray supports Markdown/asciiDoc/plaintext, but the README needs to be uploaded through the API with the package. We have code in scriptWorker to do it.

**Comment by lissyx** [comment]
NuGet will support embeded Markdown: https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg but so far, it seems not yet done, and I can't find anything to automatically upload that.

**Comment by lissyx** [comment]
> Bintray supports Markdown/asciiDoc/plaintext, but the README needs to be uploaded through the API with the package. We have code in scriptWorker to do it.

Fixed in https://github.com/mozilla/DeepSpeech/pull/2628, and upload of README.md was re-enabled on scriptworker side.

**Comment by lissyx** [comment]
> NuGet will support embeded Markdown: https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg but so far, it seems not yet done, and I can't find anything to automatically upload that.

I've got confirmation from nuget people there is nothing in place, so we can't upload through API. @reuben I think we could close this?

**Comment by reuben** [comment]
\o/
