### ISSUE TITLE
(request) ability to pass byte stream or file handle to CreateModel

### ISSUE THREAD

**Issue by bkkerrig** [mozilla/DeepSpeech#2595]
I am under the impression the only way to get DeepSpeech to load a model is to provide the file path to _[Model](https://github.com/mozilla/DeepSpeech/blob/3ea3a58f9299cbee8d8fd9c6837f64616f8b4d18/native_client/python/__init__.py#L26)_ in the native client. Could capability be added to load from other sources such as a byte stream or file handle? This would be helpful in instances where the model is being loaded from various cloud storage solutions; personally, I am using [S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html).

**Comment by lissyx** [comment]
> I am under the impression the only way to get DeepSpeech to load a model is to provide the file path to _[Model](https://github.com/mozilla/DeepSpeech/blob/3ea3a58f9299cbee8d8fd9c6837f64616f8b4d18/native_client/python/__init__.py#L26)_ in the native client. Could capability be added to load from other sources such as a byte stream or file handle? This would be helpful in instances where the model is being loaded from various cloud storage solutions; personally, I am using [S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html).

I don't think TensorFlow does allow this. Also, I'm not really sure to understand the usecase here with S3 buckets and local speech recognition.

**Comment by dabinat** [comment]
I can imagine you would have extreme latency if DeepSpeech has to wait for the network to return data every time it needs to read something. Also, this approach is only beneficial in cases where you only need to use a small portion of the file’s data. If you end up using all of the file’s data anyway, you experienced a whole lot of lag for nothing. The whole model needs to be loaded so there would be no benefit even if this worked.

So you’re probably better just downloading the file from S3 and passing in the file path to DeepSpeech. It’s also cheaper than having to receive the same data again and again from S3 for every inference job.

**Comment by bkkerrig** [comment]
For some context, I was exploring a use case where DeepSpeech would not be operating locally; instead multiple instances are to be running in a containerized fashion via Kubernetes or PCF. This way, real-time-transcriptions could be done concurrently. With that being said, the storage solution being explored to host the models (not the audio) was S3. [You don't access your stored resources via paths](https://dluo.me/s3databoto3).

@dabinat That's a good point. I will try what you suggested in the last paragraph.

**Comment by reuben** [comment]
@bernardohenz do you have any tips regarding how to do this?

**Comment by lissyx** [comment]
> a use case where DeepSpeech would not be operating locally; instead multiple instances are to be running in a containerized fashion via Kubernetes or PCF

Ok, I'm sorry I still don't get how in that context it makes it more efficient, but maybe because of my lack of propre knowledge of Kubernetes.



> This way, real-time-transcriptions could be done concurrently. With that being said, the storage solution being explored to host the models (not the audio) was S3. [You don't access your stored resources via paths](https://dluo.me/s3databoto3).

Sorry, but that feel completely orthogonal from my point of view

Also yeah, for performances reasons, as @dabinat noted, we load the model using `mmap()`. That's the reason why at TensorFlow level, I don't think we can address that usecase.

I think TensorFlow has some S3 ability, though, but:
 - that would make a specific, harder-to-test code-path
 - I'm not convinced of the impact, performance-wise, for the reasons exposed above
 - I'm far from being sure it would work with TFLite

@bkkerrig Are you working on deploying some server-side architecture for high-througoutput?

**Comment by bkkerrig** [comment]
I can close the issue since @dabinat suggestion worked fine (i.e download and then load from the file). 

I was trying to literally read the model directly from the S3 bucket; Since the file contents are provided as a byte stream, and not a file, there was no path. Having to download the model AND THEN load it from a file adds an extra step. I was concerned about network latency when spinning up new instances. After trying, it is not an issue.

@lissyx Yes, it is a server-side architecture for high-througoutput.

**Comment by lissyx** [comment]
> @lissyx Yes, it is a server-side architecture for high-througoutput.

Thanks, we are working on this as well
