### ISSUE TITLE
generate trie : Permission denied

### ISSUE THREAD

**Issue by stephanie20181997** [mozilla/DeepSpeech#2600]
I am trying to create my own language model , but i am stuck at generating the trie .
When i try to do it according to this link https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830 i get the error : Permission denied .
This is how i do it :  /home/stephanie/tmp/deepspeech-train-venv/DeepSpeech/native_client/generate_trie.cpp /home/stephanie/tmp/deepspeech-train-venv/DeepSpeech/native_client/alphabet.txt /home/stephanie/tmp/deepspeech-train-venv/DeepSpeech/native_client/lm.binary /home/stephanie/tmp/deepspeech-train-venv/DeepSpeech/native_client/trie

And i get this:
bash: /home/stephanie/tmp/deepspeech-train-venv/DeepSpeech/native_client/generate_trie.cpp: Permission denied

What can i do?

**Comment by lissyx** [comment]
This is not a bug. Please read the documentation and use pre-built generate_trie from release. What you are trying to do makes absolutely no sense.
