### ISSUE TITLE
raspbian-buster with 0.6.0: CreateModel failed with error code 12288

### ISSUE THREAD

**Issue by timaschew** [mozilla/DeepSpeech#2601]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: raspbian-buster
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: via pip
- **TensorFlow version (use command below)**: v1.14.0-21-ge77504a
- **Python version**: Python 3.7.3
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
- **CUDA/cuDNN version**: - 
- **GPU model and memory**: -
- **Exact command to reproduce**:

Fresh raspbian-buster on a Raspberry Pi 3 Model B Plus Rev 1.3

Steps from [README.md](https://github.com/mozilla/DeepSpeech/blob/551b3dd5f5c36f49af9dc562c69e78d705daee18/README.rst)

After I got an error regarding which was thrown by numpy (`ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory`) I've installed an additional package via `apt install libatlas-base-dev`.

Now I'm getting this error:

```
$ deepspeech --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie --audio audio/2830-3980-0043.wav
Loading model from file deepspeech-0.6.0-models/output_graph.pbmm
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.0-0-g6d43e21
ERROR: Model provided has model identifier '='+;', should be 'TFL3'

Error at reading model file deepspeech-0.6.0-models/output_graph.pbmm
Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/bin/deepspeech", line 8, in <module>
    sys.exit(main())
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/client.py", line 113, in main
    ds = Model(args.model, args.beam_width)
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/__init__.py", line 42, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 12288
```

Same commands on my macos are working fine.

**Comment by lissyx** [comment]
> Fresh raspbian-buster on a Raspberry Pi 3 Model B Plus Rev 1.3

As noted, please don't expect real time on this device.



> After I got an error regarding which was thrown by numpy (`ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory`) I've installed an additional package via `apt install libatlas-base-dev`.

Yes, I'm sure we have that documented somewhere. Don't hesitate to send a PR to improve documentation if you have opinions on how to make it better.



> Same commands on my macos are working fine.

As documented, RPi3/4 binaries are using the TensorFlow Lite runtime, so you need to pass `output_graph.tflite` and not `output_graph.pbmm`.

Since this is not a bug, I'll close. Feel free to discuss in Disource.
