### ISSUE TITLE
deepspeech 0.6 custome training error

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [mozilla/DeepSpeech#2603]
@lissyx 

While using deepspeech-0.6 custome training while changing an augmentation argument i'm facing an error. There is no checkpoint is mentioned.

    # Data Augmentation
    # ================

    f.DEFINE_float('data_aug_features_additive', 0, 'std of the Gaussian additive noise')
    f.DEFINE_float('data_aug_features_multiplicative', 0, 'std of normal distribution around 1 for multiplicative noise')

    f.DEFINE_float('augmentation_spec_dropout_keeprate', 1, 'keep rate of dropout augmentation on spectrogram (if 1, no dropout will be performed on spectrogram)')

    f.DEFINE_boolean('augmentation_freq_and_time_masking', True, 'whether to use frequency and time masking augmentation')
    f.DEFINE_integer('augmentation_freq_and_time_masking_freq_mask_range', 5, 'max range of masks in the frequency domain when performing freqtime-mask augmentation')
    f.DEFINE_integer('augmentation_freq_and_time_masking_number_freq_masks', 3, 'number of masks in the frequency domain when performing freqtime-mask augmentation')
    f.DEFINE_integer('augmentation_freq_and_time_masking_time_mask_range', 2, 'max range of masks in the time domain when performing freqtime-mask augmentation')
    f.DEFINE_integer('augmentation_freq_and_time_masking_number_time_masks', 3, 'number of masks in the time domain when performing freqtime-mask augmentation')

    f.DEFINE_float('augmentation_speed_up_std', 1, 'std for speeding-up tempo. If std is 0, this augmentation is not performed')

    f.DEFINE_boolean('augmentation_pitch_and_tempo_scaling', True, 'whether to use spectrogram speed and tempo scaling')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_min_pitch', 0.95, 'min value of pitch scaling')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_max_pitch', 1.2, 'max value of pitch scaling')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_max_tempo', 1.2, 'max vlaue of tempo scaling')
-----------------------------------------------------------------------------------------------------------------------------------------------------------
**Error:**
```
Use tf.where in 2.0, which has the same broadcast rule as np.where
I Initializing variables...
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                          Traceback (most recent call last):
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= -3
	 [[{{node random_uniform_3}}]]
	 [[tower_0/IteratorGetNext]]
  (1) Invalid argument: Need minval < maxval, got 0 >= -3
	 [[{{node random_uniform_3}}]]
	 [[tower_0/IteratorGetNext]]
	 [[Mean_8/_85]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 969, in <module>
    absl.app.run(main)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 942, in main
    train()
  File "DeepSpeech.py", line 635, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "DeepSpeech.py", line 603, in run_set
    feed_dict=feed_dict)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= -3
	 [[{{node random_uniform_3}}]]
	 [[tower_0/IteratorGetNext]]
  (1) Invalid argument: Need minval < maxval, got 0 >= -3
	 [[{{node random_uniform_3}}]]
	 [[tower_0/IteratorGetNext]]
	 [[Mean_8/_85]]
0 successful operations.
0 derived errors ignored.
```

**Comment by lissyx** [comment]
>  changing an augmentation argument

Which one ? There's nothing to help us reproduce here, I don't see how we can help you.

**Comment by NarasimmanSaravana1994** [comment]
@lissyx 

While training a model from scratch without using checkpoint with default argument it's working fine, the epoch is running.

Refer to the below-mentioned command for training.

'python3.7 DeepSpeech.py \
			--lm_binary_path ./data/lm/lm.binary \
			--lm_trie_path ./data/lm/trie \
			--learning_rate 0.0001 \
			--train_batch_size 1 \
			--alphabet_config_path ./data/alphabet_old.txt \
			--remove_export true \
			--train_files ./data/testing_data/16_12_19_only_wav.csv \
			--export_dir ./export  \
			--checkpoint_dir ./scratch_checkpoint \
			--epochs 10')

After changing the augmentation for **augmentation_pitch_and_tempo_scaling** to True I'm facing the issue.

While I trace the error in **spectrogram_augmentations.py**  **augment_pitch_and_tempo** funtion i'm facing **resize bilinear** 

Exactly  **spectrogram_aug = tf.image.resize_bilinear(tf.expand_dims(spectrogram, -1), [new_height, new_width])**  this line while calculating the new_hight and new_width while I think -(minus) value comming but how it is comming and unable to get the calculation value i don't know beacause it's comming tensor value.

Please assist in how to solve this issue.  Please refer the above loop conversation for augmentation arguments.

**My end goal I want to do augmentation for my dataset.**

Thanks...

**Comment by lissyx** [comment]
> Please assist in how to solve this issue. Please refer the above loop conversation for augmentation arguments.

You obviously know more about the problem than I do. Data augmentation were contributed, and I was not the one reviewing. I won't be able to help you quickly ...

**Comment by lissyx** [comment]
> 			--train_batch_size 1 \

Have you tried a bigger batch size ?

**Comment by NarasimmanSaravana1994** [comment]
> > Please assist in how to solve this issue. Please refer the above loop conversation for augmentation arguments.
> 
> You obviously know more about the problem than I do. Data augmentation were contributed, and I was not the one reviewing. I won't be able to help you quickly ...

@lissyx who can give a solution for this problem.

**Comment by NarasimmanSaravana1994** [comment]
> > ```
> >   	--train_batch_size 1 \
> > ```
> 
> Have you tried a bigger batch size ?

Yes I tried batch size 32,16 finally I tried 1 same issue coming for me

**Comment by lissyx** [comment]
> 			--train_files ./data/testing_data/16_12_19_only_wav.csv \

Can you isolate some files that reproduces the issue ?

**Comment by NarasimmanSaravana1994** [comment]
@lissyx  yes I tried it's not working.

**Comment by lissyx** [comment]
> @lissyx yes I tried it's not working.

What is not working ?

**Comment by NarasimmanSaravana1994** [comment]
> not

Sorry wrongly send the text..
I attached the sample wav please refer that even single file also not working for me.
[1.wav.zip](https://github.com/mozilla/DeepSpeech/files/3988248/1.wav.zip)

**Comment by lissyx** [comment]
> > not
> 
> Sorry wrongly send the text..
> I attached the sample wav please refer that even single file also not working for me.
> [1.wav.zip](https://github.com/mozilla/DeepSpeech/files/3988248/1.wav.zip)

Can you verify with the LDC93S1 sample we have ?

**Comment by lissyx** [comment]
@bernardohenz Do you have any idea of the reason for that behavior ?

**Comment by mychiux413** [comment]
@NarasimmanSaravana1994,
Because the augment functions consider the shape of spectrogram as `reversed` shape (#2560), 
The DeepSpeech spectrogram shape is [1, Time, Frequency, 1],
but `spectrogram_augmentations.py` considers the spectrogram's shape as [1, Frequency, Time, 1], 
since it's developed under `librosa`'s spectrogram, the shape is the opposite of DeepSpeech's.

So, It cause `augment_freq_time_mask()` consider your `short audio`'s time steps size as frequency size,
look the code `line 13` in `spectrogram_augmentations.py`:
```
  # the freq_max is `time_max` now, so the 'maxval' for short audio could be negative
  f0 = tf.random.uniform(shape=(), minval=0, maxval=freq_max - f, dtype=tf.dtypes.int32)
```

You can try my fork, I change the shape back.
```
git clone -b 'develop' --single-branch --depth 1 https://github.com/mychiux413/DeepSpeech.git
```
try training with the same arguments, it should not get error again, but here is another error you might encounter then, after the `short audio` augmented, the `time steps` could be shorter than original one (due to `--augmentation_pitch_and_tempo_scaling_max_tempo`), so you might encountered `[ctc loss error] longer outputs than inputs`, which could not be checked before training (the spec shape is randomly determined), or you could re-estimate the `valid audio length` with the coefficient: `--augmentation_pitch_and_tempo_scaling_max_tempo`.

In my fork, I just add  argument `--ctc_loss_ignore_longer_outputs_than_inputs True` to ignore this error, because the invalid spec is very rare to be generated (`short audio` + `big choosen_tempo`), I don't think it will have much impact on my model

**Comment by vigneshgig** [comment]
Hi 

> @NarasimmanSaravana1994,
> Because the augment functions consider the shape of spectrogram as `reversed` shape (#2560),
> The DeepSpeech spectrogram shape is [1, Time, Frequency, 1],
> but `spectrogram_augmentations.py` considers the spectrogram's shape as [1, Frequency, Time, 1],
> since it's developed under `librosa`'s spectrogram, the shape is the opposite of DeepSpeech's.
> 
> So, It cause `augment_freq_time_mask()` consider your `short audio`'s time steps size as frequency size,
> look the code `line 13` in `spectrogram_augmentations.py`:
> 
> ```
>   # the freq_max is `time_max` now, so the 'maxval' for short audio could be negative
>   f0 = tf.random.uniform(shape=(), minval=0, maxval=freq_max - f, dtype=tf.dtypes.int32)
> ```
> 
> You can try my fork, I change the shape back.
> 
> ```
> git clone -b 'develop' --single-branch --depth 1 https://github.com/mychiux413/DeepSpeech.git
> ```
> 
> try training with the same arguments, it should not get error again, but here is another error you might encounter then, after the `short audio` augmented, the `time steps` could be shorter than original one (due to `--augmentation_pitch_and_tempo_scaling_max_tempo`), so you might encountered `[ctc loss error] longer outputs than inputs`, which could not be checked before training (the spec shape is randomly determined), or you could re-estimate the `valid audio length` with the coefficient: `--augmentation_pitch_and_tempo_scaling_max_tempo`.
> 
> In my fork, I just add argument `--ctc_loss_ignore_longer_outputs_than_inputs True` to ignore this error, because the invalid spec is very rare to be generated (`short audio` + `big choosen_tempo`), I don't think it will have much impact on my model
Hi I also encountered the same issue using above solution i able to solve it some what like if I use for default values in augmentation for pitch and tempo I  got the same error. but If I changed the pitch and tempo value the model running fine.Can you tell me the explanation for the augmentation parameter so i can change it according to my dataset.
case 1:
error for default augmentation parameter.
f.DEFINE_float('augmentation_speed_up_std', 1, 'std for speeding-up tempo. If std is 0, this augmentation is not performed')
    f.DEFINE_float('augmentation_speed_up_prob', 0.2, 'speed up prob')

 # f.DEFINE_float('augmentation_pitch_and_tempo_scaling_prob', 0.5, 'pitch and tempo prob')
    # f.DEFINE_float('augmentation_pitch_and_tempo_scaling_min_pitch', 0.95, 'min value of pitch scaling')
    # f.DEFINE_float('augmentation_pitch_and_tempo_scaling_max_pitch', 1.2, 'max value of pitch scaling')
    # f.DEFINE_float('augmentation_pitch_and_tempo_scaling_max_tempo', 1.2, 'max vlaue of tempo scaling')

case no error:
f.DEFINE_float('augmentation_speed_up_std', 1, 'std for speeding-up tempo. If std is 0, this augmentation is not performed')
    f.DEFINE_float('augmentation_speed_up_prob', 0.2, 'speed up prob')

    f.DEFINE_boolean('augmentation_pitch_and_tempo_scaling', True, 'whether to use spectrogram speed and tempo scaling')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_prob', 0.1, 'pitch and tempo prob')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_min_pitch', 0.85, 'min value of pitch scaling')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_max_pitch', 1.2, 'max value of pitch scaling')
    f.DEFINE_float('augmentation_pitch_and_tempo_scaling_max_tempo', 1.2, 'max vlaue of tempo scaling')
Thanks

**Comment by vigneshgig** [comment]
# the freq_max is `time_max` now, so the 'maxval' for short audio could be negative
one more question so for above mentioned line I can't use augmentation for short audio .if so how can i skip short audio for augmentation.
Thanks

**Comment by mychiux413** [comment]
Hi @vigneshgig ,
The `--augmentation_sparse_warp` in my fork is still unstable, if `--augmentation_sparse_warp_time_warping_para` is too large, you might have change to get `matrix invertible error` on short audio, I haven't figured out the solution.
My personal short-term solution is to filter the `audio duration > 0.5s`, and set `--augmentation_sparse_warp_time_warping_para=12` or less, which helps my training process go through 8 million rows data and 15 epochs now, but I'm still monitoring it, so I can't guarantee it won't crash even with this parameters after many epochs.

> Is augmentation depends on other augmentation. can anyone give me a explanation for this behaviour.

Sorry for that, you shouldn't try other augmentations in my fork, it's not an official way to augment data, maybe it's inappropriate for discussion here, I just wanted to demonstrate how short audio got error, and fix freq_and_time_masking can help @NarasimmanSaravana1994 prevent this error.

**Comment by vigneshgig** [comment]
Thanks for the reply,@mychiux413
can you explain what is  augmentation_sparse_warp . is there any paper link.

Thanks

**Comment by vigneshgig** [comment]
I also got this error:

command:'python3.7 DeepSpeech.py \
			--lm_binary_path ./data/lm/lm.binary \
			--lm_trie_path ./data/lm/trie \
			--learning_rate 0.0001 \
			--train_batch_size 3 \
			--alphabet_config_path ./data/alphabet.txt \
			--remove_export true \
			--train_files ./data/testing_data/only_wav_new_6_12_2019.csv \
			--export_dir ./export  \
			--checkpoint_dir ./ \
			--epochs 10
                        --augmentation_pitch_and_tempo_scaling true
                        --augmentation_speed_up_std 1'

Epoch 0 |   Training | Elapsed Time: 0:00:02 | Steps: 3 | Loss: 91.659166                                                                     Traceback (most recent call last):
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: output dimensions must be positive
	 [[{{node cond_1/else/_9/ResizeBilinear}}]]
	 [[tower_0/IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1083, in <module>
    absl.app.run(main)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 1006, in main
    train()
  File "DeepSpeech.py", line 634, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "DeepSpeech.py", line 602, in run_set
    feed_dict=feed_dict)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/administrator/deepspeech_0.6.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: output dimensions must be positive
	 [[{{node cond_1/else/_9/ResizeBilinear}}]]
	 [[tower_0/IteratorGetNext]]

if I turn off all the augmentation it running perflectly.
error is not only for  0.6.1a also  this error get for 0.6.0.
Thanks

**Comment by mychiux413** [comment]
sparse_warp and freq_and_time_masking are come from [arxiv-SpecAugment](https://arxiv.org/pdf/1904.08779.pdf)
sparse_warp is a method to distort spectrogram like distort a picture to get different data in training steps.

the `augmentation_speed_up_std=1` is very huge value, the speed up value was chosen by normal distribution value, `augmentation_speed_up_std=1` means 31% audio files are more than double speed up as training data, This is totally far away from the voice of the real world.

`--augmentation_pitch_and_tempo_scaling`, `--augmentation_speed_up_std` they both have `resize_bilinear()` function inside, you can try disabling another one to figure out which one is the source of problem.

**Comment by vigneshgig** [comment]
It's my bad In my dataset somehow empty audio is add. Now its working fine and  also I got the intuition of augmentation.  Thanks  a lot @lissyx @mychiux413.

**Comment by lissyx** [comment]
> It's my bad In my dataset somehow empty audio is add. Now its working fine and also I got the intuition of augmentation. Thanks a lot @lissyx @mychiux413.

Can we close or is there anything that can be improved to make it easier for others in similar situations?
