### ISSUE TITLE
Ilegal instruction with native client on a N4200

### ISSUE THREAD

**Issue by sheosi** [mozilla/DeepSpeech#2604]
Hello, I've trying to use the native client (through deepspeech-rs, for Rust) and despite everything seemingly okay when I try the example in there, I get a SIGILL (Illegal instruction). I post the issue here since I assume it's related to my laptop lacking AVX.

CPU: Quad Core Intel Pentium N4200 
OS: Linux
Distro: Solus OS 4

**Comment by lissyx** [comment]
> I post the issue here since I assume it's related to my laptop lacking AVX.

This is right, and not a bug. Please use Discourse for support. Your only solution is to rebuild `libdeepspeech.so` without AVX support.
