### ISSUE TITLE
Windows 10 might require "Redistribuable Visual C++ 2015 Update 3" for runtime (NodeJS)

### ISSUE THREAD

**Issue by slaypni** [mozilla/DeepSpeech#2606]
- OS Platform and Distribution: Windows 10 (64bit)
- DeepSpeech package: deepspeech (npm)
- DeepSpeech version: 0.6.0
- Node version: 13.0.1
- Sample code: https://gist.github.com/slaypni/695df46d55fcae159105d99fe96b99d8
- Exact command to reproduce: `yarn; node main.js`

It seems using deepspeech node client fails on Windows. An error is produced as follows when trying to run:

```
> node main.js
internal/modules/cjs/loader.js:1041
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Kazuaki\Desktop\devel\ds\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64\node-v79\deepspeech.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1041:18)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Kazuaki\Desktop\devel\ds\node_modules\deepspeech\index.js:17:17)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
```

The same code runs without errors on macOS.

**Comment by lissyx** [comment]
That's weird, we have tests coverage on Windows, and NodeJS v13.0.1.

**Comment by lissyx** [comment]
> Error: A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\Kazuaki\Desktop\devel\ds\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64\node-v79\deepspeech.node

I don't know well enough Windows, but `deepspeech.node` should load `libdeepspeech.so`. Somehow, it is failing :/

**Comment by lissyx** [comment]
Looks like I reproduce that on a Windows 10 VM :'(

**Comment by lissyx** [comment]
@slaypni It looks like you need "Redistribuable Visual C++ 2015 Update 3 (64 bits)" to be installed. Can you try from this link ?

https://www.microsoft.com/fr-fr/download/details.aspx?id=53840
Only select the `vc_redist.x64.exe` package. It was enough to get `deepspeech --version` for me. I'm not sure how we should handle that, I don't know well enough Windows' world.

**Comment by lissyx** [comment]
@kdavis-mozilla @reuben I'll need your opinion whether we just update the doc, or whether we should package the libs with ours.

**Comment by lissyx** [comment]
Oh and @carlfm01 might also have opinions here :)

**Comment by slaypni** [comment]
@lissyx Thank you for finding a solution. I installed the specified version of `vc_redist.x64.exe` and tried to run deepspeech, however, the same error occured again.

**Comment by lissyx** [comment]
> @lissyx Thank you for finding a solution. I installed the specified version of `vc_redist.x64.exe` and tried to run deepspeech, however, the same error occured again.

That's weird, I verified several times with install / uninstall of it, and I would constantly reproduce / fix the issue. That should not be needed, but have you restarted between tests ? It could be possible that the path is not yet updated.

At that point, maybe you lack some other dep, but it seems like Windows is a bit a moving target, this is not something we had to do before.

@slaypni What's your exact Windows version ? Maybe you need other versions of `vc_redist.x64.exe` as well ?

**Comment by lissyx** [comment]
@slaypni Checking with `Dependency Walker`, reading `libdeepspeech.so` with it, I can confirm:
 - `msvcp140.dll`
 - `vcruntime140.dll`
Are the only ones missing after uninstalling the redistribuable package. Please check on your side as well ?

**Comment by slaypni** [comment]
@lissyx I confirmed all DLLs used from `libdeepspeech.so` exist by using [Dependencies](https://github.com/lucasg/Dependencies). (Dependency Walker seems not working on my Windows.) Although it also shows `deepspeech.node` has one missing module `libdeepspeech.so`, I am not sure if it is a problem.

Exact version of my Windows is as follows:
- Edition: Windows 10 Pro
- Version: 1909
- Installed Date: 2019/12/08
- OS Build: 18363.476

**Comment by lissyx** [comment]
> Although it also shows `deepspeech.node` has one missing module `libdeepspeech.so`, I am not sure if it is a problem.

Check `index.js` we are supposed to force `PATH` to ensure that `libdeepspeech.so` is properly found. It's possible you need to add the path containing it to Dependencies' config.

**Comment by lissyx** [comment]
@slaypni I don't know how to further debug missing DLLs on Windows.

**Comment by slaypni** [comment]
@lissyx Configuring Dependencies' search path enabled to find `libdeepspeech.so` as you said. Currently I am copying `libdeepspeech.so` on the current directly (and also a directly under PATH), therefore it should be found on runtime, however, it fails to run. I am wondering if the error is really caused by missing DLLs.

**Comment by lissyx** [comment]
> @lissyx Configuring Dependencies' search path enabled to find `libdeepspeech.so` as you said. Currently I am copying `libdeepspeech.so` on the current directly (and also a directly under PATH), therefore it should be found on runtime, however, it fails to run. I am wondering if the error is really caused by missing DLLs.

Are you sure that your Node process has the same `PATH` ? There should be no need to move the library, please avoid this as it's going to make debugging even more difficult.

**Comment by lissyx** [comment]
> I confirmed all DLLs used from `libdeepspeech.so` exist by using [Dependencies](https://github.com/lucasg/Dependencies). (Dependency Walker seems not working on my Windows.)

Please re-verify everything. I just checked with this tools, and it indeeds finds the missing redistribuable libs from its own directory. Obviously, not a directory that is known by Node process.

@slaypni On the installed module, can you hack into `deepspeech/index.js` and add some `console.log` statement to know about `process.env['PATH']` before and after we compute it ?

**Comment by carlfm01** [comment]
Hello,

Just tested and it is working for me, the thing is that I have literally all the redistributable versions installed, at the moment I can't remove then to confirm.  
What comes to my mind for now to mitigate the unknown source of the issue is to check that the redistributable is installed by using the regedit key:

something like:

```
var regedit = require('regedit')

regedit.list('HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\14.0\\VC\\Runtimes\\x64', function(err, result) {
     console.log(result['HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\14.0\\VC\\Runtimes\\x64'].values['Version'])
})
```

We need to check from 10.0 to 15.9 and see if at least one is installed(instead of only 14.0)

If the Runtime is the source of the issue I think checking the installed version and adding the requirement to the docs should be fine.

**Comment by slaypni** [comment]
@lissyx Thank you for suggesting actions.

> Please re-verify everything. I just checked with this tools, and it indeeds finds the missing redistribuable libs from its own directory. Obviously, not a directory that is known by Node process.

`Dependencies` shows all DLLs linked from `libdeepspeech.so` are located under `C:\WINDOWS\system32\`.

> On the installed module, can you hack into deepspeech/index.js and add some console.log statement to know about process.env['PATH'] before and after we compute it ?

I printed `oldPath` and `process.env['PATH']` just before `require(binding_path)` where an error occurs.

- `oldPath`: `C:\Python37\Scripts\;C:\Python37\;...`
- `process.env['PATH']`: `C:\Users\Kazuaki\Desktop\devel\ds\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64;C:\Python37\Scripts\;C:\Python37\;...`

It looks PATH is properly set. (`...` is just for truncation.)

**Comment by lissyx** [comment]
@slaypni Then I'm sorry, I don't know how to debug that further. Out of luck, can you try latest NodeJS v13? This is what I was using (13.3.1 I think ?). Have you ran `Dependencies` against `deepspeech.node` to check if it depends on anything else than `libdeepspeech.so` ?

**Comment by lissyx** [comment]
> If the Runtime is the source of the issue I think checking the installed version and adding the requirement to the docs should be fine.

It's likely this is hitting not just node users, if it is `libdeepspeech.so` that is linked against those runtime. I'm not a big fan of doing those checks in the library (and actually, I dont think we can since the linker will not load us).

@carlfm01 Should we instead package those two deps along with our runtime ? And if so, where should we source those library ? From the builders ?

**Comment by lissyx** [comment]
> `process.env['PATH']`: `C:\Users\Kazuaki\Desktop\devel\ds\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64;C:\Python37\Scripts\;C:\Python37\;...`

Just to be 100% sure, you do have `C:\Users\Kazuaki\Desktop\devel\ds\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64\libdeepspeech.so` and it is readable by your user, right ?

**Comment by slaypni** [comment]
@lissyx I upgraded NodeJS to the latest one (13.5.0), confirmed `libdeepspeech.so` exists on the certain path and it is readable, however, loading `deepspeech` still produces the same error. I understand it is hard to investigate the problem more unless reproducing the same error on your environment. I'll see if I can find solutions.

**Comment by lissyx** [comment]
> @lissyx I upgraded NodeJS to the latest one (13.5.0), confirmed `libdeepspeech.so` exists on the certain path and it is readable, however, loading `deepspeech` still produces the same error. I understand it is hard to investigate the problem further unless reproducing the same error on your environment. I'll see if I can find solutions.

What about analyzing `deepspeech.node` as well with `Dependencies` ?

**Comment by lissyx** [comment]
@slaypni It might be good if you could also give a try to the C++ native client, this might help excluding hypothesis.

**Comment by carlfm01** [comment]
> It's likely this is hitting not just node users, if it is `libdeepspeech.so`

Initially, I thought it was about the node linking, I see the issue now and my suggestion makes no sense.

> Should we instead package those two deps along with our runtime

I don't think is the ideal, let's first confirm the issue with the .so .

**Comment by carlfm01** [comment]
I'm afraid I can't help here, currently, I don't have a clean VM to deploy and debug. Tried locally but can't replicate, I've removed all the redistributables and I still see the dependency .dll's. Everything still works :/

@slaypni can you try with https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk installed?

**Comment by slaypni** [comment]
@lissyx I paste a screenshot of Dependencies against `deepspeech.node`. Are there examples to use the native C++ client?
@carlfm01 It seems I have already installed the SDK since Visual Studio is installed on the machine.

![Dependencies screenshot](https://user-images.githubusercontent.com/1160392/71320422-6eec0780-24ee-11ea-9e9d-2939be517b7a.png)

**Comment by lissyx** [comment]
> Are there examples to use the native C++ client?

Yes, please have a look at the documentation.

**Comment by lissyx** [comment]
> I paste a screenshot of Dependencies against `deepspeech.node`

What are those strange characters that are used as path separator in the status bar at the bottom ? We should see `\` and not those.

Are you using a specific locale ? How are you running node ? From a terminal ? What's your shell ?

**Comment by slaypni** [comment]
> Are there examples to use the native C++ client?

Alright, I will see it.

> What are those strange characters that are used as path separator in the status bar at the bottom ? We should see \ and not those.

The character &yen; appears in place of \ when setting Japanese on Windows. I understand it is just a matter of font.

> Are you using a specific locale ? How are you running node ? From a terminal ? What's your shell ?

It is Japanese locale. I run node from Powershell and Command prompt.

**Comment by lissyx** [comment]
> It is Japanese locale. I run node from Powershell and Command prompt.

It would not be completely impossible this is triggering a bug. It'd be awesome if you could check that:
 - try under msys2 64-bits, with `LC_ALL=C`
 - try under Powershell with C locale (I don't know how to do that)

**Comment by slaypni** [comment]
I tried to run node from Powershell and MSYS on Windows Sandbox where NodeJS and `Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215` were additionally installed, however, they seem to fail with the same error. The region was set to US and language was set to English (US).

```shell
WDAGUtilityAccount@90e34f2c-3b35-4963-99e1-91053d1b3331 MSYS ~
# export LC_ALL=C

WDAGUtilityAccount@90e34f2c-3b35-4963-99e1-91053d1b3331 MSYS ~
# "/c/Program Files/nodejs/npx" deepspeech -v
npx: installed 81 in 12.922s
A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\WDAGUtilityAccount\AppData\Roaming\npm-cache\_npx\3084\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64\node-v79\deepspeech.node
```

**Comment by lissyx** [comment]
> I tried to run node from Powershell and MSYS on Windows Sandbox where NodeJS and `Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215` were additionally installed, however, they seem to fail with the same error. The region was set to US and language was set to English (US).
> 
> ```shell
> WDAGUtilityAccount@90e34f2c-3b35-4963-99e1-91053d1b3331 MSYS ~
> # export LC_ALL=C
> 
> WDAGUtilityAccount@90e34f2c-3b35-4963-99e1-91053d1b3331 MSYS ~
> # "/c/Program Files/nodejs/npx" deepspeech -v
> npx: installed 81 in 12.922s
> A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\WDAGUtilityAccount\AppData\Roaming\npm-cache\_npx\3084\node_modules\deepspeech\lib\binding\v0.6.0\win32-x64\node-v79\deepspeech.node
> ```

I'm really unable to help more here. @carlfm01 Do you know how we can get more informations from the Windows linker ? Under linux I would `LD_DEBUG=all` and we might know more. I'm surprised we don't have similar tooling for this platform (all I could search would not be helping).

**Comment by carlfm01** [comment]
> @carlfm01 Do you know how we can get more informations from the Windows linker ?

No, sorry.

>  It might be good if you could also give a try to the C++ native client, this might help excluding hypothesis.

@slaypni please try running the native client and update us.

**Comment by lissyx** [comment]
> > Should we instead package those two deps along with our runtime
> 
> I don't think is the ideal, let's first confirm the issue with the .so .

How does other solves this ? I've seen other floss project shipping those libs as well.

**Comment by carlfm01** [comment]
> How does other solves this ? I've seen other floss project shipping those libs as well.

Hello @lissyx Sorry for the delay, digging more I found someone mentioned `/MT` to link statically against dependencies at the cost of increasing the size of the native so, using `--copt="/MT"` compiles for me, I'm now testing to see if it still works. 
I'll need your help to confirm that this removes the dependency requirement.


https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019

**Comment by carlfm01** [comment]
I confirm it still works at least with .NET client (can't test with every single client), using the dependency walker shows that `msvcp140.dll` is gone, it still shows `vcruntime140.dll` :/ only your tests @lissyx or @slaypni will tell if this removes the dependency

**Comment by lissyx** [comment]
> > How does other solves this ? I've seen other floss project shipping those libs as well.
> 
> Hello @lissyx Sorry for the delay, digging more I found someone mentioned `/MT` to link statically against dependencies at the cost of increasing the size of the native so, using `--copt="/MT"` compiles for me, I'm now testing to see if it still works.
> I'll need your help to confirm that this removes the dependency requirement.
> 
> https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019

Your link seems to suggest `MD` and not `MT`. Also, `/MT` badly fails, we need to rebuild **everything** with it, it seems :/

**Comment by carlfm01** [comment]
> Your link seems to suggest `MD` and not `MT`.

I just read again the link and for MD says **The actual working code is contained in MSVCRversionnumber.DLL, which must be available at run time**

Also MT vs MD on StackOverflow :https://stackoverflow.com/questions/757418/should-i-compile-with-md-or-mt



> we need to rebuild **everything** with it, it seems :/

:/

**Comment by lissyx** [comment]
> > Your link seems to suggest `MD` and not `MT`.
> 
> I just read again the link and for MD says **The actual working code is contained in MSVCRversionnumber.DLL, which must be available at run time**
> 
> Also MT vs MD on StackOverflow :https://stackoverflow.com/questions/757418/should-i-compile-with-md-or-mt
> 
> > we need to rebuild **everything** with it, it seems :/
> 
> :/

Ouch, misread msvcp for msvcr :/
