### ISSUE TITLE
CRLF in alphabet file breaks usage

### ISSUE THREAD

**Issue by JinZhuXing** [mozilla/DeepSpeech#2611]
```
python ./DeepSpeech.py --train_files ../zh-cn/clips/train.csv --dev_files ../zh-cn/clips/dev.csv --test_files ../zh-cn/clips/test.csv

Traceback (most recent call last):
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/text.py", line 33, in _label_from_string
    return self._str_to_label[string]
KeyError: '母'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/text.py", line 130, in text_to_char_array
    transcript = np.asarray(alphabet.encode(series['transcript']))
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/text.py", line 47, in encode
    res.append(self._label_from_string(char))
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/text.py", line 39, in _label_from_string
    ).with_traceback(e.__traceback__)
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/text.py", line 33, in _label_from_string
    return self._str_to_label[string]
KeyError: "ERROR: Your transcripts contain characters (e.g. '母') which do not occur in data/alphabet.txt! Use util/check_characters.py to see what characters are in your [train,dev,test].csv transcripts, and then add all these to data/alphabet.txt."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./DeepSpeech.py", line 965, in <module>
    absl.app.run(main)
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./DeepSpeech.py", line 938, in main
    train()
  File "./DeepSpeech.py", line 438, in train
    train_phase=True)
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/feeding.py", line 101, in create_dataset
    df['transcript'] = df.apply(text_to_char_array, alphabet=Config.alphabet, result_type='reduce', axis=1)
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/pandas/core/frame.py", line 6928, in apply           return op.get_result()
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result       return self.apply_standard()
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/home/kms/anaconda3/envs/speechenv/lib/python3.6/site-packages/pandas/core/apply.py", line 112, in f
    return func(x, *args, **kwds)
  File "/mnt/d/FPProject_git/My_Work/speech/mozilla/DeepSpeech/util/text.py", line 136, in text_to_char_array
    raise ValueError('While processing: {}\n{}'.format(series['wav_filename'], e))
ValueError: ('While processing: /mnt/d/FPProject_git/My_Work/speech/mozilla/zh-cn/clips/common_voice_zh-CN_18782225.wav\n"ERROR: Your transcripts contain characters (e.g. \'母\') which do not occur in data/alphabet.txt! Use util/check_characters.py to see what characters are in your [train,dev,test].csv transcripts, and then add all these to data/alphabet.txt."', 'occurred at index 550')
```

I am training deep speech model in chinese.
I have already downloaded chiense dataset from voice.mozilla.org (Common Voice).
Then, I tried training as the description in Project Document(https://github.com/mozilla/DeepSpeech/blob/master/TRAINING.rst#training-your-own-model).
But when I train data using DeepSpeech.py, it failed with above errors.
data/alphabet.txt already contains '母'.
I can't find reason.
Please help me.

**Comment by lissyx** [comment]
>  data/alphabet.txt already contains '母'.

Well, the code cannot find it. Can you make sure you don't mix different unicode characters that looks alike ?

How did you generate `data/alphabet.txt` ? Did you used `util/check_characters.py` as suggested ?

**Comment by JinZhuXing** [comment]
> > data/alphabet.txt already contains '母'.
> 
> Well, the code cannot find it. Can you make sure you don't mix different unicode characters that looks alike ?
> 
> How did you generate `data/alphabet.txt` ? Did you used `util/check_characters.py` as suggested ?

Yes. I have generated data/alphabet.txt file using util/check_characters.py.

**Comment by lissyx** [comment]
> > > data/alphabet.txt already contains '母'.
> > 
> > 
> > Well, the code cannot find it. Can you make sure you don't mix different unicode characters that looks alike ?
> > How did you generate `data/alphabet.txt` ? Did you used `util/check_characters.py` as suggested ?
> 
> Yes. I have generated data/alphabet.txt file using util/check_characters.py.

Well, I can't help more without more data. But you have an unmatched character in your dataset, for sure.

Maybe you could share more of you data ? The offending transcript as well as the alphabet file ?

**Comment by lissyx** [comment]
@JinZhuXing Also, can you verify if the offending character is a unicode multi-byte character?

**Comment by reuben** [comment]
Every Chinese character is multibyte in UTF-8.

**Comment by lissyx** [comment]
> Every Chinese character is multibyte in UTF-8.
> […](#)
> On 19 Dec 2019, at 10:25, lissyx ***@***.***> wrote: ﻿ @JinZhuXing Also, can you verify if the offending character is a unicode multi-byte character? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Not multi-byte then, but was it multi-point ?

**Comment by lissyx** [comment]
@JinZhuXing I also see you are using Anaconda. We're got weird behaviors sometimes, can you reproduce with vanilla Python and a new virtualenv properly setup from scratch ?

**Comment by JinZhuXing** [comment]
OK, I will test with vanilla Python.
Thanks, all of you.

**Comment by lissyx** [comment]
> OK, I will test with vanilla Python.
> Thanks, all of you.

@JinZhuXing Any update ?

**Comment by lissyx** [comment]
@JinZhuXing Please, can you give feedback ?

**Comment by JinZhuXing** [comment]
It's the same. I can't do it.
So I will try with english dataset.
Thanks.

**Comment by JinZhuXing** [comment]
> @JinZhuXing Please, can you give feedback ?

It's the same. I can't do it.
So I will try with english dataset.
Thanks.

**Comment by kdavis-mozilla** [comment]
@JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?

**Comment by JinZhuXing** [comment]
> @JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?

Uploaded.

[alphabet_20200214.zip](https://github.com/mozilla/DeepSpeech/files/4204035/alphabet_20200214.zip)

**Comment by kinni** [comment]
Make use you have run `export LC_ALL="en_US.UTF-8"` in your runtime for Python to handle unicode.

**Comment by JinZhuXing** [comment]
> Make use you have run `export LC_ALL="en_US.UTF-8"` in your runtime for Python to handle unicode.

Same error.

**Comment by JinZhuXing** [comment]
> > OK, I will test with vanilla Python.
> > Thanks, all of you.
> 
> @JinZhuXing Any update ?

It's the same. I can't do it.
So I will try with english dataset.
Thanks.

**Comment by JinZhuXing** [comment]
> > OK, I will test with vanilla Python.
> > Thanks, all of you.
> 
> @JinZhuXing Any update ?

It's the same. I can't do it.
So I will try with english dataset.
Thanks.

**Comment by lissyx** [comment]
> > @JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?
> 
> Uploaded.
> 
> [alphabet_20200214.zip](https://github.com/mozilla/DeepSpeech/files/4204035/alphabet_20200214.zip)

This does not include the transcript. Please, share debuggable data.

**Comment by JinZhuXing** [comment]
> > > @JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?
> > 
> > 
> > Uploaded.
> > [alphabet_20200214.zip](https://github.com/mozilla/DeepSpeech/files/4204035/alphabet_20200214.zip)
> 
> This does not include the transcript. Please, share debuggable data.

Uploaded transcript.

[zh-cn_trans.zip](https://github.com/mozilla/DeepSpeech/files/4279001/zh-cn_trans.zip)

**Comment by lissyx** [comment]
> > > > @JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?
> > > 
> > > 
> > > Uploaded.
> > > [alphabet_20200214.zip](https://github.com/mozilla/DeepSpeech/files/4204035/alphabet_20200214.zip)
> > 
> > 
> > This does not include the transcript. Please, share debuggable data.
> 
> Uploaded transcript.
> 
> [zh-cn_trans.zip](https://github.com/mozilla/DeepSpeech/files/4279001/zh-cn_trans.zip)

Ok, looking at your alphabet file there are **three** occurrences of `母`. Now I have no knowledge of `zh-cn` locale, but I suspect this is not expected.

**Comment by JinZhuXing** [comment]
> > > > > @JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?
> > > > 
> > > > 
> > > > Uploaded.
> > > > [alphabet_20200214.zip](https://github.com/mozilla/DeepSpeech/files/4204035/alphabet_20200214.zip)
> > > 
> > > 
> > > This does not include the transcript. Please, share debuggable data.
> > 
> > 
> > Uploaded transcript.
> > [zh-cn_trans.zip](https://github.com/mozilla/DeepSpeech/files/4279001/zh-cn_trans.zip)
> 
> Ok, looking at your alphabet file there are **three** occurrences of `母`. Now I have no knowledge of `zh-cn` locale, but I suspect this is not expected.

I just removed two '母‘ characters at alphabet file. But the same error occur.

**Comment by lissyx** [comment]
> > > > > > @JinZhuXing Could you post the transcript of common_voice_zh-CN_18782225.wav and your data/alphabet.txt?
> > > > > 
> > > > > 
> > > > > Uploaded.
> > > > > [alphabet_20200214.zip](https://github.com/mozilla/DeepSpeech/files/4204035/alphabet_20200214.zip)
> > > > 
> > > > 
> > > > This does not include the transcript. Please, share debuggable data.
> > > 
> > > 
> > > Uploaded transcript.
> > > [zh-cn_trans.zip](https://github.com/mozilla/DeepSpeech/files/4279001/zh-cn_trans.zip)
> > 
> > 
> > Ok, looking at your alphabet file there are **three** occurrences of `母`. Now I have no knowledge of `zh-cn` locale, but I suspect this is not expected.
> 
> I just removed two '母‘ characters at alphabet file. But the same error occur.

Could you please work on a reduced test case that reproduces the issue ?
99.999% of the time, those bugs are dataset-side.

**Comment by lissyx** [comment]
```
$ file issue_2611/alphabet.txt 
issue_2611/alphabet.txt: UTF-8 Unicode text, with CRLF line terminators
```

**Comment by lissyx** [comment]
@JinZhuXing Just removing `CRLF` line ending was enough. Training is only tested / supported on Linux so far, as documented.

**Comment by JinZhuXing** [comment]
Thank you @lissyx .
Solved.
Thanks all of you.

**Comment by lissyx** [comment]
@JinZhuXing #2813 will make sure people producing alphabet on one system and using it on another won't get into troubles.
