### ISSUE TITLE
mic_vad_streaming build fail on missing Python.h

### ISSUE THREAD

**Issue by mncharity** [mozilla/DeepSpeech#2617]
On Linux Ubuntu 19.10, after successfully running README's _To install and use deepspeech all you have to do is:_, I then attempted to install `mic_vad_streaming` from `DeepSpeech-examples`.  This failed in `pip install -r requirements.txt`, while compiling `src/_portaudiomodule.c`, with an error of `Python.h: No such file or directory`.

`python-config --includes` reports `-I<root>/tmp/deepspeech-venv/include/python3.7m`, which is a symlink to `/usr/include/python3.7m`.

So while `virtualenv` is creating a dedicated `<root>/tmp/deepspeech-venv/bin/python`, it is depending on the host system for includes.  If the system chances to not have python headers installed, then the `mic_vad_streaming` build fails.  After installing `python3-dev`, the build succeeded.

System `python --version` was `2.7.17rc1`, `python3 --version` was `3.7.5`, and `virtualenv --version` was `15.1.0`.  The venv `python --version` was `3.7.5rc1`.

Recommendation: Add `python3-dev` to `sudo apt install portaudio19-dev` in `mic_vad_streaming/README`'s _Installation_.

**Comment by lissyx** [comment]
> Recommendation: Add `python3-dev` to `sudo apt install portaudio19-dev` in `mic_vad_streaming/README`'s _Installation_.

That's not a bad recommandation, i'd be happy to review a PR for it :)
