### ISSUE TITLE
taskcluster.py URLs are incorrect

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2619]
`python3 util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --target .
`

Executing the above command on an Intel CPU running Ubuntu 18.04.3 generates the following URL, which returns a 404:

`https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.tensorflow.pip.v0.6.0.cpu/artifacts/public/convert_graphdef_memmapped_format`

(I get the same result when trying the `--branch` argument with various values including "master")

However, manually browsing the [Taskcluster site](https://community-tc.services.mozilla.com/tasks/groups/LKd1psmUTAy2oAms2q0fGA) allowed me to find the following URL that worked:

`https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.tensorflow.pip.cpu.e77504ac6b941fd2af495b49a0bcd56f25ca0e1e/artifacts/public/convert_graphdef_memmapped_format`

So it seems like the URLs need to contain the group ID in order to be valid.

**Comment by lissyx** [comment]
No, use the tensorflow release and not DeepSpeech one, `--branch r1. 14`

**Comment by dabinat** [comment]
@lissyx Thanks, that wasn't clear to me. I've updated the readme to be clearer about this.
