### ISSUE TITLE
v0.6 JSON output always has time=0, duration is incremental

### ISSUE THREAD

**Issue by tarekeldeeb** [mozilla/DeepSpeech#2623]
- No custom code, just used the 0.6 tag
- OS Platform: Linux Ubuntu 16.04
- native client version: DeepSpeech: v0.6.0-0-g6d43e21

I trained a model, inferring goes very good, but the "--json" option always get a time:0.
Duration gives incremental values, like an end marker for the word.

I would expect the time to be the start time of the word, and the duration to be as spelled.

Below is the output I get from a 16 sec audio file

> TensorFlow: v1.14.0-21-ge77504a
> DeepSpeech: v0.6.0-0-g6d43e21
> {
> 	"metadata": {
> 		"confidence": -46.9939
> 	},
> 	"words": [{
> 		"word": "بِسْمِ",
> 		"time": 0,
> 		"duration": 0.94
> 	}, {
> 		"word": "ٱللَّهِ",
> 		"time": 0,
> 		"duration": 1.58
> 	}, {
> 		"word": "ٱلرَّحْمَٰنِ",
> 		"time": 0,
> 		"duration": 2.56
> 	}, {
> 		"word": "ٱلرَّحِيمِ",
> 		"time": 0,
> 		"duration": 4.94
> 	}, {
> 		"word": "قُلْ",
> 		"time": 0,
> 		"duration": 6.38
> 	}, {
> 		"word": "هُوَ",
> 		"time": 0,
> 		"duration": 6.7
> 	}, {
> 		"word": "ٱللَّهُ",
> 		"time": 0,
> 		"duration": 7.52
> 	}, {
> 		"word": "أَحَدٌ",
> 		"time": 0,
> 		"duration": 8.18
> 	}, {
> 		"word": "ٱللَّهُ",
> 		"time": 0,
> 		"duration": 9.16
> 	}, {
> 		"word": "ٱلصَّمَدُ",
> 		"time": 0,
> 		"duration": 9.88
> 	}, {
> 		"word": "لَمْ",
> 		"time": 0,
> 		"duration": 10.96
> 	}, {
> 		"word": "يَلِدْ",
> 		"time": 0,
> 		"duration": 11.56
> 	}, {
> 		"word": "وَلَمْ",
> 		"time": 0,
> 		"duration": 12.08
> 	}, {
> 		"word": "يُولَدْ",
> 		"time": 0,
> 		"duration": 12.9
> 	}, {
> 		"word": "وَلَمْ",
> 		"time": 0,
> 		"duration": 13.42
> 	}, {
> 		"word": "يَكُن",
> 		"time": 0,
> 		"duration": 13.76
> 	}, {
> 		"word": "لَّهُۥ",
> 		"time": 0,
> 		"duration": 14.62
> 	}, {
> 		"word": "كُفُوًا",
> 		"time": 0,
> 		"duration": 15.22
> 	}, {
> 		"word": "أَحَدٌۢ",
> 		"time": 0,
> 		"duration": 16.02
> 	}]
> }

**Comment by lissyx** [comment]
> "--json" option

Which client are you using ? C++ ? JS ? Python ?

**Comment by tarekeldeeb** [comment]
> > "--json" option
> 
> Which client are you using ? C++ ? JS ? Python ?

C++ Downloaded with  `python util/taskcluster.py --target native_client--arch "gpu"`

**Comment by lissyx** [comment]
> > > "--json" option
> > 
> > 
> > Which client are you using ? C++ ? JS ? Python ?
> 
> C++ Downloaded with `python util/taskcluster.py --target native_client--arch "gpu"`

I don't repro here. Can you verify against the audio examples that we release?

```
$ ./tfpb/deepspeech --model eng/deepspeech-0.6.0-models/output_graph.pbmm --audio audio/4507-16021-0012.wav --json
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.0-0-g6d43e21
2019-12-31 17:02:33.202194: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
{"metadata":{"confidence":1.01063},"words":[{"word":"why","time":0,"duration":0.8},{"word":"should","time":0.86,"duration":0.22},{"word":"one","time":1.08,"duration":0.2},{"word":"halt","time":1.4,"duration":0.4},{"word":"on","time":1.82,"duration":0.22},{"word":"the","time":2.06,"duration":0.14},{"word":"way","time":2.22,"duration":0.32}]}
```

```
$ ./tfpb/deepspeech --model eng/deepspeech-0.6.0-models/output_graph.pbmm --audio audio/2830-3980-0043.wav --json
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.0-0-g6d43e21
2019-12-31 17:01:59.483542: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
{"metadata":{"confidence":1.73862},"words":[{"word":"experience","time":0,"duration":1.02},{"word":"proofsless","time":1.1,"duration":0.48}]}
```

**Comment by lissyx** [comment]
> I don't repro here. Can you verify against the audio examples that we release?

And obviously, english model.

**Comment by tarekeldeeb** [comment]
hi @lissyx , i cannot reproduce the issue with the example model as well.
With my trained model the issue persists.

**Comment by lissyx** [comment]
> hi @lissyx , i cannot reproduce the issue with the example model as well.
> With my trained model the issue persists.

That's super weird. Do you reproduce with your examples audio and ours model? And the inverse?

**Comment by lissyx** [comment]
>  "confidence": -46.9939

That is also weird, I think it should be > 0

**Comment by kdavis-mozilla** [comment]
Isn't it a raw logit[[1](https://github.com/mozilla/DeepSpeech/blob/0427c1572ac8f7253e46c7041c5e48d8da923cf2/native_client/deepspeech.h#L44)]? Thus it need not be positive.

**Comment by lissyx** [comment]
@tarekeldeeb Ping ?

**Comment by tarekeldeeb** [comment]
Sorry for being late.

MyModel/MyAudio           --> Time=0, Duration is incremental
MyModel/ExampleAudio  --> Time=0, Duration is incremental
ExampleModel/MyData --> Time is Ok, Duration is Ok

Confidence gets either positive or negative values. Did not catch a pattern here.
How can MyModel behave so weirdly, when the textual output is very good?!

**Comment by reuben** [comment]
It's very weird. The `time` value reported in the metadata output is incremented monotonically in the decoder, there should be no way for a transcription to have a character with the same time as as its parent. Did you make any modifications to the code?

**Comment by lissyx** [comment]
>  How can MyModel behave so weirdly, when the textual output is very good?!

Can you share more details on how you built this model ?

**Comment by lissyx** [comment]
@tarekeldeeb You're working on arabic language, right? Is it possible there's a funny behavior because of RTL here ?

**Comment by tarekeldeeb** [comment]
> It's very weird. The `time` value reported in the metadata output is incremented monotonically in the decoder, there should be no way for a transcription to have a character with the same time as as its parent (previous character). Did you make any modifications to the code?

Not a single line.

**Comment by lissyx** [comment]
> Maybe .. but the output string is perfectly fine. I think the RTL makes issues when mixed with latin letters/symbols or when it has multi-lines. Which is not the case here.

I'm just wondering how training and inference behaves in that case. Could you share your model, so I can investigate ?

**Comment by tarekeldeeb** [comment]
> > Maybe .. but the output string is perfectly fine. I think the RTL makes issues when mixed with latin letters/symbols or when it has multi-lines. Which is not the case here.
> 
> I'm just wondering how training and inference behaves in that case. Could you share your model, so I can investigate ?

Model and language files are found  [here](https://github.com/tarekeldeeb/DeepSpeech-Quran/tree/master/data/quran)

**Comment by lissyx** [comment]
> > > Maybe .. but the output string is perfectly fine. I think the RTL makes issues when mixed with latin letters/symbols or when it has multi-lines. Which is not the case here.
> > 
> > 
> > I'm just wondering how training and inference behaves in that case. Could you share your model, so I can investigate ?
> 
> Thanks a lot for your time. Model and language files are found [here](https://github.com/tarekeldeeb/DeepSpeech-Quran/tree/master/data/quran)

Weird. Although r1.14 and r1.15 should be a bit compatible, I'm getting segfaults loading your Protocolbuffer or TFLite models.

@tarekeldeeb Have those been exported with 0.6.0+ ? Tree status is unclear: `This branch is 41 commits ahead, 112 commits behind mozilla:master.`

Could you maybe share the checkpoints, to make sure ?

**Comment by lissyx** [comment]
Ok, I might be reproducing with your model.

**Comment by lissyx** [comment]
```
$ LD_LIBRARY_PATH=/home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflow/bazel-bin/native_client/:. ./deepspeech --model ~/tmp/deepspeech/quran/imam_graph.pb --audio ~/tmp/deepspeech/0.6.0/audio/4507-16021-0012.wav --json
TensorFlow: v1.15.0-22-gbd115ee104
DeepSpeech: v0.6.1-27-g345102da
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
item[0]: start_time=0.000000, character=و
item[1]: start_time=0.360000, character=َ
item[2]: start_time=0.960000, character=ٱ
item[3]: start_time=0.980000, character=ح
item[4]: start_time=1.000000, character=ْ
item[5]: start_time=1.160000, character=ض
item[6]: start_time=1.180000, character=ُ
item[7]: start_time=1.320000, character=ل
item[8]: start_time=1.360000, character=ْ
item[9]: start_time=1.420000, character= 
item[10]: start_time=1.480000, character=ص
item[11]: start_time=1.500000, character=َ
item[12]: start_time=1.760000, character=ف
item[13]: start_time=1.780000, character=ْ
item[14]: start_time=1.920000, character=ق
item[15]: start_time=1.940000, character=َ
item[16]: start_time=2.100000, character=ل
item[17]: start_time=2.120000, character=ْ
item[18]: start_time=2.220000, character= 
item[19]: start_time=2.260000, character=ط
item[20]: start_time=2.280000, character=َ
item[21]: start_time=2.460000, character=ي
item[22]: start_time=2.480000, character=ْ
{"metadata":{"confidence":7.73814},"words":[{"word":"وَٱحْضُلْ","time":0,"duration":1.42},{"word":"صَفْقَلْ","time":0,"duration":2.22},{"word":"طَيْ","time":0,"duration":2.48}]}
```

**Comment by lissyx** [comment]
@tarekeldeeb Your model does output only 2-bytes words. This is breaking some of the logic that we have, but the value coming from the API looks sane.

**Comment by lissyx** [comment]
@tarekeldeeb C++ builds / Python wheels out of https://community-tc.services.mozilla.com/tasks/groups/bPGMAhRKQBG2BPNX6tPSzQ should work better for you.
