### ISSUE TITLE
Error while trying to use audioTranscript examples. 

### ISSUE THREAD

**Issue by MankaranSingh** [mozilla/DeepSpeech#2631]
This is my output on running the cmd transcripter.

```Opening mic for streaming
DEBUG:root:Found Model: deepspeech-0.6.0-models\output_graph.pb
DEBUG:root:Found Language Model: deepspeech-0.6.0-models/lm.binary
DEBUG:root:Found Trie: deepspeech-0.6.0-models/trie
TensorFlow: v1.14.0-21-ge77504ac6b
DeepSpeech: v0.6.0-0-g6d43e21
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2020-01-06 01:04:21.864769: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
DEBUG:root:Loaded model in 1.020s.
DEBUG:root:Loaded language model in 0.019s.
Traceback (most recent call last):
  File "audioTranscript_cmd.py", line 92, in <module>
    main(sys.argv[1:])
  File "audioTranscript_cmd.py", line 78, in main
    bufsize=0)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by lissyx** [comment]
The error is pretty explicit : file not found. Since you don't share your command line we have nothing.

**Comment by lissyx** [comment]
> This is my output on running the cmd transcripter.
> 
> ```
> DEBUG:root:Found Model: deepspeech-0.6.0-models\output_graph.pb
> DEBUG:root:Found Language Model: deepspeech-0.6.0-models/lm.binary
> DEBUG:root:Found Trie: deepspeech-0.6.0-models/trie
> TensorFlow: v1.14.0-21-ge77504ac6b
> DeepSpeech: v0.6.0-0-g6d43e21
> Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
> 2020-01-06 01:04:21.864769: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> DEBUG:root:Loaded model in 1.020s.
> DEBUG:root:Loaded language model in 0.019s.
> Traceback (most recent call last):
>   File "audioTranscript_cmd.py", line 92, in <module>
>     main(sys.argv[1:])
>   File "audioTranscript_cmd.py", line 78, in main
>     bufsize=0)
>   File "C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```

It would have been quicker if you had shared what you are doing precisely from scratch. Instead, I had to do divination on:
 - your command line
 - your operating system

Looks like you are trying to run in streaming mode on Windows. This would execute https://github.com/mozilla/DeepSpeech-examples/blob/r0.6/vad_transcriber/audioTranscript_cmd.py#L76-L78, and I don't think `rec` works on that platform.

Please use `--audio` flag instead.

**Comment by MankaranSingh** [comment]
Ok, so i got it running by installing 'Sox 14.4.1' and replacing the command by ```sox -d -q -V0 -e signed -L -c 1 -b 16 -r 16k -t raw - gain -2``` 
on windows 10.

**Comment by MankaranSingh** [comment]
But there is another problem. the output comes up after a really long time. And that either an 'i' or an 'a' 
I am using the CPU version of deepspeech. So is it that real time transcription is more computationally heavy ?

**Comment by lissyx** [comment]
> Ok, so i got it running by installing 'Sox 14.4.1' and replacing the command by `sox -d -q -V0 -e signed -L -c 1 -b 16 -r 16k -t raw - gain -2` on windows 10.

Could you make a documentation PR for that? It's a good thing you have been able to find a solution. Or even maybe a patch ?

**Comment by lissyx** [comment]
>  the output comes up after a really long time.

Define "really long", define your hardware.



> So is it that real time transcription is more computationally heavy ?

I'm not sure to get your point here.



> And that either an 'i' or an 'a'

Known issue if you look at recently closed issues, we fixed that and it should make it in a 0.6.1 soonish. Silence would be infered as something like "i" or "a".

**Comment by MankaranSingh** [comment]
Yes sure ,ii'l do.  btw, i had some general doubts regarding usage of deepspeech in a project. Can i personally discuss with you through some medium ? I guarantee would just take 2 minutes.

**Comment by lissyx** [comment]
> Yes sure ,ii'l do. btw, i had some general doubts regarding usage of deepspeech in a project. Can i personally discuss with you through some medium ? I guarantee would just take 2 minutes.

Please use Discourse private messages for that ?
