### ISSUE TITLE
It's not installing

### ISSUE THREAD

**Issue by callmebhawesh** [mozilla/DeepSpeech#2632]
i just did everything to install deepspeech. But it is not installing, there are no icon of deepspeech, so that i should open it. is this normal ? like do i have to use terminal to launch deepspeech or is their something else ?

**Comment by lissyx** [comment]
> i just did everything to install deepspeech. But it is not installing, there are no icon of deepspeech, so that i should open it. is this normal ? like do i have to use terminal to launch deepspeech or is their something else ?

This is not a bug. Please look for support in Discourse, as you would have learnt about if you read the Github issue template you purposely ignored to fill.

Everything on how to use is already in the documentation you likely have read to perform the install, so please, help yourself and read more.
