### ISSUE TITLE
Path to 1.0

### ISSUE THREAD

**Issue by mattc-eostar** [mozilla/DeepSpeech#2633]
I see that this was brought up here two years ago.
https://discourse.mozilla.org/t/deepspeech-project-roadmap/24057

Is there any priority to create a formal roadmap for 2020? I know v1.0 is planned, but a laid list of planned features would be amazing for those of us possibly dependent on it.

Thank you!

**Comment by lissyx** [comment]
We've already shared that: https://github.com/mozilla/DeepSpeech/wiki/Meeting-Notes#agenda-25112019.
