### ISSUE TITLE
make compile error

### ISSUE THREAD

**Issue by YuBeomGon** [mozilla/DeepSpeech#2635]
in DeepSpeech/native_client,

(deepspeech-train-venv) beomgon@beomgon:~/DeepSpeech/native_client$ make -j
c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/beomgon/tensorflow/bazel-bin/native_client  -ldeepspeech  `pkg-config --libs sox`
/usr/bin/ld: cannot find -ldeepspeech
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed

I need a generate_trie and other binary, so I have to build.
what should I do??

**Comment by kdavis-mozilla** [comment]
Did you follow the instructions [here](https://github.com/mozilla/DeepSpeech/tree/master/native_client)? (It looks like you did not follow the instructions in the "Compile libdeepspeech.so & generate_trie" section.)

Could you include all steps you went through in compiling?

**Comment by lissyx** [comment]
> I need a generate_trie and other binary, so I have to build.

`generate_trie` is bunlded as part of `native_client` tarball we release. So you don't need to build.
