### ISSUE TITLE
Android: Speech-to-text result always empty

### ISSUE THREAD

**Issue by erksch** [mozilla/DeepSpeech#2642]
- **Have I written custom code**: 
Yes, an Android Demo that uses the example code from `native_client/java` but instead of compiling the libdeepspeech dependency myself I used the following gradle package:
```
implementation 'org.mozilla.deepspeech:libdeepspeech:0.6.1-alpha.0'
```

- **OS Platform and Distribution**: Linux Ubuntu 19.10. for my desktop, Samsung A50 with Arm64 architecture as the android device.
- **Exact command to reproduce**:
  - clone the repo and open the native_client/java project
  - replace `implementation project(':libdeepspeech')` with `implementation 'org.mozilla.deepspeech:libdeepspeech:0.6.1-alpha.0'` in the `build.gradle`
  - run on device

I can retrieve the sample rate of the model (`sampleRate`) without any problems so the library is basically working. 
But when I select an audio sample of my voice (double checked everything: wav, pcm, mono, 16khz, 16 bits per sample, buffer size 26) the speech to text inference only returns an empty string every time. If I additionally use `enableDecoderWihLM` (there is a typo by the way in this method) with: 
```
_m.enableDecoderWihLM("/path/to/lm.binary", "path/to/trie", LM_ALPHA, LM_BETA)
```
I only get an "i" as output. 

Is there anything I can do to debug the situation further?
The only thing my logs are printing out that seems to be relevant is:
```
E/libdeepspeech: TensorFlow: v1.14.0-21-ge77504a
E/libdeepspeech: DeepSpeech: v0.6.1-alpha.0-0-gdd645d5
```

I also have built the library myself but still no luck.

Thank you very much and keep up the good work!

**Comment by lissyx** [comment]
> I only get an "i" as output.

It's a (fixed) symptom of silence. There was an issue about silence being inferred as "I". 

>  If I additionally use `enableDecoderWihLM` (there is a typo by the way in this method) with:

Looks like you could send a fix, but I'm surprised this went through, we should have seen that in CI

> when I select an audio sample of my voice (double checked everything: wav, pcm, mono, 16khz, 16 bits per sample, buffer size 26)

This example is very simple. Have you checked logcat for error? Is your audio audible enough?

**Comment by lissyx** [comment]
Could you try with the audio samples we release?

**Comment by reuben** [comment]
> Looks like you could send a fix, but I'm surprised this went through, we should have seen that in CI

The test has the same typo. Probably a result of autocomplete.

**Comment by lissyx** [comment]
> > Looks like you could send a fix, but I'm surprised this went through, we should have seen that in CI
> 
> The test has the same typo. Probably a result of autocomplete.

So much same.

**Comment by erksch** [comment]
Yeah I'd be happy to fix the typo and contribute :)

**Comment by erksch** [comment]
Okay, I tried `/data/smoke_test/new-home-in-the-stars-16k.wav` and it works!
The only difference I see between this sample and mine is that the buffer size of that sample is 114750 while mine was only 26. What could that mean?

**Comment by lissyx** [comment]
> Yeah I'd be happy to fix the typo and contribute :)

Sorry, I've already done it :/



>  The only difference I see between this sample and mine is that the buffer size of that sample is 114750 while mine was only 26. What could that mean?

What do you mean, "buffer size" ?

**Comment by erksch** [comment]
> Sorry, I've already done it :/

No problem :)

```kotlin
RandomAccessFile wave = new RandomAccessFile(audioFile, "r");

wave.seek(20); 
char audioFormat = this.readLEChar(wave);

wave.seek(22); 
char numChannels = this.readLEChar(wave);

wave.seek(24); 
int sampleRate = this.readLEInt(wave);

wave.seek(34); 
char bitsPerSample = this.readLEChar(wave);

wave.seek(40); 
int bufferSize = this.readLEInt(wave); <--- I mean this
```

**Comment by lissyx** [comment]
> > Sorry, I've already done it :/
> 
> No problem :)
> 
> > What do you mean, "buffer size" ?
> 
> ```kotlin
> RandomAccessFile wave = new RandomAccessFile(audioFile, "r");
> 
> wave.seek(20); 
> char audioFormat = this.readLEChar(wave);
> 
> wave.seek(22); 
> char numChannels = this.readLEChar(wave);
> 
> wave.seek(24); 
> int sampleRate = this.readLEInt(wave);
> 
> wave.seek(34); 
> char bitsPerSample = this.readLEChar(wave);
> 
> wave.seek(40); 
> int bufferSize = this.readLEInt(wave); <--- I mean this
> ```

Hehe, well, 26 means your file is mostly empty.

**Comment by erksch** [comment]
hmmmm, but the app plays it back correctly...

**Comment by erksch** [comment]
But I guess that's not a problem on your site, so this can be closed.
I'll figure it out and look for the bufferSize, maybe something is misconfigured in my recording software.

Thank you very much!

**Comment by lissyx** [comment]
> But I guess that's not a problem on your site, so this can be closed.
> I'll figure it out and look for the bufferSize, maybe something is misconfigured in my recording software.
> 
> Thank you very much!

Yes, that's likely the case. As you can see, our code is very simple (as advertised, it is a simple demo). Broken-yet-working audio is not uncommon, and as much as I remember, the playback code is 100% Android-level, while we basically memcpy() based on buffer size :).
