### ISSUE TITLE
OSError: input_filepath tsv_dir/clips/common_voice_en_18885784.mp3 does not exist.

### ISSUE THREAD

**Issue by arajan10** [mozilla/DeepSpeech#2646]
i am confused as to what is happening!

Loading TSV file:  /home/arajan/Documents/Abhishek Rajan/Githubrepo/DeepSpeech-master/tsv_dir/train.tsv
Saving new DeepSpeech-formatted CSV file to:  tsv_dir/clips/train.csv
Importing mp3 files...
Traceback (most recent call last):
  File "bin/import_cv2.py", line 164, in <module>
    _preprocess_data(PARAMS.tsv_dir, AUDIO_DIR, label_filter_fun, PARAMS.space_after_every_character)
  File "bin/import_cv2.py", line 43, in _preprocess_data
    _maybe_convert_set(input_tsv, audio_dir, label_filter, space_after_every_character)
  File "bin/import_cv2.py", line 99, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "bin/import_cv2.py", line 70, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "bin/import_cv2.py", line 133, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/home/arajan/tmp/deepspeech-train-venv/lib/python3.7/site-packages/sox/transform.py", line 412, in build
    file_info.validate_input_file(input_filepath)
  File "/home/arajan/tmp/deepspeech-train-venv/lib/python3.7/site-packages/sox/file_info.py", line 215, in validate_input_file
    "input_filepath {} does not exist.".format(input_filepath)
OSError: input_filepath tsv_dir/clips/common_voice_en_18885784.mp3 does not exist.

**Comment by kdavis-mozilla** [comment]
Does the file

> ...input_filepath tsv_dir/clips/common_voice_en_18885784.mp3

exist?

From the error message it looks like it does not.

In a related question, what command line arguments did you use?

**Comment by arajan10** [comment]
hi kdavis i am using 
bin/import_cv2.py tsv_dir 
just to train the data .
tsv_dir contains train.csv , test.csv , dev.tsv
tsv_dir/clips contains audio files

**Comment by kdavis-mozilla** [comment]
What happens if you use an absolute path for 'tsv_dir'

**Comment by arajan10** [comment]
command used 
bin/import_cv2.py -h --/home/arajan/Documents/Abhishek Rajan/Githubrepo/DeepSpeech-master/tsv_dir


output:-




usage: import_cv2.py [-h] [--audio_dir AUDIO_DIR]
                     [--filter_alphabet FILTER_ALPHABET] [--normalize]
                     [--space_after_every_character]
                     tsv_dir

Import CommonVoice v2.0 corpora

positional arguments:
  tsv_dir               Directory containing tsv files

optional arguments:
  -h, --help            show this help message and exit
  --audio_dir AUDIO_DIR
                        Directory containing the audio clips - defaults to
                        "<tsv_dir>/clips"
  --filter_alphabet FILTER_ALPHABET
                        Exclude samples with characters not in provided
                        alphabet
  --normalize           Converts diacritic characters to their base ones
  --space_after_every_character
                        To help transcript join by white space

**Comment by kdavis-mozilla** [comment]
Why do you include a leading "--" on your path? It's not needed.

**Comment by arajan10** [comment]
ok ran the same command without -- .
same out put!
am i doing some thing wrong?

**Comment by kdavis-mozilla** [comment]
And don't include "-h" too.

**Comment by arajan10** [comment]
ohh ok
bin/import_cv2.py /home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir
was the command!

Loading TSV file:  /home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir/train.tsv
Saving new DeepSpeech-formatted CSV file to:  /home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir/clips/train.csv
Importing mp3 files...
Traceback (most recent call last):
  File "bin/import_cv2.py", line 164, in <module>
    _preprocess_data(PARAMS.tsv_dir, AUDIO_DIR, label_filter_fun, PARAMS.space_after_every_character)
  File "bin/import_cv2.py", line 43, in _preprocess_data
    _maybe_convert_set(input_tsv, audio_dir, label_filter, space_after_every_character)
  File "bin/import_cv2.py", line 99, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "bin/import_cv2.py", line 70, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "bin/import_cv2.py", line 133, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/home/arajan/tmp/deepspeech-train-venv/lib/python3.7/site-packages/sox/transform.py", line 412, in build
    file_info.validate_input_file(input_filepath)
  File "/home/arajan/tmp/deepspeech-train-venv/lib/python3.7/site-packages/sox/file_info.py", line 215, in validate_input_file
    "input_filepath {} does not exist.".format(input_filepath)
OSError: input_filepath /home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir/clips/common_voice_en_18885788.mp3 does not exist.

**Comment by kdavis-mozilla** [comment]
Now back to my old question. Does 

/home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir/clips/common_voice_en_18885788.mp3

exist? And do you have permissions to read it?

**Comment by arajan10** [comment]
if i gave system common_voice_en_18885788.mp3 .it asks for common_voice_en_18885789.mp3 .
i went on and now
OSError: input_filepath /home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir/clips/common_voice_en_18885791.mp3 does not exist.

**Comment by kdavis-mozilla** [comment]
No. Does the file 

/home/arajan/Documents/Abhishek_Rajan/Githubrepo/DeepSpeech-master/tsv_dir/clips/common_voice_en_18885788.mp3

exist? And do you have permissions to read it?

**Comment by arajan10** [comment]
yes

**Comment by kdavis-mozilla** [comment]
Is that yes to both questions?

**Comment by arajan10** [comment]
yes that resolved the issue!
