### ISSUE TITLE
Optimize 0.7.0 language model parameters for English

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#2650]

**Comment by doclr** [comment]
Hi. Please excuse my complete lack of experience as I am a doctor not a coder. I would like to know whether this language model could be used for healthcare application in speech recognition? All the healthcare related software is closed source and very expensive eg. Dragon. I wonder if deepspeech will be a way forward for open source software for this.

Do you think there is anyone at Mozilla interested in something like this. 

I apologise if this is the wrong place to ask this question. 

Sorry

**Comment by ftyers** [comment]
Dear @doclr, this is indeed the wrong place. But thank you for getting in contact. The right place to take this up is probably on [Disource](https://discourse.mozilla.org/c/deep-speech/247). I've taken the liberty of creating a [new topic](https://discourse.mozilla.org/t/healthcare-application-for-deepspeech/54556) there for the discussion. @kdavis-mozilla please feel free to delete these two comments.

**Comment by doclr** [comment]
Thanks and apologies again. 

Sent from Yahoo Mail on Android 
 
  On Sun, 23 Feb 2020 at 2:26, Francis Tyers<notifications@github.com> wrote:   
Dear @doclr, this is indeed the wrong place. But thank you for getting in contact. The right place to take this up is probably on Disource. I've taken the liberty of creating a new topic there for the discussion. @kdavis-mozilla please feel free to delete these two comments.

**Comment by kdavis-mozilla** [comment]
Done with current language model it lm_alpha=0.931289039105002, lm_beta=1.1834137581510284

**Comment by lissyx** [comment]
> Done with current language model it lm_alpha=0.931289039105002, lm_beta=1.1834137581510284

Was produced with your pending optimizer PR?

**Comment by kdavis-mozilla** [comment]
@lissyx Yes!
