### ISSUE TITLE
Model size is too big. Others created much smaller without compromising accuracy.

### ISSUE THREAD

**Issue by nuttyartist** [mozilla/DeepSpeech#2662]
This is a feature request. As you can see from https://github.com/Picovoice/speech-to-text-benchmark#results, Picovoice created [Cheetah](https://github.com/Picovoice/cheetah), a speech-to-text model with a model size that is 2% the size of DeepSpeech with almost the same accuracy. I'm not proficient enough to know whether it's model compression or other techniques being used but I think it's something to aspire since it's impractical to integrate DeepSpeech offline in consumer application with its big size.

**Comment by nuttyartist** [comment]
I'm sorry, I just saw your blog post and it seems that with your new version 0.6.0, you're pretty much on par. Great work!

**Comment by reuben** [comment]
It looks like their acoustic model is 5.17MB and their language model is 37.9MB. Our TFLite quantized acoustic model is 47.3MB and our language model is 957.9MB. DeepSpeech can be used without the language model, and in that case it is pretty much the same size as their model. I'll do a benchmarking run to see what our word error rate is without the LM.

**Comment by reuben** [comment]
(And we are also currently investigating ways to reduce model size both for the acoustic model and the LM.)

**Comment by nuttyartist** [comment]
Oh, can you shed some light on the difference between acoustic model and language model? And a benchmark will be awesome to see, thanks!

**Comment by nuttyartist** [comment]
Seems like there's still some way to go to get those sizes.

**Comment by reuben** [comment]
Yes, but this issue is not actionable, we're always aiming for smaller, faster, more accurate, so there's not much value in keeping this open.

I wrote a description of the system here, it should help with understanding the roles of the acoustic and language models: https://hacks.mozilla.org/2017/11/a-journey-to-10-word-error-rate/

**Comment by nuttyartist** [comment]
Gotcha. Do you information about the accuracy of the model with and without the language model on test set?

**Comment by reuben** [comment]
See here for some WER values with varying model sizes: https://github.com/mozilla/DeepSpeech/issues/2529#issuecomment-573553009

**Comment by nuttyartist** [comment]
Looks good. So AM without LM is 50.9MB and 8.6%?

**Comment by reuben** [comment]
No. The sizes in the headers are of the AM and LM independently. You have to sum the row with the column to get the total package size. For example, TFLite model (47MB) + 50.9MB LM = 97.9MB total package, WER = 8.9%.
