### ISSUE TITLE
Add TFLite for all packages

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#2671]
Current platforms status.

Default runtime:
 - [x] Linux/ARMv7 (RPi3/4)
 - [x] Linux/ARM64 (#2676)
 - [x] Android ARMv7
 - [x] Android ARM64
 - [x] Android x86-64 (not published)

Alternative runtime:
 - [x] Linux/AMD64
 - [x] MacOS/AMD64
 - [x] Windows/AMD64

**Comment by AIWintermuteAI** [comment]
Hi! I'm currently trying to run deepspeech 0.6.1 on Nvidia Jetson Nano. I downloaded pre-built binary deepspeech-0.6.1-cp37-cp37m-linux_aarch64.whl and could run it successfully on my board. The only problem is --- it cannot run .tflite models. The .pbmm model works(with swap extended to 4 Gb), but too slow (Inference took 17.638s for 1.975s audio file.).
Is pre-built binary for deepspeech_tflite-0.6.1 Linux/ARM64 available somewhere for downloading?
Thank you for your reply!

**Comment by lissyx** [comment]
> Hi! I'm currently trying to run deepspeech 0.6.1 on Nvidia Jetson Nano. I downloaded pre-built binary deepspeech-0.6.1-cp37-cp37m-linux_aarch64.whl and could run it successfully on my board. The only problem is --- it cannot run .tflite models. The .pbmm model works(with swap extended to 4 Gb), but too slow (Inference took 17.638s for 1.975s audio file.).
> Is pre-built binary for deepspeech_tflite-0.6.1 Linux/ARM64 available somewhere for downloading?
> Thank you for your reply!

This is not the place to ask.

**Comment by reuben** [comment]
Is this done? I think we can't publish Android x86-64 on PyPI?

**Comment by lissyx** [comment]
> Is this done? I think we can't publish Android x86-64 on PyPI?

Well it's only bundled in the `libdeepspeech` AAR. I think it's mostly done, but I would not be against another pair of eyes verifying we have it everywhere, either as default runtime or as an alternative package.

**Comment by lissyx** [comment]
@kdavis-mozilla Does completion of this tasks is "we have an alternative with TFLite usable by people for all platforms we have" ? If so, I'll do a new pass to verify, but I think we are covered.

**Comment by kdavis-mozilla** [comment]
@lissyx Yes the task is to "have an alternative with TFLite usable by people for all platforms we have".

**Comment by lissyx** [comment]
Right, so:

TFLite / Python:
 - [ ] Linux/AMD64
 - [ ] Linux/ARMv7
 - [ ] Linux/ARM64
 - [ ] Windows/AMD64
 - [ ] macOS/AMD64

TFLite / NodeJS
 - [ ] Linux/AMD64
 - [ ] Linux/ARMv7
 - [ ] Linux/ARM64
 - [ ] Windows/AMD64
 - [ ] macOS/AMD64

TFLite / Java
 - [ ] Android/ARM64
 - [ ] Android/ARMv7

TFLite / .Net
 - [ ] Windows/AMD64

**Comment by lissyx** [comment]
We have builds more or less ready for NodeJS and .Net, but we don't publish them to their repository. I can create those `deepspeech-tflite` there, so we get them published.  Any objection @kdavis-mozilla @reuben ?

**Comment by kdavis-mozilla** [comment]
No objection here

**Comment by lissyx** [comment]
We should be covered now. Next alpha release should help us ensure it's the case.

**Comment by lissyx** [comment]
Uploads from v0.7.0-alpha.0 are completed and it seems we are covered on all platforms now.
