### ISSUE TITLE
Can DeepSpeech be used with Windows ? 

### ISSUE THREAD

**Issue by Stass88** [mozilla/DeepSpeech#2678]
Hello,
Recently  I found article that deepspeech is is available on Windows, macOS, and Linux as well as Android. Is it valid information and is there guide how to set up everything on Windows ? 
Thank you in advance for help !

**Comment by reuben** [comment]
The issue template is meant to be read, not deleted blindly. For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).
