### ISSUE TITLE
Got this error on Google Collab: Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA

### ISSUE THREAD

**Issue by byteshiva** [mozilla/DeepSpeech#2680]
I tried to execute the sample code(https://github.com/mozilla/DeepSpeech) in google collab, but gave warning "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA"

```
!deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --lm deepspeech-0.6.1-models/lm.binary --trie deepspeech-0.6.1-models/trie --audio audio/2830-3980-0043.wav

Loading model from file deepspeech-0.6.1-models/output_graph.pbmm
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
2020-01-19 14:52:53.618118: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Loaded model in 0.0089s.
Loading language model from files deepspeech-0.6.1-models/lm.binary deepspeech-0.6.1-models/trie
Loaded language model in 0.000185s.
Running inference.
experience proof less
Inference took 1.381s for 1.975s audio file.
```

```
!python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.15.0-0-g590d6eef7e 1.15.0

```

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
 I tried to execute the sample code(https://github.com/mozilla/DeepSpeech) in google collab, but gave warning "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA"
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux e57535a128e6 4.14.137+ #1 SMP Thu Aug 8 02:47:02 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by lissyx** [comment]
There is no problem here, it's just a warning that the cpu has instructions that we don't use.
