### ISSUE TITLE
Bazel build throws Python.h not found

### ISSUE THREAD

**Issue by cli0** [mozilla/DeepSpeech#2683]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18-04
- **DeepSpeech**: 0.4.1
- **TensorFlow version (use command below)**: 1.12
- **Python version**: 2.7/3.6
- **Bazel version (if compiling from source)**:0.15.0
- **GCC/Compiler version (if compiling from source)**:gcc-6
- **CUDA/cuDNN version**:9

You can obtain the TensorFlow version with

I am trying to compile tensorflow and DeepSpeech/native_client/ using bazel and I get this error:

```
ERROR: /home/workspace/tensorflow/native_client/BUILD:52:1: C++ compilation of rule '//native_client:libdeepspeech.so' failed (Exit 1)
native_client/ctcdecode/swigwrapper_wrap.cpp:174:21: fatal error: Python.h: No such file or directory
 # include <Python.h>
                     ^
compilation terminated.
INFO: Elapsed time: 2129.205s, Critical Path: 179.47s
INFO: 1878 processes: 1878 local.
FAILED: Build did NOT complete successfully
```

If I run locate Python.h I get:

```
/usr/include/python2.7/Python.h
/usr/include/python3.6m/Python.h

```
I added the two python folders to the Python path but I still get this issue.

The same configuration but without GPU in another machine does not raise the same error. So somehow bazel is not finding Python.h. 

I am using an older version of DS and I simply cannot upgrade so that's not an option.

**Comment by lissyx** [comment]
> I am trying to compile tensorflow and DeepSpeech/native_client/ using bazel and I get this error:

Your error refers to SWIG wrapper for CTC decode. That's not related to Bazel. Can you please clarify what you are doing exactly ?

**Comment by lissyx** [comment]
@cli0 Could you please ensure you don't have stale files under `native_client/ctcdecode/` ? I suspect you somehow called `make -C native_client/ctcdecode/` and there's a dangling `native_client/ctcdecode/swigwrapper_wrap.cpp` that gets picked by Bazel.

**Comment by cli0** [comment]
The command I used is 

`bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie --config=cuda
`

I am just building DeepSpeech binaries according to: https://github.com/mozilla/DeepSpeech/tree/master/native_client

**Comment by lissyx** [comment]
> I am just building DeepSpeech binaries according to: https://github.com/mozilla/DeepSpeech/tree/master/native_client

This is documentation for `master`, please use `v0.4.1` documentation.

**Comment by lissyx** [comment]
> The command I used is
> 
> `bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie --config=cuda `
> 
> I am just building DeepSpeech binaries according to: https://github.com/mozilla/DeepSpeech/tree/master/native_client

@cli0 Can you please verify for stale files, as stated above ?

**Comment by cli0** [comment]
@lissyx  Yes, there was a dangling swigwrapper_wrap.cpp. I am currently doing a clean bazel build (clean tf, clean DS, just cloned) and am waiting for the results to see if the error appears again. That's why I did not respond sooner. Sorry.

**Comment by lissyx** [comment]
> @lissyx Yes, there was a dangling swigwrapper_wrap.cpp. I am currently doing a clean bazel build (clean tf, clean DS, just cloned) and am waiting for the results to see if the error appears again. That's why I did not respond sooner. Sorry.

I'm confident it's going to work ...

**Comment by lissyx** [comment]
> @lissyx Yes, there was a dangling swigwrapper_wrap.cpp. I am currently doing a clean bazel build (clean tf, clean DS, just cloned) and am waiting for the results to see if the error appears again. That's why I did not respond sooner. Sorry.

@cli0 So, any news ?

**Comment by cli0** [comment]
@lissyx  Yes, I just came to work and checked the process and everything was successfully built. It was the .cpp file that caused the issue :) Thanks for the help.

**Comment by lissyx** [comment]
Thanks!
