### ISSUE TITLE
Trie file version mismatch (4 instead of expected 5)

### ISSUE THREAD

**Issue by YuBeomGon** [mozilla/DeepSpeech#2684]
Hi, 
My setting is below. (from https://github.com/mozilla/DeepSpeech/blob/master/doc/TRAINING.rst#training-your-own-model)
ubuntu 18.04
CUDA Version: 10.2 
Tensorflow : tensorflow-gpu==1.14.0
python version : 3.6.8
generate_trie bin : I donwload several prebuild trie bin
(the link is right now error)
GPU : GeForce RTX 2080
GPU driver : Driver Version: 440.44
ds-ctcdecoder : 0.6.1

when I train like below, Trie file version mismatch (4 instead of expected 5) error happen during test.
python DeepSpeech.py --train_files ../et/clips/train.csv --dev_files ../et/clips/dev.csv --test_files ../et/clips/test.csv

what should I do?

```
Epoch 0 |   Training | Elapsed Time: 1:12:27 | Steps: 11800 | Loss: 109.211779
Epoch 0 | Validation | Elapsed Time: 0:10:14 | Steps: 2950 | Loss: 103.532026 | Dataset: data/KO/clips_aihub/dev.csv
I Saved new best validating model with loss 103.532026 to: data/KO/clips_aihub/ckpt/best_dev-111675
Epoch 1 |   Training | Elapsed Time: 1:12:24 | Steps: 11800 | Loss: 112.539696
Epoch 1 | Validation | Elapsed Time: 0:10:12 | Steps: 2950 | Loss: 105.310229 | Dataset: data/KO/clips_aihub/dev.csv
Epoch 2 |   Training | Elapsed Time: 1:12:24 | Steps: 11800 | Loss: 114.825185
Epoch 2 | Validation | Elapsed Time: 0:10:13 | Steps: 2950 | Loss: 109.335827 | Dataset: data/KO/clips_aihub/dev.csv
Epoch 3 |   Training | Elapsed Time: 1:12:20 | Steps: 11800 | Loss: 117.088977
Epoch 3 | Validation | Elapsed Time: 0:10:13 | Steps: 2950 | Loss: 108.244031 | Dataset: data/KO/clips_aihub/dev.csv
Epoch 4 |   Training | Elapsed Time: 1:12:19 | Steps: 11800 | Loss: 117.716074
Epoch 4 | Validation | Elapsed Time: 0:10:14 | Steps: 2950 | Loss: 111.868323 | Dataset: data/KO/clips_aihub/dev.csv
I Early stop triggered as (for last 4 steps) validation loss: 111.868323 with standard deviation: 1.699825 and mean: 107.630029
I FINISHED optimization in 6:53:08.100998
Error: Trie file version mismatch (4 instead of expected 5). Update your trie file.
terminate called after throwing an instance of 'int'
Fatal Python error: Aborted
```

**Comment by lissyx** [comment]
> what should I do?

Read the documentation and the issue template you removed.



> generate_trie bin : I donwload several prebuild trie bin
> (the link is right now error)

What does that mean ?

>  Error: Trie file version mismatch (4 instead of expected 5). Update your trie file.

`data/lm/trie` is the wrong version. What did you do, exactly ?

**Comment by kinni** [comment]
you have to use the latest generate_trie to generate the trie file in order to match the version.

[Reference](https://github.com/mozilla/DeepSpeech/blob/d925e6b5fc186f3524e7c03d6eacf440d5366262/data/lm/README.rst)

**Comment by lissyx** [comment]
> you have to use the latest generate_trie to generate the trie file in order to match the version.

No, you need to use **matching** version, the latest from master **might** be too recent as well.

**Comment by kinni** [comment]
> > you have to use the latest generate_trie to generate the trie file in order to match the version.
> 
> No, you need to use **matching** version, the latest from master **might** be too recent as well.

Yes, my bad; you need to check the version which you generate the trie and the version of the deepspeech you are using. Cheers.

**Comment by lissyx** [comment]
@YuBeomGon Please, can we have feedback ?

**Comment by lissyx** [comment]
Closing because there is no issue here, it's just mixup of models.
