### ISSUE TITLE
Can we print the transcription on the go instead of displaying all in end?

### ISSUE THREAD

**Issue by virenpawar** [mozilla/DeepSpeech#2689]
Feature Request:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: 
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Linux shavak-dl-server 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 
Yes
- **TensorFlow version (use command below)**:
v1.15.0-rc3-22-g590d6ee 1.15.0
- **Python version**: 
Python 3.6.8
- **Description**:
While using deepspeech for large audio files, it takes a lot of time to generate transcript and I understand that it is usual, but can we add a flag or feature to print the transcription on the go. For example, print transcription as soon as deepspeech generates it. May be current version of deepspeech is building a string and after interference finishes it's work, the entire string get's print, so if we could print transcription on the go it would be more helpful.

**Comment by lissyx** [comment]
>  While using deepspeech for large audio files, it takes a lot of time to generate transcript and I understand that it is usual, but can we add a flag or feature to print the transcription on the go. For example, print transcription as soon as deepspeech generates it. May be current version of deepspeech is building a string and after interference finishes it's work, the entire string get's print, so if we could print transcription on the go it would be more helpful.

Have you had a look at the API ? How does https://deepspeech.readthedocs.io/en/v0.6.1/C-API.html#_CPPv419DS_FeedAudioContentP14StreamingStatePKsj and https://deepspeech.readthedocs.io/en/v0.6.1/C-API.html#_CPPv421DS_IntermediateDecodeP14StreamingState not fit your need ?

**Comment by virenpawar** [comment]
Sorry 😅
