### ISSUE TITLE
Propagate/handle errors in Java bindings

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2701]
Right now, most of the code under `native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/` is basically Java/JNI wrapper on top of C library.
As part of making the Java interface more Java-ish, it would be nice to update each and every call sites of the C-API that might return an error and properly throw a Java-level exception.

It might be required that we define a set of Java-specific exception classes, more or less mapped on the `DeepSpeech_Error_Codes` one.

Obviously, it also means adding class annotations that those calls might throw exceptions.

**Comment by reuben** [comment]
@lissyx if this is a good first bug it should probably include an explanation here of what's missing and how to go at fixing it.

**Comment by lissyx** [comment]
> @lissyx if this is a good first bug it should probably include an explanation here of what's missing and how to go at fixing it.

I think I got lurred and mixed with another good first bug where you did it :/

**Comment by reuben** [comment]
> I think I got lurred and mixed with another good first bug where you did it :/

So should the tags be removed from this issue?

**Comment by lissyx** [comment]
Nope, just let me some time and I'll document thoroughly

**Comment by reuben** [comment]
Ah, OK. Sorry, I misunderstood your other comment.

**Comment by reuben** [comment]
@lissyx ping re documentation for this. This will require significant changes to the bindings, so it'd be best if we landed it before 0.7.0.

**Comment by lissyx** [comment]
> @lissyx ping re documentation for this. This will require significant changes to the bindings, so it'd be best if we landed it before 0.7.0.

Isn't my edit enough yet? Part of the issue is that's I'm very far from the Java world, I lack a good overview of everything that should be done differently :)

**Comment by reuben** [comment]
Oh, sorry, I missed your edit. Maybe add some documentation on how to build the Java bindings? Probably checked into the tree rather than just here on this issue. AFAIK currently you have to find out how to do it from the TaskCluster scripts.

**Comment by lissyx** [comment]
> Oh, sorry, I missed your edit. Maybe add some documentation on how to build the Java bindings? Probably checked into the tree rather than just here on this issue. AFAIK currently you have to find out how to do it from the TaskCluster scripts.

Current doc already cover the `make apk`, what do you think is missing and requires looking into TC scripts ?

**Comment by reuben** [comment]
Ah, I missed that section, because I was looking for a way to build just the bindings, so I ignored the "demo app" section. Ignore me then.

**Comment by lissyx** [comment]
> Ah, I missed that section, because I was looking for a way to build just the bindings, so I ignored the "demo app" section. Ignore me then.

I'm 100% open to improve the docs if I know the pain points :)

**Comment by reuben** [comment]
Fixed in ee30a1c9dead1b7cbd86ab51a2039f5e1859740b
