### ISSUE TITLE
Error: Trie file version mismatch (5 instead of expected 4)

### ISSUE THREAD

**Issue by victornoriega** [mozilla/DeepSpeech#2707]
When DeepSpeech tried to test after training, it threw me that error. I had seen errors like '4 instead of expected 3' but never this. The trie I generated was from the pre-built generate_trie.cpp that you compiled. I'm using DeepSpeech 0.6.1.

**Comment by lissyx** [comment]
> When DeepSpeech tried to test after training, it threw me that error. I had seen errors like '4 instead of expected 3' but never this. The trie I generated was from the pre-built generate_trie.cpp that you compiled. I'm using DeepSpeech 0.6.1.

Please ensure `generate_trie` is also from 0.6.1.

**Comment by victornoriega** [comment]
I executed this:

`python util/taskcluster.py --target .`

in a DeepSpeech 0.6.1 cloned repository.

**Comment by lissyx** [comment]
> I executed this:
> 
> `python util/taskcluster.py --target .`
> 
> in a DeepSpeech 0.6.1 cloned repository.

We could still have bugs... The URL should have been printed but you did not shared that, so I can't know for sure. 

Please force `--branch v0.6.1` or use release's `native_client.tar.xz` from github releases v0.6.1, to be sure.

**Comment by lissyx** [comment]
@victornoriega Are you sure you are using LM from 0.6.1 ? 5 is the proper value, 4 indicates that you are using older version.

**Comment by victornoriega** [comment]
Sorry. Here's what it printed:

`Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.6.1.cpu/artifacts/public/native_client.tar.xz ...
Downloading: 100%

generate_trie
libdeepspeech.so
LICENSE
deepspeech
deepspeech.h
README.mozilla`

Yes I know it should be 5 right now. I generated my lm from the kenlm code you provide, and also from the newest version of kpu/kenlm because it may be the proper. Maybe is the model I tested? I'm testing a model I trained with DS 0.5.1 in a 0.6.1 repo. Should I retrain the model with DS 0.6.1 ?

**Comment by lissyx** [comment]
Yes, please.

**Comment by lissyx** [comment]
Closing since we figured out the issue.

**Comment by victornoriega** [comment]
I retrained with DS v0.6.1 and still got the problem. I'm saving the models just for testing later. What should I do?

**Comment by lissyx** [comment]
> I retrained with DS v0.6.1 and still got the problem. I'm saving the models just for testing later. What should I do?

Are you sure everything in your training is properly uptodate at 0.6.1 ? It's really hard to help with so few informations on your setup: what's your `pip list` output ?

**Comment by carlfm01** [comment]
Make sure you are using the generatetrie tool based on master, this happened to me time ago and you only need to make sure you are using the same versions while training and when generating the trie file

**Comment by victornoriega** [comment]
> Are you sure everything in your training is properly uptodate at 0.6.1 ? It's really hard to help with so few informations on your setup: what's your pip list output ?

`Package              Version  
-------------------- ---------
absl-py              0.8.0    
asn1crypto           0.24.0   
astor                0.8.0    
attrdict             2.0.1    
audioread            2.1.8    
bcrypt               3.1.7    
beautifulsoup4       4.8.0    
bs4                  0.0.1    
cachetools           3.1.1    
certifi              2019.9.11
cffi                 1.12.3   
chardet              3.0.4    
cryptography         2.7      
cycler               0.10.0   
decorator            4.4.0    
deepspeech           0.6.1    
ds-ctcdecoder        0.6.0a8  
gast                 0.3.2    
google-auth          1.6.3    
google-auth-oauthlib 0.4.1    
google-pasta         0.1.7    
grpcio               1.16.1   
h5py                 2.10.0   
idna                 2.8      
joblib               0.13.2   
Keras                2.2.4    
Keras-Applications   1.0.8    
Keras-Preprocessing  1.1.0    
kiwisolver           1.1.0    
librosa              0.7.0    
llvmlite             0.29.0   
Markdown             3.1.1    
matplotlib           3.1.1    
mkl-service          2.3.0    
mock                 3.0.5    
numba                0.45.1   
numpy                1.17.3   
oauthlib             3.1.0    
opt-einsum           3.1.0    
pandas               0.25.1   
paramiko             2.6.0    
pip                  19.2.3   
progressbar2         3.47.0   
protobuf             3.9.2    
psutil               5.6.2    
pyasn1               0.4.7    
pyasn1-modules       0.2.7    
pycparser            2.19     
PyNaCl               1.3.0    
pyparsing            2.4.2    
python-dateutil      2.8.0    
python-utils         2.3.0    
pytz                 2019.2   
pyxdg                0.26     
PyYAML               5.1.2    
requests             2.22.0   
requests-oauthlib    1.2.0    
resampy              0.2.2    
rsa                  4.0      
scikit-learn         0.21.3   
scipy                1.3.1    
seaborn              0.9.0    
setuptools           41.2.0   
six                  1.12.0   
SoundFile            0.10.2   
soupsieve            1.9.4    
sox                  1.3.7    
tensorboard          1.14.0   
tensorflow           1.14.0   
tensorflow-estimator 1.14.0   
tensorflow-gpu       1.14.0   
termcolor            1.1.0    
tqdm                 4.32.1   
urllib3              1.25.6   
virtualenv           16.7.8   
webrtcvad            2.0.10   
Werkzeug             0.16.0   
wheel                0.33.6   
wrapt                1.11.2`

> Make sure you are using the generatetrie tool based on master, this happened to me time ago and you only need to make sure you are using the same versions while training and when generating the trie file

I pulled from the repository yesterday before opening this issue, then generated the trie and trained models. Not sure what I'm doing wrong.

**Comment by lissyx** [comment]
> deepspeech 0.6.1
> ds-ctcdecoder 0.6.0a8

Here we go, since you did not share any details on what you were doing, we know what's wrong:
 - you don't need `deepspeech` here, that's only for inference
 - you need to use matching uptodate version of `ds-ctcdecoder` ... which 100% explains your issue.

**Comment by victornoriega** [comment]
Ok, thanks, I will try updating it.

**Comment by victornoriega** [comment]
I updated the decoder to 0.7.0 and worked. Thank you @lissyx  @carlfm01

**Comment by reuben** [comment]
As people have said this several times in this thread already, you have to install the same version everywhere. You said you were using v0.6.1 to train, so you should use v0.6.1 for the decoder package too.
