### ISSUE TITLE
Out Of Memory in case of Full Audio Files

### ISSUE THREAD

**Issue by ezeiatech** [mozilla/DeepSpeech#2713]
Hi,

We are using deepspeech to transcript audio files. If we segment the audio files in chunks of 10 secs our system and pipeline works fine but if we give a 10 min audio file directly to deepspeech the memory is not released and after some time the application goes out of memory

Is there some documentation or writeup on how to deploy deepspeech in production which can handle say 20-40 concurrent requests and perform at scale.

Thanks

**Comment by kdavis-mozilla** [comment]
There are [examples](https://github.com/mozilla/DeepSpeech-examples) that indicate how to do transcription of long files. For example, see the [vad_transcriber](https://github.com/mozilla/DeepSpeech-examples/blob/r0.6/vad_transcriber/wavTranscription.md) example, the code for which is [here](https://github.com/mozilla/DeepSpeech-examples/tree/r0.6/vad_transcriber).

There are various means to deploy to SaaS production. For example, using a thread pool and one model per thread or using TensorFlow Serving. However, we do not have examples of either.

**Comment by ezeiatech** [comment]
It have been mentioned on the forum that there is no need to use vad and segment audio files from 0.61 onwards. Do i still need to use vad ?

**Comment by lissyx** [comment]
> It have been mentioned on the forum that there is no need to use vad and segment audio files from 0.61 onwards. Do i still need to use vad ?

What has been mentionned was only in reference to the architecture of the network. Your use-case in unclear, and you don't provide any context to properly analyze if there's a bug or just a discrepancy of ressources.

We don't even know what version of DeepSpeech you are referring to.
