### ISSUE TITLE
Upload CTC Decoder .whl to GitHub for Releases

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#2717]

**Comment by imskr** [comment]
Can i work on this issue ?

**Comment by kdavis-mozilla** [comment]
@lissyx Would it be possible for @imskr to take this?

**Comment by lissyx** [comment]
I'm unsure because it's mostly scriptworker stuff 😕

**Comment by lissyx** [comment]
> @lissyx Would it be possible for @imskr to take this?

Checking the `scriptworker` code, we should just have to add a dependency of the ctc decoder build in the github upload package, but that's really taskclusterish. Though, it would require doing a new alpha to ensure it works, so I'm unsure how much it can be interesting for @imskr to contribute that.

**Comment by lissyx** [comment]
> > @lissyx Would it be possible for @imskr to take this?
> 
> Checking the `scriptworker` code, we should just have to add a dependency of the ctc decoder build in the github upload package, but that's really taskclusterish. Though, it would require doing a new alpha to ensure it works, so I'm unsure how much it can be interesting for @imskr to contribute that.

That's actually a **bit** more complicated and might even require `scriptWorker` changes :/

**Comment by lissyx** [comment]
@imskr So if you want to do this, you can, I'm unsure of the value for you though. What you need to do is:
 - add a dependency against the ctc decoder builds tasks (`darwin-amd64-ctc-opt` and `linux-amd64-ctc-opt`) in the github upload task (`scriptworker-task-github`)
 - add the ctc decoder builds tasks in the `python` list of the github upload task

For context, on our TaskCluster usage, each `.yml` in `taskcluster/` is a task that gets scheduled to run something for CI/CD. Task in TaskCluter are referred to using slug names, and we have tooling that is able to preprocess the `.yml` files and extracts nice tasks names (i.e., filename without `.yml`) and transform that into internal slug identifiers.

**Comment by lissyx** [comment]
@imskr Do you still want to take it ?

**Comment by imskr** [comment]
@lissyx yes I want to work on this. I will ask for help if needed.

**Comment by lissyx** [comment]
> @lissyx yes I want to work on this. I will ask for help if needed.

@imskr Gentle ping?

**Comment by lissyx** [comment]
> > @lissyx yes I want to work on this. I will ask for help if needed.
> 
> @imskr Gentle ping?

@imskr Are you still expecting to send a patch for that or not?

**Comment by imskr** [comment]
Sorry for the delay @lissyx I will be making a PR. What I have done now is added `darwin-amd64-ctc-opt` and `linux-amd64-ctc-opt`  in `python` list of `scriptworker-task-github`. Am I doing right?

**Comment by imskr** [comment]
@lissyx Please review the PR!

**Comment by lissyx** [comment]
> Sorry for the delay @lissyx I will be making a PR. What I have done now is added `darwin-amd64-ctc-opt` and `linux-amd64-ctc-opt` in `python` list of `scriptworker-task-github`. Am I doing right?

You forgot to add the dependencies as I stated :/

**Comment by imskr** [comment]
Ohh sorry I'll just add it!
