### ISSUE TITLE
Figure out why Windows builds are failing to download Electron headers

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2718]

**Comment by lissyx** [comment]
Some data I gathered:
 - it seemed any `us-east-*` instances would fail
 - it seemed many `us-west-*` instances would succeed.

**Comment by lissyx** [comment]
Just saw an instance in `us-west-1` failing :/

**Comment by lissyx** [comment]
Failures on `us-east-1` as well.

**Comment by lissyx** [comment]
Also some success on `us-west-1` :/

**Comment by lissyx** [comment]
@reuben Maybe it would be worth hand-fetching all of them, make a tar that we can attach as a mount-point at the right place in the Windows workers ?

**Comment by reuben** [comment]
Yeah, I guess hosting ourselves is the easiest solution.
