### ISSUE TITLE
Migrate from IRC

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2735]
- [x] Remove IRC notification from TaskCluster ahead of IRC server shutdown
- [ ] Migrate to Matrix: https://bugzilla.mozilla.org/show_bug.cgi?id=1522154
- [x] Update documentation to refer to Matrix
  - [x] In-repo docs
  - [x] GitHub wiki docs
- [x] Point to Matrix room in IRC room topic and notify users
- [ ] Something else?

To be safe and avoid things failing because of the IRC server not being available.

**Comment by reuben** [comment]
No new messages on the channel since Monday, all users were notified, new link is in the topic. Nothing has caught on fire so far.

**Comment by jardayn** [comment]
Have y'all considered making a discord server?

**Comment by reuben** [comment]
Yes, see here for why it was dropped out of consideration: http://exple.tive.org/blarg/2019/09/06/forward-motion/

**Comment by reuben** [comment]
Marking this as done, IRC has shut down.
