### ISSUE TITLE
error: unrecognized arguments: --scorer deepspeech-0.6.1-models/kenlm.scorer

### ISSUE THREAD

**Issue by crowlogic** [mozilla/DeepSpeech#2743]
follwed the instructions on the project's main page and got the following results:

(deepspeech-venv) me@box:~/DeepSpeech$ deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --scorer deepspeech-0.6.1-models/kenlm.scorer --audio audio/2830-3980-0043.wav
usage: deepspeech [-h] --model MODEL [--lm [LM]] [--trie [TRIE]] --audio AUDIO
                  [--beam_width BEAM_WIDTH] [--lm_alpha LM_ALPHA]
                  [--lm_beta LM_BETA] [--version] [--extended] [--json]
deepspeech: error: unrecognized arguments: --scorer deepspeech-0.6.1-models/kenlm.scorer

**Comment by ftyers** [comment]
What happens if you do `deepspeech --version` ?

**Comment by crowlogic** [comment]
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe

**Comment by kdavis-mozilla** [comment]
The flag `--scorer` is not part of the 0.6.1 release, see for example [here](https://github.com/mozilla/DeepSpeech/blob/v0.6.1/util/flags.py). Please refer to the correct version of the documentation, in this case the 0.6.1 version of the documentation, and not master.

**Comment by jwheat** [comment]
If that is the case (The flag --scorer is not part of the 0.6.1 release) it should probably be removed from each of the example blocks here - https://github.com/mozilla/DeepSpeech under 
`# Transcribe an audio file`

**Comment by lissyx** [comment]
> If that is the case (The flag --scorer is not part of the 0.6.1 release) it should probably be removed from each of the example blocks here - https://github.com/mozilla/DeepSpeech under
> `# Transcribe an audio file`

That documentation is for master. The v0.6.1 is okay: https://github.com/mozilla/DeepSpeech/tree/v0.6.1

**Comment by jeremydvoss** [comment]
I am having this same issue. I have trained a model. I now what to test it on such an audio file, but get this error. The DeepSpeech I installed is up to date:
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
So is the github documentation under "transcribe an audio file" out of date?
https://github.com/mozilla/DeepSpeech

**Comment by rhamnett** [comment]
Scorer was introduced in 0.7 you have 0.6.1

**Comment by jeremydvoss** [comment]
Oh I see. Is there a way to install the newest version of deepspeech then? "pip3 install deepspeech" seems to install 0.6.1

**Comment by jwheat** [comment]
Yep, try `pip3 install deepspeech==0.7`

**Comment by jeremydvoss** [comment]
Thanks! It works if specify
```
$ pip3 install deepspeech==0.7.0a2
```
... or rather I'm onto some other bug. Thanks for your help!
