### ISSUE TITLE
Unicode Decode Error while running shell run file

### ISSUE THREAD

**Issue by rohitk9** [mozilla/DeepSpeech#2748]
```
(venv) Rohits-MacBook-Pro:DeepSpeech rohitkhandelwal$ ./bin/run-test1.sh
+ '[' '!' -f DeepSpeech.py ']'
+ python -u DeepSpeech.py --train_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training:Testing_data/train/train.csv --dev_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training:Testing_data/dev/dev.csv --test_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training:Testing_data/test/test.csv
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1151, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1520, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1331: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 973, in <module>
    absl.app.run(main)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 946, in main
    train()
  File "DeepSpeech.py", line 442, in train
    train_phase=True)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/util/feeding.py", line 110, in create_dataset
    df = read_csvs(csvs)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/util/feeding.py", line 24, in read_csvs
    file = pandas.read_csv(csv, encoding='utf-8')
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 973, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1158, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1520, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1331: invalid continuation byte
```

Hello, I have all the characters that I've used in csv file in my alphabet.txt but now I am coming across this error. My alphabet.txt is in plaintext utf-8 type. Can anyone please let me know where am I going wrong here ?

**Comment by lissyx** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1331: invalid continuation byte

@rohitk9 It looks like your UTF-8 data is somehow invalid, and you have the position here.

> ./bin/run-test1.sh

This is not our code, please share more context.

**Comment by rohitk9** [comment]
I have made my own runnable script labeled run-test1.sh with the code as below :

#!/bin/sh
set -xe
if [ ! -f DeepSpeech.py ]; then
    echo "Please make sure you run this from DeepSpeech's top level directory."
    exit 1
fi;

python -u DeepSpeech.py \
  --train_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training_Testing_data/train/train.csv \
  --dev_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training_Testing_data/dev/dev.csv \
  --test_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training_Testing_data/test/test.csv \
  --train_batch_size 80 \
  --dev_batch_size 80 \
  --test_batch_size 40 \
  --n_hidden 375 \
  --epochs 33 \
  --dropout_rate 0.22 \
  --learning_rate 0.00095 \
  --report_count 100 \
  --export_dir /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/data/rohit/results/model_export/ \
  --checkpoint_dir /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/data/rohit/results/checkout/ \
  --alphabet_config_path /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/data/alphabet.txt \
  --lm_binary_path /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/models/lm.binary \
  --lm_trie_path /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/models/trie \
  "$@"


Also, I am using digits 0 to 9 in my alphabet.txt file. Is this why this error is arising ?

**Comment by rohitk9** [comment]
alphabet.txt looks somewhat like this :

#Each line in this file represents the Unicode codepoint (UTF-8 encoded)
#associated with a numeric label.
#A line that starts with # is a comment. You can escape it with \# if you wish
#to use '#' as a label.
 
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
1
2
3
4
5
6
7
8
9
0
.
,
%
'
#The last (non-comment) line needs to end with a newline.

**Comment by lissyx** [comment]
> Also, I am using digits 0 to 9 in my alphabet.txt file. Is this why this error is arising ?

The error explicitely mentions `read_csvs`, so you have something bogus in your dataset. You have the error, you have the data, we can't do anything about that.

**Comment by lissyx** [comment]
>   --train_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training_Testing_data/train/train.csv \
>   --dev_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training_Testing_data/dev/dev.csv \
>   --test_files /Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/ezDIdatabase/Training_Testing_data/test/test.csv \

Which dataset is this ?

**Comment by rohitk9** [comment]
> Which dataset is this ?

It's a medical dataset which I downloaded through the Ezdi website. I am trying to build a model for speech to text for medical terms.

**Comment by lissyx** [comment]
>   File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/util/feeding.py", line 24, in read_csvs
>     file = pandas.read_csv(csv, encoding='utf-8')

Can you look into `util/feeding.py` and print the `csv` value before `pandas.read_csv`, that will point your to the broken CSV file.

**Comment by lissyx** [comment]
> > File "/Users/rohitkhandelwal/PycharmProjects/SpeechTest/venv/DeepSpeech/util/feeding.py", line 24, in read_csvs
> > file = pandas.read_csv(csv, encoding='utf-8')
> 
> Can you look into `util/feeding.py` and print the `csv` value before `pandas.read_csv`, that will point your to the broken CSV file.

With the CSV file and
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1331: invalid continuation byte

You can find the broken part.

**Comment by lissyx** [comment]
> > Which dataset is this ?
> 
> It's a medical dataset which I downloaded through the Ezdi website. I am trying to build a model for speech to text for medical terms.

How was this imported ? How were those CSV produced ?

**Comment by rohitk9** [comment]
> How was this imported ?

It had to be unzipped and it had two parts to it. The transcripts and the audio files. I got them in the form to convert to CSV files.


> How were those CSV produced ?

I created a python program to convert the files into csv. The code is below : 

import glob as glob
import pandas as pd
import os

#Creating and storing list of wav files location in alphabetical orders wav_loc[]
wav_loc = glob.glob('/Users/rohitkhandelwal/Desktop/ezDI database/train/*.wav')
a = len(wav_loc)
print("Total wav files found : " + str(a))
wav_loc.sort()
print(wav_loc)


#Get filesize of .wav files
os.chdir('/Users/rohitkhandelwal/Desktop/ezDI database/train/')
wav_size = []
for file in wav_loc:
    wav_size.append(os.stat(file).st_size)
print(wav_size)


#Changing directory to train
os.chdir('/Users/rohitkhandelwal/Desktop/ezDI database/train/')

#Creating and storing names of text files in alphabetical order as txt_loc[]
txt_loc = glob.glob('*.txt')
b = len(txt_loc)
print("Total textfiles found : " + str(b))
txt_loc.sort()
print(txt_loc)


#Opening and reading textfiles. Storing in list trans[]
trans = []
for file in txt_loc:
    with open(file, 'r') as f:
        trans.append(f.read())
print(trans)

#Creating a dataframe of the three lists
df = pd.DataFrame({'wav_filename': wav_loc, 'wav_filesize': wav_size, 'transcript': trans})
print(df)

export_csv = df.to_csv(r'/Users/rohitkhandelwal/Desktop/ezDI database\new_train.csv', index=False)

**Comment by lissyx** [comment]
> I wrote a python code to convert the files into csv. The code is below :

So no validation at all, no conversion. That's really not a DeepSpeech level issue. Please look at other importers and inspire yours to properly perform CSV import and ensure UTF-8 is well-formed at that point.

Since this is obviously not a DeepSpeech bug, please reach for support on Discourse.

**Comment by lissyx** [comment]
@rohitk9 Plenty of importers to get inspiration from in https://github.com/mozilla/DeepSpeech/tree/master/bin
