### ISSUE TITLE
I ran model with audio file it gives me the corrrect output but with microphone the model is not giving the correct result.

### ISSUE THREAD

**Issue by Neel125** [mozilla/DeepSpeech#2750]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 1.15
- **TensorFlow version (use command below)**: 1.15
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by lissyx** [comment]
This is not a bug, please reach for support on Discourse and share more informations on your problem.
