### ISSUE TITLE
Audio streaming not giving the correct output

### ISSUE THREAD

**Issue by Neel125** [mozilla/DeepSpeech#2751]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 1.15
- **TensorFlow version (use command below)**:1.15
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

I try audio file for speech to text it give me the correct result but when i gave the audio stream from mic it did not give me the correct result. So, what is the issue ? 
what kind of microphone i have to use  and any preprocess the audio ? 
if preprocess audio then what should i do?

**Comment by lissyx** [comment]
> I try audio file for speech to text it give me the correct result but when i gave the audio stream from mic it did not give me the correct result. So, what is the issue ?
> what kind of microphone i have to use and any preprocess the audio ?
> if preprocess audio then what should i do?

This is your second bug opened in a few minutes.
You obviously don't consider it is worth reading the issue template as well as reading my answers.

Why do you open issues if you don't read the replies we give you ?

Let me copy it another time:
> For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

**Comment by lissyx** [comment]
> I try audio file for speech to text it give me the correct result but when i gave the audio stream from mic it did not give me the correct result. So, what is the issue ?
> what kind of microphone i have to use and any preprocess the audio ?
> if preprocess audio then what should i do?

There are already dozen and dozen of discussions covering that on Discourse. What you provide is absolutely useless for us to help.
