### ISSUE TITLE
undefined symbol: _intel_fast_memcpy

### ISSUE THREAD

**Issue by PedroDKE** [mozilla/DeepSpeech#2752]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: LINUX, CENTOS 7.7 (cluster)
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: requirements.txt
- **TensorFlow version (use command below)**: 1.15.0 GPU
- **Python version**: 3.6.8
- **CUDA/cuDNN version**: 10/7.4

When running the ./bin/run-ldc93s1.sh file on a cluster i get the following output:

```
(myenv) user@login18-g-1:~/opensource/DeepSpeech[303]$ ./bin/run-ldc93s1.sh
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/home/user/.local/share/deepspeech/ldc93s1
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python -u DeepSpeech.py --noshow_progressbar --train_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --test_batch_size 1 --n_hidden 100 --epochs 200 --checkpoint_dir /home/user/.local/share/deepspeech/ldc93s1
Traceback (most recent call last):
  File "DeepSpeech.py", line 22, in <module>
    from evaluate import evaluate
  File "/institution/rz/cluster/home/user/opensource/DeepSpeech/evaluate.py", line 22, in <module>
    from util.feeding import create_dataset
  File "/institution/rz/cluster/home/user/opensource/DeepSpeech/util/feeding.py", line 18, in <module>
    from util.audio import read_frames_from_file, vad_split, DEFAULT_FORMAT
  File "/institution/rz/cluster/home/user/opensource/DeepSpeech/util/audio.py", line 6, in <module>
    from webrtcvad import Vad
  File "/institution/rz/cluster/home/user/myenv/lib/python3.6/site-packages/webrtcvad.py", line 3, in <module>
    import _webrtcvad
ImportError: /institution/rz/cluster/home/user/myenv/lib/python3.6/site-packages/_webrtcvad.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcpy
```
A maybe related issue that i found was:

https://github.com/scikit-learn/scikit-learn/issues/4083

Here they propose to use ICC, but my cluster does not have ICC (as far as i know) any workaround,tips,...?
This might maybe also be related to the fact i was not able to execute the following line:
`sudo apt-get install python3-dev`

Thank you in advance

**Comment by lissyx** [comment]
> ```
> ImportError: /institution/rz/cluster/home/user/myenv/lib/python3.6/site-packages/_webrtcvad.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcpy
> ```

I'm sorry, but why do you file the issue here? It's a webrtcvad-level issue, it's not our code ...

**Comment by reuben** [comment]
> This might maybe also be related to the fact i was not able to execute the following line:
> `sudo apt-get install python3-dev`

What do you mean not able to execute? Your system does not offer a package with Python development headers?

**Comment by lissyx** [comment]
> > This might maybe also be related to the fact i was not able to execute the following line:
> > `sudo apt-get install python3-dev`
> 
> What do you mean not able to execute? Your system does not offer a package with Python development headers?

I don't think he has credentials to sudo.

**Comment by reuben** [comment]
We could make the `webrtcvad` dependency optional, as it's only required for `transcribe.py`.

**Comment by lissyx** [comment]
> We could make the `webrtcvad` dependency optional, as it's only required for `transcribe.py`.

That's not completely wrong. @PedroDKE Maybe you could send a PR that does the job described above?

**Comment by PedroDKE** [comment]
> > ```
> > ImportError: /institution/rz/cluster/home/user/myenv/lib/python3.6/site-packages/_webrtcvad.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcpy
> > ```
> 
> I'm sorry, but why do you file the issue here? It's a webrtcvad-level issue, it's not our code ...

in the hope to get more answers or ideas on what to do



> > This might maybe also be related to the fact i was not able to execute the following line:
> > `sudo apt-get install python3-dev`
> 
> What do you mean not able to execute? Your system does not offer a package with Python development headers?

like lissyx said, i dont have sudo rights

> > We could make the `webrtcvad` dependency optional, as it's only required for `transcribe.py`.
> 
> That's not completely wrong. @PedroDKE Maybe you could send a PR that does the job described above?

I'll look into it, but i have not been this far into the source code. 
Any idea if i have to make a new flag for this?

**Comment by reuben** [comment]
No new flags. Just move the import into the `vad_split` function.

**Comment by PedroDKE** [comment]
Okey, I've made a PR with the suggested change, it seems to have solved the issue! 
Thank you guys!
