### ISSUE TITLE
Electron v8.0.x is out

### ISSUE THREAD

**Issue by dsteinman** [mozilla/DeepSpeech#2759]
They've bumped the version of Electron yet again (8.0.1) and I'd like to try it out.  It looks like as before, the DeepSpeech node module will need to create the *electron-v8.0* directory in:

*deepspeech/lib/binding/v0.6.1/darwin-x64/*

```
Error: Cannot find module '/Users/dstein/dev/jaxcore/deepspeech-plugin/node_modules/deepspeech/lib/binding/v0.6.1/darwin-x64/electron-v8.0/deepspeech.node'
[1] Require stack:
[1] - /Users/dstein/dev/jaxcore/deepspeech-plugin/node_modules/deepspeech/index.js
[1] - /Users/dstein/dev/jaxcore/deepspeech-plugin/lib/deepspeech-process.js
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
[1]     at Module._load (internal/modules/cjs/loader.js:691:27)
[1]     at Module._load (electron/js2c/asar.js:717:26)
[1]     at Function.Module._load (electron/js2c/asar.js:717:26)
[1]     at Module.require (internal/modules/cjs/loader.js:853:19)
[1]     at require (internal/modules/cjs/helpers.js:74:18)
[1]     at Object.<anonymous> (/Users/dstein/dev/jaxcore/deepspeech-plugin/node_modules/deepspeech/index.js:17:17)
[1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[1]     at Module.load (internal/modules/cjs/loader.js:816:32) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/Users/dstein/dev/jaxcore/deepspeech-plugin/node_modules/deepspeech/index.js',
[1]     '/Users/dstein/dev/jaxcore/deepspeech-plugin/lib/deepspeech-process.js'
[1]   ]
[1] }
```

I tried updating the version of node-abi, but it's still resolving to a non-existent directory -- the same thing that happened in the other Electron versions.

I couldn't quite figure out how adjust the DeepSpeech scripts to do this upgrade myself.

**Comment by lissyx** [comment]
You should look into our shell scripts `taskcluster/tc-builds.sh`, there are make calls that you could look at to pass the correct variables

**Comment by lissyx** [comment]
Here https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-build-utils.sh#L176 if you do the make call with the proper electronjs version string.

You might run into issues with swig wrappers that are broken with newer v8, and node-gyp / node-pre-gyp might require updating as well. As for swig, please check our docs on master, we recently revamped the process to try and make it easier for you to rebuild, and we provide pre-built patched binaries of swig.

Try and dig into that and come back if needed, I'm not able to look closer at that before a few days, but I'd welcome patches if you can: at some point, if you are lucky, it's just about adding the new version to SUPPORTED_ELECTRONJS_VERSIONS, and a few copy / paste and adapt of yml tests manifests.

**Comment by lissyx** [comment]
@dsteinman Something like:
```
 make -C native_client/javascript \
      TFDIR=${DS_TFDIR} \
      NODE_ABI_TARGET=--target=8.0.1 \
      NODE_DIST_URL=--disturl=https://electronjs.org/headers \
      NODE_RUNTIME=--runtime=electron \
      clean node-wrapper npm-pack
```

**Comment by lissyx** [comment]
> @dsteinman Something like:
> 
> ```
>  make -C native_client/javascript \
>       TFDIR=${DS_TFDIR} \
>       NODE_ABI_TARGET=--target=8.0.1 \
>       NODE_DIST_URL=--disturl=https://electronjs.org/headers \
>       NODE_RUNTIME=--runtime=electron \
>       clean node-wrapper npm-pack
> ```

You'd need a `${DS_TFDIR}/bazel-bin/native_client/libdeepspeech.so` but you can build that manually by just re-using existing `.so`.

**Comment by dsteinman** [comment]
I'm not sure if I'll be able to figure this out on my own.  I don't think I even have swig installed correctly, I downloaded the binary from that taskcluster link, but I get these make errors.

```
swig -c++ -javascript -node deepspeech.i
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'javascript.swg'
deepspeech.i:2: Error: Unable to find 'typemaps.i'
make: *** [deepspeech_wrap.cxx] Error 1
```

**Comment by lissyx** [comment]
Ah yes, symlink the ds-swig as swig, and you have to set SWIG_LIB env var to the correct documented value.

**Comment by lissyx** [comment]
> I'm not sure if I'll be able to figure this out on my own. I don't think I even have swig installed correctly, I downloaded the binary from that taskcluster link, but I get these make errors.
> 
> ```
> swig -c++ -javascript -node deepspeech.i
> :1: Error: Unable to find 'swig.swg'
> :3: Error: Unable to find 'javascript.swg'
> deepspeech.i:2: Error: Unable to find 'typemaps.i'
> make: *** [deepspeech_wrap.cxx] Error 1
> ```

Good news, it seems you can get that to work easily:
```
$ SWIG_LIB=/home/alex/tmp/deepspeech/SWIG/install/share/swig/4.0.2 PATH=$HOME/tmp/deepspeech/SWIG/install/bin/:$HOME/node_modules/.bin/:$PATH make -C native_client/javascript/ NODE_ABI_TARGET=--target=8.0.1 NODE_DIST_URL=--disturl=https://electronjs.org/headers NODE_RUNTIME=--runtime=electron clean node-wrapper npm-pack 
```

**Comment by lissyx** [comment]
> I'm not sure if I'll be able to figure this out on my own. I don't think I even have swig installed correctly, I downloaded the binary from that taskcluster link, but I get these make errors.
> 
> ```
> swig -c++ -javascript -node deepspeech.i
> :1: Error: Unable to find 'swig.swg'
> :3: Error: Unable to find 'javascript.swg'
> deepspeech.i:2: Error: Unable to find 'typemaps.i'
> make: *** [deepspeech_wrap.cxx] Error 1
> ```

There should be enough doc in https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.rst#install-nodejs--electronjs-bindings but it's very fresh, so please advise if it needs improvements.

FTR, I just tested and it looks like it should build / run easily, so I can make a PR for that later today, but that won't cover 0.6.1, you will have anyway to do it on your side. We are trying to make that as easy as we can, please mind the gap between the code and the binary.

**Comment by lissyx** [comment]
@dsteinman Support for next versions is here, do not hesitate to ask / give feedback or improvements on the docs if you still have troubles getting that with 0.6.1, because it should be transparent once you have `swig` setup and you pass the proper arguments. Again, the doc is quite new so it might need refinments, don't hesitate to ping us.

**Comment by dsteinman** [comment]
Great, thank-you @lissyx.  I'll probably end up waiting until the release is made to try it out.

**Comment by lissyx** [comment]
I've triggered a new alpha, so you should be able to use it. This is not compatible with 0.6.1 model but re-exporting should be fine.
