### ISSUE TITLE
Build Error: native_client:generate_trie not present in native_client/BUILD

### ISSUE THREAD

**Issue by MtotheKay** [mozilla/DeepSpeech#2761]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
    NO

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    Ubuntu 18.04

- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
    Mozilla Fork (Downloaded on 15.02.20)

- **TensorFlow version (use command below)**:
- **Python version**: 
    2.7.17 / 3.6.9
- **Bazel version (if compiling from source)**:
    0.23.2
- **GCC/Compiler version (if compiling from source)**:
    -> CPU compile
- **CUDA/cuDNN version**:
    -> CPU compile
- **GPU model and memory**:
    -> CPU compile

- **Exact command to reproduce**:
`~/tensorflow$ bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie`

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

When trying to build the native client, the following error occurs:
```
ERROR: Skipping '//native_client:generate_trie': no such target '//native_client:generate_trie': target generate_trie' not declared in package 'native_client' defined by /home/<username>/tensorflow/native_client/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//native_client:generate_trie': target 'generate_trie' not declared in package 'native_client' defined by /home/<username>/tensorflow/native_client/BUILD
INFO: Elapsed time: 0.859s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Upon searching generate_trie in "native_client/BUILD" I could not find it.
Is the Build Command in [Native Client Readme](https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.rst) wrong?

**Comment by lissyx** [comment]
What version are you trying to build? On master we don't have generate trie anymore I think?

**Comment by MtotheKay** [comment]
VERSION says: 0.7.0-alpha.1

**Comment by lissyx** [comment]
> VERSION says: 0.7.0-alpha.1
> What would be the correct build command then?

Remove the generate trie that's all. I think we forgot to update the docs cc @reuben

**Comment by lissyx** [comment]
Check under `data/lm` there should be a `generate_scorer` script, the new file format bundles the trie inside so no need for the separate tool now.

**Comment by reuben** [comment]
Note that you have to regenerate the lm.binary file with the `-v` option to not include the vocabulary.

**Comment by reuben** [comment]
But if you're just building from source to test code changes, just remove the `//native_client:generate_trie` target from the build command.

**Comment by MtotheKay** [comment]
Thanks, the error changed:

I think there is someting else missing?
`bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so`

```
ERROR: /home/<username>/tensorflow/native_client/BUILD:91:1: no such target '//tensorflow/core/kernels:deepspeech_cwise_ops': target 'deepspeech_cwise_ops' not declared in package 'tensorflow/core/kernels' defined by /home/<username>/tensorflow/tensorflow/core/kernels/BUILD and referenced by '//native_client:libdeepspeech.so'
ERROR: Analysis of target '//native_client:libdeepspeech.so' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.595s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by lissyx** [comment]
> Thanks, the error changed:
> 
> I think there is someting else missing?
> `bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so`
> 
> ```
> ERROR: /home/<username>/tensorflow/native_client/BUILD:91:1: no such target '//tensorflow/core/kernels:deepspeech_cwise_ops': target 'deepspeech_cwise_ops' not declared in package 'tensorflow/core/kernels' defined by /home/<username>/tensorflow/tensorflow/core/kernels/BUILD and referenced by '//native_client:libdeepspeech.so'
> ERROR: Analysis of target '//native_client:libdeepspeech.so' failed; build aborted: Analysis failed
> INFO: Elapsed time: 0.595s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
> ```
> 
> I checked deepspeech_cwise_ops is not present in tensorflow/core/kernels

Are you sure you are on the `r1.15` branch of our fork?

**Comment by MtotheKay** [comment]
@lissyx: I was using the master branch.
I will now use the r1.15 branch and update on the result.
