### ISSUE TITLE
Missed some words and got some extra words at begining and end while inference using v0.6.1

### ISSUE THREAD

**Issue by alamnasim** [mozilla/DeepSpeech#2769]
We trained model for our Hinglish dataset.
We try to infer prediction on DeepSpeech version 0.6.1.
OS: ubuntu 18.04.
Tensorflow: 1.14.0

We have total around 2300-2400 hrs of data in Hinglish language (80-85% Hindi and 15-20 % English).

Our training data audio is split into chunks of 1.5 sec to 10 sec.

DeepSpeech training command: 
**./DeepSpeech.py --train_files data/train.csv --dev_files data/dev.csv --test_files data/test.csv --alphabet_config_path data/alphabet.txt --checkpoint_dir ~/checkpoint_dir --epochs 20 --export_dir ~/export_dir --lm_binary_path data/lm.binary --lm_trie_path data/trie --report_count 10 --show_progressbar true --train_batch_size 48 --dev_batch_size 48 --test_batch_size 48 --learning_rate 0.0001 --dropout_rate 0.15 --n_hidden 2048 --audio_sample_rate 8000**

We do prediction on whole audio call and the chunks of the same audio calls (split on vad).

**Problems that We face:**
1. vad does not remove noise properly?
2. some new words like ok, haan, sir etc are added at the begining and end of the chunk predicted output.
3. some words are missing in between the chunks?
4. words are missing when inference on whole audio call but extra word append is not there in this case?

**Comment by reuben** [comment]
Use Discourse.
