### ISSUE TITLE
[Good First Bug] Implement an API to get textual descriptions of error codes

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2773]
It would be nice to have an API similar to [strerror](https://linux.die.net/man/3/strerror) to get textual descriptions of error codes so applications can show something meaningful to users in error messages.

This was already implemented ad-hoc in the .NET bindings, see here: https://github.com/mozilla/DeepSpeech/blob/0b82c751db58d9d2d90e861f9af04e671fd2ab41/native_client/dotnet/DeepSpeechClient/DeepSpeech.cs#L86-L125

Steps to fix this would be roughly:

Add a new API to `native_client/deepspeech.h`, something like:

```c
char* DS_ErrorCodeToErrorMessage(int aErrorCode);
```

And then in `native_client/deepspeech.cc`, implement the function by returning the appropriate error message. The strings can be static, inlined directly in the source code. The documentation for `DS_ErrorCodeToErrorMessage` should indicate that the returned pointers are read only and MUST not be deallocated or modified.

Feel free to ask any questions if any of this is confusing.

**Comment by reuben** [comment]
Next steps would then be to expose this API to our language bindings, as well as make use of it in the .NET binding instead of having its own list there.

**Comment by imskr** [comment]
I would like to work on this issue!

**Comment by lissyx** [comment]
> I would like to work on this issue!

You should have all the informations requires already here. Please feel free to ask for clarification if required.

**Comment by imskr** [comment]
Thank You @lissyx

**Comment by imskr** [comment]
@reuben @lissyx Shouldn't be the argument of function
 ```cpp
char* DS_ErrorCodeToErrorMessage(int aErrorCode); 
```
be 
 ```cpp
char* DS_ErrorCodeToErrorMessage(DeepSpeech_Error_Codes aErrorCode); 
```
As in `deepspeech.h`  error codes are in  `enum DeepSpeech_Error_Codes`

**Comment by reuben** [comment]
The C language standard does not guarantee the underlying size of an enum, so we could end up with nasty ABI compatibility issues due to compiler mismatches. `int` is safer in that regard.

**Comment by imskr** [comment]
Ok @reuben thanks.

**Comment by reuben** [comment]
The second part of this issue is making sure our bindings in the tree use the new API. There are four bindings in the three:

  - Python: [native_client/python](../tree/master/native_client/python)
  - JavaScript: [native_client/javascript](../tree/master/native_client/javascript)
  - .NET: [native_client/dotnet](../tree/master/native_client/dotnet)
  - Java: [native_client/java](../tree/master/native_client/java)

Here's a rough idea for how to do this for each one of them:

  - Python: in the object oriented wrapper classes ([code here](https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/__init__.py)), add checks around every fallible API call as well as using the message strings when raising an exception instead of using the numeric code. You'll also have to add the new function to the list [here](https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/impl.i#L77-L82) to make sure the strings are deallocated.
  - JavaScript: same as above. Wrapper classes are [here](https://github.com/mozilla/DeepSpeech/blob/master/native_client/javascript/index.js), list of functions that return newly allocated strings is [here](https://github.com/mozilla/DeepSpeech/blob/master/native_client/javascript/deepspeech.i#L34-L39).
  - .NET: already has its own handling, which was used as the source for the textual descriptions. Needs to be updated to use the new API. The new function needs to be added in [NativeImp.cs](https://github.com/mozilla/DeepSpeech/blob/master/native_client/dotnet/DeepSpeechClient/NativeImp.cs), and then it can be used from [DeepSpeech.EvaluateResultCode](https://github.com/mozilla/DeepSpeech/blob/a9e72eb1520a19457be967f38aec56480756185e/native_client/dotnet/DeepSpeechClient/DeepSpeech.cs#L86-L125).
  - Java: function has to be added to the list [here](https://github.com/mozilla/DeepSpeech/blob/a9e72eb1520a19457be967f38aec56480756185e/native_client/java/jni/deepspeech.i#L45-L47). Actually using it is part of a separate issue, #2701.

@imskr are you interested in also taking on this part?

**Comment by imskr** [comment]
Yes I would like to take this, thanks.

**Comment by imskr** [comment]
@reuben In python: Do I have to add all types of errors mentioned in API  in `__init__` function of both `Model` and `Stream` class [here](https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/__init__.py) ?

**Comment by reuben** [comment]
@imskr you don't need to duplicate the list of errors anywhere. Just make sure whenever we report errors, instead of just showing the error number we also include a textual description by calling the new function you added in #2794.

**Comment by imskr** [comment]
Should I remove the `raise` statement and add the `DS_ErrorCodeToErrorMessage` function [here](https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/__init__.py#L37-L39) ?
Having little confusion how do i use the `DS_ErrorCodeToErrorMessage` in `__init__.py` although i have added it in `impli.i` @reuben

**Comment by kdavis-mozilla** [comment]
@imskr You could, instead of throwing an exception with only the error code
```python
        status, impl = deepspeech.impl.CreateModel(model_path)
        if status != 0:
            raise RuntimeError("CreateModel failed with error code 0x{:X}".format(status))
```
throw an exception with the error code and textual description. Something like
```python
        status, impl = deepspeech.impl.CreateModel(model_path)
        if status != 0:
            status_message = deepspeech.impl.ErrorCodeToErrorMessage(status)
            raise RuntimeError("CreateModel failed with error message {} with error code 0x{:X}".format(status_message, status))
```

**Comment by imskr** [comment]
Ok, Thank You @kdavis-mozilla
