### ISSUE TITLE
HTTP Error 404 when running util/taskcluster.py

### ISSUE THREAD

**Issue by yinshengabc** [mozilla/DeepSpeech#2774]
![QQ图片20200220020247](https://user-images.githubusercontent.com/45324059/74912874-22556900-5385-11ea-9946-5a8eb20ae753.png)

The problem occurs when I want to switch to a stable branch, I also have tried version v0.2.0-alpha.6, but same problem occurs. Does this url work?

Thanks!

https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu/artifacts/public/native_client.tar.xz

**Comment by lissyx** [comment]
@yinshengabc Please avoid posting screenshot. `v0.4.1` release is not supported anymore and the artifact has expired, so you have to download from Github releases: https://github.com/mozilla/DeepSpeech/releases/v0.4.1

**Comment by yinshengabc** [comment]
> @yinshengabc Please avoid posting screenshot. `v0.4.1` release is not supported anymore and the artifact has expired, so you have to download from Github releases: https://github.com/mozilla/DeepSpeech/releases/v0.4.1

Thank you for your reply, also I noticed that the generate_trie file was removed, how can I do now to generate trie file and do the training?

**Comment by lissyx** [comment]
> > @yinshengabc Please avoid posting screenshot. `v0.4.1` release is not supported anymore and the artifact has expired, so you have to download from Github releases: https://github.com/mozilla/DeepSpeech/releases/v0.4.1
> 
> Thank you for your reply, also I noticed that the generate_trie file was removed, how can I do now to generate trie file and do the training?

`generate_trie` is still bundled in the `native_client.tar.xz`, so please have a look or give more context.

**Comment by yinshengabc** [comment]
But when I run this command, it doesn't shows the generate_trie.

ubuntu@ip-172-31-36-41:~/DeepSpeech$ python3 util/taskcluster.py --target native_client
Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.7.0-alpha.2.cpu/artifacts/public/native_client.tar.xz ...
Downloading: 100%

libdeepspeech.so
LICENSE
deepspeech
deepspeech.h
README.mozilla


> `generate_trie` is still bundled in the `native_client.tar.xz`, so please have a look or give more context.

**Comment by lissyx** [comment]
> But when I run this command, it doesn't shows the generate_trie.
> 
> ubuntu@ip-172-31-36-41:~/DeepSpeech$ python3 util/taskcluster.py --target native_client
> Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.7.0-alpha.2.cpu/artifacts/public/native_client.tar.xz ...
> Downloading: 100%
> 
> libdeepspeech.so
> LICENSE
> deepspeech
> deepspeech.h
> README.mozilla
> 
> > `generate_trie` is still bundled in the `native_client.tar.xz`, so please have a look or give more context.

Because if you look carefully to the result as well as the doc you will learn it defaults to downloading matching version with your DeepSpeech clone. I gave you the link to 0.4.1 as you asked, so I don't understand what's blocking now.

**Comment by lissyx** [comment]
With 0.7.0-alpha.2 we don't need `generate_trie`, so that's why it has been removed.
