### ISSUE TITLE
Train, validate, and test WER from log differ from doyouunderstand.me graph

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#278]
In the log we had the following results:

- Training WER 0.438057
- Validation WER 0.516958
- Test WER 0.566854

On the doyouunderstand.me graph we had for the same run

- Training WER 0.5170
- Validation WER 0.4381
- Test WER 0.5669

It appears as if the training and validation results are flipped.

**Comment by lissyx** [comment]
Looking at logs/hyper.js:
```
    "results": {
        "duration": 63511, 
        "last_train_wer": 0.4380570407343708, 
        "last_validation_wer": 0.5169577052062913, 
        "test_wer": 0.5668536301874748
    }
```

It looks like the values are matching the log ones.

**Comment by kdavis-mozilla** [comment]
Maybe only the mouse overs are wrong?

**Comment by kdavis-mozilla** [comment]
Oh I see you found the typo.

**Comment by lissyx** [comment]
I hand-fixed the current website. Next update should be done with the fix from master merged on wer-tracking, otherwise it would look like it regressed.
