### ISSUE TITLE
API changes in v0.7.0-alpha2

### ISSUE THREAD

**Issue by est31** [mozilla/DeepSpeech#2786]
In updating the Rust bindings to v0.7.0-alpha2 release, I found the following two (minor) issues with the API:

* The `DS_GetModelBeamWidth` function could take a const pointer instead of a mutable one ( `DS_GetModelSampleRate` has this issue too btw)
* It would be prefferable if the `DS_Version` function did not allocate. There is no need for it, if it's documented that the result doesn't have to and must not be freed.

Overall, the changes were really good, especially that the beam width is now stored with the model. This makes usage much easier. Thanks for doing this!

**Comment by reuben** [comment]
> The DS_GetModelBeamWidth function could take a const pointer instead of a mutable one ( DS_GetModelSampleRate has this issue too btw)

ModelState is an opaque pointer so I don't understand what difference that makes in practice. Communicating to the API consumer that the function is read only? Isn't it enough to document it?

> It would be prefferable if the DS_Version function did not allocate. There is no need for it, if it's documented that the result doesn't have to and must not be freed.

I was concerned about wrong `free()` usage but also users trying to modify read only memory and causing weird crashes. I guess we can try no allocation in 0.7.0 and see if any reports pop up. @lissyx thoughts?

> Overall, the changes were really good, especially that the beam width is now stored with the model. This makes usage much easier. Thanks for doing this!

Thanks for updating the Rust bindings \o/

**Comment by est31** [comment]
> ModelState is an opaque pointer so I don't understand what difference that makes in practice. Communicating to the API consumer that the function is read only? Isn't it enough to document it?

Hmm it seems I can make non-mutable wrapper functions so it seems there is no immediate need for me to have const wrappers.

> I was concerned about wrong free() usage but also users trying to modify read only memory and causing weird crashes.

You have a point, the new API is probably more obvious. It's not really important, both choices are okay.

**Comment by lissyx** [comment]
> > The DS_GetModelBeamWidth function could take a const pointer instead of a mutable one ( DS_GetModelSampleRate has this issue too btw)
> 
> ModelState is an opaque pointer so I don't understand what difference that makes in practice. Communicating to the API consumer that the function is read only? Isn't it enough to document it?

We all know people don't read the documentation. Passing that information to the compiler could be useful, indeed.



> I was concerned about wrong `free()` usage but also users trying to modify read only memory and causing weird crashes. I guess we can try no allocation in 0.7.0 and see if any reports pop up. @lissyx thoughts?

:+1:

**Comment by kdavis-mozilla** [comment]
> ModelState is an opaque pointer so I don't understand what difference that makes in practice. Communicating to the API consumer that the function is read only?

I'd guess this is the major win, communicating to the API consumer that this function does not modify ModelState. People tend to ignore documentation, but they can't ignore the compiler.

> It would be preferable if the DS_Version function did not allocate. There is no need for it, if it's documented that the result doesn't have to and must not be freed.

I agree with this. It seems like you could just return a const pointer to a string literal. 

However, this brings up another problem in that all the other strings are allocated and this "version string" would be the only one that is _not_ allocated, which will likely cause people (who generally do not read the documentation) to try and deallocate it and cause a crash.

So maybe it's better just to keep DS_Version as it is.

**Comment by reuben** [comment]
@kdavis-mozilla @lissyx Just to be clear, my point about ModelState being an opaque pointer is that it is not possible to "surprise" API users. Applications can't see the contents of a ModelState, so even if we changed the contents, they wouldn't be able to see it. There's no added type safety, taking a const pointer there would literally be just documentation for humans.

**Comment by lissyx** [comment]
> There's no added type safety, taking a const pointer there would literally be just documentation for humans.

Which is still good :)



> Applications can't see the contents of a ModelState, so even if we changed the contents, they wouldn't be able to see it.

Enforcing `const` could always help catching broken code trying to write into our data?

**Comment by reuben** [comment]
Adding `const` to the parameter is a relaxation of the constraints from the user's perspective. It would help catch *our* broken code, but not broken user code. User code is already prevented from writing into our data anyway because it's an opaque pointer so there's nothing to write to. I'll add it since it doesn't hurt anyway.

**Comment by est31** [comment]
Thanks for the changes!
