### ISSUE TITLE
cuDNN dependency is incorrect?

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2788]
I was successfully training on Ubuntu 18.04 with DeepSpeech 0.6.1 and upgraded to 0.7.0 alpha 2. According to Using.rst, the CUDA and cuDNN dependencies are identical to that of 0.6 - CUDA 10.0 and cuDNN 7.5 - so it should have worked without any changes.

However, I got the error message ‘Fail to find the dnn implementation’. Despite repeated uninstalls and reinstalls of NVIDIA drivers, CUDA and cuDNN, I wasn’t able to make the error go away.

On a whim, I tried installing cuDNN 7.6 and now everything works perfectly. So it seems like the documentation is incorrect?

**Comment by lissyx** [comment]
I'm using 7.5 successfully. The source of truth we are referring to should be tensorflow website anyway.

**Comment by dabinat** [comment]
For some reason there's no mention of recommended versions for 1.15 [here](https://www.tensorflow.org/install/source#linux). But if you assume nothing changed between 1.14 and 2.0, it should be cuDNN 7.4, not 7.5. So the dependencies for 0.6 were already contrary to what was recommended on the Tensorflow site.

**Comment by lissyx** [comment]
> So the dependencies for 0.6 were already contrary to what was recommended on the Tensorflow site.

Exactly for that reason that we wanted to avoid replicating TensorFlow website. I still think 0.6 dep change was a result of the same feedback as yours.

**Comment by reuben** [comment]
https://github.com/mozilla/tensorflow/blob/r1.15/configure.py#L36-L39

**Comment by reuben** [comment]
Sorry, it's late, that's not what I meant to send. I've been following the Ubuntu instructions here[0] which also say 7.6. Maybe it changed at some point between 1.15.0 and today? TensorFlow 1.15 was released full of documentation issues so it's hard to tell.

https://web.archive.org/web/20191223214017/https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_10
[0] https://web.archive.org/web/20191223214017/https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_10

**Comment by lissyx** [comment]
> For some reason there's no mention of recommended versions for 1.15 [here](https://www.tensorflow.org/install/source#linux). But if you assume nothing changed between 1.14 and 2.0, it should be cuDNN 7.4, not 7.5. So the dependencies for 0.6 were already contrary to what was recommended on the Tensorflow site.

And yet, NVIDIA's docker is on 7.6 as well: https://gitlab.com/nvidia/container-images/cuda/-/blob/ubuntu18.04/10.0/runtime/cudnn7/Dockerfile

@dabinat I guess it's such a mess we might as well update the docs to 7.5 ?

**Comment by victornoriega** [comment]
I also tried to use tensorflow 1.15.0 with cudNN 7.5 and had some errors until I updated to a cudnn 7.6.x.

**Comment by lissyx** [comment]
@victornoriega @dabinat Remember that PRs are welcome :)

**Comment by victornoriega** [comment]
@lissyx It's hard to conclude anything. While the Tensorflow docs says almost nothing about TF 1.15 compatibility with CUDA and cudNN, there are people like you that have no problems with 7.5, and other people like me and @dabinat  who had to upgrade cudnn to use it.

**Comment by lissyx** [comment]
> there are people like you that have no problems with 7.5,

I thought I was on 7.5, but it looks like I got tricked.
