### ISSUE TITLE
Uplift new examples contributed to 0.6 to master with new API changes

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2791]
A couple of new 0.6.x examples were contributed to the examples repo. We should update them to the new API after 0.7.0 is released.

**Comment by imskr** [comment]
I would like to work on this!

**Comment by reuben** [comment]
@imskr thanks for the interest! I guess in order to avoid duplicated work, it's better to wait until 0.7 is out before working on this. Then we'll make a new branch on the examples repository for 0.7 and this work can happen there. I'll ping you here once that happens :)

**Comment by imskr** [comment]
Ok thank you @reuben

**Comment by reuben** [comment]
@imskr sorry, I completely forgot about this issue and just did the uplift myself during the 0.7.0 release :(
