### ISSUE TITLE
Optimizing GPU Training Time

### ISSUE THREAD

**Issue by stuclearmob** [mozilla/DeepSpeech#2795]
Hello,

I'm trying to train a model with the Spanish dataset from Commonvoice. I have around 100 hours of training data. I'm not sure if my gpu is working properly. It's only using around 100mb of memory. Should it be using more?

```bash
ubuntu@ip-172-31-30-60:~/OwnLanguage/DeepSpeech$ nvidia-smi
Wed Feb 26 12:35:41 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   52C    P0    29W /  70W |    109MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     26673      C   python3                                       99MiB |
+-----------------------------------------------------------------------------+
```

 - **Have I written custom code **: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: tensorflow-gpu
- **TensorFlow version (use command below)**: v1.15.0-rc3-22-g590d6ee 1.15.0
- **Python version**: 3.6
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: T4 NVIDIA
- **Exact command to reproduce**:  
`sudo nohup python3 DeepSpeech.py --train_files Spanska/clips/train.csv --dev_files Spanska/clips/dev.csv --test_files Spanska/clips/test.csv --automatic_mixed_precision=True`

I've read before that it should take around one hour per epoch if done correctly. This is it so far:

```bash
Epoch 0 |   Training | Elapsed Time: 0:46:22 | Steps: 192 | Loss: 87.379530
WARNING: sample rate of file "/home/ubuntu/OwnLanguage/DeepSpeech/Spanska/clips/common_voice_es_19815707.wav" ( 16000 ) does not match FLAGS.audio_sample_rate. This can lead to incorrect results.
```

**Comment by kdavis-mozilla** [comment]
The default train, dev, and test batch sizes are all 1, see [flags.py#L73](https://github.com/mozilla/DeepSpeech/blob/master/util/flags.py#L73). As you don't explicitly set the train, dev, or test batch sizes, they are all 1.

To better utilize your GPU your batch size should be made larger than 1. How much larger is dependent on your data and your GPU's memory.

**Comment by lissyx** [comment]
> **GPU model and memory**: T4 NVIDIA

This is not hardware we tested. https://www.nvidia.com/en-us/data-center/tesla-t4/
Can you please share more logs to make sure that TensorFlow GPU CUDA does support this ?

Also, please refrain from using `sudo`.

**Comment by Juanvulcano** [comment]
Is there any specific logs you want to test?

**Comment by lissyx** [comment]
@stuclearmob Could you please answer our questions regarding batch size ?

**Comment by lissyx** [comment]
@stuclearmob Any news ?

**Comment by lissyx** [comment]
Closing for lack of actionability and reporter not giving feedback.
