### ISSUE TITLE
WARNING for audio_sample_rate[Portuguese trainning]

### ISSUE THREAD

**Issue by YagoRegis** [mozilla/DeepSpeech#2798]
Hello, 
I am trainning the portuguese dataset from mozilla common voice using the DeepSpeech.

I imported the files using the import_cv2.p(transform to wav, and create the dev, train and test csv)

When I started the trainning, I faced the Warning(for basically all files):

**WARNING: sample rate of file "/home/deep_train/portugues/clips/common_voice_pt_19278633.wav" ( 16000 ) does not match FLAGS.audio_sample_rate. This can lead to incorrect results**.

Digging a bit in the code I found out that audio_sample_rate from FLAGS.audio_sample_rate is 16000 and from my .wavs too and the if statement below is warning in the screen(from util/feeding.py:
```
def samples_to_mfccs(samples, sample_rate, train_phase=False, wav_filename=None):
	if train_phase and sample_rate != FLAGS.audio_sample_rate:
        tf.print('WARNING: sample rate of file', wav_filename, '(', sample_rate, ') does not match FLAGS.audio_sample_rate. This can lead to incorrect results.')
```

sample_rate is of type Tensor
FLAGS.audio_sample_rate is of type int
Both values are 16000

Plus, I start the train with this command:
**./DeepSpeech.py --train_files /home/deep_train/portugues/clips/train.csv --dev_files /home/deep_train/portugues/clips/dev.csv --test_files /home/deep_train/portugues/clips/test.csv --export_tflite --export_dir /home/deep_train/portugues --alphabet_config_path /home/deep_train/portugues/alphabet.txt**

My specs:
Debian Buster
Python 3.7.3
TensorFlow 1.15
No gpu(YET)

How can I fix this warning?
Thanks in advice.

**Comment by ykhemanth** [comment]
The same problem I encountered while training with my own dataset with indian english accent

**Comment by ykhemanth** [comment]
I encountered with the same problem while training with indian english accent dataset.

**Comment by Juanvulcano** [comment]
Same problem in Spanish dataset.

**Comment by kdavis-mozilla** [comment]
Looks like is might be related to the new code [feeding.py#L34](https://github.com/mozilla/DeepSpeech/blob/46e7993075f5ad64fde193465c05dab3b405a776/util/feeding.py#L34) comparing a zero dimensional Tensor of type int32 with an int.

**Comment by lissyx** [comment]
> Looks like is might be related to the new code [feeding.py#L34](https://github.com/mozilla/DeepSpeech/blob/46e7993075f5ad64fde193465c05dab3b405a776/util/feeding.py#L34) comparing a zero dimensional Tensor of type int32 with an int.

Indeed, and even in CI we see it. I'm wondering if @reuben and myself did not got tricked when we made / reviewed this pathc.

**Comment by lissyx** [comment]
@ykhemanth @Juanvulcano @YagoRegis Can you give a try to #2802 ? Especially check on your side if it does not slow down training.
