### ISSUE TITLE
Testing trained model with evaluation.py

### ISSUE THREAD

**Issue by Juanvulcano** [mozilla/DeepSpeech#2800]
This in an update from https://github.com/mozilla/DeepSpeech/issues/2799.
I setup CUDA correctly but it is still failing with the same error code.
How can I see the WER of my model? 

```
(tensorflow_p36) ubuntu@ip-172-31-30-60:~/OwnLanguage/DeepSpeech$ python3 evaluate.py --test_files Spanska/clips/test.csv
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/__init__.py:1467: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.

Traceback (most recent call last):
  File "evaluate.py", line 156, in <module>
    absl.app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "evaluate.py", line 147, in main
    samples = evaluate(FLAGS.test_files.split(','), create_model)
  File "evaluate.py", line 49, in evaluate
    FLAGS.scorer_path, Config.alphabet)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ds_ctcdecoder/__init__.py", line 36, in __init__
    raise ValueError('Scorer initialization failed with error code {}'.format(err))
ValueError: Scorer initialization failed with error code 1
```

**Comment by kdavis-mozilla** [comment]
Point evaluate.py to your, for example, your checkpoint using the `--checkpoint_dir` flag.

**Comment by lissyx** [comment]
> This in an update from #2799.
> I setup CUDA correctly but it is still failing with the same error code.
> How can I see the WER of my model?

Insisting is not going to get your more support, just make people loose time and don't want to help you.

**Comment by lissyx** [comment]
Please reach for support on Discourse.

**Comment by lissyx** [comment]
@Juanvulcano Please join efforts and rely on https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/Dockerfile.train as other communities does (https://github.com/MozillaItalia/DeepSpeech-Italian-Model), this will avoid you loosing time on that.

**Comment by dabinat** [comment]
The reason for this error is that you haven’t downloaded the scorer. You need to install git-lfs and do git-lfs pull to download it.

**Comment by Juanvulcano** [comment]
> > This in an update from #2799.
> > I setup CUDA correctly but it is still failing with the same error code.
> > How can I see the WER of my model?
> 
> Insisting is not going to get your more support, just make people loose time and don't want to help you.

How is it insisting if the issue was closed?
I can understand that insisting is annoying if the issue is open but I followed what you said and the issue was not solved. Not too sure if people check the closed issues. 

Thanks for assisting guys.

**Comment by lissyx** [comment]
> > > This in an update from #2799.
> > > I setup CUDA correctly but it is still failing with the same error code.
> > > How can I see the WER of my model?
> > 
> > 
> > Insisting is not going to get your more support, just make people loose time and don't want to help you.
> 
> How is it insisting if the issue was closed?

It was closed because it was not a bug. You obviously did not read the documentation nor the issue template for opening an issue without properly setting up CUDA as documented. As @dabinat mentionned, `git-lfs` is also covered.

> I can understand that insisting is annoying if the issue is open but I followed what you said and the issue was not solved. Not too sure if people check the closed issues.

Until proven otherwise, this is not a bug. Please discuss on Discourse.

> 
> Thanks for assisting guys.
