### ISSUE TITLE
generate_trie file missing in 070-alpha2

### ISSUE THREAD

**Issue by wahyubram82** [mozilla/DeepSpeech#2803]
I try to build Indonesian SR with Deepspeech and follow the instruction in https://tilmankamp.github.io/FOSDEM2018/
but i'm stuck in generate_trie. error, file no found. then I realized, hours after, there is no generate_trie file in this version.

but until now, no change in instruction with the newest version.

can I get some information about it? or...this problem just about forgot to put it ..and the solution only download to the old version...? cheers?

**Comment by lissyx** [comment]
This is not an error, `generate_trie` is not needed anymore and docs were updated in #2761

**Comment by lissyx** [comment]
@wahyubram82 Please look at `data/lm/generate_scorer.py`
