### ISSUE TITLE
Generalize `validate_label`

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#2804]
We have hard-coded english-specific `validate_label`. We should have a simpler way than forking and replacing it for locales to ensure consistency accross datasets: some importers are for multiple languages, and thus it is harder to implement importer-level consistency of the sentences.

**Comment by kdavis-mozilla** [comment]
For the [CorporaCreator](https://github.com/mozilla/CorporaCreator) I did something like this
```python
    def _preprocessor_wrapper(self, client_id, sentence, up_votes, down_votes):
        preprocessor = getattr(
            preprocessors, self.locale.replace("-", "")
        )  # Get locale specific preprocessor
        sentence = preprocessor(client_id, sentence)
        if None == sentence or not sentence.strip():
            up_votes = 0
            down_votes = 2
        return pd.Series([sentence, up_votes, down_votes])
```
where the ```preprocessors``` module has a preprocessor for each locale.

**Comment by reuben** [comment]
I think if we do this we should have a more flexible API than just `validate_label`, so new importers are able to use building blocks from previous importers, even if their requirements aren't the same. For example the "text cleaners" stuff in TTS where you can pass a list of cleaners, which are small passes over data that do a single transform, and they're applied in order.

**Comment by lissyx** [comment]
> I think if we do this we should have a more flexible API than just `validate_label`, so new importers are able to use building blocks from previous importers, even if their requirements aren't the same. For example the "text cleaners" stuff in TTS where you can pass a list of cleaners, which are small passes over data that do a single transform, and they're applied in order.

I think importers should stay dumb as they are, and that the consistency problem should be addressed at locale-level, without forking DeepSpeech repo: a new-locale specific `validate_label` that would be defined and living in locale's repo.

**Comment by lissyx** [comment]
Which is more or less close to @kdavis-mozilla solution.

**Comment by reuben** [comment]
Ah, OK. The first comment talked about importers so I thought that's what this was about. Ignore my comment!

**Comment by lissyx** [comment]
> Ah, OK. The first comment talked about importers so I thought that's what this was about. Ignore my comment!

My goal is to ensure people try and stay as close as possible of our upstream. Having to fork for some kind of feature like that makes it easier for people to think "we already have a fork, we can hack this and that" and we end up with bugs from unknown states.
