### ISSUE TITLE
ValueError: Scorer initialization failed with error code 1

### ISSUE THREAD

**Issue by zhangpengk** [mozilla/DeepSpeech#2805]
@Reuben, Hi  Mr Reuben, im  sorry  to disturb you ,i am trying to train my own english audio model, when i run  : "bashbin/run-ldc93s1.sh",  but one problem  have bothered for a long time :" ValueError: Scorer initialization failed with error code 1 ", im sure to follow this tutorial(https://github.com/mozilla/DeepSpeech/blob/master/doc/TRAINING.rst#training-your-own-model), i have tried every ｍethod to resolve this issue ,　but never solved. details as following:
ValueError: Scorer initialization failed with error code 1

The stack info：
(deepspeech-venv) zhangp@zhangp:~/tmp/deepspeech-venv/DeepSpeech$ bin/run-ldc93s1.sh
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/zhangp/.local/share/deepspeech/ldc93s1
+ export CUDA_VISIBLE_DEVICES=0
+ python -u DeepSpeech.py --noshow_progressbar --train_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --test_batch_size 1 --n_hidden 100 --epochs 200 --checkpoint_dir /home/zhangp/.local/share/deepspeech/ldc93s1
I Could not find best validating checkpoint.
I Could not find most recent checkpoint.
I Initializing all variables.
I STARTING Optimization
I Training epoch 0...
I Finished training epoch 0 - loss: 367.066681
I Training epoch 1...
I Finished training epoch 1 - loss: 335.958954
I Training epoch 2...
I Finished training epoch 2 - loss: 305.713379
I Training epoch 3...
I Finished training epoch 3 - loss: 276.875092
......
......
I Training epoch 197...
I Finished training epoch 197 - loss: 10.998775
I Training epoch 198...
I Finished training epoch 198 - loss: 12.610215
I Training epoch 199...
I Finished training epoch 199 - loss: 12.527173
I FINISHED optimization in 0:00:20.383416
Traceback (most recent call last):
  File "DeepSpeech.py", line 900, in <module>
    absl.app.run(main)
  File "/home/zhangp/tmp/deepspeech-venv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/zhangp/tmp/deepspeech-venv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 877, in main
    test()
  File "DeepSpeech.py", line 635, in test
    samples = evaluate(FLAGS.test_files.split(','), create_model)
  File "/home/zhangp/tmp/deepspeech-venv/DeepSpeech/evaluate.py", line 49, in evaluate
    FLAGS.scorer_path, Config.alphabet)
  File "/home/zhangp/tmp/deepspeech-venv/lib/python3.6/site-packages/ds_ctcdecoder/__init__.py", line 36, in __init__
    raise ValueError('Scorer initialization failed with error code {}'.format(err))
ValueError: Scorer initialization failed with error code 1

I will  appreciate it grately if you help me resolve this err,thanks!

**Comment by lissyx** [comment]
@zhangpengk You already received help on Discourse for that. Please act and void opening issues when there is no bug.
