### ISSUE TITLE
More descriptive error message when scorer isn't installed

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2807]
This is starting to become a frequent question. If the scorer has not been downloaded via git lfs, the error message `ValueError: Scorer initialization failed with error code 1` will appear. This is not a very helpful error message and I feel that a better message that actually describes the problem and how to solve it would be better and prevent this question being asked so many times.

This also only occurs at the end of training, so you have to wait for training to complete before realizing you haven't installed the scorer. Perhaps if the user has specified the test pass it should check the scorer is correct at startup?

**Comment by lissyx** [comment]
> Perhaps if the user has specified the test pass it should check the scorer is correct at startup?

Might be a good idea.


> This also only occurs at the end of training, so you have to wait for training to complete before realizing you haven't installed the scorer.

Also, since there are checkpoints, is this really a big deal ? It would restart from it, wouldn't it ?

**Comment by lissyx** [comment]
This could be a good first bug: I guess a way to do that would be to just early-initialize a `Scorer` and leave it to exception system if it's not being provided proper arguments.

**Comment by dabinat** [comment]
> Also, since there are checkpoints, is this really a big deal ? It would restart from it, wouldn't it ?

Yeah, it’s not a huge problem, but it can be frustrating if you start it training, go away for a while, come back and discover that a bunch of time was wasted because it stopped due to an error. It’s especially bad if you’re training on the cloud and paying by the hour.

**Comment by lissyx** [comment]
> It’s especially bad if you’re training on the cloud and paying by the hour.

Hm, that's not a use-case we experiment a lot, but maybe people are more affected than us for this specific need.

@dabinat do you want / have the time to send a patch ?

**Comment by lissyx** [comment]
@dabinat ping?
