### ISSUE TITLE
Documentation example broken: unrecognized arguments: --scorer

### ISSUE THREAD

**Issue by ayushkovskiy** [mozilla/DeepSpeech#2810]
Hi! I'm running the README example and it fails:
```
$ deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --scorer deepspeech-0.6.1-models/kenlm.scorer --audio audio/2830-3980-0043.wav
usage: deepspeech [-h] --model MODEL [--lm [LM]] [--trie [TRIE]] --audio AUDIO
                  [--beam_width BEAM_WIDTH] [--lm_alpha LM_ALPHA]
                  [--lm_beta LM_BETA] [--version] [--extended] [--json]
deepspeech: error: unrecognized arguments: --scorer deepspeech-0.6.1-models/kenlm.scorer

```

**Comment by lissyx** [comment]
`--scorer` is post 0.6.1.

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/blob/v0.6.1/README.rst doc does not mention `--scorer`

**Comment by lissyx** [comment]
There is no bug here, just read the appropriate documentation.

**Comment by ayushkovskiy** [comment]
Please, update the main README then: https://github.com/mozilla/DeepSpeech

**Comment by lissyx** [comment]
> Please, update the main README then: https://github.com/mozilla/DeepSpeech

The master README refers to master branch, and it is accurate.

**Comment by smeylan** [comment]
Sorry for being dense, but I am running into the same confusion with the README. Steps to recreate:
1) clone master
2) follow instructions in readme in master
3) receive above error message

It seems that the master documentation says to install with pip, which then installs something other than the master branch? Launching python in my venv I see:

```Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepspeech
>>> deepspeech.printVersions()
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe```

**Comment by lissyx** [comment]
> Sorry for being dense, but I am running into the same confusion with the README. Steps to recreate:
> 
>     1. clone master
> 
>     2. follow instructions in readme in master
> 
>     3. receive above error message
> 
> 
> It seems that the master documentation says to install with pip, which then installs something other than the master branch? Launching python in my venv I see:
> 
> ```python
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import deepspeech
> >>> deepspeech.printVersions()
> TensorFlow: v1.14.0-21-ge77504a
> DeepSpeech: v0.6.1-0-g3df20fe```
> ```

Well this is default pip behavior, it installs stable builds by default.

**Comment by rotdrop** [comment]
But the README states "it is for the master branch" **and** at the same time suggests to install via pip, which just does **not** install the master branch. So can you please update the README for the master branch to state how to install the master branch? Kind thanks.

**Comment by reuben** [comment]
master is the development branch, it has no stability guarantees, no pre-built binaries, and no pre-trained models. If you want to try our pre-built binaries, or use our pre-trained model or checkpoint, use a stable release: https://github.com/mozilla/DeepSpeech/releases/latest

**Comment by reuben** [comment]
We're in the process of changing our release process so that the default branch shown on GitHub is the most recent stable release (instead of master) to avoid this confusion.
