### ISSUE TITLE
SPANISH LANGUAGE TRAINING PROCEDURE

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [mozilla/DeepSpeech#2811]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.10
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 3.7.5
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: 9.2.1
- **CUDA/cuDNN version**: None
- **GPU model and memory**: No GPU, planning to use GCP instance
- **Exact command to reproduce**: Training for Spanish dataset

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

Hi, I have a pretty decent sized dataset for Spanish, about 350,000 clips (5-10 seconds each). I want to go ahead and train the DeepSpeech Repo. I have been sifting through Issues for ours but I have not been able to find any concrete step-by-step procedure on how to proceed with the training for a language other than English. Could anyone please outline the steps I would need to follow to train DeepSpeech for Spanish. Thanks!

**Comment by lissyx** [comment]
> Hi, I have a pretty decent sized dataset for Spanish, about 350,000 clips (5-10 seconds each). I want to go ahead and train the DeepSpeech Repo. I have been sifting through Issues for ours but I have not been able to find any concrete step-by-step procedure on how to proceed with the training for a language other than English. Could anyone please outline the steps I would need to follow to train DeepSpeech for Spanish. Thanks!

What is unclear with ? https://github.com/mozilla/DeepSpeech/blob/master/doc/TRAINING.rst

**Comment by lissyx** [comment]
BTW this is not a bug, please reach for support on Discourse. You can also find inspiration in https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/Dockerfile.train and https://github.com/MozillaItalia/DeepSpeech-Italian-Model
