### ISSUE TITLE
How to use tflite on arm64

### ISSUE THREAD

**Issue by liziru** [mozilla/DeepSpeech#2822]
Description: I want to run "deepspeech" c++ binary on arm64 board using tflite because other model costs much time. I have tried v0.6.1 and v0.7.0.a2 loading tflite ,but failed. 

Question: How can i use tflite on arm64? I will appreciate it if anyone can help me.

**Comment by liziru** [comment]
i have checked many issues but i didnot get answer.  For example, 

> @isjosan We have started experimenting with TFLite lib on other platforms, but it's still experimental. For example, you can find them on this link for your platform: https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.4/tflite

i cannot find anything through [https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.4/tflite](url).

**Comment by lissyx** [comment]
This is not a bug. Please use Discourse for support.

**Comment by lissyx** [comment]
> Question: How can i use tflite on arm64? I will appreciate it if anyone can help me.

On ARM64, TFLite is the default engine.

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/pull/2677

**Comment by lissyx** [comment]
For 0.6.1, default runtime on ARM64 was NOT TFLite, but ARMv7 one was already TFLite.

**Comment by lissyx** [comment]
> i have checked many issues but i didnot get answer. For example,
> 
> > @isjosan We have started experimenting with TFLite lib on other platforms, but it's still experimental. For example, you can find them on this link for your platform: https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.4/tflite
> 
> i cannot find anything through [https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.4/tflite](url).

This link is broken because TaskCluster infrastructure has been migrated.

**Comment by lissyx** [comment]
@liziru Now if you look at the releases pages on Github, you can see we also have them: https://github.com/mozilla/DeepSpeech/releases

**Comment by liziru** [comment]
Thank you very much. It is very embarrassing that i cannot use tflite with v0.6.1 and cannot use v0.7.0 with no pre-trained model on arm64.  I plan to cross-compile c++ binary for v0.6.1 to support tflite runtime  on arm64. Will it work?

**Comment by liziru** [comment]
> @liziru Now if you look at the releases pages on Github, you can see we also have them: https://github.com/mozilla/DeepSpeech/releases

Thank you very much. It is very embarrassing that i cannot use tflite with v0.6.1 and cannot use v0.7.0 with no pre-trained model on arm64. I plan to cross-compile c++ binary for v0.6.1 to support tflite runtime on arm64. Will it work?

**Comment by lissyx** [comment]
> > @liziru Now if you look at the releases pages on Github, you can see we also have them: https://github.com/mozilla/DeepSpeech/releases
> 
> Thank you very much. It is very embarrassing that i cannot use tflite with v0.6.1 and cannot use v0.7.0 with no pre-trained model on arm64. I plan to cross-compile c++ binary for v0.6.1 to support tflite runtime on arm64. Will it work?

Or just pick one of the 0.7 alpha that was produced **after** I merged the switch to ARM64 to default to TFLite and before we changed the model ?

**Comment by lissyx** [comment]
Like the PR I linked earlier was merged on january 17h so 0.7.0a0 includes it and it's still compatible with 0.6.1 model: https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.0-alpha.0



> I plan to cross-compile c++ binary for v0.6.1 to support tflite runtime on arm64. Will it work?

Again, cross-compiling is documented but you would need to adapt the setup to target TFLite runtime. Please try and rely on 0.7.0a0 instead.

**Comment by liziru** [comment]
> Like the PR I linked earlier was merged on january 17h so 0.7.0a0 includes it and it's still compatible with 0.6.1 model: https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.0-alpha.0
> 
> > I plan to cross-compile c++ binary for v0.6.1 to support tflite runtime on arm64. Will it work?
> 
> Again, cross-compiling is documented but you would need to adapt the setup to target TFLite runtime. Please try and rely on 0.7.0a0 instead.

well, I see. Thanks for your help.

**Comment by liziru** [comment]
> Like the PR I linked earlier was merged on january 17h so 0.7.0a0 includes it and it's still compatible with 0.6.1 model: https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.0-alpha.0
> 
> > I plan to cross-compile c++ binary for v0.6.1 to support tflite runtime on arm64. Will it work?
> 
> Again, cross-compiling is documented but you would need to adapt the setup to target TFLite runtime. Please try and rely on 0.7.0a0 instead.

I tried 0.7.0a0 with v0.6.1 pbmm model and v0.6.1 tflite model. The test shows v0.7.0a0 doesnot support v0.6.1 tflite model. However, i remember that you told me on arm64 TFLite is the default engine besides v0.6.1 of arm64.

**Comment by liziru** [comment]
Besides, when will you release v0.7.0 pre-trained model?

**Comment by nshmyrev** [comment]
@liziru did you succeed? same problem.
