### ISSUE TITLE
Cannot find v0.7.0-alpha.2 pre-trained model

### ISSUE THREAD

**Issue by liziru** [mozilla/DeepSpeech#2823]
Description: I intended to use the newest v0.7.0-alpha.2 client, but i cannot find the compatible model. I cannot inference from the newest client using v0.6.1 pre-trained model because of incompatiable problems.

Question: How can i find v0.7.0-alpha.2 pre-trained model? I will appreciate it for any help.

**Comment by reuben** [comment]
Alpha versions don't have models. The 0.7.0 model with be released with the 0.7.0 release.

**Comment by liziru** [comment]
> Alpha versions don't have models. The 0.7.0 model with be released with the 0.7.0 release.

but i cannot find 0.7.0 model on [https://github.com/mozilla/DeepSpeech/releases](url) with 0.7.0 release. I can only find 0.6.1 model.

**Comment by liziru** [comment]
![image](https://user-images.githubusercontent.com/34911790/76686338-9cf86800-6655-11ea-9e5f-0d296efcdef5.png)

**Comment by lissyx** [comment]
> ![image](https://user-images.githubusercontent.com/34911790/76686338-9cf86800-6655-11ea-9e5f-0d296efcdef5.png)

Could you please read the replies we are prividing ?

**Comment by lissyx** [comment]
> > Alpha versions don't have models. The 0.7.0 model with be released with the 0.7.0 release.
> 
> but i cannot find 0.7.0 model on [https://github.com/mozilla/DeepSpeech/releases](url) with 0.7.0 release. I can only find 0.6.1 model.

As @reuben said we don't yet have 0.7 compatible models.

**Comment by liziru** [comment]
I see. I am sorry for my poor english. Thank you very much.

**Comment by lissyx** [comment]
> I see. I am sorry for my poor english. Thank you very much.

If my Chinese was as good as your English, I'd be proud.

**Comment by liziru** [comment]
haha, I can teach you chinese if you are interested.

**Comment by liziru** [comment]
> > I see. I am sorry for my poor english. Thank you very much.
> 
> If my Chinese was as good as your English, I'd be proud.

haha, I can teach you chinese if you are interested.

**Comment by liziru** [comment]
@reuben i read your report [https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/](url) about "DeepSpeech v0.6 with TensorFlow Lite runs faster than real time on a single core of a Raspberry Pi 4", which confuses me a lot. Raspberry Pi 4 is arm64 and for 0.6.1, default runtime on ARM64 was NOT TFLite, but ARMv7 one was already TFLite. Can you tell me some details about your test? I will appreciate it for any help.

**Comment by lissyx** [comment]
> @reuben i read your report [https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/](url) about "DeepSpeech v0.6 with TensorFlow Lite runs faster than real time on a single core of a Raspberry Pi 4", which confuses me a lot. Raspberry Pi 4 is arm64 and for 0.6.1, default runtime on ARM64 was NOT TFLite, but ARMv7 one was already TFLite. Can you tell me some details about your test? I will appreciate it for any help.

RPi4 is ARM64 but the binaries we produce, as documented, are made to be compatible with RPi3 and RPi4 **and** to run on Raspbian, which is NOT **ARM64**. Hence why we changed the default runtime to TFLite on ARMv7 much before changing it on ARM64.

**Comment by liziru** [comment]
> > @reuben i read your report [https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/](url) about "DeepSpeech v0.6 with TensorFlow Lite runs faster than real time on a single core of a Raspberry Pi 4", which confuses me a lot. Raspberry Pi 4 is arm64 and for 0.6.1, default runtime on ARM64 was NOT TFLite, but ARMv7 one was already TFLite. Can you tell me some details about your test? I will appreciate it for any help.
> 
> RPi4 is ARM64 but the binaries we produce, as documented, are made to be compatible with RPi3 and RPi4 **and** to run on Raspbian, which is NOT **ARM64**. Hence why we changed the default runtime to TFLite on ARMv7 much before changing it on ARM64.

Thank you, I see. I run RPI3 native client on arm64 successfully, but it didnot run faster than real time on a single core of arm64 board. It costs 11 seconds when processing 2.48 second audio. Why did this happen?

**Comment by kdavis-mozilla** [comment]
RPi4 is faster than RPI3.

**Comment by liziru** [comment]
> RPi4 is faster than RPI3.

ok, but my device is nanopi-neo2 that is arm64 and core is arm a53. RPI4 core is arm a72.  Maybe that's why  it didnot run faster than real time on a single core.

**Comment by lissyx** [comment]
> > RPi4 is faster than RPI3.
> 
> ok, but my device is nanopi-neo2 that is arm64 and core is arm a53. RPI4 core is arm a72. Maybe that's why it didnot run faster than real time on a single core.

Again, we documented on Github performances comparisions on several boards. ARMv7 vs ARM64 was not showing any impactful difference.

RPi4 is much faster than RPi3 as said, and that's why it is able to cope with realtime on our default model.

**Comment by liziru** [comment]
> > > RPi4 is faster than RPI3.
> > 
> > 
> > ok, but my device is nanopi-neo2 that is arm64 and core is arm a53. RPI4 core is arm a72. Maybe that's why it didnot run faster than real time on a single core.
> 
> Again, we documented on Github performances comparisions on several boards. ARMv7 vs ARM64 was not showing any impactful difference.
> 
> RPi4 is much faster than RPi3 as said, and that's why it is able to cope with realtime on our default model.

Got it. Thank you very much.
