### ISSUE TITLE
Problem with tsv to csv conversion for zh-HK tsv files

### ISSUE THREAD

**Issue by cheahheng** [mozilla/DeepSpeech#2827]
I'm using Ubuntu 18, 64-bit to run deepspeech and have downloaded the zh-HK wavefiles from cv.

i did the (deepspeech-train-venv) ~/DeepSpeech$ bin/import_cv2.py data/cv/zh-HK

it converted mp3 to wav without a problem and when converting tsv to csv, there's a problem for all the csv files.

The problem is all the csv files are empty....

**Comment by cheahheng** [comment]
The downloaded tsv files are attached here
[zh-HK_tsv.zip](https://github.com/mozilla/DeepSpeech/files/4346691/zh-HK_tsv.zip)

**Comment by lissyx** [comment]
@cheahheng Please share logs.

**Comment by cheahheng** [comment]
(deepspeech-train-venv) chlinux@ubuntu:~/DeepSpeech$ bin/import_cv2.py --filter_alphabet data/alphabet.txt data/cv/zh-HK
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/train.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/train.csv
Importing mp3 files...
Progress |#############################################################################################################################################################                    |  88% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/train.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 27 samples.
Skipped 27 samples that failed on transcript validation.
Final amount of imported audio: 0:02:01.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/test.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/test.csv
Importing mp3 files...
Progress |                                                                                                                                                                                 | N/A% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/test.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 14 samples.
Skipped 14 samples that failed on transcript validation.
Final amount of imported audio: 0:01:18.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/dev.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/dev.csv
Importing mp3 files...
Progress |                                                                                                                                                                                 | N/A% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/dev.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 5 samples.
Skipped 5 samples that failed on transcript validation.
Final amount of imported audio: 0:00:35.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/validated.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/validated.csv
Importing mp3 files...
Progress |############################################################################################                                                                                     |  52% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/validated.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 46 samples.
Skipped 46 samples that failed on transcript validation.
Final amount of imported audio: 0:03:55.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/other.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/other.csv
Importing mp3 files...
Progress |###############################################################################################################################################################################  |  99% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/other.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 407 samples.
Skipped 407 samples that failed on transcript validation.
Final amount of imported audio: 0:39:22.
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
(deepspeech-train-venv) chlinux@ubuntu:~/DeepSpeech$

**Comment by cheahheng** [comment]
(deepspeech-train-venv) chlinux@ubuntu:~/DeepSpeech$ bin/import_cv2.py --filter_alphabet data/alphabet.txt data/cv/zh-HK
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/train.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/train.csv
Importing mp3 files...
Progress |#############################################################################################################################################################                    |  88% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/train.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 27 samples.
Skipped 27 samples that failed on transcript validation.
Final amount of imported audio: 0:02:01.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/test.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/test.csv
Importing mp3 files...
Progress |                                                                                                                                                                                 | N/A% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/test.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 14 samples.
Skipped 14 samples that failed on transcript validation.
Final amount of imported audio: 0:01:18.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/dev.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/dev.csv
Importing mp3 files...
Progress |                                                                                                                                                                                 | N/A% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/dev.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 5 samples.
Skipped 5 samples that failed on transcript validation.
Final amount of imported audio: 0:00:35.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/validated.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/validated.csv
Importing mp3 files...
Progress |############################################################################################                                                                                     |  52% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/validated.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 46 samples.
Skipped 46 samples that failed on transcript validation.
Final amount of imported audio: 0:03:55.
Loading TSV file:  /home/chlinux/DeepSpeech/data/cv/zh-HK/other.tsv
Saving new DeepSpeech-formatted CSV file to:  data/cv/zh-HK/clips/other.csv
Importing mp3 files...
Progress |###############################################################################################################################################################################  |  99% completedWriting CSV file for DeepSpeech.py as:  data/cv/zh-HK/clips/other.csv
Progress |#                                                                                                                                                                                | 100% completed
Imported 407 samples.
Skipped 407 samples that failed on transcript validation.
Final amount of imported audio: 0:39:22.
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
Progress |#################################################################################################################################################################################| 100% completed
(deepspeech-train-venv) chlinux@ubuntu:~/DeepSpeech$

**Comment by cheahheng** [comment]
@lissyx 
[logs.txt](https://github.com/mozilla/DeepSpeech/files/4347884/logs.txt)

**Comment by lissyx** [comment]
> @lissyx
> [logs.txt](https://github.com/mozilla/DeepSpeech/files/4347884/logs.txt)

So this is not the same execution as what you reported at first. Here there's an extra `--filter-alphabet`. Please be consistent. Can you extract a small subset that reproduces ?

**Comment by cheahheng** [comment]
sorry, the logs.txt is the one with the issue, tsv when converted to csv, there's no data in the csv file..

**Comment by lissyx** [comment]
> sorry, the logs.txt is the one with the issue, tsv when converted to csv, there's no data in the csv file..

Have you tried without filter alphabet ? What alphabet did you use ?

**Comment by cheahheng** [comment]
I just tried without filter alphabet and it works, the first time it doesn't, but it works now....thanks and sorry for the trouble...

**Comment by lissyx** [comment]
> I just tried without filter alphabet and it works, the first time it doesn't, but it works now....thanks and sorry for the trouble...

Thanks, so there is no issue here? Let's close.
