### ISSUE TITLE
Preprocessing of .wav

### ISSUE THREAD

**Issue by narendraprasath** [mozilla/DeepSpeech#2828]
I have audio file which has 8kz sample rate and single channel. I converted to 16kz and used deepspeech 0.6.1 model, it producing bad transcription. I have doubt in following aspects,

- Does converting 8kz to 16kz sample rate is good or bad?
- What are best technique to remove background noise and enhance human voice in audio file?

Does any technique needs to apply wav file to get better result in deepspeech.

This is not issue in deepspeech but here I am asking some technique to apply to get better results.

Thanks in advance.

**Comment by lissyx** [comment]
This is not a bug, please reach for support on Discourse.
