### ISSUE TITLE
Cannot feed value of shape (3,) for Tensor 'layer_6/bias/Initializer/zeros:0', which has shape '(255,)'

### ISSUE THREAD

**Issue by cheahheng** [mozilla/DeepSpeech#2829]
Hi, attached is my log. I'm using Ubuntu 18 and running deepspeech to train a zh-HK model. All my audio files and tsv files downloaded from cv is processed by import_cv2.py and i used the util/check_characters.py and added all characters to alpabet.txt, however, I still face the error as shown in my logs.txt
[logs.txt](https://github.com/mozilla/DeepSpeech/files/4348652/logs.txt)

**Comment by lissyx** [comment]
> Hi, attached is my log. I'm using Ubuntu 18 and running deepspeech to train a zh-HK model. All my audio files and tsv files downloaded from cv is processed by import_cv2.py and i used the util/check_characters.py and added all characters to alpabet.txt, however, I still face the error as shown in my logs.txt
> [logs.txt](https://github.com/mozilla/DeepSpeech/files/4348652/logs.txt)

I don't see your command line pointing to a new alphabet file.

**Comment by cheahheng** [comment]
> > Hi, attached is my log. I'm using Ubuntu 18 and running deepspeech to train a zh-HK model. All my audio files and tsv files downloaded from cv is processed by import_cv2.py and i used the util/check_characters.py and added all characters to alpabet.txt, however, I still face the error as shown in my logs.txt
> > [logs.txt](https://github.com/mozilla/DeepSpeech/files/4348652/logs.txt)
> 
> I don't see your command line pointing to a new alphabet file.

I've ran this again with --alphabet_config_path with logs as attached. Same problem...Attached also is the alphabet.txt that I used

[logs2.txt](https://github.com/mozilla/DeepSpeech/files/4348823/logs2.txt)

[alphabet.txt](https://github.com/mozilla/DeepSpeech/files/4348782/alphabet.txt)

**Comment by lissyx** [comment]
> > > Hi, attached is my log. I'm using Ubuntu 18 and running deepspeech to train a zh-HK model. All my audio files and tsv files downloaded from cv is processed by import_cv2.py and i used the util/check_characters.py and added all characters to alpabet.txt, however, I still face the error as shown in my logs.txt
> > > [logs.txt](https://github.com/mozilla/DeepSpeech/files/4348652/logs.txt)
> > 
> > 
> > I don't see your command line pointing to a new alphabet file.
> 
> I've ran this again with --alphabet_config_path with logs as attached. Same problem...Attached also is the alphabet.txt that I used
> 
> [logs2.txt](https://github.com/mozilla/DeepSpeech/files/4348823/logs2.txt)
> 
> [alphabet.txt](https://github.com/mozilla/DeepSpeech/files/4348782/alphabet.txt)

```
I Loading most recent checkpoint from /home/chlinux/.local/share/deepspeech/checkpoints/train-0
```
Can you cleanup broken checkpoints please ?

**Comment by lissyx** [comment]
@cheahheng Ping ?

**Comment by cheahheng** [comment]
Hi I manage to resolve this and have successfully build my own kenlm.scorer from scratch. There are few things that needs to be done apart from following the documentations and readme files. It's tricky but I have done it.

**Comment by lissyx** [comment]
>  There are few things that needs to be done apart from following the documentations and readme files.

Could you please file bugs / explains what is tricky to you ? We can't improve the project with that kind of feedback @cheahheng.
