### ISSUE TITLE
In Memory Caching never happens

### ISSUE THREAD

**Issue by mychiux413** [mozilla/DeepSpeech#2831]
https://github.com/mozilla/DeepSpeech/blob/29a2ac37f001e2b37a720d5b8da4a64b4aa384d6/DeepSpeech.py#L424-L427

The `FLAG.feature_cache` says "If empty, caching will be done in memory...", but if we set the argument as empty: '', the cache will never happen, because when `enable_cache = '' and True`, enable_cache is `''`, so the `enable_cache`(empty string) will always be equivalent to False, we can try it with python:
```
feature_cache = '' 
do_cache_dataset = True 
in_memory_condition = feature_cache and do_cache_dataset 
print('in_memory_condition is "{}"'.format(in_memory_condition))
# in_memory_condition is ""

if in_memory_condition:
    print("do in memory cache")
else:
    print("do others")
# do others
```

**Comment by reuben** [comment]
> The `FLAG.feature_cache` says "If empty, caching will be done in memory..."

It doesn't:

https://github.com/mozilla/DeepSpeech/blob/ff9a720764cc848132a42cf006bdd591357d0282/util/flags.py#L19
