### ISSUE TITLE
label index for another language

### ISSUE THREAD

**Issue by qute012** [mozilla/DeepSpeech#2832]
Hello. I'm newbie.
I have question. When i don't use "\s" second index 1 instead of the last index, it is different loss.
Does The index on the label affects the model's predictions?

**Comment by lissyx** [comment]
> Hello. I'm newbie.
> I have question.

Being a newbie does not makes you unable to read and understand. Questions goes to Discourse.

**Comment by qute012** [comment]
Thank you to reply.
That's right , but i'm not totally newbie. I understand almost.
I collect character set in transcripts for making char2id and id2char.
When i use "\s" for different index almost the foremost index 2 and the last index. It seems to differ loss. So i asked.

**Comment by lissyx** [comment]
> Thank you to reply.
> That's right , but i'm not totally newbie. I understand almost.

Then why do you keep insisting reaching for support here instead of Discourse?

**Comment by qute012** [comment]
I'm sorry sir.
