### ISSUE TITLE
Typescript Type Definitions in DefinitelyTyped

### ISSUE THREAD

**Issue by piraka9011** [mozilla/DeepSpeech#2841]
# Feature Request

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 10.15
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Upstream
- **TensorFlow version (use command below)**: 1.14
- **Python version**: 3.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

I have added types for the DeepSpeech module v0.6.0 to [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped).
If I could have a maintainer review my PR there to verify I covered all the Node.js bindings that would be appreciated (DefinitelyTyped/DefinitelyTyped#43321).
If the maintainers prefer a PR against this repo with the types, that is also something I am open to doing.

**Comment by lissyx** [comment]
> I have added types for the DeepSpeech module v0.6.0 to [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped).

Could you please give some context ?

**Comment by lissyx** [comment]
>  If the maintainers prefer a PR against this repo with the types, that is also something I am open to doing.

Could you also explain more what are the requirements ?
Having some DeepSpeech-stuff in some third-party repo is not a good idea: we loose track of it, it will be outdated very quickly, etc.

**Comment by piraka9011** [comment]
> Could you please give some context ?

Sure, the DeepSpeech node package currently does not have any type definitions for TypeScript. 
Having a [type decleration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) enables developers to use typescript instead of pure JS modules.

I wrote the type definitions and submitted to them to the `DefinetelyTyped` repo so that they could be installed using `npm install @types/deepspeech`.

The types could also be generated using the [`dts-gen`](https://github.com/Microsoft/dts-gen) package.

I'm not sure how you bundle your JS client to npm but if you give me some context there, I can probably just contribute the type definitions back here (and maybe add a step to the packaging process to produce the types if you have such a process).

**Comment by lissyx** [comment]
> > 
> 
> Sure, the DeepSpeech node package currently does not have any type definitions for TypeScript.
> Having a [type decleration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) enables developers to use typescript instead of pure JS modules.

Right, but that means we also advertise support for TypeScript, so we need proper CI to cover that. Would you be willing to help there?



> I wrote the type definitions and submitted to them to the `DefinetelyTyped` repo so that they could be installed using `npm install @types/deepspeech`.
> 
> The types could also be generated using the [`dts-gen`](https://github.com/Microsoft/dts-gen) package.

What's the different between hand-written and `dts-gen` ?



> I'm not sure how you bundle your JS client to npm but if you give me some context there, I can probably just contribute the type definitions back here (and maybe add a step to the packaging process to produce the types if you have such a process).

Everything to produce the NPM package is documented, have you had a look at that ? The `native_client/javascript/Makefile` should be mostly enough to grasp it, but if you have more precise questions, please feel free to ask.

**Comment by piraka9011** [comment]
> Right, but that means we also advertise support for TypeScript, so we need proper CI to cover that. Would you be willing to help there?

It sounds like this is adding a step to `npm-pack` in the `Makefile` where `dts-gen` is run to add the types automatically. The build docs are clear and I've compiled DS before. Any nuances I should be aware of though?

I have written some type tests so that should also help.
Is there anything else needed for CI?

> What's the different between hand-written and `dts-gen` ?

Automation :) That and probably documentation (but the documentation in the Node package should suffice).

**Comment by lissyx** [comment]
> It sounds like this is adding a step to `npm-pack` in the `Makefile` where `dts-gen` is run to add the types automatically. The build docs are clear and I've compiled DS before. Any nuances I should be aware of though?

Do you have some patch ? That might be the easiest way to know for sure. But from your description, it might be just that (and maybe the nodejs deps ?)



> I have written some type tests so that should also help.
> Is there anything else needed for CI?

It might be a bit convoluted to add CI, but you can try by looking at the existing NodeJS / ElectronJS tests files: `.yml` under `taskcluster/` as well as `tc-node-tests.sh` there.

Worst case, if you have basics of tests we can build on top of them.

**Comment by lissyx** [comment]
To summarize, if you can prepare CI integration it'd be awesome, but don't block yourself on that. For several reasons, we can't easily open TaskCluster CI to anybody, so it's still not super trivial to hack around.

**Comment by lissyx** [comment]
@piraka9011 Gentle ping ? If you want, just share us basics of your patch and I'll finish the integration and you can review it ?

**Comment by lissyx** [comment]
It could be nice if we can have that on 0.7.0 release.

**Comment by piraka9011** [comment]
@lissyx I added `dts-gen` to `npm pack` in the `Makefile`. See #2870.

Let me know what other changes are necessary or feel free to cherrypick.

**Comment by lissyx** [comment]
> @lissyx I added `dts-gen` to `npm pack` in the `Makefile`. See #2870.
> 
> Let me know what other changes are necessary or feel free to cherrypick.

I see you opened that as a WIP, is it because you are unsure or there are missing steps you are working on ?

**Comment by lissyx** [comment]
@piraka9011 Also, how can we test the typescript generated bits ? Do you have code to share for that ?

**Comment by piraka9011** [comment]
> I see you opened that as a WIP, is it because you are unsure or there are missing steps you are working on ?

Unsure if there's anything else related to the build I need to update.

> Also, how can we test the typescript generated bits ? Do you have code to share for that?

Types are automatically generated and tests are usually run (at least for the `DefintelyTyped` repo) by running `ts-lint` (or a and verifying that the types are valid.

An example of a simple file to run for typechecking is [here](https://github.com/piraka9011/DefinitelyTyped/blob/217f243dcc8169e1abad43713800b4952c995f84/types/deepspeech/deepspeech-tests.ts).

This the [commit](https://github.com/piraka9011/DefinitelyTyped/commit/217f243dcc8169e1abad43713800b4952c995f84) with all the changes.

**Comment by lissyx** [comment]
> This is the [commit](https://github.com/piraka9011/DefinitelyTyped/commit/217f243dcc8169e1abad43713800b4952c995f84) I was going to submit to `DefintelyTyped` with all the changes.

Shouldn't it just be the PR we need in DeepSpeech repo, in fact ? As @reuben mentionned on Matrix, it seems un-natural to run `dts-gen` during CI itself.

**Comment by lissyx** [comment]
@piraka9011 Sorry for the multiple back/forth, but the more I read this, the more I think it's actually just the PR you were submitting to `DefinitelyTyped` that we need here, with proprer doc on how to re-generate the bindings ?

**Comment by piraka9011** [comment]
Regenerating the bindings are done with `dts-gen`. The reason I suggested it be automated with CI is that if there are any changes to the API, then `dts-gen` would automatically update the type declarations.

I can however just submit the `index.d.ts` type file in `native_client/javascript` if that's  what you prefer. The README.md in `native_client` points to the toplevel README. Would you prefer I add inline comments, or update the readme on how to regenerate the type defintions.

**Comment by lissyx** [comment]
> The reason I suggested it be automated with CI is that if there are any changes to the DeepSpeech public API, then `dts-gen` would automatically update the type declarations.

My understanding is that `dts-gen` generates template information, such as what SWIG uses in its `.i` wrapper. This is indeed not built on CI, but checked in.



> Regenerating the bindings are done with `dts-gen`.

Except this requires the module to be installed. There's some chicken/egg problem here, so it needs to be clearly outlined in the doc.



> or update the `native_client/javascript` README on how to regenerate the type definitions.

This, please.

**Comment by lissyx** [comment]
> Types are automatically generated and tests are usually run (at least for the `DefintelyTyped` repo) by running `ts-lint` (or a and verifying that the types are valid.

Sorry @piraka9011, I still have several questions

This is only going to check types validity. Shouldn't we also **run** actual code making use of the typescript'd module ?

How should we package things ? I don't see anything specific about that in your PR, is bundling those files together enough ?

How is it being used ?

**Comment by lissyx** [comment]
> An example of a simple file to run for typechecking is [here](https://github.com/piraka9011/DefinitelyTyped/blob/217f243dcc8169e1abad43713800b4952c995f84/types/deepspeech/deepspeech-tests.ts).

Shouldn't that be part of your PR ? And is it the file I should use to run `ts-lint` ?

**Comment by lissyx** [comment]
> Types are automatically generated and tests are usually run (at least for the `DefintelyTyped` repo) by running `ts-lint` (or a and verifying that the types are valid.
> 
> An example of a simple file to run for typechecking is [here](https://github.com/piraka9011/DefinitelyTyped/blob/217f243dcc8169e1abad43713800b4952c995f84/types/deepspeech/deepspeech-tests.ts).

Ok so `ts-lint is another NPM package to install but the binary is `tslint`. And then even running that fails:
```
$ PATH=$HOME/node_modules/.bin/:$PATH tslint deepspeech-tests.ts 
No valid rules have been specified
```

**Comment by lissyx** [comment]
@piraka9011 I'm really sorry, but could you please share complete running example + instructions ? We know nothing about TypeScript, and I've already tried for several hours to get something running but I failed to find any useful and clear documentation. I'm not sure we have all the pieces already for DeepSpeech, so it's hard to know if we are missing things that are obvious to people used to TypeScript, if I'm misunderstanding the docs, or if we just need to complete some missing packaging steps.

**Comment by lissyx** [comment]
So far, the best point I came to was:
 - we need to package `index.d.ts`
 - we can run you example-provided `index.ts` using `ts-node`, but it should be `client.ts`

What I am still failing to understand is:
 - is `ts-node` the way to go ?
 - do we need to rewrite `client.js` as `client.ts` ?
 - does it even make sense to be able to run an equivalent of `client.js` as typescript ?
 - how are people going to use this ?
 - should typescript be packaged with current js and shipped together, like for ElectronJS ?

**Comment by lissyx** [comment]
@piraka9011 Ok, thanks to some office colleagues, I think my understanding moved a bit:
 - we can just package and ship `index.d.ts` that provides the types for our interface
 - for our CI, though, I think we will need a `client.ts` (maybe a stripped-down version as you suggested as an example)

**Comment by lissyx** [comment]
I might have been able to implement something in https://github.com/mozilla/DeepSpeech/pull/2882 based on your PR.

**Comment by piraka9011** [comment]
@lissyx I should be apologizing for being AFK and not providing enough context :)
I'll take a look at your PR and provide feedback there.

**Comment by lissyx** [comment]
> @lissyx I should be apologizing for being AFK and not providing enough context :)
> I'll take a look at your PR and provide feedback there.

Right. I'll let current PR run and see if it at least works a bit, and then see if your suggestions works. I tried do to that locally but it was failing, and I have no idea why ...

**Comment by lissyx** [comment]
@piraka9011 Namely, there were some obscure-to-me errors from `tsc` on `client.ts` (yet it did generate the JS and it seemed to be running ...) that you can likely help about.

**Comment by lissyx** [comment]
Thanks @piraka9011 for initiating this.
