### ISSUE TITLE
wave.Error: file does not start with RIFF id

### ISSUE THREAD

**Issue by shashi-netra** [mozilla/DeepSpeech#2842]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip3
- **TensorFlow version (use command below)**:v1.14.0-21-ge77504a
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**:

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

I installed deepspeech and ran the cli to generate a transcript of the sample audio, that worked fine, Now I am trying to run against an audio stream from the web and saved to mp3.

```
deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --audio audio-files/xxxxx.mp3 >> aa.txt
Loading model from file deepspeech-0.6.1-models/output_graph.pbmm
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
2020-03-23 18:43:24.768343: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Loaded model in 0.011s.
Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/client.py", line 126, in main
    fin = wave.open(args.audio, 'rb')
  File "/usr/lib/python3.5/wave.py", line 499, in open
    return Wave_read(f)
  File "/usr/lib/python3.5/wave.py", line 163, in __init__
    self.initfp(f)
  File "/usr/lib/python3.5/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id
```

IDK what that error means, the audio file plays just fine with most players, unless I am missing something.

**Comment by lissyx** [comment]
You are passing a MP3 file instead of a WAV.
