### ISSUE TITLE
generate trie from lm and alphabet.txt

### ISSUE THREAD

**Issue by superhg2012** [mozilla/DeepSpeech#2844]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream Tensorflow
- **TensorFlow version (use command below)**: 1.14.0
- **Python version**: 3.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0/
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

I am using DeepSpeech v0.6.1 source code.

I have generate lm and built binary (lm.binary)
When I am trying to train on my own corpus, I found that no trie exists, so I saw a command on branch “mandarin-all-2048” ：

`./generate_trie ../data/alphabet.txt /tmp/lm.binary /tmp/trie`

I tried to use 'make' to get the generate_trie under 'native_client' folder . it failed with below error.

`c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/gang.he/workspace/tensorflow/bazel-bin/native_client  -ldeepspeech  `pkg-config --libs sox`
Package sox was not found in the pkg-config search path.
Perhaps you should add the directory containing `sox.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sox' found
Package sox was not found in the pkg-config search path.
Perhaps you should add the directory containing `sox.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sox' found
client.cc:24:17: fatal error: sox.h: No such file or directory
compilation terminated.
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1
`

so how to generate trie without error?

**Comment by lissyx** [comment]
Please use discourse for support. You dont need to build generate_trie, we already publish it in native_client.tar.xz. If you want to build it, please read correctly the doc and install the dependencies.
