### ISSUE TITLE
generate_trie encoured kenlm error

### ISSUE THREAD

**Issue by superhg2012** [mozilla/DeepSpeech#2846]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:upstream TensorFlow
- **TensorFlow version (use command below)**1.14.0
- **Python version**: 3.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
my Deepspeech version : v0.6.1

native_client installed with cmd:

` python util/taskcluster.py --target native_client)`

then  run cmd:
./generate_trie ../../data/alphabet.txt ../../data/lm.binary ../../data/trie

throw below error

`terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/model.cc:70 in lm::ngram::detail::GenericModel<Search, VocabularyT>::GenericModel(const char*, const lm::ngram::Config&) [with Search = lm::ngram::trie::TrieSearch<lm::ngram::SeparatelyQuantize, lm::ngram::trie::ArrayBhiksha>; VocabularyT = lm::ngram::SortedVocabulary] threw FormatLoadException because `new_config.enumerate_vocab && !parameters.fixed.has_vocabulary'.
The decoder requested all the vocabulary strings, but this binary file does not have them.  You may need to rebuild the binary file with an updated version of build_binary.
Aborted (core dumped)
`

I installed kenlm from github:

pip install https://github.com/kpu/kenlm/archive/master.zip

also I tried to build kenlm in Deepspeech/native_client.but it failed on this step : cmake ..

here is the fulltrace:

`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   system
--   thread
--   unit_test_framework
--   chrono
--   date_time
--   atomic
-- Found ZLIB: /home/gang.he/anaconda3/envs/deepspeech/lib/libz.so (found version "1.2.11") 
-- Found BZip2: /home/www/anaconda3/lib/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /home/gang.he/anaconda3/envs/deepspeech/lib/liblzma.so
-- Looking for lzma_auto_decoder in /home/gang.he/anaconda3/envs/deepspeech/lib/liblzma.so - found
-- Looking for lzma_easy_encoder in /home/gang.he/anaconda3/envs/deepspeech/lib/liblzma.so
-- Looking for lzma_easy_encoder in /home/gang.he/anaconda3/envs/deepspeech/lib/liblzma.so - found
-- Looking for lzma_lzma_preset in /home/gang.he/anaconda3/envs/deepspeech/lib/liblzma.so
-- Looking for lzma_lzma_preset in /home/gang.he/anaconda3/envs/deepspeech/lib/liblzma.so - found
-- Found LibLZMA: /home/gang.he/anaconda3/envs/deepspeech/include (found version "5.2.4") 
CMake Error at util/CMakeLists.txt:58 (add_subdirectory):
  add_subdirectory given source "stream" which is not an existing directory.

CMake Error at lm/CMakeLists.txt:44 (add_subdirectory):
  add_subdirectory given source "builder" which is not an existing directory.

CMake Error at lm/CMakeLists.txt:45 (add_subdirectory):
  add_subdirectory given source "filter" which is not an existing directory.

-- Could NOT find Eigen3 (missing:  EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
CMake Warning at lm/interpolate/CMakeLists.txt:65 (message):
  Not building interpolation.  Eigen3 was not found.

-- To install Eigen3 in your home directory, copy paste this:
export EIGEN3_ROOT=$HOME/eigen-eigen-07105f7124f9
(cd $HOME; wget -O - https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2 |tar xj)
rm CMakeCache.txt

-- Configuring incomplete, errors occurred!
See also "/home/gang.he/workspace/DeepSpeech/native_client/kenlm/build/CMakeFiles/CMakeOutput.log".
See also "/home/gang.he/workspace/DeepSpeech/native_client/kenlm/build/CMakeFiles/CMakeError.lo`

**Comment by lissyx** [comment]
@superhg2012 Please use Discourse for support.
