### ISSUE TITLE
"No such file" problem when building decoder

### ISSUE THREAD

**Issue by JucyCherry** [mozilla/DeepSpeech#2852]
I have search my problem in the forum but cannot find a matched one, I'm sorry if my question duplicated (hope not). 

- **Have not written custom code
- **Linux Ubuntu 16.04)
- **Python 2.7**: 
- **GCC 5.4.0**:

I build the ctcdecoder in directory: DeepSpeech-master/native_client/ctcdecode/,
use command: python setup.py install
and I occurred some errors as following:

g++ -fPIC -c  -DKENLM_MAX_ORDER=6 -std=c++11 -Wno-unused-local-typedefs -Wno-sign-compare -O3 -DNDEBUG -I.. -I../kenlm -Ithird_party/openfst-1.6.7/src/include -Ithird_party/ThreadPool workspace_status.cc -o temp_build/temp_build/workspace_status.o
g++: error: workspace_status.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.

**Comment by lissyx** [comment]
>     * 
> 
> 
> I build the ctcdecoder in directory: DeepSpeech-master/native_client/ctcdecode/,
> use command: python setup.py install

This is not how you are supposed to do. Please install `ds_ctcdecoder` wheel, why do you want to rebuild it ?
