### ISSUE TITLE
Can not generate a trie

### ISSUE THREAD

**Issue by verloka** [mozilla/DeepSpeech#2855]
I cannot generate a trie on Linux:

![image](https://user-images.githubusercontent.com/5623092/77554610-f87cee00-6ebe-11ea-9e45-21626ee3feef.png)

There are no errors on Windows, but nothing happened and the file was not created:

![image](https://user-images.githubusercontent.com/5623092/77554808-3417b800-6ebf-11ea-8872-ca5071a3b25a.png)

I've used native client from release. DeepSpeech 0.6.1

**Comment by lissyx** [comment]
First avoid screenshot.
Second,this is not a bug, use discourse for support.
Third, please grant execution rights to the binary, and avoid sudo.
