### ISSUE TITLE
WARNING: No --validate_label_locale specified, your might end with inconsistent dataset.

### ISSUE THREAD

**Issue by HandsLing** [mozilla/DeepSpeech#2865]
i use the dataset U provided:zh-CN.tar.gz, when i transfrom it to .csv format, it comes out that message, so can U give some advices what the validate_label_locale parms mean? thx

**Comment by lissyx** [comment]
> i use the dataset U provided:zh-CN.tar.gz, when i transfrom it to .csv format, it comes out that message, so can U give some advices what the validate_label_locale parms mean? thx

Here: #2816

**Comment by lissyx** [comment]
@HandsLing This is really aimed at people training their own model. I have not been able to articulate documentation around that.

**Comment by lissyx** [comment]
@HandsLing Does #2868 answers your question, or do you think this doc needs to be improved ? If so, what is missing ?
