### ISSUE TITLE
DeepSpeech 0.6.1 - For longer sentences the recognition is not correct.

### ISSUE THREAD

**Issue by cnair-83** [mozilla/DeepSpeech#2866]
./deepspeech --model /storage/emulated/0/Android/data/com.visteon.sns.app/files/sns/asr/en-US/output_graph.tflite --lm /storage/emulated/0/Android/data/com.visteon.sns.app/files/sns/asr/en-US/lm.binary --trie /storage/emulated/0/Android/data/com.visteon.sns.app/files/sns/asr/en-US/trie --audio /data/local/test_data/1585601981991_an_e_book_an_appointment_for_maintenance_at_the_nearest_dealership_and_sore_minder_from_my_dent_as_appointment_at_noon_on_monday_next_week.wav --stream 1600

TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=246400

in 
on a bo
an e book an ipo
an e book an appointment
an e book an appointment for m
an e book an appointment for matoran
an e book an appointment for maintenance at the
an e book an appointment for maintenance at the nearest 
an e book an appointment for maintenance at the nearest dealers
an e book an appointment for maintenance at the nearest dealership 
an e book an appointment for maintenance at the nearest dealership and 
an e book an appointment for maintenance at the nearest dealership and seem
an e book an appointment for maintenance at the nearest dealership and sore minder fro
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent asap
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen 
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen at no
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen at noon on 
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen at noon on monday 
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen at noon on monday next we
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen at noon on monday next week
an e book an appointment for maintenance at the nearest dealership and sore minder from my dent aspen at noon on monday next week

./deepspeech --model /storage/emulated/0/Android/data/com.visteon.sns.app/files/sns/asr/en-US/output_graph.tflite --lm /storage/emulated/0/Android/data/com.visteon.sns.app/files/sns/asr/en-US/lm.binary --trie /storage/emulated/0/Android/data/com.visteon.sns.app/files/sns/asr/en-US/trie --audio /data/local/test_data/1585601337288_i_want_to_stop_at_a_gas_it_on_on_my_way_home_and_said_a_reminder_for_my_dent_asante_at_noon_on_monday_next_week.wav --stream 1600

TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=230400

i we
i want to st
i want to stop at a
i want to stop at a gas 
i want to stop at a gas it on on 
i want to stop at a gas it on on my way 
i want to stop at a gas it on on my way home
i want to stop at a gas it on on my way home and s
i want to stop at a gas it on on my way home and said are
i want to stop at a gas it on on my way home and said reminder 
i want to stop at a gas it on on my way home and said reminder for my de
i want to stop at a gas it on on my way home and said reminder for my dent asap
i want to stop at a gas it on on my way home and said reminder for my dent asante 
i want to stop at a gas it on on my way home and said reminder for my dent asante at 
i want to stop at a gas it on on my way home and said reminder for my dent asante at noon 
i want to stop at a gas it on on my way home and said reminder for my dent asante at noon on mind
i want to stop at a gas it on on my way home and said reminder for my dent asante at noon on monday next 
i want to stop at a gas it on on my way home and said reminder for my dent asante at noon on monday next week
i want to stop at a gas it on on my way home and said reminder for my dent asante at noon on monday next week

I am using DeepSpeech 0.6.1 release model. Even I tried without streaming also, there is not much difference. Attached the sample files here.  

[samples.zip](https://github.com/mozilla/DeepSpeech/files/4407037/samples.zip)

**Comment by kdavis-mozilla** [comment]
As this is a particular problem for a particular audio clip (one can always find an audio clip that results in an incorrect transcription) and not a bug with the code or a request for a new feature, could you move this to [discourse](https://discourse.mozilla.org/c/deep-speech/247). Thank you. 

PS: We generally reserve issues for bugs and/or feature requests.
