### ISSUE TITLE
/deepspeech-0.6.1-models does not contain kenlm.scorer

### ISSUE THREAD

**Issue by cheahheng** [mozilla/DeepSpeech#2874]
The readme at deepspeech stable release ask user to download the following
https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/deepspeech-0.6.1-models

And run the following
$ deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --scorer deepspeech-0.6.1-models/kenlm.scorer --audio audio/2830-3980-0043.wav

However, this folder deepspeech-0.6.1-models does not contain kenlm.scorer. Also, the following
$ pip3 install deepspeech

installs deepspeech version 0.6.1 which does not yet support the scorer option

Can you please make correction to the readme file found in the following path
https://github.com/mozilla/DeepSpeech

**Comment by kdavis-mozilla** [comment]
This [README](https://github.com/mozilla/DeepSpeech) you refer to is for master and is correct. 

The 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1) which you _do not_ refer to is also correct and does not mention a kenlm.scorer.

When using Deep Speech 0.6.1 please refer to the 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1)

**Comment by cheahheng** [comment]
Please, then please tell me which version of deepspeech that will be able to run the following

deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --scorer deepspeech-0.6.1-models/kenlm.scorer --audio audio/2830-3980-0043.wav

**Comment by cheahheng** [comment]
> This [README](https://github.com/mozilla/DeepSpeech) you refer to is for master and is correct.
> 
> The 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1) which you _do not_ refer to is also correct and does not mention a kenlm.scorer.
> 
> When using Deep Speech 0.6.1 please refer to the 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1)

The master readme is not correct because the deepspeech-0.6.1-models that it states to download simply does not contain kenlm.scorer

**Comment by lissyx** [comment]
> > This [README](https://github.com/mozilla/DeepSpeech) you refer to is for master and is correct.
> > The 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1) which you _do not_ refer to is also correct and does not mention a kenlm.scorer.
> > When using Deep Speech 0.6.1 please refer to the 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1)
> 
> The master readme is not correct because the deepspeech-0.6.1-models that it states to download simply does not contain kenlm.scorer

If you are using deepspeech 0.6.1 you need to refer to README of 0.6.1.

We welcome any suggestions to solve this chicken / egg problem for master, but so far we have not been able to find a valid solution.

**Comment by lissyx** [comment]
> > > This [README](https://github.com/mozilla/DeepSpeech) you refer to is for master and is correct.
> > > The 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1) which you _do not_ refer to is also correct and does not mention a kenlm.scorer.
> > > When using Deep Speech 0.6.1 please refer to the 0.6.1 [README](https://github.com/mozilla/DeepSpeech/tree/v0.6.1)
> > 
> > 
> > The master readme is not correct because the deepspeech-0.6.1-models that it states to download simply does not contain kenlm.scorer
> 
> If you are using deepspeech 0.6.1 you need to refer to README of 0.6.1.
> 
> We welcome any suggestions to solve this chicken / egg problem for master, but so far we have not been able to find a valid solution.

@cheahheng Please see the discussion in PR #2824

**Comment by lissyx** [comment]
Closing for lack of actionable item
