### ISSUE TITLE
Segmentation fault using utf8 scorer with non utf8 data.

### ISSUE THREAD

**Issue by DanBmh** [mozilla/DeepSpeech#2875]
Building an utf8 scorer out of non utf8 data and running a training + evaluation with it resulted in a `Segmentation fault` error  at the model evaluation.

With a non utf8 scorer everything works as intended. 
Maybe you could add a check somewhere which provides a more descriptive error message.

Tested with docker container from master branch some weeks ago (~v0.7.0a2).

**Comment by lissyx** [comment]
> Building an utf8 scorer out of non utf8 data and running a training + evaluation with it resulted in a `Segmentation fault` error at the model evaluation.

What do you mean "utf8 scorer" and "non utf8" data ? Can you be more explicit ?

**Comment by lissyx** [comment]
@DanBmh Is it like 09673581a492ac9ed027eefee58af9e9ebd17000 ?

**Comment by DanBmh** [comment]
No, the error occurred at training time, after the training was finished at the beginning of the checkpoint evaluation.

I did use the the `--force_utf8` flag when creating the scorer model. But my data is word based and i should not have used the flag. I have seen you added more documentation around this flag recently.

**Comment by lissyx** [comment]
> I did use the the `--force_utf8` flag when creating the scorer model. But my data is word based and i should not have used the flag.

Unfortunately, this is a very sharp edge case, and from the code itself it's hard to detect with 100% accurraccy. I'm not sure that besides improving the documentation we can fix that soonish.

Could you please give feedback or even better PR for the doc so that we can improve it ? It seems you got tricked and you learnt from that, so you know better than us what is misleading.

**Comment by DanBmh** [comment]
I did add a link to your utf8 docs in the `--force_utf8` parameter description in my above pull request.

**Comment by DanBmh** [comment]
Link to utf8 docs in the `--force_utf8` parameter description got merged.

**Comment by reuben** [comment]
I won't have time to look at this super soon. If someone is still running into this, please comment with a stack trace, it'd help a lot.

**Comment by kdavis-mozilla** [comment]
I'm going to close for lack of movement. If someone runs into this again, feel free to re-open.
