### ISSUE TITLE
Caching prepared mfcc features on disk

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#288]
The prepared mfcc features plus related meta data should be cached on disk to:
- reduce repeated CPU work as much as possible
- know sample lengths without loading/converting the whole files to determine batch-groups (#246)

**Comment by kdavis-mozilla** [comment]
With the near continual 99% GPU utilization we see now this is no longer relevant as we now know the CPU can feed data faster than the GPU can compute on it.
