### ISSUE TITLE
Dropped source layers in model evaluation.

### ISSUE THREAD

**Issue by DanBmh** [mozilla/DeepSpeech#2883]
When using `--drop_source_layers 1` in a training, the last layer will also be dropped and new initialized in the model evaluation, leading to wrong results.

Tested with docker container from master branch a week ago (~v0.7.0a3).

**Comment by lissyx** [comment]
I'm pretty sure this is expected. @JRMeyer is working on docs for that

**Comment by lissyx** [comment]
I'll let him comment

**Comment by reuben** [comment]
It can't possibly be expected, evaluation should be a read only operation.

**Comment by reuben** [comment]
This is also breaking model export at the end of a transfer run.

**Comment by JRMeyer** [comment]
if this is happening, it's a problem... I'll take a look

**Comment by rhamnett** [comment]
@JRMeyer already done https://github.com/mozilla/DeepSpeech/pull/2884

**Comment by JRMeyer** [comment]
@rhamnett, you beat me to it:) #2887

**Comment by rhamnett** [comment]
Not me! I was just trying to warn you so you didn't spend time on it, never mind :)
