### ISSUE TITLE
Remove DataSets objects from importers

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#289]
The required data-set (`train`, `dev` or `test`) should be loaded directly by a `read_data_set` routine which will replace the current `read_data_sets` one. 
This is for tidying up and a preparation step for #246 (which will then introduce additional parameters to select a batch-group).

**Comment by tilmankamp** [comment]
@kdavis-mozilla @andrenatal Should we first merge the pull requests for the remaining importers? Or would you want to wait for this and #288 and then do the transformation for them on your end?

**Comment by kdavis-mozilla** [comment]
@tilmankamp It would be easier to wait on the new importers. @andrenatal what do you think?

**Comment by andrenatal** [comment]
@kdavis-mozilla @tilmankamp Let's refactor after we merge the two remaining importers, seems it's about to happen.

**Comment by kdavis-mozilla** [comment]
Fixed by 8d21d0c
