### ISSUE TITLE
Building docker container awaits input 

### ISSUE THREAD

**Issue by DanBmh** [mozilla/DeepSpeech#2896]
Building the docker container awaits an input 

```
STEP 50: RUN ln -s /DeepSpeech/native_client /tensorflow
--> 9fa0ff23376
STEP 51: WORKDIR /tensorflow
--> 0fd7a5747d8

STEP 52: RUN ./configure
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1 installed.
Do you wish to build TensorFlow with ROCm support? [y/N]:
```

Tested with current master branch.
I'm using podman instead of docker but the issue should be the same.

**Comment by lissyx** [comment]
> Building the docker container awaits an input
> 
> ```
> STEP 50: RUN ln -s /DeepSpeech/native_client /tensorflow
> --> 9fa0ff23376
> STEP 51: WORKDIR /tensorflow
> --> 0fd7a5747d8
> 
> STEP 52: RUN ./configure
> Extracting Bazel installation...
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> You have bazel 0.24.1 installed.
> Do you wish to build TensorFlow with ROCm support? [y/N]:
> ```
> 
> Tested with current master branch.
> I'm using podman instead of docker but the issue should be the same.

Obviously not because docker builds fine in our CI

**Comment by lissyx** [comment]
https://community-tc.services.mozilla.com/tasks/IJ2Nx0JFQJSR5mksdLmL_w/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FIJ2Nx0JFQJSR5mksdLmL_w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by lissyx** [comment]
Even better: https://community-tc.services.mozilla.com/tasks/IJ2Nx0JFQJSR5mksdLmL_w/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FIJ2Nx0JFQJSR5mksdLmL_w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L19049-19091

So I don't know what you are doing @DanBmh ...

**Comment by DanBmh** [comment]
Interesting.

The behavior is the same in root and rootless build mode.

But we can close the issue, as the docker building seems to work correctly.

**Comment by lissyx** [comment]
> Interesting.
> 
> The behavior is the same in root and rootless build mode.
> 
> But we can close the issue, as the docker building seems to work correctly.

Well you could force env var to avoid that, and it might make sense as a PR

**Comment by DanBmh** [comment]
What is the reason for building tensorflow ourself instead of using a prebuilt container?

**Comment by lissyx** [comment]
> What is the reason for building tensorflow ourself instead of using a prebuilt container?

This Dockerfile was contributed by someone that had the need to rebuild from scratch.

**Comment by reuben** [comment]
Also we use a modified fork of TensorFlow: https://github.com/mozilla/tensorflow/tree/r1.15

**Comment by DanBmh** [comment]
Are there changes which are important for this project?
I'm asking because i had some problems on one computer that tensorflow did not find my gpus with this container. I switched to one of nvidias prebuilt containers and there the gpus were found.

My file is much shorter and faster to build and currently i don't miss anything for training:
```
FROM nvcr.io/nvidia/tensorflow:20.03-tf1-py3

# Install basic packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    sox libsox-dev

# Build kenlm
RUN mkdir /DeepSpeech/ /DeepSpeech/native_client/ \
    && cd /DeepSpeech/native_client/ \
    && git clone --depth 1 https://github.com/kpu/kenlm \
    && cd kenlm \
    && mkdir -p build \
    && cd build \
    && cmake .. \
    && make -j 4

# Install required python packages
COPY . /DeepSpeech/
RUN pip3 install --no-cache-dir /DeepSpeech/

# Tool to convert output graph for inference
RUN python3 /DeepSpeech/util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --branch r1.15 --target .

WORKDIR /DeepSpeech/
CMD ["/bin/bash"]
```

**Comment by reuben** [comment]
If they weren't important we wouldn't go through the trouble of using a fork...

The changes only affect our native client, which is why for training you can simply install upstream TensorFlow with pip.

**Comment by lissyx** [comment]
>  I'm using podman instead of docker but the issue should be the same.

So, since we don't reproduce on CI, can you investigate around that ?

**Comment by DanBmh** [comment]
Sorry, i can't help you very much with this now. 
If I insert the values (possible with podman), the build continues but my laptop stops responding after some minutes. And I won't have a more powerful computer at my hands for the next time, as my university is closed ...


But maybe another idea, what do you think about splitting your Dockerfile into two parts? The first part to build a container with prebuilt tensorflow and gpu-setup for training. And in the second part you build upon that image and add/replace the dependencies for native client generation.
This will greatly reduce the build time for the users who only want to do a training and should also reduce the overall build time a bit. And it will fix my gpu not detected error:)
Maybe you can then cache the images and only rebuild the ones where something did change, to reduce runtime for automatic tests.

**Comment by lissyx** [comment]
>  This will greatly reduce the build time for the users who only want to do a training and should also reduce the overall build time a bit. And it will fix my gpu not detected error:)

Like https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/Dockerfile.train ?

**Comment by lissyx** [comment]
> But maybe another idea, what do you think about splitting your Dockerfile into two parts?

Again, this Dockerfile was submitted by @GeorgeFedoseev and looked like a good idea. It addresses some specific use cases.

Having multiples Dockerfile will complexify things, when we need to simplify them.

**Comment by lissyx** [comment]
>  Maybe you can then cache the images and only rebuild the ones where something did change, to reduce runtime for automatic tests.

Except we have no tests at all on that docker.

**Comment by lissyx** [comment]
> The first part to build a container with prebuilt tensorflow and gpu-setup for training.

As @reuben said earlier, there is no need for this for training, you can just use `tensorflow-gpu` produced by upstream. The requirement for our forked tensorflow is **only** to build the `native_client` codebase.

**Comment by DanBmh** [comment]
> Like https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/Dockerfile.train ?

Not quite, i think my workflow is a bit different. I'm using the container only to install everything i need and then connect to it and run my commands inside. For input and output data, i mount those directories into the container, also files i changed. Therefore i only have to rebuild it if something in the setup did change.

I did mean like the short file I inserted above, and then in the second file uninstall tensorflow and rebuild it from source. If your lucky the dependencies for building tensorflow were already installed by nvidia. Only those who want to build the native_client codebase have to build the second container. 
I think this will reduce complexity instead of adding, because you can simplify the contents and remove things nvidia did already.

**Comment by lissyx** [comment]
> Not quite, i think my workflow is a bit different. I'm using the container only to install everything i need and then connect to it and run my commands inside. For input and output data, i mount those directories into the container, also files i changed. Therefore i only have to rebuild it if something in the setup did change.

See ? We don't have the same workflow. It's hard to have a one-for-all solution ...

This thread is now going in very different direction and we still don't know whether this is `docker` vs `podman` or if there is something else.

I don't know podman, and I really have no time to play.

**Comment by DanBmh** [comment]
> See ? We don't have the same workflow. It's hard to have a one-for-all solution ...

Thats why i suggested the splitting. It would create a minimal solution where everyone can build upon.

> This thread is now going in very different direction and we still don't know whether this is `docker` vs `podman` or if there is something else.

It builds fine in your CI, so think this is podman related.

> I don't know podman, and I really have no time to play.

Important difference to docker is that it can run without root privileges


Currently I can't play with it, and this also don't has a high priority to me right now, because I solved the problem with the dockerfile above. And solving the input problem alone, wouldn't solve my gpu detection problem.

**Comment by kdavis-mozilla** [comment]
OK to close?

**Comment by lissyx** [comment]
@DanBmh gentle ping?

**Comment by DanBmh** [comment]
Yes. I thought the question was for you, because you reopened it again.
