### ISSUE TITLE
ValueError: ../../VERSION is not valid SemVer string

### ISSUE THREAD

**Issue by fsociety5991** [mozilla/DeepSpeech#2899]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:No 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Google Colab 
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:upstream Tensorflow
- **TensorFlow version (use command below)**:tensorflow-gpu==1.15.2
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:!python3 DeepSpeech.py --helpefull

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Trying to train DeepSpeech on the Arabic common voice Datasets using google Colaboratory, and after cloning the latest version of DeepSpeech and following the exact steps on the documentation, I ran into this error after trying to start the training (or lance the --helpfull )  

Traceback (most recent call last):
  File "DeepSpeech.py", line 7, in <module>
    from deepspeech_training import train as ds_train
  File "/content/drive/My Drive/DeepSpeech/training/deepspeech_training/train.py", line 30, in <module>
    from .evaluate import evaluate
  File "/content/drive/My Drive/DeepSpeech/training/deepspeech_training/evaluate.py", line 26, in <module>
    check_ctcdecoder_version()
  File "/content/drive/My Drive/DeepSpeech/training/deepspeech_training/util/helpers.py", line 53, in check_ctcdecoder_version
    rv = semver.compare(ds_version_s, decoder_version_s)
  File "/usr/local/lib/python3.6/dist-packages/semver.py", line 452, in compare
    v1, v2 = parse(ver1), parse(ver2)
  File "/usr/local/lib/python3.6/dist-packages/semver.py", line 74, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: ../../VERSION is not valid SemVer string

**Comment by lissyx** [comment]
Are you sure you properly git clone? Can you hand verify that the root `VERSION` file is indeed here? 
can you check using path without spaces just in case?

**Comment by reuben** [comment]
I think it's Google Colab somehow. That string is what's shown in git commits for the symlink, but on clone it should turn into a real symlink.

**Comment by fsociety5991** [comment]
> can you check using path without spaces just in case?
I re-cloned the repo in the /content directory to avoid spaces in path and it solved the error, thank you.

**Comment by fsociety5991** [comment]
> I think it's Google Colab somehow. That string is what's shown in git commits for the symlink, but on clone it should turn into a real symlink.

Yes its colab problem, they use spaces in their drive repo which mess with the path in files, thank you.

**Comment by AmyChen-Qingxin** [comment]
I just ran into the same problem. How did you resolve the issue?
