### ISSUE TITLE
Port TensorFlow to RPi3

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#290]

**Comment by lissyx** [comment]
I could work on this.

**Comment by lissyx** [comment]
There is support for cross compilation in tensorflow from PR tensorflow/tensorflow#2590 
Use is documented at: https://github.com/mozilla/tensorflow/blob/warpctc/tensorflow/contrib/makefile/README.md

**Comment by lissyx** [comment]
The above comment links to the current doc. One should be aware they do not use cross-compilation but rather in-place compilation ON the RPi3.

**Comment by lissyx** [comment]
Cross-compilation also works not that bad, with a little adjustments to some variables when doing the build. Also, GCC 4.8 seems to still be a hard requirement, 4.9 shows the same atomic exchange issues. Currently RPi toolchain provides at least 4.8 (Linaro based) and 4.9.3, so it works well. One need to take care to build all dependencies (protoc/libprotobuf and zlib) with the same compiler ; std::string ABI changed with GCC 5 and thus this would break with unresolved symbols.

**Comment by tilmankamp** [comment]
@lissyx Could this get closed then?

**Comment by lissyx** [comment]
I'm not sure, we need to define and scope more precisely what we want on RPi3 I guess, since the testing I conducted was Makefile-based and not Bazel-based ; one does not know how reliable this can be over time.

**Comment by kdavis-mozilla** [comment]
@tilmankamp @lissyx The 1.0 version of TF will contain a makefile to build on RPi[[1](https://github.com/tensorflow/tensorflow/tree/r1.0/tensorflow/contrib/makefile#raspberry-pi)]. (And other platforms too.) So we're safe assuming the non-cross compiled makefile build is reliable over time.

As to what needs to be in the build, we'll only know when Chris has made more progress with the port of DeepSpeech to RPi. Until then, I think we can just close this issue.

**Comment by lissyx** [comment]
Sure, this is the Makefile I referred to, my only interrogation is that it is part of contrib, so we have no real guarantee of stability/existence overtime.

Regarding using it to cross-compile, I would like to link my notes, since it looks like it got lost :)
https://gist.github.com/lissyx/28c1a0092d9a1ea73d786381682a91be

If we consider this issue as "can we find a way to build a libtensorflow for RPi3", then it can be closed, since we could apply documentation and verify that it was working (and also ensuring doc is end-to-end).

**Comment by kdavis-mozilla** [comment]
I viewed this issue as "can we find a way to build a libtensorflow for RPi3". So, I'll close it.

PS: Thanks for the gist link, so things don't get lost!

**Comment by lissyx** [comment]
Updating that closed bug. As part of the quantization effort, I worked again on RPi3 support, and a few things need to be shared:
 - Official Raspbian image is built with march=armv6
 - I have patches on top of Tensorflow to cross-build with the RPi toolchain (GCC 4.9.3)
 - I have patches on top of DeepSpeech to cross-build with the same toolchain
 - Building with march different from armv6 for Raspbian will result in runtime crash around std::thread
 - (cross-)Building with GCC 5.4.1 targetting Ubuntu 16.04 (armv7-a) results in no visible improvement at runtime
 - Playing with GCC specific optimization (-mtune, -O2, -pipe, etc) gives more improvement.
