### ISSUE TITLE
How to continue train by increase complexity like increase n_hidden models?

### ISSUE THREAD

**Issue by wahyubram82** [mozilla/DeepSpeech#2905]
I read a good research in handle over-fitting and make good generalizing, 'Reconciling modern machine learning practice and the bias-variance trade-off', you can see it [here](https://arxiv.org/abs/1812.11118).

a good explanation and simple, you can see [here](https://www.youtube.com/watch?v=ZAW9EyNo2fw).

really-really blow your mine about machine learning / deep learning.

because many person in train the dataset, big possibilities face that problem esspecially overfitting.

so i want to implement it in deepspeech...
at this moment, i only can set the trainning rate, and especially in reduce the dropout_rate to make the n_hidden bigger, or using more complex n-grams ken-lm, but the trully things what i want to do is raise the number of n_hidden layers...to make the model complexity raise significan.

but looks like, the deepspeech code now allowed me to do that, how i can change the code to make n_hidden number without make it errors?

**Comment by rhamnett** [comment]
This video seems to simply describe the phenomenon of deep double descent and over fitting due to many parameters. There is already a training variable --n_hidden when training. See https://github.com/mozilla/DeepSpeech/blob/master/training/deepspeech_training/util/flags.py

**Comment by wahyubram82** [comment]
> This video seems to simply describe the phenomenon of deep double descent and over fitting due to many parameters. There is already a training variable --n_hidden when training. See https://github.com/mozilla/DeepSpeech/blob/master/training/deepspeech_training/util/flags.py

yeah, but it's error when you applied it, in purpose to continue trainning....

it's not simplyfy... it's only told a newest research that really interesting....and really2 blow out your mine....research means...already plan, calculated and predict and off course...tested...
if you a tipical of people who not believe in a research, but believe to another person who already tested a research,  i cannot blame you..it's just another perception...

**Comment by reuben** [comment]
1. There's no hyperparameter for the number of hidden layers, you'll have to change the code that defines the model in the function `create_model` in `train.py`.
2. In current master there's code to initialize some layers from scratch when loading a checkpoint, with the `--drop_source_layers` flag. If you want to continue a pre-trained checkpoint with more layers, it could be useful. It hasn't been tested for that, though, so you'll have to figure it out. It also wasn't available in 0.6.1 so you'll have to wait for the 0.7.0 release (which should go out in the next couple of weeks).
3. This is not a bug, please use [Discourse](https://discourse.mozilla.org/c/deep-speech) as documented in the issue template you deleted to post this issue.
