### ISSUE TITLE
Create r0.8 release branch and update release checklist with branching steps

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2919]
https://github.com/mozilla/DeepSpeech/wiki/Release-checklist

**Comment by kdavis-mozilla** [comment]
Isn't this now not needed as a result of the fix to the main README?

**Comment by reuben** [comment]
It's now disconnected from the docs issue and would not involve changing the GitHub default branch. The goal would be to only get better release management capabilities out of it, like being able to do a 0.8.x release after the first 0.9 alpha.

**Comment by kdavis-mozilla** [comment]
Got it.

Would this be something we should do for 0.8.0, where we will not offer long term support, or something we should do for 1.0.0, where we would offer long term support.

**Comment by reuben** [comment]
I think we probably won't necessarily need it for the 0.8 cycle, but it's good to exercise this before 1.0 to give time to correct anything.
