### ISSUE TITLE
Unable to load discourse forum

### ISSUE THREAD

**Issue by MittalShruti** [mozilla/DeepSpeech#2920]
Hi, this is not a bug. 

I have been unable to load discourse forum for the last 24 hours. Is the site under maintenance? If yes, when will it be back up and running?

**Comment by vjyanand** [comment]
@MittalShruti it works now

**Comment by lissyx** [comment]
> Hi, this is not a bug.
> 
> I have been unable to load discourse forum for the last 24 hours. Is the site under maintenance? If yes, when will it be back up and running?

Can you be more specific ? We have no knowledge of planned outage, it works for us, and we are not in charge of the forum itself.
