### ISSUE TITLE
i want to export the checkpoint as .pb or .pbmm format 

### ISSUE THREAD

**Issue by dimanshu** [mozilla/DeepSpeech#2923]
I FINISHED optimization in 1:10:59.979531
I Exporting the model...
I Could not find best validating checkpoint.
I Could not find most recent checkpoint.
E All initialization methods failed (['best', 'last']).

**Comment by lissyx** [comment]
This is not a bug, please reach for support on Discourse as explaine in the issue template you removed.

**Comment by dimanshu** [comment]
how to export it ?

**Comment by lissyx** [comment]
> how to export it ?

Seriously? you spam, you don't read the issue template, you reach for support on Github instead of Discourse, **and** you don't read your own output?

There's **nothing** actionable in your few console output. We don't know what you did, we can't help you.
