### ISSUE TITLE
i want to export the checkpoint as .pb or .pbmm format .i'm getting an error

### ISSUE THREAD

**Issue by dimanshu** [mozilla/DeepSpeech#2924]
command which i used =./DeepSpeech.py --train_files /home/dimanshu/train.csv --dev_files  /home/dimanshu/dev.csv ----test_files /home/dimanshu/test.csv  alphabet_config_path /home/dimanshu/alphabet.txt --load_checkpoint_dir /home/dimanshu/deepspeech-0.5.1-models/output_graph.pbmm  --learning_rate 0.0001 --epochs 24 --export_dir /home/dimanshu/checkpoint/

I FINISHED optimization in 1:10:59.979531
I Exporting the model...
I Could not find best validating checkpoint.
I Could not find most recent checkpoint.
E All initialization methods failed (['best', 'last']).

TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78

**Comment by lissyx** [comment]
Please stop spamming.
