### ISSUE TITLE
ds-ctcdecoder numpy requirements incompatable with setup.py's 

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#2931]
setup.py requires numpy version "1.18.1"[[1](https://github.com/mozilla/DeepSpeech/blob/master/setup.py#L67)] tc-py-utils.sh requires version ">=1.14.5,<=1.17.0"[[2](https://github.com/mozilla/DeepSpeech/blob/b3b357cdac3d03c1312692906d500a7c7d4248dd/taskcluster/tc-py-utils.sh#L268)][[3](https://github.com/mozilla/DeepSpeech/blob/b3b357cdac3d03c1312692906d500a7c7d4248dd/taskcluster/tc-py-utils.sh#L289)].

**Comment by kdavis-mozilla** [comment]
I don't know if this is solvable.

setup.py sets numpy version independent of python version used[[1](https://github.com/mozilla/DeepSpeech/blob/master/setup.py#L67)]

However, the ds-ctcdecoder decoder numpy versions are dependent upon the python version used[[2](https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-py-utils.sh#L235)]

This situation might be OK is we could, considering all python versions and platforms, look for the maximal minimum version required here[[2](https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-py-utils.sh#L235)] and also, considering all python versions and platforms, find the minimal maximal version required here[[2](https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-py-utils.sh#L235)] and then bound the setup.py numpy version by the interval so found.

This migh work, but this interval is empty.

For example the maximal minimum version required on Darwin for python 3.8 is 1.17.3[[3](https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-py-utils.sh#L272)] and the minimal maximal version required by python 3.7 is 1.17.0[[4](https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-py-utils.sh#L268)] so there is no version of numpy that works for all platforms and python versions.

**Comment by kdavis-mozilla** [comment]
Seems like we might have to mirror the logic of tc-py-utils.sh in setup.py using[[1](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies)]

However, repeating such delicate code seems like a recipe for a maintenance headache.

**Comment by reuben** [comment]
We can't support Python 3.8 for training anyway, because TensorFlow 1.15.2 does not have Python 3.8 wheels. Does eliminating that version fix the problem of the empty interval?

**Comment by kdavis-mozilla** [comment]
I ran into this in creating a scorer, not really training in the normal sense of the word.

But ignoring 3.8 we still have the problem as the maximal minimum version is 1.14.5 for

- Linux and Python 3.6
- Darwin and Python 3.7
- Windows and Python 3.7

while the minimal maximal version is 1.12.0 for

- Windows and Python 3.5 

So it doesn't look like we can have a numpy version that works for all cases if we ignore the platform and Python version.

**Comment by reuben** [comment]
What if we remove the version specifier in setup.py and let pip find a version that matches all constraints? That way we don't have to reimplement the build logic in setup.py, since it's already propagated by the fact that we depend on ds_ctcdecoder from there.

**Comment by kdavis-mozilla** [comment]
If that works, it sounds like the easiest solution to me.

**Comment by kdavis-mozilla** [comment]
Will be addressed by PR #2934
