### ISSUE TITLE
Docker image GPU training not working

### ISSUE THREAD

**Issue by Visuatech** [mozilla/DeepSpeech#2947]
I build the docker images with the included dockerfile and start it with the following command:
 docker run --gpus 2 -it [image]

After running ./bin/run-ldc93s1.sh as a test I get following stack trace:

> I Training epoch 0...
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
>     return fn(*args)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
>     target_list, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
>   (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[{{node tower_0/conv1d}}]]
> 	 [[concat/concat/_99]]
>   (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[{{node tower_0/conv1d}}]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "DeepSpeech.py", line 12, in <module>
>     ds_train.run_script()
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 939, in run_script
>     absl.app.run(main)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 911, in main
>     train()
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 588, in train
>     train_loss, _ = run_set('train', epoch, train_init_op)
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 548, in run_set
>     feed_dict=feed_dict)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
>   (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[node tower_0/conv1d (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> 	 [[concat/concat/_99]]
>   (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[node tower_0/conv1d (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> Original stack trace for 'tower_0/conv1d':
>   File "DeepSpeech.py", line 12, in <module>
>     ds_train.run_script()
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 939, in run_script
>     absl.app.run(main)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 911, in main
>     train()
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 474, in train
>     gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 312, in get_tower_results
>     avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 239, in calculate_mean_edit_distance_and_loss
>     logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse, rnn_impl=rnn_impl)
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 167, in create_model
>     batch_x = create_overlapping_windows(batch_x)
>   File "/usr/local/lib/python3.6/dist-packages/deepspeech_training/train.py", line 69, in create_overlapping_windows
>     batch_x = tf.nn.conv1d(input=batch_x, filters=eye_filter, stride=1, padding='SAME')
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 574, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 574, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 1681, in conv1d
>     name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1071, in conv2d
>     data_format=data_format, dilations=dilations, name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
>     attrs, op_def, compute_device)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
>     op_def=op_def)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
>     self._traceback = tf_stack.extract_stack()`

after checking cuda version with cat /usr/local/cuda/version.txt
I get CUDA Version 10.0.130

and I confirmed that all cudnn files are at the locations they should be, and env shows:

> `CUDNN_VERSION=7.6.5.32
> LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
> LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/lib64/stubs/
> TF_NEED_TENSORRT=0
> TF_CUDA_PATHS=/usr/local/cuda,/usr/lib/x86_64-linux-gnu/
> TF_ENABLE_XLA=0
> TF_NEED_VERBS=0
> HOSTNAME=cbf966cac211
> TF_CUDA_VERSION=10.0
> TF_CUDA_COMPUTE_CAPABILITIES=6.0
> TF_NEED_HDFS=0
> TF_NEED_MKL=0
> TF_BUILD_DISABLE_GCP=1
> PYTHONIOENCODING=UTF-8
> NVIDIA_VISIBLE_DEVICES=0
> TF_NEED_GDR=0
> TF_NEED_NGRAPH=0
> PYTHON_LIB_PATH=/usr/lib/python3.6/dist-packages
> TF_DOWNLOAD_CLANG=0
> TF_BUILD_ENABLE_XLA=0
> TF_BUILD_IS_OPT=OPT
> NCCL_VERSION=2.4.8
> TF_NEED_GCP=0
> PWD=/DeepSpeech
> TF_BUILD_PYTHON_VERSION=PYTHON3
> HOME=/root
> TF_CUDNN_VERSION=7
> TF_NEED_AWS=0
> LIBRARY_PATH=/usr/local/cuda/lib64/stubs
> TF_BUILD_CONTAINER_TYPE=GPU
> TF_BUILD_IS_PIP=PIP
> CC_OPT_FLAGS=-mavx -mavx2 -msse4.1 -msse4.2 -mfma
> TERM=xterm
> TFDIR=/tensorflow
> CUDA_PKG_VERSION=10-0=10.0.130-1
> CUDA_VERSION=10.0.130
> TF_NEED_OPENCL=0
> NVIDIA_DRIVER_CAPABILITIES=compute,utility
> SHLVL=1
> TF_CUDA_CLANG=0
> NVIDIA_REQUIRE_CUDA=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411
> TF_NEED_JEMALLOC=1
> TF_NEED_KAFKA=0
> TF_BUILD_OPTIONS=OPT
> TF_NCCL_VERSION=2.3
> TF_NEED_CUDA=1
> PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> PYTHON_BIN_PATH=/usr/bin/python3.6
> TF_NEED_OPENCL_SYCL=0
> _=/usr/bin/env`

so it at least LOOKs like everything is in order.
What else can I try?

**Comment by lissyx** [comment]
>  docker run --gpus 2 -it [image]

Don't you lack `--runtime=nvidia` ? This needs `NVIDIA-Docker` to work

**Comment by Visuatech** [comment]
Nvidia docker is installed, and nvidia-smi for example works in the deepspeech container, so afaik that should be okay?

**Comment by lissyx** [comment]
> Nvidia docker is installed, and nvidia-smi for example works in the deepspeech container, so afaik that should be okay?

It was not in your command.

This Dockerfile was contributed by @GeorgeFedoseev but we are only building it, we have no way to test it. You can see we never refer to it in any documentation.

This error can also sometimes be related to batch size / insufficient amount of GPU memory. We need much more details to be able to help.

**Comment by Visuatech** [comment]
Hi Lissyx, the fact that the -gpus switch works means that nvidia-docker is correctly working
I first installed it locally according to the documentation and this works with the exact same GPU's and commands, that's why I'm unsure where the error comes from... 
Which details can I provide to find a solution?

**Comment by lissyx** [comment]
>  Which details can I provide to find a solution?

I already gave you two: batch size, GPU memory. You need to share more context on what you are doing exactly ... Hardware ? Software ? Other process using GPUs outside of Docker ? etc.

**Comment by lissyx** [comment]
>  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

Have you tried searching this on our docs? https://deepspeech.readthedocs.io/en/v0.7.0/TRAINING.html#recommendations

**Comment by Visuatech** [comment]
I apologize, I totally read over that part multiple times...
When adding TF_FORCE_GPU_ALLOW_GROWTH to the script it works.
So it's possible to just build the docker container and run it.

**Comment by lissyx** [comment]
> I apologize, I totally read over that part multiple times...
> When adding TF_FORCE_GPU_ALLOW_GROWTH to the script it works.
> So it's possible to just build the docker container and run it.

Don't hesitate to send PR to improve the docs, if you think there's a need to: if you missed it maybe it is because it's not as readable as we thought?
