### ISSUE TITLE
Implement dataset merging

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#295]
Eventually we'll want to train on multiple datasets at the same time (Fisher+Switchboard, for example). This issue is for implementing that.

**Comment by reuben** [comment]
My initial idea is to plug the batch queues from several importers into an aggregation queue that is then fed into the network, but this could end up being wasteful of resources: mismatches between sequence lengths on different data sets could cause us to end up with too much padding, for example.

**Comment by kdavis-mozilla** [comment]
What happens with curriculum learning?

**Comment by tilmankamp** [comment]
@kdavis-mozilla @reuben I've the feeling, we should write some Python tool to build a combined and prepared corpus in our own format/way.

**Comment by reuben** [comment]
For curriculum learning, I wanted to look at the sequence lengths for the different datasets to see if there's big mismatches between the datasets. If sequence lengths are close enough between batches of equal ordering (first batch of importer 1 with first batch of importer 2, etc), then maybe we don't need to do anything else.

If that doesn't work, then we'll need to do global ordering and that throws my aggregator queue idea out the window.

**Comment by kdavis-mozilla** [comment]
Fixed with #506
