### ISSUE TITLE
does deepspeech has word level timestamps?

### ISSUE THREAD

**Issue by jossiekat** [mozilla/DeepSpeech#2953]
for instance 
if the translation to : "the gray fox "  will also include timestamps for each word:

the : {starttimestamp : 0
          end_timestamp: 1.2}
gray : {starttimestamp : 1.5
          end_timestamp: 2}
fox : {starttimestamp : 1.7
          end_timestamp: 2.2}

thanks
joseph

**Comment by kdavis-mozilla** [comment]
It has character level timestamps, see for example [sttWithMetadata()](https://deepspeech.readthedocs.io/en/v0.7.0/Python-API.html#native_client.python.Model.sttWithMetadata) and the  [Metadata](https://deepspeech.readthedocs.io/en/v0.7.0/Python-API.html#native_client.python.Metadata) it returns.

Words are language dependent, e.g. English vs Simplified Chinese, thus we do not "bake" word timestamps into the API.

**Comment by dabinat** [comment]
@kdavis-mozilla Is there merit in having some kind of helper function in the API to group the timed character output into words? I know it won't work for Chinese, but there are still a lot of languages it would be useful for. Currently everyone needs to roll their own solution, which is a lot of duplicated effort.

**Comment by jossiekat** [comment]
@dabinat @kdavis-mozilla my thoughts exactly.
We already use models trained for a specific language and get a transcription, can't we simple match  the characters to the transcribed word and get a time interval?
starting with english will be great.
google has it already and many request it.

**Comment by reuben** [comment]
A function in the core API needs to be designed for all possible inputs. Then it has to be exposed to Python, Node.JS, Electron, .NET, Java, etc… Then we have to provide support and maintenance.

Personally I'd be fine with contributions to the higher level language bindings to add such a helper, though I'm not sure what the rest of the team thinks. For example adding such a convenience function directly to the Python or Node.JS binding. Or even a snippet to the relevant documentation page.

For all functionality in the core C API, we aim to make it consistently supported on all language bindings and for any valid model, so adding language-specific helper functions makes for an awkward design that we'll have to support for a long time and/or break compatibility if we need to change it.
