### ISSUE TITLE
Move unit tests to TaskCluster so they can run when bumping version

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#2961]
Right now they depend on the pre-built decoder package from TC which is not available yet when the tests run.

**Comment by imskr** [comment]
@reuben I can work on this. I need some more details

**Comment by reuben** [comment]
@imskr cool! We have some unit tests in the `tests` folder, runnable with `python -m unittest` with the training package properly installed. Currently, they are being run in Travis: https://github.com/mozilla/DeepSpeech/blob/9a7ec1ae0d55db4de1ac6ac4d43c4e11478b9610/.travis.yml#L20-L27

The problem is that when installing the training package, it depends on downloading a pre-built decoder package from TaskCluster, matching the current version in the `VERSION` file. When we bump the version, `setup.py` tries to install the pre-built package, but it doesn't exist yet, because it's a new version that hasn't been built.

The fix for this is to move the unit tests execution into a TaskCluster task, which depends on the task that builds the decoder package, and so will only run after it's available. This can be done by adapting the existing training tests. See for example [taskcluster/test-training_16k-linux-amd64-py37m-opt.yml](https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/test-training_16k-linux-amd64-py37m-opt.yml).

You should be able to copy the `test-training*` tasks into similar `test-training-unittests*` tasks, that instead of running `tc-train-tests.sh`, run `tc-train-unittests.sh`. You can then adapt the logic from the existing `tc-train-tests.sh` into `tc-train-unittests.sh` by copying its [initial setup part](https://github.com/mozilla/DeepSpeech/blob/9a7ec1ae0d55db4de1ac6ac4d43c4e11478b9610/taskcluster/tc-train-tests.sh#L1-L22) and then calling `python -m unittest`.

I'll give you write access so you can trigger TaskCluster tasks to test this when you make a PR.

**Comment by imskr** [comment]
Thanks for assigning @reuben I will get into it.

**Comment by reuben** [comment]
@imskr have you been able to make progress on this?

**Comment by imskr** [comment]
Sorry for delay @reuben I will fix this by tomorrow. And I will update you on mozilla matrix.

**Comment by reuben** [comment]
No worries!
