### ISSUE TITLE
Doesnt work Properly

### ISSUE THREAD

**Issue by Paul-Tec** [mozilla/DeepSpeech#2962]

**Comment by kdavis-mozilla** [comment]
As this doesn't appear to be a bug or feature request, what we reserve issues for, could you move this discussion to [discourse](https://discourse.mozilla.org/c/deep-speech/247).

As to your problem, there are many unknowns about the audio, e.g. what processing adjust_for_ambient_noise() applies, that will effect the result and need to be dealt with. So [discourse](https://discourse.mozilla.org/c/deep-speech/247) is the better form to discuss these.
