### ISSUE TITLE
make deepspeech : cannot find -lgsm -lmagic -lltdl

### ISSUE THREAD

**Issue by rohith-krish** [mozilla/DeepSpeech#2973]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:  source code
git checkout origin/r1.15
- **TensorFlow version (use command below)**:
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.24.1
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
$ make deepspeech
c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` -fopenmp client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/rohith/ADG/mozilla/DeepSpeech_Binary/tensorflow/bazel-bin/native_client  -ldeepspeech  -Wl,-Bstatic `pkg-config --static --libs sox` -lgsm `pkg-config --static --libs libpng | cut -d' ' -f1` -lz -lmagic -lltdl -Wl,-Bdynamic -ldl
/usr/bin/ld: cannot find -lgsm
/usr/bin/ld: cannot find -lmagic
/usr/bin/ld: cannot find -lltdl
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1

Error occurring when make deepspeech
/usr/bin/ld: cannot find -lgsm
/usr/bin/ld: cannot find -lmagic
/usr/bin/ld: cannot find -lltdl

**Comment by kdavis-mozilla** [comment]
Did the TensorFlow ./configure step complete without error?

**Comment by rohith-krish** [comment]
> Did the TensorFlow ./configure step complete without error?

@kdavis-mozilla Yes it is done properly and also the **bazel build** is also completed properly.
Error is when executing the **make deepspeech**.

And i have one doubt whether we need to do the above steps ( Compiling DeepSpeech) if i want to build the DeepSpeech for Android Devices (https://github.com/mozilla/DeepSpeech/blob/v0.7.0/native_client/README.rst#android-devices)

**Comment by reuben** [comment]
> And i have one doubt whether we need to do the above steps

Only if you made changes to the code. We have a pre-built AAR that you can simply add as a dependency to your Android app, for example: https://github.com/mozilla/DeepSpeech-examples/blob/695f69bf6e5362428954c0706d32fe517153095d/android_mic_streaming/app/build.gradle#L37

See also the rest of that example: https://github.com/mozilla/DeepSpeech-examples/tree/r0.7/android_mic_streaming

The error you got is due to missing libraries. They should be installed as dependencies of libsox-dev.

**Comment by rohith-krish** [comment]
@reuben I have one more doubt could you please help.
I have continued training of en_US model file using some of my voice files and i wanted to use the newly trained model in my android application . Whether i need to only export the tflite file and use it in the android application or is there is any additional files or steps i need to execute for the same.

**Comment by reuben** [comment]
Just exporting is fine. Have you tried it?

Also please use Discourse for discussion.

**Comment by GaurangTandon** [comment]
[This SO answer](https://stackoverflow.com/a/42339395) helped me get past this error. I'm on Ubuntu 18.04, and I simply did `sudo apt install libgsm-dev libmagic-dev` as referred to in the SO answer. It did help me get past this error (however, I got another error later :(

**Comment by Shridharpawar77** [comment]
Installation od libgsm-dev helped solve the -lgsm error but -lltdl error is not resolved after installation of libmagic-dev
