### ISSUE TITLE
How do I get the latest ds-ctcdecoder package for deepspeech7

### ISSUE THREAD

**Issue by krutika23** [mozilla/DeepSpeech#2975]
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:

This URL says no resource found:
https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.7.0.cpu-ctc/artifacts/public/ds_ctcdecoder-0.7.0-cp37-cp37m-manylinux1_x86_64.whl'

where do I get the package?
running python setup.py install gives me this error
I want to make my custom scorer using generate_package.py

**Comment by lissyx** [comment]
>     * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
> 
> 
> This URL says no resource found:
> https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.7.0.cpu-ctc/artifacts/public/ds_ctcdecoder-0.7.0-cp37-cp37m-manylinux1_x86_64.whl'

This URL works fine.

> 
> where do I get the package?
> running python setup.py install gives me this error
> I want to make my custom scorer using generate_package.py

This is not a bug, for the third time, use Discourse to reach support.
