### ISSUE TITLE
Training DeepSpeech on new datasets is not clear. I follow the steps mentioned in document. After cloning deepspeech git. i ran the 'pip3 install -r requirements.txt'. But there in no requirement file. Also i am not able to install 'pip3 install $(python3 util/taskcluster.py --decoder). It shows error' usage: taskcluster.py [-h] [--target TARGET] [--arch ARCH]                       [--artifact ARTIFACT] [--source SOURCE]                       [--branch BRANCH] taskcluster.py: error: unrecognized arguments: --decoder ERROR: You must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by tusharrakshe** [mozilla/DeepSpeech#2991]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by reuben** [comment]
You're reading the wrong docs for the version of the code you're using. If you're using v0.7.1, read the v0.7.1 docs.

**Comment by tusharrakshe** [comment]
Please provide the correct document link.
I am using 0.7.0 version.
