### ISSUE TITLE
Integrate updating release tag as latest doc on readthedocs

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#2993]
Either the scriptWorker code or the readthedocs integration should allow to mark a new released tag as the new default version on readthedocs

**Comment by reuben** [comment]
DeepSpeech side task added in #2999.
Initial changes added to scriptworker here: https://github.com/mozilla/deepspeech-pkguploadworker/compare/1e4ef28e463cd17f5298278d445020a78f2864af...ad10a9019f2e45751da419290c9dd16546c9f7a1

Need to make some changes to avoid publishing prerelease versions, and double check what happens with the "latest" version and whether we really need to trigger builds manually.

**Comment by reuben** [comment]
Done.
