### ISSUE TITLE
[Windows 10] Pip install deepspeech error

### ISSUE THREAD

**Issue by rwalte25** [mozilla/DeepSpeech#2997]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Enterprise V 1909 Build 18363.836
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: No
- **TensorFlow version (use command below)**: N/A
- **Python version**: Python 3.6.3
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: pip install deepspeech

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.
----------------------------------------------------------------------------
In advance, I apologize if this is a setup error or a lack of understanding on my end. I've attempted to do all the back research I can but have come up empty-handed, so I humbly turn to you. 

In attempting to get deepspeech on my Windows machine I've come across a "could not find a version that satisfies the requirement deepspeech" error and the installation fails.

From searching the web all other instances of this have been met with "deepspeech does not support Windows," but all of these are old (ex. this post from 2018: https://github.com/mozilla/DeepSpeech/issues/1521 and this post from early 2019: https://stackoverflow.com/questions/55540656/pip-unable-to-find-deepspeech-deepspeech-gpu-from-versions-on-windows)

DS as of 0.7.1 explicitly says it supports Windows. Does this only apply to building from source?

Any direction would be much appreciated. I am attaching the output of `pip install deepspeech --verbose`
[pip_ds_log.txt](https://github.com/mozilla/DeepSpeech/files/4640927/pip_ds_log.txt)

**Comment by lissyx** [comment]
> **Python version**: Python 3.6.3

Can you verify it is 64-bits version of Python?

**Comment by rwalte25** [comment]
I was running a 32-bit version of 3.6, but I have since made a 3.8-64 bit install and pip worked to download deepspeech on that. Thank you!

As a note: on the "Supported Platforms" page of 0.7.1 "Windows 8.1, 10, and Server 2012 R2 64-bits" was ambiguous to me--I thought only the Server 2012 required the 64-bit from this, but I suppose the "bitS" should have hinted otherwise.
