### ISSUE TITLE
Creation of code to load Fisher+Switchboard and format for the python_speech_features package

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#3]

**Comment by kdavis-mozilla** [comment]
There is a Python package [python_speech_features](https://pypi.python.org/pypi/python_speech_features/0.4) that can be used to calculate MFCC features.

**Comment by reuben** [comment]
Fixed by commit bc8b046605328a2577d8093bbb7eb9f0625261a9.
