### ISSUE TITLE
Measuring performance/space impact of the parallel_iterations parameter in tf.nn.bidirectional_dynamic_rnn

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#300]

**Comment by tilmankamp** [comment]
A test with `parallel_iterations` set to 16, 32 (default), 256 and 1024 (each with 1000 and 10000 samples per epoch) didn't show any difference in performance.

**Comment by tilmankamp** [comment]
@kdavis-mozilla @reuben I vote for closing this.

**Comment by kdavis-mozilla** [comment]
@tilmankamp I'd say we shouldn't close this yet. Picking the correct number of thread to use for CUDA code is delicate and likely needs more thought.
