### ISSUE TITLE
Slow Inference Speed Raspberry Pi 3B

### ISSUE THREAD

**Issue by hankp46** [mozilla/DeepSpeech#3000]
Running Deepspeech on a raspberry Pi3b yields following results:
pi@raspberrypi:./deepspeech --model deepspeech-0.7.1-models.tflite --scorer deepspeech-0.7.1-models.scorer --audio testlastb.wav
Loading model from file deepspeech-0.7.1-models.tflite
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.1-0-g2e9c281
Loaded model in 0.0037s.
Loading scorer from files deepspeech-0.7.1-models.scorer
Loaded scorer in 0.000744s.
Running inference.
back
Inference took 10.495s for 4.195s audio file.

Any suggestions on how to reduce inference time?

**Comment by lissyx** [comment]
> Running Deepspeech on a raspberry Pi3b yields following results:
> pi@raspberrypi:./deepspeech --model deepspeech-0.7.1-models.tflite --scorer deepspeech-0.7.1-models.scorer --audio testlastb.wav
> Loading model from file deepspeech-0.7.1-models.tflite
> TensorFlow: v1.15.0-24-gceb46aa
> DeepSpeech: v0.7.1-0-g2e9c281
> Loaded model in 0.0037s.
> Loading scorer from files deepspeech-0.7.1-models.scorer
> Loaded scorer in 0.000744s.
> Running inference.
> back
> Inference took 10.495s for 4.195s audio file.
> 
> Any suggestions on how to reduce inference time?

As documented, we cannot achieve realtime on RPi3 models. Except training your own model with smaller `n_hidden`, there is no solution so far.
