### ISSUE TITLE
Threaded inference

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#3003]
When I run the command-line deepspeech app, it doesn't seem to make full use of my multi-core CPU:

```
top - 19:39:00 up  2:44,  0 users,  load average: 1.00, 1.02, 1.00
Threads:  39 total,   2 running,  37 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.7 us,  0.1 sy,  0.0 ni, 91.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  7640028 total,  4776016 free,   838948 used,  2025064 buff/cache
KiB Swap:  1048572 total,  1048572 free,        0 used.  6573860 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
   46 root      20   0 2907816 1.306g 930788 S 66.8 17.9  86:49.35 deepspeech
   69 root      20   0 2907816 1.306g 930788 R 19.9 17.9  13:12.01 deepspeech
   67 root      20   0 2907816 1.306g 930788 S  6.6 17.9  12:40.39 deepspeech
   68 root      20   0 2907816 1.306g 930788 S  6.3 17.9  17:31.61 deepspeech
   47 root      20   0 2907816 1.306g 930788 S  0.7 17.9   1:03.30 deepspeech
   48 root      20   0 2907816 1.306g 930788 S  0.7 17.9   1:03.28 deepspeech
   55 root      20   0 2907816 1.306g 930788 S  0.7 17.9   1:03.26 deepspeech
   56 root      20   0 2907816 1.306g 930788 S  0.7 17.9   1:03.42 deepspeech
   57 root      20   0 2907816 1.306g 930788 S  0.7 17.9   1:03.47 deepspeech
   49 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.57 deepspeech
   50 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.34 deepspeech
   51 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.44 deepspeech
   52 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.21 deepspeech
   53 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.33 deepspeech
   54 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.27 deepspeech
   58 root      20   0 2907816 1.306g 930788 S  0.3 17.9   1:03.65 deepspeech
   70 root      20   0 2907816 1.306g 930788 S  0.3 17.9  18:24.65 deepspeech
```
It looks like the majority of the work gets done in a single thread and most of the other threads are idle.

It seems like there could be a big performance win by splitting up the audio file into sections and transcribing them in parallel (obviously this would only work with pre-recorded clips and not live streaming). There would probably also need to be some overlap in time between sections so that the scorer has sufficient context for the sentence.

**Comment by lissyx** [comment]
Threading is already handled by tensorflow. Adding our own layer will likely add issues : this is already the case with tflite threading on r2.2. I'm unsure about the use case you describe: if you have pre-recorded data you need to run in volume, the API is maybe not the best way and relying on evaluate.py will yield much better results.

**Comment by lissyx** [comment]
> splitting up the audio file into sections and transcribing them in parallel (obviously this would only work with pre-recorded clips and not live streaming).

Doing that at timestep level might work but I fear the setup costs would kill the win

**Comment by lissyx** [comment]
> It looks like the majority of the work gets done in a single thread and most of the other threads are idle.

Please profile with perf and time : each time we verified there was a linear speedup in the number of threads until reaching the number of cores available, i.e., tensorflow threading was already doing its best usage of the ressources, and spawning more parallel threads would not help in the long run but put more pressure on the system.

**Comment by dabinat** [comment]
> Threading is already handled by tensorflow.

That's different though. Tensorflow is trying to thread processing of the model (as much as that can be parallelized) but is still processing the audio sequentially. What I'm talking about is splitting up the audio into segments (say 30 secs each in length) prior to processing and then running inference on each segment independently in parallel. This would likely not be worth the setup performance on short files but could have a big impact on files of a longer duration.

The whole reason this came up is that I had a customer upload a 3 hour file and submit it for inference. (I think the previous longest file was around 2 hours, which worked fine.) Normally I get around 3x realtime performance but in this case it's been more than 3 hours and it's still running inference. So I'm getting sub-realtime performance on longer files, and when I looked in `top -H` it wasn't doing a great deal (after I posted this two other cores got to around 20% but still nowhere near what my system is capable of).

But I understand that not every use case is the same and not everyone needs to transcribe massive files. I've just been calling the command-line version of DeepSpeech from my app for simplicity of installation, but maybe I've outgrown it now and need to use the API directly.

**Comment by reuben** [comment]
This is what transcribe.py does. We don't have any immediate plans of doing that in the native client, as it is focused on low latency (live) streaming recognition, and you're asking for high throughput batch recognition.

In terms of technical feasibility I guess there could be a check when a long enough audio buffer is provided, which enables a separate throughput optimized path.

**Comment by lissyx** [comment]
> The whole reason this came up is that I had a customer upload a 3 hour file and submit it for inference. (I think the previous longest file was around 2 hours, which worked fine.) Normally I get around 3x realtime performance but in this case it's been more than 3 hours and it's still running inference. So I'm getting sub-realtime performance on longer files, and when I looked in `top -H` it wasn't doing a great deal (after I posted this two other cores got to around 20% but still nowhere near what my system is capable of).

Even more reason to carefully analyze: if you had 3x realtime performance and this one is much slower, there might be something else that explains and your problem might become much more non trivial than "divide and conquer".
