### ISSUE TITLE
DeepSpeech 0.7.1 - confidence value is sometimes positive

### ISSUE THREAD

**Issue by cnair-83** [mozilla/DeepSpeech#3004]
The Metadata confidence parameter giving negative value for proper recognition.

Please find below the results with 0.7.1 released model and scorer.

/deepspeech --model deepspeech-0.7.0-models.tflite --scorer deepspeech-0.7.0-models.scorer --json --audio /data/local/test_data/2.wav <
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=58880
{
"metadata":{"**confidence":-25.3747**},"words":[{"word":"alexa","time":0.78,"duration":0.28}],
"alternatives":[
{"metadata":{"confidence":-10.7203},"words":[{"word":"alex","time":0.78,"duration":0.24}]},
{"metadata":{"confidence":-24.7374},"words":[{"word":"alaka","time":0.78,"duration":0.3}]}
]
}

/deepspeech --model deepspeech-0.7.0-models.tflite --scorer deepspeech-0.7.0-models.scorer --json --audio /data/local/test_data/3.wav <
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=58880
{
"metadata":{"**confidence":-25.784**},"words":[{"word":"alexa","time":0.76,"duration":0.36}],
"alternatives":[
{"metadata":{"confidence":-11.6792},"words":[{"word":"alex","time":0.76,"duration":0.32}]},
{"metadata":{"confidence":-10.141},"words":[{"word":"alec","time":0.76,"duration":0.3}]}
]
}

https://drive.google.com/drive/folders/1oYwmXVswgJUpfZDHu8r1GDJmSUjaMkfB?usp=sharing

**Comment by kdavis-mozilla** [comment]
This is expected. Confidence for a word corresponds to "roughly the sum of the acoustic model logit values for each timestep/character that contributed to the creation of" the word.

See, for example, the [confidence documentation](https://github.com/mozilla/DeepSpeech/blob/430132c5a50f79c8cb28851e94963f8e10926d17/native_client/deepspeech.h#L45) in deepspeech.h

**Comment by cnair-83** [comment]
In that case, in the above example,   
{
"metadata":{"confidence":-25.3747},"words":[{"word":"alexa","time":0.78,"duration":0.28}],
"alternatives":[
{"metadata":{"confidence":-10.7203},"words":[{"word":"alex","time":0.78,"duration":0.24}]},
{"metadata":{"confidence":-24.7374},"words":[{"word":"alaka","time":0.78,"duration":0.3}]}
]
}
word 'alexa' is having confidence of -25.3747, but for the alternative options like 'alex' which is having confidence value of '-10.7203'. Since both are negative values, alex is having a better confidence right ?

**Comment by kdavis-mozilla** [comment]
Correct.

**Comment by cnair-83** [comment]
But only one confusion here is that, if I run the above command without --json option. 
deepspeech --model deepspeech-0.7.0-models.tflite --scorer deepspeech-0.7.0-models.scorer  --audio /data/local/test_data/3.wav                                                                                     <
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=58880
alexa

I get the output 'alexa' and it is correct also, but 'alex' is having a better confidence ('-10.7203') value than alexa.

**Comment by kdavis-mozilla** [comment]
2.wav vs. 3.wav?

**Comment by cnair-83** [comment]
No, its with 3.wav only

deepspeech --model deepspeech-0.7.0-models.tflite --scorer deepspeech-0.7.0-models.scorer --json --audio /data/local/test_data/3.wav <
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=58880
{
"metadata":{"confidence":-25.784},"words":[{"word":"alexa","time":0.76,"duration":0.36}],
"alternatives":[
{"metadata":{"confidence":-11.6792},"words":[{"word":"alex","time":0.76,"duration":0.32}]},
{"metadata":{"confidence":-10.141},"words":[{"word":"alec","time":0.76,"duration":0.3}]}
]
}

Here the actual output which is 'alexa' is having confidence value of -25.784, but the words which are in the alternatives like 'alex' having confidence -11.6792, in-fact which is better then the actual output(alexa) confidence(-25.784) value.

**Comment by reuben** [comment]
The crucial fact is that the confidence is computed from the acoustic model alone. In this case, it looks like the LM scoring is causing the seemingly lower confidence result to be returned first. You can remove the post-processing step in `DecoderState::decode` if you want to take a look at the raw scores that were used to sort the list.

**Comment by cnair-83** [comment]
Please find the results without scorer 

deepspeech --model deepspeech-0.7.0-models.tflite  --json --audio /data/local/test_data/3.wav                                                                                                                      <
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=58880
{
"metadata":{"confidence":**1.24544**},"words":[{"word":"**alexa**","time":0.76,"duration":0.38}],
"alternatives":[
{"metadata":{"confidence":**1.51901**},"words":[{"word":"**alaxa**","time":0.76,"duration":0.38}]},
{"metadata":{"confidence":**2.47905**},"words":[{"word":"**alexsa**","time":0.76,"duration":0.68}]}
]
}

Here also the alternate words (alexsa) having a better confidence than actual output alexa.

**Comment by kdavis-mozilla** [comment]
Questions...

1. What is the output of 
> `deepspeech --model deepspeech-0.7.0-models.tflite --audio /data/local/test_data/3.wav`
2. Can you share 3.wav

**Comment by cnair-83** [comment]
1. deepspeech --model deepspeech-0.7.0-models.tflite --audio /data/local/test_data/3.wav
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
INFO: Initialized TensorFlow Lite runtime.
audio_format=1
num_channels=1
sample_rate=16000 (desired=16000)
bits_per_sample=16
res.buffer_size=58880
alexa

2. both 2.wav and 3.wav at below location
https://drive.google.com/drive/folders/1oYwmXVswgJUpfZDHu8r1GDJmSUjaMkfB?usp=sharing

**Comment by cnair-83** [comment]
any update ?

**Comment by cnair-83** [comment]
will this pull request will solve this issue?

**Comment by kdavis-mozilla** [comment]
What PR? #2911 was (mistakenly) linked and unlinked from this issue.

**Comment by cnair-83** [comment]
So why are we getting high negative confidencevalue  for correct recognition ?

**Comment by reuben** [comment]
Should be simpler to reason about the values after #3021, confidence values are simply log probs.

**Comment by harmandeepsinghkalsi** [comment]
I am 0.7.4 DeepSpeech version and seeing the confidence value is negative and not correct among the candidate transcripts

**Comment by BlkPingu** [comment]
The confidence score is neither easy to understand, intuitive or well documented. Is there a source other than a comment in the source code that is outlining the idea of what the confidence score means? Ideally something citable?
