### ISSUE TITLE
DLL issues with Conda environment

### ISSUE THREAD

**Issue by ZacASTaylor** [mozilla/DeepSpeech#3005]
I tried to add deepspeech to an existing Django project by using pip to add it to my Conda virtual environment (`pip install deepspeech`). I used Pycharm's virtual environment initialization tool to make the Conda environment. When I try to run deepspeech from the command line or programatically with the [code on readthedocs](https://deepspeech.readthedocs.io/en/v0.7.1/Python-Examples.html#py-api-example) I get and error that states:
```
File "c:\users\zacha\anaconda3\envs\djangotest\lib\site-packages\deepspeech\impl.py", line 13, in <module>
    from . import _impl
ImportError: DLL load failed while importing _impl: The specified module could not be found.
```

I made two other virtual environments: one by hand (`python3 -m venv ...`) and another using Pycharm's virtual environment initialization tool but to make a local (to the project) virtual environment rather than a Conda environment. Running deepspeech works fine in both of these virtual environments.

OS: Windows 10 - 1909

**Comment by reuben** [comment]
Conda causes all kinds of weird things for native code (and Python code too lots of the time), which breaks our packages. We document and support only virtualenv and venv.
