### ISSUE TITLE
Request: Support audio from AWS S3 or Google Cloud Storage

### ISSUE THREAD

**Issue by piraka9011** [mozilla/DeepSpeech#3007]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04, Mac OS 10.15
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Upstream
- **TensorFlow version (use command below)**: 1.15
- **Python version**: 3.7
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: Tesla T4
- **Exact command to reproduce**: N/A

I have made some modifications for DS so that it loads data from a cloud URL like `s3` or `gs` (AWS and Google Cloud (GC) respectively).
I was wondering if the maintainers would be interested in such a feature contributed back towards `master`?

This will add the overhead of including AWS/GC Python Modules (`boto3` and `google.storage`), however, it looks it might be possible to include them as optional dependencies.

**Comment by lissyx** [comment]
Could you describre the usecase here? Even as optional, that's a non trivial amount of work and maintenance to consider.

**Comment by piraka9011** [comment]
Ex. I have 5 million audio recordings in an S3 bucket that are over 1TB in size.
Instead of loading the audio locally and pointing the filename to the local directory, I can instead specify an S3 URL and DS would download and process the audio from there instead.

**Comment by lissyx** [comment]
Are we talking about training? Inference?

**Comment by lissyx** [comment]
Also you need to know that @tilmankamp worked hard of the topic of efficiency regarding training on our cluster and I fear this might be complicated. Have you got nice perfs out of this?

**Comment by dabinat** [comment]
I’ve being doing training on AWS and tried various methods of accessing the data in the cloud, including S3 (via FUSE) and Elastic File System. In my testing, network volumes are far too slow for training. I’m now using EBS volumes mounted directly on the instance.

**Comment by piraka9011** [comment]
> Are we talking about training? Inference?

Training. But it can be extended to inference as well.

> Have you got nice perfs out of this?

Performance will depend on the network since audio is stored in the cloud.
I don't have metrics but assuming you've optimized the audio in a cache or similar it should be 'fast'. If necessary, I might be able to do some measurements.

**Comment by piraka9011** [comment]
> I’m now using EBS volumes mounted directly on the instance.

I also tried to use EFS and between the setup and speed, I found it to be too cumbersome and just went with an expanded EBS like you did.

**Comment by lissyx** [comment]
> Training. But it can be extended to inference as well.

For training, I'm already doubtful of the performances, but for inference it's unilkely to be a good idea


> 
> Performance will depend on the network since audio is stored in the cloud.
> I don't have metrics but assuming you've optimized the audio in a cache or similar it should be 'fast'. If necessary, I might be able to do some measurements.

Training experience says otherwise, and also forces me to believe only properly validated numbers.
I mean, let's be realistic two seconds: the cloud is not magic, there will be data tranfer at some point.
And if you do it live during the training, you need to have sustained network performances from the cloud to feed your GPUs.

**Comment by piraka9011** [comment]
I see. Given that you've already seen from experience this isn't a good idea, we can probably just close this.

I'd like to know from your experience though if the simplest solution (local storage) is the best solution or if there is a better solution for storing large amounts of training data?

**Comment by lissyx** [comment]
> I see. Given that you've already seen from experience this isn't a good idea, we can probably just close this.
> 
> I'd like to know from your experience though if the simplest solution (local storage) is the best solution or if there is a better solution for storing large amounts of training data?

it's really @tilmankamp who can give useful feedback here.
