### ISSUE TITLE
Bug in the CV2 Importer.

### ISSUE THREAD

**Issue by MrKinauJr** [mozilla/DeepSpeech#3008]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: regular pip
- **TensorFlow version (use command below)**: v1.15.0-92-g5d80e1e8e6 1.15.2
- **Python version**: python 3.7.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10 / 7,6
- **GPU model and memory**: RTX 2060
- **Exact command to reproduce**: py bin/import_cv2.py tsv_path

I tried starting the Importer for the Mozilla Voice Courpus and it instantly errored out because it can't find the method label_filter_fun. I tried reinstalling python but that didn't really help. 

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\kin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\kin\DeepSpeech\bin\import_cv2.py", line 61, in one_sample
    label = label_filter_fun(sample[1])
NameError: name 'label_filter_fun' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/import_cv2.py", line 209, in <module>
    _preprocess_data(PARAMS.tsv_dir, AUDIO_DIR, PARAMS.space_after_every_character)
  File "bin/import_cv2.py", line 36, in _preprocess_data
    set_samples = _maybe_convert_set(dataset, tsv_dir, audio_dir, space_after_every_character)
  File "bin/import_cv2.py", line 112, in _maybe_convert_set
    for i, processed in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "C:\Users\kin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 748, in next
    raise value
NameError: name 'label_filter_fun' is not defined

```

**Comment by lissyx** [comment]
> NameError: name 'label_filter_fun' is not defined

It should be defined within `bin/import_cv2.py`. Please note we don't support training on Windows, so it's not surprising it is breaking.

**Comment by MrKinauJr** [comment]
> It should be defined within bin/import_cv2.py.
Well yeah it's in the code. But as soon as it tries to calls it it somehow undefined. I have no idea why. Seems like a weird issue since it works on Ubuntu. But since training on Windows isn't support i guess i'll have to install linux then. Anyways thanks for your help.

**Comment by reuben** [comment]
The way that code is written is broken, it's incompatible with some `multiprocessing` spawn methods, we should fix it. There are different default spawn methods on different platforms, which is probably why it's breaking on Windows.

**Comment by reuben** [comment]
@MrKinauJr can you try this version of the importer? https://github.com/mozilla/DeepSpeech/blob/import_cv2_multiprocessing/bin/import_cv2.py

**Comment by MrKinauJr** [comment]
tried. Seems to work. I will let it continue running in the meantime. will get back to you after it's finished to make sure.

**Comment by MrKinauJr** [comment]
```
Skipped 370976 samples that failed upon conversion.
Final amount of imported audio: 0:00:00.
Saving new DeepSpeech-formatted CSV file to:  C:\Users\kin\Downloads\de.tar\de\clips\validated.csv
Writing CSV file for DeepSpeech.py as:  C:\Users\kin\Downloads\de.tar\de\clips\validated.csv
Progress |#                                                                                            | 100% completed
Traceback (most recent call last):
  File "DeepSpeech-0.6.0/bin/import_cv2.py", line 222, in <module>
    main()
  File "DeepSpeech-0.6.0/bin/import_cv2.py", line 219, in main
    params.space_after_every_character)
  File "DeepSpeech-0.6.0/bin/import_cv2.py", line 42, in _preprocess_data
    filter_obj, rows=set_samples, exclude=exclude)
TypeError: _maybe_convert_set() got multiple values for argument 'rows'

```

**Comment by reuben** [comment]
Ah, looks like a leftover from argument reordering. I [pushed a fix](https://github.com/mozilla/DeepSpeech/commit/3d0ec01853fe9f5b73a6e35b0226e4c97c237655). The train, dev and test subsets should have completed in that run, if you're looking for validated, other, or train-all, you should be able to re-run with the fixed code and it'll skip the already done conversion work, so should be faster to continue from where it stopped. Thanks for testing!

**Comment by MrKinauJr** [comment]
no problem! will test again and close if there is no issue. ^^
