### ISSUE TITLE
[ FRAMEWORK ERROR ]  Cannot load input model: "The name 'cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph."

### ISSUE THREAD

**Issue by aishakhan22** [mozilla/DeepSpeech#3013]
Hi, 
I was trying to create a frozen model using the checkpoint files of deepspeech 0.7.1 with the openvino mo_tf.py, encountered the above error. could you please take a look at it. it will be  helpful

**Comment by kdavis-mozilla** [comment]
We currently don't support conversion using OpenVINO. Maybe the OpenVINO team could help?

That said, if you succeed in conversion using OpenVINO we'd be interested in hearing about tha result.

**Comment by reuben** [comment]
I don't know much about OpenVINO but this looks a bit like you forgot to specify `--load_cudnn`

**Comment by lissyx** [comment]
@aishakhan22 Could you please verify if it is `--load_cudnn` ?

**Comment by lissyx** [comment]
@aishakhan22 Gentle ping?

**Comment by aishakhan22** [comment]
Hi, 

> I don't know much about OpenVINO but this looks a bit like you forgot to specify `--load_cudnn`

This did not work, as it is not support by openvino IR conversion 
Openvino does not support the current architecture for now

**Comment by reuben** [comment]
That flag is precisely for when you don't have CUDNN training support, it loads CUDNN weights into a non-CUDNN graph. So it should not require any specific support in OpenVINO. You could also try exporting with the inference graph for TFLite (but without converting it to TFLite format) which is simpler.
