### ISSUE TITLE
Missing README.md in `data/lm`?

### ISSUE THREAD

**Issue by GaurangTandon** [mozilla/DeepSpeech#3016]
`data/README.md` mentions:

> For more information on how to build these resources from scratch, see data/lm/README.md

However, there is no README inside `data/lm`. Apparently, there definitely was something here since a [Discourse post from June 2019](https://discourse.mozilla.org/t/tune-moziiladeepspeech-to-recognize-specific-sentences/41350/24) links to the `data/lm` folder as "is worth refering to here for some basic detail on the LM".

**Comment by GaurangTandon** [comment]
Oh, it seems the README was [deleted two days ago](https://github.com/mozilla/DeepSpeech/commit/4356a2764ba086dc7f4049d4c90a4d07d482b3f0#diff-e2c75e1291adb7721238fa0b7eee5f95). I am not sure what "RTD" is (in the commit message)? And should I refer to the old README, or has there been some content changes as well to the README?

**Comment by reuben** [comment]
RTD is ReadTheDocs. Those docs are now here: https://deepspeech.readthedocs.io/en/master/Scorer.html

Thanks for noticing the dangling reference in data/README.rst, I'll update it.

**Comment by reuben** [comment]
And the v0.7.1 version here: https://github.com/mozilla/DeepSpeech/tree/v0.7.1/data/lm/
