### ISSUE TITLE
Mp3 file support

### ISSUE THREAD

**Issue by generosocarbone** [mozilla/DeepSpeech#3017]
Does the deepspeech client CLI have the support for mp3 files?
If no, is it planned?

**Comment by reuben** [comment]
The client in the native_client package relies on SoX to handle the input. On macOS it does support MP3, but I'm not sure if our release Linux binaries are linked against libmp3lame. You should be able to test quite easily, though.

**Comment by lissyx** [comment]
@generosocarbone Can you update us?

**Comment by generosocarbone** [comment]
Sorry for the late reply.
This is my configuration, 
I'm using the [DeepSpeech Italian Model](https://github.com/MozillaItalia/DeepSpeech-Italian-Model)
OS: ubuntu 18.04

These are the commands I use for the execution
$ virtualenv test --python=python3
$ source test/bin/activate
$ pip install deepspeech==0.7.0a1
$ deepspeech --model output_graph.pbmm --audio test.mp3 --trie trie --lm lm.binary

And this is the error I get

`Loading model from file output_graph.pbmm`
`TensorFlow: v1.15.0-24-gceb46aa`
`DeepSpeech: v0.7.0-alpha.1-0-g60cbe3b`
`2020-06-03 11:39:41.454455: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`
`Loaded model in 0.221s.`
`Loading language model from files lm.binary trie`
`Loaded language model in 0.131s.`
`Traceback (most recent call last):`
  `File "/home/generoso/java/deepseech/test/bin/deepspeech", line 8, in <module>`
 `   sys.exit(main())`
`  File "/home/generoso/java/deepseech/test/lib/python3.6/site-packages/deepspeech/client.py", line 126, in main`
`    fin = wave.open(args.audio, 'rb')`
`  File "/home/generoso/anaconda3/lib/python3.6/wave.py", line 499, in open`
`    return Wave_read(f)`
`  File "/home/generoso/anaconda3/lib/python3.6/wave.py", line 163, in __init__`
`    self.initfp(f)`
`  File "/home/generoso/anaconda3/lib/python3.6/wave.py", line 130, in initfp`
`    raise Error('file does not start with RIFF id')`
`wave.Error: file does not start with RIFF id`

At the moment I don't have the possibility to test it on macOs

**Comment by reuben** [comment]
That is the Python client (installed with pip), not the binary we provide in the native_client.tar.xz package. It doesn't support MP3 (on any platform).

**Comment by lissyx** [comment]
@generosocarbone Converting from different file format / audio format can raise very tricky issues, and it's a support burden that ends up as "deepspeech provides poor results" when it's just a matter of poor conversion. That's one of the reason we are not really keen to support that usecase, it's better you properly assert that your MP3 -> WAV conversion is correct before feeding.

**Comment by generosocarbone** [comment]
Ok, I'll check it out a different setup and let you know. Thanks for the
support

**Comment by kdavis-mozilla** [comment]
@generosocarbone Any news?

**Comment by lissyx** [comment]
@generosocarbone Could you update us ?

**Comment by generosocarbone** [comment]
Sorry guys, but I've been moved on a different project and I couldn't make
any progress.

**Comment by dag7dev** [comment]
@lissyx can't we use ffmpeg?

**Comment by lissyx** [comment]
> @lissyx can't we use ffmpeg?

Question is more: do we want to **support** this? Do we want to have to deal with specific weird bugs coming from that?

**Comment by dag7dev** [comment]
> 
> 
> > @lissyx can't we use ffmpeg?
> 
> Question is more: do we want to **support** this? Do we want to have to deal with specific weird bugs coming from that?

Well, personally dealing with more bugs it is not the most efficient thing we can choose...
