### ISSUE TITLE
Why is my WER so bad?    

### ISSUE THREAD

**Issue by MikeyBeez** [mozilla/DeepSpeech#3018]
Thank you for writing such an interesting program.  

I'm running ubuntu 18.04 with an NVIDIA 1050ti GPU.  
I've installed the examples using git clone.  And I've run the following:

`python -m pip install deepspeech-gpu` into a conda virtual environment.
  
I've `conda install pyaudio` and `python -m pip install -r requirements.txt`  I've downloaded the 6.0 7.0 and 7.1 models in to the examples directory. 

From within the examples directory I run: 
`python ./mic_vad_streaming/mic_vad_streaming.py -m ./deepspeech-0.7.1-models.pbmm
`
The accuracy is terrible.  Vosk Kaldi is far superior.  

I feel I must be doing something wrong or suboptimal.  How can I get a halfway decent WER?

**Comment by reuben** [comment]
The issue template you ignored and deleted in order to post this issue clearly states GitHub issues are not meant for support. Use Discourse.
