### ISSUE TITLE
No Bazel configuration present for Tensorflow r1.15

### ISSUE THREAD

**Issue by GaurangTandon** [mozilla/DeepSpeech#3019]
The [native_client page](https://github.com/mozilla/DeepSpeech/tree/master/native_client) mentions to:

> Clone our fork of TensorFlow and checkout the correct version:

where they show `git checkout origin/r1.15` as the version. However, on the [linked page](https://www.tensorflow.org/install/source#tested_build_configurations) for Bazel configuration under the next heading, all the tables are missing details for release 1.15. Only TF versions upto 1.14, and then straight from TF 2.0 are shown.

----

Sidenote: In my attempt to generate scorer files, I was using [data/lm/generate_package.py](https://github.com/mozilla/DeepSpeech/tree/master/data/lm), however, it gave me a `ModuleNotFoundError` for `ds_ctcdecoder`. I hope I am on the correct path to fix it, by following instructions in `native_client`.

**Comment by reuben** [comment]
Huh, TensorFlow really messed up the documentation around 1.15. It's 0.24.1. I'll include that inline in the README.
