### ISSUE TITLE
Runs our code without warp-ctc to see if this removes the crash

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#302]

**Comment by lissyx** [comment]
We enabled WarpCTC just very recently, way after we had the problems.

**Comment by tilmankamp** [comment]
First runs for [1](https://github.com/mozilla/DeepSpeech/issues/284#issuecomment-268496752) were done with WarpCTC and crashed/rebooted. After switching to classic CTC, there were no crashes/reboots anymore.

**Comment by kdavis-mozilla** [comment]
I want to do a long run over the Holiday weekend _not_ using warp-ctc to hopefully get a better picture as to if warp-ctc is causing our crashes.

**Comment by kdavis-mozilla** [comment]
Currently seems stable with out warp-ctc.
