### ISSUE TITLE
What happens when tansfer learning without extra lm?

### ISSUE THREAD

**Issue by vcjob** [mozilla/DeepSpeech#3031]
Hello everyone!

My question might be asked not in the right place, sorry for that.
According to the https://deepspeech.readthedocs.io/en/v0.7.1/TRAINING.html , to do a Transfer-Learning with new alphabet I just need to use command:
 ```
python3 DeepSpeech.py \
    --drop_source_layers 1 \
    --alphabet_config_path my-new-language-alphabet.txt \
    --save_checkpoint_dir path/to/output-checkpoint/folder \
    --load_checkpoint_dir path/to/release-checkpoint/folder \
    --train_files   my-new-language-train.csv \
    --dev_files   my-new-language-dev.csv \
    --test_files  my-new-language-test.csv
```

BUT here comes the question, what happens to the language model? Is the new one created? Where it is stored than? Or the old one is also transferred to the new language and alphabet?

Thank you for the answer!

**Comment by reuben** [comment]
> My question might be asked not in the right place, sorry for that.

No need to apologize. The issue template you deleted when posting this tells exactlu where to post this, on Discourse: https://discourse.mozilla.org/c/deep-speech

In any case, the language model is created independently from the training of an acoustic model. We've recently added some more docs to ReadTheDocs with some instructions on how to create your own: https://deepspeech.readthedocs.io/en/master/Scorer.html and https://deepspeech.readthedocs.io/en/master/Decoder.html
