### ISSUE TITLE
node v14 not supported

### ISSUE THREAD

**Issue by benbucksch** [mozilla/DeepSpeech#3038]
- **OS Platform and Distribution**: node v14.4.0 on Ubuntu 20.04, AMD64 and Rasp Pi 4, Rasbian

**Reproduction:**

1. Install node v14.4.0
2. Load deepspeech module

**Actual result:**

```
Error: Cannot find module '.../node_modules/deepspeech/lib/binding/v0.7.1/linux-x64/node-v83/deepspeech.node'
Require stack:
- /mnt/compile/source/voice/pia/node_modules/deepspeech/index.js
```

**Cause**:

ABI v83 is not included. Highest ABI included is v79.

**Expected result:**

1. Binaries for current node releases (as published on https://nodejs.org ) are included.
2. There is an easy, documented way (in INSTALL.md) to generate new binaries, or better yet, it happens automatically when the binary is missing.

**Comment by benbucksch** [comment]
See #2032 for an earlier instance of the same problem, with hints for self-compilation.

**Comment by benbucksch** [comment]
DUP of #3027

The npm module was uploaded right **after** I filed this, so this should be FIXED now.

**Comment by lissyx** [comment]
> There is an easy, documented way (in INSTALL.md) to generate new binaries, or better yet, it happens automatically when the binary is missing.

Unfortunately, this is **not** easy, because you still need `libdeepspeech.so` for linkage, and because SWIG-based wrapper generation is complicated.

**Comment by benbucksch** [comment]
I noticed :-)

I understand that it's non trivial to create such build scripts to automate the process. Should I file an another enhancement ticket for this point? Because this will keep happening that node updates and somebody installs the update before you.

**Comment by reuben** [comment]
If you look at what was changed in PR #3027, you'll see that it's not a matter of how complicated a build script is, sometimes it's not even possible to automate it (as was with this version). In this case, we had to wait for node-pre-gyp to be updated first. Sometimes, the build will start to fail due to some SWIG incompatibility, etc. NodeJS is a mess, it's not possible to simply hit a button and get support for a new platform.

**Comment by benbucksch** [comment]
Yeah, I took a brief look at the patch and got scared when I looked over the changes to 45 files, no less.

> In this case, we had to wait for node-pre-gyp to be updated first.

Do these situations appear most of the time, or only 1 out of 5 times? If the latter, a script might still be useful for the 4 cases.

> NodeJS is a mess

Agrees. Extremely useful, but very patchy in its implementation.

**Comment by benbucksch** [comment]
BTW: @lissyx : Thanks for having made these changes and having fixed #3027!
I confirm that deepspeech 0.7.3 npm package now loads with node 14.4.0. I'm still working on adapting to the new API.

**Comment by lissyx** [comment]
> Of course, even if useful, you might still leave it as "help wanted" enhancement.

I seriously doubt, given that I have shared patches as a PR against SWIG to bring support from 10+ to newer versions, and I still failed to get help from maintainers to run it on Travis.

V8 changes frequently enough that it's more trouble setting up the necessary bits for allowing people to build the wrapper than to just wait for us to ship an update.

**Comment by benbucksch** [comment]
I see. Fair enough.
Thanks for all the efforts!

**Comment by benbucksch** [comment]
DeepSpeech 0.7.3 working for me on node 14.4.0 now, in my app.
VERIFIED FIXED.
