### ISSUE TITLE
 pcm_to_np : audio_format and segment_buffer must be swapped!

### ISSUE THREAD

**Issue by vcjob** [mozilla/DeepSpeech#3039]
Hello everyone!

While trying to transcribe a file, I realized that in the training/deepspeech_training/util/feeding.py there's an error on the line:
`samples = pcm_to_np(audio_format, segment_buffer)`
It must be actually opposite order:
`samples = pcm_to_np(segment_buffer, audio_format)`
according to the function description on training/deepspeech_training/util/audio.py

Otherwise it causes an error like "bytes has no attribute channels" or so

**Comment by lissyx** [comment]
Thanks but #3030 has already been submitted :)

**Comment by lissyx** [comment]
This was merged.
