### ISSUE TITLE
DeepSpeech version (0.7.3) and CTC decoder version (0.7.1) do not match.

### ISSUE THREAD

**Issue by alexstr22** [mozilla/DeepSpeech#3040]
Hi!
I follow the instruction (https://deepspeech.readthedocs.io/en/v0.7.1/TRAINING.html) and faced with problem below:
DeepSpeech version (0.7.3) and CTC decoder version (0.7.1) do not match. Please ensure matching versions are in use.
How can I solve it?

**Comment by reuben** [comment]
When you update the code, you need to reinstall the training code and update any dependencies, otherwise you end with mismatched versions. Just follow the normal installation step: https://deepspeech.readthedocs.io/en/v0.7.1/TRAINING.html#installing-deepspeech-training-code-and-its-dependencies
