### ISSUE TITLE
Publish decoder package on PyPI to avoid pip edge cases

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#3044]
Our current setup with a direct URL dependency on the decoder package requires the use of `--force-reinstall` when installing our training code, which reinstalls *everything*, not just upgraded packages. This is a pretty awkward setup, but required because pip has completely broken version handling with direct URL dependencies.

Two ways we make this better are:

  - Publishing the decoder package on PyPI
  - Publishing a simple HTML file with links to the various wheels and using `pip install --find-links`

Because I'm lazy, and the first option requires less work, I vote for it. All we have to do is publish the packages and then use a normal dependency specification. `pip install --upgrade` (and even a plain `pip install -e`, I think) should then pick up upgrades without reinstalling the world.

**Comment by reuben** [comment]
@kdavis-mozilla @lissyx @tilmankamp any objections?

**Comment by kdavis-mozilla** [comment]
Are we planning to document the decoder package as it would be "public"? (I'd guess not but I thought I'd ask.)

**Comment by reuben** [comment]
It's already public, somewhat documented, and we already have to deal support. I don't see PyPI publishing as any more public than what we currently have, just a way with less hacks to install it.

**Comment by kdavis-mozilla** [comment]
I guess I just meant "public", as in not only TC specific, but "public" in the "real" world, i.e. PyPi.

I'm fine with the move, I just want to have it publicly decided that we aren't going to pour lots on effort into documentation, beyond what we've already have.

**Comment by reuben** [comment]
Ah, OK. Yeah I think for now we keep our current understanding for documentation. We have previously defined the API boundary for compatibility, documentation, and support at the native client level rather than including the training code. Maybe it'd be good to explicitly mention this in the docs somewhere.
