### ISSUE TITLE
ERROR: AlignOutput: Can't determine stream position creating Scorer

### ISSUE THREAD

**Issue by carlfm01** [mozilla/DeepSpeech#3053]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: Yes, to remove the prune but is not working with pruning
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.4 LTS
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: default install of the deepspeech package 
- **TensorFlow version (use command below)**: v1.15.0-92-g5d80e1e 1.15.2
- **Python version**: Python 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0] on Linux
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```
python3 generate_lm.py --input_txt names-corpus.txt --output_dir out/ --top_k 9000000 --kenlm_bins ~/Desktop/ken/kenlm/build/bin --arpa_order 5 --max_arpa_memory "90%" --binary_a_bits 255 --binary_q_bits 8 --binary_type trie 

python3 generate_package.py --alphabet alphabet.txt --lm out/lm.binary --vocab out/vocab-9000000.txt --package pack/ --default_alpha 0.75 --default_beta 1.85
```

**Output:**
```
(deepspeech-venv) carlos@ubuntu:~/Desktop/scorer/DeepSpeech/data/lm$ python3 generate_package.py --alphabet alphabet.txt --lm out/lm.binary --vocab out/vocab-9000000.txt --package pack/ --default_alpha 0.75 --default_beta 1.85
49004 unique words read from vocabulary file.
Doesn't look like a character based model.
Using detected UTF-8 mode: False
ERROR: AlignOutput: Can't determine stream position
ERROR: Could not align file during write after header
Package created in pack/
swig/python detected a memory leak of type 'Alphabet *', no destructor found
```

This is also failing with a clean env install and my clean vm, both Spanish and English text.

Ds version:https://github.com/mozilla/DeepSpeech/commit/572963e7bd5c12f0355b5816bb4c9600b71e8dbe

KenLM version: https://github.com/kpu/kenlm/commit/87e85e66c99ceff1fab2500a7c60c01da7315eec

Thanks

**Comment by lissyx** [comment]
> ERROR: AlignOutput: Can't determine stream position
> ERROR: Could not align file during write after header

this error is not from kenlm, it's from openfst code


>  --top_k 9000000

can you verify with much less data?

What are your hardware specs here?


> Spanish and English text.

Where are those data from ? Can you repro with documented LM steps and git-provided data sources for the LM?

**Comment by carlfm01** [comment]
> can you verify with much less data?

Same with 500 words:
```
python3 generate_package.py --alphabet alphabet.txt --lm out/lm.binary --vocab out/vocab-500.txt --package pack/ --default_alpha 0.75 --default_beta 1.85
500 unique words read from vocabulary file.
Doesn't look like a character based model.
Using detected UTF-8 mode: False
ERROR: AlignOutput: Can't determine stream position
ERROR: Could not align file during write after header
Package created in pack/
swig/python detected a memory leak of type 'Alphabet *', no destructor found.
```
> What are your hardware specs here?

Ryzen 9 3900x
32 GB RAM
8TB storage, host disk and project disk with more than 120GB free space each

> Where are those data from ?

Spanish from a private source, English: http://www.openslr.org/resources/11/librispeech-lm-norm.txt.gz

> Can you repro with documented LM steps and git-provided data sources for the LM?

Yes, with the English norm text from libri of the guide.

**Comment by carlfm01** [comment]
> Spanish from a private

Generating the lm and trie using the old method works fine with this text.

**Comment by lissyx** [comment]
> > Spanish from a private
> 
> Generating the lm and trie using the old method works fine with this text.

Which old method?

**Comment by lissyx** [comment]
Can you verify if `out/lm.binary` was properly generated? Maybe issue is here.

**Comment by carlfm01** [comment]
lm and trie

> Which old method?

lm.binary and trie as separate files



> Can you verify if `out/lm.binary` was properly generated? Maybe issue is here

Looks correct with 1.7GB, let me test if I can still generate the trie out of it.

**Comment by carlfm01** [comment]
> let me test if I can still generate the trie out of it.

```
./generate_trie alphabet.txt  lm.binary trie
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/model.cc:70 in lm::ngram::detail::GenericModel<Search, VocabularyT>::GenericModel(const char*, const lm::ngram::Config&) [with Search = lm::ngram::trie::TrieSearch<lm::ngram::SeparatelyQuantize, lm::ngram::trie::ArrayBhiksha>; VocabularyT = lm::ngram::SortedVocabulary] threw FormatLoadException because `new_config.enumerate_vocab && !parameters.fixed.has_vocabulary'.
The decoder requested all the vocabulary strings, but this binary file does not have them.  You may need to rebuild the binary file with an updated version of build_binary.
```
Throws an error but I think it is just my old generate_trie. Hmm no idea honestly

**Comment by carlfm01** [comment]
> Can you verify if `out/lm.binary` was properly generated

An old client can load the lm.binary without issues

**Comment by lissyx** [comment]
>  8TB storage, host disk and project disk with more than 120GB free space each

Any specificity regarding the filesystem? rights? `tellp()` to fail on an output stream is weird ...

**Comment by lissyx** [comment]
@carlfm01 Could you catch the actual error value returned by `tellp()` ?

**Comment by lissyx** [comment]
>     * Ubuntu 18.04.4 LTS

Is this native or Windows for Linux ?

**Comment by carlfm01** [comment]
> Any specificity regarding the filesystem?

No.


> rights?

double-checked and folder and files got write read permissions.



> @carlfm01 Could you catch the actual error value returned by `tellp()` ?

Yes:
Finally re-compiled the decoder
tellp returns -1, reading the docs I should read the state, will try

**Comment by carlfm01** [comment]
> Is this native or Windows for Linux ?

I'm testing on a machine with Ubuntu 18.04.4 LTS as host SO, and a vm with Ubuntu 18.04.4 LTS running Windows 10 as host, both machines with the same error

**Comment by carlfm01** [comment]
The stream state returns badbit
Docs: "This flag is set by operations performed on the stream when an error occurs while read or writing data, generally causing the loss of integrity of the stream."

**Comment by carlfm01** [comment]
> --package pack/

I was so simple, looks like at some point lost the full path, and was only taking the dir path.

Now it works with `--package pack/lm.scorer`  

@lissyx Thanks for the help.

**Comment by lissyx** [comment]
@carlfm01 We should error out then, no?

**Comment by reuben** [comment]
Yeah we should be checking errors more carefully in `save_dictionary`. Basically check errors when opening the fstream and writing to it before we get to ConstFst::Write in the first place.

**Comment by lissyx** [comment]
@carlfm01 Could you test the PR https://github.com/mozilla/DeepSpeech/pull/3066 ? I'd like to make sure it is able to catch your error, but I suspect for proper fix we'd like to change the prototype of `save_dictionary` and make it return a bool to know whether it could write.

**Comment by carlfm01** [comment]
> @carlfm01 Could you test the PR #3066 ?

It did not print the error messages, the "lissyx  version" just to make sure is actually applying the change.

```
Looks like a character based model.
Using detected UTF-8 mode: True
-----------------lissyx  version-----------------------------------'pack/'
ERROR: AlignOutput: Can't determine stream position
ERROR: Could not align file during write after header
Package created in pack/
```



> taking the dir path.

I think to avoid my error it just needs to test if it is a directory and throw a message if the directory exists, like "please don't use a valid  directory as a name for the output scorer".

@lissyx I think your solution will works for the cases when there's no permission, issues with storage(like the user with network storage), full disk etc.

**Comment by lissyx** [comment]
> > @carlfm01 Could you test the PR #3066 ?
> 
> It did not print the error messages, the "lissyx version" just to make sure is actually applying the change.
> 
> ```
> Looks like a character based model.
> Using detected UTF-8 mode: True
> -----------------lissyx  version-----------------------------------'pack/'
> ERROR: AlignOutput: Can't determine stream position
> ERROR: Could not align file during write after header
> Package created in pack/
> ```
> 
> > taking the dir path.
> 
> I think to avoid my error it just needs to test if it is a directory and throw a message if the directory exists, like "please don't use a valid directory as a name for the output scorer".
> 
> @lissyx I think your solution will work for the cases when there's no permission, issues with storage(like the user with network storage), full disk etc.

well, according to the doc, `.bad()` should also work, but maybe it is legit to open a directory as a stream?

**Comment by lissyx** [comment]
Okay, testing locally `.bad()` seems to not catch the open error, but `!fout` does

**Comment by lissyx** [comment]
@carlfm01 Made the PR better and checking `!fout` does locally reproduce the error when trying to pass a directory

**Comment by carlfm01** [comment]
> `!fout` does locally reproduce the error when trying to pass a directory

Yes, I confirm it shows the error with a directory  as output:

```
Using detected UTF-8 mode: True
Error opening 'pack/'
Error when creating pack/
```
Thanks!
