### ISSUE TITLE
run-ldc93s1  swig/python detected a memory leak of type 'Alphabet *', no destructor found.

### ISSUE THREAD

**Issue by lalimili6** [mozilla/DeepSpeech#3058]
- **OS Platform and Distribution**:  Linux Ubuntu 18.04)
- **TensorFlow installed from**: pip
- **TensorFlow version**: v1.15.0-92-g5d80e1e 1.15.2
- **Python version**: 3.6.9
- **GCC/Compiler version**: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04
- **CUDA/cuDNN version**: 10.2.89
- **GPU model and memory**: 1080Ti, 11178MiB, Driver Version: 440.33.01

**Problem**:
I get the error below when I want to test code:
```
 ./bin/run-ldc93s1.sh
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/sokhan/.local/share/deepspeech/ldc93s1
+ export CUDA_VISIBLE_DEVICES=0
+ python -u DeepSpeech.py --noshow_progressbar --train_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --tra
in_batch_size 1 --test_batch_size 1 --n_hidden 100 --epochs 200 --checkpoint_dir /home/sokhan/.local/share/deepspeech/ldc93s1
swig/python detected a memory leak of type 'Alphabet *', no destructor found.```
```
It training bu not set training on GPU?
How can fix it?
best regards

**Comment by zcy618** [comment]
hi, I also meet the same issue, even if I create scorer file:
(deepspeech-0.7-train) parallels@parallels-Parallels-Virtual-Platform:~/Desktop/ASR/mozilla/DeepSpeech-0.7/data/lm$ python3 generate_package.py --alphabet alphabet.txt --lm lm.binary --vocab vocab-500000.txt   --package kenlm.scorer --default_alpha 0.931289039105002 --default_beta 1.1834137581510284
4173 unique words read from vocabulary file.
Looks like a character based model.
Using detected UTF-8 mode: True
Error when creating kenlm.scorer
swig/python detected a memory leak of type 'Alphabet *', no destructor found.

there is no such issue on 0.7 version, could you help to check it please?
Thanks.
