### ISSUE TITLE
tensorflow/stream_executor/cuda/cuda_dnn.cc:1403] Check failed: max_seq_length > 0 (0 vs. 0)

### ISSUE THREAD

**Issue by dothehansa** [mozilla/DeepSpeech#3063]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: our builds
- **TensorFlow version (use command below)**: 1.15.2 gpu
- **Python version**:  3.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0 & 7.4.2
- **GPU model and memory**: Nvidia GTX 1070ti 8GB
- **Exact command to reproduce**: 
DeepSpeech.py --n_hidden 2048 --checkpoint_dir C:\Users\Mogford\DeepSpeech\fine_tuning_checkpoints\deepspeech-0.7.3-checkpoint\ --epochs 1 --train_files O:\Documents\recordings\train\train.csv --dev_files O:\Documents\recordings\dev\dev.csv --test_files O:\Documents\recordings\test\test.csv --train_cudnn --alphabet_config_path C:\Users\Mogford\DeepSpeech\fine_tuning_checkpoints\deepspeech-0.7.3-checkpoint\alphabet.txt --learning_rate 0.0001 --scorer_path C:\Users\Mogford\DeepSpeech\data\deepspeech-0.7.3-models.scorer --train_batch_size 16 --test_batch_size 16 --dev_batch_size 16 --log_level 0

Hi, running training on my own recorded sentences to fine tune the model results in error - 

**tensorflow/stream_executor/cuda/cuda_dnn.cc:1403] Check failed: max_seq_length > 0 (0 vs. 0)**

I've attached the full log. the recordings are all wav & the csv's have all been through character_check & I can't find any error any of them. I've tried various batch sizes
[error.txt](https://github.com/mozilla/DeepSpeech/files/4776989/error.txt)

**Comment by lissyx** [comment]
> **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10

Please note we don't support training on Windows.

> **CUDA/cuDNN version**: 10.0 & 7.4.2

I think you should be using CuDNN v7.6



> I've attached the full log. the recordings are all wav & the csv's have all been through character_check & I can't find any error any of them. I've tried various batch sizes

Have you searched a bit? A few seconds on google with your error message yields: https://github.com/tensorflow/models/issues/6305 which points to OOM of the GPU. Without more informations on your dataset, we can't conclude. Please try the growth option and report your dataset specs.

**Comment by dothehansa** [comment]
thank you, I wasn't expecting such a quick response :)

I've updated to CuDNN 7.6 & just ran again with use_allow_growth - but I get the same error, I searched plenty before asking (opening an issue is my last choice option) but I couldn't find any relevant reference to sequence length issues.

I don't think there should be any OOM issue, they should all fit comfortably in the 8GB available

my dataset consists of:

dev: 1088 wav - total size: 80MB
test: 2177 wav - total size: 162MB
train: 7631 wav - total size: 558MB

they're all 16khz, mono files and as far as I can tell match the set up of the corpora used in training up to the checkpoint.
is there any other specs on the dataset that'd help?

**Comment by lissyx** [comment]
>  is there any other specs on the dataset that'd help?

How long is each file? Are you sure you don't have one too big?

Also, Windows: again, we don't know if it does not comes from this. It's hard for us if you don't repro elsewhere.



> I've updated to CuDNN 7.6 & just ran again with use_allow_growth - but I get the same error, I searched plenty before asking (opening an issue is my last choice option) but I couldn't find any relevant reference to sequence length issues.

The linked ticket reports more than just use_allow_growth, so you should try them



>     * --train_batch_size 16 --test_batch_size 16 --dev_batch_size 16

Batch size 1 please ?

**Comment by reuben** [comment]
The error is happening on batch 0 and is complaining about a sequence length of 0, make sure to also look for empty or very short files.

**Comment by Fakhraddin** [comment]
I faced the same issue 2 days ago.I calculated the duration of all wavs using librosa.get_duration and I removed any wav greater the 8 sec . I set batch size 20 and it worked.

**Comment by dothehansa** [comment]
Closing this one - reuben was correct, not a problem with windows, just a problem with data.

thanks for your help both.

for anyone stumbling across this - I used sox's vad to clip my sentences & it was too aggressive, leading to a few 0kb files - less aggressive settings has resolved.
