### ISSUE TITLE
Switch for disabling test phase

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#307]
To do performance and analysis runs there should be an environment variable for switching off test phase.

**Comment by kdavis-mozilla** [comment]
What do you mean by "test phase"?

**Comment by tilmankamp** [comment]
The phase where we apply test batches.

**Comment by kdavis-mozilla** [comment]
Do you mean where we calculate the CER/WER for the test data set?

This only happens once after training is complete so it has no real effect on performance.

**Comment by tilmankamp** [comment]
Yes, where we calculate the WER report of the test data set.
It has no performance implication, but if you want to try out things with small data sets and a few epochs without being interested in the test report, it helps if you can switch it off.
It's not important, but helpful.

**Comment by tilmankamp** [comment]
Done in #328.
