### ISSUE TITLE
No output when executing DeepSpeech

### ISSUE THREAD

**Issue by DanielTHAY** [mozilla/DeepSpeech#3079]
I've tried to execute deepspeed following these intructions:
`$ virtualenv -p python3 $HOME/tmp/deepspeech-venv/`
`$ source $HOME/tmp/deepspeech-venv/bin/activate`
`$ pip3 install deepspeech`
`$ pip3 install --upgrade deepspeech`
`deepspeech --model deepspeech-0.7.3-models.tflite --scorer deepspeech-0.7.3-models.scorer`
`--audio my_audio_file.wav`
It returns : 
`Loading model from file deepspeech-0.7.3-models.tflite`
`Tensorflow; v1.15.0-24-gceb46aa`
`DeepSpeech: v0.7.3-0-g8858494`
`Loaded model in 0.00316s.`
`Loading scorer from files deepspeech-0.07.3-models.scorer`
`Loaded scorer in 0.000611s.`
`Running inference.`
`experience proves this`
`Inference took 4.350s for 1.975s audio files.`

I wanted to know how we can have the script to have the output. Does the script returns the speech-to-text?
How can I obtain the speech-to-text file?

Thanks you.

**Comment by lissyx** [comment]
First, please use Discourse for support request, as explained in the issue template you removed.

Second, the output is here, so I don't understand your question:
>  `experience proves this`

**Comment by DanielTHAY** [comment]
Sorry i didn't think this was the output.
I have one question, I've tried to put a 15s wav file as input but it returns just 3 words. Is it because my file is too long?
Besides, for some wav file I have this warning:
`Warning: original sample rate(44100) is different than 16000Hz. Resampling might produce erratic speed recognition`
Does it mean that my wav is 16k? And you need a sample rate of 44k1?
Furthermore, can we use DeepSpeech to have film subtitles?

Thank you.
