### ISSUE TITLE
Importers can't keep up with the GPU, and slow down the training

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#308]
On IRC we agreed that fully preprocessing the datasets, including calculating the mfcc features, is probably the way to go:

1. As a first step, change our importers to write all the labels into a single file instead of one txt file for each wav. This should reduce our time spent opening and closing tons of small files. This single file can be a CSV or JSON where each entry is of the format ```"audio": "wav file name", "transcript": "the quick brown fox…"```, for example.
2. Add an additional step to the importers that computes and saves the MFCCs so that we don't have to do that during feeding.
3. Refactor the audio related code to do format conversion, channel splitting, segment splitting and feature calculation in a single pass to avoid reopening of small files. This is probably going to result in cleaner code as well: we won't have to use the filesystem as state for the importer steps.
4. Move the Unicode normalization code from the DataSet into the data munging part of the importer. It was added to the DataSet as a hack to avoid having to delete the processed corpus files and run the importer again.

This should get us to a state where we do almost no work on the input data during feeding of the network, and remove the importers as a bottleneck for training. Any comments on this plan?

**Comment by tilmankamp** [comment]
Some of this is already covered by [this issue](https://github.com/mozilla/DeepSpeech/issues/288).

**Comment by kdavis-mozilla** [comment]
In light of issue #311 (Increase hidden layer size) which slows the GPU computation, I'd like to check to see if this is still a problem after the network size has been increased.

So, maybe we should wait until after the long weekend over which I hope to run a longer run testing #302 (Removing warp-ctc), #284 (BRNN with Stride 2), and #311 (Increase hidden layer size)

**Comment by kdavis-mozilla** [comment]
Seems like this is no longer a problem
