### ISSUE TITLE
Custom code DeepSpeed comprehension

### ISSUE THREAD

**Issue by Eichizen17** [mozilla/DeepSpeech#3081]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
 No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Raspberry Pi
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

I've tried to execute deepspeed following these intructions:
```
$ virtualenv -p python3 $HOME/tmp/deepspeech-venv/
$ source $HOME/tmp/deepspeech-venv/bin/activate
$ pip3 install deepspeech
$ pip3 install --upgrade deepspeech
deepspeech --model deepspeech-0.7.3-models.tflite --scorer deepspeech-0.7.3-models.scorer
--audio my_audio_file.wav
```

I have one question, I've tried to put a 15s wav file as input but it returns just 3 words. Is it because my file is too long? Sometimes, it returns words I don't know .. like gartano, atheromatous or ototachibana.
Besides, for some wav file I have this warning:
`Warning: original sample rate(44100) is different than 16000Hz. Resampling might produce erratic speed recognition`
Does it mean that my wav is 16k? And that the input needs to have a sample rate of 44k1?
Furthermore, can we use DeepSpeech to have film subtitles?
Last but not least, how can we have the script? To modify or add some custom code?

Thank you.

**Comment by kdavis-mozilla** [comment]
As this isn't a bug or feature request but a request for support, could you take this topic of discussion to the [Discourse forums](https://discourse.mozilla.org/c/deep-speech). Thank you.
