### ISSUE TITLE
Missing dependencies in Dockerfile.train

### ISSUE THREAD

**Issue by DanBmh** [mozilla/DeepSpeech#3082]
The new audio augmentation options don't work with the docker container.

I did add these flags:
```
      --augment reverb[p=0.1,delay=50.0~30.0,decay=10.0:2.0~1.0] \
      --augment gaps[p=0.05,n=1:3~2,size=10:100] \
      --augment resample[p=0.1,rate=12000:8000~4000] \
      --augment codec[p=0.1,bitrate=48000:16000] \
      --augment volume[p=0.1,dbfs=-10:-40]
```

And get this error:
```
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.6/dist-packages/librosa/util/utils.py'
```

Can be solved by installing:
```
apt-get install -y libopus0
apt-get install -y libsndfile1
pip3 install --upgrade "numba=0.48"
pip3 install --upgrade opuslib
```

**Comment by lissyx** [comment]
> The new audio augmentation options don't work with the docker container.

Are those merged in master? We don't have test for them anyway, so it's not surprising.



> ```
> 
> ```
> 
> 
> Can be solved by installing:
> 
> ```
> apt-get install -y libopus0
> apt-get install -y libsndfile1
> pip3 install --upgrade "numba=0.48"
> pip3 install --upgrade opuslib
> ```

Well, as usual, PR welcome, you already have the patch it looks like :)

**Comment by DanBmh** [comment]
> Are those merged in master? We don't have test for them anyway, so it's not surprising.

Yes they got merged some weeks ago.
