### ISSUE TITLE
Process exited with status 128: Process exited with status 128 ++ git describe --long --tags fatal: No names found, cannot describe anything. + tf_git_rev=

### ISSUE THREAD

**Issue by udaram** [mozilla/DeepSpeech#3084]
Getting following error during bazel build command in v0.6.1 
$ bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie

Starting local Bazel server and connecting to it...
INFO: Analysed 2 targets (92 packages loaded, 5738 targets configured).
INFO: Found 2 targets...
ERROR: Process exited with status 128: Process exited with status 128
++ git describe --long --tags
fatal: No names found, cannot describe anything.
+ tf_git_rev=
INFO: Elapsed time: 32.691s, Critical Path: 2.55s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully

please help me to resolve this error

**Comment by lissyx** [comment]
> Getting following error during bazel build command in v0.6.1
> $ bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
> 
> Starting local Bazel server and connecting to it...
> INFO: Analysed 2 targets (92 packages loaded, 5738 targets configured).
> INFO: Found 2 targets...
> ERROR: Process exited with status 128: Process exited with status 128
> ++ git describe --long --tags
> fatal: No names found, cannot describe anything.
> 
>     * tf_git_rev=
>       INFO: Elapsed time: 32.691s, Critical Path: 2.55s
>       INFO: 1 process: 1 local.
>       FAILED: Build did NOT complete successfully
> 
> 
> please help me to resolve this error

This is a support request, not a bug report. Please use Discourse as documented in the issue template you removed.

Also, have you `git clone` as documented? The error suggests no ...
