### ISSUE TITLE
Required version of ds-ctcdecoder does not exit

### ISSUE THREAD

**Issue by dabadiesimon** [mozilla/DeepSpeech#3102]
Running on Debian 9.12 - Python  3.7.6- deepspeech-training==0.9.0a0

when executing `pip3 install --upgrade -e .`

Deepspeech requires _ds_ctcdecoder==0.9.0-alpha.0_. 
However, this version does not exist as can be seen on [dedicated pypi.org page](https://pypi.org/project/ds-ctcdecoder/#history)

Full error:

> ERROR: Could not find a version that satisfies the requirement ds_ctcdecoder==0.9.0-alpha.0 (from deepspeech-training==0.9.0a0) (from versions: 0.6.1, 0.7.0, 0.7.1, 0.7.3, 0.7.4, 0.8.0a3, 0.8.0a4)
> ERROR: No matching distribution found for ds_ctcdecoder==0.9.0-alpha.0 (from deepspeech-training==0.9.0a0)

**Comment by kdavis-mozilla** [comment]
This can be resolved by using a release, e.g. 0.7.4, or pre-release, e.g. v0.8.0-alpha.4, not master.

**Comment by lissyx** [comment]
Thanks for the report.
@dabadiesimon Yeah I moved the `VERSION` file without releasing an alpha build. As said earlier, move to a release tag or be patient and within a few hours a 0.9.0a0 should be there.

**Comment by dabadiesimon** [comment]
Yes, just to let you know.
Thanks for the quick answers

**Comment by lissyx** [comment]
The 0.9.0a0 has been uploaded.

**Comment by vasudev-hv** [comment]
Adding here in case if anyone facing same issue in windows. Change the value in [VERSION](https://github.com/mozilla/DeepSpeech/blob/master/VERSION) file to `0.9.0-alpha.2`.  Seems like the path is not getting resolved properly

**Comment by Riya-11** [comment]
Hi, I am trying to perform fine-tuning on DeepSpeech's model in Colab. Here are the installation steps I am following- 

```
!git clone https://github.com/mozilla/DeepSpeech
!pip3 install --upgrade pip==20.0.2 wheel==0.34.2 setuptools==46.1.3
!pip3 install --upgrade --force-reinstall -e .

```

But, I receive this error upon trying to run it - 

```
ERROR: Could not find a version that satisfies the requirement ds_ctcdecoder==training/deepspeech_training/VERSION (from deepspeech-training===training-deepspeech-training-VERSION) (from versions: 0.6.1, 0.7.0, 0.7.1, 0.7.3, 0.7.4, 0.8.0a3, 0.8.0a4, 0.8.0a5, 0.8.0a6, 0.8.0a7, 0.8.0a8, 0.8.0, 0.8.1, 0.8.2, 0.9.0a0, 0.9.0a1, 0.9.0a2, 0.9.0a3, 0.9.0a4, 0.9.0a5, 0.9.0a8, 0.9.0a9, 0.9.0a10, 0.9.0a11)
ERROR: No matching distribution found for ds_ctcdecoder==training/deepspeech_training/VERSION (from deepspeech-training===training-deepspeech-training-VERSION)

```

Any help will be appreciated! Thanks!

**Comment by lissyx** [comment]
> Any help will be appreciated! Thanks!

Please reach for support on Discourse, not Github.

**Comment by Ifiht** [comment]
This still seems to be an issue on the latest stable release ([v0.9.3](https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3))? I just set up the environment as described in [Train Your Own Model](https://deepspeech.readthedocs.io/en/v0.9.3/TRAINING.html)

```
ERROR: Could not find a version that satisfies the requirement ds_ctcdecoder==0.9.3 (from deepspeech-training==0.9.3) (from versions: none)
ERROR: No matching distribution found for ds_ctcdecoder==0.9.3 (from deepspeech-training==0.9.3)
WARNING: You are using pip version 20.2.2; however, version 22.0.3 is available.
You should consider upgrading via the '/home/jovyan/dpsc-train-venv/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by JRMeyer** [comment]
take a look at : https://github.com/mozilla/DeepSpeech/issues/3693

**Comment by souheibdaoudi** [comment]
If  anyone got this problem after me , I suggest to create a virtual environnement with a comaptible python version .
