### ISSUE TITLE
[BUG?] import_cv2.py returned non-zero exit status 1.

### ISSUE THREAD

**Issue by adjouama** [mozilla/DeepSpeech#3104]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Your builds
- **TensorFlow version (use command below)**: v1.15.0-92-g5d80e1e 1.15.2
- **Python version**:  Python 3.7.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: Nvidia GTX 1080Ti - 11GB
- **Exact command to reproduce**: ```bin/import_cv2.py --filter_alphabet data/commonvoice/alphabet.txt data/commonvoice/```

I am trying to train the common voice model (English) following the documentation : https://deepspeech.readthedocs.io/en/v0.7.4/TRAINING.html

I am having a problem when using ```import_cv2.py```. I get the error below;
```subprocess.CalledProcessError: Command '['soxi', '-s', 'data/commonvoice/clips/common_voice_en_18686313.wav']' returned non-zero exit status 1.```

when I run soxi command manually I get:
```soxi FAIL formats: can't open input file `data/commonvoice/clips/common_voice_en_18686313.wav': WAVE: RIFF header not found```

I checked the file and it was available in the folder. 

one thing I did was to delete the common_voice_en_18686313.wav and re-run ```import_cv2.py```, I get the same error but on another file. Deleted it again, and another file was bugged, after some time, it get back to the first file.

My best guess is that there's a problem during conversion. 

Any idea on how to fix this  ? 

NOTE: I am using DeepSpeech 0.7.4

Thank you a lot in advance,

**Comment by lissyx** [comment]
> ``
> 
> when I run soxi command manually I get:
> `` soxi FAIL formats: can't open input file `data/commonvoice/clips/common_voice_en_18686313.wav': WAVE: RIFF header not found ``
> 
> I checked the file and it was available in the folder.

That does not give more information, since the error states that it could not find a valid WAVE file. Are you sure your `sox` setup is fine and able to convert from MP3 ?

So the file exists, but what is it ? Empty ? Something else ?



> My best guess is that there's a problem during conversion.
> 
> Any idea on how to fix this ?

It would have been nice to follow the documented steps of asking support on Discourse and providing more logs, there's nothing actionable here.

**Comment by adjouama** [comment]
First, thank you a lot for the quick reply. 


> That does not give more information, since the error states that it could not find a valid WAVE file. Are you sure your `sox` setup is fine and able to convert from MP3 ?
> 
> So the file exists, but what is it ? Empty ? Something else ?
> 

Actually, you are right. I have updated ffmpeg ```sudo apt install ffmpeg``` then deleted all the previously created wav then restarted the ```bin/import_cv2.py``` and now it works fine. I hope this fix can be helpful for other users. 
 
> It would have been nice to follow the documented steps of asking support on Discourse and providing more logs, there's nothing actionable here.

I really apologize. It is my first time here. forgive my ignorance, I will post on Discourse next time. 

Thank you a lot for your time

**Comment by lissyx** [comment]
> Actually, you are right. I have updated ffmpeg `sudo apt install ffmpeg` then deleted all the previously created wav then restarted the `bin/import_cv2.py` and now it works fine. I hope this fix can be helpful for other users.

Is there any doc improvement that would have helped you ?


> I really apologize. It is my first time here. forgive my ignorance, I will post on Discourse next time.


At least you filled the template and exposed your issue, that could have been worse :).


Good to know you now have a working setup, thanks for you quick feedback!

**Comment by adjouama** [comment]
> Is there any doc improvement that would have helped you ?

I think the doc covers really everything. Very well done @lissyx ! 
Maybe, the only thing I still did not find in the Doc is the best parameters to train models on the proposed datasets (common voice for instance). 

I am almost sure that such a Doc is somewhere there, I just did not find it yet maybe :-) 

My best regards,

**Comment by lissyx** [comment]
> I am almost sure that such a Doc is somewhere there, I just did not find it yet maybe :-)

There is no such doc, because it depends too much on what you are working on, what datasets your are mixing, etc. Best source of infos for that for the moment is digging through the Discourse forum.

**Comment by adjouama** [comment]
> There is no such doc, because it depends too much on what you are working on, what datasets your are mixing, etc. Best source of infos for that for the moment is digging through the Discourse forum.

Basically, I am trying to train a Speech-to-Text model based only on CommonVoice English dataset. And use it for real time captioning, later on, if satisfied enough, I will add my own dataset which has ~15h (not much I know :-) )

I'd be happy if you can send me on the good path ^^ in the meantime, I will dig deeper on discourse. 

I really appreciate your reactivity :-)

**Comment by lissyx** [comment]
> I'd be happy if you can send me on the good path ^^ in the meantime,

It's not that I dont want, it's just that we don't have data at all: our training on Common Voice English are with other datasets, and those parameters are already documented in releases.

**Comment by adjouama** [comment]
> > I'd be happy if you can send me on the good path ^^ in the meantime,
> 
> It's not that I dont want, it's just that we don't have data at all: our training on Common Voice English are with other datasets, and those parameters are already documented in releases.

Perfect 👍  Thank you a lot @lissyx
