### ISSUE TITLE
Can't run inference from command-line using the pretrained model

### ISSUE THREAD

**Issue by kareemamrr** [mozilla/DeepSpeech#3112]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Pop!_OS 20.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Upstream
- **TensorFlow version (use command below)**: 2.2.0
- **Python version**: 3.8.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.1 / 7.6.5
- **GPU model and memory**: Nvidia GTX 1060, 8gb
- **Exact command to reproduce**: deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --lm deepspeech-0.6.1-models/lm.binary --trie deepspeech-0.6.1-models/trie --audio voice.wav

When running the above command this error is thrown back to me:
`deepspeech: error: ambiguous option: --lm could match --lm_alpha, --lm_beta`

It seems that it thinks I haven't written the `--lm` flag completely due to its similarity to those other flags. Any idea what I can do?

**Comment by reuben** [comment]
It looks like you're not using the right version of the client to match the model version (0.6.1). Make sure you always use a client matching the version of the model you're running. You can find the 0.6.1 downloads here: https://github.com/mozilla/DeepSpeech/releases/v0.6.1 and the documentation here: https://deepspeech.readthedocs.io/en/v0.6.1/

**Comment by kareemamrr** [comment]
Thank you!
