### ISSUE TITLE
Mention license of code and trained models in release notes

### ISSUE THREAD

**Issue by AlexeyKruglov** [mozilla/DeepSpeech#3115]
[LICENSE](https://github.com/mozilla/DeepSpeech/blob/master/LICENSE) file states MPL-2.0 license, at least for code.

[doc/DeepSpeech.rst](https://github.com/mozilla/DeepSpeech/blob/master/doc/DeepSpeech.rst) file states MPL license for both code and the pre-trained weigths: "Open, in that the code and models are released under the Mozilla Public License." This contradicts LICENSE file. Either DeepSpeech.rst, or LICENSE must be corrected.

[Releases section](https://github.com/mozilla/DeepSpeech/releases), that contains the weights, doesn't state any license for the weights, as well as the .tar.gz files (at least in v0.6.1). It's best to include unambiguous license statement at least in one of these places -- to make the models more open and ubiquitous.

So, there are two problems:
1. Wrong code license either in doc/DeepSpeech.rst, or in LICENSE;
2. It's best to declare model (weights) license explicitly and unambiguously, for example in Releases section, or in LICENSE.

**Comment by reuben** [comment]
"Mozilla Public License" in the docs is referring to the MPL-2.0, there is no inconsistency: https://www.mozilla.org/en-US/MPL/

Thanks for the suggestion about the release notes, I'll add this issue to the next release project so we don't forget to mention the license in the notes.

**Comment by kdavis-mozilla** [comment]
Just added to draft release notes.
