### ISSUE TITLE
Directly use Deepspeech Language Model for Beam Search from Deepspeech python api

### ISSUE THREAD

**Issue by jainal09** [mozilla/DeepSpeech#3119]
Hi,
Is it possible to directly use Deepspeech Language Model.
Which takes input as text and perform Beamsearch ctc decode using the pretrained Deepspeech lm and scorer and then provides the Output text?

**Comment by reuben** [comment]
The input to the beam search algorithm is a sequence of probability distributions, not text. See for example: https://distill.pub/2017/ctc/

It's not possible to do that. In the future, use Discourse for discussion. The issue tracker is meant for bugs and feature requests, as was explained in the issue template you deleted before posting this.
