### ISSUE TITLE
Step, epoch, Weird Duration

### ISSUE THREAD

**Issue by masoudMZB** [mozilla/DeepSpeech#3120]
Hello,
I am using DeepSpeech version 0.7.4 , I don't wan't use transfer learning, I uses deep speech english dataset, and these are my hyperparameters : 

`python3 DeepSpeech.py --train_files data/CV/en/clips/dev.csv --dev_files data/CV/en/clips/dev.csv --test_files data/CV/en/clips/test.csv --checkpoint_dir data/tmpTestFolder  --export_dir data/tmpTestExport --n_hidden 2048 --epochs 100 --dropout_rate 0.40 --lm_alpha 0.75 --lm_beta 1.85  --learning_rate 0.00001 --automatic_mixed_precision --train_cudnn True`

I have 32G ram, 512G SSD, GTX 1080 TI GPU,

I have 3 questions now, 
1 - ) each epoch takes too long and too many steps( near million steps ) but I've seen in your documentation you never reach this step count ( is something wrong with my batchSize? is default batchsize is 1? ) 

2 - ) when you wrote 120 epoch for the first phase in 0.7.4 version. did you really cover all the training data? I mean you didn't use any iteration count for training data to just use some of them?

3-)  each epoch takes 12h. is it okay?

**Comment by kdavis-mozilla** [comment]
As this is not a bug or feature request could you address this support question to our [Discourse forums](https://discourse.mozilla.org/c/deep-speech) instance. Thank you.
