### ISSUE TITLE
Inconsistencies in Java bindings for Metadata structures

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#3121]
The Java bindings around the Metadata structures have some inconsistencies with the other language bindings. For example, CandidateTranscript.getTokens() which returns a single token, and Metadata.getTranscripts() which returns a single transcript. We should fix what is possible and document differences for what isn't.

**Comment by lissyx** [comment]
> CandidateTranscript.getTokens() which returns a single token

it should be an array that can be indexed with `getNum_tokens()`


> Metadata.getTranscripts() which returns a single transcript.

Same
