### ISSUE TITLE
 Exporting files necessary to run DeepSpeech

### ISSUE THREAD

**Issue by kromoxpro** [mozilla/DeepSpeech#3126]
Hello, I am new at this.

I have started training the model in Spanish but I have not defined an export directory. I have used this command:

`python3 DeepSpeech.py --train_files es/clips/train.csv --dev_files es/clips/dev.csv --test_files es/clips/test.csv`

During the training, have the necessary files been created to run DeepSpeech? else, how can I generate them?

I am referring to the following files: _output_graph.pb_, _lm.binary_ and _trie_ 

I really appreciate your help.

**Comment by kdavis-mozilla** [comment]
Please refer to [Training Your Own Model](url) section of the documentation, in particular the exporting sections.

Also, in future, support questions should be directed to our [discourse](https://discourse.mozilla.org/c/deep-speech/247) board.

We reserve issues for bugs or new feature requests.
