### ISSUE TITLE
ImportError: cannot import name 'UTF8Alphabet' from 'ds_ctcdecoder'

### ISSUE THREAD

**Issue by satishbanka** [mozilla/DeepSpeech#3128]
Hi Team,

I have upgraded deepspeech from 0.7.1 to 0.7.4.

After upgrade, I am facing the below error while running transcribe.py.

proj/newdeepspeech/DeepSpeech/data/Data_Youtube_Daily/Week1_May/results-10-05-2020/Scorer/ttg_9c_mk_yt.scorer
Traceback (most recent call last):
  File "transcribe.py", line 17, in <module>
    from deepspeech_training.util.config import Config, initialize_globals
  File "/home/eclerxadmin/speechproj/newdeepspeech/Deepspeech0.7.4/DeepSpeech/training/deepspeech_training/util/config.py", line 9, in <module>
    from ds_ctcdecoder import Alphabet, UTF8Alphabet
ImportError: cannot import name 'UTF8Alphabet' from 'ds_ctcdecoder' (/home/eclerxadmin/anaconda3/envs/latestdeepspeech/lib/python3.7/site-packages/ds_ctcdecoder/__init__.py)

Request your help or advice in fixing this.

Thanks and Regards,
Satish Banka

**Comment by lissyx** [comment]
> I have upgraded deepspeech from 0.7.1 to 0.7.4.

How ?



> running transcribe.py.

How ?

**Comment by tilmankamp** [comment]
This is a post-refactoring problem caused by de-duplication of the two alphabet classes we once had. Some of the importers are also affected.

**Comment by reuben** [comment]
v0.7.4 version of that file does not import from ds_ctcdecoder, since it's before the refactoring: https://github.com/mozilla/DeepSpeech/blob/v0.7.4/training/deepspeech_training/util/config.py

It looks like you're running the master version of the code, but using the v0.7.4 version of the decoder.

**Comment by tilmankamp** [comment]
@reuben Ah yes, missed that. Could it be closed then?

**Comment by reuben** [comment]
I think so... I triggered a new alpha on master so that `pip install -U -e .` will pick up the new decoder package.

**Comment by lissyx** [comment]
@satishbanka Could you please verify if it works?

**Comment by satishbanka** [comment]
> > I have upgraded deepspeech from 0.7.1 to 0.7.4.
> 
> How ?
> 
> > running transcribe.py.
> 
> How ?

Yes Got this issue while running Transcribe.py

**Comment by satishbanka** [comment]
> using the v0.7.4 ve

Hi Reuben, Yes I am using the master version of the code. I got it cloned from 
"git clone https://github.com/mozilla/DeepSpeech"

I thought that was the 0.7.4

Sorry for the confusion, I will use the 0.7.4 code now

**Comment by satishbanka** [comment]
> v0.7.4 version of that file does not import from ds_ctcdecoder, since it's before the refactoring: https://github.com/mozilla/DeepSpeech/blob/v0.7.4/training/deepspeech_training/util/config.py
> 
> It looks like you're running the master version of the code, but using the v0.7.4 version of the decoder.

Hi Reuben, Yes I am using the master version of the code. I got it cloned from
"git clone https://github.com/mozilla/DeepSpeech"

I thought that was the 0.7.4

Sorry for the confusion, I will use the 0.7.4 code now

**Comment by satishbanka** [comment]
Thanks very much for your quick response guys! Truly appreciate Mozilla and mainly your dedication and hard work!

**Comment by lissyx** [comment]
Thanks @satishbanka for confirming it was just running master instead of 0.7.4
