### ISSUE TITLE
Missing deepspeech_training.util.text.Alphabet

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#3130]
Some files are still using `deepspeech_training.util.text.Alphabet` which has been removed during de-duplication of alphabet implementations.

At least [these files](https://github.com/mozilla/DeepSpeech/search?q=%22from+deepspeech_training.util.text+import+Alphabet%22&unscoped_q=%22from+deepspeech_training.util.text+import+Alphabet%22) are affected.

**Comment by shichaog** [comment]
Use
from ds_ctcdecoder import Alphabet 
instead
