### ISSUE TITLE
I want to implement this API into cakephp, im new in both.

### ISSUE THREAD

**Issue by BrandonProj2020** [mozilla/DeepSpeech#3133]
Im working in the AI company, we want to implement the speech to text to make transcriptions of a call and i will then create a code that will make a disposition of the call taking into consideration some keywords.

So what i need from this API is implement it into that system, i have recordings but dont understand how request will work here i can image that willl go like this

Button that will send the audio file into this API.
get transcription from the API
run the script to get the disposition
print a flag for the disposition

Thank you in advance for any asnwer

**Comment by lissyx** [comment]
Please reach for support on Discourse.
