### ISSUE TITLE
Deepspeech dosen't detect voice(or detects voice but dosent recognize) 

### ISSUE THREAD

**Issue by sanath-ai** [mozilla/DeepSpeech#3143]
(deepspeech) C:\Users\sanath\Desktop\deepspeech>python realtime_audio.py -m
C:\Users\sanath\Desktop\deepspeech\deepspeech-0.7.4-models.pbmm   -s C:\Users\
sanath\Desktop\deepspeech\deepspeech-0.7.4-models.scorer
Initializing model...
INFO:root:ARGS.model: C:\Users\sanath\Desktop\deepspeech\deepspeech-0.7.4-mode
ls.pbmm
TensorFlow: v1.15.0-24-gceb46aae58
DeepSpeech: v0.7.4-0-gfcd9563f
INFO:root:ARGS.scorer: C:\Users\sanath\Desktop\deepspeech\deepspeech-0.7.4-mod
els.scorer
Listening (ctrl-C to exit)...
/         ##Here nothing happen it will be just in a loop and doesn't detect audio or recognize## 
forrtl: error (200): program aborting due to control-C event
##Once i press Clt + C get following error##
Image              PC                Routine            Line        Source

libifcoremd.dll    00000000100B4374  Unknown               Unknown  Unknown
libifcoremd.dll    00000000100ADF29  Unknown               Unknown  Unknown
libifcoremd.dll    000000001009A8AF  Unknown               Unknown  Unknown
libifcoremd.dll    0000000010021B06  Unknown               Unknown  Unknown
libifcoremd.dll    000000001002E680  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFB5251361F  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFB52F313D2  Unknown               Unknown  Unknown
ntdll.dll          00007FFB553303C4  Unknown               Unknown  Unknown

Installed all requirements from .txt
webrtcvad was not availabe so installed webrtcvad-wheel using pip 
same error in python 3.6, 3.7, 3.8
OS : Windows8.1(64bit)
Using Anaconda

**Comment by lissyx** [comment]
This is not a in our code, please use discourse to reach for support as stated in the github template.
