### ISSUE TITLE
Audio File Specifications to use Deep Speech

### ISSUE THREAD

**Issue by harmandeepsinghkalsi** [mozilla/DeepSpeech#3148]
Hi All

I recently started using Deep Speech for audio transcriptions. I have doubts to clarify 

1.What are the specifications to keep in mind regarding the audio file to be used for the transcription ?
Because I have different format file (.mp3,.wav, etc..) 
2. Is there any restriction of the length of the audio?

Thanks in advance!

**Comment by kdavis-mozilla** [comment]
@harmandeepsinghkalsi As we reserve GitHub issues for bugs and feature requests, I'm wondering fi you could take this support question over to [discourse](https://discourse.mozilla.org/c/deep-speech/247). Thanks.

**Comment by harmandeepsinghkalsi** [comment]
Sure @kdavis-mozilla , If that the norm being followed,  I will move it to discourse. Thank you for your response!
