### ISSUE TITLE
Training Docker Image and Language Model Creation 

### ISSUE THREAD

**Issue by gokgozf** [mozilla/DeepSpeech#3153]
I really like the idea of separating the training, and build images though i have a doubt.

In my opinion being able to easily generate a new language model and being able to test is a great opportunity for training image which i believe is neglected in the image by not adding the following statements and some dependency installations

If it is aligned with your expectations as well, i can provide quick pull request on that 

```
# Allow Python printing utf-8
ENV PYTHONIOENCODING UTF-8

# Build KenLM in /DeepSpeech/native_client/kenlm folder
WORKDIR /DeepSpeech/native_client
RUN rm -rf kenlm && \
	git clone https://github.com/kpu/kenlm && \
	cd kenlm && \
	git checkout 87e85e66c99ceff1fab2500a7c60c01da7315eec && \
	mkdir -p build && \
	cd build && \
	cmake .. && \
	make -j $(nproc)
```

**Comment by DanBmh** [comment]
What version are you using?
I already added the KenLM building part some time ago to the `Dockerfile.train.tmpl` file.

**Comment by lissyx** [comment]
> by not adding the following statements and some dependency installations

As @DanBmh said, we have that now. Can you please be clear in your wording? I'm not a big fan of mind reading, so "some dependency" is not really helpful.

**Comment by lissyx** [comment]
So @gokgozf can you elaborate explicitely on what is needed ? The only part of code you pasted is already there...

**Comment by DanBmh** [comment]
@lissyx Does scorer packaging still work? I've seen that the py file was replaced by another script with extra installation steps, but didn't test it yet.

**Comment by lissyx** [comment]
> @lissyx Does scorer packaging still work?

In the dockerfile? it's possible we don't take care of that yet

**Comment by lissyx** [comment]
Please @gokgozf ? Can you elaborate on what you miss?

**Comment by kdavis-mozilla** [comment]
@gokgozf In order to help us help you, could you elaborate on what's missing?

**Comment by lissyx** [comment]
Without more information and no feedback, I'm closing this bug. Please reopen / send PR if you need to.
