### ISSUE TITLE
How to improvise tuning or substitution for better tuning of the ASR

### ISSUE THREAD

**Issue by MrityunjoyS** [mozilla/DeepSpeech#3154]
I'm trying to use hinting and substitution methods to rectify errors and improve recognition. I'm using deep speech model only as ASR. I've used deep speech 2 model to build my own pbm and scorer as I'm trying to improvise the ASR for Hindi language. I'm facing issues like while saying "Haa", the model is only catching "a". Need to rectify that, can you please suggest how can I implement 'hints' or 'substitution' for that.

**Comment by kdavis-mozilla** [comment]
As this is not a bug or feature request for this repo (we reserve issues for bug and/or feature requests), could you take this admittedly interesting issue to [discourse](https://discourse.mozilla.org/c/deep-speech/247)?
