### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Nufflee** [mozilla/DeepSpeech#3155]
If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 v1903
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: from pip
- **TensorFlow version (use command below)**: 2.2.0
- **Python version**: 3.7.8
- **CUDA/cuDNN version**: not using GPU
- **GPU model and memory**: not using GPU
- **Exact command to reproduce**:
```sh
python3 -m venv .
.\Scripts\activate
pip install deepspeech
pip install tensorflow # doesn't change anything whether it's installed or not
deepspeech


Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\nufflee-tts\deepspeech_try2\Scripts\deepspeech.exe\__main__.py", line 4, in <module>
  File "d:\nufflee-tts\deepspeech_try2\lib\site-packages\deepspeech\__init__.py", line 23, in <module>
    from deepspeech.impl import Version as version
  File "d:\nufflee-tts\deepspeech_try2\lib\site-packages\deepspeech\impl.py", line 13, in <module>
    from . import _impl
ImportError: DLL load failed: The specified module could not be found.
```

I followed the most basic deepspeech installation steps but I keep getting this error. I also installed MSVC++ redistributables but that doesn't help either. Any help would be appreciated.

One odd thing I noticed is that it uses python from my program files, not one from my current virtual environment. Then I tried to do `python -m deepspeech` using python from the venv but that fails with the same error and path too.

**Comment by lissyx** [comment]
This is not a bug on our side and you already have a topic for support, please avoid spam.

**Comment by Nufflee** [comment]
Sorry, I only noticed the support link after posting the issue. My bad.

**Comment by 8orbs** [comment]
where is that topic in support?

**Comment by felrock** [comment]
I had this issue and using python 3.6 solved it. For anyone that run into this issue and googles it :-)

**Comment by fernando-figueredo** [comment]
> I had this issue and using python 3.6 solved it. For anyone that run into this issue and googles it :-)

Thank you! It solve my problem and help me a lot!!
