### ISSUE TITLE
pip3.6 install deepspeech fails on armv7l

### ISSUE THREAD

**Issue by sd-z** [mozilla/DeepSpeech#3156]
While trying to install deepspeech on the Raspberry Pi 4 (armv7l) via pip3.6 install deepspeech the whl file is not found.
On PyPi the listed Python Versions are 2,7, 3.4, 3.5, 3.6. 
However installing python3.7 and running python3.7 -m pip install deepspeech works like a charm.
Is there a way to include this information somewhere? I feel like the Programming Language section on PyPi is meant for this, am I mistaken ?
While executing the same command on linux amd systems via docker it works.

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Raspbian Buster armv7l
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**: none
- **Python version**: 3.6.8/3.6.11
- **GCC/Compiler version (if compiling from source)**:Raspbian 8.3
- **GPU model and memory**:Nvidia Geforce GTX 1650
- **Exact command to reproduce**:pip3.6 install deepspeech

**Comment by lissyx** [comment]
>  On PyPi the listed Python Versions are 2,7, 3.4, 3.5, 3.6.

This is likely:
 - out of date
 - cannot be specific to arm package

We only support Raspbian Buster's python version there, which is 3.7.

Can you please elaborate where the problem here is? It looks like it's all working, and our doc never mentions installing with `pip3.6`.

**Comment by sd-z** [comment]
Thanks for the quick response!
I just couldn't find the requirement and did not know what the proper way of communication was. Maybe it would be possible to include it in the docs. I was installing it with pip3.6 as only python 3.6 and 2.7 were included Buster for the Pi, maybe Noobs messed that up...
Anyways thanks for clearing it up :)
Best Regards

**Comment by lissyx** [comment]
It's hard to document more than the obvious `pip install deepspeech`, but if you can send à pr to improves docs its always welcome.
