### ISSUE TITLE
Newbie question on checkpoints

### ISSUE THREAD

**Issue by lpkoh** [mozilla/DeepSpeech#3163]
Hi,

I am a newbie and I just got the model to start training on my own dataset. I would like to tune it on a pretrained model. Could someone help me understand:

python3 DeepSpeech.py --n_hidden 2048 --checkpoint_dir path/to/checkpoint/folder --epochs 3 --train_files my-train.csv --dev_files my-dev.csv --test_files my_dev.csv --learning_rate 0.0001

Do I simply replace path/to/checkpoint/folder with something like deepspeech-0.7.4-models.pbmm? What counts as a previous checkpoint?

**Comment by lissyx** [comment]
This is a support request, please reach on Discourse and read the documentation. Checkpoints are released separately from the tensorflow model.

**Comment by lpkoh** [comment]
If I run it without a --checkpoint_dir specified, is it just going to load in some weights from before or is it a raw model architecture?

**Comment by lissyx** [comment]
Use discourse, please.
