### ISSUE TITLE
Update FAQ: TensorFlow Lite

### ISSUE THREAD

**Issue by davidak** [mozilla/DeepSpeech#3164]
https://github.com/mozilla/DeepSpeech/wiki#what-is-the-process-of-making-custom-trained-deepspeech-engines-available-to-the-end-user-on-web-android-apps-and-ios-apps

It links to an issue, that is closed in 2018. So the situation might be better now.

Please update the answer according to the current situation.

cc @lissyx

**Comment by reuben** [comment]
Done.
