### ISSUE TITLE
Quiet operation of DeepSpeech API

### ISSUE THREAD

**Issue by sharvil** [mozilla/DeepSpeech#3166]
The DeepSpeech implementation writes messages to stderr, even when there are no errors. It would be nice if DeepSpeech could operate quietly and leave it up to the caller to decide how to report success/failure. For example, I see output like:

```
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.4-0-gfcd9563
```

on stderr when I construct a DeepSpeech model without errors.

Ideally, calling into the API would be silent by default. If it's important to print these messages, a `debug` or `verbose` flag (defaulting to false) might be appropriate.

**Comment by lissyx** [comment]
This is what we did at first. Consequence was loosing a lot of time asking again people to share proper version informations, so we are not really looking nicely at a flag that would be disabled by default.

Nothing stops you from redirecting `stderr`, so please document the usecase where this is a problem for you.


> The DeepSpeech implementation writes messages to stderr, even when there are no errors.

Printing runtime information on `stderr` is quite common, some people even use it for `usage` informations. Please note our exit code is reflecting proper status for binaries we ship.



> If it's important to print these messages, a `debug` or `verbose` flag (defaulting to false) might be appropriate.

If you really have a usecase where this is problematic, please don't hesitate to expose it. PRs are welcome, but I'm quite firmly against a default value where it hides informations ; though you could imagine a situation where the default behavior is **showing** this and API allows to hide.

Please also consider that adding this kind of API-level toggle means having support (+ tests) on all supported bindings.

**Comment by sharvil** [comment]
Note that I'm only asking for silent operation when calling in via the API. Your shipped binaries can print messages as they please.

I have a multi-threaded process with each thread instantiating its own copy of the DeepSpeech model. These messages get repeatedly spammed to stderr for each instantiation (particularly bad with many cores/gpus) which isn't helpful and drowns out my own warning/error messages that I send to stderr. Redirecting is not a good option since there's inherent value in seeing stderr contents.

An alternative is that the caller provides a file descriptor or other abstraction (e.g. LogSink) into which the DeepSpeech API can write messages. At least that way the caller can decide what to do with the messages.

**Comment by lissyx** [comment]
> Note that I'm only asking for silent operation when calling in via the API. Your shipped binaries can print messages as they please.

Experience has shown this is not enough.



> I have a multi-threaded process with each thread instantiating its own copy of the DeepSpeech model. These messages get repeatedly spammed to stderr for each instantiation (particularly bad with many cores/gpus) which isn't helpful and drowns out my own warning/error messages that I send to stderr. Redirecting is not a good option since there's inherent value in seeing stderr contents.

Are you referring to "spam" for **two** lines on each model creation? Sorry, but even with a lot of GPUs / CPUs it's not going to be that much. How much spam is spam ?



> An alternative is that the caller provides a file descriptor or other abstraction (e.g. LogSink) into which the DeepSpeech API can write messages. At least that way the caller can decide what to do with the messages.

This is both a non trivial amount of work and a recipe for missing important informations. Experience has proven us that this will bite us back bad.

**Comment by sharvil** [comment]
What do you think is the path forward for those who want silent operation? I've provided a number of alternatives but I'm not hearing a solution.

**Comment by reuben** [comment]
Redirect stderr only during model creation if you have other logging that you want to keep: here's an example: https://discourse.mozilla.org/t/deepspeech-python-prevent-the-stdout-of-versions/62620/16?u=reuben

**Comment by sharvil** [comment]
SGTM, thanks @reuben.
