### ISSUE TITLE
Does DeepSpeech support converting of speech-to-text for Chinese characters now?

### ISSUE THREAD

**Issue by hongyi-zhao** [mozilla/DeepSpeech#3172]
Hi,

I want to know whether DeepSpeech support converting of speech-to-text for Chinese characters now. Any hints will be highly appreciated.

Regards
HY

**Comment by lissyx** [comment]
Please reach for support on Discourse. There are already people sharing their work regarding chinese models.

**Comment by thesby** [comment]
Do you have any link about this? Thank you.

**Comment by kdavis-mozilla** [comment]
[Discourse](https://discourse.mozilla.org/c/deep-speech/247)
