### ISSUE TITLE
Adjust initialization of the first and last network layers

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#319]
As the first and last network layers have fewer inputs and outputs than the generic hidden layer, they should, according to Xaiver initialization

![correct](https://cloud.githubusercontent.com/assets/12054740/21456840/499d27ec-c92b-11e6-9e7a-c90651b507f0.png)

draw from a different distributions. Currently they don't, but they should. The goal of this issue is to fix that.

**Comment by reuben** [comment]
This can be achieved by using `tf.contrib.layers.xavier_initializer()`, for anyone interested in fixing this bug.
