### ISSUE TITLE
Transfer Learning: Unknown command line flag 'lm_binary_path'

### ISSUE THREAD

**Issue by miladfa7** [mozilla/DeepSpeech#3197]
I run Below command-line for transfer learning English to Persian but unknown the flag 'lm_binary_path'!!
please help me, thanks

Deep Speech version ---> v0.7.4
```
python3 -u DeepSpeech.py \
    --n_hidden 2048 \
    --drop_source_layers 1 \
    --alphabet_config_path alphabet.txt \
    --checkpoint_dir ./deepspeech-0.7.4-checkpoint/ \
    --lm_binary_path lm.binary \
    --train_files ./dataset/clips/train-all.csv \
    --dev_files ./dataset/clips/dev.csv \
    --test_files  ./dataset/clips/test.csv \
    --train_cudnn  --epochs 3 --learning_rate 0.0001
```

**Error : FATAL Flags parsing error: Unknown command line flag 'lm_binary_path'**

**Comment by lissyx** [comment]
>  please help me, thanks

Please read the doc. This flag is not good anymore: use `--scorer_path`.
