### ISSUE TITLE
Got OOM on second iteration

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#321]

**Comment by lorenzfischer** [comment]
Not sure if this is relevant, but I also got OOM (on the 2nd+ iteration) when I tried to run batches that were too large (ds_XXX_batch_size). I resolved this by doing a binary search over varying batch sizes until I found a size that would not result in OOM.

**Comment by kdavis-mozilla** [comment]
@lorenzfischer As you mention, this can be solved by doing a binary search on batch size.

The odd thing, and the reason for this bug, is this happening on the **second** epoch.

Usually, if one is able to complete a **single** epoch the batch selection problem is solved for the combination of GPU and data set, but an OOM on the **second** epoch indicates that this is not always the case and should be explored.

**Comment by tilmankamp** [comment]
@lorenzfischer This should get re-evaluated due to the recent changes in session handling. Now we use **one** session for all epochs and sets (train/dev/test) per one worker's whole training lifetime.

**Comment by lorenzfischer** [comment]
Thanks for the info @tilmankamp! I will try to have a look. Hopefully, I will get round to doing this soon.
