### ISSUE TITLE
TaskCluster-trigger bot

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3228]
We would need a bot (e.g., using https://probot.github.io/docs/) that would allow for reacting to the setting of some github label on PR submitted by contributors.

Upon `ci:run-taskcluster` (for example) on a PR that is **reviewed** and accepted, then the code would, with appropriate credentials:
 - git checkout the PR
 - git push it to trigger taskcluster

**Comment by RucksP** [comment]
Hi I am new to contributing to open source. Just to be clear what you are asking you want a prorobot bot to:

1) Look at the pull requests of any specified repo, or all Mozilla repos?
2) Upon a pull request being assigned a label do something automatically. 
 a) Is there a list of what you want to be done for every label, or do you just want a framework which can be added upon later?

**Comment by lissyx** [comment]
> Hi I am new to contributing to open source. Just to be clear what you are asking you want a probot bot to:

Thanks for your interest!


> Upon a pull request being assigned a label do something automatically.

Yes


>  a) Is there a list of what you want to be done for every label, or do you just want a framework which can be added upon later?

It's really only one use-case here, and my understanding after quickly looking at the probot doc is that it should be fairly easy relying on that stack to add new cases after



> The bot should be added to the probot website.

I don't think so, why should we do that?

It should run on heroku under our control.

**Comment by RucksP** [comment]
Hi can you clarify what is meant by reviewed and accepted?

My first guess is that it means that all reviews have a state of "APPROVED", but I am not sure.

**Comment by lissyx** [comment]
> My first guess is that it means that all reviews have a state of "APPROVED", but I am not sure.

Yes.

> have classified 'reviewed and accepted' to mean any PR which has >= 2 reviews which have a state of "APPROVED"

I'm not sure I understand what that means, often there is only going to be one person reviewing a PR.



> listing all reviews includes reviews which have since been updated. (i.e. if someone initially requests changes, but then approves a PR, there will always be a review whose state is "CHANGES_REQUESTED"

I think we just care about the latest reviews from each of the reviewers ?
So if at time t all the reviewers set an "APPROVED" flag, then we can consider this is fine and proceed.



> I uploaded the bot's code to a repo [here](https://github.com/RucksP/label-reactor)

Thanks, I'll take a look!
