### ISSUE TITLE
Name for Rust bindings

### ISSUE THREAD

**Issue by est31** [mozilla/DeepSpeech#3231]
Hi I've seen you've renamed the library.

https://github.com/mozilla/DeepSpeech/commit/fa2191104878fed468cb16cc8782c345c98ff7aa

Currently the Rust bindings are still named `deepspeech` and `deepspeech-sys`. I wonder which name they should get now. Do you have any ideas?

**Comment by lissyx** [comment]
> Hi I've seen you've renamed the library.
> 
> [fa21911](https://github.com/mozilla/DeepSpeech/commit/fa2191104878fed468cb16cc8782c345c98ff7aa)
> 
> Currently the Rust bindings are still named `deepspeech` and `deepspeech-sys`. I wonder which name they should get now. Do you have any ideas?

Well, if you are okay with renaming (which we would love for consistency), I guess `mozilla-voice-stt` and `mozilla-voice-stt-sys` would be good, nope?

**Comment by est31** [comment]
Names sound good. Will use them. Thanks!

**Comment by est31** [comment]
huh I guess this isn't needed any more: #3280
