### ISSUE TITLE
import_cv2.py can fail for non-wave files

### ISSUE THREAD

**Issue by piraka9011** [mozilla/DeepSpeech#3263]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.15
- **TensorFlow version (use command below)**: 1.15.2
- **Python version**: 3.7
- **CUDA/cuDNN version**: 10.0/7.6.5
- **GPU model and memory**: P100
- **Exact command to reproduce**: `python bin/import_cv2.py /path/to/data`

When running the `import_cv2.py` script, it fails when running [this line](https://github.com/mozilla/STT/blob/master/bin/import_cv2.py#L69) with the following error:

```sh
Traceback (most recent call last):
  File "bin/import_cv2.py", line 220, in <module>
    main()
  File "bin/import_cv2.py", line 215, in main
    _preprocess_data(PARAMS.tsv_dir, audio_dir, PARAMS.space_after_every_character)
  File "bin/import_cv2.py", line 171, in _preprocess_data
    set_samples = _maybe_convert_set(dataset, tsv_dir, audio_dir, space_after_every_character)
  File "bin/import_cv2.py", line 126, in _maybe_convert_set
    for i, processed in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
subprocess.CalledProcessError: Command '['soxi', '-s', 'data/en_cv2/clips/common_voice_en_20088369.wav']' returned non-zero exit status 1.

```

When running `soxi -s data/en_cv2/clips/common_voice_en_20088369.wav` I get the following error.

```
soxi FAIL formats: can't open input file `data/en_cv2/clips/common_voice_en_20088369.wav': WAVE: RIFF header not found
```

My proposed solution is to wrap the subprocess call with a try/except and log a warning saying that the file is invalid.

**Comment by lissyx** [comment]
We have always preferred to try and keep the importers from doing work to fix datasets, and this is one case where the issue is in the dataset.

In that specific case, it seems the Common Voice English relese contains buggy data:
 - have you reported that upstream?
 - have you verified SHA from the release to ensure you have had no corruption at download
 - are you sure you re using the latest release? I think I already saw mention of that and a bugfix release being issued

@piraka9011 If you really want to wrap a try/except then it needs to be done on all the importers.

**Comment by piraka9011** [comment]
> We have always preferred to try and keep the importers from doing work to fix datasets, and this is one case where the issue is in the dataset.

Makes sense.

> have you reported that upstream?

No, I will see if there are issues upstream and see if there's a bugfix release you mentioned.

> If you really want to wrap a try/except then it needs to be done on all the importers.

If it makes the results more reliable, I wouldn't mind :)

**Comment by lissyx** [comment]
> If it makes the results more reliable, I wouldn't mind :)

The problem with not failing hard, is that people might not pay attention to the errors and continue with buggy dataset compared to their expectations.

**Comment by lissyx** [comment]
@piraka9011 Have you reported? I know in the current context it might be trouble some but ...
Also, have you verified your release? I'm pretty sure this is something we got report of and it was fixed.
Should we keep this open?

**Comment by piraka9011** [comment]
All set, thanks @lissyx !
