### ISSUE TITLE
ctc decoder , pip install upgrade problem 

### ISSUE THREAD

**Issue by aszi09** [mozilla/DeepSpeech#3287]
!pip3 install !pip3 install --upgrade -e . 

On google collab 

Obtaining file:///content/DeepSpeech
Requirement already satisfied, skipping upgrade: numpy in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (1.18.5)
Requirement already satisfied, skipping upgrade: progressbar2 in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (3.38.0)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (1.15.0)
Collecting pyxdg
  Using cached pyxdg-0.26-py2.py3-none-any.whl (40 kB)
Collecting attrdict
  Using cached attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Requirement already satisfied, skipping upgrade: absl-py in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (0.8.1)
Collecting semver
  Using cached semver-2.10.2-py2.py3-none-any.whl (12 kB)
Collecting opuslib==2.0.0
  Using cached opuslib-2.0.0.tar.gz (7.3 kB)
Collecting optuna
  Using cached optuna-2.0.0.tar.gz (226 kB)
Requirement already satisfied, skipping upgrade: sox in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (1.4.0)
Requirement already satisfied, skipping upgrade: bs4 in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (0.0.1)
Requirement already satisfied, skipping upgrade: pandas in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (1.0.5)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (2.23.0)
Collecting numba==0.47.0
  Using cached numba-0.47.0-cp36-cp36m-manylinux1_x86_64.whl (3.7 MB)
Requirement already satisfied, skipping upgrade: llvmlite==0.31.0 in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (0.31.0)
Requirement already satisfied, skipping upgrade: librosa in /usr/local/lib/python3.6/dist-packages (from deepspeech-training==0.9.0a7) (0.6.3)
Collecting soundfile
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement ds_ctcdecoder==0.9.0-alpha.7 (from deepspeech-training==0.9.0a7) (from versions: 0.6.1, 0.7.0, 0.7.1, 0.7.3, 0.7.4, 0.8.0a3, 0.8.0a4, 0.8.0a5, 0.8.0a6, 0.8.0a7, 0.8.0a8, 0.8.0, 0.8.1, 0.8.2, 0.9.0a0, 0.9.0a1, 0.9.0a2, 0.9.0a3, 0.9.0a4, 0.9.0a5)
ERROR: No matching distribution found for ds_ctcdecoder==0.9.0-alpha.7 (from deepspeech-training==0.9.0a7)

**Comment by lissyx** [comment]
>  ds_ctcdecoder==0.9.0-alpha.7

this is `mvs_ctcdecoder==0.9.0-alpha.7`, but name will change back.

**Comment by lissyx** [comment]
@aszi09 it's hard to tell if there's a real issue underlying since you purposedly removed all the template we have to share details on your setup.

**Comment by engmubarak48** [comment]
@lissyx how is this issue supposed to be solved ? do i need to change the version file ? i don't understand ?

**Comment by engmubarak48** [comment]
@lissyx thanks. which version is stable then ?

**Comment by engmubarak48** [comment]
@lissyx I installed this version `v0.8.0-alpha.4` and the `pip3 install --upgrade -e .` command successfully worked. i hope you fix the issue with the master version in the future. for now thanks.

**Comment by lissyx** [comment]
> @lissyx I installed this version `v0.8.0-alpha.4` and the `pip3 install --upgrade -e .` command successfully worked. i hope you fix the issue with the master version in the future. for now thanks.

There is no bug, its expected behavior because we unfortunately had to revert name change.

Latest stable release is advertised on github releases page

**Comment by engmubarak48** [comment]
@lissyx indeed you are right I got many other issues with `v0.8.0-alpha.4` but this one advertised on github works well `DeepSpeech 0.8.2`

**Comment by thomasjanssens** [comment]
> > @lissyx how is this issue supposed to be solved ? do i need to change the version file ? i don't understand ?
> 
> Use a stable version, as documented

FYI I'm running into the same issue following the documentation (https://deepspeech.readthedocs.io/en/latest/TRAINING.html), which just instructs to clone the master, and doesn't specify a version.

**Comment by lissyx** [comment]
> > > @lissyx how is this issue supposed to be solved ? do i need to change the version file ? i don't understand ?
> > 
> > 
> > Use a stable version, as documented
> 
> FYI I'm running into the same issue following the documentation (https://deepspeech.readthedocs.io/en/latest/TRAINING.html), which just instructs to clone the master, and doesn't specify a version.

Burning versions everywhere turns to be a maintenance nightmare, https://deepspeech.readthedocs.io/en/latest/ already refers to 0.8.1 stable version.

Please send PR to improve the doc if you can find correct wording that is maintainable.

**Comment by lissyx** [comment]
Thanks for your patience, now that we have ensured renaming has been properly reverted, and we have fixed our macOS CI, I have been able to push a new alpha, which should avoid this error.
