### ISSUE TITLE
no module named deepspeech training help needed thanks 

### ISSUE THREAD

**Issue by aszi09** [mozilla/DeepSpeech#3288]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: #
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

Hey I'm using **google collab** for training the lastest version of Deepspeech on a Spanish training set and I have some problem at the data preprocessing part  here is the GitHub gist of the full code I have done .  https://gist.github.com/aszi09/96bad06114310f2cf5b517df37352e16

It's basically an error on the last part saying that there is no deepspeech_training module. (included in the gist) 

However there are other errors I have ran into which I have absolutely no idea if are important or mean anything in terms of training and future inference. I can provide other info as well , it's just that I'm new to this. 

Also, I have another training going on another dataset with an earlier version which works (0.7.4)  after 50 minutes it still hasn't completed an epoch, I didn't change any parameters when running so I'm unsure as to what the issue may be. 

Thanks in advance

**Comment by lissyx** [comment]
@aszi09 Please use Discourse for support request and read the documentation.
