### ISSUE TITLE
Windows training: Exception: Could not find Opus library. Make sure it is installed

### ISSUE THREAD

**Issue by coen22** [mozilla/DeepSpeech#3294]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No mods
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 r2004
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 1.15.2
- **TensorFlow version (use command below)**:
- **Python version**: 3.6
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: RTX 2060 6GB
- **Exact command to reproduce**: C:\Python36\python.exe DeepSpeech.py --n_hidden 2048 --load_checkpoint_dir ../../deepspeech-0.8.0-checkpoint --epochs 50 --train_files '../Import-CGN/train_data_strip.csv' --dev_files '../Import-CGN/dev_data_strip.csv' --test_files '../Import-CGN/test_data_strip.csv' --learning_rate 0.0001 --load_cudnn --alphabet_config_path ../Import-CGN/alphabet.txt --save_checkpoint_dir ../../deepspeech-0.8.0-checkpoint --dropout_rate 0.1 --train_batch_size 20 --dev_batch_size 20 --test_batch_size 20 --feature_cache ./feature2.cache --cache_for_epochs 5 --augment reverb[p=0.1,delay=50.0~30.0,decay=10.0:2.0~1.0] --augment resample[p=0.1,rate=12000:8000~4000] --augment codec[p=0.1,bitrate=48000:16000] --augment volume[p=0.1,dbfs=-10:-40] --augment pitch[p=0.1,pitch=1~0.2] --augment tempo[p=0.1,factor=1~0.5] --augment warp[p=0.1,nt=4,nf=1,wt=0.5:1.0,wf=0.1:0.2] --augment frequency_mask[p=0.1,n=1:3,size=1:5] --augment time_mask[p=0.1,domain=signal,n=3:10~2,size=50:100~40] --augment dropout[p=0.1,rate=0.05] --augment add[p=0.1,domain=signal,stddev=0~0.5] --augment multiply[p=0.1,domain=features,stddev=0~0.5]

I'm getting the exception Exception: Could not find Opus library. Make sure it is installed

So far I've tried installing the opus-tools and opus file library into System32. I've tried installing it with 'choco', but python can't find the library. I've noticed that the 'init.py' doesn't include a case for Windows and find_library always returns 'None'.

I already saw a thread that answered this for macOS, but there you can simply do it with brew. Is there a way I can get it to work on Windows?

Thanks in advance! :)

**Comment by lissyx** [comment]
We don't support training on Windows, so I can't help for sure.

**Comment by lissyx** [comment]
> Exception: Could not find Opus library. Make sure it is installed

Having a full stack could at least help have an hint where the issue is ...

**Comment by lissyx** [comment]
@coen22 You also don't explicitely document:
 - how you setup things,
 - what version you are working on

We already have a dep against `opuslib`: https://github.com/mozilla/DeepSpeech/blob/v0.9.0-alpha.6/setup.py#L60 but since we have no stack shared I can't verify if it has been properly installed ?



> I've noticed that the 'init.py' doesn't include a case for Windows and find_library always returns 'None'.

Because we don't support training on Windows.

**Comment by lissyx** [comment]
> **CUDA/cuDNN version**: 10.1

Please triple check your setup, TensorFlow r1.15 is documented to require CUDA 10.0 ...

**Comment by coen22** [comment]
> @coen22 You also don't explicitely document:
> 
> * how you setup things,
> * what version you are working on
> 
> We already have a dep against `opuslib`: https://github.com/mozilla/DeepSpeech/blob/v0.9.0-alpha.6/setup.py#L60 but since we have no stack shared I can't verify if it has been properly installed ?
> 
> > I've noticed that the 'init.py' doesn't include a case for Windows and find_library always returns 'None'.
> 
> Because we don't support training on Windows.

I'm using 0.8.0 right now. The issue isn't that the python opuslib isn't there, but rather that the opus binaries can't be found. 
But if it's really too complicated, I'll simply install Ubuntu.

`I Loading best validating checkpoint from ../../deepspeech-0.8.0-checkpoint\best_dev-1185136
I Loading variable from checkpoint: beta1_power
I Loading variable from checkpoint: beta2_power
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias/Adam
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias/Adam_1
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel/Adam
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel/Adam_1
I Loading variable from checkpoint: global_step
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/bias/Adam
I Loading variable from checkpoint: layer_1/bias/Adam_1
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_1/weights/Adam
I Loading variable from checkpoint: layer_1/weights/Adam_1
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/bias/Adam
I Loading variable from checkpoint: layer_2/bias/Adam_1
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_2/weights/Adam
I Loading variable from checkpoint: layer_2/weights/Adam_1
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/bias/Adam
I Loading variable from checkpoint: layer_3/bias/Adam_1
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_3/weights/Adam
I Loading variable from checkpoint: layer_3/weights/Adam_1
I Loading variable from checkpoint: layer_5/bias
I Loading variable from checkpoint: layer_5/bias/Adam
I Loading variable from checkpoint: layer_5/bias/Adam_1
I Loading variable from checkpoint: layer_5/weights
I Loading variable from checkpoint: layer_5/weights/Adam
I Loading variable from checkpoint: layer_5/weights/Adam_1
I Loading variable from checkpoint: layer_6/bias
I Loading variable from checkpoint: layer_6/bias/Adam
I Loading variable from checkpoint: layer_6/bias/Adam_1
I Loading variable from checkpoint: layer_6/weights
I Loading variable from checkpoint: layer_6/weights/Adam
I Loading variable from checkpoint: layer_6/weights/Adam_1
I Loading variable from checkpoint: learning_rate
I STARTING Optimization
I Invalidating feature cache
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                            multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\P70070113\Documents\Projects\DeepSpeech\deepspeech_training\util\augmentations.py", line 158, in _augment_sample
    augmentation.apply(sample, clock)
  File "C:\Users\P70070113\Documents\Projects\DeepSpeech\deepspeech_training\util\augmentations.py", line 303, in apply
    sample.change_audio_type(new_audio_type=AUDIO_TYPE_OPUS, bitrate=bitrate)  # will get decoded again downstream
  File "C:\Users\P70070113\Documents\Projects\DeepSpeech\deepspeech_training\util\audio.py", line 111, in change_audio_type
    write_audio(new_audio_type, audio_bytes, self.audio, audio_format=self.audio_format, bitrate=bitrate)
  File "C:\Users\P70070113\Documents\Projects\DeepSpeech\deepspeech_training\util\audio.py", line 350, in write_audio    return write_opus(audio_file, pcm_data, audio_format=audio_format, bitrate=bitrate)
  File "C:\Users\P70070113\Documents\Projects\DeepSpeech\deepspeech_training\util\audio.py", line 279, in write_opus
    import opuslib  # pylint: disable=import-outside-toplevel
  File "C:\Python36\lib\site-packages\opuslib\__init__.py", line 19, in <module>
    from .classes import Encoder, Decoder  # NOQA
  File "C:\Python36\lib\site-packages\opuslib\classes.py", line 6, in <module>
    import opuslib.api.decoder
  File "C:\Python36\lib\site-packages\opuslib\api\__init__.py", line 22, in <module>
    'Could not find opus library. Make sure it is installed.')
Exception: Could not find opus library. Make sure it is installed.
"""`

**Comment by coen22** [comment]
> > **CUDA/cuDNN version**: 10.1
> 
> Please triple check your setup, TensorFlow r1.15 is documented to require CUDA 10.0 ...

Tensorflow works, I've already trained a model without augmentation

**Comment by lissyx** [comment]
> The issue isn't that the python opuslib isn't there, but rather that the opus binaries can't be found.

Well, sorry, but this is a Windows-level issue, I can't help.



> I simply downloaded the 0.8.0 source code and followed the install guide.

There's a reason we ask: simply saying you followed docs does not help us catch mistakes you might have made by looking at wrong doc, or misinterpreting.

e.g "I simply downloaded the 0.8.0 source code " do you mean a zip file or "git clone" then "git checkout" ?
Training from a zip can be broken, especially since we don't support training on Windows.



> Tensorflow works, I've already trained a model without augmentation

And we know there are TensorFlow-level bugs wrt CUDA and CUDNN, so if you add unsupported versions in the mix, it's going to make it more complex to debug. Yes, it's unrelated at that point, but if you already don't follow the docs on that point what kind of guarantee do we have you properly followed others docs?

**Comment by lissyx** [comment]
Also @coen22 just to be clear, while we don't support Windows training for the moment, several people reported successfully doing it but nobody cared enough to:
 - share extended details
 - fix code
 - fix doc

So we simply can't know if "it should work" or if there are some pieces here and here that needs to be fixed. That's why even though I can't help on Windows-specific bits, I'd like we get it to work for you so maybe we can have a chance to fix code / doc?

**Comment by coen22** [comment]
> Also @coen22 just to be clear, while we don't support Windows training for the moment, several people reported successfully doing it but nobody cared enough to:
> 
> * share extended details
> * fix code
> * fix doc
> 
> So we simply can't know if "it should work" or if there are some pieces here and here that needs to be fixed. That's why even though I can't help on Windows-specific bits, I'd like we get it to work for you so maybe we can have a chance to fix code / doc?

Thank you, but mostly everything is working. training and inference are going great. The docs are also great, with some common sense I was able to work out how to set everything up on Windows. The augmentation s the only minor issue that isn't working and it's actually due to the python opuslib wrapper.

I've also reported the issue to the appropriate repository, as this isn't maintained by Mozilla.
https://github.com/orion-labs/opuslib/issues/18

I do know where the issue is, my attempts to fix it have been unsuccessful. It's in this file:
https://github.com/orion-labs/opuslib/blob/master/opuslib/api/__init__.py
The find_library method always returns None on Windows by design. https://docs.python.org/3/library/ctypes.html?highlight=find_library
If I find something I'll let you know :)

**Comment by lissyx** [comment]
> [](https://github.com/orion-labs/opuslib/issues/18)
> 
> I do know where the issue is, my attempts to fix it have been unsuccessful. It's in this file:
> https://github.com/orion-labs/opuslib/blob/master/opuslib/api/__init__.py
> The find_library method always returns None on Windows by design. https://docs.python.org/3/library/ctypes.html?highlight=find_library
> If I find something I'll let you know :)

Ok, so the bug is absolutely not on our side? Then I really don't see how we can help :/. Still good to know it works.
If it's upstream, should we close this?

**Comment by coen22** [comment]
No, I don't think so. I'll close this thread and hope anyone can help with libopus :)
