### ISSUE TITLE
Speaker Recognition Implementation

### ISSUE THREAD

**Issue by alexivaner** [mozilla/DeepSpeech#3298]
Hi, I would like to ask if is it possible that we could modify deep speech architecture by ourselves to add a speaker recognition inside the deep speech. So the model would recognize both speaker and speech as well. I really want to contribute if it is possible since my research currently also in the speaker and speech recognition area.

**Comment by lissyx** [comment]
> is it possible that we could modify deep speech architecture

Hacking is always welcome, but I'm unsure it is in the current scope of our project and whether this can be sustainable. cc @reuben ?

**Comment by reuben** [comment]
Yep, definitely out of scope for our project, and I have a hard time picturing how we could land this into our code in a way that is maintainable. Leveraging the architecture and the pre-trained checkpoints to target this new task should be possible though.

**Comment by alexivaner** [comment]
I see so the problem is to find a way that it will be maintainable after it released right? But it really possible to do that? because I need some clue before I really do the research about this.

**Comment by reuben** [comment]
The keyword you're looking for is speaker diarization.
