### ISSUE TITLE
Fix menus on http://doyouunderstand.me

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#331]
Menus on [doyouunderstand.me](http://doyouunderstand.me) don't do anything.

**Comment by lissyx** [comment]
Are you referring to the "Parameter WER" ? I have to admit I don't see what it should contain :)

**Comment by tilmankamp** [comment]
@lissyx It will contain charts with one parameter on X-Axis and the corresponding WER on Y-Axis. Those will automatically get generated, if the log contains parameter sets that just differ in one parameter from each other.

Example: If we did 2+ training runs with different context parameter each, we will automatically get a parameter chart for the parameter "Context", which will contain our 2+ runs with the values of context on X-Axis and the corresponding WER on Y-Axis.

@kdavis-mozilla This is a bit nontransparent and confusing, yes. So I'll provide some code that removes the menu bar entry, as long as there are no Parameter chars.
