### ISSUE TITLE
libdeepspeech.io module not found

### ISSUE THREAD

**Issue by avmetze** [mozilla/DeepSpeech#3311]
Hello,

I cloned the .Net DeepSpeech exaple project. After adding my model and trying to launch I get the error:
libdeepspeech.io not found.
![image](https://user-images.githubusercontent.com/65344108/92248859-97276500-eec9-11ea-90ef-0e3651f9abe2.png)

**Comment by lissyx** [comment]
No idea. @carlfm01 maybe ?

**Comment by carlfm01** [comment]
Ugh @avmetze sorry for the delay, can you check if Visual Studio restored packages? Under references, manage NuGet packages and restore.

**Comment by carlfm01** [comment]
Looks you are using Visual Studio 2019, I confirm it is working well with v0.8 and vs 2019, please check the installed NuGets.

**Comment by lissyx** [comment]
> Looks you are using Visual Studio 2019, I confirm it is working well with v0.8 and vs 2019, please check the installed NuGets.

So this is indeed a support request, not a bug. @avmetze Please follow instructions and reach for support on Discourse.

**Comment by avmetze** [comment]
Thanks for YouTube anders, i will check your recommandations. Is it working
with Windows?

lissyx <notifications@github.com> schrieb am Di., 8. Sept. 2020, 17:35:
