### ISSUE TITLE
Add support for ElectronJS 10.0 / 10.1

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3316]

**Comment by lissyx** [comment]
@dsteinman Would you be willing to take it?

**Comment by lissyx** [comment]
Tentative PR #3316 shows we have a bug on node-gyp-cache: electron and nodejs headers gets merged together.

**Comment by dsteinman** [comment]
Sorry I wasn't able to get to this @lissyx

It's a bit unfortunate they keep bumping the Electron version so often.

**Comment by lissyx** [comment]
> Sorry I wasn't able to get to this @lissyx
> 
> It's a bit unfortunate they keep bumping the Electron version so often.

Fortunately its easy so far to update 😉
