### ISSUE TITLE
Add ability to monitor current run to doyouunderstand.me

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#332]
Currently I end up monitoring the log file `.deepspeech_wer.out.log` through `tail`
```
tail -n 200 -f ~doyouunderstand/.deepspeech_wer.out.log
```
and periodically reporting the WER and epoch times to our IRC channel.

This process should be automated and a report on the current run containing things like current loss, hours per epoch, current training WER, current validation WER....should be posted either to [doyouunderstand.me](http://doyouunderstand.me/) or to an internal web site.

**Comment by lissyx** [comment]
Could "Internal website" just be a web server running on the host and exposing the logs? Or do we want something smarter?

**Comment by tilmankamp** [comment]
Description/task got incorrect/irrelevant, as doyouunderstand.me will now be updated on every WER report of every training and soon get real burndown charts (#490). Training coordinators of running trainings will also provide pages for live monitoring (#491).
