### ISSUE TITLE
Docker build fails: `Could not find any nccl.h matching version '2.4' in any subdirectory:`

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3321]
https://community-tc.services.mozilla.com/tasks/cce8T86_RCibpqyvrrKqTQ/runs/1/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fcce8T86_RCibpqyvrrKqTQ%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by reuben** [comment]
What NVIDIA update?

**Comment by lissyx** [comment]
> What NVIDIA update?

They updates the Dockerfile and moved from NCCL 2.4 to 2.7
