### ISSUE TITLE
General Question on Augmentation for someone training over 1000 hrs. 

### ISSUE THREAD

**Issue by engmubarak48** [mozilla/DeepSpeech#3328]
Hi, 

Since there are a number of augmentations supported by Deepspeech and training of big data (i.e. over 1000 hrs) will take a very long time (min:12 days depending on the resources), I would like to know if there are suggestions/recommendations of choosing augmentations & their parameters for such scale of data. It would be nice if someone who trained such a scale of data could share with me his experience. or any thread where there's this kind of discussion. Also, is it recommended to only use the default augmentations?

NB: sorry if this question is already asked, I checked the issues and didn't see such a thread so far. 

Thanks.

**Comment by lissyx** [comment]
@engmubarak48 Please respect documented process and reach for support on Discourse.
