### ISSUE TITLE
About proper Training Model and settings for building Subtitle by using Deepspeech GitHub Project

### ISSUE THREAD

**Issue by soheilpaper** [mozilla/DeepSpeech#3330]
I am newbie in speech-to-text AI , but i am trying to find suitable deepspeech setting models for auto extracting the subtitle STR file from the video file, so when i am using the **deepspeech-0.6.1** by this setting via [this Colab Notebook][1]:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/So-AI-love/AutoSub/blob/master/Colab_try_mozilla_deepspeech_api_notebook2.ipynb)
```
!deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --lm deepspeech-0.6.1-models/lm.binary --trie deepspeech-0.6.1-models/trie --audio test.wav   --extended --json  
```

gave me a better text like this:

> and people fishing up in this wall i disarrayed anaveni an derstand
> you angle with the amidei and desol make it a relation to me now i was
> angry at first to the twin tione can annihilate them how we can tear
> down there or hiawatha known by a truly for policing the others and
> tautening to no contraction i get it summoned and you can never the
> world with the contents one man fight latest him you apaian why we
> could have her own world i guess when behind they are creators to die
> oh many a unnumbered things out on to donneraile mere the moment were
> i to tipple gave them a long amain ere hardey created on a new nothing
> pertinacity of monomania he is ugly man and this was his rage

But when i am using this GitHub project :

[https://github.com/abhirooptalasila/AutoSub][2]

which is using the **deepspeech-0.8.2**, by this kind of command:

```
!python3 autosub/main.py  --model /content/AutoSub/deepspeech-0.8.2-models.pbmm --scorer /content/AutoSub/deepspeech-0.8.2-models.scorer --file test.wav
```
It create [this kind of STR file][3] which have too differences with **deepspeech-0.6.2** result as show above ( lower quality!):

> 00:00:00,15 --> 00:00:07,90 and people the tooth allies
> 
> 2 00:00:09,15 --> 00:00:09,80 this
> 
> 3 00:00:19,05 --> 00:00:53,65 and isaiah pan i understand your anger
> with him and maybe your ride out should exist
> 
> 4 00:00:54,05 --> 00:00:55,25 a red
> 
> 5 00:00:55,70 --> 00:00:56,10 and
> ...

So i don't know what is differences of using the `--model /content/AutoSub/deepspeech-0.8.2-models.pbmm --scorer /content/AutoSub/deepspeech-0.8.2-models.scorer` setting instead of `--model deepspeech-0.6.1-models/output_graph.pbmm --lm deepspeech-0.6.1-models/lm.binary --trie deepspeech-0.6.1-models/trie` setting and how i could improve the setting to have better quality subtitle for videos, by using some more welt trained models via others open-source databases like [said here][4]:

> **2.1 Data Collection**
> 
> 
> <p style="color:gray;font-size:15px">We want to use some open-source
> datasets, that are available online</p>

<ul style="color:gray">
    <li><b><a href="https://www2.imda.gov.sg/NationalSpeechCorpus">National Speech Corpus:</a></b><p1> Contains 2000 hours of locally accented audio and text transcriptions</p1></li>
 <li><b><a href="https://wordnet.princeton.edu/download">LibriSpeech:</a></b><p1> Dataset consists of a large-scale corpus of around 1000 hours of English speech</p1></li>
<li><b><a href="https://code.google.com/archive/p/wiki-links/downloads">TIMIT:</a></b><p1>  A collection of recordings of 630 speakers of American English</p1></li>
<li><b><a href="https://psi.engr.tamu.edu/l2-arctic-corpus/">L2-ARCTIC:</a></b><p1>  A non-native English speech corpus
</p1></li>
</ul>

or etc methods.

Also asked here:

https://ai.stackexchange.com/questions/23675/about-proper-training-model-and-settings-for-building-subtitle-by-using-deepspee

Thanks.

  [1]: https://colab.research.google.com/github/So-AI-love/AutoSub/blob/master/Colab_try_mozilla_deepspeech_api_notebook2
  [2]: https://github.com/abhirooptalasila/AutoSub
  [3]: https://0bin.net/paste/6A4tCMC7#6ns48V0UlpjgF3Tl-8e9pPC0BwKi9UW7O4nJXlsgGGv
  [4]: https://github.com/Gopi-Durgaprasad/Speech-To-Text

**Comment by lissyx** [comment]
Please reach for support on Discourse

**Comment by lissyx** [comment]
> But when i am using this GitHub project :
> 
> https://github.com/abhirooptalasila/AutoSub
> 
> which is using the **deepspeech-0.8.2**, by this kind of command:

We cant provide support for third party tools, sorry.

**Comment by ftyers** [comment]
Hi @soheilpaper, this looks like a support request, not an issue with DeepSpeech. We use GitHub issues to manage issues with the code, not for end-user help. If you'd like end-user help, you can make a new post on [Discourse](https://discourse.mozilla.org/) under the [Mozilla STT](https://discourse.mozilla.org/c/mozilla-voice-stt/) topic and members of the DeepSpeech community will be able to help you there. Hope this helps and thanks for your interest in DeepSpeech!
