### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by alterEgo123** [mozilla/DeepSpeech#3332]
I am trying to decode a wav file after training a model from scratch, i finished the training and the testing phase without errors and I get the WER & CER and Loss values. NB: I’ve already done the decoding with this command with no errors but it appeared when I tested with a new model.

```
native_client/deepspeech --model /home/xyz/DeepSpeech/data/exprt_dir/output_graph.pb --scorer /home/xyz/DeepSpeech/data/lm/lm.scorer --audio data/test5.wav --beam_width 9000 > data/decoding.txt
TensorFlow: v2.2.0-15-g518c1d0
DeepSpeech: v0.9.0-alpha.3-0-g78ae08c
Warning: reading entire model file into memory. Transform model file into an  mmapped graph to reduce heap usage.
2020-09-22 12:15:00.293543: I tensorflow/core/platform/cpu_feature_guard.cc:143]  Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
terminate called after throwing an instance of 'std::length_error'
what():  vector::_M_default_append
Abandon (core dumped)
```

I tried the command without the scorer, pipe and beam and with a file from the train dataset but the error still persists.
you find below the versions of packages i have (running pip list shows more than these packages but i just kept the important ones)

```
(deepspeech-venv) (base) root@xyz:/home/xyz/DeepSpeech# pip  list
Package              Version      Location                            
-------------------- ------------ ------------------------------------
deepspeech-training  0.9.0a3      /home/xyz/DeepSpeech/training
ds-ctcdecoder        0.9.0a3      
tensorboard          1.15.0       
tensorflow-estimator 1.15.1       
tensorflow-gpu       1.15.2
```

```
(deepspeech-venv) (base) root@xyz:/home/xyz/DeepSpeech# python3 -c 'import tensorflow as tf; print(tf.__version__)'
1.15.2
```

**Comment by lissyx** [comment]
> TensorFlow: v2.2.0-15-g518c1d0
> DeepSpeech: v0.9.0-alpha.3-0-g78ae08c

This is old, please try and reproduce with current master and/or git bisect it.



> terminate called after throwing an instance of 'std::length_error'
> what():  vector::_M_default_append
> Abandon (core dumped)

There's nothing really actionable here ....

You don't even share your hardware. Is this x86-64 ? arm64 ? armv7 ? linux ? windows ? macOS ? android ?
Are those binaries you self-built or are those prebuilt binaries?
How did you trained the model?

**Comment by lissyx** [comment]
> NB: I’ve already done the decoding with this command with no errors but it appeared when I tested with a new model.

Do you repro with our models? Do you repro with our binaries?

**Comment by alterEgo123** [comment]
@lissyx Sorry for the missing details.
I run on Linux, ubuntu 18.04. I don't use any prebuilt model, i trained my own model from scratch.
CUDA Version: 10.2
GPU: nvidia GeForce RTX 2060

**Comment by lissyx** [comment]
What about binaries ? Selfbuilt ? How much ram ?

**Comment by alterEgo123** [comment]
@lissyx I used prebuilt binaries and i have 6GB GPU memory

**Comment by lissyx** [comment]
> @lissyx I used prebuilt binaries and i have 6GB GPU memory

System ram ? Did you tried gpu binaries ? Non gpu ? Tflite model ? Pbmm model ?

**Comment by lissyx** [comment]
Could you please answer ALL of my questions ?

**Comment by lissyx** [comment]
I'm not super happy to see that you are cross-posting on discourse and on github and still lack to share the required informations: this is making debugging super-painful and is wasting valuable time.
