### ISSUE TITLE
Bad analysis

### ISSUE THREAD

**Issue by ofer1111** [mozilla/DeepSpeech#3333]
Hello,
I took your .NET sample DeepSpeech.WPF using both deepspeech-0.8.0 and deepspeech-0.8.2 along with deepspeech-0.8.2-models.scorer and got really bad results on some audios i used. 
The recording sounds well and we had a couple of participants there with different accents and eventually got really bad results. A couple of gibberish words with no context. Just wanted to know whether it's expected and there is anything I can do to improve that. 
The samples that you put are great but they are very short. I'm talking about records of more than a minute. I can send you those samples

Thanks

**Comment by lissyx** [comment]
@ofer1111 As documented, please reach for support on Discourse.

**Comment by lissyx** [comment]
> with different accents and eventually got really bad results.

It is also explicitely stated in the release page that the model can perform badly depending on the accents.

**Comment by ofer1111** [comment]
It’s English (UK) accent

Many thanks,

Ofer Rosenberg
www.AGATSoftware.com<http://www.agatsoftware.com/>
SIP: oferr@agatsoftware.com<mailto:oferr@agatsoftware.com>
  [logo-agat]
