### ISSUE TITLE
DeepSpeech for Ubuntu 18.04

### ISSUE THREAD

**Issue by neodeepspeech** [mozilla/DeepSpeech#3334]
DeepSpeech for Ubuntu 18.04

Is possible to install DeepSpeech on Ubuntu 18.04?

Where can I have a tutorial about install for Ubuntu 18.04?

I only see about DeepSpeech only for Ubuntu 16.04 at this guide, but it does not work
https://progur.com/2018/02/how-to-use-mozilla-deepspeech-tutorial.html

**Comment by lissyx** [comment]
@neodeepspeech Please reach for support on Discourse.


> I only see about DeepSpeech only for Ubuntu 16.04 at this guide, but it does not work
> https://progur.com/2018/02/how-to-use-mozilla-deepspeech-tutorial.html

This is not our tutorial, we can't provide support for that.



> Is possible to install DeepSpeech on Ubuntu 18.04?

Yes. Everything should work.

**Comment by neodeepspeech** [comment]
Is there forum or useful keywords for search a guide DeepSpeech for Ubuntu 18.04?
