### ISSUE TITLE
`CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by etyhh** [mozilla/DeepSpeech#3335]
Hi,
system info as below:

- **just pip3 install deepspeech-gpu**:
- **centos 7**:
- **TensorFlow not installed **:
- **Python 3.6.8**: 
- **CUDA 10.1 cudnn 7.6 **:
- **cmd caused problem : deepspeech --model deepspeech-0.8.1-models.pbmm --scorer deepspeech-0.8.1-models.scorer --audio audio/2830-3980-0043.wav**:

error message:
version `CXXABI_1.3.8' not found (required by /home/xx/tmp/deepspeech-gpu-venv/lib/python3.6/site-packages/deepspeech/lib/libdeepspeech.so)

Thanks

**Comment by lissyx** [comment]
This is not a bug, please reach for support on Discourse. Your distro is too old for our prebuilt packages, please rebuild.
