### ISSUE TITLE
Expose Hot Words into binaries

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3336]
This is a follow-up of #3297: new API entry points have been added and exposed in all bindings.

This bug is about replicating what has been done in #3297 for using this new API in the Python binary and do that in all our other binaries, as well as add CI testing:
 - [x] JavaScript (NodeJS, ElectronJS) #3361 
 - [x] Java (APK app) #3393 
 - [x] .Net #3416 #3461 

Anyone willing to take care of that is welcome to ask more details, here or on Matrix. This is a good way to get into the project: it's technically easy but it touches several places as well as CI testing, so you get a nice overview of the surface.

**Comment by imrahul361** [comment]
I like to work on it? Is it available? @lissyx

**Comment by lissyx** [comment]
> I like to work on it? Is it available? @lissyx

Yes, you are welcome. I guess it'd be more efficient if you can join us on Matrix for helping you about the codebase!

**Comment by imrahul361** [comment]
Ok Sure @lissyx

**Comment by imrahul361** [comment]
What's the room name? @lissyx

**Comment by ftyers** [comment]
@imrahul361 https://chat.mozilla.org/#/room/#machinelearning:mozilla.org

**Comment by imrahul361** [comment]
I am on it. Trying to fix the issue @ftyers

**Comment by lissyx** [comment]
Thanks @imrahul361 I've taken your last PR and landed it.

**Comment by imrahul361** [comment]
Ok thank you 😁 and sorry for the delay
