### ISSUE TITLE
DeepSpeech [0.8.2] - tflite model with gpu/nnapi delegate is not working

### ISSUE THREAD

**Issue by cnair-83** [mozilla/DeepSpeech#3341]
When I run 0.8.2 pre-trained release model with gpu delegate enabled is giving following error

TensorFlow: v2.2.0-24-g1c1b2b9
DeepSpeech: v0.8.2-0-g02e4c76
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for NNAPI.
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

**Comment by lissyx** [comment]
> When I run 0.8.2 pre-trained release model with gpu delegate enabled is giving following error
> 
> TensorFlow: v2.2.0-24-g1c1b2b9
> DeepSpeech: v0.8.2-0-g02e4c76
> INFO: Initialized TensorFlow Lite runtime.
> INFO: Created TensorFlow Lite delegate for NNAPI.
> ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

Have you read the releases notes about that feature? It's here for you to experiment, but it's clearly explained that released model are not expected to work out of the box.

**Comment by lissyx** [comment]
@cnair-83 You're welcome to experiment and share on that feature, but until you have some code to share, I'd be better we take that discussion to Discourse.

**Comment by lissyx** [comment]
> Have you read the releases notes about that feature?

My bad, it looks like it was indeed missing. I've clarified that.
