### ISSUE TITLE
Support for .NetCore on Linux

### ISSUE THREAD

**Issue by dev-bre** [mozilla/DeepSpeech#3342]
Hi,
I can see there is a nuget package available, is this compatible with .NetCore running on Linux?

**Comment by lissyx** [comment]
> Hi,
> I can see there is a nuget package available, is this compatible with .NetCore running on Linux?

As documented, there is only .Net Framework compatiblity.

#3285 is already open for .Net Standard, I don't know the differences between all those variants, maybe @carlfm01 can enlight us.

If you are interested in this support, the best way is to submit patches.

**Comment by dev-bre** [comment]
Thanks for the reference. Feels like it is better to keep the conversation in the other thread maybe?
