### ISSUE TITLE
Feature request for using Deep speech as a feature extractor also.

### ISSUE THREAD

**Issue by meherabhi** [mozilla/DeepSpeech#3349]
The 29x1 output with the probabilities of each alphabet can be used as a feature in several other tasks. Hence it is my request to include it as a feature.
Also if there is already a way to extract them, please let me know because i intend to use them in my work.

**Comment by olafthiele** [comment]
Pleases don't double post, we'll let it stay here as it is a more technical question.

**Comment by lissyx** [comment]
This is clearly out of scope.
