### ISSUE TITLE
Running DeepSpeech on AWS p2

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#335]
- Clarify which AWS account to use / prepare developer access
- Prepare/import AWS p2 instance for DeepSpeech execution
- Prepare instance for distributed synchronous training run on p2.2xlarge (current solution with gradient averaging)
- Do some demo training to verify solution

**Comment by kdavis-mozilla** [comment]
Could you clarify a bit what the goal is.

**Comment by tilmankamp** [comment]
@kdavis-mozilla see description

**Comment by kdavis-mozilla** [comment]
@tilmankamp Could we limit this just to testing distributed TF?

**Comment by kdavis-mozilla** [comment]
@tilmankamp And also only on p2.xlarge instances

**Comment by tilmankamp** [comment]
@kdavis-mozilla updated :)

**Comment by kdavis-mozilla** [comment]
@tilmankamp I already started the process of switching our old vaani account to ET.

**Comment by kdavis-mozilla** [comment]
@tilmankamp The vaani account has been switched to ET.

**Comment by tilmankamp** [comment]
AWS run completed 4 epochs on p2.8xlarge. Performance turned out to be lower than expected. 5th epoch failed due to OOM issue (unexpected and unclarified).
