### ISSUE TITLE
How to use Deep Speech with C# .Net application?

### ISSUE THREAD

**Issue by FurkanGozukara** [mozilla/DeepSpeech#3364]
I have downloaded and installed DeepSpeech 0.8.2 package from NuGet but from there I have no clue how to use

So can someone point me where to to download trained dataset

How to transcript an mp3 file into the text file

Thank you very much for help

I can work with any C# .NET version if necessary

I am working on windows 10. I have no strong GPU but strong CPU atm

**Comment by lissyx** [comment]
@FurkanGozukara Please read and apply the issue template: this is a support request, so please ask on Discourse. All of your questions are extensively covered by our docs and forums.

**Comment by FurkanGozukara** [comment]
@lissyx can you please point me a link where it is extensively covered?

**Comment by lissyx** [comment]
> @lissyx can you please point me a link where it is extensively covered?

Have you had a look at our documentation ? It does not looks like you did.

Two first links:
 - "Using a pre-trained model" https://deepspeech.readthedocs.io/en/v0.8.2/USING.html
 - "Training your own model" https://deepspeech.readthedocs.io/en/v0.8.2/TRAINING.html
 - .Net API reference: https://deepspeech.readthedocs.io/en/v0.8.2/DotNet-API.html
 - .Net usage example: https://deepspeech.readthedocs.io/en/v0.8.2/DotNet-Examples.html

What part did you not understand in "this is not a discussion space, please reach for support on Discourse" ?

**Comment by ali-h2010** [comment]
I am getting the error:
`System.DllNotFoundException: 'Unable to load DLL 'libdeepspeech.so' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
`
Can someone please guide me to how can i get 'libdeepspeech.so'? The documentation says that the binaries are already provided but i couldn't find this DLL anywhere.

**Comment by ali-h2010** [comment]
I resolved the error by installing C++ build tools 2015. I also installed python on the console which showed me what i was missing such as the build tools and python.

Still the sample is crashing and causing all kinds of issues.
I will try to use the nuget package and follow the API document to replicate it myself.

**Comment by thnguyen00** [comment]
Late, but I installed deepspeech and deepspeech-gpu and that resolved the issues and it's wroking

**Comment by Dmitrys91** [comment]
@thnguyen00 it's not too late bro <3 thx
