### ISSUE TITLE
How to save output to a text file when using command line interface

### ISSUE THREAD

**Issue by FurkanGozukara** [mozilla/DeepSpeech#3365]
This command is working and display the output

However I could not find the command to save the output a text file

What are my options? I want to generate text of speech to upload youtube video for subtitling (yes youtube algorithm failed to auto generate)

`deepspeech --model deepspeech-0.8.2-models.pbmm --scorer deepspeech-0.8.2-models.scorer --audio audio/a.wav`

Here the above command output but I can not save output to a file which I need

![image](https://user-images.githubusercontent.com/19240467/95310799-7e79e880-0895-11eb-9f43-e20942564bd8.png)

**Comment by lissyx** [comment]
@FurkanGozukara i'm loosing patience.

**Comment by lissyx** [comment]
Next time i'll report to github for harrasment if you keep ignoring our code of conduct and use github issues instead of Discourse.

**Comment by FurkanGozukara** [comment]
@lissyx  where is Discourse I couldn't find it

**Comment by ftyers** [comment]
@FurkanGozukara merhaba! Discourse [burada](https://discourse.mozilla.org/c/mozilla-voice-stt/247) bulabilirsin. Burada GitHub issues'da kullancılara yardım edebilmiyoruz, maalesef. Discourse'ta bir yeni post yap lütfen!
