### ISSUE TITLE
Do DeepSpeech have subtitle (SRT) output mode? How can I merge words into the proper sentences?

### ISSUE THREAD

**Issue by FurkanGozukara** [mozilla/DeepSpeech#3366]
I am trying to use DeepSpeech as subtitle software

So far I have progressed really well

Downloaded example .NET and progressed to parse with meta and simple text as below

I have used this video for testing purposes : https://www.youtube.com/watch?v=oDt4ckGa-lM&ab_channel=InternationalChristianFilmFestival

Donwloaded with youtube dl and extracted audio as vaw with below command

`ffmpeg -i accept.mkv -acodec pcm_s16le -ac 1 -ar 16000 accept.wav`

Here the code I use. Am I getting the maximum accurateness that is possible?

` DeepSpeechClient.DeepSpeech deepSpeechClient =
     new DeepSpeechClient.DeepSpeech("deepspeech-0.8.2-models.pbmm");

            deepSpeechClient.EnableExternalScorer("deepspeech-0.8.2-models.scorer");

            var AudioFilePath = "accept.wav";

            Stopwatch watch = new Stopwatch();
            var waveBuffer = new NAudio.Wave.WaveBuffer(File.ReadAllBytes(AudioFilePath));
            using (var waveInfo = new NAudio.Wave.WaveFileReader(AudioFilePath))
            {
                watch.Start();

                string speechResult = "";

                if (blWithMeta == false)
                {
                    speechResult = deepSpeechClient.SpeechToText(
              waveBuffer.ShortBuffer,
              Convert.ToUInt32(waveBuffer.MaxSize / 2));

                    File.WriteAllText("without_meta.txt", speechResult);

                }
                StringBuilder srGg = new StringBuilder();

                if (blWithMeta == true)
                {
                  DeepSpeechClient.Models.Metadata vrMeta = deepSpeechClient.SpeechToTextWithMetadata(
              waveBuffer.ShortBuffer,
              Convert.ToUInt32(waveBuffer.MaxSize / 2), 1);
                 
                    foreach (var vrPerTranscript in vrMeta.Transcripts)
                    {
                        foreach (var vrPertoken in vrPerTranscript.Tokens)
                        {
                            srGg.AppendLine($"text: {vrPertoken.Text}\tstart time: {vrPertoken.StartTime}\ttime step: {vrPertoken.Timestep}");
                        }

                        srGg.AppendLine("\r\n\r\n==new transript==\r\n\r\n");

                    }

                    File.WriteAllText("with_meta.txt", srGg.ToString()); 

                }

                watch.Stop();
                var Transcription = $"Audio duration: {waveInfo.TotalTime.ToString()} {Environment.NewLine}" +
                        $"Inference took: {watch.Elapsed.ToString()} {Environment.NewLine}" +
                        $"Recognized text lenght: {speechResult.Length+ srGg.Length}";

                Dispatcher.BeginInvoke(new MethodInvoker(delegate ()
                {
                    lstBoxResults.Items.Add(Transcription);
                }));
            }
            waveBuffer.Clear();`

So this above procedures generate the below files

[with_meta.txt](https://github.com/mozilla/DeepSpeech/files/5339916/with_meta.txt)
[without_meta.txt](https://github.com/mozilla/DeepSpeech/files/5339917/without_meta.txt)

As can be seen, with meta, it just have timings but I have failed to find information about how to split them into the sentences rather than individual words.

So what would be the best approach to merge words into the sentences? 

some example lines of with meta

```
text: hey	start time: 1.22	time step: 61
text: guys	start time: 1.6	time step: 80
text: camilla	start time: 2	time step: 100
text: here	start time: 2.18	time step: 109
text: we	start time: 2.7	time step: 135
text: like	start time: 2.94	time step: 147
text: to	start time: 3.06	time step: 153
text: congratulate	start time: 3.72	time step: 186
text: you	start time: 3.88	time step: 194
text: once	start time: 4.16	time step: 208
text: again	start time: 4.46	time step: 223
text: because	start time: 4.86	time step: 243
text: your	start time: 5.2	time step: 260
text: film	start time: 5.48	time step: 274
text: was	start time: 5.64	time step: 282
text: selected	start time: 6.08	time step: 304
text: to	start time: 6.2	time step: 310
text: the	start time: 6.34	time step: 317
text: international	start time: 7.08	time step: 354
text: christian	start time: 7.58	time step: 379
text: film	start time: 7.84	time step: 392
```

here simple full output

`hey guys camilla here we like to congratulate you once again because your film was selected to the international christian film visible this year we know that some of you may not be able to attend and we completely understand that yes it's nice to be there and accept the award if you win and we do recommend it if you can but if you can't make it we completely understand because we will be broadcasting the award ceremony on several television stations this is very important please send us a video that is sixty seconds or less here some examples of some of the acceptance speech videos godefroi stralia i am so sorry couldn't be with you this weekend a thing working on the gold purse with some of the leading minds as far as christian media in australia is concerned and in having ought time to jump on a plan and get over to florida so please accept my apologies but also please except my absolute gratitude for recognizing every town down under in this way as director you only as good as your crew and i had the best crew for this project we didn't have enough money within heavy equipment that we wanted to fill the project of way that we wanted to but he god works through that and i what we did have with water perseverance and and i'm certainly a much better person and a much better producer and director as a result of this project if you're ever in a straight opium with love to say hello and break bread together and and once again thank you so much that everybody at the icy if if it's an absolute privilege for us to be recognized that this un an international stage thank you and godless i my name is walter e marshal i am the rider and director for cody high a life amatorie i would just like to think the international christian filettino of having our film there with so many other great films matteawan able to be there unfortunately because we're producing another documentary the sequel to codomanus honor and gratitude we thank you for this award thank you and enjoy the festival hello florida and readings from dugommier to give the remotest thank you very much for the work were very sorry that he could be there ready but the very honored to be part of the international christian unfestive as pinmakers we want to make a stand for christ in the world the message of the song and of the veil is to leave truelove as described in first corinthians startin and may we and you leave this love god love through their lives tankeru and coleuses send your video to inflate international catacomb thank you again and may god bless you`

**Comment by abhirooptalasila** [comment]
Hey @FurkanGozukara 
I wanted to do the same thing and ended up building my own subtitle app.
Check out [AutoSub](https://github.com/abhirooptalasila/AutoSub)!

**Comment by FurkanGozukara** [comment]
@abhirooptalasila ty for reply. how good it is? i tested mozilla DeepSpeech  and its correctness were terrible for my speech :(

**Comment by abhirooptalasila** [comment]
Depends on your audio file. If it's US English, it should have decent performance. I'm planning to use Wav2Vec2 later on for AutoSub. It has much better accuracy.
