### ISSUE TITLE
Can't download convert_graphdef_memmapped_format file

### ISSUE THREAD

**Issue by askinucuncu** [mozilla/DeepSpeech#3372]
I try to download it with the method below but it gives an error.

python util/taskcluster.py --arch "osx" --artifact convert_graphdef_memmapped_format --branch r1.15 --target .

https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.r1.15.osx/artifacts/public/convert_graphdef_memmapped_format

OS : Mac OS Big Sur

**Comment by lissyx** [comment]
That URL is wrong.

**Comment by lissyx** [comment]
https://deepspeech.readthedocs.io/en/v0.8.2/TRAINING.html#making-a-mmap-able-model-for-inference has the correct command line

**Comment by lissyx** [comment]
Also even with the correct URL, artifact expired and we cant republish it for macos.

**Comment by askinucuncu** [comment]
The command line here fails, does not work

https://deepspeech.readthedocs.io/en/v0.8.2/TRAINING.html#making-a-mmap-able-model-for-inference has the correct command line

**Comment by lissyx** [comment]
> The command line here fails, does not work
> 
> https://deepspeech.readthedocs.io/en/v0.8.2/TRAINING.html#making-a-mmap-able-model-for-inference has the correct command line

"does not work" is not useful feedback.

**Comment by askinucuncu** [comment]
The command line here fails, does not work

https://deepspeech.readthedocs.io/en/v0.8.2/TRAINING.html#making-a-mmap-able-model-for-inference has the correct command line

(venv) (base) BCODE-iMac:DeepSpeech bcode$ python3 util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --branch r1.15 --target .
Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.tensorflow.pip.r1.15.osx/artifacts/public/convert_graphdef_memmapped_format ...
Traceback (most recent call last):
  File "util/taskcluster.py", line 12, in <module>
    dsu_taskcluster.main()
  File "/Users/bcode/Desktop/p/DeepSpeech/DeepSpeech/training/deepspeech_training/util/taskcluster.py", line 128, in main
    maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact, args.branch))
  File "/Users/bcode/Desktop/p/DeepSpeech/DeepSpeech/training/deepspeech_training/util/taskcluster.py", line 58, in maybe_download_tc
    _, headers = urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by lissyx** [comment]
This is what i said earlier, this old artifact expired and we cant republish it.

**Comment by lissyx** [comment]
> python3 util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --branch r1.15 --target .

You also lack the `--arch osx`, but i my previous comment still holds
