### ISSUE TITLE
Using bazel-3.1.0 when building sources gives error

### ISSUE THREAD

**Issue by william-vw** [mozilla/DeepSpeech#3387]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.3 LTS
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: your builds
- **TensorFlow version (use command below)**: ('v1.12.0-0-ga6d8ffae09', '1.12.0')
- **Python version**: Python 3.6.9
- **Bazel version (if compiling from source)**: Bazel 3.1.0
- **GCC/Compiler version (if compiling from source)**: gcc 7.4.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so`

When using bazel-3.1.0 (as enforced in `tensorflow/.bazelversion`) to run 
```
bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
```
returns an error 
```
ERROR: Config value monolithic is not defined in any .rc file
```
(trying a different version with an unmodified `.bazelversion` file gives an error)

Running the command with bazel-3.7.0 (which required updating the `.bazelversion` file) works as expected. (Note that the [docs even recommend](https://deepspeech.readthedocs.io/en/v0.8.2/BUILDING.html) bazel-2.0.0 but this gives me a different error (`ERROR: Unrecognized option: --experimental_repo_remote_exec`)

(The only reason I'm building from source is because there doesn't seem to be a suitable pre-compiled native_client for my system, getting the error `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2`)

**Comment by lissyx** [comment]
> (The only reason I'm building from source is because there doesn't seem to be a suitable pre-compiled native_client for my system, getting the error `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2`)

This is not an error, this is a warning produced by tensorflow.


> `ERROR: Config value monolithic is not defined in any .rc file`

Are you running `bazel build` from the `tensorflow` subdirectory, as documented?



> (Note that the [docs even recommend](https://deepspeech.readthedocs.io/en/v0.8.2/BUILDING.html) bazel-2.0.0 but this gives me a different error (`ERROR: Unrecognized option: --experimental_repo_remote_exec`)

Those docs are for 0.8.2 that do not depend against the same TensorFlow version.

**Comment by william-vw** [comment]
> > (The only reason I'm building from source is because there doesn't seem to be a suitable pre-compiled native_client for my system, getting the error `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2`)
> 
> This is not an error, this is a warning produced by tensorflow.

Fair enough, but doesn't this imply that building from source would better in this case (i.e., improve performance)

> 
> > `ERROR: Config value monolithic is not defined in any .rc file`
> 
> Are you running `bazel build` from the `tensorflow` subdirectory, as documented?
> 

Yes

> > (Note that the [docs even recommend](https://deepspeech.readthedocs.io/en/v0.8.2/BUILDING.html) bazel-2.0.0 but this gives me a different error (`ERROR: Unrecognized option: --experimental_repo_remote_exec`)
> 
> Those docs are for 0.8.2 that do not depend against the same TensorFlow version.
> The `master` does properly document 3.1.0: https://deepspeech.readthedocs.io/en/master/BUILDING.html#building-deepspeech-binaries

This is the link I followed from [the GitHub repo](https://github.com/mozilla/DeepSpeech) ; also isn't 0.8.2 the [latest release](https://github.com/mozilla/DeepSpeech/releases/tag/v0.8.2)?

**Comment by lissyx** [comment]
> Fair enough, but doesn't this imply that building from source would better in this case (i.e., improve performance)

Maybe.



> This is the link I followed from [the GitHub repo](https://github.com/mozilla/DeepSpeech) ; also isn't 0.8.2 the [latest release](https://github.com/mozilla/DeepSpeech/releases/tag/v0.8.2)?

That's the stable release. You have not mentionned anything specific, so I cannot know in advance what version you want to build ...



> > > `ERROR: Config value monolithic is not defined in any .rc file`
> > 
> > 
> > Are you running `bazel build` from the `tensorflow` subdirectory, as documented?
> 
> Yes

Well, then I'm sorry but I have no idea what is wrong there. Bazel 3.1.0 works very well on CI for `master`.

**Comment by lissyx** [comment]
`--config=monolithic` is defined: https://github.com/mozilla/tensorflow/blob/23ad988fcde60fb01f9533e95004bbc4877a9143/.bazelrc#L132

**Comment by lissyx** [comment]
> This is the link I followed from [the GitHub repo](https://github.com/mozilla/DeepSpeech) ; also isn't 0.8.2 the [latest release](https://github.com/mozilla/DeepSpeech/releases/tag/v0.8.2)?

If you are working on 0.8.2, please stick to Bazel 2.0.0 as required. This is not a dependency we impose, this is TensorFlow, and it is quite picky on that point.

**Comment by lissyx** [comment]
> bazel-2.0.0 but this gives me a different error (`ERROR: Unrecognized option: --experimental_repo_remote_exec`)

Are you really sure this is running 2.0.0 ? It has this, according to their docs https://docs.bazel.build/versions/2.0.0/command-line-reference.html#flag--experimental_repo_remote_exec

**Comment by lissyx** [comment]
> When using bazel-3.1.0 (as enforced in `tensorflow/.bazelversion`) to run

This implies you are working on `master`



> This is the link I followed from [the GitHub repo](https://github.com/mozilla/DeepSpeech) ; also isn't 0.8.2 the [latest release](https://github.com/mozilla/DeepSpeech/releases/tag/v0.8.2)?

This suggests you want 0.8.2

**Comment by william-vw** [comment]
> > When using bazel-3.1.0 (as enforced in `tensorflow/.bazelversion`) to run
> 
> This implies you are working on `master`

I didn't claim otherwise

> 
> > This is the link I followed from [the GitHub repo](https://github.com/mozilla/DeepSpeech) ; also isn't 0.8.2 the [latest release](https://github.com/mozilla/DeepSpeech/releases/tag/v0.8.2)?
> 
> This suggests you want 0.8.2

It's not something I want but rather given by instructions linked from the master's README

**Comment by lissyx** [comment]
> I didn't claim otherwise

No, but you did not explicitely said, and you shared two informations that points to different versions, so it's unclear: do you work on `master` or `v0.8.2` ?

> `ERROR: Config value monolithic is not defined in any .rc file`

Sorry to insist, but this is really a symptom of running `bazel build` from the wrong directory.

**Comment by lissyx** [comment]
@william-vw It might help if you shared a bit more than just the error, like the full stdout/stderr from the `bazel build` step.

**Comment by william-vw** [comment]
After re-activating the virtual environment, and trying again with bazel-3.1.0 (for some reason, need to use `bazel-3.1.0` instead of `bazel`), it builds without a problem. Sorry about the time wasting, and thanks for your help

But, I do think it could help if the docs refer to the master version of the instructions (e.g., the docs they recommend checking out the master when building from source, but then refer to bazel version 2.0.0)

**Comment by lissyx** [comment]
> But, I do think it could help if the docs refer to the master version of the instructions (e.g., the docs they recommend checking out the master when building from source, but then refer to bazel version 2.0.0)

This is what we did in the past, and we had to handle a lot of noise in the other way, people being pointed to master when they were expecting stable,following master instructions and complaining of other things.

So we gave up and did that to stop wasting our time. Truth is, it more or less worked much better. 

> After re-activating the virtual environment, and trying again with bazel-3.1.0 (for some reason, need to use `bazel-3.1.0` instead of `bazel`), it builds without a problem. Sorry about the time wasting, and thanks for your help

**Comment by william-vw** [comment]
Fair enough :-)
