### ISSUE TITLE
problem when training own model

### ISSUE THREAD

**Issue by Asma-droid** [mozilla/DeepSpeech#3394]
Hi all

I would like to train my own model based on open source data more exactely "https://commonvoice.mozilla.org/data". I have faced the problem
FileNotFoundError: [Errno 2] No such file or directory: 'fr/clips/train-all.csv'

any solution please ?

**Comment by ftyers** [comment]
Dear @Asma-droid thanks for getting in contact with us. As this doesn't seem like a bug in DeepSpeech, we would like to ask you if you could take your request to [Mozilla's Discourse](https://discourse.mozilla.org/c/mozilla-voice-stt/). Thanks!

**Comment by olafthiele** [comment]
Thanks @ftyers for the hint on French, Asma didn't pick that up and asked the exact same question without more information ... so I hinted again :-)
