### ISSUE TITLE
Stop queue threads on changing data sets

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#340]
In attempt to stop server crashes:

- Stop any training threads that feed the training queue before starting validation
- Stop any validation threads that feed the validation queue before starting training
- Stop any validation/training threads that feed the validation/training queue before starting testing

In addition stop any internal queue threads in similar situations

**Comment by kdavis-mozilla** [comment]
@reuben I think, but I'm not sure, the refactor re-opened this, can you look at it.

**Comment by kdavis-mozilla** [comment]
@reuben Also I'd say this has the highest priority as until it's fixed we can't do anything

**Comment by reuben** [comment]
I don't see how it could have reopened this, the code from commit 0f8242ad3949be8cffd7ba145864e5852f37be2e is still there. Is the server crashing again?

**Comment by kdavis-mozilla** [comment]
@reuben Yes the server is crashing again. In particular it crashes when the transition from training to validation occurs, just where it was crashing before [0f8242a](https://github.com/mozilla/DeepSpeech/commit/0f8242ad3949be8cffd7ba145864e5852f37be2e) landed. A bit more info:

I ran the 25% dropout run last week with no problem. The 25% dropout run didn't have the refactor.

I changed the dropout from 25% to 27.5% and then started a new run using the refactor. So the only difference now being the refactor was there and the dropout was 27.5% instead of 25%. This 27.5% run never got past validation in two tries. It crashed both times. The first time the GPU fell off the PCIe bus. The second time the entire server crashed completely and rebooted.

**Comment by kdavis-mozilla** [comment]
@reuben you and @lissyx should coordinate on using the server.

Nothing is currently running on the server as a result of this issue and @lissyx also has issue #374 which requires working on the server too.

**Comment by kdavis-mozilla** [comment]
@reuben While the code for [0f8242a](https://github.com/mozilla/DeepSpeech/commit/0f8242ad3949be8cffd7ba145864e5852f37be2e) is still there. I'm guessing some timing changed. which re-introduced the bug.

In other words, the pre-refactor code implicitly relied on some thread timing. (I am not sure how this could be the case as I tried to remove all implicit thread timing issues. But it seems as if this is the case.)

The post-refactor code changed this timing subtly. Thus the post-refactor code exposed this implicitly timing dependency and re-introduced the crash.

I'd be happy to be proved wrong on all this as the non-deterministic nature of the scenario above is painful to debug.

**Comment by reuben** [comment]
Merged 8f341cf in #383. I'm now going to merge that into the automation branch and we can see how that goes.

**Comment by kdavis-mozilla** [comment]
I'm going to assume this is OK for now as with TF 1.0.0 it's at least far less prevalent.
