### ISSUE TITLE
Read the docs page not available for 0.9.0

### ISSUE THREAD

**Issue by davesdere** [mozilla/DeepSpeech#3403]
First of all, thank you for your great work. Just installed the Python bindings hoping to play around as a user and I got a `404` when getting on the docs page.

`https://deepspeech.readthedocs.io/en/v0.9.0/`
Thankfully, `v.0.8.0` is available for me to poke play around. ;)

Just wanted to put it out there, since you mentioned the docs in the release notes.

Have a great day/night!

**Comment by lissyx** [comment]
There was an issue on  readthedocs.io, breaking 0.9.0. It's fixed and /latest redirect to r0.9. We will have to issue a 0.9.1 there is no other way.
