### ISSUE TITLE
Deepspeech 3.9 Python support

### ISSUE THREAD

**Issue by dag7dev** [mozilla/DeepSpeech#3405]

**Comment by lissyx** [comment]
Adding a new Python version should, hopefully, /just/ be:
 - `git grep "3\.8" taskcluster/`: see where Python 3.8 is referenced,
 - update `SUPPORTED_PYTHON_VERSIONS` to add new python version,
 - update `maybe_numpy_min_version()` to set min deps for numpy wheels for new python version,
 - update `install_pyenv()` to use newer `pyenv` that knows about the new python version
 - update `pyenv` URLs in `taskcluster/.shared.yml` (increment digit) to re-generate cache
 - add new `.yml` test files for new python version

**Comment by CatalinVoss** [comment]
This is for the inference part only? Tensorflow 1.x isn't available for python 3.8

**Comment by lissyx** [comment]
> This is for the inference part only? Tensorflow 1.x isn't available for python 3.8 or 3.9

Yes, that's right.

**Comment by lissyx** [comment]
Thanks @dag7dev for pushing the work, I have merged that to `master` and `r0.9`: when we do a 0.9.2 release, it will publish Python 3.9 packages. Let's see the feedback we get on 0.9.1 and if there are any bugfixes required or not.
