### ISSUE TITLE
Audio examples not found in release v0.9.0

### ISSUE THREAD

**Issue by lxender** [mozilla/DeepSpeech#3407]
The audio examples mentioned in [release v0.9.0](https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.0) are not part of the released package. [Direct link](https://github.com/mozilla/DeepSpeech/releases/download/v0.9.0/audio-0.9.0.tar.gz) to what should be the download for "audio-0.9.0.tar.gz"

**Comment by reuben** [comment]
Thanks, updated the release.
