### ISSUE TITLE
Cant Install Deepspeech    ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none)              

### ISSUE THREAD

**Issue by parinay602** [mozilla/DeepSpeech#3412]
ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none)                         ERROR: No matching distribution found for deepspeech   
![image](https://user-images.githubusercontent.com/68812492/98408396-1a666200-2097-11eb-8362-cb4f8a8f9363.png)

**Comment by parinay602** [comment]
Now it shows this
![image](https://user-images.githubusercontent.com/68812492/98411065-661b0a80-209b-11eb-9a0c-49a19f56f594.png)

**Comment by lissyx** [comment]
> Now it shows this
> ![image](https://user-images.githubusercontent.com/68812492/98411065-661b0a80-209b-11eb-9a0c-49a19f56f594.png)

**Comment by lissyx** [comment]
Please use discourse for support. Avoid screenshots, read the docs. Share context on what you are doing.
