### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by brcisna** [mozilla/DeepSpeech#3417]
Debian Bullseye amd64

installed deepspeech according to instructions here: (top portion)
https://deepspeech.readthedocs.io/en/v0.9.1/

after this is done if simply run deepspeech with no other code i get "Illegal instruction"

Ideas?
Thanks

**Comment by lissyx** [comment]
As documented, please reach for support on Discourse and please provide precise details on your setup. Very likely your CPU does not support AVX.
