### ISSUE TITLE
pb model size

### ISSUE THREAD

**Issue by Modanisa-deep** [mozilla/DeepSpeech#3418]
hi
i used deepspeech
i have my own data
every thing is ok
i get mt result
"also and i get my " output_graph.pb
i want to know my model pb size
how much equal
??

**Comment by lissyx** [comment]
@Modanisa-deep So, after spamming existing Discourse thread, not articulating correctly a question on discourse, spamming by force-notifying people, you decided to spam our github issues ?

This is my last warning. Next time, you will be banned and it will be escalated on both GitHub and Discourse.

**Comment by Modanisa-deep** [comment]
iam very sorry i don't know this
I did not mean to make a noise 
I just want to get a help
but someone guide me me to put here on the github
 I am sorry
