### ISSUE TITLE
Feature Request: Supporting in-browser speech to text

### ISSUE THREAD

**Issue by akshat-khare** [mozilla/DeepSpeech#3419]
Hello everyone. I found DeepSpeech very interesting and wanted to use it. I want to convert speech to text in the browser itself with audio never leaving the frontend. We have [Meyda](https://meyda.js.org/) for extracting audio features that DeepSpeech model needs. Now I need a in-browser library like Meyda which does speech to text. I guess DeepSpeech would be perfect for the task. Tensorflow-js can be used here but I see that models for tensorflow-js has not been made yet and some people are facing troubles converting existing models to tensorflowjs compatible format #2233 . 
I am new to typescript and don't know if the [native support for typescript](https://github.com/mozilla/DeepSpeech/tree/master/native_client/javascript) can replace tensorflow-js or not. 
If the machinery for doing predictions in the browser itself is supported by using typescript please indicate me and I will try to experiment with it and make it work. Else can we provide tensorflow-js support and make the library more user-friendly.
Thanks for making such a nice library.

**Comment by lissyx** [comment]
> Tensorflow-js can be used here but I see that models for tensorflow-js has not been made yet and some people are facing troubles converting existing models to tensorflowjs compatible format #2233 .

You already have it there, read and act on that.
