### ISSUE TITLE
Deepspeech not recognizing Indian Accent

### ISSUE THREAD

**Issue by EsakkiSundar** [mozilla/DeepSpeech#3422]
Hi,
    I have an Indian accent and trying DeepSpeech pre-trained English model, V0.91. When I give my voice as in the attached file, to DeepSpeech, Im getting the output as "hoooooo".  Kindly suggest how to recognize my voice. Also attaching the snippet of code. Thanks for your help and suggestion. 
 
[testingdeepspeech.zip](https://github.com/mozilla/DeepSpeech/files/5545458/testingdeepspeech.zip)

`import deepspeech
import wave
import numpy as np

model_file_path = r"C:\deepspeech\0.91\deepspeech-0.9.1-models.pbmm"
model = deepspeech.Model(model_file_path)
scorer_file_path = r"C:\deepspeech\0.91\deepspeech-0.9.1-models.scorer"
model.enableExternalScorer(scorer_file_path)

recordingfile = r"C:\testingdeepspeech.wav"
w = wave.open(recordingfile, 'r')
rate = w.getframerate()
frames = w.getnframes()
buffer = w.readframes(frames)
print(rate)
print(model.sampleRate())
type(buffer)
data16 = np.frombuffer(buffer, dtype=np.int16)
type(data16)
text = model.stt(data16)
print(text)`

**Comment by olafthiele** [comment]
Please follow the advice in the first line of opening a new issue, post questions like that on [Discourse](https://discourse.mozilla.org/c/mozilla-voice-stt/247).

**Comment by shravanshetty1** [comment]
You need to train it for indian accent....

**Comment by lissyx** [comment]
Model is trained on american english as documented, other accents might give less good results. Please read and act on issue template and reach for support on Discourse, this is not a bug.

**Comment by shravanshetty1** [comment]
I could get subtitles for an audio file with speaker with indian accent https://www.youtube.com/watch?v=BZ7v0wVrKDo - 
[english (copy).txt](https://github.com/mozilla/DeepSpeech/files/5545623/english.copy.txt)

It will work - better if you fine tune it...

**Comment by EsakkiSundar** [comment]
> You need to train it for indian accent....

I assume the out of the box model is trained with the below distributions based on the data published at https://commonvoice.mozilla.org/en/datasets . A total of 61,528 people have voiced.  5% of the population is with Indian accent (which is roughly 3076 people). 

When you say the model has to be trained, roughly how many people voice are you expecting more to be given to the model ?

**Accent**
23% - United States English
8% - England English
5% - India and South Asia (India, Pakistan, Sri Lanka)
4% - Australian English
3% - Canadian English
2% - Scottish English
1% - Irish English
1% - Southern African (South Africa, Zimbabwe, Namibia)
1% - New Zealand English

**Comment by olafthiele** [comment]
Please continue on Discourse, this is not the place to discuss the training on accents.

**Comment by lissyx** [comment]
> Please continue on Discourse, this is not the place to discuss the training on accents.

Moreover, read the release notes they documents the training corpus.
