### ISSUE TITLE
make a packed binary for transcribe.py

### ISSUE THREAD

**Issue by NoamDev** [mozilla/DeepSpeech#3423]
Some people would like to transcribe a long sound file and use the batching capabilities of transcribe.py.
However, those people don't have the tools to install deepspeech from source.

**Comment by olafthiele** [comment]
Sounds like a good idea. Unfortunately, the team probably doesn't have the resources to make the necessary changes. If you got the time, we would be very grateful for a PR.

**Comment by lissyx** [comment]
> What do you think @lissyx?

The issue is very vague, I don't understand what is the need here ...

**Comment by olafthiele** [comment]
@NoamDev if I understand you correctly, you think of extending the native client to not just taking a single wav file as an argument but a whole directory of files that is transcribed one after the other?

If you have the time, we are happy for a PR. In the meantime, why not write a script that uses the native client to do that and post it on [Discourse ](https://discourse.mozilla.org/c/mozilla-voice-stt/247)for others to find?

**Comment by lissyx** [comment]
> Some people would like to transcribe a long sound file and use the batching capabilities of transcribe.py.
> However, those people don't have the tools to install deepspeech from source.

@NoamDev `transcribe.py` directly depends on TensorFlow. Please elaborate on "those people don't have the tools to install deepspeech from source", because if those people can't install TensorFlow, there's not much we can do.

**Comment by NoamDev** [comment]
No, installing tensorflow isn't that much of a hassle.
However, transcribe.py require you to build deepspeech from source, as it depends on parts of the library that cannot be found in the pypl's deepspeech-gpu.

**Comment by lissyx** [comment]
> No, installing tensorflow isn't that much of a hassle.
> However, transcribe.py require you to build deepspeech from source, as it depends on parts of the library that cannot be found in the pypl's deepspeech-gpu.

@NoamDev I'm not sure what you are referring to, there is no `from deepspeech import xxx` in `transcribe.py`. Please be more explicit.

**Comment by NoamDev** [comment]
transcribe.py mainly uses stuff from deepspeech_training and ds_ctcdecoder.
The only way to use this libraries is two install deepspeech **from source** as described [here](https://deepspeech.readthedocs.io/en/v0.9.1/TRAINING.html).
This installation process is not easy.

**Comment by lissyx** [comment]
>  This installation process is not easy.

That's your opinion. Please explain where is the complexity, otherwise your issue is unactionable.

> transcribe.py mainly uses stuff from deepspeech_training and ds_ctcdecoder.

`deepspeech_training` is installing deepspeech deps and that's it. It just requires `pip install --upgrade .`, including `ds_ctcdecoder` which is also published on pypi: https://pypi.org/simple/ds-ctcdecoder/

So for now, this request is still unclear.

**Comment by lissyx** [comment]
```
$ docker run --rm -it "ubuntu:18.04"
root@docker # apt update && apt install git python3-pip
root@docker # cd /opt && git clone https://github.com/mozilla/DeepSpeech/ && cd DeepSpeech && git checkout v0.9.1
root@docker # pip3 install --upgrade pip==20.2.2 wheel==0.34.2 setuptools==49.6.0
root@docker # pip3 install --upgrade -e .
root@docker # python3 transcribe.py
```

**Comment by lissyx** [comment]
@NoamDev that's basically it. so, again, please elaborate on where is the complexity: if you can't, I'm afraid we won't be able to help because we just don't know what to fix ...

**Comment by NoamDev** [comment]
The complexity arises because `pip install .` compiles the c/cpp (I don't
remember) code.
While this is mostly easy in ubuntu, it isn't on windows.
Usually windows users who install python packages that contain native code
depend on python wheels.
This could be a solution.
Alternatively, a pyinstaller bundle of transcribe.py with all its
dependencies could also work.
Sorry for being that unclear 🙈 before..

>

**Comment by lissyx** [comment]
> The complexity arises because `pip install .` compiles the c/cpp (I don't remember) code. While this is mostly easy in ubuntu, it isn't on windows. Usually windows users who install python packages that contain native code depend on python wheels. This could be a solution. Alternatively, a pyinstaller bundle of transcribe.py with all its dependencies could also work. Sorry for being that unclear see_no_evil before..
> […](#)

We don't support training on Windows, so that's not unsurprising. If you care about, please send PR and step up to maintain.

Our packages, including `ds-ctcdecoder` DOES have Python wheels on Windows. TensorFlow as well. If it's some other third-party dep that requires compilation step, I'm sorry, but it is out of our hands.

**Comment by NoamDev** [comment]
I don't think it's required to support training on windows. But
transcribe.py is obviously not related to training. It just happens to use
functions from deepspeech_training. (Mostly from the util submodule).
Maybe what's needed is to add those functions to pypl's deepspeech, or
extract them to a new separate module.
Maybe stuff like deepspeech_training.train.create_model already has
equivalents in the deepspeech?

**Comment by reuben** [comment]
You're missing the delayed imports. `transcribe.py` leverages the training code heavily.

**Comment by lissyx** [comment]
> I don't think it's required to support training on windows. But transcribe.py is obviously not related to training. It just happens to use functions from deepspeech_training. (Mostly from the util submodule).

No, but basically, supporting `transcribe.py` under Windows is more or less the same work as supporting training.



> Maybe what's needed is to add those functions to pypl's deepspeech, or extract them to a new separate module. Maybe stuff like deepspeech_training.train.create_model already has equivalents in the deepspeech?

No, seriously. The whole purpose of `transcribe.py` is for when you need to do lot of batching, GPU supported.

Please, I've given several hints earlier, but if you keep us in the vague "some code requires compilation", we definitively can't help you.

**Comment by NoamDev** [comment]
Hmm okay then, I thought this was an easy problem, closing.

**Comment by lissyx** [comment]
> Hmm okay then, I thought this was an easy problem, closing.

We still don't know what dependency(ies) is(are) problematic.
At some point, if you need it, you should do it.
