### ISSUE TITLE
What is the class Stream used for？

### ISSUE THREAD

**Issue by shizhuoyang** [mozilla/DeepSpeech#3439]
What is the class Stream used for?  Is it the intermediate output of the acoustic model? Where does it work in the overall process？

![微信图片_20201125185715](https://user-images.githubusercontent.com/52410445/100218698-0acc9180-2f50-11eb-81ff-cc40c6f079d0.png)

**Comment by olafthiele** [comment]
[Check the docs and source code a bit more](https://deepspeech.readthedocs.io/en/v0.9.1/NodeJS-Examples.html) and you'll find some examples. As this is usage related, ask further questions on Discourse as described in the first line of opening an issue.
