### ISSUE TITLE
How can I use Intel-Tensorflow with deepspeech?

### ISSUE THREAD

**Issue by jczaja** [mozilla/DeepSpeech#3448]
Hi,

I'm running DeepSpeech (inference) on CPU and execution is rather slow. So I would like to test intel-tensorflow (https://pypi.org/project/intel-tensorflow/) which has some optimizations to better utilise CPU. How can I do that?

Thanks for developing such a wonderful project:)

**Comment by olafthiele** [comment]
As you read in the first line of opening an issue, this is support and should live at [Discourse](https://discourse.mozilla.org/c/mozilla-voice-stt/247). Please close the issue here. Short answer: You can't and even if you could it would be way too slow. Use colab for smaller projects.

**Comment by jczaja** [comment]
@olafthiele Maybe you can advice me where should I start looking in code of DeepSpeech to do modification so I can use intel-tensorflow ?

**Comment by olafthiele** [comment]
Please start reading what we write, continue on Discourse ...

**Comment by lissyx** [comment]
> @olafthiele Maybe you can advice me where should I start looking in code of DeepSpeech to do modification so I can use intel-tensorflow ?

Maybe you can start by explaining what kind of inference usage you have, `libdeepspeech.so` ?
Maybe you can start by documenting "rather slow"? How much? What CPU? What use-case? What are your expectations?

And do all of that on Discourse, as requested ?

**Comment by jczaja** [comment]
Ok, thanks. I  will use Discourse for further disscussion.
