### ISSUE TITLE
ARGS = parser.parse_args()

### ISSUE THREAD

**Issue by iProMC** [mozilla/DeepSpeech#3449]
Hello I have a problem I use the deep speech 0.8.2 with his exact example (https://github.com/mozilla/DeepSpeech-examples/blob/r0.6/mic_vad_streaming/mic_vad_streaming.py) and I installed the scorer and pbmm when i start the project i got from this code: ARGS = parser.parse_args() is output is (2)

and from the console : 
usage: deep.py [-h] [-v VAD_AGGRESSIVENESS] [--nospinner] [-w SAVEWAV]
                   [-f FILE] -m MODEL [-s SCORER] [-d DEVICE] [-r RATE] [-k]
deep.py: error: the following arguments are required: -m/--model

CAN ANYONE HELP ME PLZ >>>>>>>>

**Comment by ftyers** [comment]
Dear @iProMC thanks for getting in contact with us. As this doesn't seem like a bug in DeepSpeech, we would like to ask you if you could take your request to [Mozilla's Discourse](https://discourse.mozilla.org/c/mozilla-voice-stt/). Thanks!
