### ISSUE TITLE
the following arguments are required: -m/--model

### ISSUE THREAD

**Issue by iProMC** [mozilla/DeepSpeech#3453]
Hello,

I have a problem with deep speech I used the last version 0.9.2 and I am using the mic_vad_streaming example but it seems it not work. Link: https://github.com/mozilla/DeepSpeech-examples/tree/r0.8/mic_vad_streaming

I installed all the requirement and the phmm and scorer

when I run the app I got this problem:

usage: model.py [-h] [-v VAD_AGGRESSIVENESS] [--nospinner] [-w SAVEWAV] [-f FILE] -m MODEL [-s SCORER] [-d DEVICE] [-r RATE] [-k]
model.py: error: the following arguments are required: -m/--model

**Comment by ftyers** [comment]
Dear @iProMC thanks for getting in contact with us. As this doesn't seem like a bug in DeepSpeech, we would like to ask you if you could take your request to [Mozilla's Discourse](https://discourse.mozilla.org/c/mozilla-voice-stt/). Thanks!
