### ISSUE TITLE
API doc broken on r0.9

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3462]
https://community-tc.services.mozilla.com/tasks/Eh2O5dknTqiAP9QmpzppVQ
> No JSDoc documentation was found for object "Stream" or any path ending with that.

**Comment by lissyx** [comment]
I guess we need https://github.com/mozilla/DeepSpeech/pull/3460 on r0.9 @reuben ?

**Comment by reuben** [comment]
None of the causing PRs landed on r0.9 so I don't think it's that.

**Comment by reuben** [comment]
> https://community-tc.services.mozilla.com/tasks/Eh2O5dknTqiAP9QmpzppVQ
> 
> > No JSDoc documentation was found for object "Stream" or any path ending with that.

This task points to 72004d8f719af7b0b0095e8ac3e26c460659fd02 which is not on r0.9.

**Comment by lissyx** [comment]
> > https://community-tc.services.mozilla.com/tasks/Eh2O5dknTqiAP9QmpzppVQ
> > > No JSDoc documentation was found for object "Stream" or any path ending with that.
> 
> This task points to [72004d8](https://github.com/mozilla/DeepSpeech/commit/72004d8f719af7b0b0095e8ac3e26c460659fd02) which is not on r0.9.

Doh, you're right, I mixed up things.
