### ISSUE TITLE
DeepSpeech.py runs out of memory (OOM) and fails to fork new processes

### ISSUE THREAD

**Issue by i-sf** [mozilla/DeepSpeech#3464]
**System information**

I am using the Dockerfile, with no modifications to the script files.

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): x86_64 Linux 4.19.0-13-amd64, Debian 10 buster
- TensorFlow version (use command below): v1.15.3-68-gdf8c55c, 1.15.4
- Python version: 3.6.9 final 0
- Bazel version (if compiling from source): ?
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: NVIDIA driver v450.80.02, libcudart.so.10.0.130
- GPU model and memory: Tesla T4 ([Amazon G4 instance](https://aws.amazon.com/es/ec2/instance-types/g4/))

**Describe the current behavior**

The machine runs out with 16GB of memory and no swap partition.

<details><summary>Full traceback</summary>

```
Epoch 17 | Validation | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000 | Dataset: /mnt/corpus/clips/dev.csv                                                         T
raceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[{{node tower_0/IteratorGetNext}}]]
  (1) Out of range: End of sequence
         [[{{node tower_0/IteratorGetNext}}]]
         [[tower_0/IteratorGetNext/_185]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DeepSpeech/training/deepspeech_training/train.py", line 572, in run_set
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[node tower_0/IteratorGetNext (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Out of range: End of sequence                                                                                                                                              [[node tower_0/IteratorGetNext (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[tower_0/IteratorGetNext/_185]]
0 successful operations.
0 derived errors ignored.

tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[node tower_0/IteratorGetNext (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Out of range: End of sequence
         [[node tower_0/IteratorGetNext (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[tower_0/IteratorGetNext/_185]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'tower_0/IteratorGetNext':
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/DeepSpeech/training/deepspeech_training/train.py", line 982, in run_script
    absl.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/DeepSpeech/training/deepspeech_training/train.py", line 954, in main
    train()
  File "/DeepSpeech/training/deepspeech_training/train.py", line 484, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "/DeepSpeech/training/deepspeech_training/train.py", line 317, in get_tower_results
    avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
  File "/DeepSpeech/training/deepspeech_training/train.py", line 236, in calculate_mean_edit_distance_and_loss
    batch_filenames, (batch_x, batch_seq_len), batch_y = iterator.get_next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/DeepSpeech/training/deepspeech_training/train.py", line 982, in run_script
    absl.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/DeepSpeech/training/deepspeech_training/train.py", line 954, in main
    train()
  File "/DeepSpeech/training/deepspeech_training/train.py", line 617, in train
    set_loss, steps = run_set('dev', epoch, init_op, dataset=source)
  File "/DeepSpeech/training/deepspeech_training/train.py", line 575, in run_set
    exception_box.raise_if_set()
  File "/DeepSpeech/training/deepspeech_training/util/helpers.py", line 149, in raise_if_set
    raise exception  # pylint: disable = raising-bad-type
  File "/DeepSpeech/training/deepspeech_training/util/helpers.py", line 157, in do_iterate
    yield from iterable()
  File "/DeepSpeech/training/deepspeech_training/util/feeding.py", line 114, in generate_values
    for sample_index, sample in enumerate(samples):
  File "/DeepSpeech/training/deepspeech_training/util/augmentations.py", line 226, in apply_sample_augmentations
    initargs=(context,)) as pool:
  File "/DeepSpeech/training/deepspeech_training/util/helpers.py", line 115, in __init__
    self.pool = Pool(processes=processes, initializer=initializer, initargs=initargs)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

</details>

**Describe the expected behavior**

I expect to **not** see this happen:

```
$ ps aux | grep "python3 DeepSpeech" | wc
    134    5067   70446
```

Over 5000 instances of the process running makes no sense. I do not understand why there are so many of them, but it's not a surprise forking fails...

**Standalone code to reproduce the issue**

I am training with the CommonVoice Spanish corpus v5.1, with the following command:

```
CORPUS=/path/to/clips
BASE=/path/to/mountpoint
cd /DeepSpeech
python3 DeepSpeech.py \
        --train_files $CORPUS/train.csv \
        --train_batch_size 1 \
        --limit_train 1000 \
        \
        --dev_files $CORPUS/dev.csv \
        --dev_batch_size 1 \
        --limit_dev 150 \
        \
        --test_files $CORPUS/test.csv \
        --test_batch_size 1 \
        --limit_test 150 \
        \
        --automatic_mixed_precision \
        --train_cudnn \
        \
        --checkpoint_dir $BASE/checkpoints \
        --export_dir $BASE/exported \
        \
        --alphabet_config_path $BASE/alphabet.es.txt
```

I first tried with a batch size of 10, then 5, then 2 (which crashed with some other strange error), then 1, but all of them end up breaking because it's unable to fork anymore.

The `alphabet.es.txt` simply adds vowels with accents and ñ to the [`data/alphabet.txt`](https://github.com/mozilla/DeepSpeech/blob/master/data/alphabet.txt) from this repository:

```diff
diff --git a/alphabet.txt b/alphabet.es.txt
index 46aa35e..4c0f26f 100644
--- a/alphabet.txt
+++ b/alphabet.es.txt
@@ -30,4 +30,10 @@ x
 y
 z
 '
+á
+é
+í
+ó
+ú
+ñ
```

I have searched for other issues regarding "memory", "RAM", or "OOM" before posting this, but I found none with precisely the issue being unable to fork a new process.

Please let me know if I should provide any more information, or should I perform any additional tests that may be valuable.

**Comment by lissyx** [comment]
> GPU model and memory: Tesla T4 ([Amazon G4 instance](https://aws.amazon.com/es/ec2/instance-types/g4/))

Please provide accurate specs, I don't have time to dig into the mess of Amazon EC2



> The machine runs out with 16GB of memory and no swap partition.

NO swap is bad practice, 16GB might be not enough given your dataset


Also please try, reuse and contribute to https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/ which is already used by other languages communities to manage their training: reusing this makes sure you don't do silly mistakes.

**Comment by reuben** [comment]
> I expect to **not** see this happen:
> 
> ```
> $ ps aux | grep "python3 DeepSpeech" | wc
>     134    5067   70446
> ```
> 
> Over 5000 instances of the process running makes no sense. I do not understand why there are so many of them, but it's not a surprise forking fails...

`wc` outputs `lines words bytes`, so that's actually 134 processes, not 5067.

What's the output of `python -c 'import os; print(os.cpu_count())'`?

**Comment by i-sf** [comment]
> Please provide accurate specs

For the graphics card, [NVIDIA T4 website](https://www.nvidia.com/en-us/data-center/tesla-t4/) claims the following:

- Turing Tensor Cores: 320
- NVIDIA CUDA® cores: 2,560
- Single Precision Performance (FP32): 8.1 TFLOPS
- Mixed Precision (FP16/FP32): 65 FP16 TFLOPS
- INT8 Precision: 130 INT8 TOPS
- INT4 Precision: 260 INT4 TOPS
- Interconnect: Gen3 x16 PCIe
- Memory Capacity: 16 GB GDDR6
- Bandwidth: 320+ GB/s
- Power: 70 watts

As reported by `screenfetch`:
- CPU: Intel Xeon Platinum 8259CL @ 4x 3.222GHz
- RAM: 15746MiB

Disk space should not be an issue, but the data is in a 256GB volume.

> NO swap is bad practice, 16GB might be not enough given your dataset

The clips have a sample rate of 16KHZ, converted from CommonVoice's `.mp3` files via the `sox` command (used `bin/import_cv2.py`, basically). Most clips are in the range of 100KB to 200KB, and in theory, `--limit_train 1000` is capping that to 1000 clips only. Way below the 16GB of RAM.

Skimming through previous issues seemed to indicate swap was fine, and if it's indeed unused memory, I can't see how swap would be harmful.

> reusing this makes sure you don't do silly mistakes

I have made sure to carefully follow [Training Your Own Model](https://deepspeech.readthedocs.io/en/v0.9.2/TRAINING.html) from the documentation, and given I'm using the docker image, I'd hope everything is configured correctly already. The only thing that is different here is the way I run `DeepSpeech.py` and the parameters I use.

> `wc` outputs `lines words bytes`, so that's actually 134 processes

Apologies, you're right, I misread that output. In any case, if I leave it running for longer, I'm reached 345 processes (16GB RAM, 16GB swap) before it ran out again. Thank you both for the prompt response.

**Comment by lissyx** [comment]
> The clips have a sample rate of 16KHZ, converted from CommonVoice's `.mp3` files via the `sox` command (used `bin/import_cv2.py`, basically). Most clips are in the range of 100KB to 200KB, and in theory, `--limit_train 1000` is capping that to 1000 clips only. Way below the 16GB of RAM. The total set consists of 381K files, roughly 57GB, but as I understand it, I'm using only 1000 with the limit.

Maybe there is a bug in limitation

Memory usage without running ? Memory usage evolution over time?
Kernel logs showing OOM ?
`ulimit` ?

**Comment by i-sf** [comment]
> Maybe there is a bug in limitation

If you think it's worth investigating, I could run the same command but on a trimmed-down version `head -n1001` of the `train.csv` set. However, I don't think this is the issue. With a limit of 1000 for the training set as above but a batch size of 10 to run out of memory faster, training only takes 100 steps, which checks out with the limit. Each epoch takes roughly 20 seconds:

```
--------------------------------------------------------------------------------
Epoch 4 |   Training | Elapsed Time: 0:00:18 | Steps: 100 | Loss: 73.963538
Epoch 4 | Validation | Elapsed Time: 0:00:01 | Steps: 15 | Loss: 90.087933 | Dataset: /mnt/corpus/clips/dev.csv
--------------------------------------------------------------------------------
Epoch 5 |   Training | Elapsed Time: 0:00:18 | Steps: 100 | Loss: 73.619752
Epoch 5 | Validation | Elapsed Time: 0:00:01 | Steps: 15 | Loss: 85.446852 | Dataset: /mnt/corpus/clips/dev.csv
I Saved new best validating model with loss 85.446852 to: /mnt/corpus/tiny-ds-train/checkpoints/best_dev-593
--------------------------------------------------------------------------------
```


> Memory usage without running

226MB. tmux, Docker and this program is pretty much all that running.

> Memory usage evolution over time?

I am not sure what the right way to check this is, so I've ran the following command instead (using the same command as above but batch size 10 to trigger the issue faster):

<details><summary>while true; do date | tee -a memgrow.txt; free | tee -a memgrow.txt; sleep 60; done</summary>

```
Fri 11 Dec 2020 12:57:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420      274508    15012452       12136      837460    15502952
Swap:      16776188      116856    16659332
Fri 11 Dec 2020 12:58:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420      548084    14491164       22384     1085172    15219260
Swap:      16776188      116856    16659332
Fri 11 Dec 2020 12:59:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420     2406724    12110048       28536     1607648    13354836
Swap:      16776188      116856    16659332
Fri 11 Dec 2020 01:00:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420     4499868     6649652     1109968     4974900    10180312
Swap:      16776188      116856    16659332
Fri 11 Dec 2020 01:01:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420     6825728     2207724     1110064     7090968     7854376
Swap:      16776188      116856    16659332
Fri 11 Dec 2020 01:02:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420     8538276      680608     1110148     6905536     6141500
Swap:      16776188      115832    16660356

---reaches epoch 9 and 10 in between here---

Fri 11 Dec 2020 01:03:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420     9948224      154812     1110228     6021384     4731280
Swap:      16776188      115832    16660356
Fri 11 Dec 2020 01:04:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420    11480604      169436     1110328     4474380     3199056
Swap:      16776188      115832    16660356
Fri 11 Dec 2020 01:05:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420    13135940      169088     1110424     2819392     1562976
Swap:      16776188      115832    16660356
Fri 11 Dec 2020 01:06:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420    14224344      169036     1109884     1731040      492428
Swap:      16776188      115832    16660356
Fri 11 Dec 2020 01:07:04 PM UTC
              total        used        free      shared  buff/cache   available
Mem:       16124420    14521380      265876     1099016     1337164      216736
Swap:      16776188      909176    15867012
```

</details>

> Kernel logs showing OOM 

Sorry, I do not have enough experience with this. `dmesg` seems to not show anything relevant, unless I don't know what to look for. I do not think the kernel is running out of memory, the script simply halts when trying to fork, but it does this close to 15G, not the maximum amount (15.4G). This is the last line of the traceback I posted above where it halts:

```
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

> `ulimit` ?

```
$ ulimit
unlimited
```

**Comment by lissyx** [comment]
>  However, I don't think this is the issue.

Please prove this. So far you just prove you get to the limit of your memory and `fork()` failing is just a side-effect.

**Comment by lissyx** [comment]
>  I could run the same command but on a trimmed-down version `head -n1001` of the `train.csv` set.

Please do.



> Most clips are in the range of 100KB to 200KB

Have you verified this?

**Comment by i-sf** [comment]
> > Most clips are in the range of 100KB to 200KB
>
> Have you verified this?

I've checked with `ls -lh | head` and the 10 first files fall in the range. If you take the average of 381K files over 58G, the math also checks out (roughly ~160KB).

**Comment by i-sf** [comment]
Running `DeepSpeech.py` as above but with batch size 10, given the following `.csv` sizes:

```
$ wc /mnt/corpus/clips/{train,dev,test}.csv
  1001   9759  97198 /mnt/data/corpus/cv-es-5.1/clips/train.csv
   151   1466  14613 /mnt/data/corpus/cv-es-5.1/clips/dev.csv
   151   1398  14156 /mnt/data/corpus/cv-es-5.1/clips/test.csv
```

When this is done, memory usage is around the 4.5GB mark. It still increases, but far more slowly.

Not knowing how `DeepSpeech.py` is working, perhaps it's loading all the `.wav` files randomly and never freeing them? Even if it only trains with 1K at a time, it has 381K to choose from. If this was the case, then I misunderstood how the limits work, as I thought it would only choose the same first 1000, not 1000 random every time. This is a plausible explanation with no additional knowledge of the code.

Assuming that's the case, I presume the solution would be to have the script free the loaded files after it completes the training step. This can potentially cause a lot more reads from disk, but will keep the memory usage reasonable, and with so many files but such a low limit, it's probably unlikely the cache would be reused anyway. Regardless, I expect the bottleneck to be training itself, not reading from disk.

Thank you both so much for helping me investigate this issue.

**Comment by i-sf** [comment]
I would like to know why was this closed as invalid? Why is wanting to adjust the behaviour of `--limit_*` to be adjusted to free the memory it used after each epoch invalid? If I were to send a patch for this, would it mean it would be rejected?

**Comment by i-sf** [comment]
By the way, after training completes, it seems to get stuck and use a lot of CPU (and the memory isn't freed, either):

<details><summary>Last lines of output</summary>

```
--------------------------------------------------------------------------------
I Exporting the model...
I Loading best validating checkpoint from /mnt/corpus/tiny-ds-train/checkpoints/best_dev-393
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_5/bias
I Loading variable from checkpoint: layer_5/weights
I Loading variable from checkpoint: layer_6/bias
I Loading variable from checkpoint: layer_6/weights
I Models exported at /mnt/corpus/tiny-ds-train/exported
I Model metadata file saved to /mnt/corpus/tiny-ds-train/exported/author_model_0.0.1.md. Before submitting the exported model for publishing make sure all information in the metadata file is correct, and complete the URL fields.
```

</details>

<details><summary>First few lines of top</summary>

```
top - 08:23:33 up 4 days, 15:26,  4 users,  load average: 2.16, 39.16, 27.86
Tasks: 729 total,   1 running, 728 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.4 us,  6.4 sy,  0.0 ni, 92.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15746.5 total,    176.0 free,  13959.3 used,   1611.3 buff/cache
MiB Swap:  98303.0 total,  52354.2 free,  45948.8 used.    378.2 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27090 root      20   0   36.1g   1.4g 420212 S  35.2   9.4   1619:55 DeepSpeech.py
 7968 admin     20   0   11788   4344   3032 R   0.7   0.0   0:00.19 top
```

</details>

35% CPU usage after being done, 45948MB of swap usage and 13959MB of RAM in use after completing does not feel right. At least the GPU is not in use (even if memory is still allocated there).

**Comment by lissyx** [comment]
> I would like to know why was this closed as invalid?

because there seems to be no bug that you first described


> If I were to send a patch for this, would it mean it would be rejected?

if you have a clear bug,  STRs and a patch, that's not the same story.

**Comment by i-sf** [comment]
No point in opening a new issue if it's not considered a bug, so I will ask first. Is `DeepSpeech.py` not freeing the memory used after each epoch something that could be considered a bug that needs fixing? If it is, then I would consider this issue to still be valid (it's running out of memory when it shouldn't because it should be freeing the data it loaded after each epoch).

**Comment by i-sf** [comment]
Another issue is that cancellation does not seem to be clean (I need to press <kbd>Ctrl+C</kbd> a few times or else I won't actually terminate), but that might need to be a separate issue, if you consider it to be one.

**Comment by lissyx** [comment]
> Another issue is that cancellation does not seem to be clean (I need to press Ctrl+C a few times or else it won't actually terminate), but that might need to be a separate issue, if you consider it to be one.

that's not a bug, that's a feature of python

**Comment by lissyx** [comment]
> No point in opening a new issue if it's not considered a bug, so I will ask first. Is `DeepSpeech.py` not freeing the memory used after each epoch something that could be considered a bug that needs fixing? If it is, then I would consider this issue to still be valid (it's running out of memory when it shouldn't because it should be freeing the data it loaded after each epoch).

you only have showed weird behaviors when you push **your** system to the limits. if you have clear STR, you are welcome to file a bug.

**Comment by i-sf** [comment]
> that's not a bug, that's a feature of python

I would expect a well-structured Python program that, when I pressed <kbd>Ctrl+C</kbd>, would cleanly unlock every point where the threads or processes are locked (e.g. stuck waiting in queues) and finish. Not to need to repeatedly send `KeyboardInterrupt`. But if you consider this a "feature" of Python and not a bug in `DeepSpeech.py`, that's fine by me.

> you only have showed weird behaviors when you push **your** system to the limits

I expect my system to be able to handle 1000 audio clips at a time. I expect the `--limit_*` flags to tell `DeepSpeech.py` how much data it should load and train with at a time. At the very least, the help could be updated to clarify that it limits the amount of in-use audios, and that are not freed after the epoch completes. Regardless, I would argue this behaviour should change, to enable people (like me) to train on very large datasets, with a small percentage of the data at a time.

> if you have clear STR, you are welcome to file a bug

I am not familiar with the abbreviation "STR", if you could explain it, I would be grateful.

**Comment by lissyx** [comment]
> I would expect a well-structured Python program that, when I pressed Ctrl+C, would cleanly unlock every point where the threads or processes are locked (e.g. stuck waiting in queues) and finish. Not to need to repeatedly send `KeyboardInterrupt`. But if you consider this a "feature" of Python and not a bug in `DeepSpeech.py`, that's fine by me.

Please, search about python, multithreading and killing with CTRL+C. If you are willing to fix that properly, and this is likely going to be a can of worms, you are welcome to send a patch.



> I expect my system to be able to handle 1000 audio clips at a time. I expect the `--limit_*` flags to tell `DeepSpeech.py` how much data it should load and train with at a time. At the very least, the help could be updated to clarify that it limits the amount of in-use audios, and that are not freed after the epoch completes. Regardless, I would argue this behaviour should change, to enable people (like me) to train on very large datasets, with a small percentage of the data at a time.

That feature has been broken for ages until we fix it a few months ago and we don't rely on it. So the hard truth is, it can be bugged. 

If you think the help is not clear enough, please send a patch ...



> I am not familiar with the abbreviation "STR", if you could explain it, I would be grateful.

Steps To Reproduce

**Comment by i-sf** [comment]
> Please, search about python, multithreading and killing with CTRL+C. If you are willing to fix that properly, and this is likely going to be a can of worms, you are welcome to send a patch.

Now that we've agreed that this could be solved but it would potentially take a large amount of effort and time, do you think there should be a report open to track progress on this work, or is it so unlikely to ever be fixed that it's not worth tracking? Maybe someone would eventually step in and tackle it, was the report present.

> That feature has been broken for ages until we fix it a few months ago and we don't rely on it. So the hard truth is, it can be bugged.

Okay thanks, I will open a new issue tracking improvements to that feature then, with steps to reproduce.

**Comment by lissyx** [comment]
> Regardless, I would argue this behaviour should change, to enable people (like me) to train on very large datasets, with a small percentage of the data at a time.

Please also understand that your usecase is quite a specific one, and to be honest this is the first time someone reports. It's not surprising you run into issues.



> I expect my system to be able to handle 1000 audio clips at a time.

Which turned out to be true.



>  I expect the `--limit_*` flags to tell `DeepSpeech.py` how much data it should load and train with at a time.

Which was supposed to be how it works, but the feeding is non trivial, so there could be bugs from us, bugs from the tensorflow runtime. This is where it should be dealt with: https://github.com/mozilla/DeepSpeech/blob/3e10163ec8c8941d1a5afb45f8b1c5b1e0c9592c/training/deepspeech_training/util/feeding.py#L106-L120

So above `num_samples` we should stop yielding, but maybe we already read and transformed WAV.

> At the very least, the help could be updated to clarify that it limits the amount of in-use audios, and that are not freed after the epoch completes.

Again, feeding and running the graph is not that simple.

**Comment by lissyx** [comment]
> Now that we've agreed that this could be solved but it would potentially take a large amount of effort and time, do you think there should be a report open to track progress on this work, or is it so unlikely to ever be fixed that it's not worth tracking? Maybe someone would eventually step in and tackle it, was the report present.

If I was able to predict future, I would be rich.



> Okay thanks, I will open a new issue tracking improvements to that feature then, with steps to reproduce.

Thanks, but please understand we are unlikely to have time to investigate.

**Comment by i-sf** [comment]
> Again, feeding and running the graph is not that simple.

I am certain that I am very likely underestimatnig the difficulty in solving this issue, but my primary goal is making sure we understand that all known issues are acknowledged and tracked, even if there is no time to solve them in the near or mid future.

> If I was able to predict future, I would be rich.

Not quite my point, rather, if you think the issue should be tracked at all when it's so unlikely anyone has the time or interest to ever fix it. It technically works, but it could be improved. I am asking for your opinion on the importance to **track** this bug (having an issue open for it in this repository).

> we are unlikely to have time to investigate.

This is completely understandable, the project's goals do not necessarily align with mine. But given it's an open source, anyone can step in and make the library better for everyone as long as the additions are reasonable (worst case, a new fork is born). The first step is to have a way to track these features, for which I've now opened the above linked issue.

**Comment by LiamHz** [comment]
@i-sf Have you tried setting the `--use_allow_growth` flag to `True`? This fixed the OOM issue for me

**Comment by reuben** [comment]
> > 
> 
> I would expect a well-structured Python program that, when I pressed Ctrl+C, would cleanly unlock every point where the threads or processes are locked (e.g. stuck waiting in queues) and finish. Not to need to repeatedly send `KeyboardInterrupt`. But if you consider this a "feature" of Python and not a bug in `DeepSpeech.py`, that's fine by me.

It bothers me too and I took a brief look at it but could not identify any specific reasons in our code, thus reaching the same conclusion as @lissyx: this is a weird Python behavior. But to be clear, I would happily review and accept a patch to fix this, I just have no idea where the problem comes from. I filed https://github.com/mozilla/DeepSpeech/issues/3471 to track this, you're welcome to take a look.

**Comment by i-sf** [comment]
> Have you tried setting the `--use_allow_growth` flag to `True`? This fixed the OOM issue for me

I have been trying around with a larger corpus and keep getting https://github.com/tensorflow/tensorflow/issues/14433#issuecomment-343403513 with ever-decreasing batch sizes. That comment suggests the same solution. I have tried that flag, and although memory usage starts low, it ends up erroring in the same way. Might be my setup or other parameters causing issues though. I'll keep that flag set at all times though, since it likely helps, if anything. Thanks for confirming.

> I filed #3471 to track this

Thanks for stepping in, even if it's not fixed any time soon, it's good to know that it's acknowledged and being tracked. I'll be sure to watch that issue.
