### ISSUE TITLE
("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))

### ISSUE THREAD

**Issue by nerd2ninja** [mozilla/DeepSpeech#3465]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No. Got error running test script in the install instructions
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: TensorFlow: v2.3.0-6-g23ad988
- **TensorFlow version (use command below)**: TensorFlow: v2.3.0-6-g23ad988
- **Python version**: Python 3.7.9
- **Bazel version (if compiling from source)**: How do I get that?
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- **CUDA/cuDNN version**: It seems to be broken and I can't fix it
- **GPU model and memory**: NVIDIA GEFORCE 1080Ti
- **Exact command to reproduce**: deepspeech --model deepspeech-0.9.1-models.pbmm --scorer deepspeech-0.9.1-models.scorer --audio audio/2830-3980-0043.wav

Gets error

2020-12-12 00:46:49.695794: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Loading model from file deepspeech-0.9.1-models.pbmm
TensorFlow: v2.3.0-6-g23ad988
DeepSpeech: v0.9.3-0-gf2e9c85
Not found: deepspeech-0.9.1-models.pbmm; No such file or directory
Traceback (most recent call last):
  File "/home/waifuaiv2/anaconda3/envs/deepspeech/bin/deepspeech", line 8, in <module>
    sys.exit(main())
  File "/home/waifuaiv2/anaconda3/envs/deepspeech/lib/python3.7/site-packages/deepspeech/client.py", line 119, in main
    ds = Model(args.model)
  File "/home/waifuaiv2/anaconda3/envs/deepspeech/lib/python3.7/site-packages/deepspeech/__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)

**Comment by lissyx** [comment]
This is not a support channel, use discourse.

**Comment by lissyx** [comment]
> Not found: deepspeech-0.9.1-models.pbmm; No such file or directory

And this is likely your problem...

**Comment by dynamicdips** [comment]
Get error-
raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)
