### ISSUE TITLE
Chinese Evaluation Error.

### ISSUE THREAD

**Issue by iamweiweishi** [mozilla/DeepSpeech#3468]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:pip install tensorflow-gpu
- **TensorFlow version (use command below)**:1.15.4
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:-
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:10.1
- **GPU model and memory**:16G V100
- **Exact command to reproduce**:

I installed the requirements from setup.py. 
What I am trying to do is to use Chinese pretrained model from [Here](https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3), and evalute the pretrained model based on my own audios. 

The test.csv file is like this,
![image](https://user-images.githubusercontent.com/23145532/102077967-14596300-3e45-11eb-8694-bf8b70e693b5.png)

Then I run the command:
CUDA_VISIBLE_DEVICES=7 python evaluate.py --scorer_path deepspeech-0.9.3-checkpoint/deepspeech-0.9.3-models-zh-CN.scorer --test_files data/test.csv --checkpoint_dir deepspeech-0.9.3-checkpoint/

Then, I got the Error,
ValueError: Alphabet cannot encode transcript "哈哈" while processing sample "data/audios/real.wav", check that your alphabet contains all characters in the training corpus. Missing characters are: ['哈', '哈'].

I do not know the exact reason. The alphabet I use might be for English training and inference. Although the pretrained Chinese Model could be fetched, I have no idea where could I get the Chinese Alphabet.
  
Thank you.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by lissyx** [comment]
This is no à bug, please reach for support on Discourse. Chinese model, as documented, relies on bytes output mode and not an alphabet.

**Comment by lissyx** [comment]
> The test.csv file is like this

Please avoid screenshots and share pure text content.
