### ISSUE TITLE
Please switch to .taskcluster.yml version 1

### ISSUE THREAD

**Issue by djmitche** [mozilla/DeepSpeech#3472]
In taskcluster/taskcluster#4098 we are dropping support for v0.  This repo is one of the few still using v0.

SInce it's just creating a decision task, the transition should be pretty easy.  The https://community-tc.services.mozilla.com/quickstart can generate a template that you can then copy/paste the payload, etc. into.  https://community-tc.services.mozilla.com/docs/reference/integrations/github/taskcluster-yml-v0 and https://community-tc.services.mozilla.com/docs/reference/integrations/github/taskcluster-yml-v1 can help translate the `{{..}}` into JSON-e expressions, where necessary.

**Comment by djmitche** [comment]
This will also apply on the `tensorflow` repo.  It doesn't support issues so I can't file a separate issue to track that.

The timing on this drop is flexible -- we just want something sooner than "never" :)

**Comment by djmitche** [comment]
(or maybe tensorflow isn't actually running tasks?)

**Comment by reuben** [comment]
I've got a WIP that seems to be working in #3473, basically by emulating the v0 GITHUB_* variables by hand. Seems self contained enough but I'll wait for Alex to be back to get this reviewed and merged.

**Comment by djmitche** [comment]
NIce!!

**Comment by lissyx** [comment]
> I've got a WIP that seems to be working in #3473, basically by emulating the v0 GITHUB_* variables by hand. Seems self contained enough but I'll wait for Alex to be back to get this reviewed and merged.

is it ready yet?

**Comment by reuben** [comment]
Now it is :)

**Comment by djmitche** [comment]
I'm curious why the variables are in the command and not in the `env:..` map?  I'm not disagreeing -- if it works it works :)

**Comment by reuben** [comment]
Because I completely missed that! 😅

**Comment by reuben** [comment]
Merged on master (thanks for the `payload.env` tip, looks cleaner now!), but we still have an active release branch to merge it on.

**Comment by djmitche** [comment]
No rush on our account -- this functionality won't be removed immediately.  If you'd rather wait for the next release branch that's probably fine!

**Comment by djmitche** [comment]
@reuben did this get wrapped up?  It's fine if there's more time required, but I will stop pinging if it's done :)

**Comment by reuben** [comment]
@djmitche This was merged on master but we still have an active release branch using the older format.

**Comment by lissyx** [comment]
@djmitche I need to thank you again for the continued support regarding TaskCluster, but we are sadly not going to address that :/
