### ISSUE TITLE
DeepSpeech version (0.10.0-alpha.3) and CTC decoder version (0.9.3) do not match. Please ensure matching versions are in use.

### ISSUE THREAD

**Issue by shs-odoo** [mozilla/DeepSpeech#3481]
DeepSpeech version (0.10.0-alpha.3) and CTC decoder version (0.9.3) do not match. Please ensure matching versions are in use.

not able to run deepspeech.py program any solution?

**Comment by azarezade** [comment]
@shs-odoo `pip3 install ds-ctcdecoder==0.10.0-alpha.3` should solve your issue.

**Comment by lissyx** [comment]
> DeepSpeech version (0.10.0-alpha.3) and CTC decoder version (0.9.3) do not match. Please ensure matching versions are in use.
> 
> not able to run deepspeech.py program any solution?

Or use `0.9.3 for everything. By the way, this is not a bug so please use Discourse for requesting support.
