### ISSUE TITLE
Training error when trying to train with "--train_cudnn" flag.

### ISSUE THREAD

**Issue by Varuzhan97** [mozilla/DeepSpeech#3494]
Hi. I am using Linux Ubuntu 20.14 OS with GTX 1060 GPU. With "--train_cudnn" flag I am getting this error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNCanonicalToParams' used by node tower_0/cudnn_lstm/cudnn_lstm/CudnnRNNCanonicalToParams (defined at /home/varuzhan/anaconda3/envs/RUSSIAN/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [seed2=257, seed=4568, dropout=0, num_params=8, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm"]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]

	 [[tower_0/cudnn_lstm/cudnn_lstm/CudnnRNNCanonicalToParams]]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
I have installed required CUDA, cuDNN and Tensorflow-gpu correct versions.  Without "--train_cudnn" flag I can do the training. How can I fix this error?

**Comment by lissyx** [comment]
@Varuzhan97 Please respect the template and reach for support on Discourse.

**Comment by lissyx** [comment]
> I have installed required CUDA, cuDNN and Tensorflow-gpu correct versions. Without "--train_cudnn" flag I can do the training. How can I fix this error?

Your error explicitely stipulates that your CuDNN setup is broken. When reaching for support, be respectful of the time of those who are going to help you and provide context, setup steps and versions you followed. DONT just "I did as the doc said", 99% of those statements turns out to show people followed something somehow wrong or missed steps.

**Comment by Varuzhan97** [comment]
Sorry for template and thanks.
