### ISSUE TITLE
error when adding hot_words

### ISSUE THREAD

**Issue by sumeet-tiwari-samespace** [mozilla/DeepSpeech#3501]
`  File "/usr/local/lib/python3.7/dist-packages/ds_ctcdecoder/swigwrapper.py", line 810, in ctc_beam_search_decoder
    return _swigwrapper.ctc_beam_search_decoder(probs, alphabet, beam_size, cutoff_prob, cutoff_top_n, ext_scorer, hot_words, num_results)
TypeError: Wrong number or type of arguments for overloaded function 'ctc_beam_search_decoder'.
  Possible C/C++ prototypes are:
    ctc_beam_search_decoder(double const *,int,int,Alphabet const &,size_t,double,size_t,std::shared_ptr< Scorer >,std::unordered_map< std::string,float,std::hash< std::string >,std::equal_to< std::string >,std::allocator< std::pair< std::string const,float > > >,size_t)
    ctc_beam_search_decoder(double const *,int,int,Alphabet const &,size_t,double,size_t,std::shared_ptr< Scorer >,std::unordered_map< std::string,float,std::hash< std::string >,std::equal_to< std::string >,std::allocator< std::pair< std::string const,float > > >)`

Using ds-ctcdecoder 0.9.3

**Comment by lissyx** [comment]
It will be impossible to help if you dont share code to repro and more context. Hot words is exposed through the libdeepspeech api and bindings, not the decoder.

**Comment by sumeet-tiwari-samespace** [comment]
@lissyx i am calling the function directly

`from ds_ctcdecoder import Scorer, Alphabet, ctc_beam_search_decoder`
`
hot_words = {"monday":1.5}
alphabet = Alphabet("alphabet.path")
scorer = Scorer(1, 2.5, scorer_path="scorer.path", alphabet=alphabet)
res = ctc_beam_search_decoder(
            probs_list,
            alphabet,
            beam_size=10,
            cutoff_prob=1,
            cutoff_top_n=40,
            scorer=scorer,
            hot_words=hot_words
        )
`

**Comment by lissyx** [comment]
> @lissyx i am calling the function directly
> 
> `from ds_ctcdecoder import Scorer, Alphabet, ctc_beam_search_decoder hot_words = {"monday":1.5} alphabet = Alphabet("alphabet.path") scorer = Scorer(1, 2.5, scorer_path="scorer.path", alphabet=alphabet) res = ctc_beam_search_decoder( probs_list, alphabet, beam_size=10, cutoff_prob=1, cutoff_top_n=40, scorer=scorer, hot_words=hot_words )`

Well, this is not supported, it's not a bug. Please reach for support on Discourse.
