### ISSUE TITLE
Incorrect math for _split_sets in ./bin/import_swb.py

### ISSUE THREAD

**Issue by dzubke** [mozilla/DeepSpeech#3511]
Based on the comments in `_split_sets` fuction in `./bin/import_swb.py`([link](https://github.com/mozilla/DeepSpeech/blob/master/bin/import_swb.py#L292)), I think the math is incorrect in the training/dev/test splits. 

The function is below:

```
def _split_sets(filelist):
    # We initially split the entire set into 80% train and 20% test, then
    # split the train set into 80% train and 20% validation.
    train_beg = 0
    train_end = int(0.8 * len(filelist))

    dev_beg = int(0.8 * train_end)
    dev_end = train_end
    train_end = dev_beg

    test_beg = dev_end
    test_end = len(filelist)

    return (
        filelist[train_beg:train_end],
        filelist[dev_beg:dev_end],
        filelist[test_beg:test_end],
    )
```

And the comment suggests a "80% train and 20% test" and then an "80% train, 20% validation" split. In either case, the code with a multiplication factor of `0.8` as written will yield a 64%/ 16%/ 20%  for a training/dev(validation)/test split, which doesn't seem desriable or the intended result.  

If the desired split was 80%/10%/10% for training/dev/test, the multiplication factor would need to be `0.9` instead of `0.8`. 

A factor of `0.95` could be used to get a 90/5/5 split. 

Just wanted to point this small error out, as it is consequential for anyone using this importer. If you have splitting functions in other importers, you may want to review them as well. 

I really enjoyed reading through the  `import_swb.py` script; really beautiful code!

**Comment by lissyx** [comment]
@dzubke It seems you identified a legit issue, why not sending a PR?

**Comment by reuben** [comment]
I don't think this is a math error, just a judgement error. The .64/.16/.20 split is intended, but I do think the validation and test sets end up too large and should be based on a confidence level estimation rather than a set percentage.

**Comment by dzubke** [comment]
Yeah, I thought the validation and test sets ended up being a bit large and awkward that they aren't the same size. It also wasn't clear from the function comments that the training set would be 64% instead of 80%.  

I'm happy to submit a PR, though I'm not sure, @reuben, what a "confidence level estimate" is for the dataset split. What would that entail?

**Comment by dzubke** [comment]
Unless you have strong feelings about using the confidence level estimation approach, @reuben, I will aim to submit a PR with the changes I outlined next week.

**Comment by reuben** [comment]
Sorry @dzubke, I missed the first email here! By confidence level I mean going for e.g. a 99% confidence level and 1% margin of error based on the number of samples in your dataset. You can use a tool such as [this one](https://www.surveymonkey.com/mp/sample-size-calculator/) for example.

**Comment by reuben** [comment]
That'd be my preferred approach but I don't feel too strongly about this as we're no longer using Switchboard for our trainings, so if you don't think it's reasonable I'lll take the PR with your original suggestions too :)

**Comment by dzubke** [comment]
I'm open to the confidence-level approach but needed an explanation as I haven't seen dataset splits like that before. Thanks for the link. 

I see the formula for calculating the sample size on the link you shared. To check my understanding of how to implement the tool you shared in this context, here is some pseudo-code:  

```
sample_size = calc_sample_size(population_size, confidence_level, error_margin)
where:
sample_size = size of the validation and test sets.
population_size = the size of the entire dataset. 
confidence_level and error_margin  = constants set by the user. 
```

And then the training/validation/test split would be: 
```
train_size = population_size - 2*sample_size
validation_size = sample_size
test_size = sample_size
```

Is my understanding correct? 

Do you think 99% and 1% are good default values for confidence level and error margin, respectively? 

I see Fisher also uses the same `_split_sets` function. I could put the `_split_sets` function in a `./bin/utils.py` file and import that function into `./bin/import_swb.py` and `./bin/import_fisher.py` but that may be overkill for a single function, so I may instead just duplicate the function in the switchboard and fisher scripts. 

Thanks for the input!

**Comment by reuben** [comment]
In general I prefer to avoid lifting functionality out of the importers into shared scripts to avoid having importers break on changes that aren't made directly to them. Datasets are mostly immutable so the importer code should also be mostly immutable. In this case, I don't expect this math will ever change anyway so it's OK to lift it into utils. I also remembered that there's already a computation in the tree for it here:

https://github.com/mozilla/DeepSpeech/blob/962a117f7ed5720435904e3ac864cc8420256ca1/bin/import_swc.py#L103-L118

And yes, updating Fisher and other affected importers is welcome. Thanks for the help!

**Comment by dzubke** [comment]
Thanks @reuben for the link to the `get_sample_size` function in import_swc.py. That made the updates to the `_split_sets` function trivial. I just submitted the PR that updates both `bin/import_swb.py` and `bin/import_fisher.py`.
