### ISSUE TITLE
Saw a non-null label (index >= num_classes - 1) following a null label

### ISSUE THREAD

**Issue by neenaloysius** [mozilla/DeepSpeech#3520]
Im getting the following error while doing CTC training:
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 40 labels: 35,4,6,18,8,36,29,37,38,39,40,0 labels seen so far: 35,4,6,18,8,36,29,37,38
	 [[node CTC-MODEL/ctc/CTCLoss (defined at <ipython-input-9-9c0e9d8d1d6f>:18) ]]
  (1) Invalid argument:  Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 40 labels: 35,4,6,18,8,36,29,37,38,39,40,0 labels seen so far: 35,4,6,18,8,36,29,37,38
	 [[node CTC-MODEL/ctc/CTCLoss (defined at <ipython-input-9-9c0e9d8d1d6f>:18) ]]
	 [[gradient_tape/CTC-MODEL/ctc/Shape/_72]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_12365]

**Comment by lissyx** [comment]
@neenaloysius Please use discourse for support.

**Comment by xingxindrst** [comment]
> 我在进行 CTC 训练时收到以下错误：无效参数错误：找到 2 个根错误。 （0） 无效参数：看到一个非空标签（索引 >= num_classes - 1） 在空标签之后，批次：0 num_classes： 40 标签：35，4，6，18，8，36，29，37，38，39，40，0 到目前为止看到的标签：35，4，6，18，8，36，29，37，38 [[节点 CTC-MODEL/ctc/CTCLoss （定义为：18）]] （1） 无效参数： 看到一个非空标签（索引 >= num_classes - 1） 在空标签之后，批次：0 num_classes：40 标签： 到目前为止看到的 35，4，6，18，8，36，29，37，38，39，40，0 个标签：35，4，6，18，8，36，29，37，38 [[节点 CTC-MODEL/ctc/CTCLoss （定义于 ：18） ]] [[gradient_tape/CTC-MODEL/ctc/Shape/_72]] 0 次成功操作。忽略 0 个派生错误。[操作：__inference_train_function_12365]

Have you solved the issue?I'm having the same issue
