### ISSUE TITLE
Installing Deepspeech on Raspberry PI 4 OS 64 bit fails

### ISSUE THREAD

**Issue by hackebike** [mozilla/DeepSpeech#3521]
I am trying to Install **deepspeech** on Raspberry PI 4 OS 64 bit and it failes, I attached a log

Raspberry PI 4 8Gb 64 bit OS
Linux 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux

**pip3 install deepspeech --verbose > deepspeech.log
  Could not find a version that satisfies the requirement deepspeech (from versions: )
No matching distribution found for deepspeech**

Probably not supported?

[deepspeech.log](https://github.com/mozilla/DeepSpeech/files/5937160/deepspeech.log)

**Comment by lissyx** [comment]
First, follow the github template and seek support on Discourse. Second, aarch64 is not allowed on pypi. Please use github release linux aarch64 python wheel.

**Comment by lissyx** [comment]
Third, as rpi os 64 bits is still relatively new we have not had time to verify and add ci, though our Linux aarch64 python wheel are tested on armbian buster so it should work well.

**Comment by hackebike** [comment]
ok did not know that was not listed.
Can you point me to which packages I need to download?
thx

**Comment by hackebike** [comment]
I was able to run it on the Raspberry PI OS 64 bit.
I tested the ~/deepspeech/DeepSpeech-examples/mic_vad_streaming $ python3 mic_vad_streaming.py -m deepspeech-0.9.3-models.tflite -s deepspeech-0.9.3-models.scorer

btw, sorry, I am new to this, so doing a lot of reading!

**Comment by hackebike** [comment]
The exmaple works but I am seeing some "warnings" ?

python3 mic_vad_streaming.py -m deepspeech-0.9.3-models.tflite -s deepspeech-0.9.3-models.scorer -v 3
Initializing model...
INFO:root:ARGS.model: deepspeech-0.9.3-models.tflite
TensorFlow: v2.3.0-6-g23ad988
DeepSpeech: v0.9.3-0-gf2e9c85
INFO:root:ARGS.scorer: deepspeech-0.9.3-models.scorer
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib conf.c:5014:(snd_config_expand) Unknown parameters {AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 0}
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 0}
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM input
Listening (ctrl-C to exit)...
Recognized:

**Comment by ftyers** [comment]
@hackebike those look to be related to your sound setup and not DeepSpeech. If you like to continue the conversation, could I recommend [DeepSpeech on Discourse](https://discourse.mozilla.org/c/deepspeech/247). Thanks!

**Comment by lissyx** [comment]
> ok did not know that was not listed.
> Can you point me to which packages I need to download?
> thx

As i said, linux python wheel for aarch64

**Comment by odidev** [comment]
> First, follow the github template and seek support on Discourse. Second, aarch64 is not allowed on pypi. Please use github release linux aarch64 python wheel.

Now, AArch64 is supported by PyPI. It would be helpful is you could upload AArch64 wheels on PyPI.

**Comment by lissyx** [comment]
> > First, follow the github template and seek support on Discourse. Second, aarch64 is not allowed on pypi. Please use github release linux aarch64 python wheel.
> 
> Now, AArch64 is supported by PyPI. It would be helpful is you could upload AArch64 wheels on PyPI.

Feel free to add support in a PR, i'm not working on this anymore.
