### ISSUE TITLE
DeepSpeech iOS Compile Error in XCode 12.4

### ISSUE THREAD

**Issue by erksch** [mozilla/DeepSpeech#3525]
Hey there!

I am currently integrating the DeepSpeech iOS framework into an App.
I downloaded the ios framework from task cluster on tag 0.9.3.

With XCode 12.4 and swift 5.3.2 I am getting the following compile error:

```
module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3.2
``` 

Here are some issues / resources on that

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

https://github.com/aws-amplify/aws-sdk-ios/issues/2365 (Similar issue for AWS SDK)

I guess a quick fix would be to update the XCode in CI that builds the releases to 12.4.
Other sources suggest adding the flag `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` in the build process.

- **Have I written custom code**: Made a new project and added the framework
- **OS Platform and Distribution**: macOS Big Sur Version 11.2 on Mac Mini

**Comment by lissyx** [comment]
> I guess a quick fix would be to update the XCode in CI that builds the releases to 12.4.

That's actually not a quick fix

**Comment by lissyx** [comment]
>  Other sources suggest adding the flag `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` in the build process.

I have no idea where to do that. @reuben maybe?

**Comment by zaptrem** [comment]
> BUILD_LIBRARY_FOR_DISTRIBUTION=YES

 @erksch I added that to the framework's build settings in Xcode a while ago and it started working for me. If you want, you can download the framework from my repo [here](https://github.com/zaptrem/react-native-transcription/blob/master/ios/Frameworks/deepspeech_ios.framework/deepspeech_ios).

However, the framework crashes completely on iOS when files are too long. I've been trying to fix the issue and provide information [here](https://github.com/mozilla/DeepSpeech/issues/3061) but the devs haven't commented on this significant issue in nearly a month in a half. I proposed a potential fix in the most recent comment, but it isn't quite working so I haven't opened a PR yet. Would you be willing to take a look at it?

**Comment by lissyx** [comment]
> I added that to the framework's build settings in Xcode a while ago and it started working for me.

You should make a PR then.

**Comment by zaptrem** [comment]
> > I added that to the framework's build settings in Xcode a while ago and it started working for me.
> 
> You should make a PR then.

I would, but I don’t know whether the Xcode GUI settings interact with your build system or if I have to modify some script somewhere.

**Comment by lissyx** [comment]
> > > I added that to the framework's build settings in Xcode a while ago and it started working for me.
> > 
> > 
> > You should make a PR then.
> 
> I would, but I don’t know whether the Xcode GUI settings interact with your build system or if I have to modify some script somewhere.

And I have no idea where this needs to be applied: env variable, config?

Please open a PR, we can help us, it's better than letting issues like that lay around.

**Comment by lissyx** [comment]
All of the ios stuff is within https://github.com/mozilla/DeepSpeech/tree/master/native_client/swift and building is drived by https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/ios-build.sh

**Comment by zaptrem** [comment]
> > > > I added that to the framework's build settings in Xcode a while ago and it started working for me.
> > > 
> > > 
> > > You should make a PR then.
> > 
> > 
> > I would, but I don’t know whether the Xcode GUI settings interact with your build system or if I have to modify some script somewhere.
> 
> And I have no idea where this needs to be applied: env variable, config?
> 
> Please open a PR, we can help you, it's better than letting issues like that lay around.

Maybe I misunderstood how PRs work? I thought I’m only supposed to open one when I’ve built the feature/fix. What’s it supposed to look like when there is no change yet? 

If I’m not misunderstanding you I’ll definitely submit it, but it’s 4:30am here (I wanted to see if I could catch Reuben while he was awake/online for the other issue) so I’ll do it tomorrow.

**Comment by lissyx** [comment]
> Maybe I misunderstood how PRs work? I thought I’m only supposed to open one when I’ve built the feature/fix (like I did when I submitted the last commit changes to that Swift folder you linked to). What’s it supposed to look like when there is no change yet?

We can discuss on this issue, and then you can open the PR, for example. But I really really hate it if you know a fix, and we have other people facing an issue than can be solved by that fix.


> but it’s 4:30am here

I guess you should be sleeping :)



> I wanted to see if I could catch Reuben while he was awake/online for the other issue

Reuben and myself are on the same timezone, and it's 10:47 now, but I know he's working on other things and I'm unsure he has time in the next hours / days to look at that. But when he can, I know he will look at it, no worries. It's not we don't care, it's just we lack of time (and we still have to babysit the macOS CI infra, which is painful ...)

**Comment by reuben** [comment]
> > > I added that to the framework's build settings in Xcode a while ago and it started working for me.
> > 
> > 
> > You should make a PR then.
> 
> I would, but I don’t know whether the Xcode GUI settings interact with your build system or if I have to modify some script somewhere.

Our CI simply calls `xcodebuild` which respects the GUI settings.

**Comment by lissyx** [comment]
Fixed in #3527

**Comment by lissyx** [comment]
@erksch @zaptrem If this is required on 0.9, please send matching PR.

**Comment by zaptrem** [comment]
Or just download it here and drop it in: https://community-tc.services.mozilla.com/tasks/DoV-Ms9WRNKXsC_1yTPBxA

**Comment by lissyx** [comment]
> Or just download it here and drop it in: https://community-tc.services.mozilla.com/tasks/DoV-Ms9WRNKXsC_1yTPBxA

Yes, but PRs artifact expires after seven days, merges artifacts expires after a bit more, but quite quickly.
And that does not change the fact it's only on `master`, while the original report was on `0.9.3`, though I'm unsure we would release a new stable version for just that, we could do a new alpha on `master`.

**Comment by zaptrem** [comment]
Whatever's easiest. A new alpha would probably be fine as afaik there haven't been any breaking changes for a while now.

**Comment by erksch** [comment]
Just came back to this and saw that there are no artifacts from the task cluster that have run the `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` configuration, I think. Is there a build available that was run with that configuration?

**Comment by lissyx** [comment]
Taskcluster has been decommissioned, you would need to add github actions support for iOS bindings.
