### ISSUE TITLE
Provide DeepSpeech German in pbmm format

### ISSUE THREAD

**Issue by GeorgeS2019** [mozilla/DeepSpeech#3530]
Please consider distribute DeepSpeech German in pbmm format.
If this is available in the original sites, please provide the link

**Comment by lissyx** [comment]
> Please consider distribute DeepSpeech German in pbmm format.
> If this is available in the original sites, please provide the link

Please understand we don't have:
 - enough people speaking german
 - enough data for training german

So we can't support German and currently only officially provide an English model.

Next time, please make an effort and look at Discourse as documented in the GitHub template you removed: there are people sharing links to models they train.

**Comment by GeorgeS2019** [comment]
@lissyx  I am new to DeepSpeech community. I am now checking up the Discourse link. Tank you.

**Comment by jhagege** [comment]
@GeorgeS2019 Can you please provide pointers to the solution? 
Do you have a link documenting it? Thanks!
