### ISSUE TITLE
Can this model be used for Speaker Recognition

### ISSUE THREAD

**Issue by doctorwho-123** [mozilla/DeepSpeech#3534]
Hi,
I am working on Speaker Recognition. Is it possible to use this model for Speaker Recognition ?
If yes can you please guide me a little. And If not can you refer me some Deep Learning models which I can use for it  by c# .

**Comment by ftyers** [comment]
Dear @doctorwho-123, please take this question to Mozilla's [Discourse](https://discourse.mozilla.org/c/deepspeech/247). GitHub issues are not a support channel.

**Comment by lissyx** [comment]
@doctorwho-123 Please avoid spamming multiple repos with the same question.
