### ISSUE TITLE
Error when trying deepspeech in Java (not Android)

### ISSUE THREAD

**Issue by Jochen-sys** [mozilla/DeepSpeech#3537]
Hello,
I'm trying to integrate deepspeech in Java, but when I'm starting my Java programm I'm getting following error:
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no deepspeech-jni in java.library.path
I'm working on Windows 10 and after some research I found out, that deepspeech-jni is an .so and no dll. So I don't know if this cares about the using system, but also I don't know how it could work, so if you could help me, I would be very thankfull.

**Comment by lissyx** [comment]
We don't have Java support outside of Android for now. See #3503

**Comment by Jochen-sys** [comment]
Ouh ok I'm sorry. I only thought is because of this documentary:
https://deepspeech.readthedocs.io/en/latest/Java-API.html
But thanks for the answer.

**Comment by Jzow** [comment]
@Jochen-sys hi jochen Have you found a solution to integrate Java

**Comment by Jochen-sys** [comment]
No and I don't think there is any support for Java, because it was made only for Android.
