### ISSUE TITLE
Look into using Nervana's gemm implementation with TensorFlow

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#354]
See http://svail.github.io/rnn_perf/

And https://github.com/NervanaSystems/nervanagpu

The performance difference grows with mini-batch size. At low values cuBLAS is equivalent, so this may not be applicable to our current models. But even for batch size 32 there's already significant improvements in some of Baidu's benchmarks.

**Comment by kdavis-mozilla** [comment]
I'm wondering if this is worth the effort. It seems like there are many pain points:

[nervanagpu](https://github.com/NervanaSystems/nervanagpu) deprecated and only maintained as a backend inside [neon](https://github.com/NervanaSystems/neon). So if we were to use nervanagpu in TensorFlow, work would be involved in combating bitrot, maintaining the abandoned code base, integrating nervanagpu in to TensorFlow.... 

If we were to switch to neon, we'd loose time learning the new platform, porting code, and we'd loose contributors/momentum (Tensorflow has 602 contributors to neon's 52)

As we are working with batch size 16 the performance difference seems to be there, but maybe not worth the effort required to use nervanagpu.

![graph](https://cloud.githubusercontent.com/assets/12054740/22462092/28a94940-e7ac-11e6-97bf-9921d1fbf6f3.png)
