### ISSUE TITLE
Common Voice training data

### ISSUE THREAD

**Issue by monkeycc** [mozilla/DeepSpeech#3551]
https://deepspeech.readthedocs.io/en/v0.9.3/TRAINING.html

bin/import_cv2.py --filter_alphabet path/to/some/alphabet.txt /path/to/extracted/language/archive

Mozilla’s Common Voice  6.1
-----------

/ clips
dev.tsv
invalidated.tsv
other.tsv
reported.tsv
test.tsv
train.tsv
validated.tsv

-----------

How to transform ？

**Comment by lissyx** [comment]
Please respect the GitHub issue template and reach for support on Discourse: https://discourse.mozilla.org/c/deepspeech/247
