### ISSUE TITLE
Chinese  Mandarin Garbled 

### ISSUE THREAD

**Issue by wingdi** [mozilla/DeepSpeech#3556]
I use pre-trained model  deepspeech-0.9.3-models-zh-CN.pbmm, it generated Garbled  in GBK or UTF-8 ; 
is there any method to repair this ?

this is the generate json :
![QQ图片20210314104814](https://user-images.githubusercontent.com/25787391/111055621-d2c36d00-84b2-11eb-8dc5-c305cef82e19.png)

when i  print the word value,

`word = '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94'
    print(word)`
 
it got :
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-15: surrogates not allowed 

 
os :  win10 ; python Server ;  Pycharm(UTF-8)

**Comment by ftyers** [comment]
Hey there! Looks like [Discourse](https://discourse.mozilla.org/c/deepspeech/247) is the right way to go for this :)
