### ISSUE TITLE
Mandarin Chinese  garbled

### ISSUE THREAD

**Issue by wingdi** [mozilla/DeepSpeech#3557]
I use pre-trained model deepspeech-0.9.3-models-zh-CN.pbmm, it generated Garbled in GBK or UTF-8 ;
is there any method to repair this ?

this is the generate json :
![QQ图片20210314104814](https://user-images.githubusercontent.com/25787391/111094543-76c21c80-8576-11eb-9e16-bcfd96be14ab.png)

when i print the word value:
`word = '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94' `

print(word)

it got :
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-15: surrogates not allowed

os : win10 ; python Server ; Pycharm(UTF-8)

Why this issue closed ? I didn't find solution in Discourse. and other similar questions in Discouse and here didn't get a solution.    I think this is a bug , it need to be fixed ...

**Comment by lissyx** [comment]
> Why this issue closed ? I didn't find solution in Discourse. and other similar questions in Discouse and here didn't get a solution. I think this is a bug , it need to be fixed ...

Please follow the guidelines for reaching for support and use discourse.

**Comment by lissyx** [comment]
> word = '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94'

I'm no mandarin speaker but this looks as valid utf8 for that lang. 

> UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-15: surrogates not allowed

This sounds more of a python / utf8 / Windows issue.

**Comment by lissyx** [comment]
Since you dont care about sharing requested infos i can only speculate on the code you wrote but this seems to be your issue and valid solution https://stackoverflow.com/a/62935174

**Comment by wingdi** [comment]
> Since you dont care about sharing requested infos i can only speculate on the code you wrote but this seems to be your issue and valid solution https://stackoverflow.com/a/62935174

Thanks for your reply
`word = '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94'`,  
this is invalid to transcode to mandarin .

 https://stackoverflow.com/a/62935174, this link don't give a solution.\

**Comment by lissyx** [comment]
> > Since you dont care about sharing requested infos i can only speculate on the code you wrote but this seems to be your issue and valid solution https://stackoverflow.com/a/62935174
> 
> Thanks for your reply
> `word = '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94'`,
> this is invalid to transcode to mandarin .

As I said, I'm no speaker, but this looks to be a valid python string.

> 
> https://stackoverflow.com/a/62935174, this link don't give a solution.\

Again, please use Discourse.

**Comment by lissyx** [comment]
> > > > Since you dont care about sharing requested infos i can only speculate on the code you wrote but this seems to be your issue and valid solution https://stackoverflow.com/a/62935174
> > > 
> > > 
> > > Thanks for your reply
> > > `word = '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94'`,
> > > this is invalid to transcode to mandarin .
> > 
> > 
> > As I said, I'm no speaker, but this looks to be a valid python string.
> > > https://stackoverflow.com/a/62935174, this link don't give a solution.\
> > 
> > 
> > Again, please use Discourse.
> 
> I am almost pretty sure '\udce5\udcb8\udce5\udce5\udcb9\udcb3\udce6\udcba\udca6\udce5\udc8f\udce6\udcb1\udc89\udce5\udc94' not valid.
> this mandarin encode range using Unicode ：
> ![Unicode-中文编码范围](https://user-images.githubusercontent.com/25787391/111334531-978d8d80-86ae-11eb-8e73-e53ab0add7b3.png)
> 
> thanks.

Maybe. But until you follow the discourse steps to reach for support https://discourse.mozilla.org/t/what-and-how-to-report-if-you-need-support/62071:
 - we don't know what you did,
 - we don't know how you did,
 - other people have reported successfully using the mandarin model,
 - this is provided as experimental,

There's basically nothing I can do to help. Please follow the steps on Discourse.
