### ISSUE TITLE
 Could not find a version that satisfies the requirement ds_ctcdecoder==0.9.3 

### ISSUE THREAD

**Issue by allsoppn** [mozilla/DeepSpeech#3565]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubunti 18.04
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 3.0.1
- **GCC/Compiler version (if compiling from source)**:7.5.0
- **CUDA/cuDNN version**:10.2
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

I'm trying to build DeepSpeech v0.9.3 using the guide at:
https://deepspeech.readthedocs.io/en/v0.9.3/TRAINING.html#

Whilst building the code in the python virtual environment I get the following error:

Collecting pandas
  Using cached pandas-1.1.5-cp36-cp36m-manylinux2014_aarch64.whl (9.5 MB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting numba==0.47.0
  Using cached numba-0.47.0.tar.gz (1.9 MB)
Collecting llvmlite==0.31.0
  Using cached llvmlite-0.31.0.tar.gz (110 kB)
Collecting librosa
  Using cached librosa-0.8.0.tar.gz (183 kB)
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement ds_ctcdecoder==0.9.3 (from deepspeech-training==0.9.3) (from versions: none)

It seem the file ds_ctcdecoder-0.9.3-p36-cp36m-manylinux2014_aarch64.whl or ds_ctcdecoder-0.9.3-py2.py3-none-any.whl is missing from the distribution

**Comment by ftyers** [comment]
This looks like a support request. Best to use [Discourse](https://discourse.mozilla.org/c/deepspeech) or on [GitHub Discussions](https://github.com/coqui-ai/STT/discussions).

**Comment by lissyx** [comment]
> It seem the file ds_ctcdecoder-0.9.3-p36-cp36m-manylinux2014_aarch64.whl or ds_ctcdecoder-0.9.3-py2.py3-none-any.whl is missing from the distribution

We dont support those platforms for this package. As @ftyers said have à look at Discourse some contributors shared steps to build it
