### ISSUE TITLE
why first_bytes plus one in path_trie.cpp

### ISSUE THREAD

**Issue by zh794390558** [mozilla/DeepSpeech#3566]
https://github.com/mozilla/DeepSpeech/blob/f2e9c85880dff94115ab510cde9ca4af7ee51c19/native_client/ctcdecode/path_trie.cpp#L133

**Comment by ftyers** [comment]
Hi @zh794390558 ! This looks like a support request. Best to use [Discourse](https://discourse.mozilla.org/c/deepspeech) or on [GitHub Discussions](https://github.com/coqui-ai/STT/discussions). :)
