### ISSUE TITLE
LM score error

### ISSUE THREAD

**Issue by zh794390558** [mozilla/DeepSpeech#3568]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

https://github.com/mozilla/DeepSpeech/blob/master/native_client/ctcdecode/ctc_beam_search_decoder.cpp#L234

```
if (prefix_boundary && ext_scorer_->is_scoring_boundary(prefix_boundary, prefix->character)) {
        ...
        std::vector<std::string> ngram = ext_scorer_->make_ngram(prefix_boundary);
        ...
      }
```

**Comment by lissyx** [comment]
@zh794390558 You keep opening issues without giving any context: this is spamming. Either file a real issue or stop.
