### ISSUE TITLE
Bug: invalidating `feature_cache` calls non-existent method `gfile.remove_remote()`, halts execution

### ISSUE THREAD

**Issue by KathyReid** [mozilla/DeepSpeech#3569]
## Templated information

* Custom code - no, I am working in a Docker environment that was PULL'd from `mozilla/deepspeech:v0.9.3`
* OS Platform and distribution - Ubuntu 20.04 LTS 
* TensorFlow - 1.15 as per the training Docker image
* Python - 3.6 as per the training Docker image 
* Bazel - n/a
* GCC - n/a
* CUDA / cuDNN version - as per the training Docker imaGe 
* GPU model - NVIDIA RTX 2060, 6GB RAM

## Steps to reproduce 

* Specify a `feature_cache` location and run training (ie with augmentation) 
* When the training epochs reaches the `--cache_for_epochs N` limit, the `feature_cache` will be invalidated
* This reliably triggers the following error: 
```
I Invalidating feature cache
Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/DeepSpeech/training/deepspeech_training/train.py", line 982, in run_script
    absl.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/DeepSpeech/training/deepspeech_training/train.py", line 954, in main
    train()
  File "/DeepSpeech/training/deepspeech_training/train.py", line 607, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "/DeepSpeech/training/deepspeech_training/train.py", line 546, in run_set
    remove_remote(feature_cache_index)  # this will let TF also overwrite the related cache data files
  File "/DeepSpeech/training/deepspeech_training/util/io.py", line 81, in remove_remote
    return gfile.remove_remote(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.io.gfile' has no attribute 'remove_remote'
``` 
Digging into the `io.py` file, I noticed the following code: 
https://github.com/mozilla/DeepSpeech/blob/cf16afafe9519259b2a6e6df93d1551c59e9f207/training/deepspeech_training/util/io.py#L81

```
return gfile.remove_remote(filename)
```

Looking at the `tf` reference: 
https://www.tensorflow.org/api_docs/python/tf/compat/v1/gfile/Remove

there is no `remove_remote()` method on the `gfile` object. 

I resolved this by replacing: 

```
return gfile.remove_remote(filename)
```

with 

```
return gfile.remove(filename)
```

in `io.py`

and this resolved the error. 

Happy to raise a PR for this.

**Comment by lissyx** [comment]
> Happy to raise a PR for this.

yes, please

**Comment by lissyx** [comment]
@KathyReid please make two PRs, one against r0.9 and one against master

**Comment by lissyx** [comment]
> @KathyReid please make two PRs, one against r0.9 and one against master

Make sure you push to a branch on your fork, and open a PR against this repo. I gave you creds so you should be able to trigger  taskcluster yourself (while we still rely on it for a few days)

**Comment by KathyReid** [comment]
Noted with thanks, leave this with me, bed time now, but will get to it in about 24 hours.

**Comment by KathyReid** [comment]
* #3570 raised for `r0.9` branch 
* #3571 raised for `master` branch
