### ISSUE TITLE
Port Set NUMPY min versions to GitHub Actions

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3586]
We had code on TaskCluster to set proper numpy versions to avoid:
 - pulling unsupported numpy requiring building from source
 - ensuring proper binary compat at runtime

It should be quite an easy task:
 - port the code (can be a `composite` action)
 - I think using action's inputs/outputs mechanism should be enough

https://github.com/mozilla/DeepSpeech/blob/d8fa9e7b60709c80ccd66950c09911dae4bd83a3/taskcluster/tc-py-utils.sh#L194-L274

**Comment by Ayushsunny** [comment]
Hello @lissyx I would like to work on this issue

**Comment by lissyx** [comment]
> Hello @lissyx I would like to work on this issue

Feel free to have a look at the code and propose a PR, or ask questions!

**Comment by Ayushsunny** [comment]
> @Ayushsunny Are you hacking on it? Do you have questions?

Yes, I'm trying to understand Sir

**Comment by Ayushsunny** [comment]
Hello @lissyx , So I have to change the NUMPY version here?

**Comment by lissyx** [comment]
> Hello @lissyx , So I have to change the NUMPY version here?

no, we have the code I linked, which was used on taskcluster, the goal of the issue is to replicate the behavior for GitHub Actions

**Comment by lissyx** [comment]
@Ayushsunny We would need this shell code to be ported as an action being used in this job: https://github.com/mozilla/DeepSpeech/blob/5f566f442541d76f320ee081294cdef980c361d1/.github/workflows/macOS-amd64.yml#L243-L285

You could make it in JS https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action or I think a simple Composite action can be enough https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

We already have a few composite actions, look under `.github/actions`.

As you can see, existing bash code sets some env variables. For using as GitHub Actions, we would rely on the Inputs/Outputs mechanism to pass the correct values as `NUMPY_BUILD_VERSION` and `NUMPY_DEP_VERSION`.

**Comment by lissyx** [comment]
@Ayushsunny One example of a composite action setting an output value can be seen at https://github.com/mozilla/DeepSpeech/blob/5f566f442541d76f320ee081294cdef980c361d1/.github/actions/get_cache_key/action.yml and it is used https://github.com/mozilla/DeepSpeech/blob/5f566f442541d76f320ee081294cdef980c361d1/.github/workflows/macOS-amd64.yml#L154-L171

**Comment by lissyx** [comment]
@Ayushsunny Is it clear to you? Do you think you have all the infos? It's fine if you feel you need more infos, just dig into the code, hack and ask! :)

**Comment by Ayushsunny** [comment]
> @Ayushsunny Is it clear to you? Do you think you have all the infos? It's fine if you feel you need more infos, just dig into the code, hack and ask! :)

Sorry @lissyx Sir I'm not able to understand this as these things are new to me, but I really want to solve this issue to learn, So Please help me sir I want to contribute.

**Comment by lissyx** [comment]
> > @Ayushsunny Is it clear to you? Do you think you have all the infos? It's fine if you feel you need more infos, just dig into the code, hack and ask! :)
> 
> Sorry @lissyx Sir I'm not able to understand this as these things are new to me, but I really want to solve this issue to learn, So Please help me sir I want to contribute.

Well it's fine if you can't work on this one, you can find many others: https://github.com/mozilla/DeepSpeech/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22

**Comment by lissyx** [comment]
@Ayushsunny If it can help you get a better understanding, here is my PR: https://github.com/mozilla/DeepSpeech/pull/3598
