### ISSUE TITLE
Error when executing bin/import_cv2.py

### ISSUE THREAD

**Issue by rook86** [mozilla/DeepSpeech#3588]
I am following https://deepspeech.readthedocs.io/en/v0.7.4/TRAINING.html#installing-deepspeech-training-code-and-its-dependencies
But, error message ModuleNotFoundError: No module named 'deepspeech_training' appears when executing bin/import_cv2.py
How do I solve this problem?

**Comment by lissyx** [comment]
Please read the documentation and reach for support on Discourse.

**Comment by lissyx** [comment]
And use matching tag.
