### ISSUE TITLE
Compare GRU's vs Current LSTM's

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#361]

**Comment by andi4191** [comment]
GRU Cell Results:

Dataset Used: TED
Number of GPU instances: 4

I FINISHED Optimization - **training time: 8:13:07**
I Test of Epoch 10 - WER: 0.530035, loss: 94.745821317, mean edit distance: 0.254709
I --------------------------------------------------------------------------------
I WER: 0.200000, loss: 5.857036, mean edit distance: 0.050000
I  - src: "to do that dont look"
I  - res: "o do that dont look"
I --------------------------------------------------------------------------------
I WER: 0.333333, loss: 4.066966, mean edit distance: 0.111111
I  - src: "and i say"
I  - res: "and i saw"
I --------------------------------------------------------------------------------
I WER: 0.333333, loss: 4.303623, mean edit distance: 0.090909
I  - src: "yes he said"
I  - res: "yes the said"
I --------------------------------------------------------------------------------
I WER: 0.333333, loss: 5.691000, mean edit distance: 0.222222
I  - src: "and i say"
I  - res: "and i save"
I --------------------------------------------------------------------------------
I WER: 0.500000, loss: 4.931426, mean edit distance: 0.285714
I  - src: "sort of"
I  - res: "sort a"
I --------------------------------------------------------------------------------
I WER: 0.500000, loss: 5.437888, mean edit distance: 0.133333
I  - src: "not intensively"
I  - res: "not intensely"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 1.898744, mean edit distance: 0.333333
I  - src: "and"
I  - res: "nd"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 2.118078, mean edit distance: 0.500000
I  - src: "so"
I  - res: "of"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 2.586474, mean edit distance: 0.500000
I  - src: "so"
I  - res: "o"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 3.953010, mean edit distance: 0.500000
I  - src: "so"
I  - res: "o"
I --------------------------------------------------------------------------------

**Current LSTM cell architecture:**

I FINISHED Optimization - **training time: 1:44:32**
I Test of Epoch 10 - WER: 0.415028, loss: 75.5818332566, mean edit distance: 0.196590
I --------------------------------------------------------------------------------
I WER: 0.166667, loss: 3.768760, mean edit distance: 0.035714
I  - src: "and treating them so i think"
I  - res: "and treating them so i thank"
I --------------------------------------------------------------------------------
I WER: 0.333333, loss: 2.177231, mean edit distance: 0.076923
I  - src: "no im serious"
I  - res: "now im serious"
I --------------------------------------------------------------------------------
I WER: 0.333333, loss: 2.362657, mean edit distance: 0.076923
I  - src: "no im serious"
I  - res: "now im serious"
I --------------------------------------------------------------------------------
I WER: 0.400000, loss: 3.249178, mean edit distance: 0.090909
I  - src: "its such a rich system"
I  - res: "it such a ric system"
I --------------------------------------------------------------------------------
I WER: 0.500000, loss: 2.693307, mean edit distance: 0.090909
I  - src: "were lovers"
I  - res: "where lovers"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 1.175059, mean edit distance: 0.500000
I  - src: "so"
I  - res: "o"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 1.413706, mean edit distance: 0.500000
I  - src: "so"
I  - res: "o"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 1.456704, mean edit distance: 0.333333
I  - src: "and"
I  - res: "nd"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 2.545368, mean edit distance: 0.500000
I  - src: "okay"
I  - res: "ka"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 2.734726, mean edit distance: 0.333333
I  - src: "and"
I  - res: "nd"
I --------------------------------------------------------------------------------
