### ISSUE TITLE
alphabet file related to the checkpoint, deepspeech-0.9.3-checkpoint-zh-CN.tar.gz

### ISSUE THREAD

**Issue by wuchaowei2012** [mozilla/DeepSpeech#3616]
I want to continue to train a model from the pretrained Mandarin checkpoint,  However, I can not get the alphabet file corresponding to the checkpoint. 

The Mandarin checkpoint is from https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3.
With name as:
- ** deepspeech-0.9.3-checkpoint-zh-CN.tar.gz

**Comment by ftyers** [comment]
This looks like a supoort request so you should check out Discourse or [STT Discussions](https://github.com/coqui-ai/STT/discussions), but afaik Mandarin is based on the bytes-only mode so you don't need an alphabet file.

**Comment by lissyx** [comment]
@wuchaowei2012 Mandarin model is using Byte output mode, so you don't need an alphabet.
