### ISSUE TITLE
Can't recognize my words

### ISSUE THREAD

**Issue by ananas-hebo** [mozilla/DeepSpeech#3637]
input wav file:
[s1.wav.zip](https://github.com/mozilla/DeepSpeech/files/6376830/s1.wav.zip)

model_file = 'deepspeech-0.9.3-models.pbmm'
scorer_file = 'deepspeech-0.9.3-models.scorer'

-------

output:
```
{
  "transcripts": [
    {
      "confidence": -17.701541900634766,
      "words": [
        {
          "word": "i",
          "start_time": 3.76,
          "duration": 0.0
        }
      ]
    }
  ]
}
```
something wrong with me?

**Comment by lissyx** [comment]
Please use Discourse for support.
