### ISSUE TITLE
Add https://pypi.org/project/transcribe-anything/ to demos

### ISSUE THREAD

**Issue by zackees** [mozilla/DeepSpeech#3644]
Hi there - I created an easy transcription service based on deepspeech. It's vastly easier to use than anything else out there, IMO.

Check it out:
https://pypi.org/project/transcribe-anything/

I would like to propose that this be included in your examples page. Thank you.

**Comment by ftyers** [comment]
Sounds good, you should open at issue at [DeepSpeech-examples](https://github.com/mozilla/DeepSpeech-examples/issues) :)
