### ISSUE TITLE
MinimumIOSVersion 13.5

### ISSUE THREAD

**Issue by erksch** [mozilla/DeepSpeech#3646]
Hey there! 

If you take the [deepspeech iOS framework from the 0.9.3 taskcluster tag](https://community-tc.services.mozilla.com/tasks/JuU2kE0eRfCLkRX8-oMzvg), you can see in `Info.plist` that the `MinimumIOSVersion` is set to 13.5 and you can also see it in the [deepspeech_ios project file](https://github.com/mozilla/DeepSpeech/blob/5f566f442541d76f320ee081294cdef980c361d1/native_client/swift/deepspeech_ios.xcodeproj/project.pbxproj#L295), I read something about it [in this PR](https://github.com/mozilla/DeepSpeech/pull/3436#discussion_r530860681). But in the [deepspeech_ios.podspec](https://github.com/mozilla/DeepSpeech/blob/master/native_client/swift/deepspeech-ios.podspec#L12) it is 0.9.

Is the 13.5 still intended? 

From [this comment](https://github.com/mozilla/DeepSpeech/pull/3436#discussion_r535800004) it seems that the framework itself does not need to be that low:
>  OK, I think on second look and test, 9.0 actually works here. At this stage, we're not using any audio libraries yet -- that comes in through the example app, so 9.0 should be good.

**Comment by ftyers** [comment]
See #3693
