### ISSUE TITLE
python version has illegal instruction (at least on m1 macs)

### ISSUE THREAD

**Issue by alok** [mozilla/DeepSpeech#3648]
I'm running on an M1 Macbook pro. I did `pipx install deepspeech`, and running the binary with no args gave: `[1]    65156 illegal hardware instruction  deepspeech`

**Comment by lissyx** [comment]
Not a supported platform.

**Comment by Alatius** [comment]
Well, are there any plans on supporting M1 officialy? Or has anyone from the community tried to recompile it for M1?

**Comment by ftyers** [comment]
@Alatius see #3693.
