### ISSUE TITLE
Run code with warp-ctc

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#365]
As the current code is relatively stable, we should re-introduce warp-ctc for a performance boost.

**Comment by striki70** [comment]
But warp-ctc is not working. Can you confirm this?

**Comment by kdavis-mozilla** [comment]
Our fork of tensorflow contains a branch with warp-ctc integrated[[1](https://github.com/mozilla/tensorflow/tree/warpctc)].

This branch has worked in the past. I'd assume it works now.

However, over the last couple of weeks we've had server problems and switched back to release versions of tensorflow to eliminate one variable from our debug work. Once the debug work is done we'll switch back to tensorflow with warp-ctc for a performance boost.

**Comment by striki70** [comment]
Does version that is currently available work properly with warp-ctc?

**Comment by kdavis-mozilla** [comment]
@striki70 We haven't tested it recently. But it should work. 

We have a TensorFlow fork/branch [v1.0.0-warpctc](https://github.com/mozilla/tensorflow/tree/v1.0.0-warpctc) that has warp-ctc integrated in to TensorFlow.

In addition we have a flag [`use_warpctc`](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L49) that can be used make our code use warp-ctc.

One can turn on the flag and test.

**Comment by striki70** [comment]
No it doesn't work:
Traceback (most recent call last):
...
total_loss = tf.contrib.warpctc.warp_ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
AttributeError: 'module' object has no attribute 'warpctc'

**Comment by kdavis-mozilla** [comment]
Are you using a tensorflow version compiled from the fork/branch [v1.0.0-warpctc](https://github.com/mozilla/tensorflow/tree/v1.0.0-warpctc)?

**Comment by striki70** [comment]
According to installation instructions installing this is done by pip install tensorflow-gpu, and I did that already. 

    On Tuesday, March 7, 2017 2:41 PM, Kelly Davis <notifications@github.com> wrote:
 

 Are you using a tensorflow version compiled from the fork/branch v1.0.0-warpctc?—

**Comment by kdavis-mozilla** [comment]
The installation instructions are for the standard use case, using the ctc algorithm that's part of Tensorflow not using the warp-ctc ctc algorithm.

Using warp-ctc is special, as it's not part of TensorFlow. So, to use it one has to use our fork/branch [v1.0.0-warpctc](https://github.com/mozilla/tensorflow/tree/v1.0.0-warpctc) of Tensorflow which has the warp-ctc ctc algorithm integrated.

We did not include instructions for using the warp-ctc ctc algorithm as its experimental and much more difficult to install, one has to compile Tensorflow from source. We wanted the instructions to be as simply as possible, to get people up and running with no friction.

**Comment by lissyx** [comment]
Moreover, this is documented in README.Mozilla.md: https://github.com/mozilla/tensorflow/blob/v1.0.0-warpctc/README.Mozilla.md#taskcluster-built-pip-packages

Please note that I ran into strange segfault sometimes when using the package (problem I did not face with previous builds of master), and I had no time to investigate why so far.

**Comment by lissyx** [comment]
It looks like my doc is broken, proper direct link for v1.0.0 should be: https://tools.taskcluster.net/index/artifacts/#project.deepspeech.tensorflow.pip.v1.0.0-warpctc/project.deepspeech.tensorflow.pip.v1.0.0-warpctc.gpu

**Comment by striki70** [comment]
That worked. Thnx for support.

**Comment by kdavis-mozilla** [comment]
Welcome
