### ISSUE TITLE
How to Run DeepSpeech On a non AVX CPU ?

### ISSUE THREAD

**Issue by Karim-Fadi** [mozilla/DeepSpeech#3653]
I have tried to run an example of Deep Speech on an old laptop without AVX Support and as i have expected, i got "illegal instruction (core dumped)" error, as TensorFlow requires it. So this is kind of a question and a feature request in the same time. How does Deep Speech run on a Raspberry Pi 4 which uses an Arm CPU (100% doesn't support AVX). And Can i run it on a non AVX CPU somehow ?

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Your Builds
- **TensorFlow version (use command below)**: 2.5.0
- **Python version**: 3.9.5
- **Bazel version (if compiling from source)**: Not Compiling from Source
- **GCC/Compiler version (if compiling from source)**: Not Compiling from Source
- **CUDA/cuDNN version**: No CUDA
- **GPU model and memory**: Intel HD Graphics 3000
- **Exact command to reproduce**: Not a problem.

**Comment by lissyx** [comment]
This is a support request, please use Discourse.

**Comment by lissyx** [comment]
> How does Deep Speech run on a Raspberry Pi 4 which uses an Arm CPU (100% doesn't support AVX).

Your question does not even make any sense ; it's not the same code that is being ran by `libdeepspeech.so` on ARM CPUs than on Intel/AMD x86-64 CPUs.

As documented, AVX is required for the prebuilt binaries, for performance reasons. Chances are if you CPU does not support AVX it's anyway too slow to perform decently on this task, but you can always rebuild.

Next time:
 - read the doc
 - read the code
 - ask for support on discourse
