### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Karim-Fadi** [mozilla/DeepSpeech#3654]
I have installed deepspeech as described and whenever i run an example i get the error above and i have tried with both, the standard pbmm and the tflite models, in case my PC don’t support AVX. And in either case i get the same error, so how is that ? Is this a bug ?

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Don’t have tensorflow. (Is it a requirement? ). It is not mentioned in the docs.
- **TensorFlow version (use command below)**: Don’t have TensorFlow
- **Python version**: 3.9.5
- **Bazel version (if compiling from source)**: Not compiling from Source
- **GCC/Compiler version (if compiling from source)**: Not compiling from source.
- **CUDA/cuDNN version**: No CUDA
- **GPU model and memory**: Intel HD 4000, 128 of memory
- **Exact command to reproduce**: Try doing the same thing on a relatively underpowered machine like Raspberry Pi 4.

**Comment by lissyx** [comment]
Second time you are purposedly not opening a support request on Discourse but on Github.

**Comment by lissyx** [comment]
> in case my PC don’t support AVX

You will have to rebuild `libdeepspeech.so`, it is documented our binaries requires it. Performances cannot be the same without AVX.
