### ISSUE TITLE
Colab Notebook for online Japanese TTS?

### ISSUE THREAD

**Issue by krigeta** [mozilla/DeepSpeech#3658]
Hello, is there any colab version available for text to speech in Japanese or multiple languages?

**Comment by lissyx** [comment]
Please use Discourse for reaching support.

**Comment by krigeta** [comment]
May you please give me a link for that?

**Comment by lissyx** [comment]
> May you please give me a link for that?

It is the first item you have when you file a new issue.

**Comment by lissyx** [comment]
https://discourse.mozilla.org/c/deepspeech
