### ISSUE TITLE
build native client error

### ISSUE THREAD

**Issue by oftenliu** [mozilla/DeepSpeech#3662]
OS Platform and Distribution : Linux 
TensorFlow installed from (our builds, or upstream TensorFlow): tensorflow 1.15
deepspeech:0.90
TensorFlow source code version (use command below): deepspeech'submodule,2.3
Python version: Python 3.6.9
Bazel version (if compiling from source): Bazel 0.230
GCC/Compiler version (if compiling from source): gcc 7.5.0
CUDA/cuDNN version: N/A
GPU model and memory: N/A

bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_scorer_package

returns an error

ERROR: Skipping '//native_client:libdeepspeech.so': error loading package 'native_client': Unable to load package for '@com_github_nelhage_rules_boost//:boost/boost.bzl': The repository could not be resolved
ERROR: error loading package 'native_client': Unable to load package for '@com_github_nelhage_rules_boost//:boost/boost.bzl': The repository could not be resolved

**Comment by lissyx** [comment]
Please use Discourse for support.

**Comment by Geremia** [comment]
@lissyx This looks like [nelhage/rules_boost issue #186](https://github.com/nelhage/rules_boost/issues/186). I get this
```
ERROR: Skipping '//native_client:libdeepspeech.so': error loading package 'native_client': Unable to find package for @com_github_nelhage_rules_boost//:boost/boost.bzl: The repository '@com_github_nelhage_rules_boost' could not be resolved.
```
issue with Bazel release 3.7.2, too.

**Comment by lissyx** [comment]
> @lissyx This looks like [nelhage/rules_boost issue #186](https://github.com/nelhage/rules_boost/issues/186). I get this
> 
> ```
> ERROR: Skipping '//native_client:libdeepspeech.so': error loading package 'native_client': Unable to find package for @com_github_nelhage_rules_boost//:boost/boost.bzl: The repository '@com_github_nelhage_rules_boost' could not be resolved.
> ```
> 
> issue with Bazel release 3.7.2, too.

I'm not sure bazel 3.7.2 is a supported release for the version of tensorflow targetted

**Comment by Geremia** [comment]
@lissyx True. [#tested_build_configurations](https://www.tensorflow.org/install/source?hl=sv#tested_build_configurations) and [DeepSpeech docs](https://deepspeech.readthedocs.io/en/r0.9/BUILDING.html) indeed say Bazel 3.1.0 for tensorflow-2.4.0.
🙏

**Comment by lissyx** [comment]
Any reason why you would need another version ? Because removing those rules will break for other's.
