### ISSUE TITLE
Single keyword recognition on Android

### ISSUE THREAD

**Issue by bloodcarter** [mozilla/DeepSpeech#367]
Hi, is it possible to train DeepSpeech to recognize only one keyword and make in run the model win Android Tensorflow lib ? I suppose this task is just a binary classification task. Any suggestions?

**Comment by kdavis-mozilla** [comment]
We haven't done this yet. However it's something we have been thinking about doing and will likely do in the future.

One place with might be a nice place to start for some of this is the recent article [An End-to-End Architecture for Keyword Spotting and Voice Activity Detection](https://arxiv.org/abs/1611.09405) which covers how to use a "DeepSpeech like architecture" to do keyword spotting and VAD.

**Comment by bloodcarter** [comment]
@kdavis-mozilla Hmm...looks like I can use kitty.ai here. But please, keep us posted here on this!

**Comment by kdavis-mozilla** [comment]
I think we're not going to pursue this now. However, the code can generally be re-appropriated for such a use without much work by anyone who's interested in doing so.
