### ISSUE TITLE
error: 'numeric_limits' is not a member of 'std'

### ISSUE THREAD

**Issue by lw64** [mozilla/DeepSpeech#3670]
Error when building deespeech. The full log:

```
ERROR: /home/lorenz/.cache/bazel/_bazel_lorenz/eeb30bcc94cc480fee5070ff982fe22d/external/com_google_absl/absl/synchronization/BUILD.bazel:30:11: C++ compilation of rule '@com_google_absl//absl/synchronization:graphcycles_internal' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 43 argument(s) skipped)
external/com_google_absl/absl/synchronization/internal/graphcycles.cc: In member function 'void absl::lts_2020_02_25::synchronization_internal::GraphCycles::RemoveNode(void*)':
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:26: error: 'numeric_limits' is not a member of 'std'
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before '>' token
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:52: error: '::max' has not been declared; did you mean 'std::max'?
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/algorithm:62,
                 from external/com_google_absl/absl/synchronization/internal/graphcycles.cc:38:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/stl_algo.h:3467:5: note: 'std::max' declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
Target //native_client:libdeepspeech.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

gcc version: 11.1.0

For me it built successfully, when adding `#include <limits>` to `tensorflow/bazel-tensorflow/external/com_google_absl/absl/synchronization/internal/graphcycles.cc`

This is a bug in the abseil library which is a dependency of gRPC which is a dependency of bazel.

But bazel 3.1 is very outdated now. All these bugs have been fixed upstream.

The only "clean" solution in my opinion would be to use the newer bazel version, but then also a newer tensorflow version would be probably be needed and maybe that would also break deepspeech.

**Comment by lissyx** [comment]
Use older gcc version, or send PR for tensorflow.

**Comment by lw64** [comment]
What PR?

**Comment by lissyx** [comment]
> What PR?

Since you seems to have a workaround, maybe you can share it?

**Comment by lissyx** [comment]
https://github.com/mozilla/tensorflow/tree/r2.4

**Comment by lw64** [comment]
yeah, but the workaround is not in a file in mozilla/tensorflow, but in a file from a package automatically downloaded from bazel. (abseil)

**Comment by lissyx** [comment]
> yeah, but the workaround is not in a file in mozilla/tensorflow, but in a file from a package automatically downloaded from bazel. (abseil)

That's not a problem: https://github.com/mozilla/tensorflow/blob/r2.4/tensorflow/workspace.bzl#L188

**Comment by lw64** [comment]
could that line then be `patch_file = [clean_dep("//third_party:com_google_absl_fix_mac_and_nvcc_build.patch"), path_to_this_patch"],` ?

**Comment by lw64** [comment]
and where should the patch be stored?

**Comment by lw64** [comment]
tf_http_archive() only accepts one patch. should then the existing merged with the new one?

**Comment by lw64** [comment]
Question:

I checkout absl with commit df3ea785d8c30a9503321a3d35ee7d35808f190d. It is in this line

https://github.com/mozilla/tensorflow/blob/r2.4/tensorflow/workspace.bzl#L192

But when I apply the patch in tensorflow/third_party/com_google_absl_fix_mac_and_nvcc_build.patch it says error in line 135.

**Comment by lissyx** [comment]
I'm sorry, but I am not working on that project anymore, and I don't have time to investigate that.

**Comment by lw64** [comment]
thanks for the advices, maybe someone else can help me solve this?

**Comment by lw64** [comment]
This issue relates to the version pulled in from deepspeech v0.9.3. So there are already more up to date branches. For 0.9.3 the solution would be then to compile with gcc10.
