### ISSUE TITLE
How I execute convert_graphdef_memmapped_format

### ISSUE THREAD

**Issue by luis-vera** [mozilla/DeepSpeech#3671]
Hi everybody:

I want you to tell that I downloaded **convert_graphdef_memmapped_format** using taskcluster.py as you mentioned in documentation. I trainned my own model and I got my PB file. Th problem is trying to convert it in PBMM file. 

I tried on Centos as you indicate in documentarion, this is:

**convert_graphdef_memmapped_format --in_graph=output_graph.pb --out_graph=output_graph.pbmm**

But the error message was:

**[root@SErverTest Documentos]# convert_graphdef_memmapped_format output_graph.pb
-bash: convert_graphdef_memmapped_format: no se encontró la orden**

**[root@SErverTest Documentos]# bash convert_graphdef_memmapped_format --in_graph=output_graph.pb --out_graph=output_graph.pbmm
convert_graphdef_memmapped_format: convert_graphdef_memmapped_format: no se puede ejecutar el fichero binario**

I tried the same step on Windows 10 but the problem was the same:

**"convert_graphdef_memmapped_format" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.**

How can I execute this program for getting the PBMM model file?

Thank's a lot for your help

**Comment by lissyx** [comment]
Please use Discourse for support, this is not a bug.
