### ISSUE TITLE
Error System.AccessViolationException on inference from .NET

### ISSUE THREAD

**Issue by Henderz** [mozilla/DeepSpeech#3684]
Error on Inference (not training)
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:NA
- **TensorFlow version (use command below)**:NA
- **Python version**: NA
- **Bazel version (if compiling from source)**:NA
- **GCC/Compiler version (if compiling from source)**:NA
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**: objDeepSpeech.IntermediateDecodeWithMetadata(objStream, 1);

Bug?
===

I am using DeepSpeech for inference from microphone stream captured via CSCore audio module. I have custom code for VAD and get Intermediate decoding done to get sentence wise live transcription. 

Models: 9.0.3 Pre-Trained English Audio Model and custom Scorers with the same hyper-parameters as the Pre-Trained Scorer.

This works but at random times I get 

StackOverflowException 
from objDeepSpeech.FeedAudioContent(objStream, buffers, Convert.ToUInt32(buffers.Length));
or
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
from objDeepSpeech.IntermediateDecodeWithMetadata(objStream, 1);

The errors originate from within libdeepspeech.so so I am not able to debug any further. Any help is much appreciated. Thanks.

**Comment by ftyers** [comment]
See #3693
