### ISSUE TITLE
.sttWithMetadata() produces inaccurate token timings

### ISSUE THREAD

**Issue by nikola-ctx** [mozilla/DeepSpeech#3687]
When transcribing audio (.wav, 16KHz) using DeepSpeech's sttWithMetadata method, I get inaccurate token start_time values. If compared against the actual waveform in tools such as Audacity, the DeepSpeech timings are invariably late/wrong.
Here's the code I use to generate the metadata/transcription (deepspeech version 0.9.3):

```
import deepspeech
from scipy.io import wavfile

model_path = "deepspeech-0.9.3-models.pbmm"
scorer_path = "deepspeech-0.9.3-models.scorer"
ds_model = deepspeech.Model(model_path)
ds_model.enableExternalScorer(scorer_path)

sr, audio_signal = wavfile.read("some_audio.wav")
metadata = ds_model.sttWithMetadata(audio_signal)
```

**Comment by ftyers** [comment]
See #3693
