### ISSUE TITLE
Convert checkpoint to pb file 

### ISSUE THREAD

**Issue by lfgogogo** [mozilla/DeepSpeech#3688]
I am using the v0.9.3 checkpoint to get the pb file.
I have done this by command:
python3 DeepSpeech.py --checkpoint_dir ../deepspeech-0.9.3-checkpoint-zh-CN --export_dir ../
But got a error:
ValueError: Cannot feed value of shape (256,) for Tensor 'layer_6/bias/Initializer/zeros:0', which has shape '(29,)'
Error happends when loading the checkpoint using utils/checkpoint.py.However,i can make it when using deepspeech-0.9.3-checkpoint,not the -zh-CN version.

I install the env using pip3 install -e . in the DeepSpeech folder
OS Platform and Distribution:Linux Ubuntu 18
TensorFlow version:1.15.4
Python version:3.7.11

**Comment by lissyx** [comment]
Please use Discourse for support and read the doc.

**Comment by Moon0316** [comment]
hello, I face the same problem, have you solved it?
