### ISSUE TITLE
Support Python 3.9 on Linux / ARMv7l

### ISSUE THREAD

**Issue by Quiterion** [mozilla/DeepSpeech#3689]
Currently there's no supported pypi wheel for Linux / ARMv7l systems with Python 3.9 bindings. This makes DeepSpeech binaries unavailable for Raspberry 3 Arch Linux systems.

**Comment by lissyx** [comment]
We only provided support for latest Raspbian, if it is running elsewhere it's nice but not enforced. Please send PR for adding new python versions.
