### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [mozilla/DeepSpeech#3691]
Aarch64 wheel for python version 3.7 is getting built on GHA. It looks that the wheel is released successfully in [GitHub](https://github.com/mozilla/DeepSpeech/releases), but not on Pypi. 

@lissyx and Team Since Aarch64 is now supported by PyPI, it would be really helpful if you could upload Aarch64 wheels on PyPI as well.

**Comment by lissyx** [comment]
@odidev Please avoid spamming issues, I have already replied to you in https://github.com/mozilla/DeepSpeech/issues/3521#issuecomment-929978075.

**Comment by ftyers** [comment]
See #3693
