### ISSUE TITLE
Roadmap for Upgrading to TensorFlow 2.X ?

### ISSUE THREAD

**Issue by tim5go** [mozilla/DeepSpeech#3692]
I understand this question has been asked for many times:
* #2709
* #2506
* #2697

But I would like to raise it again given that TF 1.15 is not an option for me in production environment as there're plenty of vulnerabilities found in the older version of TF:

https://snyk.io/vuln/pip:tensorflow

I know that the upgrade may not bring any actual improvement in terms of model accuracy or model training time.
But the terrible vulnerabilities found in TF 1.X will prevent others like me from using your framework from a security perspective.

Would your team re-consider planning an upgrade hopefully in the near future?

**Comment by lissyx** [comment]
Inference on client side is already based on TensorFlow r2.4. Only training is stuck at r1.15. Please understand nobody is actively working on the codebase anymore. Feel free to send patches for supporting training on r2.x branches.

**Comment by tim5go** [comment]
@lissyx 
Understood.
Um... from your rough estimation, do you know the development effort of upgrading TF 1.15 to the latest version of TF?

**Comment by lissyx** [comment]
Not more than the previously shared feedback.

**Comment by tim5go** [comment]
@lissyx 
So, is it not considered even if it is paid under a proper commercial deal ?

**Comment by ftyers** [comment]
@tim5go there are people offering commercial support for DeepSpeech. You could contact them.

**Comment by tim5go** [comment]
@ftyers 
Got it, I will contact them directly

**Comment by lissyx** [comment]
> @lissyx So, is it not considered even if it is paid under a proper commercial deal ?

You'd need some entity to sign that, there is no such thing available for deepspeech. If you work on it and send PR, I'd review it.
