### ISSUE TITLE
Python 3.10 wheel?

### ISSUE THREAD

**Issue by Geremia** [mozilla/DeepSpeech#3694]
Is there a wheel compatible with Python 3.10? I currently get:

>$ pip3 install deepspeech-gpu
>ERROR: Could not find a version that satisfies the requirement deepspeech-gpu (from versions: none)
>ERROR: No matching distribution found for deepspeech-gpu

**Comment by lissyx** [comment]
Nobody is working on that but if you send patches we can review.

**Comment by ftyers** [comment]
You can also check out  #3693.
