### ISSUE TITLE
is scorer 9.3 missing from github?

### ISSUE THREAD

**Issue by stonkpunk** [mozilla/DeepSpeech#3700]
attempting to download https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.scorer seems to hang curl/browsers. eventually the connection times out. the pbmm file etc is still there. tried through some VPN locations assuming it's some CDN issue, but same result. are there any other ways to get the scorer?

**Comment by ftyers** [comment]
Check out #3693.
