### ISSUE TITLE
Add support for modern Electron releases

### ISSUE THREAD

**Issue by dudewheresmycode** [mozilla/DeepSpeech#3701]
Looking to integrate this project with Electron and I noticed you have some support, but the javascript package only provides prebuilt binaries up to Electron `v11`. However, the current supported releases of Electron are: `v15.3.1`, `v14.2.1`, `v13.6.1` (https://releases.electronjs.org/)

I'm hoping the solution is as easy as adding additional versions to this line:
https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/tc-all-vars.sh#L98

**Comment by reuben** [comment]
FWIW I've just updated the Coqui STT builds to cover newer NodeJS and ElectronJS versions over in https://github.com/coqui-ai/STT/pull/2018

Should be available in npm soon, I'll trigger a new alpha version.

**Comment by rjstalb** [comment]
I'm trying to get the nodejs binaries built against node versions but getting nowhere. Am I supposed to install electron manually or against a specific version? am I using the wrong node versions? 

- v10.4.0
- v12.22.7
- v14.18.1
- v16.10.0

Output:
![image](https://user-images.githubusercontent.com/7339311/142336359-bba908d5-2e97-4d1c-85e9-e207d342ee62.png)

**Comment by ftyers** [comment]
Check out #3693.
