### ISSUE TITLE
Support for TensorFlow 2 

### ISSUE THREAD

**Issue by peterjungx** [mozilla/DeepSpeech#3706]
DeepSpeech not using TensorFlow 2 is a major limitation. 

Today, Ubuntu 20.04 LTS  is among the most used linux distributions for Deep Learning related development. Nvidia is at version 11.5 with its CUDA Toolkit, and does not provide version 10.2 of the toolkit for Ubuntu 20.04 LTS. Yet the TF version used by DeepSpeech requires CUDA Toolkit 10.2. This means DeepSpeech is not usable on one of the most popular linux distros, Ubuntu 20.04 LTS.

I could not find any roadmap of the DeepSpeech developers on this issue. I think clarifying the stance would be valuable here.

**Comment by ftyers** [comment]
Check out #3693.

**Comment by peterjungx** [comment]
@ftyers thank you! This explains a lot.
