### ISSUE TITLE
Word Probabilities

### ISSUE THREAD

**Issue by karim-eladl** [mozilla/DeepSpeech#3707]
Hi, I'm a quite new to these kinds of models so I'd appreciate your help! I want to rate speech clarity in addition to transcribing the words.  I know the RNN converts an input to a sequence of character probabilities. I was wondering if it would be possible to output a probability along with each outputted word from this specific model? If so, how should I go about making these changes? Again, thank you for your tips!

**Comment by JRMeyer** [comment]
Take a look at issue #3693
