### ISSUE TITLE
my cosum model turkmen language

### ISSUE THREAD

**Issue by merdan1997** [mozilla/DeepSpeech#3709]
i  use python 3.8 
i  create my own turkmen language model. but i  have same  error 

I FINISHED optimization in 4:02:06.697799
I Loading best validating checkpoint from /content/drive/MyDrive/checkpoint1/best_dev-7200
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
I Loading variable from checkpoint: global_step
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_5/bias
I Loading variable from checkpoint: layer_5/weights
I Loading variable from checkpoint: layer_6/bias
I Loading variable from checkpoint: layer_6/weights
Testing model on /content/drive/MyDrive/sound/test.csv
Test epoch | Steps: 40 | Elapsed Time: 0:00:10
Test on /content/drive/MyDrive/sound/test.csv - WER: 0.347682, CER: 0.215981, loss: 99.878929
--------------------------------------------------------------------------------
Best WER:
--------------------------------------------------------------------------------
WER: 0.000000, CER: 0.000000, loss: 74.404655
- wav: file:///content/drive/MyDrive/sound/sound192.wav
- src: "şertlerine laýyk gelmegi babatda bildirilýän talaplara laýyklykda"
- res: "şertlerine laýyk gelmegi babatda bildirilýän talaplara laýyklykda"
--------------------------------------------------------------------------------
WER: 0.000000, CER: 0.013699, loss: 68.444801
- wav: file:///content/drive/MyDrive/sound/sound184.wav
- src: "türkmenistan bilen ýola goýulan köpýyllyk hyzmatdaşlygyna buýsanýandygyny"
- res: "türkmenistan bilen ýola goýulan köpýyllyk hyzmatdaşlygyna buýsanýandygyny "
--------------------------------------------------------------------------------
WER: 0.000000, CER: 0.016667, loss: 66.918755
- wav: file:///content/drive/MyDrive/sound/sound183.wav
- src: "baýramçylyk çärelerine gatnaşmaga döredilen mümkinçilik üçin"
- res: "baýramçylyk çärelerine gatnaşmaga döredilen mümkinçilik üçin "
--------------------------------------------------------------------------------
WER: 0.000000, CER: 0.000000, loss: 65.741348
- wav: file:///content/drive/MyDrive/sound/sound174.wav
- src: "türkmenistanyň bank ulgamyny tutýan orny örän ulydyr"
- res: "türkmenistanyň bank ulgamyny tutýan orny örän ulydyr"
--------------------------------------------------------------------------------
WER: 0.000000, CER: 0.000000, loss: 63.067028
- wav: file:///content/drive/MyDrive/sound/sound185.wav
- src: "buýsanýaandygyny we netijeli gatnaşyklary mundan beýläkde ösdürmäge"
- res: "buýsanýaandygyny we netijeli gatnaşyklary mundan beýläkde ösdürmäge"
--------------------------------------------------------------------------------
Median WER:
--------------------------------------------------------------------------------
WER: 0.200000, CER: 0.145161, loss: 47.088356
- wav: file:///content/drive/MyDrive/sound/sound191.wav
- src: "tehnikalaryň görnüşlerini kämilleşdirýär olaryň türkmenistanyň"
- res: "tehnikalaryň görnüşlerini kämilleşdirýär olaryň ynsanyň "
--------------------------------------------------------------------------------
WER: 0.250000, CER: 0.192982, loss: 84.911255
- wav: file:///content/drive/MyDrive/sound/sound178.wav
- src: "hereket etmegi daşary ýurt maýa goýumlarynyň kanun taýdan"
- res: "hereket etmegi daşary ýurt maýa guramanyň haly taýdan "
--------------------------------------------------------------------------------
WER: 0.272727, CER: 0.206897, loss: 132.757645
- wav: file:///content/drive/MyDrive/sound/sound173.wav
- src: "goýumlary çekmek we olaryň möçberini artdyrmak babatynda alnyp barylýan işiň çäklerinde"
- res: "ýer çekmek olaryň işler artdyrmak babatynda alnyp barylýan işiň çäklerinde "
--------------------------------------------------------------------------------
WER: 0.285714, CER: 0.137255, loss: 71.566231
- wav: file:///content/drive/MyDrive/sound/sound196.wav
- src: "täze görnüşdäki kämil tehnikalary satyn almak bilen"
- res: "täze görnüşdäki we kämil tehnikalary satyn almak bilen bu "
--------------------------------------------------------------------------------
WER: 0.333333, CER: 0.256757, loss: 146.555511
- wav: file:///content/drive/MyDrive/sound/sound161.wav
- src: "oba hojalyk maksatly ýörite ýer gaznazysynyň möçberini tassyklamak hakynda"
- res: "oba halk maksatly ýörite ýer gadymy gerek tassyklamak hakynda "
--------------------------------------------------------------------------------
Worst WER:
--------------------------------------------------------------------------------
WER: 0.714286, CER: 0.425926, loss: 87.827034
- wav: file:///content/drive/MyDrive/sound/sound179.wav
- src: "daşary ýurt maýa goýumlarynyň kanun taýdan goraglylygy"
- res: "daşary maýalarynyň haly taýdan orny "
--------------------------------------------------------------------------------
WER: 0.777778, CER: 0.403226, loss: 117.482162
- wav: file:///content/drive/MyDrive/sound/sound165.wav
- src: "ýurdumyzda uly möçberli maýa goýum işlerini amala aşyrmak üçin"
- res: "ýurdumyza möçberli maýa işleriň alamaga "
--------------------------------------------------------------------------------
WER: 0.857143, CER: 0.362319, loss: 134.416412
- wav: file:///content/drive/MyDrive/sound/sound176.wav
- src: "ýurdumyzyň ykdysadyýetine daşary ýurt maliýe serişdeleriň çekilmegine"
- res: "ýurdumyza ykdysady we şert meseleleriň çekilmegine "
--------------------------------------------------------------------------------
WER: 0.900000, CER: 0.594203, loss: 161.787582
- wav: file:///content/drive/MyDrive/sound/sound170.wav
- src: "ýurdumyzda nebit gaz nebit himiýa saglygy goraýyş we derman senagaty "
- res: "ýurdumyza we işini halkara derman "
--------------------------------------------------------------------------------
WER: 1.250000, CER: 0.966102, loss: 381.671783
- wav: file:///content/drive/MyDrive/sound/sound199.wav
- src: "amala aşyrylýan möhüm özgertmeleriň esasy ugry bolup durýar"
- res: "oba hojalyk tehnikalaryň şol sanda täze görnüşli pagta ýygyjy we "
--------------------------------------------------------------------------------
I Exporting the model...
I Loading best validating checkpoint from /content/drive/MyDrive/checkpoint1/best_dev-7200
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_5/bias
I Loading variable from checkpoint: layer_5/weights
I Loading variable from checkpoint: layer_6/bias
I Loading variable from checkpoint: layer_6/weights
I Models exported at /content/drive/MyDrive/model
I Model metadata file saved to /content/drive/MyDrive/model/author_model_0.0.1.md. Before submitting the exported model for publishing make sure all information in the metadata file is correct, and complete the URL fields.
Making a mmap-able model for inference
The output_graph.pb model file generated in the above step will be loaded in memory to be dealt with when running inference. This will result in extra loading time and memory consumption. One way to avoid this is to directly read data from the disk.

and use mic_vad_streaming.py  . my model worked uncorectly .

**Comment by JRMeyer** [comment]
Firstly - yay for Turkmen! Glad to see the language getting some new technology:)

Take a look at issue #3693
