### ISSUE TITLE
Python >= 3.8 not supported

### ISSUE THREAD

**Issue by RomainL972** [mozilla/DeepSpeech#3712]
Hi,

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04 LTS
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Not installed yet
- **TensorFlow version (use command below)**: Not installed yet
- **Python version**: 3.8.10
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `pip3 install --upgrade -e .`

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

When trying to install all dependencies, I get an error for installing tensorflow : "No matching distribution found for tensorflow==1.15.4". According to [this issue](https://github.com/tensorflow/tensorflow/issues/34302), all versions of tensorflow before 2.2 don't support Python 3.8. Since DeepSpeech requires tensorflow 1.15, by extension it doesn't any Python version above 3.7.

On Ubuntu 20.04, the default Python version is 3.8, so that's a problem when a user on a fresh system wants to install DeepSpeech without installing third-party repositories or building Python from source.

Best regards.

**Comment by lissyx** [comment]
Thanks, this is a hard requirements inherited from tensorflow, and moving training pipeline to 2.x is already an open issue that wont be fixed given we are not working on that anymore. Using docker would make you immune to this. You might hit the same limite with coqui but they are actively working on it so training should move to 2.x at some point. @reuben can tell you more on @coqui_ai
