### ISSUE TITLE
Nodejs_wav "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by AndreP2211** [mozilla/DeepSpeech#3713]
Hello,
I have summarized the whole thing a bit. you can find all the information in my prepared GitHub:
https://github.com/AndreP2211/deepspeech-help

**Comment by lissyx** [comment]
> Hello, I have summarized the whole thing a bit. you can find all the information in my prepared GitHub: https://github.com/AndreP2211/deepspeech-help

Please avoid forwarding people like that, it makes it much more complicated to understand your issue ...

Illegal instruction, you're running a VM it seems? And there's no AVX extensions reported on the CPU, so it's unsupported and expected to fail like that.
