### ISSUE TITLE
run transcribe.py over gpu

### ISSUE THREAD

**Issue by ros-packages** [mozilla/DeepSpeech#3719]
Hello
I want to transcribe a large number of files with deepspeech and I want to use Tensorflow but apparently, transcribe.py does not use GPU and it fills all my CPU cores.
Is there a way for transcribe.py to use GPU?
Is there any way to run pb file instead of checkpoints in transcribe.py?
thanks.

**Comment by JRMeyer** [comment]
Take a look at issue https://github.com/mozilla/DeepSpeech/issues/3693
