### ISSUE TITLE
Tensorflow 1.15.4 dependency

### ISSUE THREAD

**Issue by dmitryelj** [mozilla/DeepSpeech#3720]
Hi all,
Thanks for the cool project.

I am trying to learn my own language model using Deepspeech, but I cannot install this project correctly on a fresh system. 

The current version of Deepspeech is using Tensorflow 1.15.4, which is not available anymore using pip on Linux. Building Tensorflow from source requires ancient version of Bazel 0.26.1 (the current version is 5.0.0, just for info), and while building Tensorflow there are other incompatibilities with GCC/GLIBC/gRPC, and so on.

Is there any chance to get rid of this?

Thanks.

**Comment by ftyers** [comment]
Please take a look at  #3693.
