### ISSUE TITLE
Wake Word Detection

### ISSUE THREAD

**Issue by Siyamfahad** [mozilla/DeepSpeech#3721]
I am preparing data to train my deepspeech language model for the danish language,
how can I add a wake word to the model like "hey Siri", "Alexa"...
maybe deepspeech doesn't provide this feature, so which free service should I use as best alternatives

**Comment by JRMeyer** [comment]
You might take a look into Issue https://github.com/mozilla/DeepSpeech/issues/3693 before you get started
