### ISSUE TITLE
Node binding npm Deepspeech module missing for 9.3

### ISSUE THREAD

**Issue by Perpleex** [mozilla/DeepSpeech#3725]
I updated to 0.93

deepspeech node error Error: Cannot find module '/node_modules/deepspeech/lib/binding/v0.9.3/linux-x64/node-v93/deepspeech.node'

My npm node module updated to 0.9.3 :
:~/sttServer/ws2/node_modules/deepspeech/lib/binding/v0.9.3/linux-x64$ ls
electron-v10.0  electron-v11.0  electron-v6.0  electron-v7.0  electron-v8.0  electron-v9.1  libdeepspeech.so  node-v67  node-v79  node-v88
electron-v10.1  electron-v5.0   electron-v6.1  electron-v7.1  electron-v9.0  electron-v9.2  node-v64          node-v72  node-v83
No reference to node-v93

**Comment by lissyx** [comment]
What is weird you just confirmed my statement ? v16 was pushed only on master, never released.
