### ISSUE TITLE
.Net code returns different result

### ISSUE THREAD

**Issue by Camel-RD** [mozilla/DeepSpeech#3726]
Im using 2830-3980-0043.wav file from audio-0.9.3.tar.gz

This command returns "experience proves this":
deepspeech.exe --model deepspeech-0.9.3-models.pbmm --audio "2830-3980-0043.wav"

This c# code returns "experience prooes thiss".
```
  DeepSpeech deepSpeechClient = new DeepSpeech("deepspeech-0.9.3-models.pbmm");
  var waveBuffer = new NAudio.Wave.WaveBuffer(File.ReadAllBytes("2830-3980-0043.wav"));
  string speechResult = deepSpeechClient.SpeechToText(
    waveBuffer.ShortBuffer,
    Convert.ToUInt32(waveBuffer.MaxSize / 2));
```

**Comment by ftyers** [comment]
@Camel-RD thanks for your interest! Please see #3693.
