### ISSUE TITLE
Please tell me is this setup is good for DeepSpeech Model Training 

### ISSUE THREAD

**Issue by mukeshbadgujar** [mozilla/DeepSpeech#3727]
I am trying to build model with DeepSpeech,
I got many errors about versions,

Is it right version i am using for DeepSpeech

DeepSpeech: 0.9.3
Ubuntu: 20.04.4 LTS
CUDA: 11.6
Graphics card: Nvidia RTX 3070 Ti 8GB
Python: 3.6
RAM: 32GB
CPU: 16Cores

I am using Docker as shown in DeepSpeech Playbook,
Followed each Step,

But getting errors likely to versions as i searched on internet,

Please tell me above version are right?

I also posted on mozilla but no reply,

https://discourse.mozilla.org/t/deepspeech-model-training-on-ubuntu-20-04-4-lts-with-cuda-11-6/94723?u=mukeshbadgujar

**Comment by ftyers** [comment]
See #3693.

**Comment by mukeshbadgujar** [comment]
> See #3693. 

I am very sad to see this, but i will find a way,

Thank you Sir for improving my knowledge.
