### ISSUE TITLE
Docs bug: Missing some info

### ISSUE THREAD

**Issue by mladenb** [mozilla/DeepSpeech#3729]
Using Ubuntu/Linux, but not that it's really important.
The doc file https://github.com/mozilla/DeepSpeech/blob/r0.9/doc/TRAINING.rst contains setup instructions and following those, I've received pip error:
```
$ pip3 install --upgrade -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/mladen/speech-recognition
```
after switching to a directory where the git repo was cloned, the error disappeared. I believe this is trivial stuff for you guys, but for people that haven't used python/pip so frequently, this could have been a show stopper, considering that internet search results on that error were quite misleading.

Thank you for a great tool! :)

**Comment by ftyers** [comment]
Please see #3693 :)
