### ISSUE TITLE
Would you mind share the pretrained .pb file

### ISSUE THREAD

**Issue by aboutx** [mozilla/DeepSpeech#3730]
Hello, I would like to use pre-trained Mandarin Chinese deepspeech models to extract audio features. However I did not find a way to load .pbmm file. When I tried to load checkpoint, I also encountered with a cudnn_lstm bug. So may I get the pretrained .pb file(only academic purpose)? My email is 20120346@bjtu.edu.cn, thank you very much!

**Comment by ftyers** [comment]
Dear @aboutx please see #3693.

**Comment by wzx7084** [comment]
> Hello, I would like to use pre-trained Mandarin Chinese deepspeech models to extract audio features. However I did not find a way to load .pbmm file. When I tried to load checkpoint, I also encountered with a cudnn_lstm bug. So may I get the pretrained .pb file(only academic purpose)? My email is [20120346@bjtu.edu.cn](mailto:20120346@bjtu.edu.cn), thank you very much!

Hello, I have the same problem. Do you have the pb file of version 0.9.3?

**Comment by tailangjun** [comment]
> Hello, I would like to use pre-trained Mandarin Chinese deepspeech models to extract audio features. However I did not find a way to load .pbmm file. When I tried to load checkpoint, I also encountered with a cudnn_lstm bug. So may I get the pretrained .pb file(only academic purpose)? My email is [20120346@bjtu.edu.cn](mailto:20120346@bjtu.edu.cn), thank you very much!

请问老铁是否找到了中文的.pb模型

**Comment by xuduo18311199384** [comment]
> > Hello, I would like to use pre-trained Mandarin Chinese deepspeech models to extract audio features. However I did not find a way to load .pbmm file. When I tried to load checkpoint, I also encountered with a cudnn_lstm bug. So may I get the pretrained .pb file(only academic purpose)? My email is [20120346@bjtu.edu.cn](mailto:20120346@bjtu.edu.cn), thank you very much!
> 
> 请问老铁是否找到了中文的.pb模型

同求中文.pb模型
