### ISSUE TITLE
# NOT able to install " convert_graphdef_memmapped_format "

### ISSUE THREAD

**Issue by BSAnirudh** [mozilla/DeepSpeech#3739]
trying to install "convert_graphdef_memmapped_format" using the command mentioned in https://deepspeech.readthedocs.io/en/v0.6.1/TRAINING.html

command : python3 util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --branch r1.14 --target .

facing this error. 

<img width="945" alt="graphdef_error" src="https://user-images.githubusercontent.com/96466399/179714829-84ca38bc-c42b-4e39-91e4-1a8a45f003b6.PNG">

**Comment by lissyx** [comment]
> Hey @lissyx , may i know why the issue is closed?

Search other issues, discourse, etc. DeepSpeech is not maintained anymore, there is no more CI.
