### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by St3ph3nBr00ks** [mozilla/DeepSpeech#3741]
I am attempting to create a WebGL solution for DeepSpeech and hit a wall with the DLL files. What would it take to create a DLL file compatible with WebGL? Is it something I would be able to do myself? I have tried opening the win64 DLL with dnSpy and dotPeek but neither was able to show the contents.

**Comment by ftyers** [comment]
DeepSpeech is unmaintained, please see #3693.

**Comment by lissyx** [comment]
While @ftyers is right, please note @St3ph3nBr00ks that stating "and hit a wall with the DLL files" is absolutely unactionable, even if I wanted to help, you provide 0 information on the actual issue.

**Comment by St3ph3nBr00ks** [comment]
The big-picture action I am trying to achieve is making DeepSpeech compatible with Unity WebGL. I believe the next step in that process is creating a new DLL file compatible with WebGL. I do not know where to begin with that process and was hoping for advice. However, since DeepSpeech is not maintained and the new iteration "Coqui STT" is, I imagine the better course of action is to attempt WebGL support for Coqui.

**Comment by lissyx** [comment]
> The big-picture action I am trying to achieve is making DeepSpeech compatible with Unity WebGL. I believe the next step in that process is creating a new DLL file compatible with WebGL. I do not know where to begin with that process and was hoping for advice. However, since DeepSpeech is not maintained and the new iteration "Coqui STT" is, I imagine the better course of action is to attempt WebGL support for Coqui.

Nevermind, I misread "WebGL" as "OpenGL". Using WebGL from TensorFlow, I dont know, WebGL is still quite new. Maybe the WASM work done on Coqui can help.
