### ISSUE TITLE
Is there any way to prove that the sound file A has not been trained by the DeepSpeech model?

### ISSUE THREAD

**Issue by DN-kyeongminKim** [mozilla/DeepSpeech#3745]
**This is not an issue, but a feature inquiry.**

To have this model verified by an external organization

It is a situation where you need to prove that the prepared sound source file for verification has not been trained.

Is there any way to prove that the sound file A has not been trained by the DeepSpeech model?
(After recognizing the A file model STT, output the contents of "It is an untrained file", etc.)

**Comment by ftyers** [comment]
Dear @DN-kyeongminKim please see #3693.
