### ISSUE TITLE
Dockerfiles won't work  

### ISSUE THREAD

**Issue by jkaspereit** [mozilla/DeepSpeech#3749]
I checked out the master branch. 
Created the Dockerfile with: make Dockerfile.train
Tried to build the Dockerfile and ended up with the following exception in Step 2 (RUN apt-get update && apt-get install -y --no-install-recommends     apt-utils....) :

#5 14.64 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#5 14.64 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is no longer signed.
[+] Building 12.8s (15/19)

I tried to fix the issue by adding the following lines:
# Updating CUDA Linux GPG Repository Key
RUN apt-get install wget
RUN apt-key del 7fa2af80
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb
RUN sed -i '/developer\.download\.nvidia\.com\/compute\/cuda\/repos/d' /etc/apt/sources.list
RUN rm etc/apt/sources.list.d/cuda-ubuntu1804-x86_64.list
RUN rm etc/apt/sources.list.d/cuda.list

Then i built again and crashed again in Step 12/17 ( => ERROR [12/17] RUN cd /DeepSpeech && pip3 install --upgrade pip==20.2.2 wheel==0.34.2 setuptools==49.6.0 &&     DS_NODECODER=y DS_NOTENSORFLOW=y pip3 install ....) with the following error:

ERROR: Could not find a version that satisfies the requirement scipy<1.9.0,>=1.7.0 

Any advice how to fix this error? Or does someone have a working Dockerfile?

**Comment by ftyers** [comment]
See #3693 .
