### ISSUE TITLE
[WIN] [ERR] Error: spawn sox ENOENT

### ISSUE THREAD

**Issue by affanmehmood** [mozilla/DeepSpeech#3756]
Is it possible to run this project on a windows machine?

My Node version is 14.19.0
My python version is 3.7.9

Is it possible to run it in windows in a node environment? Can someone guide me on how to do that?

when I run 'node index.js' I get the following error:

C:\User\DeepSpeech-examples\nodejs_wav>node index.js
TensorFlow: v2.3.0-6-g23ad988fcd
DeepSpeech: v0.9.3-0-gf2e9c858
2022-12-16 11:30:13.040723: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
memory stream START
memory stream DONE
result:
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn sox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Stream instance at:
    at C:\User\DeepSpeech-examples\nodejs_wav\node_modules\sox-stream\index.js:40:11
    at C:\User\DeepSpeech-examples\nodejs_wav\node_modules\create-temp-file\index.js:16:13
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn sox',
  path: 'sox',
  spawnargs: [
    '--no-dither',
    'C:\\Users\\affan\\AppData\\Local\\Temp\\571fee9d-49e4-4c86-8ff9-cd61cae7430f',
    '--bits',
    16,
    '--rate',
    16000,
    '--channels',
    1,
    '--encoding',
    'signed-integer',
    '--endian',
    'little',
    '--compression',
    0,
    '--type',
    'raw',
    '-'
  ]
}

**Comment by lissyx** [comment]
Project is unmaintained and you are referring to code from examples, not deepspeech.
