### ISSUE TITLE
Error while installing deepspeech

### ISSUE THREAD

**Issue by EY500** [mozilla/DeepSpeech#3765]
I am using `pip3 install deepspeech` for installing deepspeech. I am using Windows 10 for this project and it gives out an error like this:

ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none)
ERROR: No matching distribution found for deepspeech

I also tried specifying the version while installing but it still did not work.
I tried downloading it with a `venv` and without but did not work in either case. it gave the same error in both cases
I don't know what requirements my system doesn't have.

**Comment by lissyx** [comment]
Please understand that the project is unmaintained. Likely there is no wheel published for this pair of platform and python version
