### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none) ERROR: No matching distribution found for deepspeech

### ISSUE THREAD

**Issue by parisa-hr** [mozilla/DeepSpeech#3766]
Hi, I add my issue in [discourse.mozilla](https://discourse.mozilla.org/t/error-could-not-find-a-version-that-satisfies-the-requirement-deepspeech-from-versions-none/114647) too.

If you've found a bug, or have a feature request, then please create an issue with the following information:

I follow the [installation Doc](https://deepspeech.readthedocs.io/en/r0.9/?badge=latest#) guide but can't install it in `fedora 38`.

```
[parisa@fedora ~]$ virtualenv -p python3 $HOME/tmp/deepspeech-venv/
created virtual environment CPython3.11.3.final.0-64 in 192ms
  creator CPython3Posix(dest=/home/parisa/tmp/deepspeech-venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(extra_search_dir=/usr/share/python-wheels,download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/parisa/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.5.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[parisa@fedora ~]$ source $HOME/tmp/deepspeech-venv/bin/activate
(deepspeech-venv) [parisa@fedora ~]$ sudo pip3 install deepspeech
[sudo] password for parisa: 
ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none)
ERROR: No matching distribution found for deepspeech
(deepspeech-venv) [parisa@fedora ~]$ 

```
- **Exact command to reproduce**:

![image](https://github.com/mozilla/DeepSpeech/assets/44742050/a592f037-227a-4103-ae32-64abd2c9ef13)

and I don't know which `.whl` I should use.
I also try to build from the [source](https://github.com/mozilla/DeepSpeech) but I didn't understand how can I do that.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 38
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- 
![image](https://github.com/mozilla/DeepSpeech/assets/44742050/24dee71a-9267-47f9-9788-6d0dd813d9f5)

- **Python version**: 3.11.3
- **Bazel version (if compiling from source)**: 6.2.0
- **GCC/Compiler version (if compiling from source)**:13.1.1
- **CUDA/cuDNN version**:
[parisa@fedora ~]$ nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
```
- **GPU model and memory**:

![image](https://github.com/mozilla/DeepSpeech/assets/44742050/8c96beb0-5a3e-49a8-8cfd-3df99cd7d1bf)

**Comment by lissyx** [comment]
project is unmaintained, and there is no wheel for 3.11
