### ISSUE TITLE
Request for precompiled DeepSpeech-TFLite for ARMv7l (armhf)

### ISSUE THREAD

**Issue by TYeniyayla** [mozilla/DeepSpeech#3773]
Have I written custom code (as opposed to running examples on an unmodified clone of the repository):
No, I am working with DeepSpeech examples.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Debian 10 (Buster), architecture ARMv7l (armhf)

TensorFlow installed from (our builds, or upstream TensorFlow):
Upstream TensorFlow (v2.3.0)

TensorFlow version:
v2.3.0

Python version:
Python 3.7.3

Bazel version (if compiling from source):
N/A

GCC/Compiler version (if compiling from source):
N/A

CUDA/cuDNN version:
N/A

GPU model and memory:
N/A

Exact command to reproduce:
python3 [script.py](https://pastebin.com/embed_js/chnbur2n) ([script.py](https://pastebin.com/embed_js/chnbur2n) includes loading the DeepSpeech model)

Relevant TensorFlow version information:
'v2.3.0-6-g23ad988' '2.3.0'

Description of the problem:
I am planning to use DeepSpeech on ARMv7l (armhf) in my project. However, in the release section, there is no precompiled DeepSpeech-TFLite version for this architecture. Considering the wide use of ARMv7l devices in edge computing, a precompiled DeepSpeech-TFLite version for this architecture will provide great benefit to the community. Compiling TensorFlow Lite on these devices is technically challenging and time-consuming, and a precompiled version will speed up the development process for many users.

Feature Request:
I kindly request you to consider adding a precompiled DeepSpeech-TFLite version for the ARMv7l (armhf) architecture. This will be beneficial not only for my project but also for many people working in the community.

Thank you very much.

**Comment by lissyx** [comment]
There were armv7l binaries published: https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3
