### ISSUE TITLE
Index.rst is either out of date  or I cannot cut and paste any more  

### ISSUE THREAD

**Issue by NeilWP** [mozilla/DeepSpeech#3786]
As  a  windows / C#  type rather than a  Python /MAC  dev my expectation from reading  index.rst  and in particular the elements in the screen shot below,  it was all simple cut and paste  
<img width="696" alt="ds2" src="https://github.com/mozilla/DeepSpeech/assets/66391866/9d712dbb-4fbf-4ff3-94c1-2af80fd0f17a">

**Alas -** the pip install feature fails with 
`
ERROR: Could not find a version that satisfies the requirement deepspeech==0.9.3 (from versions: none)
ERROR: No matching distribution found for deepspeech==0.9.3    
`
Dropping the forced  versioning I get the same error 
<img width="679" alt="deepspeech" src="https://github.com/mozilla/DeepSpeech/assets/66391866/9160c638-217f-4783-9a16-9d8b2c1c8a7c">

I proved that python and venv functioning correctly by pip installing pandas .
<img width="757" alt="ds5" src="https://github.com/mozilla/DeepSpeech/assets/66391866/b3d4a75d-c830-4510-a453-6076c404ea8b">

**The curl**   examples fail.
<img width="767" alt="ds3" src="https://github.com/mozilla/DeepSpeech/assets/66391866/3adbc4ae-a894-47a2-983c-5ddd088ce6b9">

dropping the errroneous parameter LO  I get a download going. **BUT** it too fails  

<img width="767" alt="ds4" src="https://github.com/mozilla/DeepSpeech/assets/66391866/db426141-656f-4551-bca3-c5793498024a">

**Comment by lissyx** [comment]
Please avoid posting screenshot for CLI, it's impossible to work with.

Sadly, `curl` in PowerShell is not `curl` so please adapt parameters.

Your `pip` failing is just because this is either a version we did not publish wheel for, or the ABI is incompatible (we only supported official Python builds).

Plus, project is unmaintained for years.
