### ISSUE TITLE
.Net version is at End of Life  ?

### ISSUE THREAD

**Issue by NeilWP** [mozilla/DeepSpeech#3787]
So when I cloned he git repo  and opened it is Visual studio 2022. the first out of the box compilation to see what falls over  was  a biggie.

```
Severity	Code	Description	Project	Path	File	Line	Suppression State	Details
Error	MSB3644	The reference assemblies for .NETCore,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	DeepSpeechClient	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1241		
```
The resolution could be install the  .NetCore  version 5, if that were not at end of life - and only compatible with VS 2019.    
[https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-5.0.408-windows-arm64-installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-5.0.408-windows-arm64-installer) 

after  a few minutes of tinkering and delving into setup.py  I discover  that the references to version files are either empty or ot working and when I look at PyPi, there are no  versions for the dtc encoder  and tensor flow which will work with today with the sources as delivered.   

So it would appear that  DeepSpeech is truly at end of life and mute for Windows / python 2024  :-(

**Comment by lissyx** [comment]
Project is unmaintained for years, yes.
