### ISSUE TITLE
Provide a native client / library

### ISSUE THREAD

**Issue by Cwiiis** [mozilla/DeepSpeech#379]
It would be ideal for embedded if we could provide a native library/client for DeepSpeech that didn't rely on Python or other such heavy dependencies. TensorFlow provides a C API and a shared library.

**Comment by lissyx** [comment]
Would it be realistic this is relying on the makefile libtensorflow build that provides basic featuring? I guess that now you have a native client, it could be tested if we have all what we need from this lib :)

**Comment by Cwiiis** [comment]
@lissyx I've opened issue #382 to investigate - hopefully it already works :)

**Comment by Cwiiis** [comment]
Fixed by PR #380
