### ISSUE TITLE
[NEW RESOURCE] Introducing MARS5, open-source, insanely prosodic text-to-speech (TTS) model.

### ISSUE THREAD

**Issue by akshhack** [mozilla/DeepSpeech#3796]
Hey community members!

We're super stoked to announce the open source release of MARS5, an extremely prosodic text-to-speech engine that is able to handle prosody as hard as things like sports commentary, anime, movies with just a few seconds of audio reference. 

We'd love for you to check it out at
https://github.com/Camb-ai/MARS5-TTS/tree/master

Quick links:
**Official release video**: https://www.youtube.com/watch?v=bmJSLPYrKtE
**Discord:** https://discord.gg/ZzsKTAKM
**Github:** https://www.github.com/camb-ai/mars5-tts
**Website:** https://www.camb.ai/
**Youtube:** https://www.youtube.com/@camb-ai

**Comment by lissyx** [comment]
Spam is not welcome.
