### ISSUE TITLE
Investigate using tensorflow/contrib/makefile/Makefile for native client

### ISSUE THREAD

**Issue by Cwiiis** [mozilla/DeepSpeech#382]
There's a Makefile in the contributions directory for TensorFlow that allows building without the monstrosity that is Bazel, and makes it easier/possible to cross-compile. It would be ideal if the native client could link against this built library. It may already work, opening this issue to investigate if that's the case.

**Comment by Cwiiis** [comment]
Useful information from IRC: https://gist.github.com/lissyx/28c1a0092d9a1ea73d786381682a91be

**Comment by lissyx** [comment]
FTR, the lib being built this way is a static one, not a shared one as much as I recall. I am not sure if the Makefile has targets to build .so, this might be something to consider.

**Comment by Cwiiis** [comment]
So I experimented with this, and although I could get it to build, it seems the static library built by the Makefile differs somewhat in behaviour to the shared library built by Bazel and I couldn't easily reconcile the difference. Also, @lissyx has been successfully cross-compiling TensorFlow with bazel, so I don't think this is an avenue worth spending any considerable time on. You can see some of the work I did here: https://github.com/Cwiiis/DeepSpeech/tree/native-client-makefile

All that said, closing this issue.
