### ISSUE TITLE
Training is continuously slowing down

### ISSUE THREAD

**Issue by striki70** [mozilla/DeepSpeech#384]
Execution time of the following line:
result = session.run(params, **extra_params)
in calculate_loss_and_report function is constantly increasing.
Any idea about the reason for this?

**Comment by kdavis-mozilla** [comment]
@striki70 Could you supply more details?

- Which data set are you using?
- What hardware?
- What version of tensorflow?
- ...

**Comment by reuben** [comment]
I don't know how much slower it gets for you, but some slowdown is expected due to curriculum learning. Later batches get slower as the examples get bigger. You should see faster session runs during the start of later epochs though.

**Comment by kdavis-mozilla** [comment]
I'm going to close on inactivity
