### ISSUE TITLE
Please add MPL2 license to this repository

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/DeepSpeech#39]
Per Mofoco policy, all original open source works should (where possible) be licensed under MPL2, but this public repository is missing the LICENSE file necessary to determine its usability by other projects. You can use the plain-text MPL2 at https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt (or, if your specific project requires it, the equivalent plain-text form of whatever license you're required to use.)

**Comment by kdavis-mozilla** [comment]
Resolved with commit ea38c68
