### ISSUE TITLE
Benchamark XLA JIT with DeepSpeech training

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#390]
Once we've switched to 1.0.0 we should benchmark XLA JIT to see if we've a performance gain.

Generically the switch should only involve:

```python
# Config to turn on JIT compilation
config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1

sess = tf.Session(config=config)
```
NMT like models have shown 20-60% performance improvement[[1](https://youtu.be/kAOanJczHA0?t=39m4s)]. As we're similar, NMT are essentially stacked LSTM-RNN, we should also see a nice performance boost.

**Comment by lissyx** [comment]
I have 1.0.0 building properly now, I'll give a try to enabling XFA and see the improvements we can get on my GTX1080 :)

**Comment by lissyx** [comment]
So far, most of the testing I could perform did not yield an improvement in execution time. XLA JIT did kick in, but it was still a bit slower than without.

**Comment by lissyx** [comment]
I should give that more testing now, especially that we have the 4 GPUs machine free mostly, and that XLA has been backing for longer.

**Comment by lissyx** [comment]
I don't think that's relevant anymore ?
