### ISSUE TITLE
Code to calculate MFCC features for TED-LIUM using python_speech_features and format them for the net

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#4]

**Comment by kdavis-mozilla** [comment]
There is a Python package [python_speech_features](https://pypi.python.org/pypi/python_speech_features/0.4) that can be used to calculate MFCC features.

**Comment by kdavis-mozilla** [comment]
The issue6 branch[[1]](https://github.com/mozilla/DeepSpeech/tree/issue6) has example code showing how data can be integrated.

**Comment by kdavis-mozilla** [comment]
@andrenatal I've made a WIP commit f1d697a addressing this issue. It's not finished but the majority of the code is there. The largest pain was having to write the queue and threading code by hand.

As a warning, do no try to use the standard TensorFlow Queues and Readers[[1]](https://www.tensorflow.org/versions/r0.11/how_tos/reading_data/index.html#reading-from-files). They will not work. 

As we require paddings, we would have to use a [PaddingFIFOQueue](https://www.tensorflow.org/versions/r0.11/api_docs/python/io_ops.html#PaddingFIFOQueue). However, a [PaddingFIFOQueue](https://www.tensorflow.org/versions/r0.11/api_docs/python/io_ops.html#PaddingFIFOQueue) doesn't allow the other thing we require SparseTensors, as TensorFlow's Queues do not work with SparseTensors[[2]](https://www.tensorflow.org/versions/r0.11/how_tos/reading_data/index.html#sparse-input-data). So this basically means we have to write the code by hand as I did.

**Comment by andrenatal** [comment]
Thank you @kdavis-mozilla! I'll jump on it right now!
