### ISSUE TITLE
Don't create a new session every time we do validation

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#402]
Creating a new session is probably not necessary and just adds extra overhead and console spam to the already convoluted training process. We should get rid of it.

**Comment by tilmankamp** [comment]
Once this was done on purpose to avoid having two graphs (for validation and training) in memory. Situation changed a bit in the meantime, and I am working on a totally different train loop. I already designed my code to use just one session. However: Certain details still need to get figured out (queue-switching). Let's put this on hold.

**Comment by reuben** [comment]
That sounds awesome :)

**Comment by reuben** [comment]
Fixed by #478.
