### ISSUE TITLE
Rank beam_width ctc_beam_search_decoder() results on language model + word weighting

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#409]
The goal of this issue is to start with issue #408 then to add rank not only upon the language model, but also upon the the number of words in the STT's results. The relative weight of the two factors must be tuned through the use of a hyperparameter.

In particular implement

> ![lm](https://cloud.githubusercontent.com/assets/12054740/23355570/a08f788c-fcd6-11e6-8a7a-5457c0edeea2.png)

without the RNN log probability term and with alpha set to 1, as it's value is irrelevant once we remove the RNN log probability term.

**Comment by reuben** [comment]
This was fixed by the KenLM beam scoring code.
