### ISSUE TITLE
Rank beam_width ctc_beam_search_decoder() results on language model + word weighting + RNN log prob

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#410]
If issue #400 indicates that tensorflow/tensorflow#6034 is fixed in in TF 1.0.0, then add the RNN log prob summand to the branch of issue #409 to fully implement

> ![lm](https://cloud.githubusercontent.com/assets/12054740/23355801/b6d32908-fcd7-11e6-97d1-54528e8236ae.png)

tuning the hyperparameters alpha and beta using the validation data set.

**Comment by reuben** [comment]
This was fixed by the KenLM beam scoring code.
