### ISSUE TITLE
Loading the LM will be faster if you build a binary file

### ISSUE THREAD

**Issue by pannous** [mozilla/DeepSpeech#412]
how to build the binary file?

**Comment by kdavis-mozilla** [comment]
Once one's installed kenlm from sources, then from the `kenlm` directory:
```bash
kdaviss-MBP:kenlm kdavis$ bin/build_binary text.arpa text.binary 
```
See the `Querying` section of KenLM Language Model Toolkit[[1](http://kheafield.com/code/kenlm/)].
