### ISSUE TITLE
While Downloading Libs Gpu is Being Used

### ISSUE THREAD

**Issue by lacvapps** [mozilla/DeepSpeech#430]
Because TensorFlow is started before the the resources are checked TensorFlow allocates the GPU memory buffer unnecessarily and the GPU will be unusable for other tasks while the libraries are downloaded. TensorFlow should be started / imported after the libraries have been downloaded. Not sure if this affects the CPU as well

**Comment by kdavis-mozilla** [comment]
@lacvapps Just to clarify. When you say

> ...while the libraries are downloaded

I think you mean

> ...while the data set is downloaded.

Is this correct? We do not, to my knowledge, download any libraries.

**Comment by lacvapps** [comment]
@kdavis-mozilla Yes you are correct, I meant data set.

**Comment by kdavis-mozilla** [comment]
@tilmankamp We mentioned this yesterday. Do you want to fold this in to you refactor for distributed training?

**Comment by kdavis-mozilla** [comment]
One can download via a browser first to spare the GPU while downloading.
