### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kenyeung128** [mozilla/DeepSpeech#436]
Hi I got this error with Segmentation Fault, after running the python DeepSpeech.py

Does anyone has idea? Thanks.

ResourceExhaustedError (see above for traceback): /home/ubuntu/.local/share/deepspeech/model.ckpt-29.data-00000-of-00001.tempstate16895047797406960199
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, b1, b1/Adam, b1/Adam_1, b2, b2/Adam, b2/Adam_1, b3, b3/Adam, b3/Adam_1, b5, b5/Adam, b5/Adam_1, b6, b6/Adam, b6/Adam_1, beta1_power, beta2_power, bidirectional_rnn/bw/basic_lstm_cell/biases/_2021, bidirectional_rnn/bw/basic_lstm_cell/biases/Adam/_2023, bidirectional_rnn/bw/basic_lstm_cell/biases/Adam_1/_2025, bidirectional_rnn/bw/basic_lstm_cell/weights/_2027, bidirectional_rnn/bw/basic_lstm_cell/weights/Adam/_2029, bidirectional_rnn/bw/basic_lstm_cell/weights/Adam_1/_2031, bidirectional_rnn/fw/basic_lstm_cell/biases/_2033, bidirectional_rnn/fw/basic_lstm_cell/biases/Adam/_2035, bidirectional_rnn/fw/basic_lstm_cell/biases/Adam_1/_2037, bidirectional_rnn/fw/basic_lstm_cell/weights/_2039, bidirectional_rnn/fw/basic_lstm_cell/weights/Adam/_2041, bidirectional_rnn/fw/basic_lstm_cell/weights/Adam_1/_2043, h1, h1/Adam, h1/Adam_1, h2, h2/Adam, h2/Adam_1, h3, h3/Adam, h3/Adam_1, h5, h5/Adam, h5/Adam_1, h6, h6/Adam, h6/Adam_1)]]

Segmentation fault (core dumped)

**Comment by reuben** [comment]
Looks like you ran out of space in the disk/partition?

**Comment by kenyeung128** [comment]
that's right, thanks a lot
