### ISSUE TITLE
Segfault on completion of ldc93s1 training

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#440]
See description here[[1](https://github.com/mozilla/DeepSpeech/issues/437#issuecomment-285938761)].

**Comment by kdavis-mozilla** [comment]
Also seeing same segfault on our 4 x Titan X machine

**Comment by kdavis-mozilla** [comment]
The problem occurs when running 
```bash
DeepSpeech$ bin/run-ldc93s1.sh
```
on a multi-gpu machine.

When running the above the env variable `ds_export_dir` is not set. Hence its value is set via
```
export_dir = os.environ.get('ds_export_dir', None)
```
Thus code of the form
```python
    # Finally, we restore the trained variables into a simpler graph that we can export for serving.
    # Don't export a model if no export directory has been set
    if export_dir:
        with tf.device('/cpu:0'):
            tf.reset_default_graph()
            session = tf.Session(config=session_config)
            ...
```
will not execute as `export_dir` is `None` so the `if` block is not executed.

That said, if one comments out the `if` block including the `if`
```python
    # Finally, we restore the trained variables into a simpler graph that we can export for serving.
    # Don't export a model if no export directory has been set
#   if export_dir:
#       with tf.device('/cpu:0'):
#           tf.reset_default_graph()
#           session = tf.Session(config=session_config)
#           ....
```
The problem disappears.

So removing code that _does not execute_ fixes the problem.

**Comment by kdavis-mozilla** [comment]
**Addendum**: This behavior is not consistent, the problem still appears intermittently even if the code above is commented out.

**Comment by kdavis-mozilla** [comment]
Removing the import
```
from util.shared_lib import check_cupti
```
Solves the problem consistently. 

It appears as if module initializations triggered by that import have binding(s) to C/C++ that are buggy. This is not surprising as the method `check_cupti()` checks for a profiling lib and thus has to probe at a lower level than standard python code.

**Comment by lissyx** [comment]
Woops. Probably a quick fix would be to move the import within the `if do_fulltrace` ?

**Comment by kdavis-mozilla** [comment]
I can try.

**Comment by kdavis-mozilla** [comment]
Does not work....
```
...
Not publishing, missing some required environment variables: ['ds_website_server_fqdn', 'ds_website_server_root', 'ds_website_privkey', 'ds_website_username']
But maybe this is what you wanted, after all ...
Segmentation fault (core dumped)
```

**Comment by kdavis-mozilla** [comment]
For the time being I'm just going to remove the import and `do_fulltrace` code until we have a longer term solution.

**Comment by lissyx** [comment]
That seems really really strange, if you have:
```
if do_fulltrace:
    from util.shared_lib import check_cupti
    check_cupti()
```

and nothing that enables do_fulltrace, then the import should not be done, why would the segfault happen?

**Comment by kdavis-mozilla** [comment]
I don't know why. I can just say it does.

I think worrying about why is a longer term problem. Near term I'm just going to remove the `do_fulltrace` code.

**Comment by kdavis-mozilla** [comment]
I've introduced issue #442 for the longer term problem

**Comment by lissyx** [comment]
Maybe https://github.com/tensorflow/tensorflow/commit/905662a1c047f314ad295e27d2e2a00b4aa51e90 ?

**Comment by lissyx** [comment]
@andi4191 Current https://github.com/mozilla/tensorflow v1.0.0-warpctc branch should include the fix mentionned above. If you update the virtualenv with this Python PIP package, we should be able to know if the segfault at the end of training you saw earlier is actually fixed: https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.v1.0.0-warpctc.gpu/artifacts/public/tensorflow_gpu_warpctc-1.0.1-cp27-cp27mu-linux_x86_64.whl

**Comment by lissyx** [comment]
I switched from 1.0.0 branch to some 1.3.0rc0 master-based, so that issue is probably not a problem anymore. I could reproduce a segfault at runtime using taskcluster-build python packages to perform training on TaskCluster, but that disappeared as soon as I switched to the new master-based builds. So I guess we can safely consider this to be fixed, now.
