### ISSUE TITLE
Import Error after installanation on ubuntu 16.04

### ISSUE THREAD

**Issue by saurabhvyas** [mozilla/DeepSpeech#444]
I just followed readme file instructions and got this error 

```
saurabhorange@orangepc:~/deepspeech$ ./bin/run-ldc93s1.sh
+ export ds_importer=ldc93s1
+ export ds_train_batch_size=1
+ export ds_dev_batch_size=1
+ export ds_test_batch_size=1
+ export ds_n_hidden=494
+ export ds_epochs=50
+ [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py
Traceback (most recent call last):
  File "DeepSpeech.py", line 21, in <module>
    from util.spell import correction
  File "/home/saurabhorange/deepspeech/util/spell.py", line 2, in <module>
    import kenlm
ImportError: /home/saurabhorange/anaconda2/lib/python2.7/site-packages/kenlm.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

```

**Comment by kdavis-mozilla** [comment]
Did you run
```bash
pip install -r doc/requirements.txt
```

**Comment by saurabhvyas** [comment]
@kdavis-mozilla Yes I did , @reuben I already have clean version of libstdc++6 preinstalled

**Comment by kdavis-mozilla** [comment]
What does 
```bash
saurabhorange@ubuntu:~$ ldd /home/saurabhorange/anaconda2/lib/python2.7/site-packages/kenlm.so
```
print?

**Comment by saurabhvyas** [comment]
![image](https://cloud.githubusercontent.com/assets/6899784/24001594/9081be58-0a84-11e7-83e7-255b2ad7968a.png)

**Comment by lissyx** [comment]
This shows that your kenlm.so is linked against a different libstdc++ and others. That seems a bit strange. How did you installed it on your system ?

**Comment by saurabhvyas** [comment]
I simply followed the instructions from read me file here -> https://github.com/mozilla/DeepSpeech

**Comment by kdavis-mozilla** [comment]
What does the following command yield
```bash
saurabhorange@ubuntu:~$ nm -D /home/saurabhorange/anaconda2/lib/lidsdtc++.so.6 | grep basic_stringstreamIcSt11char_traitsIcESaIcEE
```

**Comment by saurabhvyas** [comment]
Here is the output
```
saurabhorange@orangepc:~/deepspeech$  nm -D /home/saurabhorange/anaconda2/lib/lidsdtc++.so.6 | grep basic_stringstreamIcSt11char_traitsIcESaIcEEnm: '/home/saurabhorange/anaconda2/lib/lidsdtc++.so.6': No such file
saurabhorange@orangepc:~/deepspeech$ 

```

**Comment by kdavis-mozilla** [comment]
Did I type something wrong? The file should be there according to the previous `ldd` call.

**Comment by saurabhvyas** [comment]
I tried it again its still showing the same thing

```
saurabhorange@orangepc:~$ nm -D /home/saurabhorange/anaconda2/lib/lidsdtc++.so.6 | grep basic_stringstreamIcSt11char_traitsIcESaIcEE
nm: '/home/saurabhorange/anaconda2/lib/lidsdtc++.so.6': No such file
saurabhorange@orangepc:~$ 

```

**Comment by kdavis-mozilla** [comment]
What does the following print?
```bash
saurabhorange@orangepc:~$ ls /home/saurabhorange/anaconda2/lib/lidsdtc*
```

**Comment by saurabhvyas** [comment]
```
saurabhorange@orangepc:~$ ls /home/saurabhorange/anaconda2/lib/lidsdtc*
ls: cannot access '/home/saurabhorange/anaconda2/lib/lidsdtc*': No such file or directory

```

**Comment by kdavis-mozilla** [comment]
It appears as if you don't have `lidsdtc++.so.6` installed or it's installed in a location that `kenlm.so` does not expect.

I'd suggest taking the advice of @reuben and installing `libstdc++6` with `apt-get` then maybe re-installing the dependencies 
```bash
pip install -r doc/requirements.txt
```
If that doesn't work, I'd suggest contacting [Victor Chahuneau](https://github.com/vchahun) as he wrote the python binding to the kenlm and it appears as if that's failing.

**Comment by saurabhvyas** [comment]
actually I uninstalled libstdc++6 before reinstalling it , but I noticed it asked me that system could be severely affected by uninstalling it , I continued anyway , I saw many packages including grub and essential software getting uninstalled along the way , even apt-get got removed , I had to reinstall ubuntu from scratch , Um so I think Ill close this for now because Ill experiment something different but Ill check again in future , Thanks for the help :)

**Comment by kdavis-mozilla** [comment]
Oh no! I didn't want you to _uninstall_  `libstdc++6`! Only install it. Sorry.

**Comment by saurabhvyas** [comment]
I see but its fine , It took only 20 minutes to install back , I only keep ubuntu for playing with stuff and learning

**Comment by josabandal1993** [comment]
Hi is this one already solved? I am also experiencing same problem I get an error:
"ImportError: /home/jakesabandal/anaconda3/lib/python3.6/site-packages/kenlm.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
"
when I ran python DeepSpeech.py --help

hope you can help me. Thanks.

**Comment by kdavis-mozilla** [comment]
@josabandal1993 Did you see the similar discussion[[1](https://github.com/mozilla/DeepSpeech/issues/555#issuecomment-298251035)] where a solution was proposed for anaconda.

**Comment by alughaGmbH** [comment]
@saurabhvyas   I am following https://github.com/mozilla/DeepSpeech. 
the files tells , 
Using the Node.JS package
You can download the Node.JS bindings using npm:

**npm install deepspeech.** 

but I get : 
>deepspeech@0.1.0 install /home/megha/node_modules/deepspeech
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.v1.0.0-warpctc.arm/artifacts/public/v0.1.0/Release/deepspeech-v0.1.0-node-v57-linux-x64.tar.gz .......

can you track my mistake ?I am struck here and not able to move forward.

**Comment by lissyx** [comment]
@alughaGmbH Please avoid hihacking already-closed issues with unrelated problems. Help with installation should be requested in https://discourse.mozilla.org/c/deep-speech and please provide more details on your system.
