### ISSUE TITLE
Changes for training resume should not override the last checkpoint.

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#447]

**Comment by reuben** [comment]
This and #407 are the same (underlying) issue. There's a fix in #415.

**Comment by kdavis-mozilla** [comment]
Yeah I agree the underlying problem is basically the same. But, the issues that lead to the underlying problem take slightly different paths there.

Issue #447 (Changes for training resume should not override the last checkpoint) is more worried about restarting overwriting the last checkpoint where as #407 (There's no way to restore a checkpoint and do just testing) comes at it from a slightly different view point.

In the review of PR #415 I mentioned that there's still a problem with the PR. It wasn't even a theoretic problem either. At the time, the machine actually crashed on the last epoch before testing finished, and I had to restart to publish the results to the website. With the PR this wouldn't have been possible.

**Comment by reuben** [comment]
Fixed by #478.
