### ISSUE TITLE
Problem loading a language model

### ISSUE THREAD

**Issue by nebgru** [mozilla/DeepSpeech#456]
I just started using this framework, so perhaps I'm missing something...
Running on Lubuntu 16.04, cpu only, after starting the training, I'm getting
IOError: Cannot read model './data/lm/lm.binary'
If I disable the lm correction for wer report, the training proceeds fine.
Any ideas?

**Comment by kdavis-mozilla** [comment]
Did you install git lfs[[1](https://git-lfs.github.com/)] _then_ clone the repo? 

The README.md[[2](https://github.com/mozilla/DeepSpeech/blob/master/README.md#prerequisites)] indicates git lfs is required, but doesn't say explicitly that you need to install git lfs first, then do the clone.

However, you do need to install git lfs first, then close the repo.

**Comment by nebgru** [comment]
Thank you for the quick reply. That was the solution. I never used git-lfs before, so I wasn't aware that it needs to hook up to git first to resolve deps. Cheers
