### ISSUE TITLE
is deepSpeech good enough?

### ISSUE THREAD

**Issue by joyousrabbit** [mozilla/DeepSpeech#487]
Hello Mozilla, thanks for this great work. I'm newcomer in speech recognization. I noticed that DeepSpeech is paper of 2014, now it is 2017. So do you think DeepSpeech is good enough? What about DeepSpeech 2? Do you suggest some more recent papers?

Hope reply. Thanks.

**Comment by mach327** [comment]
I am also a newcomer. 

The [`ds2-v2`  branch](https://github.com/mozilla/DeepSpeech/tree/ds2-v2) seems to be an initial DeepSpeech2 implementation. Make sure to also read #479 if you want to use it.

For the "good enough" question, if you read through the [open issues](https://github.com/mozilla/DeepSpeech/issues), you'll see a number that follow the format of `compare x vs y ... vs z`, presumably for making this implementation better and further research. 
If you're as new as me, those issues may provide topics to google and read about.

I would point you to interesting papers, but I'm _very_ new, and so can't really help there.

**Comment by kdavis-mozilla** [comment]
@joyousrabbit I'm going to close this as it seems the associated question has been answered.
