### ISSUE TITLE
Job submission to internal cluster

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#493]
- Command line tool to submit jobs
- Jobs queued executed in order (Maybe with priority)
- Tool should support job interruption
- White-list users (possible external users)
- Initially intranet
- “Job spec” submitted with job to indicate required resources

**Comment by kdavis-mozilla** [comment]
As far as I know all of this is supported by SLUM.

**Comment by tilmankamp** [comment]
Yes, it does and we will use it for that.
