### ISSUE TITLE
mfcc vs filterbanks

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#501]
Hey @reuben and mozilla team, in the original Baidu DeepSpeech-1 paper, the input is filterbanks instead of mfcc. Also you had pushed some changes to use that. Have you compared the results of both on any dataset like Switchboard. Any visible insight will be great

**Comment by reuben** [comment]
We have not compared MFSC vs MFCC yet, mostly due to all the different experiments we want to do competing for server time. Issue #353 is open for exactly this question.
