### ISSUE TITLE
How to test a trained model ?

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#503]
How to test the output of a new batch (without providing ground truth transcriptions) on a fully trained model similar to TED corpus ?

And the accuracy reported in test corpus seems to CER . According to the code , its somewhat like mean levenshtein distance . Why is it printed as accuracy since it decreases as the CER decreases ?

**Comment by kdavis-mozilla** [comment]
I'm not sure I understand your question. It's impossible to test a batch or epoch without ground truth transcriptions as the system can't know if it is correct or not.

On the CER vs accuracy point I think you're right. I'll file an issue.

**Comment by pdcoded** [comment]
No what I mean to say is , I want to feed an batch of audio files as a test batch and want to see the output. I can use that output to calculate WER against the ground truth transcriptions. Does the question make sense now ?

**Comment by kdavis-mozilla** [comment]
@pdcoded Now it makes sense.

You want to do STT batch processing of audio. Converting several audio files to text.

We currently don't have a means to do that in our code, but it shouldn't be too hard to hack together.

**Comment by pdcoded** [comment]
Thanks

**Comment by elpimous** [comment]
@kdavis-mozilla 
Hello,
I'd like to do STT too
Do you have an example for testing a wav file ?
Best.
Vincent

**Comment by kdavis-mozilla** [comment]
Did you see this thread[[1](https://github.com/mozilla/DeepSpeech/issues/752#issuecomment-320057177)]

**Comment by priteshpj** [comment]
Any updates on batch STT?
