### ISSUE TITLE
GPU under-utilized

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#507]
I my running my model on 8NVIDIA GPU machine on GCP. During the training epoch, if I look at the snapshot of gpu usage using nvidia-smi , I see only 1 or 2 machines being 50-80% used. Rest 6 machines are always unused or hardly 1-2% . With tower concept since the architecture supports synchronous distributed training on all the GPU, I wonder why are some machines under-used?

**Comment by kdavis-mozilla** [comment]
I haven't used the code on GCP. However, on our machine we get 99% simultaneous utilization on all of our GPU's for TED and Librivox.

What data set are you using and what are the batch sizes?

**Comment by pdcoded** [comment]
I am using around 6 hours of polly generated synthetic data . The training set has around 4000 wav files and my batchsize is 6. To complete 300 epochs , it takes around 6 hours .

**Comment by kdavis-mozilla** [comment]
How much memory does each GPU have?

**Comment by pdcoded** [comment]
12GB

**Comment by kdavis-mozilla** [comment]
Could you try running our TED script and see what GPU utilization is? In other words run
```bash
bin/run-ted.sh
```

**Comment by pdcoded** [comment]
Sure . Doing that in sometime

**Comment by pdcoded** [comment]
But it will take time to download the huge corpus. What i am doing is similar to the ted exercise , just that i am prefeeding wav and txt files of my synthetic data and skipping a lot of steps like converting sph to wav , stm to txt etc

**Comment by kdavis-mozilla** [comment]
Yes it will take time to download. But in debugging what you're doing I can't determine if its a problem with your importer/batch sizes or something with GCP unless I have you using something I know to work. Otherwise I'm just guessing at to what you are or are not doing.

**Comment by kdavis-mozilla** [comment]
@pdcoded Any news on this?

**Comment by pdcoded** [comment]
Yes, I am running the ted training model. so this is a snapshot when when optimization has just started. I have reduced the hidden layers to 600 .![ted-training_1stepoch](https://cloud.githubusercontent.com/assets/9830931/24803207/19f5c752-1bc8-11e7-819e-2bd414d43560.png)

**Comment by kdavis-mozilla** [comment]
@pdcoded Can you run the model with the full width not 600?

**Comment by pdcoded** [comment]
ok doing that . From the download of the ted corpus till 1st epoch run, ideally how much time it should take ? My 1st epoch has not been trained yet and its been 40mins

**Comment by kdavis-mozilla** [comment]
I can't say how long a epoch takes on your machine. It depends on the GPU's, and I've not used GCP's GPU's so I can't say.

However, as a point of reference, our machine has about 44 TFlops of GPU compute and takes about 2h24m for one epoch of TED with the GPU's generally at 99% utilization.

**Comment by kdavis-mozilla** [comment]
@pdcoded I guess one thing you have to accept in this game is that training takes time. :-)

**Comment by pdcoded** [comment]
Yeah true .That's what I was validating .  my GPU utilization is now increasing. Can you tell me what is the computational power factor  compared to the one that you are using ? I am using a 8 GPU one (the last one in this link )https://cloud.google.com/compute/docs/gpus/

**Comment by kdavis-mozilla** [comment]
Looking at the `nvidia-smi` output you're on `K80`'s. These are unfortunately relatively slow.

They're packaged two GPU's per card and each card is advertised at 8.73 TFlops per card. So, 4.365 TFlops per GPU. 

So, you're using 8 GPU's each at 4.365 TFlops that's 34.92 TFlops total. So, generally you have about 79.36% the compute of our 4 GPU server. So, an epoch should take about 3h2m

**Comment by pdcoded** [comment]
Thanks for the quick maths.Ok for 600 hidden layer, it took me around 1h  to train one epoch. I think we can close the issue for now. I will keep you posted for the full hidden width training later since I will be switching to my own dataset training now.
