### ISSUE TITLE
How to use a list of phone

### ISSUE THREAD

**Issue by msobhan69** [mozilla/DeepSpeech#509]
I have a list of phone in my ASR corpus. The list of phone includes 32 English characters (letter case).
How to train DeepSpeech with the corpus?
Should I just create a dataset that includes text and wav files with the same name?d

**Comment by kdavis-mozilla** [comment]
We train on only lower case text for now, but this can easily be changes. So one would train on wav + lowercase text.

If you want to do this right away, I'd suggest looking at how the various importers[[1](https://github.com/mozilla/DeepSpeech/tree/master/util/importers)] work.

However, if you can wait a few days, I'd suggest waiting on the "Importer Cleanup" pull request[[2](https://github.com/mozilla/DeepSpeech/pull/506)] as it simplifies importing a corpus.
