### ISSUE TITLE
Most critical hyperparameter tuning for Switchboard corpus

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#515]
I am working with a conversational speech corpus similar to Switchboard. What would be the most critical hyperparameter tuning to capture pitch and accent invariance ?

**Comment by kdavis-mozilla** [comment]
Training data with various pitches and accents is the best bulwark against overfitting an accent or pitch.

FWIW, the team is on the #vaani channel on irc.mozilla.org. GitHub issues are awkward for discussions so I figure I'd point you there. Instructions on how to connect are here: https://wiki.mozilla.org/IRC

**Comment by pdcoded** [comment]
Sure :)
