### ISSUE TITLE
Convolution layer ahead of non-recurrent layers

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#516]
Has the team tried implementing convolution layer to capture the spatial invariance, ahead of the non -recurrent layers similar to the recent DeepSpeech-2 paper? 

According to the code, will it bring in any major issues since I am planning to add a convolutional layer ahead of a non-recurrent layer? Planning to use something similar http://ttic.uchicago.edu/~haotang/speech/06707746.pdf

**Comment by pdcoded** [comment]
@reuben you would be the right person to answer since you are working on it :) Any heads up will be great :)

**Comment by reuben** [comment]
I've linked to the WIP branch on your other issue. As for your second paragraph, I'd love to see what results you can get, it sounds like a very cool approach.

FWIW, the team is on the #vaani channel on irc.mozilla.org. GitHub issues are awkward for discussions so I figure I'd point you there. Instructions on how to connect are here: https://wiki.mozilla.org/IRC

**Comment by pdcoded** [comment]
yea :)  But I am sure it will be equally useful for the community here when they will have a rich context and similar questions.

**Comment by kdavis-mozilla** [comment]
@pdcoded I'm going to close this. Search engines should still be able to find it.
