### ISSUE TITLE
Testing epoch issue

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#522]
So I have trained the model on TED data for 10 epochs. Just wanted to re-confirm few things 
1) So it trains on 0-9 epoch and the results printed for 10th epoch is for testing data as shown on the console? 
2) Now I have saved my checkpoint. If I dont change the epoch,it essantially does testing again ? 
3)If I change my testing data folder to a new dataset, and start it from the same checkpoint, will it do the testing in same amount of time ? There is a significant gpu usage for testing I believe

**Comment by pdcoded** [comment]
Need some help here @kdavis-mozilla @reuben

**Comment by kdavis-mozilla** [comment]
1. Results are printed for the tests applied after the 9th epoch finished but before the 10th starts both being 0 based.

2. What do you means by "change the epoch"?

3. I'm not sure if I know what you mean by "change my testing data folder to a new dataset". But I assume you mean you change the test data set. With that assumption, it's completely dependent on the new data set how long the test will take.

@pdcoded In future could you take these discussions to the IRC channel as they're better addressed there.
