### ISSUE TITLE
is GPU must to execute this code

### ISSUE THREAD

**Issue by nomadiccoder** [mozilla/DeepSpeech#523]
Hi Team,
   I am trying to execute the script DeepSpeech.py but it fails with error 
Traceback (most recent call last):
  File "DeepSpeech.py", line 29, in <module>
    from util.spell import correction
  File "/Users/boredmgr/work/speech-rnd/DeepSpeech/util/spell.py", line 3, in <module>
    import kenlm
ImportError: No module named kenlm

so the query : Is GPU a requirement to execute this script?

**Comment by kdavis-mozilla** [comment]
You need to install kenlm. See the [Install](https://github.com/mozilla/DeepSpeech#install) section of the README.md.
