### ISSUE TITLE
How to print the output of only the acoustic model ?

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#526]
I am in the process of improving the language model but for that I want to see the output of acoustic model separately to make an assessment of how bad/good the output becomes after adding the language model.

**Comment by kdavis-mozilla** [comment]
Remove the line [DeepSpeech.py#L693.](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L693)
```python
     ....
     corrected = correction(decoding)
     ....
```
and replace it with
```python
     ....
     corrected = decoding
     ....
```
