### ISSUE TITLE
2 GB NVIDIA Graphics Card

### ISSUE THREAD

**Issue by pandeydivesh15** [mozilla/DeepSpeech#527]
The project's [README](https://github.com/mozilla/DeepSpeech/blob/master/README.md) suggests using a GPU with a minimum of 8 GB VRAM. Is this a strict restriction? I mean, I have previously used my 2 GB graphics card for some tasks. I am only testing Deep Speech with small datasets on my laptop, so will 2 GB GPU create problems ?

Note: Currently, I am using Deep Speech on CPU.

**Comment by kdavis-mozilla** [comment]
If you're not using the GPU, a good GPU is not required.

However, if you want to train on larger (1000 hours) data sets, a good GPU will be required to train in a reasonable (week or less) time frame.
