### ISSUE TITLE
Ability to specify number of checkpoints that are kept in checkpoint dir

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#537]
Pass a [CheckpointSaverHook](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointSaverHook) instance with a custom `Saver` to `MonitoredTrainingSession` and expose the saver's `max_to_keep` property as a `FLAGS` variable.
As discussed in https://github.com/mozilla/DeepSpeech/issues/534 .

**Comment by andi4191** [comment]
@tilmankamp: how many files are expected to be configured (max_to_keep) as a FLAG variable ? By default its 5. 

The filenames by default are named as model.ckpt-XXX. Should we change that or use as it is?
