### ISSUE TITLE
layer_1 full connection vs conv2d

### ISSUE THREAD

**Issue by joyousrabbit** [mozilla/DeepSpeech#539]
Hello, why at layer_1 the full connection? Considering the full_connection is very heavy, is the traditional conv2d & pool_max a better choice?

I read the deepspeech paper but no details. 

Hope reply thanks.

**Comment by kdavis-mozilla** [comment]
The Deep Speech paper[[1](https://arxiv.org/abs/1412.5567)] uses a fully connected first layer, see section 2 of the paper.

We are also implementing Deep Speech 2 variants[[2](https://github.com/mozilla/deepspeech/tree/ds2-v2)][[3](https://arxiv.org/abs/1512.02595)] which include convolutional layers.

**Comment by joyousrabbit** [comment]
@kdavis-mozilla Hello Davis, thanks for fast reply. Which one do you think is better? Did you do some experiment for the comparation?

**Comment by kdavis-mozilla** [comment]
We currently don't have any results for Deep Speech 2 as there's a bug in the Batch Norm implementation we're currently trying to work around.

However, we assume the Deep Speech 2 architecture will perform better.

**Comment by joyousrabbit** [comment]
@kdavis-mozilla Yes, should I also change the full connection of deepspeech 1 (this project) to the conv2d&poolmax for a better performence and lighter weights?

**Comment by kdavis-mozilla** [comment]
@joyousrabbit No we're purposely keeping the two architectures separate to cleanly compare performance

**Comment by kdavis-mozilla** [comment]
@joyousrabbit However, if your interested in benchmarking various architectures. We've several experiments[[1](https://github.com/mozilla/deepspeech/issues?q=is%3Aopen+is%3Aissue+label%3A%22server+time%22)] we want to bechmark but are on hold while we wait for our new hardware.

If you have questions about any one of the experiments, which are only lightly documented, feel free to comment on the associated issue.

**Comment by joyousrabbit** [comment]
@kdavis-mozilla Sure, thanks, I just think the full connection is very heavy, for 26x19x2048 maybe OK, but if we have larger features ...
