### ISSUE TITLE
mfcc 26 vs 80

### ISSUE THREAD

**Issue by joyousrabbit** [mozilla/DeepSpeech#540]
Hello, I read in the deepspeech paper that it used a 80 array vector as feature. In your project it's only 26 quite less than 80, will it causes the drop down of performence?

**Comment by kdavis-mozilla** [comment]
We use different features MFCC vs their homegrown features. So the 80 vs 26 is a bit apples vs oranges.

As to if it causes a drop in performance, I'm not sure as we've not implemented their homegrown features.
