### ISSUE TITLE
README needs to be updated to mention recent importer changes

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#541]

**Comment by sgt101** [comment]
Hi - just to comment on this, I've had a lot of trouble with my proxy and the new importers. I've self solved some of this by using urllib2 and not using base. maybe_download which seems to cal urllib and ends up producing a request that my proxy regards as malformed and therefore bounces (dunno why...) 

I fully realize that this is to do with my setup and not the general experience but it might be worth flagging?

**Comment by braindead** [comment]
I faced issued with the importer as well. It took a long time to download and didn't show the progress properly. I ended up wget'ing the tar.gz files separately and running the importer script afterwards. That created the csv files correctly.

**Comment by reuben** [comment]
Oops, I completely forgot about this issue. I created PR #558 fixing this. I didn't mention anything about the proxy issues because that part didn't change with the refactor, base.maybe_download was always used. I'm gonna mention that in the wiki instead.
