### ISSUE TITLE
Interested in benchmarks (client)

### ISSUE THREAD

**Issue by jacobjennings** [mozilla/DeepSpeech#548]
Preface: I'm new to ML, go easy :)

I'm very exited to hear that large trained models will be published soon. I'm curious about one thing, since I'm working with constrained hardware. For a larger trained model (600-1000 Mb), I'd love to see a benchmark of "seconds of speech processed per second" on any system as a baseline. Particularly, I'm interested to see if a DeepSpeech client is in the realm of viability on something like an iPhone for offline speech applications.

Thanks to all contributors!

**Comment by kdavis-mozilla** [comment]
Our goal is to allow for off-line speech applications, e.g. iPhone ot Raspberry Pi 3. As part of that we're working on compressing models using quantization (32 bits to 8 bits) and [SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition).

However, it's a bit early for us to start publishing benchmarks as we're still in the process of finalizing our architecture and means of quantization.

**Comment by captainnurple** [comment]
Hi @kdavis-mozilla, curious what your ROUGH timeline estimate is for off-line recognition esp. on mobile device. Thanks!

**Comment by kdavis-mozilla** [comment]
Very rough, next 3-6 months.

**Comment by monouser7dig** [comment]
@kdavis-mozilla any news on this one? thanks

**Comment by saurabhvyas** [comment]
@kdavis-mozilla Very curious how much latency you get on rpi 3, and do you have a docker image for it, so we can play with it ?
