### ISSUE TITLE
Coordinator stopped

### ISSUE THREAD

**Issue by braindead** [mozilla/DeepSpeech#551]
The following exception occurs during training, during the validation loss calculation

```
I Training of Epoch 15 - loss: 30.071040
Traceback (most recent call last):
  File "DeepSpeech.py", line 1628, in <module>
    tf.app.run()
  File "/home/rajiv/ds-env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1591, in main
    train()
  File "DeepSpeech.py", line 1497, in train
    job = COORD.next_job(job)
  File "/home/rajiv/ds-env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 478, in __exit__
    self._close_internal(exception_type)
  File "/home/rajiv/ds-env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 511, in _close_internal
    self._sess.close()
  File "/home/rajiv/ds-env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 739, in close
    self._sess.close()
  File "/home/rajiv/ds-env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 827, in close
    self._coord.join()
  File "/home/rajiv/ds-env/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 390, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: Thread-27 Thread-8 Thread-21 Thread-20 Thread-12 Thread-9 Thread-22 Thread-13 Thread-5 Thread-10 Thread-23 Thread-14 Thread-11 Thread-24 Thread-18 Thread-15 Thread-7 Thread-19 Thread-25 Thread-16 Thread-6 Thread-26 Thread-4 Thread-17
```

**Comment by guevaralb** [comment]
I got the same trouble, Im testing with spanish phrases, I think that accentued words trigger this error in my case...

**Comment by kdavis-mozilla** [comment]
@guevaralb Code changes are required to deal with accents. So, there is no expectation that accented text will work. What @braindead is seeing is something else.

**Comment by kdavis-mozilla** [comment]
@braindead Did this occur with code that included 843f55d?

In other words, I'm wondering if 843f55d fixes this problem as 843f55d registers the threads with the Coordinator and thus should cause the Coordinator to wait on the registered threads.

**Comment by braindead** [comment]
@kdavis-mozilla Yes, my local brach has the sha 843f55dbe2f270ffa43c7e21d679bf9b0313cf24

**Comment by kdavis-mozilla** [comment]
@braindead Thanks for the info! So, must be something else.

**Comment by braindead** [comment]
I think it started happening after 96ebba516f4d5aeb7edec1d394dca4bf167883df. The first 10 epochs didn't have this issue. After I pulled 96ebba516f4d5aeb7edec1d394dca4bf167883df this started.

**Comment by kdavis-mozilla** [comment]
@braindead What version of TensorFlow are you using?

**Comment by braindead** [comment]
@kdavis-mozilla 1.01.

**Comment by machuanli** [comment]
I got this problem.
```
mayaxiong@slave2:~/DeepSpeech$ ./bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/home/mayaxiong/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batc
h_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/mayaxiong/.local/share/deepspeech/ldc93s1Traceback (most recent call last):
  File "DeepSpeech.py", line 25, in <module>
    from util.spell import correction
  File "/home/mayaxiong/DeepSpeech/util/spell.py", line 3, in <module>
    import kenlm
ImportError: /home/mayaxiong/anaconda3/lib/python3.5/site-packages/kenlm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

```
It shows that the kenlm is not imported successfully, what should I do to tackle it?

**Comment by lissyx** [comment]
Given the import error, I would put my money on discrepency wrt C++11/Strings stuff ; see https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by kdavis-mozilla** [comment]
@machuanli As this is not related to the Coordinator stopped issue I've opened #555 to cover your problem.

**Comment by machuanli** [comment]
@kdavis-mozilla  
forget to say, a warning occurred when I running setup.py,
does it make any sense?
And, after I had installed kenlm on another machine, it is imported successfully. The machine's information is as follows:
`machuanli@machuanli-All-Series:~$ python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kenlm
>>> 
`
so, i am really confused. the version of gcc of the two is the same......

**Comment by kdavis-mozilla** [comment]
@machuanli Could you copy your last comment in to issue #555?  Thanks

**Comment by machuanli** [comment]
@kdavis-mozilla 
ok,the comment is now in #555o

**Comment by kdavis-mozilla** [comment]
@machuanli Thanks!

**Comment by harinderbedi** [comment]
Hi everyone, Do we have update on this? I am getting this issue locally when i run one of the sample example "bin/run-librivox.sh" and the error is same "RuntimeError: Coordinator stopped with threads still running: Thread-12"..

This error does not appear when i run other sample example "bin/run-ldc93s1.sh".

Thoughts?

**Comment by tilmankamp** [comment]
@harinderbedi 
Is this happening immediately at the start of the training or later?
Which version of TensorFlow do you use?

**Comment by harinderbedi** [comment]
So as soon as i execute a command, it waits for 2-3mins and then throw the error..

**Comment by tilmankamp** [comment]
@harinderbedi Could you retry with `--train_batch_size 1`?

**Comment by harinderbedi** [comment]
yes did that, no difference and got the same error..
But i got your point...

It is quite interesting that below command gives error 
`python -u DeepSpeech.py --train_files /home/someDataset/files/someDataset-train.csv --dev_files /home/someDataset/files/someDataset-dev.csv --test_files /home/someDataset/files/someDataset-test.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1`

and this command does not (where the difference is only dataset):

`python -u DeepSpeech.py --train_files /home/DS/data/librvox/librivox-train-clean-100.csv --dev_files /home/DS/data/librvox/librivox-train-clean-100.csv --test_files /home/DS/data/librvox/librivox-train-clean-100.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1`


Thoughts ?

**Comment by harinderbedi** [comment]
The difference between the dataset are 1. it is bigger dataset 2. different language

Should i checkout code from history which is not effected with this bug ?

**Comment by tilmankamp** [comment]
Were both checkpoint directories clean before the runs?

**Comment by harinderbedi** [comment]
Yes. i ran it again with different new checkpoints directories..
So i will repeat one more time for clarity -

1. This works:
```
checkpoint_dir=/root/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files /home/root_speechRecoginition/DeepSpeech/DeepSpeech/data/librvox/librivox-train-clean-100.csv --dev_files /home/root_speechRecoginition/DeepSpeech/DeepSpeech/data/librvox/librivox-train-clean-100.csv --test_files /home/root_speechRecoginition/DeepSpeech/DeepSpeech/data/librvox/librivox-train-clean-100.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1
I STARTING Optimization
```


2. This does not work
```
checkpoint_dir=/root/.local/share/deepspeech/spanish
+ python -u DeepSpeech.py --train_files /home/spanish/files/spanish-train.csv --dev_files /home/spanish/files/spanish-dev.csv --test_files /home/spanish/files/spanish-test.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/spanish
Traceback (most recent call last):
  File "DeepSpeech.py", line 1647, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1610, in main
    train()
  File "DeepSpeech.py", line 1516, in train
    job = COORD.next_job(job)
```


One of the suggestion i got from my colleague is that as spanish dataset (different encoding characters) has some special characters so that could be a problem , Thoughts ?

**Comment by harinderbedi** [comment]
So @tilmankamp : It is an encoding issue.. i just put three lines in dataset.. 1. without special characters which work and 2. with special characters which does not work. 

But we are getting misleading Error trace, so may be actual error is eaten somewhere else, i guess. I hope this help someone..

Now i will change the batch size.. i think there is some issue as well.

**Comment by kdavis-mozilla** [comment]
It's definitely the case that non-ascii characters can cause problems.

The Spanish á, é, í, ó, ú, ü, ñ, ¿, and ¡ can definitely cause problems. Maybe take a look at how we normalize, for now, to ascii. For example here[[1](https://github.com/mozilla/DeepSpeech/blob/2ad3594173f8ccbc9e7384533a80d47c0dfb7c1b/bin/import_librivox.py#L161)].

The algorithm itself is capable of being modified to deal with non-ascii characters. However, initially we are targeting English; so, we didn't put in the code to deal with non-ascii characters. But doing so shouldn't be too hard.

**Comment by tilmankamp** [comment]
@harinderbedi 
You are right - the actual error is eaten somewhere else and this is one of the most annoying problems at the moment. Am still collecting input on which root cause errors are surfacing as "coordinator stopped" ones. So your input definitely helps.

**Comment by harinderbedi** [comment]
Thank you all then i know what to do.

**Comment by pdcoded** [comment]
@kdavis even I am getting this error for ds1 . Infact I have a modified ds2 architecture which runs fine with the dataset but ds1 throws me this error. It has nothing to do with non-ascii characters in my case since everything is 26 english character + space . This error pops up immediately at the start of optimization. 
I think it has something to do with larger dataset and recent commits since it runs perfectly fine with ds2.

**Comment by kdavis-mozilla** [comment]
@pdcoded What data set are you using?
