### ISSUE TITLE
understanding test epoch

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#552]
When I run the ldc93s1 dataset , I am unable to understand the logic to why it sometimes skips printing src and res for test ? Also sometimes when you rerun from a checkpoint , it weirdly skips to a epoch 700 or 800 when I haven't trained it on that many epochs even

**Comment by kdavis-mozilla** [comment]
If WER=0 it does not print src and res.

I've never seen it skip to epoch 700-800. Could you remove the existing checkpoint, reproduce the strand skipping results, and post the steps to repo here? Thanks.

**Comment by pdcoded** [comment]
Okay would reproduce the steps and post it . If WER is zero it doesnt print but can I enable it ? Also does it include the zero WER while averaging out the results ?

**Comment by reuben** [comment]
Use the [source](https://github.com/mozilla/DeepSpeech/blob/a2731a3e9e331aa712544bd4c7e1938b8f46bf0d/DeepSpeech.py#L683-L714), Luke.

**Comment by pdcoded** [comment]
Thanks @reuben . worked out ! Posting the other issue soon.

**Comment by pdcoded** [comment]
I am not able to reproduce the issue. It can be closed till I reproduce it again.
