### ISSUE TITLE
kenlm is not imported successfully

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#555]
@machuanli got this problem.
```
mayaxiong@slave2:~/DeepSpeech$ ./bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/home/mayaxiong/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batc
h_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/mayaxiong/.local/share/deepspeech/ldc93s1Traceback (most recent call last):
  File "DeepSpeech.py", line 25, in <module>
    from util.spell import correction
  File "/home/mayaxiong/DeepSpeech/util/spell.py", line 3, in <module>
    import kenlm
ImportError: /home/mayaxiong/anaconda3/lib/python3.5/site-packages/kenlm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

```
It shows that the kenlm is not imported successfully, what should I do to tackle it?

**Comment by kdavis-mozilla** [comment]
Given the import error, I would put my money on discrepency wrt C++11/Strings stuff ; see https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by kdavis-mozilla** [comment]
@machuanli @lissyx

**Comment by kdavis-mozilla** [comment]
@machuanli I've got to agree with @lissyx this seems like a problem with C++11 strings and is related to kenlm installation[[1](https://github.com/kpu/kenlm#installation)] as opposed to the code in this repo.

**Comment by machuanli** [comment]
I recognized this:

`pandas

progressbar2

python-utils

tensorflow

numpy

scipy

paramiko

pysftp

sox

python_speech_features

pyxdg

bs4

six

https://github.com/kpu/kenlm/archive/master.zip`
does the order of the installation causes the problem？
I have installed kenlm before running this script

**Comment by lissyx** [comment]
No, the order is unrelated. You should make sure that your Python 3.5 has been built with the same ABI as your kenlm module.

**Comment by machuanli** [comment]
forget to say, a warning occurred when I running setup.py,
does it make any sense?
And, after I had installed kenlm on another machine, it is imported successfully. The machine's information is as follows:
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul 2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
so, i am really confused. the version of gcc of the two is the same......

**Comment by lissyx** [comment]
@machuanli We would need more detailed informations on your environment and the steps you followed to install kenlm to help you. Right now, there is nothing actionnable.

**Comment by besanza2014** [comment]
Hello, I'm also have a problem installing: pip install https://github.com/kpu/kenlm/archive/master.zip 
This is part of the error:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tputil/double-conversion\fast-dtoa.cc /Fobuild\temp.win-amd64-3.5\Release\util/double-conversion\fast-dtoa.obj -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    fast-dtoa.cc
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tputil/double-conversion\fixed-dtoa.cc /Fobuild\temp.win-amd64-3.5\Release\util/double-conversion\fixed-dtoa.obj -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    fixed-dtoa.cc
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tputil/double-conversion\strtod.cc /Fobuild\temp.win-amd64-3.5\Release\util/double-conversion\strtod.obj -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    strtod.cc
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-Ic:\users\master engineer\appdata\local\programs\python\python35\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppython/kenlm.cpp /Fobuild\temp.win-amd64-3.5\Release\python/kenlm.obj -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    kenlm.cpp
    .\util/bit_packing.hh(111): warning C4244: '=': conversion from 'uint64_t' to 'uint32_t', possible loss of data
    .\util/bit_packing.hh(138): warning C4244: '=': conversion from 'uint64_t' to 'uint32_t', possible loss of data
    .\util/file_piece.hh(106): warning C4101: 'e': unreferenced local variable
    .\lm/quantize.hh(161): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data
    .\lm/quantize.hh(165): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data
    .\lm/quantize.hh(192): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data
    .\lm/quantize.hh(196): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data
    .\lm/vocab.hh(78): warning C4244: 'return': conversion from '__int64' to 'lm::WordIndex', possible loss of data
    .\lm/vocab.hh(210): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
    .\lm/vocab.hh(211): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
    .\lm/vocab.hh(213): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
    creating C:\Users\MASTER~1\AppData\Local\Temp\pip-0xplkmry-build\build\lib.win-amd64-3.5
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:c:\users\master engineer\appdata\local\programs\python\python35\libs" "/LIBPATH:c:\users\master engineer\appdata\local\programs\python\python35\PCbuild\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" stdc++.lib rt.lib /EXPORT:PyInit_kenlm build\temp.win-amd64-3.5\Release\util\bit_packing.obj build\temp.win-amd64-3.5\Release\util\ersatz_progress.obj build\temp.win-amd64-3.5\Release\util\exception.obj build\temp.win-amd64-3.5\Release\util\file.obj build\temp.win-amd64-3.5\Release\util\file_piece.obj build\temp.win-amd64-3.5\Release\util\float_to_string.obj build\temp.win-amd64-3.5\Release\util\integer_to_string.obj build\temp.win-amd64-3.5\Release\util\mmap.obj build\temp.win-amd64-3.5\Release\util\murmur_hash.obj build\temp.win-amd64-3.5\Release\util\parallel_read.obj build\temp.win-amd64-3.5\Release\util\pool.obj build\temp.win-amd64-3.5\Release\util\read_compressed.obj build\temp.win-amd64-3.5\Release\util\scoped.obj build\temp.win-amd64-3.5\Release\util\spaces.obj build\temp.win-amd64-3.5\Release\util\string_piece.obj build\temp.win-amd64-3.5\Release\util\usage.obj build\temp.win-amd64-3.5\Release\lm\bhiksha.obj build\temp.win-amd64-3.5\Release\lm\binary_format.obj build\temp.win-amd64-3.5\Release\lm\config.obj build\temp.win-amd64-3.5\Release\lm\lm_exception.obj build\temp.win-amd64-3.5\Release\lm\model.obj build\temp.win-amd64-3.5\Release\lm\quantize.obj build\temp.win-amd64-3.5\Release\lm\read_arpa.obj build\temp.win-amd64-3.5\Release\lm\search_hashed.obj build\temp.win-amd64-3.5\Release\lm\search_trie.obj build\temp.win-amd64-3.5\Release\lm\sizes.obj build\temp.win-amd64-3.5\Release\lm\trie.obj build\temp.win-amd64-3.5\Release\lm\trie_sort.obj build\temp.win-amd64-3.5\Release\lm\value_build.obj build\temp.win-amd64-3.5\Release\lm\virtual_interface.obj build\temp.win-amd64-3.5\Release\lm\vocab.obj build\temp.win-amd64-3.5\Release\util/double-conversion\bignum-dtoa.obj build\temp.win-amd64-3.5\Release\util/double-conversion\bignum.obj build\temp.win-amd64-3.5\Release\util/double-conversion\cached-powers.obj build\temp.win-amd64-3.5\Release\util/double-conversion\diy-fp.obj build\temp.win-amd64-3.5\Release\util/double-conversion\double-conversion.obj build\temp.win-amd64-3.5\Release\util/double-conversion\fast-dtoa.obj build\temp.win-amd64-3.5\Release\util/double-conversion\fixed-dtoa.obj build\temp.win-amd64-3.5\Release\util/double-conversion\strtod.obj build\temp.win-amd64-3.5\Release\python/kenlm.obj /OUT:build\lib.win-amd64-3.5\kenlm.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\util\kenlm.cp35-win_amd64.lib
    LINK : fatal error LNK1181: cannot open input file 'stdc++.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181

    ----------------------------------------
Command ""c:\users\master engineer\appdata\local\programs\python\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\MASTER~1\\AppData\\Local\\Temp\\pip-0xplkmry-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MASTER~1\AppData\Local\Temp\pip-w7wovjx1-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\MASTER~1\AppData\Local\Temp\pip-0xplkmry-build\

Hope you can help me.

**Comment by besanza2014** [comment]
Running it on:
C:\Users\Master Engineer>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>


Thanks.

**Comment by lissyx** [comment]
@besanza2014 this is a build issue unrelated to the problem documented on that issue. Please refer to kenlm docs on how to install that on windows ; we cannot help you with that.

**Comment by sgt101** [comment]
Hi all - don't know if this is related but I was having similar issues and suddenly realized that I hadn't included --proxy XXX.YYY.com:0000 in my pip install -r requirements on install.

**Comment by aniketk1** [comment]
I ran into a similar issue trying to run this on an Ubuntu EC2 instance. To solve it I ran "conda install gcc" and then followed the KenLM build instructions.

**Comment by lissyx** [comment]
@YaxiongMa Have you been able to get more informations on your issue ? Should we close this ? It's likely we might at the very least give more documentation, once we know what was wrong in your case.

**Comment by YaxiongMa** [comment]
Hi~Iissyx, I am so sorry for not making a timely reply. I finally solved the problem. However, I cannot  remember what I have done specially because it is almost one week ago and I  didn't make a detailed note. 
And I will write the answer of this issue here when I remember it later~
thanks a lot !

**Comment by lissyx** [comment]
I'm closing this, please re-open if you find more informations on the issue.
