### ISSUE TITLE
New importer scripts problems

### ISSUE THREAD

**Issue by sgt101** [mozilla/DeepSpeech#556]
Hi, thanks for all your work on this project. 

I am having trouble with the new importer scripts - I am behind a proxy and this seems to be the heart of the issue, but I've got confused by some references to python 3 in the comments and I've now got to a place where I'm not sure what's going on. 

Have the importers been tested vs a proxy and do you have any advice about what to do? Also should I be using python 3 not 2?

**Comment by kdavis-mozilla** [comment]
We have not, to the best of my knowledge, tested them behind a proxy.

The code use to download the copora, for example for the TED corpus
```python
...
from tensorflow.contrib.learn.python.learn.datasets import base
...

    # Conditionally download data
    TED_DATA = "TEDLIUM_release2.tar.gz"
    TED_DATA_URL = "http://www.openslr.org/resources/19/TEDLIUM_release2.tar.gz"
    local_file = base.maybe_download(TED_DATA, data_dir, TED_DATA_URL)
    ...
```
uses the `base.maybe_download()` method from Tensorflow[[1](https://github.com/mozilla/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/base.py#L193)] which in turn uses `urllib` from `six.moves` and `urlretrieve`[[2](https://docs.python.org/2/library/urllib.html#urllib.urlretrieve)].

Supposedly `urllib` can work with proxies that do not require authentication if one sets the `HTTP_PROXY` environment variable[[3](http://kaamka.blogspot.de/2009/06/httpproxy-environment-variable.html)]. So I would try that.

Both python 3 and 2 should be supported. We more commonly use 2. However, if 3 does not work, please file an issue.

**Comment by sgt101** [comment]
Thanks! That worked.
