### ISSUE TITLE
Investigate why deepspeech.getMfccFrames doesn't outperform util.audio.audiofile_to_input_vector

### ISSUE THREAD

**Issue by Cwiiis** [mozilla/DeepSpeech#557]
getMfccFrames does the equivalent of util.audio.audiofile_to_input_vector. It relies mainly on python_speech_features.mfcc.

c_speech_features.mfcc outperforms psf's by a considerable margin when compiled with optimisation, but getMfccFrames does not outperform audiofile_to_input_vector when built with our current build scripts, supposedly with optimisation. The margin to which it loses looks very much like the library was not built with optimisation, despite the bazel optimised build flag being specified.

It would be good to understand what's happening here - switching over to libdeepspeech would allow us to cut out a lot of code duplication and should provide a small performance win at the same time.

**Comment by Cwiiis** [comment]
I think this may be down to some eccentricities with how bazel builds things... Building with

"-c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --copt=-O2 --experimental_omitfp=true"

squashes the warnings that Tensorflow gives when compiled without optimisation, but I don't know that it affects the compilation of kissfft (which is the real driver for performance in this particular function). My numbers on this particular machine vary too much and do actually outperform audiofile_to_input_vector consistently, so I'd like to test on the machine where it doesn't. I should be able to do that tomorrow (caught some kind of bug and working from home today).

I also need to test out with -mtune and -march options, though given the other options given here, I doubt they'd have an effect.

(tldr; bazel doesn't seem to respect the opt target, need to test on another machine)

**Comment by Cwiiis** [comment]
So handily, you can see what flags -mtune/-march affect by executing gcc like so:

gcc -march=native -mtune=native -Q --help=target

On my haswell core i7 laptop with gcc 6.3.1, all of the above -m* flags are redundant except -mfpmath=both when specifying -march=native. It seems like for good efficient performance, you'd want to compile with -march=native -mtune=native, but if you want to distribute the code, something like -march=x86-64 -mtune=generic would make sense, or -march=i686 -mtune=generic on 32-bit.

Note though, that those latter options include none of the flags that trigger the TensorFlow warnings and so performance may be degraded on modern CPUs.

**Comment by Cwiiis** [comment]
So now having run various tests on my other machine, I'm pretty confused as to what's happening. Both are haswell i7's, one the desktop part and one the laptop part. The mfcc function outperforms python_speech_feature's on both, but by a much greater margin on the laptop. The getMfccFrames function significantly underperforms (~0.75x) on the desktop i7 part, pretty much regardless of what flags I pass when building with Bazel.

There are some code changes I need to make to make libdeepspeech more useful, I'm going to try testing some theories while I make these changes.

I wonder if linking to multiple shared libraries is causing a significant hit? The major differences between c_speech_features and libdeepspeech with respect to bindings, c_speech_features is statically linked, where as libdeepspeech uses shared libraries (for tensorflow, c_speech_features, kissfft and finally deepspeech). I wouldn't have expected this would cause a significant hit, but perhaps it does. I should be able to modify the build to link statically (except for tensorflow, which for whatever reason doesn't build a static library) and find out.

**Comment by Cwiiis** [comment]
More interesting developments...

Exposing csf_mfcc in libdeepspeech bindings shows the exact same code operating at an approximate 10% performance deficit vs. c_speech_features. Even if kissfft is built with c_speech_features instead of in a separate library. I'm going to try to get c_speech_features linked statically with the bindings to see if that makes a difference...

I'm getting very close to the only difference between c_speech_features and deepspeech being bazel at this point. Hopefully it'll end up being something easily worked around/fixed.

**Comment by Cwiiis** [comment]
Pretty much narrowed down the problem now. There are multiple things;

* -fstack-protector causes slowness, we can get rid of this in nocopts.
* -fno-omit-frame-pointer causes a small amount of slowness, we can get rid of this in nocopts too.
* c_speech_features uses -O3 by default, which can make a significant difference. -c opt only uses -O2. We can specify this in copts (I don't know that we'd want this across the entire library, but maybe - in that case, we can just recommend specifying this via --copts on the command-line).
* Specifying -march=native significantly slows mfcc down. -mtune=native is ok and provides a small speed boost. Something that gets enabled in -march=native causes a significant speed deficit in c_speech_features.

With all these addressed, libdeepspeech manages to at least match c_speech_features in performance of the same functions (and code). Just need to do some more tests and tidying before I can open a PR and close this :)

**Comment by Cwiiis** [comment]
So, specifically, -mfma causes a large speed hit, then both -mavx and -mavx2 cause significant speed hits, but not as hugely significant as -mfma. I will explicitly disable these features in the build file.

**Comment by Cwiiis** [comment]
Ok, so results are now inline, except on my laptop everything is faster and on my desktop everything (including c_speech_features) is slower :) Given I've previously tested c_speech_features to be faster on this same machine, I've got some more digging to do... But at least whatever's still happening here is likely my fault rather than Bazel's.

**Comment by Cwiiis** [comment]
So with the default parameter for numcep in mfcc, c_speech_features outperforms python_speech_features, but with the increased number we use in DeepSpeech, it underperforms, at least on my desktop (it's still faster on the laptop). That's the root-cause now, so I'll look at further optimisation of the mfcc function.

**Comment by Cwiiis** [comment]
There was an obvious inner-loop optimisation for csf_mfcc, this issue is now comprehensively fixed :)

**Comment by reuben** [comment]
Sounds like this can be closed! :)
