### ISSUE TITLE
What kind of RTF should one expect?

### ISSUE THREAD

**Issue by migueljette** [mozilla/DeepSpeech#563]
Hi there,

Just out of curiosity, what kind of RTF can one expect from your code?
I want to test it out, but I was curious to know ahead of time if the decoding is fairly fast.

Thank you!
Miguel

**Comment by kdavis-mozilla** [comment]
It's hardware dependent.

**Comment by migueljette** [comment]
Yes, sorry, I realize that.
Let's say I have a Titan X for decoding.
Also, let's assume I am decoding using a 5 inner layer DNN, with 1024 neurons in each layers.
I'm wondering, can RTF <0.1 be achieved?
I am currently using Kaldi's nnet3 (tdnn_lstm) setup and my RTF is more around 1 - 1.1.

**Comment by kdavis-mozilla** [comment]
@migueljette I'm sure we can get RTF < 1.0 with a Titan X, but I don't know the exact number for the DS2 architecture. Also, I didn't know  Kaldi's nnet3 (tdnn_lstm) RTF is greater than 1.0 on a Titan X.

@reuben Do you know what the RTF is for the DS2 net you're currently working with?

**Comment by migueljette** [comment]
@kdavis-mozilla Thanks for the comments. The RTF might be a little lower than 1, but I am never able to get it anywhere close to 0.1. I do have a pretty big LM and then i rescore using a larger LM... so maybe I am doing too many things to get 0.1 :) The DNN is pretty big too.

**Comment by reuben** [comment]
I don't, in fact I haven't even updated the inference graph. I'll comment here when I have an answer.

**Comment by reuben** [comment]
There's a constant factor for smaller samples, but as they grow in size I got an average RTF of 0.6 on my MacBookPro11,3 (GTX 750M) with tensorflow-gpu==1.1. Using the CPU only package we're around 1.3x real time.

**Comment by reuben** [comment]
I also did some tests on my desktop with two GTX 1070's and the RTF there was closer to 0.2.

**Comment by migueljette** [comment]
Fascinating! Thanks for checking and letting me know!
Out of curiosity, would using 4 GPUs reduce it to 0.1? I wonder what the limit is. But i'm just curious... i'll do some real test soon. I just keep running out of time. :)
Thanks again! 👍

**Comment by reuben** [comment]
It would not, inference is only done on a single GPU. I only mentioned the two GPUs on the desktop out of habit :)

**Comment by migueljette** [comment]
ha ha! Ok, got it. Thanks again!
