### ISSUE TITLE
OOM errors from CPU or GPU?

### ISSUE THREAD

**Issue by aaronzira** [mozilla/DeepSpeech#565]
Having encountered errors such as the following with batch sizes of 32/16/16, 24/12/12, and 16/8/8 in my most recent runs ([#559](https://github.com/mozilla/DeepSpeech/issues/559) - 4 x GTX 1080Ti 11GB FE), and presumably of the same type as others ([#321](https://github.com/mozilla/DeepSpeech/issues/321),[#234](https://github.com/mozilla/DeepSpeech/issues/234), and [#239](https://github.com/mozilla/DeepSpeech/issues/239)), do we know the source of the problem?

> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4096,4096]
> [[Node: tower_0/gradients/tower_0/rnn/while/multi_rnn_cell/cell_3/gru_cell/gates/gates/MatMul/Enter_grad/Add = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/gradients/tower_0/rnn/while/multi_rnn_cell/cell_3/gru_cell/gates/gates/MatMul/Enter_grad/Switch:1, tower_0/gradients/tower_0/rnn/while/multi_rnn_cell/cell_3/gru_cell/gates/gates/MatMul_grad/tuple/control_dependency_1)]]
> [[Node: Adam/update_rnn/multi_rnn_cell/cell_0/gru_cell/gates/weights/ApplyAdam/_4150 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_10621_Adam/update_rnn/multi_rnn_cell/cell_0/gru_cell/gates/weights/ApplyAdam", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]

**Comment by kdavis-mozilla** [comment]
You're simply allocating more memory than your GPU has. You need to decrease the batch size.
