### ISSUE TITLE
Slow Training on Ted and 8 K80s

### ISSUE THREAD

**Issue by dahlem** [mozilla/DeepSpeech#569]
Hi guys,

I'm training on the ted dataset on a p2.8xlarge instance on AWS. I compiled tensorflow from scratch, checked out DeepSpeech on the 5th of May.

5 days later I'm only on episode 2 and I noticed using "watch nvidia-smi" that the GPU utilisation is 0% a lot of the times and 99% for very short bursts. Any ideas how I can debug this, or whether this is expected?

Thank you.
Dominik

My run script is as follows:
#!/bin/sh
set -xe
if [ ! -f DeepSpeech.py ]; then
    echo "Please make sure you run this from DeepSpeech's top level directory."
    exit 1
fi;

if [ ! -d "${ds_dataroot}" ]; then
    ds_dataroot="data"
fi;

# Warn if we can't find the train files
if [ ! -f "${ds_dataroot}/ted-train.csv" ]; then
    echo "Warning: It looks like you don't have the TED-LIUM corpus downloaded"\
         "and preprocessed. Make sure \$ds_dataroot points to the folder where"\
         "folder where the TED-LIUM data is located, and that you ran the" \
         "importer script at bin/import_ted.py before running this script."
fi;

checkpoint_dir=$(python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ted"))')

python -u DeepSpeech.py \
  --train_files "$ds_dataroot/ted-train.csv" \
  --dev_files "$ds_dataroot/ted-dev.csv" \
  --test_files "$ds_dataroot/ted-test.csv" \
  --train_batch_size 8 \
  --dev_batch_size 8 \
  --test_batch_size 8 \
  --epoch 100 \
  --display_step 1 \
  --validation_step 1 \
  --dropout_rate 0.30 \
  --default_stddev 0.046875 \
  --learning_rate 0.0001 \
  --checkpoint_dir "$checkpoint_dir" \
  --export_dir "deepspeech/models/ted" \
  --summary_secs 300 \
  --log_level 0 \
  "$@"

**Comment by kdavis-mozilla** [comment]
This is not expected. That said, we've also seen this before.

In our case, which I doubt is the same as yours, this behavior arose when our training machine crashed, was subsequently rebooted, and then training resumed while the machine was in the process of checking the file system.

For us once the file system was checked this GPU "ping pong" behavior disappeared.

**Comment by dahlem** [comment]
Thank you for the info. I deleted the ~/.local/share/deepspeech folder and started training again. I'm still seeing the same issue. The server hasn't crashed, so I don't think this would be the issue.

Is there any other state kept by deepspeech that could impact a training run?

Thank you

**Comment by sgt101** [comment]
Hello, I've been training ted using 4 * 1080 maxwells, these have only 8GB ram, so I reduced the batch size to 6 in order to do the training. It takes about 8 days to train the model on my setup. I think that k80's have much more memory, so maybe increasing the batch size would be an enabler? 

Another thing that helped me was to reduce the ted-train.csv to 10% of its size for debugging runs; this let me train the model to the end quite quickly (approx a day) and this allowed me to sort out the memory overflow problems by finding the best batch size. 

Due to a small batch size I think I am getting some overfitting...

**Comment by kdavis-mozilla** [comment]
@sgt101 @dahlem A few other tips...

- You can reduce the number of wav's used in training, dev, and testing using the command line arguments `limit_train`, `limit_dev`, and `limit_test` which take the number of training, dev, and test wav's to use respectively
- We use curriculum learning so the shortest wavs are in the initial batches the longest are in the final batches. However, batch size is dependent only on the largest wavs. So one normally has to wait until the last batch to determine if batch size is correct. However, one can temporarily sort by largest wav first by changing the sort order here[[1](https://github.com/mozilla/DeepSpeech/blob/master/util/data_set_helpers.py#L81)] then the OOM occur right away with no wait.

**Comment by dahlem** [comment]
@kdavis-mozilla , thank you for the tips. I found that the job reports, which compute the levenshtein distance and the WER, are slowing things down significantly. Either switching the reports off or report more infrequently solves my problem (I think -- I need to run the job till the end to be sure).
