### ISSUE TITLE
core dumped with native client

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#571]
when running the following code : 
 ARGS="~/Projects/DeepSpeech/logs/checkpoints/graph.pbtxt ~/Projects/DeepSpeech/data/smoke_test/LDC93S1.wav " make run 

I'm receiving the following error:

Segmentation fault (core dumped)
Makefile:57: recipe for target 'run' failed
make: *** [run] Error 139

any ideas?

**Comment by kdavis-mozilla** [comment]
Just to clarify. Did you follow all the steps of the [README.md](https://github.com/mozilla/DeepSpeech/tree/master/native_client)

**Comment by alanbekker** [comment]
yes, when running it  with client.py..I'm receiving:
ImportError: libdeepspeech.so: cannot open shared object file: No such file or directory

Although I installed: sudo pip install deepspeech

**Comment by alanbekker** [comment]
I manged to solve the problem..do you know where the transcription file in received when running:
ARGS="~/Projects/DeepSpeech/logs/checkpoints/graph.pb ~/Projects/DeepSpeech/data/smoke_test/LDC93S1.wav " make run

Thanks in advance!

 ?

**Comment by lissyx** [comment]
There is no such thing as « transcription file », the computed string being recognized is outputted on the standard output.

**Comment by alanbekker** [comment]
so..it means the command didn't succeeded if don't get any error/transcription?

**Comment by lissyx** [comment]
If you just get an empty output, it means nothing has been recognized. Without more details on how you trained the model, we cannot jump to any conclusion :)

**Comment by alanbekker** [comment]
I train my model on librivox with a 1000 examples for 10 epochs :)
Just want to check the native client right now..it supposed to return some no sense transcription right?

**Comment by lissyx** [comment]
It is supposed to return according to what has been trained. Your previous messages states `graph.pb` and `LDC93S1.wav`, so it is unclear what you trained. 1000 samples over 10 epochs might also not be enough and thus the model and native_client might be working as expected, just not being trained enough. Please overfit the `ldc93s1` sample model, and when training shows good overfit, running native_client with LDC93S1.wav should output some strings. This has been working well for all of us, there is no reason it would not work for you :)

**Comment by alanbekker** [comment]
great! works now.

Thank you very much!

**Comment by lissyx** [comment]
I will consider that your problem was related to the use of text-based protocolbuffer for the model and close this then :)

**Comment by manuliner** [comment]
@alanbekker how did you solve this problem?
