### ISSUE TITLE
Training slower and slower

### ISSUE THREAD

**Issue by striki70** [mozilla/DeepSpeech#572]
I'm training network with batches of 12 files. However, time needed to process single batch is constantly growing.
Is there any way to keep this time steady?

**Comment by kdavis-mozilla** [comment]
The batches are organized via curriculum learning[[1](http://dl.acm.org/citation.cfm?id=1553380)][[2](https://github.com/mozilla/DeepSpeech/blob/master/util/data_set_helpers.py#L77)].

So initial batches contain shorter wav's later batches contain longer wav's.

As processing longer wav's takes longer, the behavior you see is expected.

You can keep the time per batch steady by randomizing wav ordering. However, WER will increase.

**Comment by striki70** [comment]
Thanks a lot!

**Comment by abuvaneswari** [comment]
In reference to issue #580 , can you confirm if by restarting DeepSpeech, after it reads the checkpoint, it will go on to process the un-processed wav files, and it will not go back and start with wav file #1 in the corpus?
