### ISSUE TITLE
Code problem when exporting a model (ds2-v2)

### ISSUE THREAD

**Issue by sgt101** [mozilla/DeepSpeech#573]
Hi, 

I've been trying ds2-v2 and have successfully trained a model and now have tried exporting it. 

I got 

I Exporting the model...
Traceback (most recent call last):
  File "DeepSpeech.py", line 1602, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1596, in main
    export()
  File "DeepSpeech.py", line 1497, in export
    logits = BiRNN(input_tensor, tf.to_int64(seq_length), no_dropout)
TypeError: BiRNN() takes exactly 5 arguments (3 given)

I think that the code on 1497 lacks "is_training" and "reuse" parameters.

**Comment by reuben** [comment]
Yes, the export code hasn't been updated to match the model on that branch.

I won't be able to get to this before next week, but I would review a PR ;)

**Comment by offbit** [comment]
@reuben Before you update the export code I would suggest change the line:
https://github.com/mozilla/DeepSpeech/blob/ds2-v2/util/bngru.py#L58

`from tensorflow.contrib.layers.python.layers import utils
...
return utils.smart_cond(self._training, batch_statistics, population_statistics)
`

If you don't use smart condition you will probably face problems loading the graph afterwards. tf.cond is not working properly when exporting graphs. 

At least it didn't work for my tests

**Comment by sgt101** [comment]
Hi,
I've hacked around the export function to export the model - so it can be done (not tested yet!) but even before testing I'm unhappy with it. 

I've edited def export() @ 1479 in DeepSpeech.py. 

The issue arises with line 1498, logits =BiRNN(

there are two issues. First is to set the missing parameters for the new version of BiRNN. I set reuse=None (no trick there!) and then struggled with is_training which needs to be a scalar that gets evaluated to tf.bool (python bools force an exception later) I obtained that by setting x and y as tf.constants and then evaluating tf.less(y,x) to give a value that I hope is false! 

Ok - awkward, but it works. 

Then the bit that I am suspicious about. 
The code will now throw a "mismatched tensor shape" exception. the input tensor is 19 times the size of the output tensor... I have made it "work" by editing 1494 so that the placehoder has a shape of [None, None, n_input] rather than n_input+2*n_input*n_context

Presto - a model of some sort gets written into the output directory.

We are now building a tensorflow.so so that we can see if we can get the model into one of the clients and then see if it works as a transcriber... my guess is that it won't because of the shape hack above!

**Comment by sgt101** [comment]
After building and some more messing about I have now got the client compiled and am able to attempt to pull in the exported model. 

I used @offbit 's suggestion to fix the export so that the binary model can be imported again (without the move to smart_cond the binary won't import. 

However now I am getting : 

deepspeech: client.cc:71: int main(int, char**): Assertion `ctx' failed.
Invalid argument: Input 0 of node rnn/while/multi_rnn_cell/cell_4/gru_cell/gates/r/cond/rnn/while/multi_rnn_cell/cell_4/gru_cell/gates/r/strided_slice_1/_assign/RefEnter was passed float from rnn/multi_rnn_cell/cell_4/gru_cell/gates/r/pop_var:0 incompatible with expected float_ref.
not ok in DsInit after graph creation make: *** [run] Aborted (core dumped)

You can see that I have ToString'd the status code from ctx->session->Create(ctx->graph_def) and that I've added an error message so I know where the core is being dumped. 

I'm pretty stuck at this point - any ideas?

**Comment by reuben** [comment]
Sorry for taking so long to reply here, I was away from work for a few days. I'll try to reproduce the problem.

**Comment by reuben** [comment]
The problem here is that TensorFlow doesn't know how to properly freeze a graph that uses batch norm. I'm focusing on getting the training side of ds2-v2 running perfectly before working on exporting and etc, so I won't be able to debug TensorFlow very soon.

**Comment by reuben** [comment]
Will be fixed before the branch is finalized/merged/abandoned.
