### ISSUE TITLE
Reword README.md to not suggest TF serving is used

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#579]
Text of README.md

> ## Exporting a model for serving
> 
> If the `--export_dir` parameter is provided, a model will have been exported to this directory during training.
> Refer to the corresponding [README.md](native_client/README.md) for information on building and running a client that can use the exported model.

suggests TF serving is used. It is not, so the text should be changed.

**Comment by reuben** [comment]
Fixed by #672.
