### ISSUE TITLE
step processing time increases with time

### ISSUE THREAD

**Issue by abuvaneswari** [mozilla/DeepSpeech#580]
My environment:
Ubuntu 14.04
Python 3.4.3
tensorflow 1.1.0
16 hyper core CPU, no GPU

I observe that the time to process a batch increases wrt batch index (and wall clock time). Attaching a ppt with additional details. At this rate, it is difficult to project when the training will be completed. I understand that running it on a GPU enabled server would reduce the execution time, but wonder if the same pattern will continue in that scenario as well.

I searched discussions on similar issues, and found this Stackoverflow post:
http://stackoverflow.com/questions/37472420/tensorflow-each-iteration-in-training-for-loop-slower 

I started to study the DeepSpeech code, trying to look for patterns discussed there; it would take me a while to figure out the answer. 

Meanwhile, can someone please respond for the following:
1) Have you observed that the execution time per batch (/step) increases wrt batch (/step) index (or wall clock time) while running strictly on CPU?
2) If so, have you figured out why
3) Has this been observed when it is run on a server with GPU?

Out of curiosity, I ran an experiment in which I restart DeepSpeech every 31 minutes (right after its 3rd checkpoint, checkpoint interval being 10 min) - I suppose due to the fact that DeepSpeech reads from the checkpoint and starts from where it left, there is no data loss (please confirm). This meant that the average execution time per step does not grow unbounded, making it possible to project when the training will certainly complete - please let me know your comments.

[DeepSpeechStepExecTime.pptx](https://github.com/mozilla/DeepSpeech/files/1008276/DeepSpeechStepExecTime.pptx)

**Comment by kdavis-mozilla** [comment]
See issue #572
