### ISSUE TITLE
Problem while configuring Client   

### ISSUE THREAD

**Issue by pandeydivesh15** [mozilla/DeepSpeech#581]
I followed all the instructions for building tensorflow from the source as described in [README.md](https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md). But when I am running ```make deepspeech``` I am getting an error.
```bash
g++ -o deepspeech `pkg-config --cflags sox` -L../../tensorflow/bazel-bin/tensorflow -L../../tensorflow/bazel-bin/native_client  client.cc `pkg-config --libs sox` -ltensorflow -ldeepspeech 
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::SlowCopyFrom(tensorflow::Status::State const*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::TensorShape(tensorflow::gtl::ArraySlice<long long>)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ConfigProto::~ConfigProto()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::SlowCopyFrom(tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Env::Default()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::ToString() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::DestructorOutOfLine()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckIsAlignedAndSingleElement() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::~Tensor()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::Tensor(tensorflow::DataType, tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::~GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::dim_size(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsAtLeast(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::string const&, google::protobuf::MessageLite*)'
collect2: error: ld returned 1 exit status
make: *** [deepspeech] Error 1
```

I had tried this process previously, before the python bindings came up for client (before certain commits in th project). At that time also, I got the same error. What can be the problem here ?

My directory structure:
```bash
|-- tensorflow
|   |-- bazel-bin
|   |-- bazel-genfiles
|   |-- bazel-out 
|   |-- bazel-tensorflow
|   |-- bazel-testlogs
|   |-- native_client -> ../DeepSpeech/native_client
|   |-- tensorflow
|   |-- third_party
|   |-- tools
|   `-- util
|-- DeepSpeech
.
.
.
|   |-- native_client
|   |   |-- c_speech_features
|   |   |-- kiss_fft130
|   |   `-- python
```

**Comment by kdavis-mozilla** [comment]
Are you sure creation of `libtensorflow.so` completed correctly?

Could you first check it's existence from the `native_client` as follows
```bash
pandeydivesh15-MBP:native_client pandeydivesh15$ ls -l ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so
```
You should get something like
```bash
pandeydivesh15-MBP:native_client pandeydivesh15$ ls -l ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so
-r-xr-xr-x  1 pandeydivesh15  wheel  111614784 17 May 11:48 ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so
```
If it doesn't exist, tensorflow complication failed.

I guess in a second step you can check its symbols. But I guess it's better to first know if it exists.

**Comment by pandeydivesh15** [comment]
It is present.
```bash
DeepSpeech/native_client$ ls -l ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so
-r-xr-xr-x 1 divesh_pandey divesh_pandey 44076512 May 18 12:05 ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so
```

**Comment by kdavis-mozilla** [comment]
If you're on linux can you look at its symbols.

For example for `CheckDimsAtLeast` something like
```bash
nm ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so | grep CheckDimsAtLeast
```

**Comment by pandeydivesh15** [comment]
I am getting **No symbols**

**Comment by kdavis-mozilla** [comment]
Then something went wrong with the tensorflow compilation

**Comment by behnamasefi** [comment]
Hi,
 I have the same problem as above. I checked for symbols in libtensorflow.so file for missing references with:

nm libtensorflow.so | grep SlowCopyFrom
000000000388d480 T _ZN10tensorflow11TensorShape12SlowCopyFromERKS0_
0000000003a19140 T _ZN10tensorflow6Status12SlowCopyFromEPKNS0_5StateE

However I can not accomplish the last step by  make deepspeech.
Any help please?

**Comment by kdavis-mozilla** [comment]
@behnamasefi What errors occur?

**Comment by behnamasefi** [comment]
The error is:

../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsAtLeast(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Env::Default()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ConfigProto::~ConfigProto()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::SlowCopyFrom(tensorflow::Status::State const*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::dim_size(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckIsAlignedAndSingleElement() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::SlowCopyFrom(tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::Tensor(tensorflow::DataType, tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::~Tensor()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::TensorShape(tensorflow::gtl::ArraySlice<long long>)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::~GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::DestructorOutOfLine()'
collect2: error: ld returned 1 exit status
Makefile:48: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1

**Comment by kdavis-mozilla** [comment]
Are you sure ` libtensorflow.so` is getting loaded?

**Comment by behnamasefi** [comment]
@kdavis-mozilla  How can I be sure about this?

**Comment by kdavis-mozilla** [comment]
lld + LD_LIBRARY_PATH

**Comment by behnamasefi** [comment]
Yes the folder contains libtensorflow.so in on my LD_LIBRARY_PATH

**Comment by pandeydivesh15** [comment]
@behnamasefi the error is entirely same. @kdavis-mozilla Can python environments be a problem? Actually I am running Deepspeech.py(training) in an different environment and preparing the client(building tf and other) in an another.

**Comment by behnamasefi** [comment]
@pandeydivesh15  I use same env for both cases. However I think there is no need to be in any env because this the c++ code compile stage.

**Comment by pandeydivesh15** [comment]
@kdavis-mozilla you told me about those symbols. There are two libdeepspeech.so files.
You asked me for checking symbols for ```../../tensorflow/bazel-bin/tensorflow/libtensorflow.so | grep CheckDimsAtLeast```, for which I got **No symbols**. There is onle file at ```tensorflow/bazel-bin/native_client/libdeepspeech.so```, for which I am getting symbols.
```bash
DeepSpeech/native_client$ nm ../../tensorflow/bazel-bin/native_client/libdeepspeech.so | grep CheckDimsAtLeast
                 U _ZNK10tensorflow11TensorShape16CheckDimsAtLeastEi
```

**Comment by behnamasefi** [comment]
@pandeydivesh15  just change the
LDFLAGS += -ltensorflow -ldeepspeech -lc_speech_features -lkissfft $(EXTRA_LDFLAGS)

with this line:
LDFLAGS += -ldeepspeech -ltensorflow -lc_speech_features -lkissfft $(EXTRA_LDFLAGS)

in makefile inside nativaclient folder. That's it :)

**Comment by kdavis-mozilla** [comment]
@behnamasefi Do you want to make a pull request from this?

**Comment by pandeydivesh15** [comment]
@kdavis-mozilla @behnamasefi Still no luck.
Do I have to build kissfft and c_speech_features libs too? 
G++ linker is not finding those libs.
```
/usr/bin/ld: cannot find -lc_speech_features 
/usr/bin/ld: cannot find -lkissfft
```
Please help.

**Comment by lissyx** [comment]
Some of the build failures in this thread may be a consequence of issue #654, one can find a simpler example/confirmation in issue #653 .
