### ISSUE TITLE
Batch size for graphic card with 8 GB of RAM

### ISSUE THREAD

**Issue by striki70** [mozilla/DeepSpeech#585]
Which is the maximum length of the batches that we can assign having NVIDIA GeForce 1080 with 8 GB of RAM?
Currently I'm doing training with the length of 12. Can this be increased for further epochs?

**Comment by kdavis-mozilla** [comment]
I don't know. But we use curriculum learning so the shortest wavs are in the initial batches the longest are in the final batches. However, batch size is dependent only on the largest wavs. So one normally has to wait until the last batch to determine if batch size is correct. However, one can temporarily sort by largest wav first by changing the sort order here[[1](https://github.com/mozilla/DeepSpeech/blob/master/util/data_set_helpers.py#L81)] then the OOM signaling the batch is too large occurs right away with no wait allowing you to easily set the batch size for your hardware via a binary search, say.
