### ISSUE TITLE
native client on non-x86 architectures? 

### ISSUE THREAD

**Issue by gvoysey** [mozilla/DeepSpeech#589]
I'd like to run the native client on an embedded system (e.g., ARM v8).   

From what I can tell, getting tensorflow and bazel to build from source on ARM is a giant pain -- I was lucky and found some prebuilt wheels that I've been able to use.  

Is it worth the pain to go through building the client?  I need to hand WAV files to the network, in python3. Is there a better option than using the native client?

**Comment by lissyx** [comment]
We already have ARMv6 builds that runs on Raspberry Pi3 under Raspbian for the `native_client`. Some changes and hacking are required to cross-build the python wheel for tensorflow, and installation is a bit much more painful if you don't have prebuilt dependencies such as `numpy`/`scipy`. In the end, I could get Tensorflow python package to work on the RPi3 but of course there was low value regarding training :).

Latest successfull ARM build of `native_client` is at https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.arm/artifacts/public/native_client.tar.xz

**Comment by lissyx** [comment]
Oh and since you mention ARMv8 I have not yet tested that completely, though the toolchain should be able to produce binaries. I wanted to wait a bit more for a more stable ARMv8 distro being more available, but if nothing gets soon I may just rely on current Debian ARMv8 and perform some benchmarking. Also, we are currently only working on RPi3 as ARM hardware, and last time I checked, there was still not everything completed to get decent ARMv8 on RPi3. This may have changed, though.

**Comment by gvoysey** [comment]
@lissyx OK.  I'll have a look.  For reference, i'm planning on using a TX1, which has a quad-core ARM A57.

**Comment by lissyx** [comment]
RPi3 is Quad-Core Cortex A53, so slower :)

**Comment by gvoysey** [comment]
hey, as long as it builds!  ;)

**Comment by lissyx** [comment]
You can probably build that on top of our tensorflow fork that includes rpi toolchain ?

**Comment by gvoysey** [comment]
I should.  I'll try the binary you linked above first, though.  Compiling is slow..

**Comment by lissyx** [comment]
Cross compiling is quite fast, takes ~500 secs on my desktop with 8 cores and 32 GB RAM. We have tensorflow with the RPi GCC toolchain for cross compilation, you can probably start from that ?

**Comment by gvoysey** [comment]
@lissyx silly question time: i untarred the binaries you linked above.  how do i execute them? running `./deepspeech` results in `bash: no such file or directory`.

**Comment by lissyx** [comment]
You should at least do `LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./deepspeech`

**Comment by lissyx** [comment]
Hello, @gvoysey have you been able to run that on your side ?

**Comment by kdavis-mozilla** [comment]
Close on inactivity
