### ISSUE TITLE
Create Character Based RHN language model

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#592]
Create a character based language model using RHN[[1](https://arxiv.org/abs/1607.03474)].

**Comment by pdcoded** [comment]
Why this architecture? And I suppose this would be an external Language model ?or one integrated with beam search decoder.

**Comment by kdavis-mozilla** [comment]
In light of [Exploring Neural Transducers for End-to-End Speech Recognition](https://arxiv.org/abs/1707.07413) this issue seems counter productive.
