### ISSUE TITLE
serving_client missing

### ISSUE THREAD

**Issue by striki70** [mozilla/DeepSpeech#599]
I'm looking for a way to expose trained neural network for input wave files. My guess is that serving_client module should do the job, but it's missing in master. Any information about handling wave files for recognition?

**Comment by kdavis-mozilla** [comment]
We aren't supporting TensorFlow serving, a conscious decision

**Comment by abuvaneswari** [comment]
Hello, I was just looking for serving_client and found this 'issue'. Can you please share what prompted you to make the decision to not support tensorflow serving?
