### ISSUE TITLE
Error : SparseTensor is not valid 

### ISSUE THREAD

**Issue by harinderbedi** [mozilla/DeepSpeech#600]
I am able to run the same script/command with one dataset but when i run another dataset (which is bigger and same language) then i get this error -

`tensorflow/core/framework/op_kernel.cc:993] Invalid argument: label SparseTensor is not valid: indices[25] = [0,25] is out of bounds: need 0 <= index < [1,25]`

Any idea ?

**Comment by kdavis-mozilla** [comment]
Could you provide more details? What script? What data sets? How was the other data set prepared?

My guess is that the data set has a malformed sentence in it.

**Comment by harinderbedi** [comment]
Thanks for the response Davis-

Script/Command is -
` python -u DeepSpeech.py --train_files /home/spanish/files/spanish-train1.csv --dev_files /home/spanish/files/spanish-train1.csv --test_files /home/spanish/files/spanish-train1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --fulltrace True --log_level 0 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/spanish12345`

Dataset -
Which works - 3 lines in csv with special characters 
Which does not work - 1 million lines with special characters

**Comment by kdavis-mozilla** [comment]
What do you mean by "with special characters"? Could you copy the 3 lines here?

**Comment by kdavis-mozilla** [comment]
> Can you please tell what is the meaning of the error like what is not valid ? and what is "[0,25]".

This basically means you have non-ascii characters. There are code changes that have to occur, see my comments here[[1](https://github.com/mozilla/DeepSpeech/issues/551#issuecomment-303669182)]
