### ISSUE TITLE
Report loss and WER during training

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#601]
There is a way to print the loss and WER every number of batches?
I need to wait 1 epoch for seeing the progress.

Thanks!

**Comment by kdavis-mozilla** [comment]
Currently not. We calculate WER only as a full batch average.

**Comment by alanbekker** [comment]
what do you mean as a full batch average? I currently can't see any WER report after each batch

**Comment by kdavis-mozilla** [comment]
Sorry, a typo as a full epoch average.
