### ISSUE TITLE
Memory leakege when training librivox

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#602]
I'm suffering from memory leakage during the training, while eventually my program crashes.

any ideas how to fix that?

**Comment by kdavis-mozilla** [comment]
How do you know it's memory leakage? Are you sure your batch size is set correctly?

**Comment by alanbekker** [comment]
my batch size is 12...and I see as long the training progress each batch takes more time.
I'm running on a 1080 machine, at the beginning each batch takes 2 seconds and after a while it takes 30 seconds and more

**Comment by kdavis-mozilla** [comment]
I guess I still have the same questions: 

> How do you know it's memory leakage? Are you sure your batch size is set correctly?

I can't really answer either with the info you provided. Could you provide more details as to why you think memory is leaking? (You know we use curriculum learning right?) How do you know your batch size is set correctly (Have you run through an entire epoch?)

**Comment by alanbekker** [comment]
I'm not aware of the curriculum learning, can you provide a link so I can learn more about it?
How can I know the correct batch size? as I told you before the end of the first epoch my program crashed.

**Comment by kdavis-mozilla** [comment]
Here's the standard reference on curriculum learning[[1](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.149.4701)]. This explains your observation that later batches take longer than earlier batches, earlier batches contain shorter wav's.

If you can run through an entire epoch, then you know the batch size is less than or equal to its maximum. Finding the maximum is a process of,say, binary search, e.g. 20 gives out of memory error, 10 completes the epoch, 15 gives out of memory error, 12 completes the epoch, 13 gives out of memory error; so the maximum batch size is 12.

**Comment by alanbekker** [comment]
so why after the process crashed and I run it again the initial batches are
taking short time to run..they weren't supposed to take as long as the
latest batches before the process crashed?

**Comment by kdavis-mozilla** [comment]
@alanbekker If the process dies due to a too large batch size and you don't restart from a checkpoint, then the curriculum learning curriculum starts again.

I'm going to close this for now until you establish 

- Your batch size is set correctly
- There really is, as you claim, a memory leak

If you can show that there really is a memory leak, feel free to re-open.

**Comment by alanbekker** [comment]
It seems by default it continues from the last checkpoint since the batch
number continue from the one that the process was stopped..
