### ISSUE TITLE
Question: Deep Voice 

### ISSUE THREAD

**Issue by loretoparisi** [mozilla/DeepSpeech#605]
Will this architecture implement the recent Baidu Deep Voice DNN?

**Comment by kdavis-mozilla** [comment]
No. Deep Voice is TTS. This is SST.

**Comment by loretoparisi** [comment]
@kdavis-mozilla Thanks, I know. Is `mozilla` going to implement in `tensorflow` the nn behind Deep Voice (1 or 2)?

**Comment by kdavis-mozilla** [comment]
This is undecided. However, we plan on doing TTS.

**Comment by loretoparisi** [comment]
@kdavis-mozilla Great, that's awesome, thank you for your work!

**Comment by kdavis-mozilla** [comment]
Welcome!
