### ISSUE TITLE
Reading input files after a crash

### ISSUE THREAD

**Issue by abuvaneswari** [mozilla/DeepSpeech#607]
I understand that DeepSpeech uses tensorflow's checkpoint facility to save models and restore from crash. However, does DeepSpeech process input files from where it left off prior to the crash? or, does it just process the files all over again from file #1 in the data set? If that is the case, then are there any plans to support this feature?

**Comment by tilmankamp** [comment]
It starts over the batch order with every beginning of an epoch or whenever training is continued using a checkpoint. So far there were no plans for that feature, but I'll add it and reference this issue.
Thanks!
