### ISSUE TITLE
Continue checkpointed training at correct next sample index

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#611]
After resuming a checkpoint, training batches/samples start over at index 0 and by that curriculum learning notion is violated.
One has to calculate the correct sample index in `start_coordination()` based on the the current training `step` and derived values.

**Comment by tilmankamp** [comment]
Based on #607.

**Comment by andi4191** [comment]
@tilmankamp : Can we write a wrapper to override the save method of tf.train.Saver class?

That way we can read the latest checkpoint file at start and while saving the checkpoint file, assign the global step updated as an argument in the save method.

**Comment by tilmankamp** [comment]
That's not the actual problem of this issue. The global step is already loaded at startup and can also be gathered from the checkpoint's filename. The challenge here is to correctly compute the next sample's index and initialize the training coordinator accordingly.

One can only do this under certain assumptions:
 - The number of GPUs, 
 - the number of replicas and 
 - the batch size 
did not change between checkpoint save and restore.

**Comment by andi4191** [comment]
Are we referring to the next index from _read_data_sets function from util package?

**Comment by tilmankamp** [comment]
The `read_data_sets` from `data_set_helpers` module gets fed a lambda which in turn retrieves the next index from the training coordinator. This is the sample index, yes.

**Comment by praveeny1986** [comment]
This issue still persists in the release version. After resuming from a checkpoint training batches start from 0 index.  Doesn't really solves the purpose of resuming the training....

**Comment by lissyx** [comment]
I think we can now safely close this ...

**Comment by reuben** [comment]
Technically to solve this we still need the extra step of saving the input pipeline itself in a checkpoint or with the main model checkpoint. But I'm not sure if this is still a goal. Maybe a nice to have?
