### ISSUE TITLE
run-ldc93s1.sh error

### ISSUE THREAD

**Issue by gaoxuesong** [mozilla/DeepSpeech#618]
[root@deepspeech DeepSpeech]# ./bin/run-ldc93s1.sh
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ echo 'Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1.'
Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1.
+ python -u bin/import_ldc93s1.py ./data/ldc93s1
Successfully downloaded LDC93S1.wav 93638 bytes.
Successfully downloaded LDC93S1.txt 62 bytes.
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/root/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1
I STARTING Optimization
I Training of Epoch 0 - loss: 359.028595
I Training of Epoch 1 - loss: 192.948044
I Training of Epoch 2 - loss: 226.711533
I Training of Epoch 3 - loss: 180.602234
I Training of Epoch 4 - loss: 145.870453
I Training of Epoch 5 - loss: 157.380051
I Training of Epoch 6 - loss: 144.472702
I Training of Epoch 7 - loss: 138.105057
I Training of Epoch 8 - loss: 142.844727
I Training of Epoch 9 - loss: 139.909805
I Training of Epoch 10 - loss: 133.610733
I Training of Epoch 11 - loss: 133.186905
I Training of Epoch 12 - loss: 134.790802
I Training of Epoch 13 - loss: 132.281769
I Training of Epoch 14 - loss: 128.866882
I Training of Epoch 15 - loss: 127.601883
I Training of Epoch 16 - loss: 128.016113
I Training of Epoch 17 - loss: 125.186966
I Training of Epoch 18 - loss: 123.230835
I Training of Epoch 19 - loss: 120.769020
I Training of Epoch 20 - loss: 118.863579
I Training of Epoch 21 - loss: 116.341286
I Training of Epoch 22 - loss: 113.150780
I Training of Epoch 23 - loss: 110.229614
I Training of Epoch 24 - loss: 108.166756
I Training of Epoch 25 - loss: 104.465652
I Training of Epoch 26 - loss: 101.894493
I Training of Epoch 27 - loss: 97.565475
I Training of Epoch 28 - loss: 94.959503
I Training of Epoch 29 - loss: 90.845039
I Training of Epoch 30 - loss: 87.314827
I Training of Epoch 31 - loss: 83.088257
I Training of Epoch 32 - loss: 79.354385
I Training of Epoch 33 - loss: 74.980415
I Training of Epoch 34 - loss: 70.493866
I Training of Epoch 35 - loss: 66.212601
I Training of Epoch 36 - loss: 61.337326
I Training of Epoch 37 - loss: 57.566959
I Training of Epoch 38 - loss: 51.770466
I Training of Epoch 39 - loss: 48.860481
I Training of Epoch 40 - loss: 42.656582
I Training of Epoch 41 - loss: 39.113071
I Training of Epoch 42 - loss: 34.690170
I Training of Epoch 43 - loss: 30.556097
I Training of Epoch 44 - loss: 26.330395
I Training of Epoch 45 - loss: 22.336706
I Training of Epoch 46 - loss: 19.093647
I Training of Epoch 47 - loss: 17.412798
I Training of Epoch 48 - loss: 13.914777
I Training of Epoch 49 - loss: 12.436376
I FINISHED Optimization - training time: 0:01:20
Loading the LM will be faster if you build a binary file.
Reading /opt/DeepSpeech/data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Traceback (most recent call last):
  File "kenlm.pyx", line 114, in kenlm.Model.__init__ (python/kenlm.cpp:2132)
RuntimeError: lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43 
The above exception was the direct cause of the following exception: 
Traceback (most recent call last):
  File "DeepSpeech.py", line 1514, in train
    job.wer, job.samples = calculate_report(report_results)
  File "DeepSpeech.py", line 701, in calculate_report
    corrected = correction(decoding)
  File "/opt/DeepSpeech/util/spell.py", line 34, in correction
    layer = [(-log_probability(node + [cword]), node + [cword]) for cword in candidate_words(word) for priority, node in layer]
  File "/opt/DeepSpeech/util/spell.py", line 34, in <listcomp>
    layer = [(-log_probability(node + [cword]), node + [cword]) for cword in candidate_words(word) for priority, node in layer]
  File "/opt/DeepSpeech/util/spell.py", line 28, in log_probability
    return get_model().score(' '.join(sentence), bos = False, eos = False)
  File "/opt/DeepSpeech/util/spell.py", line 15, in get_model
    MODEL = kenlm.Model('./data/lm/lm.binary')
  File "kenlm.pyx", line 117, in kenlm.Model.__init__ (python/kenlm.cpp:2242)
OSError: Cannot read model './data/lm/lm.binary' (lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException. first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43) 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last):
  File "DeepSpeech.py", line 1649, in <module>
    tf.app.run()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1612, in main
    train()
  File "DeepSpeech.py", line 1518, in train
    job = COORD.next_job(job)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 478, in __exit__
    self._close_internal(exception_type)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 511, in _close_internal
    self._sess.close()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 739, in close
    self._sess.close()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 827, in close
    self._coord.join()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 390, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: Thread-9 Thread-17 Thread-21 Thread-10 Thread-18 Thread-22 Thread-19 Thread-23 Thread-24 Thread-11 Thread-25 Thread-15 Thread-16 Thread-3 Thread-26 Thread-4 Thread-12 Thread-5 Thread-13 Thread-6 Thread-7 Thread-20 Thread-14 Thread-8

**Comment by gaoxuesong** [comment]
How to fix the error? 
Pls help.

**Comment by lissyx** [comment]
It really looks like you don't have the proper language model data. Is your Git-LFS installation working wel ?

**Comment by gaoxuesong** [comment]
Thanks @lissyx . Install git-lfs and reclone the code, then the error is fixed.
Manually install Git Large File Storage, then open a terminal and run:
git clone https://github.com/mozilla/DeepSpeech
cd DeepSpeech
pip install -r requirements.txt
