### ISSUE TITLE
librivox.sh epoch time

### ISSUE THREAD

**Issue by varunravi** [mozilla/DeepSpeech#619]
Hey,

Has anyone achieved a WER of less than 5% with the Librispeech dataset? And how long did it take you to get through one epoch?

- Varun

**Comment by kdavis-mozilla** [comment]
Epoch time is hardware dependent; so, "it depends" is the answer.

One the clean data set running 15 epochs we got a WER of 12% on the clean subset.

**Comment by supriyalk** [comment]
Do you have the WER on just the librivox-clean-100 data set? I am not able to get anything better than 43%.
