### ISSUE TITLE
Training time on Librivox Data Set

### ISSUE THREAD

**Issue by istojan** [mozilla/DeepSpeech#626]
Hi guys,

I just started using this engine and I wanted to see its results on a lot of data. Could anyone give me a time estimate for the training needed for the librivox data set. I would run it on 2 x GTX 1080 with 8GB memory. 

Thanks for the response

**Comment by kdavis-mozilla** [comment]
Just for approximate reference, we trained librivox on 16 Titan X's Pascal's in a two node cluster in about 2 days.

**Comment by cnewton** [comment]
Kelly - Is the model you trained against the librivox dataset available anywhere?

**Comment by kdavis-mozilla** [comment]
Not yet. There was/is a disk failure on our cluster. The network filesystem corrupted the checkpoint.

**Comment by abuvaneswari** [comment]
@istojan , did you ever get to the training of librivox dataset on your 2x 1080 GTX system? I started training on my 2x 1080 GTX system with 12GB memory, default parameters as in run-librivox.sh. It has been 5 days and the first epoch is still not complete. @kdavis-mozilla, do you think this speed is expected?

**Comment by kdavis-mozilla** [comment]
@abuvaneswari This seems too slow.

@abuvaneswari As we're trying to move discussions to our [discourse forum](https://discourse.mozilla.org/c/deep-speech) and keep bugs + feature requests in the issues, could you move future discussions of training speed to the [discourse forum](https://discourse.mozilla.org/c/deep-speech). Thanks.
