### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by deepak02** [mozilla/DeepSpeech#630]
I need to get the trained model and run the inference locally on my laptop. Is there some documentation for this. I am new to deep speech and want to use this for my graduate project.

**Comment by lissyx** [comment]
Hello,

There is not (yet) pre-trained model available. For running the inference locally, you should refer to the `native_client/README.md` documentation :)

**Comment by deepak02** [comment]
Hi lissyx
Thanks for answering. So effectively, since there is no pre-trained model available, I need to train the model on servers first, export that model and only then I can run the inference locally on my laptop. 
my problem is that I do not have access to high end servers where this training can be done. Is there some work around for this.

Thanks
Deepak

**Comment by lissyx** [comment]
Well, sadly, if you don't have access to the computational resources it is going to not be possible. This is something we want to do for sure, but it does require some more work.

**Comment by dimatter** [comment]
Is there any information on training times? i.e how long does it take to train X on Y hardware?

**Comment by kdavis-mozilla** [comment]
Off the top of my head here are some examples @dimatter :
- TED data set with 4 Titan X Pascal GPU's takes 2h24m per epoch
- TED data set with 8 Titan X Pascal GPU's takes about 1h15m per epoch
- Librivox data set with 4 Titan X Pascal GPU's takes about 10h55m per epoch

**Comment by nealmcb** [comment]
Watch #435 for updates on the release of pre-trained models.
