### ISSUE TITLE
Cannot read model './data/lm/lm.b'

### ISSUE THREAD

**Issue by NghiLamPhuc** [mozilla/DeepSpeech#631]

**Comment by reuben** [comment]
You need to install Git LFS and then clone the repo again.

**Comment by NghiLamPhuc** [comment]
Sorry, I found the issue in the closed. I am trying to lock my issue!

**Comment by nguyenvietquoc2569** [comment]
Yeah! You are VNese? 
Please check your lm file, it was not synchronized when you cloned it. It is only 80kb. The real one is 80mb
Anyway. Ask me if you need someone do it together
Facebook : fb.com/rain0506 or rain_0506.
I dont remember exactly
