### ISSUE TITLE
module 'python_speech_features' and kenlm issue on spyder(Anaconda)

### ISSUE THREAD

**Issue by ztilottama** [mozilla/DeepSpeech#632]
Trying to execute the DeepSpeech code on Spyder (Windows 10), however I am unable to install"python_speech_features" and "Kenlm" library through CONDA install, Always getting below error for both
"PackageNotFoundError: Package missing in current win-64 channels:"
Appreciate any help if anyone can details steps to execute this project on WINDOWS

**Comment by kdavis-mozilla** [comment]
We've not tested on Windows. However, if you've found out any useful info, please let us know.

**Comment by lissyx** [comment]
Nothing actionable for us here. Feel free to open a thread on Discourse if you have more informations to share.
