### ISSUE TITLE
issues within running ./bin/run-ldc93s1.sh

### ISSUE THREAD

**Issue by tiagmoraismorgado** [mozilla/DeepSpeech#638]
# Greetings

**I did the following:**

- _cloned this repository_ 
- _installed the pre-requisites_ 
- _tried to run ./bin/run-ldc93s1.sh_

**unfortunately this is not running. maybe i will test it with python 3 as well to see if i get the same error message, you can find at my log in the gist down below**

_https://gist.github.com/tiagmoraismorgado/d9ae25c73012ad963bbb749c8c69c9b1_

**please provide me with insights on how i can deal with this compiling issue. looking forward**

**Comment by kdavis-mozilla** [comment]
A prerequisites is Git Large File Storage[[1](https://github.com/mozilla/deepspeech#prerequisites)]. 

You must first install Git Large File Storage, then re-clone the project.

**Comment by tiagmoraismorgado** [comment]
installed git large file storage

**Comment by tiagmoraismorgado** [comment]
you are right, i had installed it with homebrew, but it was not linked

**Comment by tiagmoraismorgado** [comment]
![captura de ecra 2017-06-19 as 10 36 22](https://user-images.githubusercontent.com/7303598/27279067-5a596bf4-54db-11e7-83d4-a3c6ed7d8a68.png)

**Comment by tilmankamp** [comment]
I think you have to do another `git lfs install` to finally activate it for git.

**Comment by kdavis-mozilla** [comment]
Did you re-clone the project?

**Comment by tiagmoraismorgado** [comment]
yes, i did

**Comment by tiagmoraismorgado** [comment]
i confirm that i was missing git lfs install to initialize the git lfs. i now cloned the project again and it seems to be cloning the entire 1.9 gb dataset

**Comment by tiagmoraismorgado** [comment]
i am not getting any further errors with git lfs but i am getting a weird traceback error message

**Comment by tiagmoraismorgado** [comment]
**https://vimeo.com/222183017 i got the example to finish the training bur i am not getting**
```
--------------------------------------------------------------------------------
I WER: 0.090909, loss: 4.567764, mean edit distance: 0.019231
I  - src: "she had your dark suit in greasy wash water all year"
I  - res: "she had your dark suit in greasy wash water al year"
I --------------------------------------------------------------------------------
```
**as part of my console output. is this what python console is supposed to return? kind regards. thank you very much**

**Comment by kdavis-mozilla** [comment]
Yes, other than the fact that it missed the last 'l' of 'all' it looks good.

**Comment by tiagmoraismorgado** [comment]
yes, the fact is that was initially getting this message, but i am not anymore

**Comment by kdavis-mozilla** [comment]
You only get it if the WER is not 0%. If it's 0% it doesn't print anything out.

**Comment by tiagmoraismorgado** [comment]
**thank you very much for all your precious insights. i concluded that:**
- _deepspeech is a state of the art speech reconigtion;_
- _however, it cannot be pretty tricky to do pattern matching;_

**if you have any suggestions of an implementation suitable for doing audio pattern matching, using tensorflow, i would be thankful**

**looking forward, kind regards**
