### ISSUE TITLE
Create a utility that continually receives audio files and does STT on them

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#640]

**Comment by kdavis-mozilla** [comment]
@reuben Could you give details on what you want to do here?

**Comment by elpimous** [comment]
anything like this ?
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, division, print_function
import sys
import scipy.io.wavfile as wav
from deepspeech.model import Model
import timeit
import os

model2 = '/home/nvidia/DeepSpeech/data/deepspeech_material/exported_model/output_graph.pb'
micro2 = '/home/nvidia/DeepSpeech/data/deepspeech_material/test/record.'

ds = Model(model2, 26, 9) #model link, cepstrum, context

REC = 'rec --encoding signed-integer --bits 16 --channels 1 --rate 16000 alfred.wav silence 1 0.1 1% 1 1.5 1%'

p = ''

print('''

     °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
     Testing Deepspeech model, with a simple rec voice detection
     press Enter to continue, or other input to leave !
     °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°

      ''')
while p == '':
    
      os.system(REC)
      b='alfred.wav'
      fs, audio = wav.read(b)
      a = str(ds.stt(audio, fs))
      print(a)
      p = raw_input('\n>>')
      pass
      
print('\nBye')
```

**Comment by kdavis-mozilla** [comment]
@reuben ping

**Comment by reuben** [comment]
Something like that, yes. We ended up deciding to build a GUI for the demonstration, and I plan to merge it when we release our models so people have a tool to test them more easily.

**Comment by jehoshua7** [comment]
> We ended up deciding to build a GUI for the demonstration, and I plan to merge it when we release our models so people have a tool to test them more easily.

@reuben - can you please advise what the status of this is ?

**Comment by reuben** [comment]
Yes, I ported the demo to work with our Python package and put it on that repo. Right now it depends on #1164 so you should install the deepspeech package from TaskCluster, not PyPI. I'm gonna update the README there to reflect that.

**Comment by jehoshua7** [comment]
@reuben - thanks; I was testing it last night.  :)

**Comment by lissyx** [comment]
Closing because that was done.
