### ISSUE TITLE
trying to test my model but receiving core dumped, any ideas why?

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#641]
I'm running:

 ARGS="/home/alan/DeepSpeech/logs/libribox/export_models/output_graph.pb   /home/alan/Projects/DeepSpeech/data/smoke_test/alan.wav" make run

and I receive: 

alan@alan:~/DeepSpeech/native_client$ ARGS="/home/alan/DeepSpeech/logs/libribox/export_models/output_graph.pb   /home/alan/Projects/DeepSpeech/data/smoke_test/alan.wav" make run ARGS="/home/alan/DeepSpeech/logs/libribox/export_models/output_graph.pb   /home/alan/Projects/DeepSpeech/data/smoke_test/alan.wav" make run
LD_LIBRARY_PATH=/home/alan/tensorflow/bazel-bin/tensorflow:/home/alan/tensorflow/bazel-bin/native_client::/home/alan/tensorflow/bazel-bin/tensorflow:/usr/local/cuda/lib64:/home/alan/tensorflow/bazel-bin/native_client ./deepspeech /home/alan/DeepSpeech/logs/libribox/export_models/output_graph.pb   /home/alan/Projects/DeepSpeech/data/smoke_test/alan.wav
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
formats: can't open input file `/home/alan/Projects/DeepSpeech/data/smoke_test/alan.wav': No such file or directory
deepspeech: client.cc:75: int main(int, char**): Assertion `input' failed.
Aborted (core dumped)
Makefile:63: recipe for target 'run' failed
make: *** [run] Error 134

**Comment by lissyx** [comment]
Can you make sure that `/home/alan/Projects/DeepSpeech/data/smoke_test/alan.wav` does exists and is accessible ?

**Comment by alanbekker** [comment]
when I converted it to mono and reduces the sample rate it worked...any
ideas why?

**Comment by lissyx** [comment]
No, the code should be able to resample. Though the error message is quite clear: `No such file or directory`, hence my previous question :)

**Comment by alanbekker** [comment]
Sorry, the error I sent you before wasn't related.

I meant to say that without converting to mono and sub-sample the audio the
results looked very bad. Do you know why?

**Comment by lissyx** [comment]
As I said earlier the code does resampling, so I'm surprised you get bad results. Can you share more informations on that ? `mediainfo` on the two WAV files might help, as well as the output of your network and how you trained your model.

**Comment by alanbekker** [comment]
The model was trained on livribox and achieved 30% WER.

I recorded my self saying "one two three four five"
The first file  is 44100hz, stereo (original)
The second is 8000hz mono (reduced)

with the reduced file the network output is:"len to flly full tham "
-obviously not good results but still the phone level is similar

but with the original file(stereo with 44100hz)  and don't get any network
output..I just get the message  "input: multi-channel effect drained
asymmetrically!"

**Comment by lissyx** [comment]
Network is being trained against 16kHz WAV mono audio files. The error `multi-channel effect drained asymmetrically!` is from SOX, I don't know exactly why, but I can investigate. Maybe it is resampling failing to work ?

Besides, 30% WER and the behavior you describe is consistent. Being a non native english speaker, a TED-trained at 35% WER network would produce similar garbage even in non-noisy recording when I speak, while a native american english speaker would get less garbage but has to articulate very precisely. This is why we need more training on more data.

**Comment by lissyx** [comment]
Checking: https://github.com/chirlu/sox/blob/master/src/effects.c#L356 we do have code in client.cc that leverage SOX' chain effect to resample. @Cwiiis does it rings any bell ?

**Comment by alanbekker** [comment]
I converted now to mono with 16k and received much better results "one too
thri four five"

**Comment by lissyx** [comment]
Thanks, then @alanbekker I guess we should close this issue. Can you file a clean new issue for the resampling behavior ? I'm as well surprised that you get different inference results with your hand-converted mono 16k. Was that converted from the stereo 44kHz file or the 8kHz mono one? If it was the 8kHz one, I would have expected that sox' resampling would have given you the same results.

So thanks for documenting that in the new issue :)
