### ISSUE TITLE
The sox doesn't convert my wav file to 16khz as supposed to

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#643]

**Comment by kdavis-mozilla** [comment]
Could you give us more detail? What importer? What error message? What data set?...

**Comment by tilmankamp** [comment]
@alanbekker If it's about importing data: the Fisher importer does 8 to 16 kHz [re-sampling](https://github.com/mozilla/DeepSpeech/blob/master/bin/import_fisher.py#L164). Maybe this helps.

**Comment by kdavis-mozilla** [comment]
Closing on in activity. @alanbekker if this is still a problem, feel free to reopen.
