### ISSUE TITLE
Understanding the ctc_beam_search_decoder 

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#644]
How does the CTC beam search works? I ask because something isn't clear to me.

A regular beam search assumes that the dependent probability of P(y1,..yn) (n is the beam width) is tractable it means that we now how to calculate P(yn| y1...Yn-1) but in our case how does the ctc_beam_search_decoder knows the transition statistics between the different characters? 

Somehow if I understand correct the ctc_beam_search_decoder  function needs to know the transition statistics between the different characters in the train-set but I can't see where this is happening in the code...

Thanks in advance!

**Comment by kdavis-mozilla** [comment]
`ctc_beam_search_decoder()` is a function in TensorFlow. You should refer to TensorFlow's documentation for the function[[1](https://www.tensorflow.org/api_docs/python/tf/nn/ctc_beam_search_decoder)].
