### ISSUE TITLE
inference time 

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#656]
HI guys,

I'm running inference on a 3 seconds wav file and according to my profiling the sess.run operation takes me 8 seconds, does it make sense to you? there is any way to optimize it?

In addition maybe someone tried to use a more shallow network rather than the default in the code.

Thanks,

Alan

**Comment by kdavis-mozilla** [comment]
The timing is hardware dependent. That said we've been able to do inference faster than real time on a MacBook Pro, i.e. a 3 sec sample takes less than 3 sec to process.
