### ISSUE TITLE
Error in Monitored Tensorflow Session

### ISSUE THREAD

**Issue by vtan25** [mozilla/DeepSpeech#662]
Reading /home/aneeme/Desktop/deepSpeech/data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
E Cannot read model './data/lm/lm.binary' (lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException. first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43)
Traceback (most recent call last):
  File "DeepSpeech.py", line 1719, in <module>
    tf.app.run()
  File "/home/aneeme/anaconda2/envs/tensorflow17/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1679, in main
    train()
  File "DeepSpeech.py", line 1577, in train
    hook.end(session)
  File "/home/aneeme/anaconda2/envs/tensorflow17/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 376, in end
    self._save(last_step, session)
  File "/home/aneeme/anaconda2/envs/tensorflow17/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 387, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/home/aneeme/anaconda2/envs/tensorflow17/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1386, in save
    raise TypeError("'sess' must be a Session; %s" % sess)
TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7f2d3b95ce10>

**Comment by kdavis-mozilla** [comment]
You need to install git large file storage[[1](https://github.com/mozilla/DeepSpeech#prerequisites)], remove the existing repo clone, then re-clone the repo.

**Comment by kdavis-mozilla** [comment]
@vtan25 I'm going to assume this fixed the problem and close the issue. If this is not the case, feel free to re-open.

**Comment by laibulle** [comment]
Hello, it did not work for me

**Comment by andi4191** [comment]
@laibulle: Did you run  _git lfs install_ after installation of git large file storage?
It should return the following output:
Git LFS initialized.

That should solve the problem.

**Comment by andi4191** [comment]
@laibulle : Cool :)

**Comment by megharangaswamy** [comment]
I followed this(https://help.github.com/articles/installing-git-large-file-storage/) in the begging as it was mentioned in **Prerequisites**  of readme.md in mozilla/DeepSpeech . 

but I end up with this after training for a long time. 

> TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7f3ac2879b10>

Look the below section just for more details on the error trace - may be it helps to analyse my issue


>D Starting batch...
>D Finished batch step 100193.
>D Sending Job (ID: 2195, worker: 0, epoch: 3, set_name: train)...
>D Computing Job (ID: 2196, worker: 0, epoch: 3, set_name: train)...
>... 
>D Finished batch step 102211.
> D Sending Job (ID: 4213, worker: 0, epoch: 3, set_name: train)...
> D Computing Job (ID: 4214, worker: 0, epoch: 3, set_name: train)...
> D Starting batch...
> 2018-03-22 14:16:27.628874: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at ctc_loss_op.cc:166 : Invalid argument: Labels length is zero in batch 6
> E Labels length is zero in batch 6
> E 	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/logits/_915, tower_0/ToInt64/_917, tower_0/Gather, tower_0/Gather_DequeueMany:1)]]
> E 	 [[Node: Mean_4/_965 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1981_Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> E 
> E Caused by op u'tower_0/CTCLoss', defined at:
> E   File "DeepSpeech.py", line 1838, in <module>
> E     tf.app.run()
> E   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
> E     _sys.exit(main(argv))
> E   File "DeepSpeech.py", line 1795, in main
> E     train()
> E   File "DeepSpeech.py", line 1501, in train
> E     results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
> E   File "DeepSpeech.py", line 640, in get_tower_results
> E     calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
> E   File "DeepSpeech.py", line 527, in calculate_mean_edit_distance_and_loss
> E     total_loss = tf.nn.ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
> E   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.py", line 158, in ctc_loss
> E     ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
> E   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 212, in _ctc_loss
> E     name=name)
> E   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> E     op_def=op_def)
> E   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
> E     op_def=op_def)
> E   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
> E     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> E 
> E InvalidArgumentError (see above for traceback): Labels length is zero in batch 6
> E 	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/logits/_915, tower_0/ToInt64/_917, tower_0/Gather, tower_0/Gather_DequeueMany:1)]]
> E 	 [[Node: Mean_4/_965 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1981_Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> E 
> Traceback (most recent call last):
>   File "DeepSpeech.py", line 1637, in train
>     _, current_step, batch_loss, batch_report = session.run([train_op, global_step, loss, report_params], **extra_params)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
>     run_metadata=run_metadata)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
>     run_metadata=run_metadata)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
>     raise six.reraise(*original_exc_info)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
>     run_metadata=run_metadata)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 950, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
>     run_metadata_ptr)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
>     options, run_metadata)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
>     raise type(e)(node_def, op, message)
> InvalidArgumentError: Labels length is zero in batch 6
> 	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/logits/_915, tower_0/ToInt64/_917, tower_0/Gather, tower_0/Gather_DequeueMany:1)]]
> 	 [[Node: Mean_4/_965 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1981_Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> 
> Caused by op u'tower_0/CTCLoss', defined at:
>   File "DeepSpeech.py", line 1838, in <module>
>     tf.app.run()
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "DeepSpeech.py", line 1795, in main
>     train()
>   File "DeepSpeech.py", line 1501, in train
>     results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
>   File "DeepSpeech.py", line 640, in get_tower_results
>     calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
>   File "DeepSpeech.py", line 527, in calculate_mean_edit_distance_and_loss
>     total_loss = tf.nn.ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.py", line 158, in ctc_loss
>     ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 212, in _ctc_loss
>     name=name)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
>     op_def=op_def)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> InvalidArgumentError (see above for traceback): Labels length is zero in batch 6
> 	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/logits/_915, tower_0/ToInt64/_917, tower_0/Gather, tower_0/Gather_DequeueMany:1)]]
> 	 [[Node: Mean_4/_965 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1981_Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> 
> D Closing queues...
> D Queues closed.
> Traceback (most recent call last):
>   File "DeepSpeech.py", line 1838, in <module>
>     tf.app.run()
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "DeepSpeech.py", line 1795, in main
>     train()
>   File "DeepSpeech.py", line 1666, in train
>     hook.end(session)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 463, in end
>     self._save(session, last_step)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 474, in _save
>     self._get_saver().save(session, self._save_path, global_step=step)
>   File "/home/megha/Alu_Meg/DeepSpeech_Alug_Meg/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1646, in save
>     raise TypeError("'sess' must be a Session; %s" % sess)
> **TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7f3ac2879b10**>
> 

Can I do some thing to make this work or any suggestion ?


thanks :)

**Comment by kdavis-mozilla** [comment]
@megharangaswamy What exactly did you run? What is your setup? What OS? What version of TF? What command line did you execute?
