### ISSUE TITLE
no lm of native_client output?

### ISSUE THREAD

**Issue by jinserk** [mozilla/DeepSpeech#673]
I'm not sure there is no doc or explanation about this, but the output of native_client seems no lm. Am I correct?
If so, how I can add this?

**Comment by reuben** [comment]
You'd have to reimplement the stuff in util/spell.py in C/C++ (kenlm has a C/C++ API).

**Comment by reuben** [comment]
PRs welcome!

**Comment by jinserk** [comment]
Simply I've modified the native_client/client.py like this:
```
#!/usr/bin/env python3

import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

import scipy.io.wavfile as wav
from deepspeech.model import Model
from util.spell import correction

ds = Model(sys.argv[1], 26, 9)
fs, audio = wav.read(sys.argv[2])

output = ds.stt(audio, fs)
corrected = correction(output)
print(output)
print(corrected)
```
Anyway it seems it works. since util is not the part of native_client package, so I didn't send PR. Will try to improve client.cc later. :)

**Comment by kdavis-mozilla** [comment]
@jinserk as you've soled your problem, I'm going to close.

**Comment by proflim** [comment]
@jinserk How did you run client.py? I get 'Segmentation fault (core dumped)' when running 
`python native_client/client.py /path/to/graph /path/to/audio`
