### ISSUE TITLE
Handling audio with more than one channel?

### ISSUE THREAD

**Issue by gardenia22** [mozilla/DeepSpeech#675]
I have some audio data with 2-d stereo format. Seems like currently only 1-d mono audio is supported in training process? I have to add following code in `audio.py` to make the result right:
```
    # Load wav files
    fs, audio = wav.read(audio_filename)

    # if audio have more than 1 dimension, take the mean of all the channels as one channel
    if len(audio.shape) > 1:
        audio = audio.mean(axis=1, dtype=np.int16)

    # Get mfcc coefficients
    orig_inputs = mfcc(audio, samplerate=fs, numcep=numcep)
```
I also tried only take the first channel, it worked even better than the mean value on my dataset. 
```
        #audio = audio.mean(axis=1, dtype=np.int16)
        audio = audio[:,0]
```
Also, 2-d stereo wav file causes following error in `native_client.py`:
```
>>> ds.stt(audio, fs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gardenia/virlen/lib/python2.7/site-packages/deepspeech/deepspeech.py", line 121, in stt
    return _deepspeech.Model_stt(self, aBuffer, aSampleRate)
TypeError: Array must have 1 dimensions.  Given array has 2 dimensions
```

**Comment by tilmankamp** [comment]
@gardenia22 Interesting observations. Unfortunately you are right - we don't support stereo at the moment.

**Comment by gardenia22** [comment]
Since the default `wav` format in training process has 16000 sample rate and 1 channel. I converted my dataset with 16000 sample rate and 1 channel to make the format consistent. 
In `_maybe_convert_wav_dataset` function in `import_xxx.py`, add something like this:

```
                transformer = Transformer()
                transformer.convert(samplerate=16000, n_channels=1)
                transformer.build(mp3_file, wav_file)
```
It is the best solution I found so far.

**Comment by arunimathappa** [comment]
File "/data/newdeepspeech/DeepSpeech/util/audio.py", line 73, in audiofile_to_input_vector
    orig_inputs = mfcc(audio, samplerate=fs, numcep=numcep)
**NameError: name 'mfcc' is not defined**

what should i do to correct this error

**Comment by lissyx** [comment]
@arunimathappa First, stop replying on already closed bugs, with no useful related information. Two, ask on Discourse. Three, it's strange, you should have an another error earlier, or there's something wrong with your `python_speech_features` package.

**Comment by lissyx** [comment]
@gardenia22 We landed support for conversion, though it might not be perfect. I'm closing that, if there are improvements to be done on the conversion, feel free to start a thread on Discourse: https://discourse.mozilla.org/c/deep-speech

**Comment by NicoletteIge** [comment]
@gardenia22 I am trying to follow your solution, I got lost with, "In _maybe_convert_wav_dataset function from import_xxx.py". I am unsure of what you are referring to.
