### ISSUE TITLE
Quantization: cannot quantize_nodes with transform_graph

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#691]
Confere https://github.com/tensorflow/tensorflow/issues/7162

**Comment by leonxun** [comment]
Dear Lissyx，

        I tried to quantize the pre-trained model, use the tensorflow GTT, transform_graph.py to convert it to quantized model. use the following commands:

bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=output_graph.pb \
--out_graph=optimized_graph.pb \
--inputs='input_node' \
--outputs='output_node' \
--transforms='add_default_attributes strip_unused_nodes(type=float, shape="1,299,299,3") remove_nodes(op=Identity) fold_old_batch_norms quantize_weights quantize_nodes strip_unused_nodes sort_by_execution_order'

     it works to transform the model from 490M to 122M, try to build native_client with all kernel op support, this quantized model works for inference. but I got following issues:

1: the BI-RNN layer seams not quantized. the calculation performed still in FLOAT type, Have you ever succeded in quantizing BI-RNN layer?
2: the inference time seams became longer, about 2-3 times than the 32bit float model. 

Thanks,
Leon

**Comment by lissyx** [comment]
@leonxun Yes, this is not news to us.

**Comment by leonxun** [comment]
@lissyx Thanks, but is there any chance to quantize the LSTM node competely？

**Comment by lissyx** [comment]
We'll see that after #1275

**Comment by leonxun** [comment]
OK，Thanks

**Comment by lissyx** [comment]
Closing, because it's not accurate anymore.
