### ISSUE TITLE
Train-set batch size used for dev and test

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#698]
So far in `DataSet.next_batch()` the batch size is not treated as a placeholder. Therefore it is injected into the graph as a constant. Effectively it carries the value of the default data-set's batch size - which is the one from the train-set.

**Comment by kdavis-mozilla** [comment]
Is it really the case that this carries the train data set's batch size?

For example the TED batch sizes [run-ted.sh](https://github.com/mozilla/DeepSpeech/blob/master/bin/run-ted.sh) are 16, 8, and 8 for train, dev, and test respectively.

From testing we know that the batch size 16 will give and OOM on a Titan X with 12GB, this is the reason we introduced different train, dev, and test batch sizes to begin with.

So if what you are saying is true, then we should get an OOM on a Titan X with 12GB when running TED dev or test data sets. We don't get such an OOM.

**Comment by tilmankamp** [comment]
I also wondered exactly about this.

**Comment by kdavis-mozilla** [comment]
My guess is that there are 3 values injected in to the graph, one for training, one for dev, and one for test.
