### ISSUE TITLE
Integrate a linter as a git pre-commit hook

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#703]
We should integrate a linter in a git pre-commit hook to make it easier for everyone to stay on a consistent code style. Personally, I think we should follow the output of [autopep8](https://pypi.python.org/pypi/autopep8) as our code style.

**Comment by kdavis-mozilla** [comment]
I'm not religious about formatting so autopep8 is fine by me.

**Comment by reuben** [comment]
Git pre-hooks are hard to set up and share across the team and external contributors. I've been toying with the idea of running a linter as a CI step on PRs. Here's an example of what it would look like: https://github.com/reuben/DeepSpeech/pull/6

There's two runs there, the initial one that adds the config and passes the lint check, and then a commit that adds some lint problems to trigger a failure.

It uses Travis CI and cardboardlint to run the linter on just the changes added in the PR, so nobody should get forced to correct problems in other parts of the code in their PR, but it does mean if you're touching some existing code that has problems, you'll need to fix it. I've tried to fix most of the existing problems to make this less of an issue.

@kdavis-mozilla @tilmankamp @lissyx what do you think? This should help us keep a consistent style specially with external contributors. It's also super easy to add cppcheck to also check our native code, just add the config file and another entry in the .cardboardlint.yml file.

**Comment by kdavis-mozilla** [comment]
Seems reasonable to me.

**Comment by lissyx** [comment]
Also okay with me. Can we still document the local use and how people should enable it by default on their pre-commit setup ?

**Comment by reuben** [comment]
Local use is:

```
pip install cardboardlint
cardboardlinter
```

Getting a pre-commit hook working requires platform-specific instructions and handling missing packages which is the reason why I decided to go with the CI approach. I'll document the steps above somewhere, maybe add a CONTRIBUTING.md file.

**Comment by lissyx** [comment]
Let's close this.
