### ISSUE TITLE
Native client error

### ISSUE THREAD

**Issue by varunravi** [mozilla/DeepSpeech#705]
Trying to run the native client and am getting this error when I try initiating the make run command against a .wav file and the out graph my export produced. 

`ILANGOs-MacBook-Pro:native_client ravi$ ARGS="/Users/ravi/Desktop/DeepSpeech/export/output_graph.pb /Users/ravi/Desktop/DeepSpeech/174-50561-0000.wav" make run
DYLD_LIBRARY_PATH=../../tensorflow/bazel-bin/tensorflow:../../tensorflow/bazel-bin/native_client:/Developer/NVIDIA/CUDA-8.0/lib ./deepspeech /Users/ravi/Desktop/DeepSpeech/export/output_graph.pb /Users/ravi/Desktop/DeepSpeech/174-50561-0000.wav
dyld: lazy symbol binding failed: Symbol not found: __ZN10tensorflow8GraphDefC1Ev
  Referenced from: ../../tensorflow/bazel-bin/native_client/libdeepspeech.so
  Expected in: flat namespace

dyld: Symbol not found: __ZN10tensorflow8GraphDefC1Ev
  Referenced from: ../../tensorflow/bazel-bin/native_client/libdeepspeech.so
  Expected in: flat namespace

make: *** [run] Trace/BPT trap: 5
`

**Comment by lissyx** [comment]
Can you ensure `libtensorflow_cc.so` was properly built? And make sure it is part of  `../../tensorflow/bazel-bin/tensorflow/` ?

Can you run `otool -L` on both `libdeepspeech.so` and `libtensorflow_cc.so` ?

**Comment by lissyx** [comment]
Nothing actionable, and likely to have been fixed for a while now.
