### ISSUE TITLE
tensorflow deep convolutional recursive swarm of hybrid bdi and ANN

### ISSUE THREAD

**Issue by ghost** [mozilla/DeepSpeech#706]
<h1> [WISHLIST] tensorflow deep convolutional recursive swarm of hybrid bdi and ANN</h1>

<b>it would be interesting to have:</b>

- <i>an implementation of the previous model in a framework like tensorflow.</i>

<b>just use this: </b>

- <i>https://drive.google.com/file/d/0B2kT6ra3MW4FTnI1OFRtcWdheWs/view?usp=sharing as a basis for start developing it. I will be happy to get involved. </i>

it was my PhD proposal for city university of london. i didn't get accepted, so, why not opensourcing the overal phd proposal and get it implemented easily in a far much faster rate? 

the interesting aspect of this project is that it has musical and medical implications, although it can be linked to almost anything.

**Comment by lissyx** [comment]
@ghost Have you been able to hack on that ?

**Comment by udaymistry** [comment]
Page Not Found

**Comment by kdavis-mozilla** [comment]
I'm going to close due the the "Page Not Found" error and @ghost not giving any updates over the last 2 years.
