### ISSUE TITLE
File not found error when not providing a train_files parameter 

### ISSUE THREAD

**Issue by robmsmt** [mozilla/DeepSpeech#707]
I have set --train False so it should not be looking for train_files or dev_files ? I am having to provide it a dummy file currently.

**Comment by rmsmith88** [comment]
To add to this- there is no way of telling if a checkpoint/model has been loaded for test mode. Unless I am missing something.

**Comment by reuben** [comment]
Yeah I had to workaround this for some local tests but ended up just passing data/ldc93s1/ldc93s1.csv for train/validation files. Supporting empty lists requires a surprisingly large amount of modifications.

**Comment by rmsmith88** [comment]
That's exactly what I did. I don't believe that supporting empty lists is in order. With --train False you should bypass any training and therefore train csv reading all together.

**Comment by kdavis-mozilla** [comment]
Closing as no longer needed.
