### ISSUE TITLE
Hosting language model binary outside of source tree

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#711]
There is a problem with the way we host the language model binaries as part of the source tree: First time users are usually not aware of the LFS requirement.

So - like the corpora - the language model binaries could be hosted outside the source tree:
 - Hosted on some service like S3
 - Download URLs should feature a version number
 - Current binary version number being part of current source code
 - There is a /bin script to download the required version
 - DeepSpeech.py should fail with a help message, if required binary not downloded yet 
 - Removing LFS requirement
 - Potentially rewriting master history to get rid of old binaries (warning to all the community in advance)

**Comment by mertyildiran** [comment]
@tilmankamp how can I get the pre-trained models mentioned in [the graph here](http://doyouunderstand.me/)? I would like to try the models by myself. :blush: 

As far as I understand, you are planning to host these models in somewhere, according to this issue. That's a good news. :+1:

**Comment by tilmankamp** [comment]
@mertyildiran This graph is already a bit dated. Yes, we want to get soon a fresh graph and at least one up-to-date pre-trained model.

**Comment by mertyildiran** [comment]
@tilmankamp what is the size of the model, approximately? Also is there anything I can do to speed up the resolvement of this issue? If there is nothing I can do about it then could you give me an estimated date of the publication of the official model? :blush:

**Comment by hwine** [comment]
@tilmankamp anything I can do to move this split along? The LFS support is a bit of a pain to keep dealing with (for various reasons).

**Comment by tilmankamp** [comment]
@hwine This involves some external storage to be provided and managed. Therefore I think this is something to be handled by us. If we still want to do it. As I now understood Git LFS a bit better, I now know that Git LFS is NOT storing the binaries within the repo itself. It just downloads the binaries required by commits that you check out/work with (I'll change the issue's discription accordingly).

**Comment by mertyildiran** [comment]
@tilmankamp you are correct. I even use Git LFS to store large CAD files in [this project](https://github.com/DragonComputer/DragonArmor) for example.

You can also consider to use [releases section](https://github.com/mozilla/DeepSpeech/releases) to store the binaries.

By the way what is the size of the language model binary?

**Comment by tilmankamp** [comment]
@mertyildiran You are right in regards to the release section - it just feels a bit hack-ish. The current `lm.binary` is about 1.5 GB.

**Comment by hwine** [comment]
> @kdavis-mozilla What's your opinion?
> I tend to keep Git LFS for now and close this (sorry @hwine).

No worries -- just be aware that the object may not be available at times due to delays in adding additional data packs as needed.

**Comment by kdavis-mozilla** [comment]
@hwine Ok. I think we need to come up with a global strategy as to how to release models, as we're going to be doing so soon. I think the language model storage can be part of that discussion.

**Comment by hwine** [comment]
Sounds good -- I don't think getting space on S3 will be an issue (and I think that works with LFS by just flipping the URL). The real problem isn't technical or financial, it's administrative challenges using GitHub for hysterical raisins.
