### ISSUE TITLE
ImportError: No module named data_set_helpers

### ISSUE THREAD

**Issue by deepak02** [mozilla/DeepSpeech#715]
Hi 
While running ./bin/run-ldc93s1.sh, I am getting this error

Traceback (most recent call last):
  File "bin/import_ldc93s1.py", line 13, in <module>
    from util.data_set_helpers import DataSets, DataSet
ImportError: No module named data_set_helpers

Can somebody help here?

Thanks

**Comment by tilmankamp** [comment]
Oh - this is a glitch of my most recent merge. Will fix this immediately.

**Comment by tilmankamp** [comment]
Fixed. Please try again with latest master.

**Comment by prashantmaheshwari94** [comment]
I have cloned branch ds2-v2 in that I am facing the same issue. Can anyone help in this
Traceback (most recent call last):
  File "bin/import_ldc93s1.py", line 13, in <module>
    from util.data_set_helpers import DataSets, DataSet
ImportError: No module named data_set_helpers

Thanks

**Comment by prashantmaheshwari94** [comment]
I followed your commit and commented that line. It worked fine. :)
