### ISSUE TITLE
Benchmark the CTC against a seq2seq model

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#721]
Hi all,

I curious if some one has the thoughts to replace the ctc_loss with seq2seq mechanisem (with attention..)?

The main advantages would  be:
1.The repeated chars would't need to be merged and words like "three" would not convert to "thre".
2. Easy incorporation of LM into the transcription decoding.
3. Replacing the chars prediction with words prediction

**Comment by kdavis-mozilla** [comment]
We've thought about replacing the entire BRNN + CTC with CNN's much like Wav2Letter[[1](https://arxiv.org/abs/1609.03193)] but we've not implemented anything.

If you'd be interested in pursing this, we'd be very interested in your results as Tensorflow quantization, which we want to use to compress the model, doesn't play well with BNN or RNN.

**Comment by alanbekker** [comment]
Thanks for the response, maybe in the next couple of months I'll do it, and
I will share my obtained results.

**Comment by patrickms** [comment]
There are some promising results in this paper from Baidu:
[Exploring Neural Transducers for End-to-End Speech Recognition](https://arxiv.org/abs/1707.07413)

**Comment by kdavis-mozilla** [comment]
@patrickms Yeah the results look very promising!

**Comment by kdavis-mozilla** [comment]
@patrickms Also added issue to track RNN-Transducer benchmark #753

**Comment by patrickms** [comment]
@kdavis-mozilla thank you very much.

**Comment by kdavis-mozilla** [comment]
Not going to do for now.
