### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by RyanEdwardHall** [mozilla/DeepSpeech#723]
It would be really helpful if there were an official docker image with everything configured, ready to go. I've followed the setup guide and am still unable to build the native client for inference.

**Comment by pranjaldaga** [comment]
Seconded

**Comment by lissyx** [comment]
Can you please document your need to build the native client for inference ? I can understand that in the past it was mandatory, but we now have everything build and exposed as artifacts, for example https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu or https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/arm or https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/osx or https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/gpu

Which of your use-case is not covered ? @RyanEdwardHall @pranjaldaga

**Comment by voidspacexyz** [comment]
I have been building the docker image. The issue that I am facing with your pre-built clients for CPU machines is that, right after training (using ./bin/run-ldc93s1.sh ), it ends up in a core dump.

I Training of Epoch 46 - loss: 9.216556
I Training of Epoch 47 - loss: 7.460158
I Training of Epoch 48 - loss: 7.166224
I Training of Epoch 49 - loss: 5.868577
I FINISHED Optimization - training time: 0:00:57
Illegal instruction (core dumped)

But the same on a GPU machine does not seem to have any issue. 

I am still wondering if this should be a seperate issue or should be discussed under the same

**Comment by lissyx** [comment]
@voidspacexyz Your docker picks any release of tensorflow, as I documented on issue #896 it's likely to be the root cause because of incompatibilities with our CTC decoder and your Tensorflow release.

**Comment by 0shape** [comment]
mine currently worked binary composed version of Dockerfile
https://gist.github.com/0shape/543b90257da8c3dbe43e64193135cdb5

**Comment by cbluth** [comment]
I see this here: https://github.com/mozilla/DeepSpeech/blob/master/Dockerfile
