### ISSUE TITLE
Variables are not restored from a checkpoint file

### ISSUE THREAD

**Issue by HyuntakLee** [mozilla/DeepSpeech#725]
I am trying to use a checkpoint file to save and restore variables.
But restoring doesn't work while saving works.

`python3 DeepSpeech.py --train_files "data/mydata/train.csv" --dev_files "data/mydata/dev.csv" --test_files "data/mydata/test.csv" --train_batch_size 12 --dev_batch_size 12 --test_batch_size 12 --display_step 1 --validation_step 1 --epoch 15 --checkpoint_dir "data/mydata/checkpoint“ --log_level 0`

Checkpoint files are created every 10 minutes (default).
But when I stop the training and run again, it starts the training from the beginning again. (From batch step 0, epoch 0)

I added `checkpoint_dir = FLAGS.checkpoint_dir` to the argument of MonitoredTrainingSession, and the model was restored properly.
I wonder if this is the right thing, or is there another correct way?

**Comment by kdavis-mozilla** [comment]
@HyuntakLee Could you update you copy of the code? I think this was fixed with commit a0a9e9d

**Comment by HyuntakLee** [comment]
Oh! Sorry I didn't know it was fixed. It's working now. Thanks.
