### ISSUE TITLE
Provide libdeepspeech as part of virtualenv on server

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#728]

**Comment by kdavis-mozilla** [comment]
How would code changes get propagated to libdeepspeech?

**Comment by tilmankamp** [comment]
By us - using some script that will update it. It's the same as with all other dependencies that could change.

**Comment by kdavis-mozilla** [comment]
What if two people are running two tests that require different libdeepspeech versions?

**Comment by tilmankamp** [comment]
What if they do something like this in regards to one of the other dependencies? If you really want to be safe here, we cannot do it. Not even with a CI build, as this would require to switch between different CI integrated libdeepspeech versions. 

However: If you see our cluster as a CI system, we should integrate/install everything for every run - also all the dependencies (including TF).

**Comment by reuben** [comment]
Our only training dependency on native client code is now the ctcdecoder, which is [installed from TaskCluster](https://github.com/mozilla/DeepSpeech/blob/8f2c3f0f0080e2bdf1f715ec06a340ddafc1282a/.install#L10-L11), so closing this. Feel free to reopen if it's still relevant.
