### ISSUE TITLE
Move corpora into sub-directories of shared data directory

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#729]
There should be standard sub directories within the shared data directory named after the corpora/organizations. Scripts and importers should be altered accordingly.

**Comment by reuben** [comment]
Is this already fixed? Right now we have this layout:

```
data="${DATA_ROOT}/shared/data"
fis="${data}/LDC/fisher"
swb="${data}/LDC/LDC97S62/swb"
lbs="${data}/OpenSLR/LibriSpeech/librivox"
```

Which is already under a `organization/corpus` folder structure.

**Comment by reuben** [comment]
I think this is fixed. Feel free to reopen if not.
