### ISSUE TITLE
Workflow for producing and publising WER values

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#73]
Let us design and document a complete end-to-end workflow that will:
 * train a network out of master
 * keep track of WER
 * publish that onto a website

Per design of current notebook, `merge_logs()` mostly does the keep track part.

**Comment by lissyx** [comment]
I suggest we name the branch used for the WER production « wer-tracking » @kdavis-mozilla @gregorwagner

**Comment by kdavis-mozilla** [comment]
@lissyx "wer-tracking" sounds fine to me
