### ISSUE TITLE
native client RuntimeError -- message unclear

### ISSUE THREAD

**Issue by gvoysey** [mozilla/DeepSpeech#733]
running the native client against the master branch of DeepSpeech, with the libraries on the path: 

`RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa`

It's clear that my version of numpy doesn't match the one the wheel used, but I don't know what those (hex?) strings  mean.

**Comment by kdavis-mozilla** [comment]
@lissyx Do have a guess?

**Comment by lissyx** [comment]
Not really. @gvoysey can you document more precisely what you do ? It's unclear whether you are using some pre-built binaries from us or build everything yourself, nor the platform you are working on.

**Comment by lissyx** [comment]
FYI, lurking on the internets gives me that: https://github.com/astropy/astropy/issues/5939#issuecomment-291233773, so without more information on what you do, which system, etc., it's going to be tricky and it seems to be related to your system.

**Comment by gvoysey** [comment]
@lissyx sorry for the long delay. 

I've since switched management of python installations to the (truly awesome) [pyenv](https://github.com/pyenv/pyenv), and with more careful management, this hasn't recurred.  I don't think it's your bug, so I'm closing it.  Thanks!
