### ISSUE TITLE
Invalid link order result in linker failure

### ISSUE THREAD

**Issue by kuropone** [mozilla/DeepSpeech#735]
when i'm running command make deepspeech inside native client, i got this following error

g++ -o deepspeech `pkg-config --cflags sox` -L../../tensorflow/bazel-bin/tensorflow -L../../tensorflow/bazel-bin/native_client  client.cc `pkg-config --libs sox` -ltensorflow_cc -ldeepspeech -ldeepspeech_utils 
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsAtLeast(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Env::Default()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ConfigProto::~ConfigProto()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::SlowCopyFrom(tensorflow::Status::State const*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::dim_size(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckIsAlignedAndSingleElement() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::SlowCopyFrom(tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::Tensor(tensorflow::DataType, tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::~Tensor()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::TensorShape(tensorflow::gtl::ArraySlice<long long>)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::~GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::DestructorOutOfLine()'
collect2: error: ld returned 1 exit status
Makefile:48: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1

after i debug makefile, this line which cause the error

deepspeech: client.cc
$(TOOLCHAIN)$(CXX) -o deepspeech $(CFLAGS) client.cc $(LDFLAGS)

this is my environtment
python 3.6.0
tensorflow GPU 1.1.0

anyone can help me?
Thx in advance

**Comment by kdavis-mozilla** [comment]
@lissyx Could you take a look? (PS: Thanks)

**Comment by kuropone** [comment]
Mr. gerard-majax give a solution for this one.
Just change the position of -ltensorflow_cc after -ldeepspeech

**Comment by lissyx** [comment]
@kuropone can you give us here your gcc version ?

**Comment by kuropone** [comment]
sorry for late reply.
here is my gcc version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by lissyx** [comment]
@kuropone Please, this is an issue, not a discussion forum, let us deal with one problem at a time.

**Comment by lissyx** [comment]
Changing the link order on TC build resulted in non-regression as exposed in https://tools.taskcluster.net/task-group-inspector/#/c04XqBaBST6GPsAcaWfvzg, so it might be straightforward to fix.

**Comment by lissyx** [comment]
Closing as the fix was merged.
