### ISSUE TITLE
Installing under /lib on OSX ?

### ISSUE THREAD

**Issue by jeffxusichao** [mozilla/DeepSpeech#737]
Hi, I'm new to this field and this is surely a rookie question.
I'm trying to follow the instruction and put the native client file under /lib while I'm told that I have to break the Apple security system to achieve when attempting to get permission.
Is there a way that I can get around or I can put the file on somewhere else where I do not to get extra permission? Thx a lot!

**Comment by lissyx** [comment]
I'm not too much used to OSX, but I guess it is documented on our side to rely on `PREFIX=/usr/local make install [...]` so I'm a bit puzzled about your reference to `/lib`. 

Can you retry with the proper PREFIX ?

**Comment by lissyx** [comment]
We now have everything for OSX build on TaskCluster: https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/osx so you should be able to just download and extract that https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.osx/artifacts/public/native_client.tar.xz and run it :)
