### ISSUE TITLE
Build KenLM's LM model: 

### ISSUE THREAD

**Issue by cuhkebook** [mozilla/DeepSpeech#740]
When I attempt to build DS for new language, it needs to train a language model using KenLM.  I can run the KenLM toolkit but it always say

```
in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `discounts_[i].amount[j] < 0.0 || discounts_[i].amount[j] > j'.
```

My corpus is around 20,000 utterances (News) and 5-gram.  How to build a LM in DS by KenLM (or can use other toolkit?)

**Comment by kdavis-mozilla** [comment]
I used the steps described here[[1](https://kheafield.com/code/kenlm/estimation/)] to build an arpa model then a binary model from that. 

They suggest doing it all in one step as follows:
```bash
bin/lmplz -o 5 <text | bin/build_binary /dev/stdin text.binary
```

**Comment by cuhkebook** [comment]
Yes, i use same steps but got the mentioned error.

2017年7月25日 17:10 於 "Kelly Davis" <notifications@github.com> 寫道：

**Comment by kdavis-mozilla** [comment]
I'm not sure. It worked for me. Could you open an issue on the [kenlm](https://github.com/kpu/kenlm) repo?

**Comment by cuhkebook** [comment]
Yes, I have already opened an issue but see no reply.

**Comment by elpimous** [comment]
Dit you have success with arpa creation ?
lmplz --text xxx/xxx/sentences.txt --arpa  xxx/xxx/.arpa --o 5

**Comment by phanlong95** [comment]
cmake error configuring incomplete errors occurred and i can not find lmplz . so what can i do now ? 
:'(

**Comment by phanlong95** [comment]
lm.binary is ok. but i can not create trie file . help meeeeee

**Comment by lissyx** [comment]
Nothing actionable here, and @elpimous' tutorial on https://discourse.mozilla.org/c/deep-speech already covers this pretty well.
