### ISSUE TITLE
Refactor to ease switching of supported characters

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#741]

**Comment by elpimous** [comment]
Hi all,
I'd like to use this wonderfull package with non-ascii characters.
I'm french, working on robot. My AI is based on Rivescript (python 3), and plays with accents.
I tried some french sentences, and they all report errors on execution of deepspeech.

question1: can we use Unicode for input and output ? just need a simple conversion after output, to recovery special characters ?!

If anyone has idea...
See U all.
Vincent

**Comment by kdavis-mozilla** [comment]
The thrust of this issue is to make code changes that allow for any set of Unicode characters to be used as an "alphabet." So once this issue is resolved, one can use Unicode as input and output.

**Comment by lissyx** [comment]
We landed that a long time ago now.
