### ISSUE TITLE
Usage with Transfer Learning

### ISSUE THREAD

**Issue by wtesler** [mozilla/DeepSpeech#747]
Is there any pre-trained DeepSpeech model (for english at least), that is ready for inference? Something that can be tweaked with transfer learning to do new things. If someone has seen something like that, it would be useful to put here.

**Comment by JianCao92** [comment]
I would also greatly appreciate that!

**Comment by sanjayraojjn** [comment]
I also need this feature.

**Comment by kdavis-mozilla** [comment]
We are planning a 0.1.1 release within the next month or so, that will include checkpoints allowing for transfer learning.
