### ISSUE TITLE
Test a wavfile with the created model, in python

### ISSUE THREAD

**Issue by elpimous** [mozilla/DeepSpeech#752]
Could anyone post a simple example of the model testing with a wavefile as input ?!
Thanks all

**Comment by lissyx** [comment]
That PR should help https://github.com/mozilla/DeepSpeech/pull/731 :)

**Comment by elpimous** [comment]
hi Lissyx
Well, I don't see anything useful. I used to work with keras or pocketsphink, and it's quite different.

I can load my model and I have wav's !

Must I preprocess the wavefile ? Will the result be a numpy.array ?

Thanks

**Comment by lissyx** [comment]
@elpimous Have a look at that particular line: https://github.com/mozilla/DeepSpeech/pull/731/commits/3ea9344a14fe82b298bc982191f688c6d061b1aa#diff-d0ac6246cc1dba140dcaef678287e612R52

This is the call to native_client/client.py, I guess this is what you want to do. Current master code can be viewed at https://github.com/mozilla/DeepSpeech/blob/master/native_client/client.py

**Comment by elpimous** [comment]
@lissyx 
Thanks for help.
Ok, I tested native_client to stt a wav file : 

this doesn't produce anything ?!
```
ARGS="/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pbtxt /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav" make run
```
```
LD_LIBRARY_PATH=../../tensorflow/bazel-bin/tensorflow:../../tensorflow/bazel-bin/native_client:/home/nvidia/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu:/usr/local/cuda-8.0/lib64 ./deepspeech /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pbtxt /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav
```

**Comment by lissyx** [comment]
Well, as you can see in https://github.com/mozilla/DeepSpeech/blob/master/native_client/deepspeech.cc#L31 we only read from binary protocolbuffer file :), you should have had an error trying to use a text-based file.

Besides, it may also return empty string depending on your model's training: if it has not been trained enough, for instance. Have a look at the exit code, it should be 0 when everything works well.

**Comment by elpimous** [comment]
hello,
I converter a pbtxt to a pb, and tested..
```
ARGS="/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pbtxt /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav" make run

LD_LIBRARY_PATH=../../tensorflow/bazel-bin/tensorflow:../../tensorflow/bazel-bin/native_client:/home/nvidia/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu:/usr/local/cuda-8.0/lib64 ./deepspeech /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pbtxt /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav
```

No exit code.

**Comment by lissyx** [comment]
@elpimous In your command, it is still a .pbtxt file, is that right? Exit code should be checked with `$?` variable, after calling the code.

**Comment by elpimous** [comment]
@lissyx 

> Hello, it's the created deepspeech .bptxt, converted by tensorflow as binary file.
> ARGS="/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav $?" make run



> ......./checkout/graph.pb /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav 2

It returns the value 2 normal ?

**Comment by lissyx** [comment]
@elpimous That is not how you should be doing.

```
user@host$: ARGS="/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav" make run
user@host$: echo $?
```

This will run the client and output the proper exit code. Again, please tell us more how you trained that model, it may be exactly the same thing as what was in the thread linked by @kdavis-mozilla earlier.

**Comment by elpimous** [comment]
ok.
it returns 127   ...?

My model is the stock model from your github. no changes
my wav's are 16000 mono
the words.txt contains all my learnt sentences (i want to limit possibilities, and the variations are processed by my rivescript chatbot)
the lm.binary is the big french lm model from cmusphinx (i modified it to arpa, and after to kenlm bin, nearly 280 mo)

here is the python that I try to run.

#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function

> import sys
> import scipy.io.wavfile as wav
> from deepspeech.model import Model
> 
> model = '/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb'
> micro = '/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav'
> 
> ds = Model(model, 26, 3) #model link, cepstrum, context
> print('\nModel ok')
> 
> print('\nreading voice')
> fs, audio = wav.read(micro)
> print(ds.stt(audio, fs))
> print('Done')

**Comment by lissyx** [comment]
Exit code 127 obviously means something is wrong. If this is that python code, we should see some output. Make sure your python environment is properly setup and you have installed the deepspeech bindings properly.

Also, `make run` would rely on the C++ code. In that context, exit code 127 means `command not found`.

Please try (replace TFDIR with the appropriate values):
```
LD_LIBRARY_PATH=${TFDIR}/bazel-bin/tensorflow:${TFDIR}/bazel-bin/native_client:$LD_LIBRARY_PATH ./deepspeech /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav
```

**Comment by elpimous** [comment]
@lissyx 
Good. echo $? returns 0 !!
it was a link problem. Thanks

Regarding to my python code, it returns  a "Segmentation fault (core dumped)"
An idea ?

**Comment by lissyx** [comment]
Good. With exit code 0, do you have proper output ?

For the segfault, do you have the whole input ? Would it segfault when using the deepspeech python module ? gdb or strace might help get a hint there.

**Comment by elpimous** [comment]
@lissyx 

ARGS="/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav" make run

Returns no output !  (but echo $? -> 0)

my python, run from terminal : 
nvidia@tegra-ubuntu:~/deepspeech/DeepSpeech/native_client$
    python /home/nvidia/deepspeech/elpimous_utils/DPClient.py

DPClient.py:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function
import sys
import scipy.io.wavfile as wav
from deepspeech.model import Model

model = '/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb'
micro = '/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav'

ds = Model(model, 26, 3) #model link, cepstrum, context
print('\nModel ok')
print('\nreading voice')
fs, audio = wav.read(micro)
print(ds.stt(audio, fs))
print('Done')

loading model ok and fast
nothing for a long time, and
"Segmentation fault (core dumped)"

**Comment by elpimous** [comment]
Tested with graph.pbtxt and graph.pb : both work when echo  ->0
But for both, no return !

**Comment by lissyx** [comment]
Which version of tensorflow did you used to train ? Which version are you using to run ?

**Comment by elpimous** [comment]
run version : '1.0.1'
train version : I don't know !! same version !

**Comment by lissyx** [comment]
Was the model overfitted? pbtxt should segfault btw

**Comment by elpimous** [comment]
Ah... It's possible.
But same problems with LDC93S1
Should the command ARGS.... report anything ?

**Comment by lissyx** [comment]
How many epochs overfitting LDC93S1 ? Can you share the training logs ?

**Comment by elpimous** [comment]
yes. newbie question : where is log ?

**Comment by lissyx** [comment]
stdout when you perform training

**Comment by elpimous** [comment]
nvidia@tegra-ubuntu:~/deepspeech/DeepSpeech$ sudo ./bin/run-ldc93s1.sh 
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/nvidia/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/nvidia/.local/share/deepspeech/ldc93s1
W Parameter --validation_step needs to be >0 for early stopping to work
I Test of Epoch 50 - WER: 0.272727, loss: 33.7071266174, mean edit distance: 0.075472
I --------------------------------------------------------------------------------
I WER: 0.272727, loss: 33.707127, mean edit distance: 0.075472
I  - src: "she had your dark suit in greasy watch water all year"
I  - res: "she had your dak suit in greasy wash water al year"
I --------------------------------------------------------------------------------
nvidia@tegra-ubuntu:~/deepspeech/DeepSpeech$

**Comment by lissyx** [comment]
I'm out of ideas for tonight.

**Comment by elpimous** [comment]
Thanks Lissyx. Goodnight

**Comment by lissyx** [comment]
Oh wait !? Why `sudo` ? There is no need to use that. Can you provide (properly formatted, please) the output of:
```
strace -ff -e open,stat,read LD_LIBRARY_PATH=${TFDIR}/bazel-bin/tensorflow:${TFDIR}/bazel-bin/native_client:$LD_LIBRARY_PATH ./deepspeech /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/graph.pb /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/test/record.27.wav 2>&1
```

**Comment by elpimous** [comment]
hello Lissyx,
I did it without sudo, and no changes.

command : 
```
strace -ff -e open,stat,read LD_LIBRARY_PATH=/home/nvidia/tensorflow/bazel-bin/tensorflow:/home/nvidia/tensorflow/bazel-bin/native_client:$LD_LIBRARY_PATH ./deepspeech /home/nvidia/DeepSpeech/data/ldc93s1/checkpoint/graph.pbtxt /home/nvidia/DeepSpeech/data/ldc93s1/LDC93S1.wav 2>&1

strace: Can't stat 'LD_LIBRARY_PATH=/home/nvidia/tensorflow/bazel-bin/tensorflow:/home/nvidia/tensorflow/bazel-bin/native_client:/home/nvidia/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu:/usr/local/cuda-8.0/lib64': No such file or directory
```

??

**Comment by lissyx** [comment]
If you cannot get proper output with LDC93S1 then there is something wrong in your setup, somehow. But again you referred to `pbtxt` model, which would not work since we expect `pb` (binary) file.

**Comment by elpimous** [comment]
```
strace -ff -e open,stat,read LD_LIBRARY_PATH=/home/nvidia/tensorflow/bazel-bin/tensorflow:/home/nvidia/tensorflow/bazel-bin/native_client:$LD_LIBRARY_PATH ./deepspeech /home/nvidia/DeepSpeech/data/ldc93s1/checkpoint/graph.pb /home/nvidia/DeepSpeech/data/ldc93s1/LDC93S1.wav 2>&1

strace: Can't stat 'LD_LIBRARY_PATH=/home/nvidia/tensorflow/bazel-bin/tensorflow:/home/nvidia/tensorflow/bazel-bin/native_client:/home/nvidia/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu:/usr/local/cuda-8.0/lib64': No such file or directory
```
same...

As you said, I should see results with the "ARGS" native client command, with LDC93S1.
I'll search for the problem. Thanks Lissyx

**Comment by prashantmaheshwari94** [comment]
I am  facing similar problems on this issue. I also got segmentation fault when ran this command after training the model.
python client.py ../data/librivox/graph.pb ../../ba-dls-deepspeech/data/test-clean-wav/2300-131720-0010.wav

2017-08-07 03:30:34.083700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-08-07 03:30:34.084127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: Quadro P5000
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:00:05.0
Total memory: 15.89GiB
Free memory: 15.70GiB
2017-08-07 03:30:34.084154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-08-07 03:30:34.084162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-08-07 03:30:34.084177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro P5000, pci bus id: 0000:00:05.0)
Segmentation fault (core dumped).

On running this in gdb I got this error - 
(gdb) run client.py ../data/librivox/graph.pb ../../ba-dls-deepspeech/data/test-clean-wav/2300-131720-0010.wav                                         
Starting program: /home/paperspace/miniconda2/envs/mozilla-deepspeech2/bin/python client.py ../data/librivox/graph.pb ../../ba-dls-deepspeech/data/test-clean-wav/2300-131720-0010.wav
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffead1b700 (LWP 13443)]
[New Thread 0x7fffea51a700 (LWP 13444)]
[New Thread 0x7fffe7d19700 (LWP 13445)]
[New Thread 0x7fffe5518700 (LWP 13446)]
[New Thread 0x7fffe2d17700 (LWP 13447)]
[New Thread 0x7fffe0516700 (LWP 13448)]
[New Thread 0x7fffddd15700 (LWP 13449)]
[New Thread 0x7fffb0bff700 (LWP 13513)]
[New Thread 0x7fffb03fe700 (LWP 13514)]
[New Thread 0x7fffafbfd700 (LWP 13515)]
[New Thread 0x7fffaf3fc700 (LWP 13516)]
[New Thread 0x7fffaebfb700 (LWP 13517)]
[New Thread 0x7fffae3fa700 (LWP 13518)]
[New Thread 0x7fffadbf9700 (LWP 13519)]
[New Thread 0x7fffad3f8700 (LWP 13520)]
[New Thread 0x7fffacbf7700 (LWP 13524)]
[New Thread 0x7fff8ffff700 (LWP 13525)]
[New Thread 0x7fff8f7fe700 (LWP 13526)]
[New Thread 0x7fff8effd700 (LWP 13527)]
2017-08-07 03:33:51.973560: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-08-07 03:33:51.973944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: Quadro P5000
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:00:05.0
Total memory: 15.89GiB
Free memory: 15.70GiB
2017-08-07 03:33:51.973969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-08-07 03:33:51.973978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-08-07 03:33:51.974024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro P5000, pci bus id: 0000:00:05.0)
[New Thread 0x7fff8e3ff700 (LWP 13528)]
[New Thread 0x7fff8dbfe700 (LWP 13529)]
[New Thread 0x7fff8d3fd700 (LWP 13530)]
[New Thread 0x7fff8cbfc700 (LWP 13531)]
[New Thread 0x7fff81fff700 (LWP 13532)]
[New Thread 0x7fff817fe700 (LWP 13533)]
[New Thread 0x7fff80ffd700 (LWP 13534)]
[New Thread 0x7fff5d163700 (LWP 13535)]
[New Thread 0x7fff5c962700 (LWP 13536)]
[New Thread 0x7fff47fff700 (LWP 13537)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd0ac871c in csf_mfcc () from /home/paperspace/miniconda2/envs/mozilla-deepspeech2/lib/libdeepspeech_utils.so

Can anyone help me out in this. 
Thanks

**Comment by lissyx** [comment]
@prashantmaheshwari94 Thanks for the report, but I really need more context on what you have done. Have you built everything by yourself ? Trained ? Which version of tensorflow are you building, and which version have you trained on ?

**Comment by prashantmaheshwari94** [comment]
yeah I have built everything by myself following the instructions of gitHub readme. For training I did a virtual setup using conda environment installed tensorflow gpu version 1.1.0. But for testing I cloned tensorflow from github branch r1.1, and compiled as guided in Native_client Readme. 

Following this issue I converted my graph.pbtxt to graph.pb. 
I ran ARGS="../data/librivox/graph.pb ../../ba-dls-deepspeech/data/test-clean-wav/2300-131720-0010.wav" make run command I got no output with error code - 0.
and the python client.py path/to/model path/to/wavfile gave Seg fault description of that attached in my previous comment

**Comment by lissyx** [comment]
Please rebuild `native_client` bits and python bindings with debug infos, otherwhise the stacktrace is useless :)

**Comment by prashantmaheshwari94** [comment]
I rebuild native_client by adding --config=debug flag in bazel build. Is that the right way of enabling debug infos?
bazel build command -> bazel build -c opt --config=cuda --config=debug --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*

**Comment by lissyx** [comment]
@prashantmaheshwari94 I'm not sure 100% that this would work, I guess it is safer for you to change `native_client/BUILD` and add `-ggdb` into the `copts`. Probably that passing `--copt=-ggdb` to build the target `//native_client:*` would be good as well. I would advise against adding the `libtensorflow_cc.so` target though, since it is going to rebuild all and it takes time.

**Comment by prashantmaheshwari94** [comment]
Hi, I don't see any changes in the output of ARGS="../data/librivox/graph.pb ../../ba-dls-deepspeech/data/test-clean-wav/2300-131720-0010.wav"  command

LD_LIBRARY_PATH=../../tensorflow/bazel-bin/tensorflow:../../tensorflow/bazel-bin/native_client:/home/paperspace/torch/install/lib:/usr/lib/:/usr/lib32/nvidia-375/:/home/paperspace/torch/install/lib:/usr/lib/:/usr/lib32/nvidia-375/:/home/paperspace/src/torch/install/lib: ./deepspeech ../data/librivox/graph.pb ../../ba-dls-deepspeech/data/test-clean-wav/2300-131720-0010.wav
2017-08-07 06:43:44.887187: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-08-07 06:43:44.887675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: Quadro P5000
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:00:05.0
Total memory: 15.89GiB
Free memory: 15.70GiB
2017-08-07 06:43:44.887702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-08-07 06:43:44.887707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-08-07 06:43:44.887720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro P5000, pci bus id: 0000:00:05.0)
0

**Comment by lissyx** [comment]
If you re-run within `gdb` we should have more infos :) @prashantmaheshwari94

**Comment by prashantmaheshwari94** [comment]
This is the gdb output
Program received signal SIGSEGV, Segmentation fault.
csf_mfcc (aSignal=<optimized out>, aSignalLen=<optimized out>, aSampleRate=<optimized out>, aWinLen=<optimized out>, aWinStep=<optimized out>, 
    aNCep=1836412517, aNFilters=26, aNFFT=<optimized out>, aLowFreq=0, aHighFreq=8000, aPreemph=<optimized out>, aCepLifter=22, aAppendEnergy=1, 
    aWinFunc=0x0, aMFCC=0x7fffffffd2d0) at native_client/c_speech_features/c_speech_features.c:38
38	          dct2f[didx] = cos(M_PI * j * (2 * k + 1) / (double)(2 * aNFilters));

**Comment by lissyx** [comment]
Wait, you are using DeepSpeech 2 ? That's not even yet merged and still under lots of work.

**Comment by prashantmaheshwari94** [comment]
yesss, I am using Deepspeech2 branch (ds2-v2)

**Comment by lissyx** [comment]
I would suggest to join on IRC if you are debugging ds2, the current issue is about running ds1.

**Comment by lissyx** [comment]
@elpimous No need for the `strace` now that you are not running that as root :)

Can you please:
```
LD_LIBRARY_PATH=/home/nvidia/tensorflow/bazel-bin/tensorflow:/home/nvidia/tensorflow/bazel-bin/native_client:$LD_LIBRARY_PATH ./deepspeech /home/nvidia/DeepSpeech/data/ldc93s1/checkpoint/graph.pb /home/nvidia/DeepSpeech/data/ldc93s1/LDC93S1.wav -t
```

And paste the complete output ?

**Comment by elpimous** [comment]
@lissyx 
here is the result : 
`cpu_time_overall=0.00840 cpu_time_mfcc=0.00840 cpu_time_infer=0.00001`

I totally reinstalled native_client:

cd DeepSpeech/native_client/
`    sudo python setup.py install`
cd tensorflow/
```
    ln -s ../DeepSpeech/native_client ./
    sudo bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*
```
cd ../DeepSpeech/native_client
```
    make deepspeech
    PREFIX=/usr/local/bin sudo make install
```

**make bindings**
```
nvidia@tegra-ubuntu:~/DeepSpeech/native_client$ sudo make bindings
python ./setup.py bdist_wheel
running bdist_wheel
running build
running build_ext
running build_py
installing to build/bdist.linux-aarch64/wheel
running install
running install_lib
creating build/bdist.linux-aarch64/wheel
copying build/lib.linux-aarch64-2.7/_model.so -> build/bdist.linux-aarch64/wheel
copying build/lib.linux-aarch64-2.7/_utils.so -> build/bdist.linux-aarch64/wheel
creating build/bdist.linux-aarch64/wheel/deepspeech
copying build/lib.linux-aarch64-2.7/deepspeech/utils.py -> build/bdist.linux-aarch64/wheel/deepspeech
copying build/lib.linux-aarch64-2.7/deepspeech/model.py -> build/bdist.linux-aarch64/wheel/deepspeech
copying build/lib.linux-aarch64-2.7/deepspeech/__init__.py -> build/bdist.linux-aarch64/wheel/deepspeech
running install_egg_info
running egg_info
writing requirements to deepspeech.egg-info/requires.txt
writing deepspeech.egg-info/PKG-INFO
writing top-level names to deepspeech.egg-info/top_level.txt
writing dependency_links to deepspeech.egg-info/dependency_links.txt
reading manifest file 'deepspeech.egg-info/SOURCES.txt'
writing manifest file 'deepspeech.egg-info/SOURCES.txt'
Copying deepspeech.egg-info to build/bdist.linux-aarch64/wheel/deepspeech-0.0.1-py2.7.egg-info
running install_scripts
creating build/bdist.linux-aarch64/wheel/deepspeech-0.0.1.dist-info/WHEEL
```
sudo pip install deepspeech-0.0.1-py2.7-linux-aarch64.egg
```
nvidia@tegra-ubuntu:~/DeepSpeech/native_client/dist$ sudo pip install deepspeech-0.0.1-py2.7-linux-aarch64.egg
The directory '/home/nvidia/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nvidia/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting deepspeech-0.0.1-py2.7-linux-aarch64.egg
  Could not find a version that satisfies the requirement deepspeech-0.0.1-py2.7-linux-aarch64.egg (from versions: )
No matching distribution found for deepspeech-0.0.1-py2.7-linux-aarch64.egg
    
```

**Comment by lissyx** [comment]
You should never ever call make or bazel under sudo :(. Besides, 0.00001 inference time is consistent with discrepency I had between the training tensorflow version and the execution version. It might be a side effect of messing up with sudo :/. I'm sorry, but it is going to be very very complicated to debug that now, you might need to cleanup everything :)

Also, if you target ARM, you should rather do cross-compilation, but that's just a side-topic (we have ARMv6 support, and I have local branches for ARMv8).

**Comment by elpimous** [comment]
Well, hard for a quite newbie!! Ok
let's go for a full reinstall !
I'd like your ARMv8 local Branches.
Thanks

**Comment by lissyx** [comment]
It's a set of patches on my desktop computer, I have to find them and share :)

**Comment by elpimous** [comment]
I'll wait. thanks Lissyx (but I will continue until it work !!! lol)
waiting, I'll continue to create sentences and wav's....

**Comment by lissyx** [comment]
@elpimous here: https://gist.github.com/lissyx/c008b43fd808d132989ec4d238d664fb

You'll have to change DEEPSPEECH_ROOT to your deepspeech root, maybe create a Debian ARMv8 Sid tree under DEEPSPEECH_ROOT/multistrap-debian_arm64-sid/ using multistrap: https://gist.github.com/lissyx/f007de2fff24b5af219ce07d283ebe0f

It will involves some hacking, since you need to pre-populate the debian keyring files into the directories `multistrap-debian_arm64-sid/etc/apt/trusted.gpg.d/` and you will also have to do some magic using qemu-static for ARM64 otherwhise when you multistrap your system will be left half-configured and a lot of process will not be properly configured, and nothing will work :D

**Comment by prashantmaheshwari94** [comment]
Hi Lissyx, 
I checked out deepspeech2 did training and posted some bugs here earlier today regarding running it on a standalone wav file, when you suggested me to join IRC for Deepspeech2. 
I tried doing that but I don't think I was successful in doing that.

Can we connect off from this forum, where you can guide me to join IRC and other related things of Deepspeech-2.
Thanks 
And sorry for spamming it here :)

**Comment by lissyx** [comment]
Yes @prashantmaheshwari94, I removed our discussion to avoid adding noise to the current work ongoing on that issue. Please join irc.mozilla.org #machinelearning to discuss work regarding DeepSpeech v2 :)

**Comment by elpimous** [comment]
My
 Python works.
It was a wrong graph.pb file

**Comment by sekarpdkt** [comment]
@elpimous how did you convert .local/share/deepspeech/ldc93s1/graph.pbtxt ro binary? Am i suppose to use something like https://github.com/irfansharif/tensorflow/blob/master/converter.py

**Comment by roxima** [comment]
@sekarpdkt No need to go that far for another script, just pass `--export_dir` when doing training, by which you'll get it once training is done. You could test it with [ldc93s1](https://github.com/mozilla/DeepSpeech/blob/master/bin/run-ldc93s1.sh) for example.

**Comment by elpimous** [comment]
@roxima  Yes, @sekarpdkt  is right !!!
I did a too long time before anderstanding that !! (and it's written in readme.txt, Lol)
--export_dir /your dir/model_export_for_example/ \

inside, you'll have input_graph and output_graph

you want output graph for inference

(did you have success with your mic array Respeaker ?)

Vincent

**Comment by sekarpdkt** [comment]
Thanks. It helped
