### ISSUE TITLE
Allowing deep speech ai algorithm to recognize complex sound gestures others then speech

### ISSUE THREAD

**Issue by ghost** [mozilla/DeepSpeech#755]
**it would be interesting if we could allow:**
- _deep speech ai algorithm to recognize complex sound gestures other then speech_

**it would be particularly cool if that would be;**
- _implemented on easily wrapable languages for general purpose development_

**an interesting application for that would be for instance:**
- _recognizing complex gestures of a musical performance, specially if it involves some form of improvisation;_

**even cool then that would be:**
- _adding markov chain complex models, to analyze and predict complex sequences of gestures_

**another cool application of the technology, would be:**
- _allowing it to trace patterns in medical data (for instance for patterns heart frequency rate, or analyzing patterns in tumors throughout sound)._

**Comment by reuben** [comment]
While these are interesting experiments I don't think we have any plans to work on it in this repo. Probably a fork would be the best way to organize such an effort.
