### ISSUE TITLE
ValueError: File format '<HTM'... not understood.

### ISSUE THREAD

**Issue by supriyalk** [mozilla/DeepSpeech#763]
I am trying to run the example ./bin/run-ldc93s1.sh 
I get the  error each time: 
`Training model...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/slkapur/rnn_studies/DeepSpeech-1/util/importers/ldc93s1.py", line 82, in _populate_batch_queue
    source, source_len, target, target_len = self._compute_source_target()
  File "/home/slkapur/rnn_studies/DeepSpeech-1/util/importers/ldc93s1.py", line 72, in _compute_source_target
    audio_waves = audiofile_to_input_vector(wav_file, self._numcep, self._numcontext)
  File "/home/slkapur/rnn_studies/DeepSpeech-1/util/audio.py", line 14, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/slkapur/rnn_studies/TF_100_2/local/lib/python2.7/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/slkapur/rnn_studies/TF_100_2/local/lib/python2.7/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format '<HTM'... not understood.

`
I have installed all of the requirements and am using tensorflow 1.0

**Comment by lissyx** [comment]
Obviously, I guess `data/ldc93s1/LDC93S1.wav` is not a WAV file:
```
$ file data/ldc93s1/LDC93S1.wav 
data/ldc93s1/LDC93S1.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz
```

Please remove `data/ldc93s1/*`and re-run the code, it should re-import properly.

**Comment by supriyalk** [comment]
Even after running the command  rm data/ldc93s1/* I still get the same error. Perhaps there is a problem with the import script?

**Comment by reuben** [comment]
Can you share the entire contents of data/ldc93s1/LDC93S1.wav? It looks like your network can't reach the URL.

**Comment by supriyalk** [comment]
<HTML><HEAD>
<TITLE>Request Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Request Error (invalid_request)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your request could not be processed. Request could not be handled
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This could be caused by a misconfiguration, or possibly a malformed request.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

**Comment by supriyalk** [comment]
`<HTML><HEAD>
<TITLE>Request Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Request Error (invalid_request)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your request could not be processed. Request could not be handled
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This could be caused by a misconfiguration, or possibly a malformed request.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
`

**Comment by reuben** [comment]
Something is wrong with your network setup. https://catalog.ldc.upenn.edu/desc/addenda/LDC93S1.txt should contain the following text:

    0 46797 She had your dark suit in greasy wash water all year.

**Comment by supriyalk** [comment]
I think there is an issue with the link in the import file. The link is not reachable, and thus populating the data incorrectly.

**Comment by lissyx** [comment]
The URL in the import file is the same as the one reuben gave earlier. If you cannot download that properly, then either it's an issue on their server, or on your side, but here it works:
```
$ curl -Lv https://catalog.ldc.upenn.edu/desc/addenda/LDC93S1.txt 
*   Trying 128.91.252.214...
* TCP_NODELAY set
* Connected to catalog.ldc.upenn.edu (128.91.252.214) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server key exchange (12):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS change cipher, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / ECDHE-RSA-AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; postalCode=19104; ST=PA; L=Philadelphia; street=3600 Market Street; O=University of Pennsylvania; OU=LDC; CN=catalog.ldc.upenn.edu
*  start date: Jan 12 00:00:00 2017 GMT
*  expire date: Jan 12 23:59:59 2020 GMT
*  subjectAltName: host "catalog.ldc.upenn.edu" matched cert's "catalog.ldc.upenn.edu"
*  issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*  SSL certificate verify ok.
> GET /desc/addenda/LDC93S1.txt HTTP/1.1
> Host: catalog.ldc.upenn.edu
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 10 Aug 2017 21:33:19 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 62
< Last-Modified: Tue, 30 Jun 2009 15:09:10 GMT
< Connection: keep-alive
< ETag: "4a4a2a96-3e"
< Expires: Thu, 31 Dec 2037 23:55:55 GMT
< Cache-Control: max-age=315360000
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Accept-Ranges: bytes
< 
0 46797 She had your dark suit in greasy wash water all year.
* Curl_http_done: called premature == 0
* Connection #0 to host catalog.ldc.upenn.edu left intact
```

**Comment by supriyalk** [comment]
the link  "https://catalog.ldc.upenn.edu/desc/addenda/" is not accessible to me. Using the link provided in the earlier comment, I am able to get the .txt file, but I cant get it via "https://catalog.ldc.upenn.edu/desc/addenda/", which is in the import file

**Comment by andi4191** [comment]
Thats the LDC93S1_BASE_URL which is appended with the LDC93S1_BASE and  followed by extension and makes the complete URL as shared by reuben above

```
LDC93S1_BASE = "LDC93S1"
     LDC93S1_BASE_URL = "https://catalog.ldc.upenn.edu/desc/addenda/"
     local_file = base.maybe_download(LDC93S1_BASE + ".wav", data_dir, LDC93S1_BASE_URL + LDC93S1_BASE + ".wav")
     trans_file = base.maybe_download(LDC93S1_BASE + ".txt", data_dir, LDC93S1_BASE_URL + LDC93S1_BASE + ".txt")
```

**Comment by lissyx** [comment]
I'm closing that issue, there is nothing wrong on our side.
