### ISSUE TITLE
Status of pretrained models

### ISSUE THREAD

**Issue by alanbekker** [mozilla/DeepSpeech#769]
Dear mozillas,

Could you please provide the status of the pretrained models which you plan to release #435 ?
What is the current WER you achived so far? I understand it's not below 10%...but how much far from the target is right now?

In addition could you please specify the topology of the respected model?

Thanks in advance!

**Comment by kdavis-mozilla** [comment]
We're currently working on a bug that prevented the longer run from restoring correctly from a checkpoint. If you want the gory details you can join #machinelearning on irc.mozilla.org

**Comment by alanbekker** [comment]
Can you please just answer my question above?

I'm from a different time zone than yours so each time I enter the channel
its empty

Thanks in advance!


Alan
