### ISSUE TITLE
2x GTX 1080ti crashing 

### ISSUE THREAD

**Issue by varunravi** [mozilla/DeepSpeech#771]
```
E OOM when allocating tensor with shape[19776,2048]
E 	 [[Node: tower_0/gradients/tower_0/MatMul_4_grad/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=true, _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/gradients/tower_0/Add_4_grad/tuple/control_dependency, h6/read)]]
E 	 [[Node: tower_0/gradients/tower_0/MatMul_grad/tuple/control_dependency_1/_1351 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3549_tower_0/gradients/tower_0/MatMul_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


```
Hey,

Currently testing out the Librispeech dataset on my 2x GTX 1080ti PC. It's currently crashing at a batch size of 48 but I'm expecting it to handle this large of a batch size.

Could someone shed some light on what is going wrong or if my exceptions are too high?

best
Varun

**Comment by reuben** [comment]
Your expectations are probably too high. Do a binary search on the batch size to find the maximum working value. You can flip `ascending` to False in util/feeding.py to speed up this process. (Remember to flip it back to do the real training).

**Comment by varunravi** [comment]
Something seems wrong...maybe it's my hardware. I tried that out and now I'm crashing with 12 batch size 20x8192 seems awfully small for two of these GPUs

**E ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[20,8192]**
E 	 [[Node: tower_0/bidirectional_rnn/fw/fw/while/fw/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/bidirectional_rnn/fw/fw/while/fw/basic_lstm_cell/basic_lstm_cell/concat, tower_0/bidirectional_rnn/fw/fw/while/fw/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
E 	 [[Node: tower_0/gradients/tower_0/bidirectional_rnn/bw/bw/while/bw/basic_lstm_cell/basic_lstm_cell/MatMul/Enter_grad/b_acc_3/_695 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3449_tower_0/gradients/tower_0/bidirectional_rnn/bw/bw/while/bw/basic_lstm_cell/basic_lstm_cell/MatMul/Enter_grad/b_acc_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by CR1AT0RS** [comment]
@varunravi I am getting same error. Did you find a fix ?

**Comment by kdavis-mozilla** [comment]
For librispeech with Titan X Pascal's, basically the same as the 1080ti 's, we use batch size 12. So 20 is too large.
