### ISSUE TITLE
import_swb.py

### ISSUE THREAD

**Issue by supriyalk** [mozilla/DeepSpeech#773]
The import_swb.py file creates empty directories. How can I correctly import the swb dataset?

After running import_swb.py with out error, I run run-swb.py and get the following error: 

Exception in thread Thread-47:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/slkapur/rnn_studies/DeepSpeech/util/feeding.py", line 142, in _populate_batch_queue
    index = self._data_set.next_index(index) % file_count
ZeroDivisionError: integer division or modulo by zero

**Comment by kdavis-mozilla** [comment]
Could you provide info on the directories/files `import_swb.py` created? Thanks.

**Comment by supriyalk** [comment]
The file creates directories swb1_d1-wav, swb1_d2-wav, swb1_d3-wav, swb1_d4-wav, swb1_d1-split-wav, swb1_d2-split-wav, swb1_d3-split-wav, and swb1_d4-split-wav. When these files are created, they reference "original" directories from the LDC97S62 data set, but the names and structure do not match the downloaded data set, which can be downloaded from here: https://catalog.ldc.upenn.edu/ldc97s62

**Comment by supriyalk** [comment]
Another follow up question: I am trying to recreate the results seen in the DeepSpeech paper, so I want to download the fisher and switchboard data sets. How do run them together, as the paper shows results for the fisher and switchboard model run on the full 2300 hours of data?

**Comment by reuben** [comment]
You can simply pass the CSV files from both datasets in the --train_files, --dev_files, --test_files flags.

**Comment by kdavis-mozilla** [comment]
@supriyalk With regards to the original problem. I'm trying an import now. I'll let you know how it progresses. Unfortunately we haven't used `import_swb.py` recently. So it may suffer from bitrot.

**Comment by kdavis-mozilla** [comment]
I made some minor changes to make `import_swb.py` work on my side in branch issue773. Could you test them out on your side?

**Comment by supriyalk** [comment]
Yes I will give it a try! Just to clarify, you are downloading the data from  swb1_dialogact_annot.tar.gz, un-taring it, and storing it in the LDC97s62 folder?

**Comment by kdavis-mozilla** [comment]
I've downloaded the data long ago directly from LDC

**Comment by supriyalk** [comment]
I think the problem may be that they rearranged the structure of the folders then, if you look at the contents of swb1_dialogact_annot.tar.gz, downlaoded from  https://catalog.ldc.upenn.edu/ldc97s62, the structure  and names of files do not match the way that import_swb.py references them.

**Comment by kdavis-mozilla** [comment]
Ugh!

**Comment by supriyalk** [comment]
Do you think an updated import_swb.py will come out anytime soon?

**Comment by kdavis-mozilla** [comment]
The thing I'm trying to understand is when the format of the data set changed.

We purchased the data set on 2016-04-14 which is _after_ the final update of the data set noted here[[1](https://catalog.ldc.upenn.edu/LDC97S62)]. So the current data set and our data set should be the same. Which has me confused.
