### ISSUE TITLE
Building native client for model inference

### ISSUE THREAD

**Issue by SebastianScherer88** [mozilla/DeepSpeech#780]
hi all,
this might be an obvious question but im struggling to get bazel to help me use a trained and exported model for inference. The "preparation" section of the "DeepSpeech native client" of the main README says:

"""Create a symbolic link in the TensorFlow checkout to the deepspeech native_client directory.

cd tensorflow
ln -s ../DeepSpeech/native_client ./ """

In which directory do i have to be when entering that into the console? Whether I change into the repo's ".../local_tf/tensorflow" or my main "/usr/local/lib/python2.7/dist-packages/tensorflow", the result once i run the lines

""" bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:* """ is the same:

"""ERROR: no such package 'tensorflow': BUILD file not found on package path
INFO: Elapsed time: 0.232s
FAILED: Build did NOT complete successfully (0 packages loaded)
 """
Tensorflow itself is installed and I used it to train models, so no issues on that side. Could you help me spot my mistake, or maybe give more details for the DeepSpeech native client and bazel usage to set this up?

Thanks!

**Comment by lissyx** [comment]
Hi @SebastianScherer88, you need to do the symlink from within the tensorflow repo clone, assuming that `../DeepSpeech/` is your relative path to your DeepSpeech repo clone.

If you just want to play with inference, you should be able to just use our binaries. For example, for linux/amd64 CPU only build, download the `native_client.tar.xz` from https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu at https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/native_client.tar.xz

**Comment by SebastianScherer88** [comment]
ah, i see, my bad! i didnt install tensorflow from source but instead tried to use the version that was installed via pip (and that i used to train the model). I'll install from source and retry the native client stuff. thanks

**Comment by lissyx** [comment]
Feel free to re-open if needed :)

**Comment by SebastianScherer88** [comment]
Hi lissyx, building tensorflow from source doesnt seem to work out for me, so I have downloaded the native_client.tar.xz you posted. How do I use it now to apply the model? I have the model graph etc, do I still need to go through all the steps in the native client README (as seen on this github)?

**Comment by lissyx** [comment]
Just 
```
LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH ./deepspeech path/to/model.pb path/to/sample.wav 
```

**Comment by SebastianScherer88** [comment]
hi lissyx, i did it and the inference seems to work now, thanks a lot! one more question though: can i pass this native_client multiple audio files at once, or do i have to call it one audio file at a time?

**Comment by lissyx** [comment]
That's a demo tool, it only takes one wav file. The tar bundles the needed libs for both python and node bindings, so you can also hack using them (URL of the bindings can be found on the previous link I gave, node 4 to 6 included should be good. When using them you also need the LD_LIBRARY_PATH definition for now :-)
