### ISSUE TITLE
Online/Incremental API feature request

### ISSUE THREAD

**Issue by oplatek** [mozilla/DeepSpeech#786]
An incremental interface is necessary for use in real-time application e.g. in dialogue systems.

Instead of batch API on needs something like

```
ds = Model(*params)
for audio_chunk in audio_generator():
      ds.accept_audio(audio_chunk)
      interim_hyp = ds.infer()
final_hyp = ds.infer()
ds.reset()
```
PS: Let me know if you consider it at all. If yes, I will gladly explain more details about the use cases.

**Comment by reuben** [comment]
Our use of a bidirectional RNN layer on the acoustic model means that the network needs to have the entire audio sample to do inference. We're experimenting with alternative architectures, but for now, we can't provide this API.
