### ISSUE TITLE
Browser add-on that has basic control of browser

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#79]

**Comment by lissyx** [comment]
Made some progress:
 - bootstrap addon
 - able to constantly listen on the mic (with no user interaction, I guess a on/off button in the toolbar would be better)
 - looks at FFT to detect spikes in sound
 - records when sound is detected, until some silence for ~2 secs
 - write to disk as ogg/opus file (this is what firefox produces)

Next steps:
 - python websocket server that waits for the addon to send some sound
 - converts to the same kind of audio file as the ones we trained the network against (WAV/PCM ?)
 - passes over to Tensorflow Serving
 - passes back decoded string to the addon, over websocket
 - addon interprets what server could decode

**Comment by lissyx** [comment]
Made some progress:
 - bootstrap addon
 - able to constantly listen on the mic (with no user interaction, I guess a on/off button in the toolbar would be better)
 - looks at FFT to detect spikes in sound
 - records when sound is detected, until some silence for ~2 secs
 - write to disk as ogg/opus file (this is what firefox produces)
 - python websocket server that waits for the addon to send some sound
 - converts to the same kind of audio file as the ones we trained the network against, WAV/PCM
 - passes over to Tensorflow Serving
 - passes back decoded string to the addon, over websocket
 - addon interprets what server could decode
 - open website in a new tab command working

Next steps:
 - run this with really trained model
 - add more commands:
  - switch to an open tab
  - scroll up/down
  - zoom in/out
