### ISSUE TITLE
VoxForge importer depends on BeautifulSoup 3 which doesn't work with Python 3

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#793]
It should be updated to use bs4, which is compatible with both, and is already a requirement.

**Comment by CR1AT0RS** [comment]
Voxforge importer works fine for me. I am using python 3.6.2 works fine for me. I was able to import all the files and decompress too into .wav and .txt files. 

-Correct me if I am wrong.

**Comment by reuben** [comment]
This was fixed in #800, but I forgot to close the issue.

**Comment by reuben** [comment]
I'll gladly take a PR for a run-voxforge script :)
