### ISSUE TITLE
native_client

### ISSUE THREAD

**Issue by prabhat003** [mozilla/DeepSpeech#798]
I have downloaded the native_client.tar.xz and  compatible .whl file from task cluster. Now as mentioned in the installation steps we need to install the libraries in native_client.tar.xz.
I extracted the tar file and executed the './deepspeech' command from the root folder. The output that i get is as below.

Usage: deepspeech MODEL_PATH AUDIO_PATH [-t]
  MODEL_PATH	Path to the model (protocol buffer binary file)
  AUDIO_PATH	Path to the audio file to run (any file format supported by libsox)
  -t		Run in benchmark mode, output mfcc & inference time

Is it the right way to install the native client libraries. It shows the usage with model and audio file. M confused. Please help!!!!!!!

**Comment by lissyx** [comment]
Hello @prabhat003, it is the right way: you need to give the `deepspeech` binary a model and an audio file to perform inference :-).
