### ISSUE TITLE
error loading package ''

### ISSUE THREAD

**Issue by mcelhennyi** [mozilla/DeepSpeech#822]
I am trying to build the tensorflow bazel package using a net i trained off of the voxforge database. I am behind a proxy, have set both the HTTP_PROXY and the http_proxy (and the s versions) variables (including auth) for my system. However I get this error:

![image](https://user-images.githubusercontent.com/14264857/30182142-6b5f74ae-93db-11e7-80af-d755b51ae68f.png)

adc-lab@adc-lab-desktop:~/workspace/tensorflow$ bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*
WARNING: ignoring http_proxy in environment.
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [http://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz, https://github.com/bazelbuild/rules_closure/archive/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz] to /home/adc-lab/.cache/bazel/_bazel_adc-lab/4534105d4045448773f96d944be86b59/external/io_bazel_rules_closure/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz: All mirrors are down: [java.lang.NullPointerException]
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [http://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz, https://github.com/bazelbuild/rules_closure/archive/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz] to /home/adc-lab/.cache/bazel/_bazel_adc-lab/4534105d4045448773f96d944be86b59/external/io_bazel_rules_closure/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz: All mirrors are down: [java.lang.NullPointerException]
INFO: Elapsed time: 2.155s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by lissyx** [comment]
Hello @mcelhennyi. Why do you have to build the packages, we have binaries available: https://github.taskcluster.net/v1/repository/mozilla/DeepSpeech/master/latest

Besides, if it's a bazel related issue, we cannot help you.

**Comment by mcelhennyi** [comment]
@lissyx 
When I try to use the binary i get this error: 
![image](https://user-images.githubusercontent.com/14264857/30213270-f76185a4-946d-11e7-899a-1c4e027ddc68.png)

Running in an Ubuntu 16.04 VM on an intel xeon processor

**Comment by lissyx** [comment]
@mcelhennyi we do build tensorflow with AVX2, so I cannot really see why you get that, and on our systems, with AVX2 available, it works.
