### ISSUE TITLE
Different results using native_client .

### ISSUE THREAD

**Issue by ionsurdu** [mozilla/DeepSpeech#832]
Hi guys, 

I am triing to run some tests for Romanian language.  
So far I started from "run-ldc93s1.sh" example, providing similar ( format ) input data. 
I have prepared about 20 wav with about 3-6 seconds each, also 
updated ./data/spell/words.txt file with similar content (in Romanian). 

After train , I got some results which are not really bad taking in consideration reduced input. 

>
(env) iosu@LPT0968:/mnt/d/DeepSpeech/DeepSpeech$ ./bin/run-ebook.sh
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ebook/ebook.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ebook"))
+ checkpoint_dir=/home/iosu/.local/share/deepspeech/ebook
+ python -u DeepSpeech.py --train_files data/ebook/ebook.csv --dev_files data/ebook/ebook.csv --test_files data/ebook/ebook.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/iosu/.local/share/deepspeech/ebook --export_dir out/ebook_model
W Parameter --validation_step needs to be >0 for early stopping to work
I STARTING Optimization
I Training of Epoch 0 - loss: 218.102144
I Training of Epoch 1 - loss: 213.555966
I Training of Epoch 2 - loss: 220.170152
I Training of Epoch 3 - loss: 189.608788
I Training of Epoch 4 - loss: 178.988115
I Training of Epoch 5 - loss: 170.516114
I Training of Epoch 6 - loss: 166.826372
I Training of Epoch 7 - loss: 165.180416
I Training of Epoch 8 - loss: 182.506078
I Training of Epoch 9 - loss: 169.536512
I Training of Epoch 10 - loss: 176.776394
I Training of Epoch 11 - loss: 161.854043
I Training of Epoch 12 - loss: 156.774208
I Training of Epoch 13 - loss: 153.913694
I Training of Epoch 14 - loss: 149.406402
I Training of Epoch 15 - loss: 145.174464
I Training of Epoch 16 - loss: 137.392881
I Training of Epoch 17 - loss: 130.173787
I Training of Epoch 18 - loss: 123.807348
I Training of Epoch 19 - loss: 119.140656
I Training of Epoch 20 - loss: 107.645366
I Training of Epoch 21 - loss: 98.097982
I Training of Epoch 22 - loss: 91.555851
I Training of Epoch 23 - loss: 95.074957
I Training of Epoch 24 - loss: 85.332717
I Training of Epoch 25 - loss: 81.856475
I Training of Epoch 26 - loss: 87.617549
I Training of Epoch 27 - loss: 70.009808
I Training of Epoch 28 - loss: 56.499496
I Training of Epoch 29 - loss: 50.325785
I Training of Epoch 30 - loss: 46.749018
I Training of Epoch 31 - loss: 45.806911
I Training of Epoch 32 - loss: 48.846286
I Training of Epoch 33 - loss: 39.284415
I Training of Epoch 34 - loss: 30.009140
I Training of Epoch 35 - loss: 23.469799
I Training of Epoch 36 - loss: 24.376562
I Training of Epoch 37 - loss: 13.789710
I Training of Epoch 38 - loss: 8.067623
I Training of Epoch 39 - loss: 4.637545
I Training of Epoch 40 - loss: 3.210315
I Training of Epoch 41 - loss: 1.756652
I Training of Epoch 42 - loss: 1.223044
I Training of Epoch 43 - loss: 0.949996
I Training of Epoch 44 - loss: 0.901400
I Training of Epoch 45 - loss: 1.035198
I Training of Epoch 46 - loss: 0.968719
I Training of Epoch 47 - loss: 1.210128
I Training of Epoch 48 - loss: 0.471799
I Training of Epoch 49 - loss: 0.577918
I FINISHED Optimization - training time: 1:29:04
I Test of Epoch 50 - WER: 0.096157, loss: 0.266266524988, mean edit distance: 0.000957
I --------------------------------------------------------------------------------
I WER: 0.200000, loss: 0.258107, mean edit distance: 0.000000
I  - src: "nu-i deloc placut sa vezi un om corpolent slabind brusc"
I  - res: "nu i deloc placut sa vezi un om corpolent slabind brusc"
I --------------------------------------------------------------------------------
I WER: 0.250000, loss: 0.104180, mean edit distance: 0.000000
I  - src: "doua luni si jumatate nu ne-am mai vazut"
I  - res: "doua luni si jumatate nu ne am mai vazut"
I --------------------------------------------------------------------------------
I WER: 0.250000, loss: 0.136861, mean edit distance: 0.000000
I  - src: "doua luni si jumatate nu ne-am mai vazut"
I  - res: "doua luni si jumatate nu ne am mai vazut"
I --------------------------------------------------------------------------------
I WER: 0.285714, loss: 0.121975, mean edit distance: 0.000000
I  - src: "mincind putin si alungindu-si din preajma servitorii"
I  - res: "mincind putin si alungindu si din preajma servitorii"
I --------------------------------------------------------------------------------
I WER: 0.285714, loss: 0.123145, mean edit distance: 0.000000
I  - src: "intelesesem ca de-acum inainte raminea zavorit acolo"
I  - res: "intelesesem ca de acum inainte raminea zavorit acolo"
I --------------------------------------------------------------------------------
I WER: 0.555556, loss: 1.099776, mean edit distance: 0.018182
I  - src: "m-a azvirlit afara din laborator intr-un acces de furie"
I  - res: "m a azvirlit afara din adorator intr un acces de furie"
I --------------------------------------------------------------------------------
I Exporting the model...
I Restored checkpoint at training epoch 951
WARNING:tensorflow:From DeepSpeech.py:1655: generic_signature (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
Please use SavedModel instead.
WARNING:tensorflow:From DeepSpeech.py:1657: generic_signature (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
Please use SavedModel instead.
WARNING:tensorflow:From DeepSpeech.py:1657: init (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
Please use SavedModel instead.
WARNING:tensorflow:From DeepSpeech.py:1665: export (from tensorflow.contrib.session_bundle.exporter) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
Please use SavedModel instead.
Converted 14 variables to const ops.
326 ops in the final graph.
I Models exported at out/ebook_model
>

When I try to reuse saved model with native client (python code) I get very 
different results ,( with a sample sentence  from train process ).
It shall be :  dupa saptamini intregi de exil
>
(env) iosu@LPT0968:/mnt/d/DeepSpeech/DeepSpeech$ sh sample_ebook.sh "out/ebook_model"
diuoa satamumrinteris de vir
>

So my question here: 
Why using native client I get very different results than in train process ? 
For a better result (in other than English language ) shall I rebuild also the
Language Model file (lm.binary) or updating words.txt file is enough ? 

Thanks in advance. 
Ion

**Comment by elpimous** [comment]
Reuben told me that  actually, native client doesn't use ctc-decoder optimizations,
so if you trained your model with ctc, it's normal

**Comment by reuben** [comment]
You do need to rebuild the Language Model binary file if you're training with a different language. The native clients don't leverage the decoder with integrated LM yet, but you should still get reasonable results, even if not as good as the ones from the test epoch.

**Comment by elpimous** [comment]
Reuben, on the fly, I could evaluate the wer to 10-15% more; comparing end training test wer's to client.py ones.
Recurrent errors are : attached words, and some start/end missing lettres in words

**Comment by reuben** [comment]
This should be fixed now that #856 has landed.
