### ISSUE TITLE
Not able to generate new trie files

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#833]
I am able to use the libctc_decoder_with_kenlm.so  but I am not able to generate a new trie

the default syntax is 
./native_client/generate_trie <alphabet> <lm_model> <vocabulary> <trie_path>

But I do not understand why I have to give the old trie path when I am generating a new trie. If I give the trie path as any new folder path, it says out unable to open the output file.

**Comment by kdavis-mozilla** [comment]
The syntax is actually
```bash
./native_client/generate_trie <alphabet> <lm_model> <vocabulary> <trie_path>
```
See [generate_trie.cpp#59](https://github.com/mozilla/DeepSpeech/blob/master/native_client/generate_trie.cpp#L59)

Also, you don't have to give an old trie path. The path you give is the path of the new trie you're generating.

**Comment by pdcoded** [comment]
I have generated .so file in a folder named destination using 
python util/tc.py destination cpu
Now I used the same syntax as above with my lm and txt file

/DeepSpeech$ 
./destination/generate_trie ./data/lm/alphabet.
txt ./data/lm/lm_decoder1.lm ./data/lm/lm_decoder1.txt ./data

unable to open output file ./data

If I change the ./data ./data/lm/trie (path to old trie) ,it doesnt throw any error but doesnt create a new trie either

**Comment by kdavis-mozilla** [comment]
In using ./data you're trying to write a trie to an existing directory.

Try using a path for the new trie that is not an existing directory and not an existing file.

**Comment by elpimous** [comment]
Finish with ./data/trie

**Comment by pdcoded** [comment]
thanks working

**Comment by phanlong95** [comment]
bash: ./generate_trie: cannot execute binary file: Exec format error
````````````````````````````````````
anyone help me
