### ISSUE TITLE
Problem using native client library + python bindings

### ISSUE THREAD

**Issue by dsouza95** [mozilla/DeepSpeech#836]
Hello,

I have just updated my branch in order to get the new improvements that came with #805. Prior to #805, I never used the native client, and I am somehow struggling to use it. I tried using the pre-compiled libraries provided, but I face the problem seen in image 1. Other than that, I tried compiling the libraries from the tensorflow sources, and not using conda environments, but got the same results. 
I am using Anaconda for Python 2.7. Tried compiling with both g++-4.8 and g++-5.0. I copied all .so files inside native_client while keeping the permissions to /usr/lib, a path defined in LD_LIBRARY_PATH.
I feel this is somehow related to where the deepspeech pip package is installed, but I am not really sure. Any ideas?
Thank you in advance :)

Daniel

Image 1:
![image](https://user-images.githubusercontent.com/5633988/30552118-4c7513d2-9c73-11e7-884f-39bdb3c6ce3f.png)

**Comment by lissyx** [comment]
@dsouza95 We need more context, you don't give us the `LD_LIBRARY_PATH` value that you are defining, nor where `libtensorflow_cc.so` lives.  Also, you should not be using `run-tc-ldc93s1.sh`, that's only for TaskCluster.

**Comment by lissyx** [comment]
Under the proper `LD_LIBRARY_PATH` context, we would also need the output of `ldd /usr/lib/libctc_decoder_with_kenlm.so`. Also, it would help a lot @dsouza95 if you could copy/paste properly formatted text rather than images :)

**Comment by dsouza95** [comment]
Hello,
Thanks for the quick reply! I'm sorry I won't be able to show some logs of my situation from yesterday. My Mint just decided it wouldn't boot anymore, to which I decided to make a clean install. As it turns out, everything works like a charm now :) I probably messed up somewhere along the setup or afterwards. 

Keep up the good work!
Daniel
