### ISSUE TITLE
How many audio frames are created from one second of audio?

### ISSUE THREAD

**Issue by SebastianScherer88** [mozilla/DeepSpeech#839]
I have a question regarding the conversion of audio to array that is related to the"'tensorflow's ctc cant handle audios that have fewer frames than the target annotation has characters" issue: What is the conversion rate between seconds and audio frames, i.e. how many audio frames do i get out of, say, 1 second of audio; in other words, how finely are the audio chopped up when converted into arrays? Im asking because due to some audio-annotation mismatches in my DIY importer, i seem to get short audios with long (incorrect) annotations. tensorflow says something like: "length of audio (100) is shorter than length of annotation (143)."

now i know that all my audios are at least 2 seconds long (this i have verified). If i knew how many frames (-> "length of audio" from tensorflow's point of view) each second of audio produces, i could catch those audios during preprocessing with simple if "n_character > r_conv * n_secs = n_frames" for each audio segment. is there a fixed conversion rate r_conv? i have looked in the code but i havent been able to find that rate if it is there.

many thanks in advance,

seb

**Comment by kdavis-mozilla** [comment]
As far as I remember, someone correct me if I'm wrong. We chop the audio into 25ms windows every 10ms. So, we have a 25ms window at 0ms, 10ms, 20ms.... We then do a stride of 2 which means that we throw away half of that data leaving us with a window at 0ms, 20ms, 40ms.... So for 1 second you get 50 windows.

**Comment by SebastianScherer88** [comment]
ha thanks! then i guess the '100' from my problem is 2 seconds * 50 frames/second = 100 frames. i'll test it and report back!

cheers!

**Comment by SebastianScherer88** [comment]
yeah, that works now! thanks for the quick reply!

**Comment by kdavis-mozilla** [comment]
You're welcome!
