### ISSUE TITLE
Illegal instruction (core dumped) at the end of training process

### ISSUE THREAD

**Issue by yscope75** [mozilla/DeepSpeech#843]
I got an  "Illegal instruction (core dumped)" error when it was finishing the training process.
I'm testing out the ldc93s1 script on NVIDIA P6000 PC

Could someone help me to figure out what is going wrong ?

Thanks, 
Thieny

**Comment by lissyx** [comment]
Can you provide more informations on your system ? That error feels more related to the CPU than the GPU.

**Comment by yscope75** [comment]
thanks for your respond @lissyx!
My pc is running Ubuntu 16.04. with intel Xeon E5-2630 v2.
I installed Tensorflow using pip command
This error occurs either I run on CPU or GPU. I found on google that Numpy package may be involved and tried reinstalling it, but the error is still there. 
Thanks

**Comment by lissyx** [comment]
@yscope75 Which pip package did you used ? Upstream tensorflow ? Which version ?

**Comment by lissyx** [comment]
@yscope75 I'd also be interested in the output of `/proc/cpuinfo`, Intel's website only refers to `AVX`, while for my laptop's CPU it properly refers to `AVX 2.0` and `SSE 4.2` ; that might explain your issue. At least, it would be consistent.

**Comment by yscope75** [comment]
@lissyx  here is my output of /proc/cpuinfo:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
stepping	: 4
microcode	: 0x428
cpu MHz		: 2490.344
cache size	: 15360 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 5200.13
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

and i'm using tensorflow 1.3.0

**Comment by lissyx** [comment]
@yscope75 Upstream tensorflow? You should check anyway if it was built with AVX2 support, I'm pretty sure this is what you hit. If you are using the tensorflow packages we have on TaskCluster, they are built with AVX2 use enabled, so it's likely not to work on your CPU.

**Comment by yscope75** [comment]
it's Upstream tensorflow @lissyx. I will check it again. It also works well on my laptop. 
thank you

**Comment by yscope75** [comment]
@lissyx  I'm rebuilding native_client with my tensorflow but I got this error: 
"name 'if_linux_x86_64' is not defined " 
what am I doing wrong?

**Comment by lissyx** [comment]
@yscope75 That's a change that landed while 1.3 cycle, I don't know what version of the tensorflow tree you are using. I would recommend using something close to what we test on ; worst case, change `if_linux_x86_64` to `if_x86` in `native_client/BUILD`. The upstream git head we are relying on currently is 16d39e94e3724417fcaed87035434e098e892842

**Comment by yscope75** [comment]
@lissyx  I changed Build file as you said above and already rebuilt. Everything work looks good.
Thank you so much for your help!

**Comment by mohjaba** [comment]
Hi, I have the same problem. I tried installing on both laptop (CPU only) and  desktop (GPU -Quadro k620), but same problem.
@yscope75 can you please clarify how you rebuild the tensorflow with native_client?

**Comment by yscope75** [comment]
@mohjaba 
- First, You should check your CPU info by command /proc/cpuinfo. Then build your tensorflow from source with option follow the libraries that your CPU support. 
- After you built tensorflow, follow the instruction on the Deepspeech website to build native_client.

**Comment by lissyx** [comment]
This is not an issue on DeepSpeech itself, let's close that.

**Comment by guruvasuraj** [comment]
When I try to run the pre-trained model, I am getting the below error.  Could anyone help me fix this?

I used python bindings and  command-line client both are returning the same error.

wiz@gpu2h:~/Speech_recognition/deepspeech/DeepSpeech$ ./deepspeech models/output_graph.pb models/alphabet.txt models/lm.binary models/trie audio_input.wav
Illegal instruction (core dumped)

**Comment by kdavis-mozilla** [comment]
@guruvasuraj It looks like you are using the wrong command line argument ordering.

To find the ordering of the command line arguments try
```bash
deepspeech -h
```
