### ISSUE TITLE
Segmantation fault

### ISSUE THREAD

**Issue by eduvenson** [mozilla/DeepSpeech#846]
Hello, 
I have recently updated my code to take advantage of the new improvements **(specially the ctc decoder with KenLM).** It worked great for the ldc93s1 dataset, but it gives me a segmentation fault on **my data.** The segfault happens only when the **report_params** is passed to the session. I tried using gdb, but the core was not dumped, so it didn't really show me anything. I believe the reason this is happening is that my data contains **latin characters (á,à,ã, ...),** but again, this is only a guess. The data is properly encoded to utf-8, and it worked on the previous implementation (with spell.py), with some tweaks. Is there any special setup I should have done? Any ideas? 
Thanks in advance :)

José

**Comment by kdavis-mozilla** [comment]
Did you update [alphabet.txt](https://github.com/mozilla/DeepSpeech/blob/master/data/alphabet.txt), [lm.binary](https://github.com/mozilla/DeepSpeech/blob/master/data/lm/lm.binary) and the [trie](https://github.com/mozilla/DeepSpeech/blob/master/data/lm/trie)?

**Comment by elpimous** [comment]
Hi eduvenson,
I has same error as you previously, I solved it with the newest master version.
hope to help

**Comment by eduvenson** [comment]
Thanks @kdavis-mozilla and @elpimous, the problem was on trie file.
