### ISSUE TITLE
problem with native client

### ISSUE THREAD

**Issue by sruteesh** [mozilla/DeepSpeech#848]
Hello,
I have followed the instructions as given in [native_client README](https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md) 
Tensorflow build was successful but while trying to make deepspeech. I throws
```
g++ -o deepspeech `pkg-config --cflags sox` -L../../tensorflow/bazel-bin/tensorflow -L../../tensorflow/bazel-bin/native_client  client.cc `pkg-config --libs sox` -ldeepspeech -ldeepspeech_utils -ltensorflow_cc 
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsAtLeast(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Env::Default()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShapeRep::DestructorOutOfLine()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::ConfigProto::~ConfigProto()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dim_size(int) const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::SlowCopyFrom(tensorflow::Status::State const*)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::CheckIsAlignedAndSingleElement() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShapeRep::SlowCopyFrom(tensorflow::TensorShapeRep const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(tensorflow::gtl::ArraySlice<long long>)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::Tensor(tensorflow::DataType, tensorflow::TensorShape const&)'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::Tensor::~Tensor()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::GraphDef::~GraphDef()'
../../tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
collect2: error: ld returned 1 exit status
Makefile:47: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1
```

my LB_LIBRARY_PATH has `libtensorflow_cc.so` 
I tried
`ls -l ../../tensorflow/bazel-bin/tensorflow/libtensorflow._cc.so`
output: `-r-xr-xr-x 1 root root 125829632 Sep 24 05:34 ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so`
`nm ../../tensorflow/bazel-bin/tensorflow/libtensorflow.so | grep CheckDimsAtLeast`
output: no symbols

The earlier issues say tensorflow compilation failed. But my build was successful. What am i missing?

**Comment by kdavis-mozilla** [comment]
Is `LB_LIBRARY_PATH` a typo? Did you mean `LD_LIBRARY_PATH`?

**Comment by sruteesh** [comment]
yeah I meant `LD_LIBRARY_PATH`

**Comment by kdavis-mozilla** [comment]
Is the typo in the issue or the in env variable you set on the command line?

**Comment by sruteesh** [comment]
It was a typo in the issue
my `LD_LIBRARY_PATH` has libtensorflow_cc.so

**Comment by sruteesh** [comment]
@kdavis-mozilla  any suggestions?

**Comment by lissyx** [comment]
Your nm call is against the wrong lib, please do:
```
nm ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so | grep CheckDimsAtLeast
```

**Comment by lissyx** [comment]
Also @sruteesh which version of tensorflow did you checked-out ? Why do you need to re-build yourself instead of using the binaries we provide ?

**Comment by sruteesh** [comment]
@lissyx I was following instructions from 
i tried building tensorflow and Deespeech libraries using 
`bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*`

The build was successful but when i tried to `make deespeech`
It gave the ablove undefined reference error
I checked the 
`nm ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so | grep CheckDimsAtLeast`
It says no symbols.

**Comment by lissyx** [comment]
@sruteesh Which version of tensorflow ? What does `file ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so` gives? And `ldd ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so` ?

**Comment by sruteesh** [comment]
**`file ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so` gives** 
`../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[md5/uuid]=3f3f40c66f4e936559343940f4229036, stripped`

**`ldd ../../tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so` gives**
`	linux-vdso.so.1 =>  (0x00007fff6673d000)
	libtensorflow_framework.so => /root/github_folders/DeepSpeech/native_client/../../tensorflow/bazel-bin/tensorflow/../_solib_local/_U_S_Stensorflow_Clibtensorflow_Ucc.so___Utensorflow/libtensorflow_framework.so (0x00007faf614b2000)
	libcublas.so.8.0 => /root/github_folders/DeepSpeech/native_client/../../tensorflow/bazel-bin/tensorflow/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcublas.so.8.0 (0x00007faf5e46d000)
	libcusolver.so.8.0 => /root/github_folders/DeepSpeech/native_client/../../tensorflow/bazel-bin/tensorflow/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccusolver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcusolver.so.8.0 (0x00007faf5aeff000)
	libcudart.so.8.0 => /root/github_folders/DeepSpeech/native_client/../../tensorflow/bazel-bin/tensorflow/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudart.so.8.0 (0x00007faf5ac99000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faf5a990000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faf5a78c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faf5a56f000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007faf5a34d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faf59fcb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faf59db5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faf599eb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faf69dec000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007faf58ba6000)
	libcudnn.so.6 => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6 (0x00007faf4f644000)
	libcufft.so.8.0 => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcufft.so.8.0 (0x00007faf467f5000)
	libcurand.so.8.0 => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcurand.so.8.0 (0x00007faf4287f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007faf42677000)
	libnvidia-fatbinaryloader.so.384.66 => /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.66 (0x00007faf42425000)
`

**Comment by lissyx** [comment]
@sruteesh 1.0.1 would be not good with the current code, please switch to master :)

**Comment by lissyx** [comment]
But if you just use CUDA on Linux/AMD64 you can directly rely on those binaries: https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.gpu/artifacts/public/native_client.tar.xz

**Comment by lissyx** [comment]
BTW as a side note @sruteesh you should avoid building (and working, in general) as root :/

**Comment by sruteesh** [comment]
just to clarify
I should just download https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.gpu/artifacts/public/native_client.tar.xz and extract into `./Deepspeech/native_client`
and run `python setup.py install`
??
Yeah, maybe running in root caused the earlier problems

**Comment by sruteesh** [comment]
But I'm getting `tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow16KernelDefBuilderD2Ev`
this error while running ./bin/run-ldc93s1.sh

**Comment by lissyx** [comment]
@sruteesh Can you expose clearly what you want to achieve ?

**Comment by sruteesh** [comment]
I'm trying to run sample ldc93s1.sh with the latetst update **libctc_decoder_with_kenlm.so**

**Comment by reuben** [comment]
You don't need to run `setup.py install` at all, just pass the appropriate path to the decoder library in the --decoder_library_path argument to DeepSpeech.py.

**Comment by reuben** [comment]
The undefined symbol error is probably because you're using an out of date TensorFlow version. Try upgrading to 1.3.0.

**Comment by sruteesh** [comment]
Ohh the README still says TF 1.0 or 1.1 in the prerequisites. Yeah will upgrade and try again.

**Comment by sruteesh** [comment]
Cool it works with TF 1.3.0.

**Comment by lissyx** [comment]
So it just confirms we need to fix all our docs, thanks :)
