### ISSUE TITLE
audio preprocessing / things to look out for

### ISSUE THREAD

**Issue by SebastianScherer88** [mozilla/DeepSpeech#851]
hi all,

im trying to train the deepspeech model using data that i created from audio recordings, matching transcriptions and forced alignment using python tools. I ended up with segments between 2 and 25 seconds each (all segment from the ted data base are between 2 and 20 seconds).

the data set i created this way is roughly twice as big as TEDLIUM, i.e. now i have 3 times as much data as with only TEDLIUM. The problem i now have: the model does not seem to converge any more, at least not as quickly and as well as it did using the TEDLIUM data only. I know that with bigger datasets the convergence tends to be slower in general, but the specific numbers make me think the change of size is not the issue here.

I'm using learning rate lr = 0.0002 (as opposed to the default rate 0.0001). other than my data being corrupted in some way (and random sample verification showed that it seems to be ok in terms of alignment etc.), is there anything else i have to look out for? is there any audio preprocessing i need to consider, like normalizing audio inputs, or is this handled by the model feeder/ audio_to_input etc.? in other words, any ideas where i could be going wrong?

thanks in advance,

seb

**Comment by kdavis-mozilla** [comment]
Could you describe what "the model does not seem to converge" means with examples from the run's log(s)?

**Comment by SebastianScherer88** [comment]
if you run the below script in python 2 like so (i had to add the txt ending to the visualizer script to upload it, other format weren't supported):

python visualize_training_logs deepspeech_training_1_output.txt deepspeech_training_10_output.txt

you should a picture of two training runs: left columns is a model trained on TEDLIUM, and evaluated on TEDLIUrM (i.e. seen data). right column is a model that was trained on the scraped data (roughly a third of the size of TEDLIUM) and evaluated on the same scraped data.

[deepspeech_training_1_output.txt](https://github.com/mozilla/DeepSpeech/files/1332210/deepspeech_training_1_output.txt)

[deepspeech_training_10_output.txt](https://github.com/mozilla/DeepSpeech/files/1332211/deepspeech_training_10_output.txt)

[visualize_training_logs.txt](https://github.com/mozilla/DeepSpeech/files/1332214/visualize_training_logs.txt)

**Comment by kdavis-mozilla** [comment]
Thanks for the great visualization! It's more than I'd expected to get!

As to the data, we "whiten" each clip before it's fed to the network[[1](https://github.com/mozilla/DeepSpeech/blob/master/util/audio.py#L46)]. So you shouldn't need to do any audio preprocessing like normalizing audio inputs.

To debug, I've a few questions:
- Why did you increase the learning rate from 0.0001 to 0.0002? If the learning rate it too, high the model will not converge.
- If you use your data alone with the learning rate 0.0002, does the model converge?
- If you use your data alone with the learning rate 0.0001, does the model converge?
- If you use your data + TED with the learning rate 0.0001, does the model converge?

**Comment by SebastianScherer88** [comment]
thanks for the response! to  answer your questions:
- i played around with higher learning rates to make learning as quick as possible (we're using amazon webservice, i.e. time is money). 
- i found that for 0.0002 it still converges on TED, but not on the data i scraped
- see above point
- i havent tried that yet

New development: i looked at your importer scripts and i see you're converting all the audios to have framerate = 16000, so i did that with my imported data and it seems to do the trick:

python visualize_training_logs.py deepspeech_training_1_output.txt deepspeech_training_10_output.txt deepspeech_training_14_output.txt training

first two columns as before, right column now with resampled scraped data to bring it to framerate = 16000. much better! the difference between the curves on the right and the left are, i think, due to the left column having run on learning rate 0.0002 and the right one on learning rate 0.0001, hence slower learning and a less steep descent. It looks like this solved the issue, but i will experiment further and post again once i can confirm. @kdavis-mozilla: can you confirm that you bring all your audio to a common framerate of 16000 frames/second? thats what i got from the importer scripts (fisher or librivox i think) anyway. Thanks!

[deepspeech_training_14_output.txt](https://github.com/mozilla/DeepSpeech/files/1336676/deepspeech_training_14_output.txt)

[deepspeech_training_10_output.txt](https://github.com/mozilla/DeepSpeech/files/1336674/deepspeech_training_10_output.txt)

[deepspeech_training_1_output.txt](https://github.com/mozilla/DeepSpeech/files/1336678/deepspeech_training_1_output.txt)

[visualize_training_logs.txt](https://github.com/mozilla/DeepSpeech/files/1336702/visualize_training_logs.txt)

**Comment by kdavis-mozilla** [comment]
@SebastianScherer88 Great that it's working, and yes we always target 16KHz

**Comment by reuben** [comment]
Seems like this can be closed, feel free to reopen if needed.
