### ISSUE TITLE
Update generic-worker to v10.2.3

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#855]
Now that bug https://bugzilla.mozilla.org/show_bug.cgi?id=1402152 has been fixed, we can update the generic-worker on the MacBook Pro to v10.2.3 and remove both scopes:
 - queue:claim-task
 - queue:resolve-task

On clientId:
 - project/deepspeech/worker/macos-heavy-1
 - project/deepspeech/worker/macos-heavy-2
 - project/deepspeech/worker/macos-light-1
 - project/deepspeech/worker/macos-light-2
 - project/deepspeech/worker/macos-light-3
 - project/deepspeech/worker/macos-light-4
 - project/deepspeech/worker/macos-light-5
 - project/deepspeech/worker/macos-light-6

**Comment by petemoore** [comment]
r+ :)

**Comment by lissyx** [comment]
Updated the binary, all generic-worker instances are running new 10.2.3.

**Comment by lissyx** [comment]
Scopes removed, launching PR for Tensorflow and DeepSpeech to verify.

**Comment by lissyx** [comment]
DeepSpeech test: https://tools.taskcluster.net/task-group-inspector/#/Kzl-8S8kQn2SnTBEMQT2WQ

**Comment by lissyx** [comment]
Tensorflow test: https://tools.taskcluster.net/task-group-inspector/#/Vm0LMa-rS5qHZnLIP_nMKw

**Comment by lissyx** [comment]
DeepSpeech task completed successfully: https://tools.taskcluster.net/groups/Kzl-8S8kQn2SnTBEMQT2WQ/tasks/ZmIqhBapTLOnLsXk90b-Mg/details

**Comment by lissyx** [comment]
Tensorflow task completed successfully: https://tools.taskcluster.net/groups/Vm0LMa-rS5qHZnLIP_nMKw/tasks/ZPhz_BehS-qtIzLvNqS3Lg/details

**Comment by lissyx** [comment]
It seems to be all good !

**Comment by petemoore** [comment]
:man_dancing:
