### ISSUE TITLE
how to use/install kenlm

### ISSUE THREAD

**Issue by SebastianScherer88** [mozilla/DeepSpeech#858]
hi all,

i have just tried to train a model using the current version, but im getting this error message:

(deepspeech_new) sebastian@Peter-Skynet-Ultron:~/GitReps/DeepSpeech$ ./bin/run-ldc93s1.sh
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/sebastian/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/sebastian/.local/share/deepspeech/ldc93s1
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
Traceback (most recent call last):
  File "DeepSpeech.py", line 468, in <module>
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/sebastian/anaconda3/envs/deepspeech_new/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: cannot open shared object file: No such file or directory

I think when i first used DeepSpeech there was no kenlm model involved for the decoding, it was done 'internally' in tensorflow, and it worked fine for me. How would i set up kenlm (preferably within a conda env) to get the model setup running again? i did a pip install as shown in kenlm's readme but that did not help. it looks like i need to push around some libraries, but i'm struggling to figure out the details. 

thanks,

seb

**Comment by elpimous** [comment]
it seems that you missed some params : 
did you add --decoder_library_path \  and --alphabet_config_path \?

if you use ctc_decoder, you need too : 
--lm_binary_path \
--lm_trie_path \

**Comment by reuben** [comment]
Check out the README, you don't have to build it yourself, just grab the binaries from our servers and then pass the appropriate path to --decoder_library_path. You don't have to worry about the language model or the trie unless you're building a model for a different language

**Comment by SebastianScherer88** [comment]
i want to train it on english data and i've now added the path to the alphabet text file, but he is still trying to access above kenlm related files. I dont want to use kenlm and would be happy to use the tensorflow ctc decoder as was implemented as few months ago, but i dont know how to make it so; the model default seems to be trying to access the kenlm stuff and use it in the decoding as seen on line 468-482 of DeepSpeech.py.

@elpimous: when i pass empty flags like that, i just get complaints/hints from argparse on how to properly use DeepSpeech.py

@reuben: which README do you mean specifically? is there any way i can just train the model on english data in a tensorflow, self-contained setting or is there no way around installing these trie/kenlm etc clients? I just dont remember setting this stuff up when i first ran the model.

**Comment by reuben** [comment]
You can use an older version of the code if you don't want the new decoder. There's no way to run the code on master without downloading the binaries that we provide.
