### ISSUE TITLE
unable to create trie with specific lm.binary

### ISSUE THREAD

**Issue by elpimous** [mozilla/DeepSpeech#863]
hi, I made a lm.binary, compressed, with next command : 
`build_binary trie -a 64`

So I try to create trie file : 
`./generate_trie /home/nvidia/DeepSpeech/data/alphabet.txt /home/nvidia/DeepSpeech/data/lm.binary /home/nvidia/DeepSpeech/data/words.txt /home/nvidia/DeepSpeech/data/trie`

returns error : 
```
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/binary_format.cc:131 in void lm::ngram::MatchCheck(lm::ngram::ModelType, unsigned int, const lm::ngram::Parameters&) threw FormatLoadException.
The binary file was built for trie with array-compressed pointers but the inference code is trying to load probing hash tables
Aborted (core dumped)
```
------------------------------------------

So, i think i can't create a trie file with a compressed binary lm !! Can U confirm ??

So, could I create the trie file with a default created lm.binary, and recreate, after a compressed lm ???

Really need it, 'cause a simple lm.binary of 14mo uses more than 3Go !!!

**Comment by reuben** [comment]
The language model needs to use a probing hash table. Don't pass the trie parameter to build_binary.

**Comment by elpimous** [comment]
Thanks Reuben, for precisions !
