### ISSUE TITLE
integrated kenlm decoder slower

### ISSUE THREAD

**Issue by SebastianScherer88** [mozilla/DeepSpeech#867]
hi all,

i have recently updated my deepspeech repo and noticed that you now seem to have a C based language model integrated into the beam search decoding stage. after some experimenting it seems that this causes a slowing down of the training; i have replaced the "decode_with_kenlm" line in during the operation placement stage of the DeepSpeech.py script with the older generic "tf.nn.ctc_decode" one, i.e. "simple", generic tensorflow sequence decoding, and it seems to be 4 times quicker. so two questions:

1) is this slowdown something that you observed as well?
2) with the above change of code, do i now essentially have the old model (on the tensorflow graph & and decoding to word-level level)?

thanks,

seb

**Comment by reuben** [comment]
1. Yes. The new decoder has to query the language model during its operation which is not free, and the beam width we use is now higher. You can try reducing the beam width to something like 100 or 200 to see if it's fast enough for your needs without sacrificing too much of the error rate.
2. Yes, except there's no such `tf.nn.ctc_decode` op in TensorFlow. We used to use `tf.nn.ctc_beam_search_decoder` with the default parameters.

**Comment by reuben** [comment]
BTW, one optimization that is still missing from the new decoder is beam pruning, which is supposed to achieve speedups of up to 20x. TensorFlow doesn't support it out of the box, but it's definitely on my radar to implement it.

**Comment by SebastianScherer88** [comment]
1. Thanks, that makes a lot of sense. I might try that!
2. Yes, thats the one i meant/used!

thanks!
