### ISSUE TITLE
Build instructions in native_client/README.md are bogus on OSX 10.12

### ISSUE THREAD

**Issue by Jfeng3** [mozilla/DeepSpeech#870]
### Command run
```
bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*
```
### Error message
```
1 warning generated.
ERROR:tensorflow/native_client/BUILD:59:1: Stripping native_client/generate_trie.stripped for //native_client:generate_trie failed (Exit 1).
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: only one -R option allowed
INFO: Elapsed time: 2298.852s, Critical Path: 168.02s
```

**Comment by lissyx** [comment]
@Jfeng3 Please provide STR, builds are okay on TaskCluster.

There is mention of `.stripped` target, which is known to be broken until newer version of `bazel` is available with https://github.com/bazelbuild/bazel/commit/b3be32e7135895737b64e3ad8ddb09176bfc8dd5

It's likely you used a wildcard, `//native_client:*` which would do that. Please use precise targets instead.

**Comment by lissyx** [comment]
confere: https://github.com/mozilla/DeepSpeech/blob/master/tc-build.sh#L39-L42

**Comment by lissyx** [comment]
@Jfeng3 Thanks, I guess you copy/pasted the command line from the documentation, we will have to update it :). In the meantime, there are mostly no reason you need to build yourself, you should be able to just use your prebuilt binaries at https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.osx/artifacts/public/native_client.tar.xz

**Comment by Jfeng3** [comment]
@lissyx  thanks for the quick reply! am testing it.

**Comment by Jfeng3** [comment]
basically you said to run
```
bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client::deepspeech //native_client:deepspeech_utils //native_client:ctc_decoder_with_kenlm //native_client:generate_trie
``` 
instead of the one on the README. right? not familiar with bazel

**Comment by Jfeng3** [comment]
@lissyx all the library file under https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.osx/artifacts/public/native_client.tar.xz seems to be *.so, which is shared library in linux. Can I use them on mac?

**Comment by elpimous** [comment]
bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*

**Comment by kdavis-mozilla** [comment]
@Jfeng3 Click on the "Other configurations" link, then on the "osx" link and there should be OS X  artifacts there.

**Comment by Jfeng3** [comment]
@kdavis-mozilla the native_client lib still has .so files

**Comment by lissyx** [comment]
@Jfeng3 Yes, it is okay to use them.
