### ISSUE TITLE
small example failed 

### ISSUE THREAD

**Issue by Jfeng3** [mozilla/DeepSpeech#871]
on Ubuntu, running the small example
```
./bin/run-ldc93s1.sh
```

Error message:
```
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43
```

**Comment by lissyx** [comment]
You have not installed Git-LFS, as documented: https://github.com/mozilla/DeepSpeech#prerequisites

**Comment by Jfeng3** [comment]
@lissyx I did 
git-lfs/2.3.2 (GitHub; linux amd64; go 1.8.1)
Sorry, no usage text found for "git-lfs"

**Comment by lissyx** [comment]
@Jfeng3 Either your git-lfs installation is not working properly, or you did that after git clone of the project. If the later, then re-do a clone.

**Comment by Jfeng3** [comment]
@lissyx worked after re-do clone . Thanks a lot!!
