### ISSUE TITLE
Ted training - GTX 1080 ti and  GTX 770 - OOM memory error 

### ISSUE THREAD

**Issue by CR1AT0RS** [mozilla/DeepSpeech#876]
Apologies if this is a very recurring issue. Please let me know if you can think of something I am missing.

**File:**
bin/run-ted.sh

**Tried already:**
I've tried changing ascending order in feeding.y and reducing Batch size to 2 and epoch to 1 Same error. I made sure that epoch_size % batch_size != 0

I've also always cleared out my .loca/share/deepspeech/ted checkpoint directories.

**Nvidia-smi:**
![screenshot from 2017-10-07 12-54-08](https://user-images.githubusercontent.com/4299288/31311321-a653a00e-ab5e-11e7-9e5d-63795b7ab947.png)

**Error:**
`+ [ ! -f DeepSpeech.py ]
+ [ ! -d  ]
+ COMPUTE_DATA_DIR=data
+ [ ! -f data/ted-train.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ted"))
+ checkpoint_dir=/home/teppi/.local/share/deepspeech/ted
+ python -u DeepSpeech.py --train_files data/ted-train.csv --dev_files data/ted-dev.csv --test_files data/ted-test.csv --train_batch_size 2 --dev_batch_size 2 --test_batch_size 2 --epoch 1 --display_step 5 --validation_step 1 --dropout_rate 0.30 --default_stddev 0.046875 --learning_rate 0.0001 --checkpoint_dir /home/teppi/.local/share/deepspeech/ted
E OOM when allocating tensor with shape[1000,2,2048]
E 	 [[Node: tower_1/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT64, batch_dim=1, seq_dim=0, _device="/job:localhost/replica:0/task:0/gpu:1"](tower_1/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3, tower_1/ToInt64_2)]]
E 	 [[Node: tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1/_555 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:1", send_device_incarnation=1, tensor_name="edge_2392_tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E 
E Caused by op 'tower_1/ReverseSequence', defined at:
E   File "DeepSpeech.py", line 1765, in <module>
E     tf.app.run()
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
E     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
E   File "DeepSpeech.py", line 1725, in main
E     train()
E   File "DeepSpeech.py", line 1484, in train
E     results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
E   File "DeepSpeech.py", line 625, in get_tower_results
E     calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
E   File "DeepSpeech.py", line 506, in calculate_mean_edit_distance_and_loss
E     logits = BiRNN(batch_x, tf.to_int64(batch_seq_len), dropout)
E   File "DeepSpeech.py", line 436, in BiRNN
E     sequence_length=seq_length)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 435, in bidirectional_dynamic_rnn
E     seq_dim=time_dim, batch_dim=batch_dim)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 419, in _reverse
E     seq_dim=seq_dim, batch_dim=batch_dim)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2394, in reverse_sequence
E     name=name)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2801, in reverse_sequence
E     batch_dim=batch_dim, name=name)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
E     op_def=op_def)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
E     original_op=self._default_original_op, op_def=op_def)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
E     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
E 
E ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1000,2,2048]
E 	 [[Node: tower_1/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT64, batch_dim=1, seq_dim=0, _device="/job:localhost/replica:0/task:0/gpu:1"](tower_1/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3, tower_1/ToInt64_2)]]
E 	 [[Node: tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1/_555 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:1", send_device_incarnation=1, tensor_name="edge_2392_tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E 
Traceback (most recent call last):
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/teppi/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1000,2,2048]
	 [[Node: tower_1/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT64, batch_dim=1, seq_dim=0, _device="/job:localhost/replica:0/task:0/gpu:1"](tower_1/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3, tower_1/ToInt64_2)]]
	 [[Node: tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1/_555 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:1", send_device_incarnation=1, tensor_name="edge_2392_tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1552, in train
    step = session.run(global_step, feed_dict=feed_dict)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1000,2,2048]
	 [[Node: tower_1/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT64, batch_dim=1, seq_dim=0, _device="/job:localhost/replica:0/task:0/gpu:1"](tower_1/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3, tower_1/ToInt64_2)]]
	 [[Node: tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1/_555 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:1", send_device_incarnation=1, tensor_name="edge_2392_tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'tower_1/ReverseSequence', defined at:
  File "DeepSpeech.py", line 1765, in <module>
    tf.app.run()
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1725, in main
    train()
  File "DeepSpeech.py", line 1484, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 625, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
  File "DeepSpeech.py", line 506, in calculate_mean_edit_distance_and_loss
    logits = BiRNN(batch_x, tf.to_int64(batch_seq_len), dropout)
  File "DeepSpeech.py", line 436, in BiRNN
    sequence_length=seq_length)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 435, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 419, in _reverse
    seq_dim=seq_dim, batch_dim=batch_dim)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2394, in reverse_sequence
    name=name)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2801, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1000,2,2048]
	 [[Node: tower_1/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT64, batch_dim=1, seq_dim=0, _device="/job:localhost/replica:0/task:0/gpu:1"](tower_1/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3, tower_1/ToInt64_2)]]
	 [[Node: tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1/_555 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:1", send_device_incarnation=1, tensor_name="edge_2392_tower_1/gradients/tower_1/MatMul_4_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

E You must feed a value for placeholder tensor 'Queue_Selector' with dtype int32
E 	 [[Node: Queue_Selector = Placeholder[dtype=DT_INT32, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E 	 [[Node: tower_1/boolean_mask/Reshape_1/_1045 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:1", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2184_tower_1/boolean_mask/Reshape_1", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/gpu:1"]()]]
E 
E Caused by op 'Queue_Selector', defined at:
E   File "DeepSpeech.py", line 1765, in <module>
E     tf.app.run()
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
E     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
E   File "DeepSpeech.py", line 1725, in main
E     train()
E   File "DeepSpeech.py", line 1472, in train
E     tower_feeder_count=len(available_devices))
E   File "/media/teppi/Extra/DeepSpeech/util/feeding.py", line 43, in __init__
E     self.ph_queue_selector = tf.placeholder(tf.int32, name='Queue_Selector')
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
E     return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, in _placeholder
E     name=name)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
E     op_def=op_def)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
E     original_op=self._default_original_op, op_def=op_def)
E   File "/home/teppi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
E     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
E 
E InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Queue_Selector' with dtype int32
E 	 [[Node: Queue_Selector = Placeholder[dtype=DT_INT32, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E 	 [[Node: tower_1/boolean_mask/Reshape_1/_1045 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:1", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2184_tower_1/boolean_mask/Reshape_1", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/gpu:1"]()]]
E 
E Provide a --checkpoint_dir argument to work with models of different shapes.`

**Comment by CR1AT0RS** [comment]
SO the first GPU is running out of memory the  GTX 770 one.  It runs fine without the GTX 770. I can manually assign GPU but memory management from tensorflow should avoid this issue.

Even reducing size of batch doesn't help and I also wanna make sure 1080 ti gets used to its max. So even if I run it with batch_size=1 then I am wasting resources on 1080ti. In what way can I use the other graphic card so that it's not a complete waste ?

**Comment by reuben** [comment]
> In what way can I use the other graphic card so that it's not a complete waste?

You'll have to change the code to not deploy identical graphs to all the GPUs. The GTX 770 has 2GB of RAM which I don't think is enough to do any training, but you could try offloading just some operations to it, like running test epochs in parallel only on that GPU alone to evaluate the WER progression, or something like that.
