### ISSUE TITLE
Is batch size at all related to model geometry?

### ISSUE THREAD

**Issue by nmstoker** [mozilla/DeepSpeech#879]
I've been running TED on 1080 Ti for a while now (it's around 18 hours in) and am now concerned that with the default batch sizes (16, 8, 8) I _may_ run into OOM issues.

Please could someone confirm if stopping a run and changing the batch size has any impact on the model geometry (_sorry, it's probably obvious to others, but I couldn't infer it from docs or looking over  issues_).

The reason I ask is that there is this point in [README.md](/mozilla/DeepSpeech/blob/master/README.md): 
> Be aware however that checkpoints are only valid for the same model geometry they had been generated from. In other words: If there are error messages of certain Tensors having incompatible dimensions, this is most likely due to an incompatible model change. One usual way out would be to wipe all checkpoint files in the checkpoint directory or changing it before starting the training.

And if changing the batch size changes the geometry then I  won't be able to continue later with the checkpoint from now.  I may well be out of options, but would rather avoid wasting that ~18 hrs if at all possible!!

Thank you
Neil

**Comment by Drea1989** [comment]
hello, no you can start/stop the training with different batch sizes without losing progress

**Comment by nmstoker** [comment]
Thanks. Good to know! (I'd guessed that might be true but appreciate the response)
