### ISSUE TITLE
Package and publish Python/Node.JS bindings

### ISSUE THREAD

**Issue by sruteesh** [mozilla/DeepSpeech#892]
Hello I'm trying to use the updated native client decoder with lm 
I have a `output_graph.pb` generated using the `./bin/run-ldc93s1.sh` I am getting the following error
`ImportError: No module named deepspeech.model`
I have downloaded the bindings using `python util/tc.py ./native_client gpu`
I'm running inference using `python client.py output_graph.pb <input_audio_file>.wav ../data/alphabet.txt ../data/lm/lm.binary ../data/lm/trie`
Thanks

**Comment by reuben** [comment]
The native_client.tar.xz file downloaded by tc.py doesn't include the Python or Node.JS bindings, so for now you need to build and install those from source. It's probably a good idea to package the bindings, so I'll make this issue track that.

**Comment by lissyx** [comment]
There are prebuilt packages for the Python and Node bindings. You can find latest amd64 cpu builds there: https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu

**Comment by lissyx** [comment]
Those bindings should pickup your GPU-enabled libdeepspeech downloaded.

**Comment by reuben** [comment]
Ah, even better! I looked at the artifact list for the GPU build and didn't see those there.

**Comment by lissyx** [comment]
@sruteesh Update to current master, you should be able to do something like:
```
$ python util/tc.py --target /tmp/nc/ --arch gpu
$ python util/tc.py --target /tmp/nc/ --arch cpu --artifact deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl
$ pip install --upgrade /tmp/nc/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl
```

You can change the artifact to any of those available on: https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu
