### ISSUE TITLE
Training a model with ubuntu 16.04 using 64 bit machine

### ISSUE THREAD

**Issue by guruCDL** [mozilla/DeepSpeech#896]
Hi All,

Installed Tensorflow from source as per native_client read me. 

Built tensorflow and native library successfully as well.
make successful as well.
Lib path has all the binaries which are required.

Tensorflow version installed from source - 1.4.0
gcc version - 5.4.0
os - ubuntuv version 16.04 using 64 bit machine
python - 2.7

When i try to train a model below error occurs - is this related to cpu compatibility?

("deepspeech/ldc93s1"))
+ checkpoint_dir=/root/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1
Traceback (most recent call last):
  File "DeepSpeech.py", line 468, in <module>
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow10DEVICE_CPUE

Note- This error does not occur if i run tensorflow version 1.3.0 but the training will fail at the end saying illegal instruction(core dumped).

Any suggestions?

**Comment by voidspacexyz** [comment]
I can also confirm the same issue on a CPU only machine. But the same on a GPU machine works

**Comment by lissyx** [comment]
1.4 is an unknown area, the CTC decoder was worked on against ~1.3.

**Comment by lissyx** [comment]
I guess @reuben can provide more insight, but I would advise either sticking to our prebuilt binaries and/or if you need to rebuild, using our tensorflow master https://github.com/mozilla/tensorflow

**Comment by voidspacexyz** [comment]
@lissyx The problem with custom tensorflow is the need for me as an ops to maintain many versions and its usually not approved at multiple places. I know its a very vauge reason, but this is the reality. So if there is someway we could stick to the default tensorflow with a specific version, it just get much easier.

Will wait to hear from @reuben  as well

**Comment by voidspacexyz** [comment]
@lissyx I am currently running 1.3 tensorflow. Following is the details 
root@cdedce3dbcd9:/work/DeepSpeech# pip freeze | grep tensorflow
tensorflow==1.3.0
tensorflow-tensorboard==0.1.8
So I guess, there is something else,that is going wrong.

**Comment by lissyx** [comment]
@voidspacexyz I can understand your admin issue, but for diagnosing problems we need to be sure it's not just a broken setup that triggers your bug. So far, you just confirm that you are running a prebuilt, upstream Tensorflow.

You really need to get that straight: either use ALL of ours prebuilt binaries (tensorflow, libctc, libdeepspeech), or build everything from compatible source code. Mixing prebuilt binaries would clearly trigger that kind of segfault (I know, I have been there, there might be differences in ABI, in headers, in data structure sizes).

Compatibility with upstream tensorflow cannot be guaranteed, because they don't guarantee C++ API stability. So they might have done some changes to 1.3 API between the snapshot we started worked on, and the release, and the same story can apply to 1.4.

**Comment by voidspacexyz** [comment]
https://github.com/voidspacexyz/DeepSpeech-docker/blob/master/Dockerfile

So I tried what you told. Above is the docker file I used. 
I am still stuck with " Aborted (core dumped) " .
Am I making something wrong ?

**Comment by lissyx** [comment]
@voidspacexyz In your latest message, the Docker refers to  https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.cpu.0b3924976af2f14707702156973725ec5fd4a32d/artifacts/public/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl ... That's quite an old commit, and not the one https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/native_client.tar.xz is getting linked against for sure.

**Comment by lissyx** [comment]
Please use:
 - https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/native_client.tar.xz
 - https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl

**Comment by lissyx** [comment]
Also, the full log run would be useful to diagnose what is failing.

**Comment by voidspacexyz** [comment]
I am currently building everything manually and testing it out, just to make sure I dont repeat these silly mistakes again. Once I finish, I will immediately update here. Also will update the docker accordingly.

PS : Thanks for the right links. There was a certain degree of confusion with that.

**Comment by lissyx** [comment]
FYI, all the prebuilt binaries are being built and tested on TaskCluster, training included. Technically, there's Docker below the TaskCluster linux instances, so there's no reason anything would not work on your side.

**Comment by voidspacexyz** [comment]
@lissyx  This is the gist I followed in a fresh ubuntu 16.04 docker.

https://gist.github.com/voidspacexyz/9890dfb02e0730acbfc218980c59fdc9

I am still stuck with Illegal instruction (core dumped)
Can you have a look at it once ?

**Comment by reuben** [comment]
If you built TensorFlow and libctc_decode_with_kenlm.so out of the same tensorflow source tree then there should be no symbol mismatches. I haven't personally tested with TensorFlow 1.4, I'll update my clone and rebuild to see if I run into the same problem.

**Comment by lissyx** [comment]
Illegal instruction is not segfault :-). @voidspacexyz Can you document your bazel build flags ?

**Comment by reuben** [comment]
Something weird is going on with TensorFlow 1.4.0rc0, I recommend sticking with stable versions. I'll investigate more carefully before 1.4.0 is released, but I can't focus on that right now.

**Comment by voidspacexyz** [comment]
@lissyx @reuben  I am running tensorflow 1.3 and not 1.4. 
I just did a pip install tensorflow==1.3 , and I still havent compiled mozilla's tensorflow. That is something I am going to do now.Will update once done.

**Comment by voidspacexyz** [comment]
@lissyx  I have not been able to build mozilla's version of tensorflow . Any build instructions. From tensorflow-wrapctc I figured out, the tensorflow version is 1.3.0rc0 . I tried installing tensorflow==1.3.0rc0 from pypi, and this is the error I get.

root@1792d90ae9dc:/work/DeepSpeech# ./bin/run-ldc93s1.sh 
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/root/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /root/.local/share/deepspeech/ldc93s1
2017-10-20 06:36:32.353648: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)

I am clearly missing something very silly here. BTW, just in case, I am running all this on a CPU only machine.

**Comment by lissyx** [comment]
@voidspacexyz Well the error is explicit, you are using upstream tensorflow with AVX2 enabled and you system does not support that. There are two problems in your statement about 1.3.0rc0 ; first, you pick upstream with AVX2 :). Second, you get tricked by the versionning from Tensorflow, which seems to use 1.3.0rc0 all along dev period, so what we have with that version number *might* not be compatible with theirs.

There is really no reason you should not be able to build yourself. Looking at your gist, I see several problems:
 - `-c opt` and `--config=opt` does the same
 - you have `--copt=-mavx2`, you are going to have issues
 - what is that `-k` ?

I never ever saw that weird ` ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors`. Which version of bazel are you using ? 0.5.2 and 0.5.4 should work. It might also be possible that the fact you run everything as root is not a good idea.

**Comment by lissyx** [comment]
@voidspacexyz Another thing I saw in your gist: there's a `pip install tensorflow==1.3` statement at line 23, so I'm unsure about your other install at line 38. It might get your into a weird state.

On line 44 you copy all the .so files, to `/work/DeepSpeech/native_client/`, it is likely you will need to change your `LD_LIBRARY_PATH` to contain that path otherwise the bindings you install on line 47 won't pick the `.so` files.

And there's no trace of your bazel installation there.

**Comment by lissyx** [comment]
I got similar reports from other contributor hitting similar issue than you regarding the bazel error. This was with Bazel 0.7.0. Switching to 0.5.4 fixed that.

**Comment by guruCDL** [comment]
@voidspacexyz - Here is what worked for me on Ubuntu 16.04(X86 _64 machine)

1.Installed Bazel 0.5.4 (select appropirate .sh file for you machine below)
https://github.com/bazelbuild/bazel/releases/tag/0.5.4

2. Built TensorFlow 1.3.0 from source 
https://www.tensorflow.org/install/install_sources
https://github.com/tensorflow/tensorflow/releases/tag/v1.3.0-rc1

Errors Encountered during build time 
--------------------------------------------
1.  https://github.com/tensorflow/tensorflow/issues/12979

Solution : As a workaround just comment the sha256 checksum lines in tensorflow/workspace.bzl or replace with what is showed in the error message. 
---------------------------------------------------
2. Encountered if_Linux_x86_64 not defined or found when running below command 

bazel build -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*

Solution: change if_linux_x86_64 to if_x86
------------------------------------------------------
3. Encountered implementation not found for native_client/libctc_decoder_with_kenlm.so

solution: make deepspeech should fix this- else just copy libctc_decoder_with_kenlm.so from tensorflow-1.3.0/bazel-bin/native_client/ to Deepspeech/native_client. 

Hope it helps.

**Comment by lissyx** [comment]
@guruCDL Those steps are useless, except the Bazel 0.5.4 one. Please rely on our Tensorflow, and not upstream tensorflow, if you build from sources: you will not have to disable the checksum, `if_linux_x86_64` is defined, and `libctc_decoder_with_kenlm.so` will work.

**Comment by guruCDL** [comment]
@lissyx - Thanks I had missed your earlier comment of building https://github.com/mozilla/tensorflow master from source. It actually works with bazel 0.5.4 and training a model works great . 

However we still below error when running the client (ARGS="/opt/DeepSpeech/exportmodel/output_graph.pb /opt/DeepSpeech/data/ldc93s1/LDC93S1.wav" make run )
                  
"./deepspeech: symbol lookup error: ./libdeepspeech.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
"

Ubuntu-16.04

Any thoughts?

**Comment by lissyx** [comment]
@guruCDL I can definitively remember hitting that missing symbol because of mixing .so between versions :-). Can you: `objdump -t libtensorflow_cc.so` ?

For me, it gives:
```
$ objdump -t libtensorflow_cc.so | grep CheckOpMessageBuilder9
0000000003bd0260 g     F .text	00000000000000d7              _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
$ objdump -t libdeepspeech.so | grep CheckOpMessageBuilder9
0000000000000000         *UND*	0000000000000000              _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```

So the symbol is defined by `libtensorflow_cc.so` and used by `libdeepspeech.so`.

**Comment by guruCDL** [comment]
@lissyx  - Actually I corrected the missing symbol issue(pls check attachment)

![result](https://user-images.githubusercontent.com/2729268/31865917-09d7aae8-b745-11e7-8141-75417b96688d.png)

But Unfortunately when i run below i get core dumped error
root@lifescience:/opt/DeepSpeech/native_client# deepspeech /opt/DeepSpeech/exportmodel/output_graph.pb /opt/DeepSpeech/data/ldc93s1/LDC93S1.wav /opt/DeepSpeech/data/ldc93s1/LDC93S1.txt

Aborted(core dumpled)

**Comment by voidspacexyz** [comment]
I havent been able to figure it out yet.The whole thing is so confusing on a CPU only machine.My laptop has some basic gpu(Intel) and the docker file I wrote builds just fine with stock tensorflow(1.3 upstream) and training and predection just works. I am stopping to pursue CPU only machine here, since I am going to be getting a nvidia GPU machine starting next month. I would be happy if someone is able to pursue and get this to actually work.

**Comment by lissyx** [comment]
@guruCDL Pretty sure that this segfault is because you gave no alphabet file :). We added a few arguments to the `deepspeech` binary, run it without any arguments and you'll get more documentation :)

**Comment by lissyx** [comment]
BTW @guruCDL when you say you corrected the missing symbol, can you document what your issue was ? It might help us in writing a FAQ and ensuring our README and other docs are straight :)

**Comment by guruCDL** [comment]
@lissyx - Thanks for pointing out the alphabet file. Below is the issue and fix for missing symbol. 

Issue- Missing symbol error from libdeepspeech.so

Cause- Happens when you have other versions of libtensorflow_cc.so in your native_client folder. I had 1.3.0 version of that but my built version of libdeepspeech.so was different. 

I had to copy correct version to match the symbol .

**Comment by lissyx** [comment]
Perfect, that exactly matches my expectations :)

**Comment by guruCDL** [comment]
@lissyx - Have you guys published any pre-trained models? something like generic English model?

**Comment by praveeny1986** [comment]
Why there is no link to download tensorflow_warpctc wheel file in the installation instruction in ReadMe ? I think this missing link is creating confusion and everyone is trying to build it from source or installing it from upstream tensorflow and hence issues :(

**Comment by reuben** [comment]
Yeah, I'm actually updating the docs right now to highlight the prebuilt binaries :(

**Comment by liuguangyuan** [comment]
i have solved it.
**_NOTE on gcc 5 or later: the binary pip packages available on the TensorFlow website are built with gcc 4, which uses the older
ABI. To make your build compatible with the older ABI, you need to add --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" to your
bazel build command. ABI compatibility allows custom ops built against the TensorFlow pip package to continue to work against your built package._**

so, you should check version of gcc. if it  is 5 or later, you should add _--cxxopt="-D_GLIBCXX_USE_CXX!!_ABI=0"_

when you compile tensorflow by yourself, use bazel build _-cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt //tensorflow/tools/pip_package:build_pip_package_
then you use _bazel build -cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" -c opt --copt=-march=native --copt=-mtune=native --copt=-O3 //tensorflow:libtensorflow_cc.so //native_client:*_
at last, you use _bazel build -cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"  //native_client:ctc_decoder_with_kenlm_
succeed!

**Comment by lissyx** [comment]
@liuguangyuan It's not safe to advise people to do that, the C++ API has no stability guarantee from Tensorflow team, and so the decoder might not work as expected if you mix out pre-built binaries with upstream builds.

**Comment by liuguangyuan** [comment]
@lissyx i see, thank you.

**Comment by lissyx** [comment]
@liuguangyuan It's not about agreeing with me or not, Tensorflow people do not guarantee the stability of the API and we know it is broken between 1.3 and 1.4 for example. Consequence of that is that people doing this will run into strange bugs and issues we won't be able to help with.

**Comment by nealmcb** [comment]
Having a docker build like this would be great.
Like @voidspacexyz I can't use the latest official wheels because I have a slightly older Ivy Bridge Intel machine without AVX2.  It thus complains like this after doing `pip install deepspeech`, for linux, python 2.7, and running `deepspeech --help`:
```
F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled
to use AVX2 instructions, but these aren't available on your  machine.
Aborted (core dumped)
```
So I'd love it if someone can incorporate all the advice above on how to build using the Mozilla Tensorflow, without requiring the new harware instructions.

The time is ripe now that [Release Deep Speech 0.1.0 · mozilla/DeepSpeech](https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0).

**Comment by sn0wf1llin** [comment]
Please HELP needed
`Illegal instruction: 4
`
python 2.7 
mac os high sierra 10.13.1
`gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by lissyx** [comment]
@sn0wf1llin Please avoid to hijack closed issues and give more informations on what you are doing. We cannot help if we don't know what you are doing.

**Comment by sn0wf1llin** [comment]
I want to use your library from the code, with standard `import deepspeech` or smth else; I just want to process speech with your pre-trained model (client.py has this functional)
`from deepspeech.model import Model`
give me `illegal instruction: 4`

**Comment by imKKK** [comment]
can anyone please help me with this error on windows subsytem for linux :ubuntu cpu
tensorflow.python.framework.errors_impl.NotFoundError: /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE

**Comment by lissyx** [comment]
> can anyone please help me with this error on windows subsytem for linux :ubuntu cpu
> tensorflow.python.framework.errors_impl.NotFoundError: /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE

This is the third time in a few minutes I'm seeing the exact same message from you. You should really stop spamming everywhere and start reading the documentations.

**Comment by MuruganR96** [comment]
This Native client mismatch error. Sir you should follow proper arch,
branch for your cloned repo.

**Comment by imKKK** [comment]
@MuruganR96 if you dont mind can you please elaborate the steps.. I am using DeepSpeech 0.3.0 model from the releases. but the project was cloned on 30.10.2018 from master.

**Comment by MuruganR96** [comment]
Sir once again you will do step by step,

clone deep speech repo,
Then check out v0.3.0,
Download Native client,
python3 until/taskcluster.py --arch "cpu" --target new_native_client/
--branch "v0.3.0"

Sir and then run DeepSpeech.py .

**Comment by imKKK** [comment]
okay sir thank you...

the steps I am going to do is....

1. clone deepspeech repo from current Master,
2. Then check out v0.3.0 
3. Then Download Native Client using python3 until/taskcluster.py --arch "cpu" --target new_native_client/ --branch "v0.3.0" .... and the native client files would go to the new_native_client directory. so that i should include this directory path to the command while training.....
4. Then i should start training with DeepSpeech.py 
 correct...!!

**Comment by imKKK** [comment]
@MuruganR96 sir Thank you so much for your support. I followed your steps and successfully built the project and I had some error in my a CSV files which caused 'Series' object has no attribute 'transcript' error and cleared.. Now The training is going on.. 
@nullbyte91 Thankyou for your support..
