### ISSUE TITLE
Confidence Values from DeepSpeech model

### ISSUE THREAD

**Issue by nancywang1991** [mozilla/DeepSpeech#900]
Hi everyone, I was wondering if there could be a way to produce a confidence value for each transcription? Thanks!

**Comment by gr8nishan** [comment]
i also need to know this. If anyone knows let me know.

**Comment by kdavis-mozilla** [comment]
We currently don't have this. However, I think it would be a great addition.

**Comment by lissyx** [comment]
We could do that now that we have `ctcdecode`

**Comment by Aadhar3** [comment]
Hi, how can you use ctcdecode to obtain the confidence values?

**Comment by lissyx** [comment]
@Aadhar3 You should check that on ctcdecode codebase / repo directly: https://github.com/parlance/ctcdecode

**Comment by reuben** [comment]
Well, no, since we import the code directly into our repo and change it significantly. I'm pretty sure I've described in high level terms how one would modify the code to expose this, but I don't remember where...

**Comment by reuben** [comment]
Here: the Output structure also has a probability field which corresponds to the language model confidence in the transcription: https://discourse.mozilla.org/t/word-letter-timestamp-with-deep-speech/34981/5?u=reuben

**Comment by lissyx** [comment]
@reuben we could build on top of the changes from @dabinat to build that ?

**Comment by reuben** [comment]
Yes, should be super simple to add now, just add to the existing structures.

**Comment by dabinat** [comment]
As well as confidence, it would be handy to have a list of words it could also be. That may be more of a client feature though.

**Comment by lissyx** [comment]
> As well as confidence, it would be handy to have a list of words it could also be. That may be more of a client feature though.

Hey @dabinat, do you want to try and add confidence exposure at first ?

**Comment by dabinat** [comment]
Happy to take a look, but won't be able to for a couple of weeks.
