### ISSUE TITLE
Publish packages on repositories

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#909]
Now that we have `npm` and `pypi` packages that we build and test, we should publish those on the repositories. This depends on #908

**Comment by lissyx** [comment]
We might actually want to perform this before #908

**Comment by kdavis-mozilla** [comment]
Why before?

**Comment by lissyx** [comment]
Because it might be easier :)

**Comment by lissyx** [comment]
PyPi is done, npm should be soon.

**Comment by lissyx** [comment]
This was done with #1041
