### ISSUE TITLE
Training with custom data+issues

### ISSUE THREAD

**Issue by guruCDL** [mozilla/DeepSpeech#913]
[test.txt](https://github.com/mozilla/DeepSpeech/files/1423420/test.txt)

Hi All,

I was able to successfully train the example data ldc93s1.csv and corresponding wav file. I do see desired results after training . 

Now I am trying to train our own data and not seeing desired results . My test.wav is 7 secs in length (see attached pls rename .txt to .wav). 

Below is my test.csv file

wav_filename,wav_filesize,transcript
/opt/DeepSpeech/data/pharmadata/test.wav,224078,this is reporting title venus scratch that this is reporting title initial evaluation patient name jennifer gratys

Below is the output i get after training 
this is eprtingtitlevenusscrathtathisnisrpotingtitenitilevauipoptienamejenifergratys

I have verified test.wav properties and reads as below
test.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz

Below is the command I am running to train my model 
root@lifescience:/opt/DeepSpeech# python -u DeepSpeech.py --train_files /opt/DeepSpeech/data/pharmadata/test.csv --dev_files /opt/DeepSpeech/data/pharmadata/test.csv --test_files /opt/DeepSpeech/data/pharmadata/test.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494  --epoch 50  --export_dir /opt/DeepSpeech/venus/  --checkpoint_dir /opt/DeepSpeech/dictexroot

Below is what i get when i run the client 
this is eporting title enscrcatht this is reprting titlenitil eauatonptien namejnifergratys

**Comment by guruCDL** [comment]
@All - Increasing epoch solved my issue- Few questions. 

1. vocub.txt in  ldc93s1/lm folder - can we add more data to it?

2. Do we need to build the language model every time when we add data?

3. How to reuse exported model to train new data?

**Comment by elpimous** [comment]
Hi GuruCDL
I train my models from scratch, and here is my process:

I record wav's  and add the corresponding sentences in a textfile (vocabulaire.txt)
I use this textfile to create lm, trie, and the present vocab

1/ As you see, I add sentences when I create wavs, but you could, too, add texts, without corresponding wavs.  This bigger textfile could be used to create your lm and trie files.
Lm and binaries act like probabilities (ex : I have 4 words ! What is their best order, regarding to lm)

The bigger the lm, the best words order in sentence (in the facts!)
But the more material (wavs/sentences), the best the model (depending of the deep structure of course.)

2/ if you add new wavs , with new sentences, words... yes you must improve your lm.
How your new model could order words in unknown sentence ??! (It would try, but with lower accuracy)

3/ waiting for howto, too !

CU.
Vincent

**Comment by guruCDL** [comment]
@elpimous - Thanks for sharing.

**Comment by lissyx** [comment]
Looks like there is no issue here, I'm closing that, especially since there are discourse threads covering this.
