### ISSUE TITLE
I STARTING Optimization

### ISSUE THREAD

**Issue by dreamibor** [mozilla/DeepSpeech#916]
Hi.

How long does it take for you to train the Deep Speech model on a GPU? I am using a GTX 980 to train the Deep Speech model on LibriSpeech. The program gives a info :"I STARTING Optimization" and there is no more logs even I have trained for two days.

Here is my configuration:
"
+ [ ! -f DeepSpeech.py ]
+ [ ! -d  ]
+ COMPUTE_DATA_DIR=data/LibriSpeech
+ [ ! -f data/LibriSpeech/librivox-train-clean-100.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/librivox"))
+ checkpoint_dir=/home/ivg/.local/share/deepspeech/librivox
+ python -u DeepSpeech.py --train_files data/LibriSpeech/librivox-train-clean-100.csv,data/LibriSpeech/librivox-train-clean-360.csv,data/LibriSpeech/librivox-train-other-500.csv --dev_files data/LibriSpeech/librivox-dev-clean.csv,data/LibriSpeech/librivox-dev-other.csv --test_files data/LibriSpeech/librivox-test-clean.csv,data/LibriSpeech/librivox-test-other.csv --train_batch_size 12 --dev_batch_size 12 --test_batch_size 12 --learning_rate 0.0001 --epoch 15 --display_step 5 --validation_step 5 --dropout_rate 0.30 --default_stddev 0.046875 --checkpoint_dir logs/ckpt --export_dir logs/pb
"

Thanks,

**Comment by guruCDL** [comment]
@dreamibor - how many days did it take for you to complete this training- also can you tell us what was the RAM speed and cpu/gpu?

**Comment by dreamibor** [comment]
@guruCDL Hi, I haven't finished the training yet. The model constantly gives me error like "OOM not enough", even after I have reduced the batch size to 3. It seems I don't have enough RAM memory in GPU, but it's unreasonable that the program cannot show any logging files.

The CPU: Intel® Core™ i7-6700 CPU @ 3.40GHz × 8
The GPU: PNY GeForce GTX 980 4GB
RAM: 16 GB SK Hynix 2133 MHz

**Comment by lissyx** [comment]
@dreamibor Sadly, 4GB of memory is not enough. You should switch to something with at least 8GB.

**Comment by jackHuanghello** [comment]
Have you finished training yet？ I have trained the model with default parameters for 10 days, but the training progress doesn't finish. I  use one GPU (Tesla, 12G) to train the model.

**Comment by dreamibor** [comment]
@jackHuanghello Hi, I stopped the training manually and got a relatively good result (0.208 WER).

**Comment by bambamochu** [comment]
@dreamibor how did you stop the training manually and get the output model? I thought the model is only generated after all training?

**Comment by dreamibor** [comment]
@bambamochu Control + C will do the trick, and then you can extract the model from saved checkpoints.

**Comment by bambamochu** [comment]
@dreamibor do you have code example or reference on how to extract the model from saved checkpoint?

**Comment by dreamibor** [comment]
@bambamochu http://www.cloverio.com/2017/10/27/tensorflow-save-and-restore-models/. You have to download the TensorFlow source code first. The output_node_names for this model is: "output_node".
