### ISSUE TITLE
Client.py example error

### ISSUE THREAD

**Issue by dcam0050** [mozilla/DeepSpeech#944]
Hi, great repo had no issue training a model on GPU using `./bin/run-ldc93s1.sh` however when I try to use `client.py` to perform an inference I get the following error:

```Error running session: Invalid argument: Session was not created with a graph before Run()!```

I modified the training to save my model to DeepSpeech/../models and trained with   ```--decoder_library_path ./native_client/libctc_decoder_with_kenlm.so ```

The parameters I'm using for my `client.py` are (launched from root DeepSpeech folder):
```./native_client/client.py ../models ./data/smoke_test/LDC93S1.wav ./data/alphabet.txt```

I've installed:
```tensorflow_gpu_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl``` from ```project.deepspeech.tensorflow.pip.gpu.0b3924976af2f14707702156973725ec5fd4a32d```

```deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl``` using ```python util/tc.py --target /destination --artifact deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl```

Downloaded DeepSpeech master and installed native_client using ```python util/tc.py --target /destination --arch gpu```

Any help would be greatly appreciated

**Comment by lissyx** [comment]
You should give the `.pb` file path, not just the export directory :)

**Comment by dcam0050** [comment]
Great! Thanks for that!
