### ISSUE TITLE
Can I just use the model without any training? If no, can I download a pretrained model?

### ISSUE THREAD

**Issue by The-Gupta** [mozilla/DeepSpeech#948]

**Comment by raubreywhite** [comment]
+1

**Comment by cathalgarvey** [comment]
It seems that there are now public binaries, and instructions to use them.. though the Protobuf files seem not to be in the repository?

**Comment by stes** [comment]
I guess uploading the model is currently in progress, see the [Meeting notes](https://github.com/mozilla/DeepSpeech/wiki/Meeting-Notes) in the wiki:

```
Release TODO

Test CV data set [Tilman]
Update documents to suggest virtual env [Alex]
Add GPU whl's to PyPI + update docs [Reuben]
Change contact point for PyPI packages [Reuben]
Add node packages by hand + update docs [Reuben + Alex]
Tag release [Reuben + Alex]
Upload model + LibriVox clean audio samples to github releases [Kelly]
Remake gif using github releases model + LibriVox clean audio samples [Kelly]
Update docs with new gif [Kelly]
Go live with the Hacks blog post [Reuben]
Inform partners of release [Kelly]
```

**Comment by andrzejwp** [comment]
The model is available in the Relases section:
https://github.com/mozilla/DeepSpeech/releases/download/v0.1.0/deepspeech-0.1.0-models.tar.gz

**Comment by cathalgarvey** [comment]
Thank you!

On 25 November 2017 10:06:09 GMT+00:00, andrzejwp <notifications@github.com> wrote:
>The model is available in the Relases section:
>https://github.com/mozilla/DeepSpeech/releases/download/v0.1.0/deepspeech-0.1.0-models.tar.gz
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/DeepSpeech/issues/948#issuecomment-346931084

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lissyx** [comment]
I'm going to close that issue now, feel free to ask for help and discuss on Discourse :) https://discourse.mozilla.org/c/deep-speech
