### ISSUE TITLE
issue with  libctc_decoder_with_kenlm.so

### ISSUE THREAD

**Issue by 19578** [mozilla/DeepSpeech#950]
`sudo python DeepSpeech.py 
Traceback (most recent call last):
  File "DeepSpeech.py", line 468, in <module>
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
`

I have been trying for a few weeks to try to solve the issues with the native libraries however it isn't working well for me.
I have already tried the method that is written in the instructions, however i always get an error in making.
when i am supposed to do 

> cd ../DeepSpeech/native_client
make deepspeech

the error i receive 
`g++ -o deepspeech `pkg-config --cflags sox`  client.cc `pkg-config --libs sox` -Wl,-rpath,. -L../../tensorflow/bazel-bin/tensorflow -L../../tensorflow/bazel-bin/native_client  -ldeepspeech -ldeepspeech_utils -ltensorflow_cc 
/usr/bin/ld: cannot find -ldeepspeech
/usr/bin/ld: cannot find -ldeepspeech_utils
/usr/bin/ld: cannot find -ltensorflow_cc
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1
`
It is very important for me to get this working.

Thank you in advance .

**Comment by kdavis-mozilla** [comment]
Are you using Mozilla'S fork of TensorFlow?

**Comment by reuben** [comment]
Is your TensorFlow checkout reachable at ../../tensorflow? If not, set the TFDIR environment variable to the appropriate path so that the linker can find the libraries you built.

**Comment by 19578** [comment]
@kdavis-mozilla i dont understand, i dont think i am, can you elaborate a little more... ?

@reuben in the instructions it says 

> By default, the Makefile will assume there is a TensorFlow checkout in a directory above the DeepSpeech checkout. If that is not the case, set the environment variable TFDIR to point to the right directory.

but even with it i get the same error.

> root@Alienware:~/tensorflow/DeepSpeech-master/native_client# make
g++ -o deepspeech `pkg-config --cflags sox`  client.cc `pkg-config --libs sox` -Wl,-rpath,. -L../../tensorflow/bazel-bin/tensorflow -L../../tensorflow/bazel-bin/native_client  -ldeepspeech -ldeepspeech_utils -ltensorflow_cc 
/usr/bin/ld: cannot find -ldeepspeech
/usr/bin/ld: cannot find -ldeepspeech_utils
/usr/bin/ld: cannot find -ltensorflow_cc
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1


im sorry but i am very new to tensorflow

**Comment by kdavis-mozilla** [comment]
@19578 We maintain a TensorFlow fork as we've created a custom C++ op and TensorFlow does not guarantee ABI/API compatibility across versions.

Installing our TensorFlow fork is described here[[1](https://github.com/mozilla/DeepSpeech/issues/912#issuecomment-339971714)]

**Comment by lissyx** [comment]
@19578 Your call to `make` is incomplete, please check in the README. You need to give the path to your Tensorflow checkout as `TFDIR` variable, it seems that it is not in `../../tensorflow/`.

**Comment by lissyx** [comment]
@19578 I'm closing this, since we now have r1.4-based binaries out of TaskCluster. Feel free to re-open if that does not fix your case, but as much as we could verify it should now work properly to train using upstream TensorFlow 1.4.0 and out decoder library :)

**Comment by susanootux** [comment]
I am finding the same issue, can you please re-open?

**Comment by lissyx** [comment]
@susanootux please read the thread, and document what you do exactly
