### ISSUE TITLE
Checkpoint cleaning

### ISSUE THREAD

**Issue by dcam0050** [mozilla/DeepSpeech#951]
Will cleaning all but the latest checkpoint data affect training of the model? Also I have some files called `events.out.tfevents.<number>.hostname` are those important to keep too? Thanks

**Comment by reuben** [comment]
It shouldn't affect training, but I don't know if anyone has tried it before. Don't forget to update the `checkpoint` file to remove the pointers to the removed files.

Do a backup before and let us know how it went :)

**Comment by saikishor** [comment]
Yes you need to clear the `checkpoint` file, that's enough. Tensorflow checks for the new checkpoint data file only from this file. So, just cleaning this file will do the work.
