### ISSUE TITLE
Acoustic Outputs only?

### ISSUE THREAD

**Issue by sayon794** [mozilla/DeepSpeech#964]
Is it possible to get only the output of the acoustic model? Skipping the LM and all that? I'm training on a custom language and don't have an LM yet. Saw an issue that had the same question previously but the code has changed a lot since then.

**Comment by lissyx** [comment]
Using the language model is optional, as you can see in this example:
 - https://github.com/mozilla/DeepSpeech/blob/1c381903bb62a2aa1b49e8562950f4f50405d721/native_client/client.cc#L79-L84 (C++)
 - https://github.com/mozilla/DeepSpeech/blob/1c381903bb62a2aa1b49e8562950f4f50405d721/native_client/client.py#L52-L54 (Python)
 - https://github.com/mozilla/DeepSpeech/blob/1c381903bb62a2aa1b49e8562950f4f50405d721/native_client/client.js#L49-L52 (NodeJS)

**Comment by sayon794** [comment]
But what if I wanted to skip the LM while training? DeepSpeech.py seems to expect a 'data/lm/lm.binary' by default.
Also I'm facing a separate issue right now. I can't get Mozilla's fork of Tensorflow running because trying to import it gets me this:
`>>> import tensorflow
2017-11-18 18:19:25.409425: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.`

**Comment by sayon794** [comment]
The issue with tensorflow doesn't seem to occur on the computer I'm going to be primarily working on, only on my personal device. So that's not a major issue for me right now. However, due to lack of an LM, I can't train a model, I was wondering if there was any way to bypass this.

**Comment by reuben** [comment]
The LM is only used when creating error rate reports on validation and test epochs. You can replace the decode_with_lm call with a call to the builtin ctc_beam_search_decoder to disable using the LM.

**Comment by lissyx** [comment]
@sayon794 Regarding your tensorflow problem, you seem to be trying to run that on a system that does not have `AVX2` support, which we built with. Your best solution for now would be to rebuild yourself with the proper flags for your target system, from our tensorflow repo.

**Comment by sayon794** [comment]
Replacing the call worked, thanks a lot guys!
