### ISSUE TITLE
Build and package our mozilla/tensorflow for Python 3

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#970]
Currently we only have Python 2 builds of our fork.

**Comment by cathalgarvey** [comment]
Is this one of the main reasons this tool/library is Python 2 only right now? Because that's a pretty big issue IMO. :)

**Comment by reuben** [comment]
It's the only reason, or at least it should be :)

**Comment by lissyx** [comment]
2.7, 3.4, 3.5 and 3.6 ?

**Comment by reuben** [comment]
Ideally, yes :)

**Comment by lissyx** [comment]
Would be easier to do after we merge https://github.com/mozilla/DeepSpeech/issues/959
