### ISSUE TITLE
Feature Request: REST/Streaming Service with GCP-Compatible API

### ISSUE THREAD

**Issue by cathalgarvey** [mozilla/DeepSpeech#977]
Hey folks, I'm really delighted to see the Pretrained Models officially up and in the Readme! I've started experimenting with this, looking forward to having some fun.

Something I'd love to try with DeepSpeech is to build a backend for Mycroft - Mycroft's STT API is pretty basic so this shouldn't be too hard. But, for making Moz DeepSpeech maximally useful, it'd be cool to have a REST API that's compatible with Google's, so using DeepSpeech with existing code would only require changing a URI (or hacking a DNS record, at worst?).

The Google REST API is pretty straightforward: https://cloud.google.com/speech/docs/apis

Might even complete this myself after some experimentation, we'll see if I have time and bandwidth. :)

**Comment by MainRo** [comment]
I started a project to host deepspeech as a service, see #847. It is only for testing purposes for now but making it google compatible should be easy. I may also expose the nuance API in it.

**Comment by sci472bmt** [comment]
I wrote django based web app that can record sound from browser and return its transcription. Please check #847.

**Comment by kdavis-mozilla** [comment]
@cathalgarvey As there is a third part project doing this[[1](https://github.com/MainRo/deepspeech-server)], I am going to close this issue.
