### ISSUE TITLE
Create Common Voice importer

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#982]
Create importer for the Common Voice data set

**Comment by nmstoker** [comment]
FYI: I managed to create a basic process to bring in files I'd produced with a locally installed version of Common Voice (is not the "official" Mozilla files). Details are here in case it's of use: https://discourse.mozilla.org/t/using-common-voice-data-with-deepspeech/19823

**Comment by aleixrvr** [comment]
I've had troubles executing bin/import_cv.py

Successfully downloaded cv_corpus_v1.tar.gz 290 bytes.
Extracting "/media/ramon/f5cc7ae9-0207-4f3e-8133-bce1998882f6/PycharmProjects/data/common_voice/cv_corpus_v1.tar.gz"...
Traceback (most recent call last):
  File "bin/import_cv.py", line 112, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_cv.py", line 36, in _download_and_preprocess_data
    _maybe_extract(data_dir, CV_DIR, local_file)
  File "bin/import_cv.py", line 44, in _maybe_extract
    with tarfile.open(archive) as tar:
  File "/home/ramon/.pyenv/versions/2.7.13/lib/python2.7/tarfile.py", line 1680, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

The error pops immediately, so I think it is not succesfully downloaded...

**Comment by tilmankamp** [comment]
@aleixrvr : This will get fixed by https://github.com/mozilla/DeepSpeech/pull/1020 .
In the meantime you can directly download the corpus archive to the target directory (you'll find the link in the importer source code).

**Comment by kdavis-mozilla** [comment]
Tilman's finished a first version of this, see commit a78dd0d
