### ISSUE TITLE
Add node packages by hand + update docs

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#986]
The could also slip to the hard release if needed

**Comment by reuben** [comment]
https://www.npmjs.com/package/deepspeech

For the GPU version, npm requires needs the package name changed in package.json. I'm working on the build system changes required for it.

**Comment by reuben** [comment]
https://www.npmjs.com/package/deepspeech-gpu

Docs updated in #1014.
